### ISSUE TITLE
CarSettings_RedLineDisplayedPercent  ignores per gear redline

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1005]
**Describe the bug**
Hi,
I just noticed DataCorePlugin.GameData.CarSettings_RedLineDisplayedPercent doesn't use the per gear redline settings.
We can work around this thanks to DataCorePlugin.GameData.CarSettings_CurrentGearRedLineRPM but I assume this is a small oversight.

**Simhub version**
7.4.16

Bonne fin de soirée.

**Comment by Romainrob** [comment]
Hi,
This looks good on 7.4.1b1
Thank you for the fix!

**Comment by SHWotever** [comment]
Perfect ! Thnaks
