### ISSUE TITLE
[Feature Request] Add estimated iRacing wheel slips as properties

### ISSUE THREAD

**Issue by RogerFrigola** [SHWotever/SimHub#1006]
iRacing does not output wheel slips in its telemetry. However, wheel slips seem to be estimated in SimHub in order to drive the bass shakers. It would be very nice to have those slip estimates available in the property list.

**Comment by SHWotever** [comment]
Hi ! Unfortunately it's not a simple value, they neeed all the shakeit processing to be generated.

As a workaround you can redirect the shake it result to a property : 
![image](https://user-images.githubusercontent.com/2207331/151651638-de4e01b7-4124-4675-98a6-c67c3a88a25e.png)
