### ISSUE TITLE
Simhub doesn't connect to Assetto Corsa when in Replay

### ISSUE THREAD

**Issue by CloudMracek** [SHWotever/SimHub#1007]
**Describe the bug**
Simhub doesn't detect Assetto Corsa when it's running a replay.

**Simhub version**
7.4.16

**To Reproduce**
1. Run an AC replay
2. Look into Simhub
3. Simhub is "Waiting for data"

**Expected behavior**
Simhub pulls data from the game as usual

**Log files**
[2022-01-25 23:17:45,879] INFO - AC shared memory connected
Simhub suggests that it sees the game but there might be a if replay -> don't care statement.

**Additional context**
I'm trying to make race highlights using a Replay and I want to add TV graphics using SimHub (Position, timing etc.)

**Comment by SHWotever** [comment]
Hi ! I'm afraid this is intentional, simhub ignores replays when it's possible to avoid corrupting all the data being tracked (lap history etc, statistics, lap records...)

**Comment by CloudMracek** [comment]
How likely is a "safe mode" implementation for this issue?
Like "Don't store anything from this session" mode.
Do you think a viable alternative is to record the race using the built-in record feature with the same fps as the final recording?
