### ISSUE TITLE
Overlay visibility toggle

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1008]
**Describe the bug**
Hi,
On the latest beta version, the overlay visibility toggle control only works to hide the overlay.
Pressing the button again doesn't make the overlay visible.

**Simhub version**
7.4.17b1

**To Reproduce**
1. Open a game or replay
2. Open an overlay layout
3. Press the overlay visibility toggle button to hide it
4. Press it again, and nothing happens.

**Log files**
Nothing special in the log:
[SimHub.log OVERLAY VISIBILITY.Log](https://github.com/SHWotever/SimHub/files/7942912/SimHub.log.OVERLAY.VISIBILITY.Log)

**Additional context**
I can tell the formulas in the overlay are still running.
The restart overlay button brings it back to visibility as expected

Bonne fin de journée

**Comment by SHWotever** [comment]
Hello ! Thanks !  I will check that !

**Comment by SHWotever** [comment]
Hello ! I tested it in various conditions unfortunately i could not reproduce it, is there anything special I should take into account to try to reproduce it ?

**Comment by Romainrob** [comment]
Hi!
I took a closer look and noticed the controls were mapped with the press type "Pressed".
Changing the press type to "ShortPress" type solved this.
On a nitpicky side note, the press types could use a larger text box ;) Some of them don"t fit.
Bon week-end!

**Comment by SHWotever** [comment]
Amazing ! That was it indeed ! Pressed and released were not behaving correctly with actions having dedicated "during" capability (for instance for overlays it hides as long as the button is pressed)

**Comment by Romainrob** [comment]
I see. Good catch!
I can't remember why I changed the press type on this control. Probably by mistake lol.
At least it helped finding a bug :D
And this got me thinking about the long and short press options, and how I could some buttons twice...
I'm off to remap everything.

**Comment by SHWotever** [comment]
:D that was the exact goal :D, reusing twice a single input for rarely used features is pretty useful :D
