### ISSUE TITLE
[Feature request] add go to first screen action to GraphicalDashPlugin

### ISSUE THREAD

**Issue by ybmods** [SHWotever/SimHub#1010]
**Is your feature request related to a problem? Please describe.**
When designing a dashboard in Dash Studio, I would like the ability to have a Home button on the dashboard that goes back to the first dashboard screen.

**Describe the solution you'd like**
The `GraphicalDashPlugin` already has actions `NextScreen` and `PreviousScreen` and the proposal is to add a `FirstScreen` (or `GoToFirstScreen`) similar named action that could be selected for an on-screen button in Dash Studio. It would return the user to the first screen of the same type, e.g. the first `InGameScreen` according to the list of dashboard screens.

**Describe alternatives you've considered**
I took a look at the two sample plugins provided in the SDK and I was able to make my own Action that could trigger the Action of the `GraphicalDashPlugin`:
```
pluginManager.TriggerAction("GraphicalDashPlugin.NextScreen");
```
But there is no existing action in the `GraphicalDashPlugin` that would help go to the first screen. I also found a class `DisplayManager<T>` that has a method `GoToFirstDisplay()`, but I could not figure out how to reach that from the Action delegate in the plugin. The Action delegate only has access to the `PluginManager` and I could not see how to get a reference to the `DisplayManager`. 

**Additional context**
The context is to make dashboards that can emulate a touch screen terminal with a rich interactive experience. A home button could be placed in the top right corner for example, to always return the user to the first initial screen.

**Comment by SHWotever** [comment]
Hi ! I've added the action to the latest simhub version :
https://www.simhubdash.com/download-2/

Nicolas

**Comment by ybmods** [comment]
Thank you for your efforts. It works great!
