### ISSUE TITLE
[Feature request] go to screen button action in Dash Studio

### ISSUE THREAD

**Issue by ybmods** [SHWotever/SimHub#1011]
**Is your feature request related to a problem? Please describe.**
When designing a dashboard in Dash Studio, I would like the ability to have a button on the dashboard that goes to a selected dashboard screen. This would allow the design to have buttons such as Page 1, Page 2 etc.

**Describe the solution you'd like**
In Dash Studio in the Action section for a Button, add an option `GoToScreen` with a text input field where the user would enter the name of a screen (e.g. `Screen1`). During operation, when the button is pressed, it would go to that screen. If the screen they entered does not exist or is the wrong type for the context (i.e. button on `InGameScreen` trying to go to `IdleScreen`), it would do nothing.

The screen selection could be a dropdown of existing screen names, or to make it more powerful, a bindable text field.

The solution could also add it as a method to `GraphicalDashPlugin` for use by other plugins. It is not clear if it could also be an Action such as `GraphicalDashPlugin.GoToScreen` as there is no way to pass parameters to Actions.

**Describe alternatives you've considered**
Similar to Issue #1010, I tried to figure out how to do this in a custom plugin. I found the class `DisplayManager<T>` has a method that has a method `GoToDisplay(T screen, [bool enqueue = True])`, but I could not figure out how to reach that from the Action delegate in the plugin. The Action delegate does not have any event source information from which I could infer the screen where the button was pressed and from there, to get to the `DisplayManager`.

I have also considered that instead of making multiple screens, there could be one screen and you could make buttons to toggle the visibility of elements to simulate other screens. A custom plugin would provide variables such as `DemoPlugin.ScreenOneActive` for binding the Visibility of screen elements. A custom action in the plugin such as `DemoPlugin.ToggleScreenOneActive` would then change those variables.

![button_plugin](https://user-images.githubusercontent.com/97799495/151673667-1b85a7ae-aa21-47c7-b652-af44d62ccb89.gif)

This works to emulate going to a screen by toggling visibility, but it is not actually changing screens. It does not scale very well and requires a custom plugin. A native solution in Dash Studio would be much cleaner and take advantage of the screen system already in place.

**Additional context**
The context is to make interactive dashboards such as a touchscreen terminal for a tractor for use in Farming Simulator 22.

Here is a Case IH Pro 1200 display with buttons Run 1, Run 2, Run 3 etc. along the bottom for direct access to individual run pages.
![AFS-Connect-Magnum](https://user-images.githubusercontent.com/97799495/151673692-ea60d615-250f-4d77-9a5d-9a82baf44f0a.png)

There are other manufacturers such as the FendtONE terminal where you tap on a home screen widget and it goes to the page for that particular function. This should also be possible if there was a GoToScreen action by using a large transparent button that covers the widget.

**Comment by SHWotever** [comment]
Hi ! 

I close this as it have been made available a few releases ago.
