### ISSUE TITLE
Dashboard freezing on session change

### ISSUE THREAD

**Issue by andreasdahl1987** [SHWotever/SimHub#1012]
My dash sometimes freezes on session change. Fixed by quitting the dash and opening it fresh. 

Here is the log file. Issue appears at 22:25:30

My dash is heavily dependent on my plugin, which doesnt use the Windows.Controls.Grid namespace as far as I can see? The LED plugin does however, though that is default as in the LED plugin example. 

[SimHubLog8.txt](https://github.com/SHWotever/SimHub/files/7967093/SimHubLog8.txt)

**Comment by SHWotever** [comment]
Hi ! Dashboard rendering heavily relies on grid, it looks like one of the formulas is giving back an infinity as a result which is then spread in wpf (often the result of a division by zero), could you spot a binding which gives such result ?

**Comment by andreasdahl1987** [comment]
I guess Ill just have to start looking😅 Is this a freeze that will resolve if the values used in the calculation changes and the formula suddenly is computable? Or is it dead from the first frame, and will need a restart to work? Also, are you able to tell what kind of binding from this? Text value, visibility, color, coordinates?

**Comment by SHWotever** [comment]
Hi ! Since it affects size of a grid I would think about width/height bindings, maybe a progress bar with a 0 maximum.

At this point It would not recover by itself, I think wpf engine will keep stuck here. I've tried to add a filter inside the formula engine to avoid feeding any binding with infinity values. I need to test it after work, if the source of the issue is here it will fall in the "invalid formula protection logging" and point the guilty formula in the error message

**Comment by andreasdahl1987** [comment]
Ok, this gives me a good idea of where to look. I have a bunch of variables that are reset to default value on session/car/track change. I think there might be some of these properties that I've used to change the position of dash elements, and in those calculations possibly a division by 0.

**Comment by SHWotever** [comment]
Hi ! I've added the "infinity checks" to the latest version, if the issue comes from bindings it should be able to catch it before it does harm and log it

**Comment by andreasdahl1987** [comment]
That is mega! I'll download and do some testing this evening :)

**Comment by andreasdahl1987** [comment]
I can confirm that division by zero was the issue, and that the latest update of SimHub prevented the dash from freezing, and instead posting the issue in the log, allowing me to fix the problem. I found a few zero-divisions before this, but they were all in NCalc, just returning "NaN". The ones causing  the problem was using javascript, having checked the box for javascript in the editor.
[SimHub.log1.txt](https://github.com/SHWotever/SimHub/files/7998973/SimHub.log1.txt)

**Comment by SHWotever** [comment]
Perfect !
