### ISSUE TITLE
Android app does not connect to SimHub

### ISSUE THREAD

**Issue by bkoehle2** [SHWotever/SimHub#1016]
After the 7.4.19 update, my old Samsung Galaxy tablet cannot connect to Simhub using the Android application. It was functioning OK prior to the update with a version downloaded last November. 

The Galaxy tablet is running Android version 4.4.2, yeah old but it was previously functional.

The new experimental "_2" app appears to be OK as it works on my OnePlus 5 and OnePlus 7 Pro. 

Screen shot is attached. 
![Screenshot_2022-02-03-23-43-49](https://user-images.githubusercontent.com/52330634/152475343-4e73ce68-eda1-4fc5-87fb-dd4b79828388.png)

When viewing the logs, the logs do not display any connection attempts from this device.

I tried removing the "new" app and using the apk of the older version I have, and it still brings me to this screen. I also tried downgrading to 7.4.18 and 7.4.17 with no luck, as well as a fresh install of 7.4.17 with again the same results. 

Navigating to the SimHub address via Chrome does appear to be functional in that it loads the available dashboards and I can open and use one.

**Comment by SHWotever** [comment]
Hi !

Thanks For the report ! There was a new bit of code not compatible with such old devices, I replaced it with something which is back compatible : https://www.simhubdash.com/download-2/

**Comment by bkoehle2** [comment]
Thanks! With the new update things appear to be fixed. 

Now if you don't mind me inserting another question in this ticket, is it possible to integrate the swipe down and side swipe features that are present for accessing the menu in web version? I had made another feature request for this but closed it since the app had started malfunctioning, but if its better to open it again and discuss things there I certainly can.
