### ISSUE TITLE
Once I open up simhub, it is trying to configure to american truck simulator, even though I don't have the game. Once I click on Codemasters f1 2021 to change to that game, the applicatiion freezes and stops working

### ISSUE THREAD

**Issue by julianeee** [SHWotever/SimHub#1018]
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Could your join the log files as shown In the issue template ?

**Comment by julianeee** [comment]
sure which log should I link the text file named LapLog or the text file named simhub

**Comment by SHWotever** [comment]
Hi ! You can make a zip with all of them ;)

**Comment by julianeee** [comment]
https://www.mediafire.com/file/opsytuien3kzpft/SimHub_Logs.rar/file
there you go, thanks!

**Comment by SHWotever** [comment]
Thanks I took a look at the log but I couldn't see the game change event, could you join me all the the log files ? (there should be one per simhub execution) or eventually make sure to try to switch the game before collecting the log file so the errors are being traced in the file ?

**Comment by SHWotever** [comment]
Thanks ! It looks like a similar case I encountered yesterday, with a corrupted car setting file, could you try this version ? https://www.simhubdash.com/unofficial/SimHub.7.04.21b1.zip I should be able to safely skip invalid files.

Nicolas

**Comment by julianeee** [comment]
when I try and extractit it says the file is corrupt and i cant extract it and when i try and open it while it is still zipped it says windows cannot open it because the gile is invalid

**Comment by julianeee** [comment]
What should I do ?

**Comment by julianeee** [comment]
nvm i fixed it myself
