### ISSUE TITLE
Custom effect formula block to control output separately from input

### ISSUE THREAD

**Issue by sierses** [SHWotever/SimHub#1022]
**Is your feature request related to a problem?**
Custom code can currently control frequency and volume in two ways: 1) input and output together 2) input only with output controlled by the response curve.
For the first case, if a user wants to change the volume of an effect programmatically, then it will also change the frequency.
For the second case, a user can programmatically set the volume to 0, but otherwise can only control volume with the response curve.
This means that for effects that use frequency range there is effectively no way to use custom code to control only the volume.

**Describe the solution you'd like**
A single custom code / formula block dedicated to controlling output (that appears when Frequencies based on Input is selected) would solve this. This is an advanced option that could completely replace the response curve when activated for a custom effect.

A more complete solution would be to add the option to all effects to select between a normal response curve, an editable response curve, and custom code.

**Comment by sierses** [comment]
There's an easier way to implement this without breaking compatibility for other effects.
Make a new "Custom filter" with a custom code block and then use that to replace the gamma filter in a new "Custom advanced effect".

**Comment by sierses** [comment]
Recently I've been brainstorming a new suspension effect where output volume is controlled by velocity and frequency is controlled by acceleration. Having independent custom code fields for each tire would allow this type of effect to be created.

Here is a mockup of how it might look.
![Advanced Custom Effect](https://user-images.githubusercontent.com/20391356/207264674-35e45afb-25ba-44c4-868d-1a372582675b.png)

I removed frequencies based on output because that works with regular custom effects.

**Comment by SHWotever** [comment]
Hi !
Formulas for custom effects frequencies are now available : https://www.simhubdash.com/download-2/

**Comment by sierses** [comment]
Thank you! This will help a lot to make better effects.

Here's a couple of things I've experienced so far:

The Test button doesn't play the current frequency (understandable because it's a variable, but it would be useful for testing if it played back whatever the current value is)

It works in Corners mode, but not in L/R, F/R, or Mono mode.
I don't remember it being explained anywhere, but based on my testing, L/R uses the largest of the left and right values as outputs, F/R uses the largest of the front and rear values as outputs, and Mono uses the max value of all four formulas. That should work for frequencies too.
