### ISSUE TITLE
VR petit budget pour SimHub

### ISSUE THREAD

**Issue by Ben017** [SHWotever/SimHub#1025]
Bonjour,

Je fait un peu de programmation Arduino est j'ai réalisé un programme qui avec une carte Arduino micro est un module gyroscopique mpu6050 positionné sur mon casque audio détecte les mouvement de ma tête et ainsi ressemble a un VR (sans lunette) ce qui pour ma part ne me rend pas malade.

Le programme doit encore être encore amélioré mais voici un tuto que j'ai fait pour vous montrer à quoi ca ressemble:       https://www.youtube.com/watch?v=6FcuaXEb5gE

Il est reconnu comme une sourie et est utilisable sur tout les jeux qui utilise la sourie en camera libre. Je joue principalement à rFactor 2 et Eurotruck Simulateur 2 et marche très bien car en plus le casque VR comme le HTC vive n'ai pas pris en charge par le jeu par ETS2.

Mon problème c'est qu'a force de tourné le tête je ne reviens pas forcement au centre, sur l'image on voit que quand je tourne a droite je vais a -5 et quand je reviens je vais a 4 (0 étant aucun mouvement)
![moveVR](https://user-images.githubusercontent.com/99882238/154486860-c9a84874-7423-4ade-87b5-36a91ccc484f.png)
Quelqu'un aurait il un idée pour améliorer le retour au centre? Je n'ai pas beaucoup de connaissance donc merci de resté clair et indulgent
Voici le code:

#include <Wire.h>
#include <MPU6050.h>
#include <Mouse.h>

MPU6050 mpu;
int16_t ax, ay, az, gx, gy, gz;
int vx, vy;

void setup() {
  Serial.begin(9600);
  Wire.begin();
  mpu.initialize();
  if (!mpu.testConnection()) {
    while (1);
    }
}

void loop() {
  mpu.getMotion6(&ax, &ay, &az, &gx, &gy, &gz);
  
  //Rotation tete 
    vx = -(gz-2000)/1500;  //Réglage: 1er chiffre = mise a zero(stabilise entre 250 et 350)(- ce decale a gauche)(+ decale a droit) 
                                        // 2eme chiffre = vitesse de rotation (- va plus vite)(+ va moins vite)
                                                                            
      
  //Ochement de tete
  vy = (gy-300)/1800; //Réglage: 1er chiffre = mise a zero(stabilise entre 250 et 350)(- descend)(+ monte) 
                                  // 2eme chiffre = vitesse de rotation (- va plus vite)(+ va moins vite)
                                  
 Serial.print(vx);Serial.print("          ");Serial.print(gz);Serial.print("          ");
 Serial.print(vy);Serial.print("          ");Serial.println(gy);

 Mouse.move(vx, vy);
  
  delay(10);     // Joue sur la souplesse des déplacements mais influt sur la vitesse
                      //(+ plus souple mais plus lent)(- moins souple et plus rapide)
                    
}

**Comment by SHWotever** [comment]
Bonjour,

Ca a l'air très interressant, mais je suis désolé je n'ai pas d'expérience avec ce type de composants,

Peut ètre les forums arduino seraient d'une plus grand aide.

Nicolas
