### ISSUE TITLE
Project Cars 2 UDP ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by mjgornall** [SHWotever/SimHub#1026]
**Describe the bug**
When driving the Ginetta G40 GT5 car in Project Cars 2 on XBOX, dash and bass shaker do not respond. In the SimHub logs it is throwing an error on each UDP packet:

System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
  at System.String.Substring(Int32 startIndex, Int32 length)
  at PCarsSharedMemory.PC2UDP.PCars2UDPMamager.GD_CarModel()

Dash and bass shaker work as expected on other cars, same track, e.g. Renault Clio Cup, Ginetta G55 GT3, Ginetta G40 Junior.

**Simhub version**
7.4.21

**To Reproduce**
1. Start a race in the Ginetta G40 GT5
2. Dash and bass shaker unresponsive
3. UDP is working, Race Dash iOS app works, can see UDP packets being received at PC running SimHub
4. Go to SimHub System Log to see error

**Expected behavior**
Dash to update and bass shakers to react to in game events when driving Ginetta G40 GT5

**Comment by mjgornall** [comment]
Did the 7.4.22 release contain the fix for this? 

I’ve updated but still seeing the same issue and error message in the system log

**Comment by SHWotever** [comment]
Hi ! Yes it was, but unfortunately it was a "blind" fix, the PC version of the game is not affected by this issue and i could not reproduce this issue, I will double check if somehow I left a way for the bug to occur.
Nicolas

**Comment by SHWotever** [comment]
Hi !

I've been able to reproduce it, and even if my fix was appropriate, there was another issue when this case was happening later in the code making my fix useless overall. I've fixed it completely for the next release ;)

**Comment by mjgornall** [comment]
Fixed and confirmed working now, thanks!
