### ISSUE TITLE
Wheel reconnects on white flags

### ISSUE THREAD

**Issue by crazytotz** [SHWotever/SimHub#1027]
**Describe the bug**
When I am on iRacing and I am either doing the last lap of qualifying or it is the last of of the race, aka white flag conditions, my wheel will constantly connect and disconnect over and over again.  It does this to me in officials and when I try it against ai.  It causes my computer to stutter every time it reconnects.

**Simhub version**
7.4.21

**To Reproduce**
When the white flag is waved in iRacing the wheel will randomly connect and disconnect multiple times.

**Expected behavior**
The screen on my wheel will turn on and off, my pc will make the sound like a usb device is being plugged in and unplugged, and my computer will stutter every time it reconnects.

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**
[LapLog.txt](https://github.com/SHWotever/SimHub/files/8103418/LapLog.txt)
[SimHub.log](https://github.com/SHWotever/SimHub/files/8103419/SimHub.log)

**Comment by SHWotever** [comment]
Hi !

White is the most power consuming colour. How your Arduino is plugged ? To avoid power issues make sure to plug it to a good quality usb hub or directly from the motherboard.if somehow your computer usb port can't give enough power you can either lower the matrix brightness which will reduce the power consumption.

**Comment by crazytotz** [comment]
Thanks for this info. My led brightness was set to 100%. I have turned this down and will test out tomorrow.
