### ISSUE TITLE
installation of joystick and directional d-pad

### ISSUE THREAD

**Issue by krystof01bis** [SHWotever/SimHub#1028]
hello sorry to post here I do not know how to do for my request on programming in simhub when creating game pad with leonardo would it be possible to join a joystick recognized as such and a directional d-pad I look in all directions and nothing works last question can we connect the game pad by bluetooth thank you for your understanding while waiting for your answer very cordially

**Comment by SHWotever** [comment]
Hi !

Currently it's not possible, simhub sketch only supports inputs to buttons. You have the full list of supported inputs (inputs section) available here : https://github.com/SHWotever/SimHub/wiki#components-wiring-and-configuration

Concerning bluetooth the arduino does not support it i'm sorry. You should take a look to esp32, it's not supported by simhub but it has bluetooth support.

Best regards,
Nicolas

**Comment by krystof01bis** [comment]
hello thank you for the feedback i will try to look at all this
krystof
 
 
 
> Message du 21/02/22 11:28> De : "Wotever" > A : "SHWotever/SimHub" > Copie à : "krystof01bis" , "Author" > Objet : Re: [SHWotever/SimHub] installation of joystick and directional d-pad (Issue #1028)> >
>
Hi !
Currently it's not possible, simhub sketch only supports inputs to buttons. You have the full list of supported inputs (inputs section) available here : https://github.com/SHWotever/SimHub/wiki#components-wiring-and-configuration
Concerning bluetooth the arduino does not support it i'm sorry. You should take a look to esp32, it's not supported by simhub but it has bluetooth support.
Best regards,> Nicolas
—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: 
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/SHWotever/SimHub/issues/1028#issuecomment-1046718846", "url": "https://github.com/SHWotever/SimHub/issues/1028#issuecomment-1046718846", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
