### ISSUE TITLE
DFRobot 4 & 8 7 Segment LED Display Library

### ISSUE THREAD

**Issue by byteinsight** [SHWotever/SimHub#1033]
I noted looking at the I2C LCD Setup section that the DFRobot library was supported and so filled with confidence purchases a number of other DFRobot 7Segment Displays but it seems that these are not supported.  

Please can you include their library and the ability to assign I2C addresses as required.  Details for the 8Digit are here
[8-Digital LED Segment Display Module SKU%3A DFR0646-G DFR0646-R](https://wiki.dfrobot.com/8-Digital%20LED%20Segment%20Display%20Module%20%20SKU%3A%20DFR0646-G_DFR0646-R#target_5)

I would consider purchasing another set of displays but in the current global market there seems to be poor stock of suitable alternatives.

Thank you.

Chris

**Comment by SHWotever** [comment]
Hi ! I close this suggestion, I did not had any other requests for the same hardware yet.
