### ISSUE TITLE
Vocore 4'' vs 5'' Idle Behaviour power OFF

### ISSUE THREAD

**Issue by damiank388** [SHWotever/SimHub#1036]
**Describe the bug**
4'' VoCore version powers off perfectly ( pitch black), with 5'' version there is still a backlight glow visible 

**Simhub version**
7.4.20

**Comment by SHWotever** [comment]
Hi ! 
Unfortunately it's aa screen limitation,
I double checked and I confirm that the 4" does not totally stops when backlight is set to minimum unlike the other models. I also verified the vocore SDK and it still does not provides a dedicatedd "shutdown" instruction.

Nicolas
