### ISSUE TITLE
Microsoft .Net Framework 4.8 required but upon install error 0x800f081e

### ISSUE THREAD

**Issue by Miro228** [SHWotever/SimHub#1038]
Hi, so I was trying to install Sim Hub and towards the end of the installation I'm greeted with this error message: 

![image](https://user-images.githubusercontent.com/97639741/156732318-489fbf2b-c627-4986-9c55-c6caa34d49e0.png)

So I click yes and follow the prompts to install Microsoft .NET Framework but however after all the files download and it gets to 100% I get this error screen.

![image](https://user-images.githubusercontent.com/97639741/156732511-8c32d3a3-eb27-44af-b38e-b644829f4a9e.png)

If somebody could help that'd be greatly appreciated. 
*Edit attached log file from .NET error screen

[Microsoft NET error log full.txt](https://github.com/SHWotever/SimHub/files/8184524/Microsoft.NET.error.log.full.txt)

**Comment by martinlanza** [comment]
What operating system are you using?

**Comment by Miro228** [comment]
@martinlanza Windows 10

**Comment by SHWotever** [comment]
Hi ! Please make sure to update your windows 10 using windows update, windows 10 had lot of major versions in the last years, and the oldest versions had support dropped by microsoft so the latest .NET versions can't be installed on it. 

The latest major windows 10 versions even have .NET 4.8 preiinstalled, so you don't even need to do it manually.

Nicolas
