### ISSUE TITLE
 (Question) Support for Arduino Nano ATmega168? (for 8x8 LED Matrix)?

### ISSUE THREAD

**Issue by 13raguz** [SHWotever/SimHub#1039]
I´m wanted to have my own iFlag (specially for AC and ACC) and got the hardware I needed, but as I don´t know anything about this kind of things, I bought an Arduino Nano ATmega168 clone without knowing it wasn´t a ATmega328 (the page didn´t specified which one it was). 

Without knowing this, I tried to set up everything to find out it wasn´t working because the microchip is not available in Simhub. 
Is there a way to use this Arduino Nano ATmega168 as I initially wanted?

**Comment by SHWotever** [comment]
Hi !
No i'm sorry atmega358 is the minimum supported, smaller chips like 168 does not have enough memory and storage.
https://github.com/SHWotever/SimHub/wiki/Arduino--Setup#recommended-arduinos
Nicolas
