### ISSUE TITLE
Binding Editor will sometimes not open

### ISSUE THREAD

**Issue by BigAl66** [SHWotever/SimHub#1040]
**Describe the bug**
After exiting a game, or while a game is active in the background the binding editor in Dash Studio will not open anymore. The editor will open but is not visible. Hovering the mouse over the area where the editor should be change the mouse-cursor to a beam (for text editing). Pressing escape will exit the invisible dialog and the Dash Studio can be used except the binding editor... 

**Simhub version**
7.4.20

**To Reproduce**
1. Start any game wile SimHub is running
2. Exit the game (or just change to SimHub while the game is running)
3. Open the DashStudio
4. Try to edit any binding value

**Expected behavior**
The binding editor should work.

**Screenshots**
---

**Log files**
Nothing is shown in the log that has to do with the DashStudio

**Additional context**
---

Update: The current version (7.4.22) have the same problem. I seems even worse...

**Comment by SHWotever** [comment]
Hi I close this issue, as it was related to the old dashboard editor.
