### ISSUE TITLE
Assetto Corsa (AC) only triggers backdriving wheel slip, not forward?

### ISSUE THREAD

**Issue by blacky75** [SHWotever/SimHub#1042]
**Describe the bug**
Throttle pedal/rumble motor: Seems not getting any forward driving wheel-spin input, only on "R", backwards driving with wheel spin works... not forward

**Simhub version**
7.4.22

**To Reproduce**
open SimHub and go to ShakeIt Motors - Effects Profile - WHEELS SLIP (expand this last one to see the detailed options)

**Expected behavior**
On the LIVE EFFECTS data bars, per wheel, you see the data incoming. Mode is set to CORNERS.... when making a 'burn' in 1rst gear, saying going forward with slippy wheels, no data shows up in the LIVE EFFECTS on the right/left REAR.... do I put the "R" gear, spinning backwards, the data shows up in right/left REAR wheels, and the rumble motors, rumble.... I have the feeling that the AC data is not catched as it should be, I don't know.... but I can't get the motors working spinning forward, only backwards. (no forward spin data showing up, but backwards)
[Logs.zip](https://github.com/SHWotever/SimHub/files/8200201/Logs.zip)

TIA
Cheers

**Comment by SHWotever** [comment]
Hi ! I double checked everything wen't fine, i would think about a calibration issue, could you try to reset calibration using the following button ?
![image](https://user-images.githubusercontent.com/2207331/158420649-b008fa2f-5b2d-4a95-ab26-64c109c87233.png)

**Comment by blacky75** [comment]
hi! will try it coming week end, many thanks for your help, I'll keep it posted ;) Have a nice week! 
BR
