### ISSUE TITLE
Problème arduino

### ISSUE THREAD

**Issue by IdioticDuck17** [SHWotever/SimHub#1043]
Bonjour je vous contact car je rencontre un problème au moment de l’émulation des touches.
Après avoir compilé et respecter les branchements la carte arduino nano, je constate qu’il n’y a un seul côté qui fonctionne correctement. De la pin D13 à A7, les micro switch sur D13 et A0 ne son pas détecté pendant l’affectation des touche. Même en branchant un bouton poussoir à la place cela ne fonctionne pas.
Ensuite, l’arduino détecte en permanence une action sur lés encodeur situé aux pin A1 à A6 même si ils ne sont pas  brancher. La pin GND fonctionne des deux côté, J’ai essayé plusieurs carte (arduino nano, arduino nano every et AZDelivery) mais le problème persiste.
merci de me contacter afin de régler ce problème.

**Comment by SHWotever** [comment]
Bonjour ! 

Pouvez vous joindre le profil du "sketch" ainsi qu'une photo du cablage ? afin que je puisse regarder ? 
![image](https://user-images.githubusercontent.com/2207331/157819169-033e85c8-2c3d-4e4d-8f67-48ab1d84bdd2.png)


Estes vous sur de bien utiliser simhub ? La nano every n'est pas supportée, je suis surpris que vous la citiez dans la liste de ce que vous avez testé.

Concernant les encodeurs c'est parfaitement normal, il ne faut pas les activer si ils ne sont pas branchés, cela fausse les lectures de valeurs. 

Nicolas.
