### ISSUE TITLE
Overlay size gets reset at reopen

### ISSUE THREAD

**Issue by St54Kevin** [SHWotever/SimHub#1045]
**Describe the bug**
When resizing an overlay widget, reopening the overlay resets it to its default size. No matter the overlay origin.

**Simhub version**
7.4.22

**To Reproduce**
1. Open an overlay
2. Edit it
3. Resize a widget
4. Save the overlay
5. Close it
6. Reopen it
7. Widget size gets reset

**Expected behavior**
size should save

**Screenshots**

**Log files**

**Additional context**

**Comment by SHWotever** [comment]
Hi !

Thanks for the feedback !
I've fixed it for the next version !

Nicolas
