### ISSUE TITLE
4 Channel Bass-Shaker with Led Intensity Flashing light ring arround it [Feature request]

### ISSUE THREAD

**Issue by Doprintityourself** [SHWotever/SimHub#1048]
Hello,
I have setup my rig with 4 channel Bass-Shaker System from 3DP-Evolution.
So each corner a Bass-Shaker is mounted.

I did not find any solution yet that is why I am asking here:

 I would like to build an (RGB) led ring around any of the Bass-Shaker 
and let them  light up by the intensity of it being used.
So the more a specific Bass-Shaker is vibrating, or getting audio information's the more and brighter the led shine.

Could you imagine that such kind of feature would be possible to be managed on top of the Bass-Shaker being used through 
the telemetry data of the Racing Sims?

Would be awesome to hear that you are interested to implement or if already exist 
where can I find the solution.

Thank you very much in advance

*

**Comment by SHWotever** [comment]
Hi ! Unfortunately after all those months this request remained completely unique. I close it for readability purpose even if the the feature would be interesting.
