### ISSUE TITLE
[Feature request] 7 Segment Displays without controller chip

### ISSUE THREAD

**Issue by ogaskell** [SHWotever/SimHub#1051]
**Is your feature request related to a problem? Please describe.**
I have an arduino Mega2560, and would like to use a series of 7 segment displays with it. It has plenty of pins, so it is frustating that I cannot directly connect 7 segments to the Arduino without a controller chip.

**Describe the solution you'd like**
I would like an option in the setup for directly connect 7 segments, even if just for the Mega2560 (since it has much more pins than the other arduinos)

**Describe alternatives you've considered**
I've considered buying controller chips but this makes my project more complicated, wastes useful pins on the Mega2560 and means I need to use a breadboard or similar rather than just connecting the displays (they're 5.4 - 6.0V displays so I don't need resistors)

**Comment by SHWotever** [comment]
Hi ! 7 segments  can vbe rather complex to wire, common anode, common cathode, resistors, it involves lot of wiring and lot of possibilties and mistakes. As is it's not something I want to add to simhub as it can be troublesome. I prefer to stick to ready to use modules with 3 or 3 wires which are easy to setup. 

As a workaround it's possible to "hack' a current supported display and make it do whatever you want, for the purpose i would take the TM1637 which is a simple 8 digits display : C:\Program Files (x86)\SimHub\_Addons\Arduino\DisplayClientV2\SHTM1637.h
