### ISSUE TITLE
lag in 21/9

### ISSUE THREAD

**Issue by Teklahaine** [SHWotever/SimHub#1052]
hello since I acquired a 21/9 screen simhub lag. I use it for rfactor2. I would like to find a solution! thank you.

**Comment by Teklahaine** [comment]
up!

**Comment by SHWotever** [comment]
Hi ! In theory aspect ratio should not have any influence. Could you check the load of the GPU if it's not full ? Task manager now allows to watch it. Usually enabling v-sync allows to restrain the game from consuming everything.
Another clue could be gsync. In Nvidia settings if gsync is enabled for desktop applications. It will interfere with the wpf technology used in simhub.

Could you also join the simhub log files ? Without more details it's hard to give some pertinent answers.

Nicolas

**Comment by Teklahaine** [comment]
hi SHWotever ! thank you for your interest.
As for the gpu utilization rate, it is not 100%
here radeon rx 6600 8go.
I already use v-synch and freesynch is enabled too.
What is strange is that the significant lags are not transcribed in my fps counter integrated into the amd radeon software.
If I switch simhub in my second screen everything works perfectly but this solution does not really interest me.

my pc is as follows:
mb: msi b450 gaming plus max
cpu: r5 2600
32gb (4*8) ddr4 3200mhz cl16
amd radeon, rx 6600 8gb
lg 29 inch screen 2560*1080 75hz

I am French so I use google translation so forgive any language problems.
thank you

**Comment by Teklahaine** [comment]
indeed in the simhub log there are many problems indicated.

the last for example:

Expression (JS) var colour = $prop('GarySwallowDataPlugin.Generic.CarClass4Colour'); <br>var name = $prop('GarySwallowDataPlugin.Generic.CarClass4');

if (colour == ''){return 'transparent'}
else if (name == 'LMP2'){return '#FF0091FF'}<br>else if (name == 'LMP3'){return '#FFC000FF'}
else if (name == 'LMGTE PRO'){return '#FF00EC00'}
else if (name == 'LMGTE AM'){return '#FFFFA700'}
else if (name == 'LMGT PRO'){return '#FF00EC00'}
else if (name == 'LMGT AM'){return '#FFFFA700'}
else if (name == 'LMP1'){return '#FFC10000'}
else if (name.search('LMH')!=-1){return '#FFC10000'}
else if (name.search('GT3')!=-1){return '#FF00DC32'}
else return colour has generated an error (TypeError: name is null)and wont be run again for 30s

**Comment by SHWotever** [comment]
hi I close this, I've published a the performance guide covering most of the cases : https://github.com/SHWotever/SimHub/wiki/DashStudio-performance
