### ISSUE TITLE
[Feature request] ACC New cars Brake Bias Offset

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1054]
Hi,
ACC just released 5 new cars as DLC.
I've added and tested BB csv files for these.
I included the missing original Super Trofeo car.
[LookupTables.zip](https://github.com/SHWotever/SimHub/files/8350093/LookupTables.zip)
Bonne journée!

**Comment by SHWotever** [comment]
Hi ! Thnaks a lot, I've added them to the next release !
