### ISSUE TITLE
[Feature request] Richard Burns Rally. Enable SimHub data already during "RaceIntro" phase (camera spinning around a car)

### ISSUE THREAD

**Issue by mika-n** [SHWotever/SimHub#1055]
Richard Burns Rally (RBR) has a logic that when a race starts it shows a short "race/car introduction" for about 10 secs before the actual countdown begins. During this "raceIntro" a camera is spinning around the car.

**Description of SH limitation in RBR:**
There is one limitation in SimHub-RBR data integration. SH overlays/dashboards start to show the correct car and stage data (car name, stage name etc) only after the actual countdown has begun and not during this "spinning camera" raceIntro phase. 

Several people in www.RallySimFans.hu discord discussion groups have asked/suggested that it would be good to see car and stage details in SH dashboards already during this raceIntro phase because it would give few extra seconds to prepare for the stage (can see personal best time in SH dash, drivers can start to dig out their "live" pacenote for the stage if they drive with a live co-driver friend etc).

RSF rbr mod has also "3-2-1 countdown paused" mode where the actual countdown doesn't begin until a driver pulls a handbrake to at least 30% level (the countdown doesn't surprise a driver if she/he looked at Twitter messages while the stage was loading). Especially with this 3-2-1 countdown paused feature it would be good to see car and stage details in SH dashboard.

**Suggested solution in SH rbr integration:**

SH rbr integration has IsInRaceState logic where it enables the SH dashboard and RBR data integration only under certain game states. It would be a simple solution to this issue by adding RaceIntro gameStatus in the IsInRaceState checks.
`stateId == GameStatus.Race || stateId == GameStatus.Replay || stateId == GameStatus.EndOfRaceMenu || stateId == GameStatus.PauseMenu || stateId == GameStatus.RaceIntro`

Here is a picture illustrating that this RaceIntro status would work great in RBR and by that time RBR has already loaded the stage and car, so the information is correct (ie. no longer data from the previous stage and car).

![simhub_ShowCarAndTrackDetailsAlreadyDuringRaceIntro](https://user-images.githubusercontent.com/35538525/160391139-588acc5d-521d-442b-bcde-f9dab45b1d48.png)

Would be great to have this improvement in the upcoming SH 8.x releases. Thank you for the work you do with SH.

**Comment by mika-n** [comment]
@SHWotever have you had time to evaluate this proposal about adding the gameState.RaceIntro as an active IsInRaceState mode in RBR reader in order to see car and stage details on SimHub dash a bit earlier when a stage starts?

**Comment by mika-n** [comment]
@SHWotever Hi. Sorry to ping this post again, but have you had time to evaluate the suggestion mentioned in the opening post? (ie. RBR and enabling SimHub to show data already during RBR gameStatus.RaceIntro (gameStatus 0x0A)? This would be one additional status check in IsInRaceState check. Thx.

**Comment by SHWotever** [comment]
Hi ! I finally took the time to look at it. I had to cheat as the fact that race intro was not included was linked to UDP telemetry not being active at this time neither, I'm using some fake empty telemetry at this time.

I also looked to add some extra data directly from memory. I found the independent wheel speed which is extremely valuable for spin/spin/lock detection. But if you have some other pointers to share i'm interested.

**Comment by mika-n** [comment]
Hi. Excellent news. Thank you for taking time to look at the "into sequency" RBR game state.
Curious about what is "independent wheel speed"? Speed of each of the 4 wheels?

Have you seen this file in my github repository? This has lots of RBR internals (many of those already used in SimHub, but lots of other details not used in Simhub. Well, most of those are probably not that interesting for SimHub purposes anyway).
https://github.com/mika-n/NGPCarMenu/blob/master/src/RBRAPI.h

**Comment by SHWotever** [comment]
Yes indeed, wheel rotation speed (overall simply RPS x tyre circumference). It was something not available in NGP telemetry, and having that data helps a lot to build effects.

I took a look to your def files, I agree that was not the kind of pointers I was looking for. I'm thinking more about the physics :  slip, smoke , damages, HUD indicators (engine etc ..)
When looking for the wheels speed pointer I noticed that it was referenced by the NGP plugin which makes sense, and I was wondering if there were some other "physical" interesting values around which I didn't hunt for yet without taking days and days learning cheatengine :D (even if it's an interesting exercice, it's really time consuming :D)

**Comment by mika-n** [comment]
@SHWotever a word of warning. Please don't dig in too deep in NGP physics engine or publish anything in public about NGP physics implementation offsets and details. WorkerBee actively develops NGP and we all should leave NGP offsets, pointers and code logic as "no-go-zone". If something specific from NGP core (ie. not general RBR things) would be useful then it may be better idea to discuss with WorkerBee in Discord if telemetry or some API interface could provide the data in a controlled manner.

**Comment by SHWotever** [comment]
No problems, i'm mostly interested about "native" RBR features. No matter the game I primarily focus on vanilla versions. for instance for the wheel speed I noticed the NGP plugin was pointing to it, but I only took a pointer chain available in the vanilla game.

**Comment by greennyreborn** [comment]
> vanilla

Hi Wotever,
I have a question. There are two telemetry options for RBR. If I choose the NGP option, will the new added wheel speed information still be available?

**Comment by SHWotever** [comment]
Yes ;) It's implemented on vanilla game first ;), NGP option adds some extra data over it
