### ISSUE TITLE
TC value doesn't work with 7.4.23. 

### ISSUE THREAD

**Issue by FirstAirbender** [SHWotever/SimHub#1056]
**Describe the bug**
Traction control value doesn't get displayed in any dash. This only started happening after I updated to the latest version. 

**Simhub version**
7.4.23

**To Reproduce**
run any dash and the TC value doesn't show up

**Expected behavior**
TC value should display according with the game

**Comment by SHWotever** [comment]
Hi ! I could not see any issues with it and I did not had any other reports.

I close this issue.
