### ISSUE TITLE
V7.4.23 not starting up, task closing itself after 1-2 seconds

### ISSUE THREAD

**Issue by Kwoliver93** [SHWotever/SimHub#1057]
[SimHub.log](https://github.com/SHWotever/SimHub/files/8397315/SimHub.log)
**Describe the bug**
SimHub won't start. It shows the small title window with logo, etc,  but when the program should open it doesn't doanything and the task closes itself after 1-2 seconds.

**Simhub version**
V7.4.23

**Expected behavior**
SimHub starting up normaly.

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**
I used the V7.04.22b1_Rexing before and it worked fine!

**Comment by Kwoliver93** [comment]
Still not working.
[SimHub.log](https://github.com/SHWotever/SimHub/files/8558820/SimHub.log)

**Comment by SHWotever** [comment]
Hi I close this issue, as i did not had any other reports, it was probably linked to the windows setup.
