### ISSUE TITLE
Assetto Corsa Competizione - DataCorePlugin.GameData.Position - Mise à jour avec retard

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1060]
**Describe the bug**
Je suis 13eme en course et l'attribut DataCorePlugin.GameData.Position est toujours à 14 et il passera finalement à 13 au bout de plusieurs dizaines de secondes. Il se met à jour avec retard
les driverahead_xx_position, eux, sont à la bonne valeur

**Simhub version**
V8.0.0b5

**To Reproduce**
race 
![1](https://user-images.githubusercontent.com/58605557/161555010-deda613f-7e40-48d7-9301-0334d9c9b4aa.jpg)

**Comment by herve4545** [comment]
j'ai remarqué que la mise à jour de la position s'effectue à chaque partiel (S1, S2) ou sur le passage de la ligne de chronométrage

**Comment by SHWotever** [comment]
Hello !

Effectivement la position "officielle" n'est mise à jour par le jeu qu'une fois de temps en temps. les données driverahead_xx_position utilisent les données de leaderboard qui sont quand à elle actualisées plus régulièrement par le jeu.

Malheureusement cette étrange limitation existe depuis AC premier du nom, et ils ne l'on jamais corrigé.

**Comment by herve4545** [comment]
Ok
Merci

**Comment by herve4545** [comment]
Hello
Juste pour info
@swoop sur racingfr a développé un plugin pour ACC et il récupère bien la position en temps réel sans attendre sa réactualisation à chaque partiel
