### ISSUE TITLE
"CORESHADERS.MAS" error when opening rfactor from Simhub

### ISSUE THREAD

**Issue by juanipede** [SHWotever/SimHub#1061]
Hello I am from Argentina.
Does anyone know the solution to this error? It happens to me when I want to enter rfactor from simhub, thanks

![277827934_3201175496792359_1850528810287334212_n](https://user-images.githubusercontent.com/87074050/162188771-e3ac1787-0f49-4ac5-a611-f253c883ed03.jpg)
!

**Comment by SHWotever** [comment]
Hi ! 

What version of the game are you using ? I've been trying with a stock rf1 steam version without troubles.

**Comment by juanipede** [comment]
> Hola !
> 
> ¿Qué versión del juego estás usando? He estado probando con una versión de vapor stock rf1 sin problemas.

Hello ! I am using a pirated version. Would you be so kind to pass me the "coreshaders.mas" file that is inside the rfactor folder? Thank you very much for the help .
( juanipedevilla@gmail.com )

**Comment by SHWotever** [comment]
Hi ! 

I'm sorry pirated games are not supported by simhub : https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#troubleshooting-steps
And I can't and won't share copyrighted materials. This game is still sold so it can't be considered as an abandonware.
