### ISSUE TITLE
ACC new DLC

### ISSUE THREAD

**Issue by RodentYell** [SHWotever/SimHub#1062]
Doesn't matter what dash, offical /custom you use, when you use a dash with the new BMW M2 CS functions like TC/ABS/Brake Bias/Steering Angle and Brake pressure stop working, as soon as you change to a different car, even the other 4 cars out of the new DLC it all starts working again, switch back to the M2 again and thos function stop again.

V7.4.23

Just use a dash which displays some of the functions, check they work then change to the BMW M2 CS.

Should work the same as other cars.

Don't know if the fault is with Simhub or ACC new DLC.

**Comment by SHWotever** [comment]
Hi ! 

I checked the data with the M2 and everything went fine (except brake bias which is unusable out of box and requires a remapping (Romainrob kindly provided the mapping files to be dropped in simhub "lookuptables" directory) : https://github.com/SHWotever/SimHub/issues/1054)

Maybe it was a temporary bub from the game ? Could you try again and provide me the simhub log files if it still happens ?

**Comment by RodentYell** [comment]
Yeh don't know why I said brake bias as that is a fixed setting, as for the rest they still do it its abit odd..
[SimHub.log](https://github.com/SHWotever/SimHub/files/8544413/SimHub.log)

**Comment by SHWotever** [comment]
Thanks for the log I see that you are using EnsiFerrumACCCDS plugin , does the dash comes form the same pack ? Ensy (the author of EnsiFerrumACCCDS) is using his own extracted game data using this plugin to feed his dashes, and it's not possible to fix it on my end, only the author of the plugin can fix it.

**Comment by RodentYell** [comment]
No the dash is a custom dash by me, I do my own, all other dash's I create have no problem what so ever I can swap them around and so on, now if Im in game and swap the vehicle to the M2 it still works 100% so steering angle/brake press and so on still pick up info but if I drop out of the game and come back in tyo ACC having already previously selected the M2 then certain items fail to work, it quite odd it only effects the M2.

**Comment by RodentYell** [comment]
So had a play around and made sure that was no remains of Ensi install from his dash set, and then just put his drivers back in and all is fine now, anyway thanks for the help.

**Comment by SHWotever** [comment]
Perfect ! Thanks for the feedback !
