### ISSUE TITLE
Arduino nano Ledbar Lag/freezing

### ISSUE THREAD

**Issue by KLucky13** [SHWotever/SimHub#1063]
**Describe the bug**
I have a arduino nano connected/soldered to 2 x 8-Led RGB WS2812b (so 16 LEDs in total). Connected to digital pin number 4. It works flawless for most of the time but sometimes out of nowhere the LEDS start to lag/freeze for a second. Sometimes they just shut down for a few seconds and then come back to life. It seems very unpredictable when or why it happens.

I also have multiple vocore dashboards and they do not freeze. When I monitor the FPS counter in SimHub, it never dips (pretty steady at 60 FPS).

I also have a DD1 with formula steering wheel, those leds do not freeze/lag (just extra info)

I have made multiple LED bars (so different cable, LED bars, and Arduino), same issue happens on that one as well, so a hardware problem is very unlikely

**Simhub version**
Latest version

**To Reproduce**
Difficult to reproduce, it seems that the first 10-15 minutes everything works fine, then the problems start. I've seen it happen faster as well. So very inpredictable behaviour.

**Expected behavior**
No lag/freezing on the LEDs

**Screenshots**
I made a video of the problem, found here: https://www.youtube.com/watch?v=ML4UybpfnjQ&ab_channel=KennyLiebert

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
[Logs.zip](https://github.com/SHWotever/SimHub/files/8502363/Logs.zip)

**Additional context**
I only tried this on iRacing since I only use this Sim.

What have I tried:
- Tried different hardware: same problem
- Monitored FPS in SimHub: not the problem 
- Reflashed the Arduino: just as switching hardware, same problem remains

If there is anything I can try to help troubleshooting this issue, please let me know

**Comment by SHWotever** [comment]
Hi !I looked at the logs and it clearly appears that the Arduino is losing data.the automatic retry algorithm is saving the situation and is able to resend the missed packets. 
As is it makes me think about a power issue or a bandwidth issue. I see a single cable going out from the device. Are you using an usb hub to connect both vocore and the Arduino ? I would try to connect the Arduino straight from the computer to see if it helps. If the power is the issue lowering the led brightness can help to diagnose it. I've also seen an Arduino with a RGB matrix which is a big bandwidth+power consumer. Maybe the usb root is running out of bandwidth/power too

**Comment by KLucky13** [comment]
Hello, it is connected with 2 separate cables. The dashboard/vocore uses 1 cable and the arduino with the LEDs is using another one.

At the moment the LED bar is connected to a hub, but during my troubleshooting I also tried connecting it straight to the pc. However, the problem occurred in both cases. Could it still be a bandwidth issue when it is connected straight to the pc?

The LED brightness at the moment is only about 20% (brighter would be annoying anyway).

Anything else I could try to troubleshoot this issue?

Kr,

Kenny

**Comment by SHWotever** [comment]
That eliminates most power issues indeed, the bandwidth can be limited by the usb root still. Most motherboard will use a single usb root shared with 2 to 4 usb ports depending of the layout. 16 LEDs is not "exotic" and that's what most people (including me) uses so I doubt there is something to be found on the sketch or simhub side, and the logs clearly shows that data had trouble get it's way to the Arduino. What kind of serial to usb chip your Arduino uses ? Ch340 is the most common, ftdi was the historical one which can benefit of some packet latency tuning in the drivers.

**Comment by KLucky13** [comment]
It is indeed a CH340.

I have USB ports on the motherboard itself but also have an expansion USB card with 4 extra ports and 2 more on the front of the case. I do have a lot of usb devices on my sim rig (4 vocore screens, wireless headset dongle, rgb matrix, wireless keyboard + usb mouse on the rig, wired keyboard at the desk, etc etc).

But I did disconnect the 3 other vocore screens and usb matrix and the problem still occurred. So I'm not sure what else I could try to find the root of the problem.

I could do some tests with the USB expansion slot and USB port on the front of the case since I can't remember what port I used when I connected it straight to the pc.

If you would have any other things or ideas on what to try next, that would be great!

**Comment by SHWotever** [comment]
Hi ! 

Unfortunately nothing more, the logs are showing the bottleneck somewhere on the serial "layer" (delays in data receiving) ... Since it can recover it's not a full arduino failure like I often see (due to power drop, or bad solders). 
This time it definitely occurs somewere on the middle. Are you using usb3.X ports ? Depending of the USB chip they can sometime cause some hard to figure struggles.

**Comment by KLucky13** [comment]
Hi, I have both 2.0 ports as 3.0 ports on my PC. I did not pay attention when testing different ports. I will do some more testing on different port types and see if I can find out more
