### ISSUE TITLE
Automobilista 2 ERS Mode

### ISSUE THREAD

**Issue by twitchexodium** [SHWotever/SimHub#1064]
Hey Wotever,
not sure if you know that the last Update brings a pretty cool F1 car, but would be nice to have the ERS Mode there :)
Seems like Reiza did implement it in the shared mem... maybe you can have a look at
-Added ERS deployment mode and clutch state information to shared memory

enum ErsDeploymentMode
{
  ERS_DEPLOYMENT_MODE_NONE = 0, // The vehicle does not support deployment modes
	ERS_DEPLOYMENT_MODE_OFF, // Regen only, no deployment
	ERS_DEPLOYMENT_MODE_BUILD, // Heavy emphasis towards regen
	ERS_DEPLOYMENT_MODE_BALANCED, // Deployment map automatically adjusted to try and maintain target SoC
	ERS_DEPLOYMENT_MODE_ATTACK,  // More aggressive deployment, no target SoC
	ERS_DEPLOYMENT_MODE_QUAL, // Maximum deployment, no target Soc
};

  int mErsDeploymentMode;           // [ enum (Type#15)  ErsDeploymentMode ]
  bool mErsAutoModeEnabled;         // true if the deployment mode was selected by auto system. Valid only when mErsDeploymentMode > ERS_DEPLOYMENT_MODE_NONE

**Comment by stssamsts** [comment]
Jeez! I thought it was just me, I think I couldn't do it work but nope, more than patiently waiting for a fix

**Comment by SHWotever** [comment]
Hi ! The update has been released in simhub v8.0.2
