### ISSUE TITLE
Problem about fuel consumption data on ACC

### ISSUE THREAD

**Issue by fralbo** [SHWotever/SimHub#1065]
**Describe the bug**
Read values for `[DataCorePlugin.Computed.Fuel_RemainingLaps]`,  `[DataCorePlugin.Computed.Fuel_LitersPerLap]` and `[DataCorePlugin.Computed.Fuel_LastLapConsumption]` are most of the time, incorrect on ACC1.8.14. Don't know about previous ACC versions.
Sometimes it's good, but I don't really know when.

**Simhub version**
7.4.23

**To Reproduce**
Let's play!

![](https://i.imgur.com/tTiA1WY.png)

**Comment by SHWotever** [comment]
Hi ! Thnaks for the report indeed the game was sending a first frame with a "0" fuel level completely braking the tracking. I've fixed it for the next major version.

**Comment by SHWotever** [comment]
Hi ! I've released the fix with the enw simhub version : https://www.simhubdash.com/download-2/
