### ISSUE TITLE
Leds Dont work properly

### ISSUE THREAD

**Issue by Rodor29** [SHWotever/SimHub#1071]
Leds of rpm that i have configured light Up but then when the simulation starts, the leds light Up correctly but the they got stuck and the leds don't correspond to the simulation value of rpms and i don't know how to fix It.

**Comment by SHWotever** [comment]
Hi ! This looks like a powering or soldering issue , could you make sure to avoid any usb hub, and use a good usb cable , and double check the solder points are good and sturdy ? If somehow this does not help do not hesitate to reduce brightness.
