### ISSUE TITLE
[Feature request] Last error as property

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1072]
Hi,
Would it please be possible to have the last error that popped in the log as a property?
And/or and error counter property?
I like having an alert when an error occurs.
For now I use some scripts to copy and read the log file at regular intervals, trigger alerts and display errors directly on a dash.
It works but is a bit clunky.
Having a dedicated property to monitor will greatly simplify error detection.
Thank you for considering the idea.
Bonne soirée!

**Comment by SHWotever** [comment]
Hi ! I added it, it's already available in the current beta ;) 
![image](https://user-images.githubusercontent.com/2207331/187239907-87cd3e2b-53a9-4315-a75d-bceab3ca9746.png)
