### ISSUE TITLE
T300 w/ Ferrari F1 in Advanced Mode not Detected

### ISSUE THREAD

**Issue by septemberwasp** [SHWotever/SimHub#1073]
**Describe the bug**
Software does not detect wheel and base in this combintation

**Simhub version**
7.4.23

**To Reproduce**
combine t300 base with F1 Ferrari wheel in advanced mode

**Expected behavior**
Software should detect the wheel and base 

**Screenshots**
![f1wheelhardware IDs](https://user-images.githubusercontent.com/105310339/167686631-16eeb5f5-4e3e-4511-a588-9c5cdfa77827.jpg)

![f1wheelreg](https://user-images.githubusercontent.com/105310339/167686672-93db6991-71b8-4f13-aa53-408fed9cd573.jpg)

**Additional context**
I was directed by Romainrob in Discord to the following bug report. I think I'm providing the same information

[https://github.com/SHWotever/SimHub/issues/731](url)

**Comment by SHWotever** [comment]
Hi ! I close this as it has been released with simhub 8.x
