### ISSUE TITLE
[Feature request] Gamepad analog signal to button mapping

### ISSUE THREAD

**Issue by melsy6666** [SHWotever/SimHub#1077]
I built out a Leonardo button box a few months ago using typical momentary switch's, and some toggle switch's and some potentiometers.
iRacing supports analog signal so the pots are working great. 
I built out some logic for the toggles that will press them like a button when they flip, so toggle on really sends a push of a button, as most games don't seem to support always pressed buttons. 

Upon building it out, I noticed that most games do not use the analog signal, and instead use push button for up and down, or a specific button press for each "preset" in the game. ie ABS 1 = Button 23, ABS 2 = Button 24 ....

So i built out the logic and a serial communication WPF application to talk to the Arduino, and change the profile it is in, so the analog signal converts into segmented button presses uses the analog map() function. 

Pretty basic stuff. 

Fast forward to finding Simhub. A fantastic, FANTASTIC, program for making life as a DIY'er a lot easier. 

 I played with the gamepad system a little bit and it does not have a lot of these kind of features to it. 

Is there anyway you could add something like the above mentioned systems into Simhub? 
I would gladly send you my Arduino and C# projects and solutions if you wanted to go thru them. 

Long and short:
Analog signal can be segmented into X subdivisions to allow for a variable button press as the value changes.
    Turn a Potentiometer into X amount of button's. 
Toggle switch logic that will press a button for X interval upon the switch changing state. 
Build profiles that tie into game launch's that can change the subdivisions and the toggle interval.
    ie, iRacing seems to like 110 ms but ACC seems to like 300ms

Thank you.

**Comment by melsy6666** [comment]
I have written this into a Custom Serial device for now.

**Comment by SHWotever** [comment]
Hi ! I close this. Unfortunately such features are extremely sensitive to settings and it would be extremely hard to make it reliable.
