### ISSUE TITLE
Dash Studio Freezes when editing Dashboard with ACC running in background paused

### ISSUE THREAD

**Issue by tfc** [SHWotever/SimHub#1078]
**Describe the bug**

Hi, i am currently setting up a complex dashboard for my needs.
During single player races i sometimes see that something can be enhanced, so i want to pause the game, open dash studio, fix the dash as intended and then continue racing.

This does not work, because dash studio freezes in exactly this scenario. When i stop the game and play on the dashboard while replaying recorded data, it works.

**Simhub version**
7.4.23

**To Reproduce**

1. Start some single player session and just drive
2. Pause the game,
3. switch focus to dash studio
4. try to edit calculated values by clicking on the "f" button of a widget attribute
5. observe there is no reaction. the whole dash studio hangs

**Expected behavior**

It should just work, regardless if ACC is running or not.

**Screenshots**
-

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
[SimHub.log](https://github.com/SHWotever/SimHub/files/8694815/SimHub.log)
[LapLog.txt](https://github.com/SHWotever/SimHub/files/8694816/LapLog.txt)

**Additional context**
-

**Comment by tfc** [comment]
So when the bug happens, it pulls the whole app into a "partly freezed" mode.

Sometimes it does not occur while clicking stuff with the game in background.

**Comment by SHWotever** [comment]
Hi I close this issue, as it was related to the old dashboard editor.
