### ISSUE TITLE
[Feature request] - Auto loading overlay only at first game connection

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1080]
Hi,
I have SimHub starting with Windows, obviously ;)
I find myself toggling the overlay auto load feature on and off quite often as I actually only want it when I'm going for a sim drive.
I think it would make more sense for the overlay to auto load at the first game connection rather than on SimHub start.
Thanks for considering the idea.
Bonne soirée et bon week end.

**Comment by SHWotever** [comment]
Hi ! I close this as it has been added to V8 ;)

**Comment by Romainrob** [comment]
Thanks for the addition!
No more fiddling with the settings needed :)
