### ISSUE TITLE
No RGB-Matrix 'Plugin, Profiles, Function' after Update

### ISSUE THREAD

**Issue by raphabaz** [SHWotever/SimHub#1081]
**Describe the bug**
While Updating from V7.4.8 there was an Error in Update-Log like "File ...json... for Plugin 'RGB-Matrix ...' not found. Reverting to Version-...". Now in the UI the RGB-Matrix-Tab is quite 'empty' - only Header and Base-Controls. Default-Profile also empty.
If I try to import my old Profiles I get an Error (Windows Popup) "An Error occured while saving Profile."

**Simhub version**
7.4.23

**To Reproduce**
1. Go to 'Arduino-Tab'
2. Click on 'RGB Matrix'
3.  Click on 'Profiles Manager'
4. Click on 'Import Profile' Button
5.  Choose File xy.ledsprofile
6. See error

**Expected behavior**
RGB Matrix Tab with my Profiles like in the other Tabs. RGB-Matrix working like before.

**Screenshots**
![RGB-Matrix-TAB](https://user-images.githubusercontent.com/5842241/169859593-19ddad16-3593-4a00-a277-160d2f5af791.PNG)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
[SimHub.log](https://github.com/SHWotever/SimHub/files/8756176/SimHub.log)
[first-after-update-today_SimHub.log](https://github.com/SHWotever/SimHub/files/8756177/first-after-update-today_SimHub.log)
[oldest-today_before-update_SimHub.log](https://github.com/SHWotever/SimHub/files/8756178/oldest-today_before-update_SimHub.log)

**Additional context**
[Any Game - Default Profile_MATRIX__bak05-22.ledsprofile.txt](https://github.com/SHWotever/SimHub/files/8756213/Any.Game.-.Default.Profile_MATRIX__bak05-22.ledsprofile.txt)
[Any Game - MOD-of-DEF_LEDs-1_BAK-5-22.ledsprofile.txt](https://github.com/SHWotever/SimHub/files/8756214/Any.Game.-.MOD-of-DEF_LEDs-1_BAK-5-22.ledsprofile.txt)

Did not work:
Restarting Machine
Restarting SimHub
Granting rights for Profiles-Folder
Importing Profile from other than User-Folders

Thanx, Sacha

**Comment by raphabaz** [comment]
New and simple RGB-Matrix-Profile works now with Test-data-monitor. 
Old user-Profiles for RGB-Matrix not found in SimHub-Install-Directory-Subfolders (where should they be if stored there?). They are only present in User-Doc-SimHub-Folder. 
Import of User-Profiles still produces same Error "An Error occured while saving Profile".

**Comment by SHWotever** [comment]
Hi Thanks for the report, I found that the old profile was containing an opacity pulse effect which was not working and removed in more recent versions, 
I've fixed the profile and converted it to a simple group, i've also added an automatic conversion for the next update so profiles does not get get stuck in error when it was containing this deprecated effect. 
[Any.Game.-.Default.Profile_MATRIX__bak05-22.zip]
(https://github.com/SHWotever/SimHub/files/8784438/Any.Game.-.Default.Profile_MATRIX__bak05-22.zip)

Nicolas

**Comment by raphabaz** [comment]
Hi

Thanks a lot. And thank you for this unbelievable application.

I will purchase a licence next month finally.

I had a question about 'ShakeIt' plugin:

Often I engage the reverse-gear while shifting down fast. Now I made a
vibramotor inside the shifting knob. Which way could I go to make the motor
selectively vibrate only if engaging 2nd (or last) gear? Is it possible by
ncalc/js-script and where was it implemented for ShakeIt?

Should I better write a 'feature request' for that?

Kind  regards,

Sacha

(from Switzerland)

Wotever ***@***.***> schrieb am Fr., 27. Mai 2022, 08:24:

**Comment by SHWotever** [comment]
Hi !

It's not possible on shakeit to do it out of box,  but Indeed a custom effect could do the trick :
if(changed(200, [Gear]) and ([Gear] = '2' or [gear] = [CarSettings_MaxGears]),100,0) 

Unfortunately that's the kind of requests I would avoid in the core of shake it, complexity for end user is already high, and I prefer to avoid adding so specific features.

**Comment by raphabaz** [comment]
Hi
Just wanted to tell you that the formula you sent me does exactly the
trick  :-)

There's a little issue that the 'last gear' isn't known for cars that I did
not drive before and the term is 'true' before every gear was engaged once.
But I workaround that by shifting all gears before race start.

Thanks again! 🙏

If you need help for translation (English to German), writing lists,
designing/filling/editing databases (I worked on this),  I would be the man
and have plenty of time.. Just tell me if/when needed.

Sacha

Sacha H ***@***.***> schrieb am Sa., 28. Mai 2022, 08:57:

**Comment by raphabaz** [comment]
Hi again

I understand.  Thanks a lot.
I'll give it a try but won't spend to much time on it.

Have a nice weekend.

Wotever ***@***.***> schrieb am Sa., 28. Mai 2022, 08:50:
