### ISSUE TITLE
Simhub is slow and unresponsive

### ISSUE THREAD

**Issue by CloudMracek** [SHWotever/SimHub#1082]
**Describe the bug**
SimHub is slow and lagging. It is usable but things just aren't as smooth as I'd like them to be. Whenever I click a button in SimHub it takes a while to respond and the dashboard editor becomes a real pain after an hour of work. I don't know if this is a bug or if it's just poorly optimized but I didn't find any other issues addressing it. What I do find interesting is that I find the completely same behavior on my laptop as well. Even my simple dashboards are slow even with all the settings set to smooth and having the premium SimHub version.

**Simhub version**
V7.4.23

**To Reproduce**
1. Open SimHub
2. Open the dash editor
3. Work in it for a while
4. Becomes really slow and unresponsive

**Expected behavior**
SimHub runs smoothly. Don't have to wait for the software to register button presses. Sometimes the window itself even doesn't respond

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/8763772/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! I see a huge amount of errors coming from a third party plugin (GarySwallow.PluginSdk.GarySwallowDataPlugin.DataUpdate) which will indeed slow down the whole simhub (errors cost a lot) , could you try to disable it in the settings ? It should be enough to recover a normal SimHub "health".

**Comment by CloudMracek** [comment]
Yes, that fixed it right up. Thanks for the quick support!
