### ISSUE TITLE
UPDATE 8.0.0 - MATRIZ RGB WS2812B 8X8

### ISSUE THREAD

**Issue by RogerioPipoli** [SHWotever/SimHub#1090]
With this new update 8.0.0 there was an implementation of the RGB MATRIX. 
With 1 Arduino Nano is it possible to perform 1 matrix WS2812B 8X8 for right Iflag and 1 for left?. Is that possible? 
I'm not getting the second array to work on the same arduino.

**Comment by RogerioPipoli** [comment]
Does anyone have this connection scheme?

**Comment by SHWotever** [comment]
Hi ! It's not possible to run two matrix fromba single Arduino. It has been left unchanged.

But you can run multiple Arduino with each one having its own matrix : https://github.com/SHWotever/SimHub/wiki/Arduino-RGB-Matrix#how-to-manage-separate-matrixes-content
