### ISSUE TITLE
Steady, but slowly climbing CPU usage

### ISSUE THREAD

**Issue by xracer99** [SHWotever/SimHub#1092]
Simhub v.8.0.1

Using this version together with GS plugin v.6.6.0beta while simulataneously running let say Assetto Corsa Competizione v.1.8.14 (newest), the combination makes Simhub's CPU usage climb steady from 8-10% all the way up to whats available to it (total 100%). This is without loading any Overlays. A note, Simhub seems to work fine without installing the GS plugin and using the Simhub supplied overlays. So fault is may not be in Simhub, but in GS plugin or using the combination of the two.

**Comment by SHWotever** [comment]
Hi ! Indeed based ont the symptoms I fear that I can't do anything on the simhub side. Do it hesitate to report it to the Gary swallow plugin discussion so the can fix it.

Nicolas

**Comment by xracer99** [comment]
> Hi ! Indeed based ont the symptoms I fear that I can't do anything on the simhub side. Do it hesitate to report it to the Gary swallow plugin discussion so the can fix it.
> 
> Nicolas

Yes, lets hope it gets fixed. Thanks for the reply :)
