### ISSUE TITLE
Copy/Paste

### ISSUE THREAD

**Issue by RodentYell** [SHWotever/SimHub#1093]
8.0.1

Seem to be unable to copy and paste a item whilst creating a dash, ie if there is something I want to copy and paste into a different postion I can select copy but only by right mouse button, but when tring to paste it doesn't give me a paste option. also to get any option to appear I have to do within a item I have on the dash already not a blank space that is available.. it would be nice still to have the copy/paste option in the menu pull down stll.

**Comment by SHWotever** [comment]
Hi ! I will look in for the missing context menu entries , but currently you have full copy paste capabilities by using the standard ctrl+C, ctrl+V shortcuts. It will work both from the designer area or the tree hierarchy.

**Comment by RodentYell** [comment]
Ah ok wasn't aware of the shortcut keys, but will be nice to have it working back on the right mouse button again..thxs for the reply.
