### ISSUE TITLE
rF2 overlay screen roles not working

### ISSUE THREAD

**Issue by St54Kevin** [SHWotever/SimHub#1095]
**Describe the bug**
![image](https://user-images.githubusercontent.com/448627/173103438-17a7cc2c-44ab-493e-9c9a-51261648902d.png)
This Option does not work in rF2. The screens still show when in garage, or even outside a session

**Simhub version**
v8.0.1

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Could you send the whole dash ? 

Currently the system is intended to always show a screen, if there is no appropriate screen for the current mode (game, idle...) Simhub will take the first one no matter the mode.

**Comment by St54Kevin** [comment]
> Hi ! Could you send the whole dash ?
> 
> Currently the system is intended to always show a screen, if there is no appropriate screen for the current mode (game, idle...) Simhub will take the first one no matter the mode.

Oh i didnt know. I interpreted these options as "only show when". So basically that I could tell a whole overlay to just show in that specific situation. The overlay is my own: [https://www.racedepartment.com/downloads/rf2-simhub-mmo-modern-multiclass-overlay-standings-relative-tires.45898/](url)
