### ISSUE TITLE
Shakelt Bass Shaker Output devices do not refresh

### ISSUE THREAD

**Issue by St54Kevin** [SHWotever/SimHub#1096]
**Describe the bug**
The list of output devices do not refresh with a new device connected.

**Simhub version**
8.0.1

**To Reproduce**
1. Turn off or unplug your bass shaker audio device
2. Start Simhub
3. Plug in or turn on audio device
4. Bass Shakers will not work because Simhub doesnt recorgnize the preferred device

**Expected behavior**
Simhub should recorgnize the new device and activate it if its the device normally used.

**Screenshots**

**Log files**

**Additional context**

**Comment by gaddster** [comment]
This is also happening to me but only seems to have appeared with the new 8.0.3 version.  I have licensed version.

To replicate:

Not have my bass shaker amp connected at startup.
Simhub loads at startup (as admin) and minimized.
Connect usb bass shaker amp but it's not shown as an output device in Simhub.
Close simhub and restart it with the bass shaker amp connected; Simhub now shows the output device as expected

Thanks

**Comment by SHWotever** [comment]
Hi !

the fix has been released with SimHub 8.1.0.

Best regards,
Nicolas
