### ISSUE TITLE
[Feature request] Assetto Corsa Competizione Suspension Damage

### ISSUE THREAD

**Issue by KaiSforza** [SHWotever/SimHub#1100]
**Is your feature request related to a problem? Please describe.**  
The current damage info from ACC only lists the aero/body damage taken, but the suspension damage is unlisted. This should be listed in the properties available for ACC

**Describe the solution you'd like**  
Simply read the memory address where the damage should be.

**Describe alternatives you've considered**
Writing a separate plugin to do the same work would be okay, but it exists in the data already.

**Additional context**
The current [ACC Shared Memory docs][1] is incorrect about the suspension damage not being used in ACC. You can run some tests, but the location where the suspension damage should be actually has information that maps directly onto the suspension damage. See the image below for some proof, though simply reading that bit of the shared memory will get you the data.

![image](https://user-images.githubusercontent.com/1731430/173419973-c6656247-ab56-42ef-90c6-c96b1a585867.png)

[1]: https://www.assettocorsa.net/forum/index.php?threads/acc-shared-memory-documentation.59965/

**Comment by KaiSforza** [comment]
An example of reading it can be found in this commit:

https://github.com/rrennoir/PyAccSharedMemory/commit/a916b0e6378823bbc674502f253e1257bd442a0f

**Comment by SHWotever** [comment]
Hi ! I've added it for the next version ;)
