### ISSUE TITLE
[Feature request] Assetto Corsa Competizione Slip Angles

### ISSUE THREAD

**Issue by KaiSforza** [SHWotever/SimHub#1101]
**Is your feature request related to a problem? Please describe.**  
Add tyre slip angles to ACC

**Describe the solution you'd like**  
Read the physics memory for slip angles, `slipRatio` and `slipAngle`

**Describe alternatives you've considered**  
I've been using the `DataCorePlugin.GameRawData.Physics.WheelSlip0[1..4]` properties, but want some more insight into the raw data.

**Additional context**  
https://www.assettocorsa.net/forum/index.php?threads/acc-shared-memory-documentation.59965/

**Comment by SHWotever** [comment]
Hi ! I've added it as a properties for the next version.

Nicolas
