### ISSUE TITLE
[Feature request] Assetto Corsa Competizione Full Raw Data

### ISSUE THREAD

**Issue by KaiSforza** [SHWotever/SimHub#1103]
## Summary

The current Assetto Corsa Competizione (ACC) `GameRawData` properties don't seem to map onto all of the available exposed items. I know some of them are duplicated by other outputs but having something that maps onto all of the [ACC Shared Memory documentation][1] would be beneficial.

[1]: https://www.assettocorsa.net/forum/index.php?threads/acc-shared-memory-documentation.59965/

Below I have listed the missing options from the shared memory (ex #1101). There are also some items that the docs are incorrect about, those have also been noted (see #1100). Some of them are already available under different names, others are completely unavailable in SimHub, though they are available in the game. Enabling these would let us use everything the game has to offer in ways specific to ACC. 

### Physics
* `float wheelPressure[4]` (duplicated by `DataCorePlugin.GameData.TyrePressure*`)
* `float brakeTemp[4]` (duplicated by `DataCorePlugin.GameData.BrakeTemperature*`)
* `float slipRatio[4]` - #1101 
* `float slipAngle[4]` - #1101 
* `float suspensionDamage[4]` - Docs say it's disabled, but it exists (#1100)

### Graphics
* `int activeCars` - active cars on track
* `float carCoordinates[60][3]` - all of the cars coordinates
* `float carID[60]` - list of all the cars, not sure what the indexing here is.

### Static
* `float AllowTyreBlankets` - Assuming this will just change for the gt4/cup cars

**Comment by SHWotever** [comment]
Hi ! I've added everything possible, 

- Converning activeCars it's names "CarCount", inherited from the AC version of the telemetry (and I can't rename it to avoid breaking existing dashs using it.
- AllowTyreBlankets is named AidAllowTyreBlankets for the same reason.
The two lasts : carCoordinates[60][3]  and carID[60] are kept inaccessible, the data would be too heavy to be used in the scripting engine, and basically they are meaningless without some heavy processing and reconciliation vs the game broadcast api. However it's fully accessible to the plugin SDK. 

Nicolas
