### ISSUE TITLE
J'ai était ban du discord et je voudrais revenir sur le serveur SimHub car mon compte a étais piraté et j'ai réussi a récupérer mon compte

### ISSUE THREAD

**Issue by erkan377** [SHWotever/SimHub#1104]
Bonjour,
Je suis TheFastRace#2515 sur discord j'ai eu un petit soucis avec mon compte il y a quelque semaine, je vient ici pour écrire mon problem car j'ai envoyer un mails et je n'ai pas eu de réponse de votre part.

Voici pourquoi j'ai était ban mon compte a était piraté et j'ai réussi a changer mon mot de passe avant d'avoir plus de soucis, car mon compte a envoyer ce message:

Steam started discord nitro giveaway for 3 month!! 
To claim it, just login with your steam account, and click activate nitro.  Join and start using new features !!
disrcgkhods-gift.cokggjkhgkmkgjk/gkgNitro (j'ai écrit n'importe quoi dans le lien pour pas que vous cliquer sur le lien)

je m'excuse de l'incident et je souhaiterais revenir sur le serveur.

Merci.

**Comment by SHWotever** [comment]
Bonjour,

Pour ce type de type de messages (même si je comprends qu'ils ne sont pas volontaires) il est prévu dans le règlement du discord un bannissement définitif. Nous avons déjà essayé de débannir pour ce même type de causes dans le passé certaines personnes mais ils s'est avéré que ces personnes avaient toujours leur compte "compromis" et ont posté de nouveau ce type de scams. C'est pourquoi je suis normalement extrêmement strict sur ce type d'évènements au risque de contribuer encore plus à la diffusion de ce type d'arnaques.

J'ai exceptionnellement révoqué le bannissement. 

Nicolas
