### ISSUE TITLE
Vertical linear gauge broken in v8 when centered

### ISSUE THREAD

**Issue by KaiSforza** [SHWotever/SimHub#1105]
### Describe the bug
Linear gauges work, all orientations of horizontal gauges work perfectly, and the top and bottom vertical gauges work, but the centered vertical gauge are broken completely. They do have a part that changes, but it's completely in the wrong place and the wrong dimensions are changing.

### Simhub version
v8.0.1

### To Reproduce
1. Create linear gauge
2. Set gauge alignment to centered (should work at this point as a horizontal gauge)
3. Set gauge orientation to vertical
4. Move around the value. It should go from the bottom left corner and clip out of bounds as well.

### Expected behavior
A vertical gauge that expands vertically from the center to the top and bottom borders.

### Screenshots

I tested this with the frame duration and a 60s frame skip just to see things, and it looks like the following two images. The top is in the dash studio, showing that it looks proper compared to the actual running dash in the bottom image.

![image](https://user-images.githubusercontent.com/1731430/174461351-e74b63c3-4d03-4320-b93b-8e5c26b7cad8.png)
![image](https://user-images.githubusercontent.com/1731430/174461364-d9b48c87-0977-4ae3-a7c6-ef64812b85cd.png)

**Comment by SHWotever** [comment]
Hi ! The fix has been released with 8.0.3 version.

Nicolas
