### ISSUE TITLE
Low frame rate even with liscence

### ISSUE THREAD

**Issue by Mathis754** [SHWotever/SimHub#1106]
**Describe the bug**
I bought a liscence not long ago and it fix my framerate but now, overlay and dashboard are lagging like crazy, i get like 2-3 fps when i'm in game and i am using assetto corsa. The lag look like the type of lag when your CPU is at 100% but mine is just at 40% so I wonder what cause this lag because it is not my computer and I have a liscence so everything should be ok.

**Simhub version**
8.0.1

**To Reproduce**
1. Go to 'overlay or dashboard'
2. Click on 'one of the overlay to load it'
3. Start your game
4. The overlay is very low frame rate 

**Expected behavior**
I expect that somebody have already saw this problem and can help me

**Screenshots**
I don't have any screenshot because you cannot see a low frame rate on a photo

**Log files**
https://github.com/SHWotever/SimHub/files/8959421/SimHub.log

**Additional context**
I hope somebody help me because I realy like this software

**Comment by SHWotever** [comment]
Hi ! I see that a third party plugin "Gary swallow plugin" is throwing lot of errors which will indeed slowdown simhub. Could you try to disable it ?
