### ISSUE TITLE
Turing smart screen not detected under dash studio 

### ISSUE THREAD

**Issue by texanman** [SHWotever/SimHub#1107]
**Describe the bug**
Trying to enable a TSS screen under the dash studio however the display is not detected

**Simhub version**
8.0.1

**To Reproduce**
1. Plug in screen and let windows discover it
2. Go into dash studio and enable TSS display
3. Device is never found

**Expected behavior**
Device found and able to display a dash

**Screenshots**
![image](https://user-images.githubusercontent.com/12819237/175468524-894214c7-1011-4801-8be1-53fba7a25f19.png)

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/8973410/SimHub.log)

**Additional context**
Tried the display on both my Windows 11 sim rig and my windows 10 laptop. The only other thing is that this is a recently purchased version of the screen that looks different then the prevous but still displays turing smart screen. Think its 5 inches?

**Comment by SHWotever** [comment]
Hi ! This only works with the original 3.5" TSS, I've indeed seen a 5"/7" series coming lately and i've evaluated the 7" version, but the performance was absolutely awful (about 1frame every 2s) so I don't plan to support those new models as it do not meets any interresting performance/price ratio.

**Comment by SHWotever** [comment]
I've added a mention about the 3.5 being only supported in the documentation. When I added these devices there was only a single version under the name "Turing Smart Screen"

**Comment by jbastawrose120** [comment]
@SHWotever could you provide some steps to get the 5" TSS screen working? I bought the 5" before knowing the only the 3.5 was supported. They seem to be very similar hardware, so is it difficult to make a plugin or something for it? I know how to code, I'm just not familiar with these displays and Simhub development.
