### ISSUE TITLE
Keyboard controller actions are not recognized if SimHub starts minimized on boot

### ISSUE THREAD

**Issue by lflem29** [SHWotever/SimHub#1108]
Keyboard controller actions are not recognized if SimHub starts minimized

8.0.1

1. configure a keyboard action to control an event, i use graphical dash plugin A as an example.
2. ensure simhub starts with windows and minimised
3. attempt to use the keyboard as a controller action.

**Expected behavior**
keyboard controller actions work.

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/8975111/SimHub.log)

**Comment by SHWotever** [comment]
Hi a fix for this has been released a few versions ago, I close it ;)
