### ISSUE TITLE
[Feature request] Alternative payment method

### ISSUE THREAD

**Issue by Awpii** [SHWotever/SimHub#1109]
I live in Argentina where Paypal is not allowed to take credit card payments (Argentine banks block them) therefore I can't pay a license.
It would be nice to have an alternative payment method so that we can buy licenses too, I feel left out and I really wanna use Simhub :(

**Comment by SHWotever** [comment]
Hi !

Thanks for your interest. Currently for administrative reasons I'm keeping only paypal, i'm looking for alternatives which can be integrated with the licensing system and accessible to individual developers, but most of them does not supports neither the countries not available in paypal

If somehow I find a compliant payment system I will be happy to add it, but for now i've not found any good candidate. 

I close this as this is more a "commercial" issue, and it can't be changed easily for now.
