### ISSUE TITLE
[Feature request] Ability to set profiles for events based on car, or other telemetry value

### ISSUE THREAD

**Issue by DragRedSim** [SHWotever/SimHub#111]
I'd like the ability to set up a group of input mappings that can be enabled or disabled together. I have joypad buttons bound to assignments in the game, which also trigger the TM1638 screens in SimHub via Arduino. However, these screens differ from car to car.

So for example, if I'm driving an Indycar, that activates a profile where the joypad buttons trigger one event, while if I'm driving a GT car, a different profile is active. Ideally, this could be triggered by any value the user chooses, but I'm looking to set it based on GameData.NewData.CarModel.

**Comment by SHWotever** [comment]
Hi ! Unfortunately after all those years this request remained completely unique. I close it for readability purpose even if the the feature would be interesting.
