### ISSUE TITLE
bug simhub 

### ISSUE THREAD

**Issue by hugodanilosanchezmayorga** [SHWotever/SimHub#1112]
**Describe the bug**

**Simhub version 8.0.3**
Make sure to run the latest version

**7.4.23**

**Expected behavior**

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/99372898/177085333-53df8988-d6be-4c44-9197-5b4c27af1112.png)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**
help please, in the dash studio settings in default dashboard controls in the cycle of the next script template and cycle of the previous script template when assigning a button to change it does not respond and does not change the templates in the secondary screen or dashboard , this happens from version 8.0, 8.0.1, 8.0.2 and 8.0.3 in version 7.4.23 there is no this defect so I had to change version, I bought the license, I hope they help to solve this defect as soon as possible, thanks

**Comment by SHWotever** [comment]
Hi ! 

Thanks for your report, 

I've identified the bug and fixed it for the next version,

Nicolas

**Comment by hugodanilosanchezmayorga** [comment]
Thank you very much I will be waiting for the next version to check

**Comment by hugodanilosanchezmayorga** [comment]
thanks with version 8.0.4 the problem is solved, keep it up congratulations

**Comment by hugodanilosanchezmayorga** [comment]
GREETINGS, AFTER INSTALLING VERSION 8.3.3, 8.3.4.,. AND VERSION 8.3.5, WHEN YOU TURN OFF THE PC, THE DEVICES WITH LED LIGHT DO NOT TURN OFF AND I HAVE HAD TO GO BACK TO VERSION 8,2,3, I HAVE A PURCHASED LICENSE, I HOPE THEY SOLVE THIS BUG SOON
