### ISSUE TITLE
Install bug 8.00.3

### ISSUE THREAD

**Issue by AnotherRuben** [SHWotever/SimHub#1113]
**Describe the bug**
When I want to install 8.00.3 I get an error saying I do not have the propper permission to install it. 

1. Download from simhubdash.com
2. extract zip
3. open file
4. error

1. Download from simhubdash.com
2. extract zip
3. open file as admin
4. error

**Expected behaviour**
That the executable will install

**Screenshots**
![image](https://user-images.githubusercontent.com/26065182/177194611-bf6e7f50-b1f7-4504-a2e8-b8e172dd62b3.png)

**Comment by SHWotever** [comment]
Hi ! This looks like a windows error, could you try to move it in another folder before trying to launch it ? This might be a rights issue or maybe a one drive issue blocking it (one drive depending of the settings can put files "online" and prevent the proper launch.

**Comment by AnotherRuben** [comment]
Tried that, didn't solve it. Forgot to turn of the anti virus, that did solve the problem. Thanks for the response!
