### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by romarin84** [SHWotever/SimHub#1118]
Hello SHWotever,  
Je parle Français il me semble que toi aussi, 
j'ai une question un peu spéciale 
j'utilise un overlays F1 time pour notre ligue de formule 1  lorsque je conduit les secteur sont bien referencé et il s'affiche avec une couleur 
alors que quand le streamers diffuse nos courses lorsqu'il regarde quelqu'un d'autres les couleurs et les secteurs n'apparaissent pas , je me demande comment résoudre ce probleme je ne suis pas tres fort en java script

voici le lien du timer en question 
https://www.racedepartment.com/downloads/official-f1-2022-tv-overlays-for-assetto-corsa-simhub.50569/

j'utilise tous les overlays de cette personne

Merci Wotever pour ta réponse  ^^

**Comment by SHWotever** [comment]
Hello ! Je cloture ;) Les replays/spectator ne sont supportés qu'en partie en fonction des données disponibles, le focus de simhub est le temps réel.

Nicolas
