### ISSUE TITLE
[Feature request] Knobster Support 

### ISSUE THREAD

**Issue by jbnl** [SHWotever/SimHub#1120]
**Is your feature request related to a problem? Please describe.**
I own 4 Sim Innovation Knobsters (dual rotary encoders) for my Flight simulator using Air Manager for dashboards/panels, but I can't use them with racing sims as they are not supported by Simhub.

**Describe the solution you'd like**
It would be great if I could connect my Knobsters to Simhub. There is an API available to connect to the Knobster; https://github.com/SimInnovations/libknobster 

The API link describes how to find, connect and await responses from the Knobster device(s), and there is an example available written in C.

**Describe alternatives you've considered**
I've tried flashing the Knobsters as regular Arduino dual rotary encoders but they are closed off and I'm not able to flash them. I was in contact with Sim Innovations, and they pointed me to libknobster - their API. I asked the developer of Axis and Oh's ([www.axis](https://axisandohs.weebly.com/)) and he found a way to connect to the Knobsters using their API and now offers support. This way I can use the software to bind Knobster output to keys. But Axis and Oh's is also only working with flight simulators, and not racing simulators. It would be fantastic if I could use the same rotary encoders (Knobster) for simracing as well, so I don't have to buy new ones and/or constantly have to switch them out when changing my flight setup to race setup.

**Additional context**
Nope, just a pretty please and I hope this is something you can connect to in a future update.

**Comment by SHWotever** [comment]
Hi ! I took a look at this device. I'm not sure simhub is the good candidate for your need. From my understanding you want to control your games with it. This is clearly the kind of things which could be done by the device driver. Or eventually build a small standalone utility using the sdk to convert rotations to keystrokes/game controller key presses so it becomes completely universal. 
Overall this is out of the scope of simhub in my mind (it does not uses game data, does not act as a display device and primarly needs to interact with the game as a standard controller ....). 

Nicolas
