### ISSUE TITLE
SimHub Installer 8.00.4 detected as virus

### ISSUE THREAD

**Issue by PedroHenriqueGS** [SHWotever/SimHub#1121]
**Describe the bug**
The SimHub installer to 8.00.4 is detected as virus by Kaspersky Total Security

**Simhub version**
8.00.4

**To Reproduce**
1. Have Kaspersky Total Security lastest version and updated.
2. Extract SimHub 8.00.4 installer'
3. Try to install and get a message from Windows about file corruption and notification by KTS about infection on data0003

**Expected behavior**
Start install normally

**Screenshots**
![image](https://user-images.githubusercontent.com/24606969/178647014-c9279f82-56f0-42a7-8bba-e0ffda3a1a35.png)

**Log files**
N/A

**Additional context**
N/A

**Comment by SHWotever** [comment]
Hi !

Unfortunately Kaspersky seems to trigger randomly false positives toward simhub in the latest versions. I tested it using virustotal before release and it was perfectly fine, however virustotal's Kaspersky version might not report results the exact same way as consumer version. Do not hesitate to report this false positives to your antivirus support so they can fix it. Apparently Kaspersky is the only antivirus acting this way so it's definitely something which should be fixed on the antivirus side.

Best regards,
Nicolas
