### ISSUE TITLE
Incorrect Font rendering in HTML Mode; FontFaces.css generated incorrectly (with solution)

### ISSUE THREAD

**Issue by akamal** [SHWotever/SimHub#1123]
**Describe the bug**
Many fonts display with incorrect weight on phones\tablets or windowed with the HTML engine enabled. Most commonly bold or extra bold are used instead of normal or lighter weights. [Solution below!]

**Simhub version**
8.0.4

**To Reproduce**
Download the [Titillium Web](https://fonts.google.com/specimen/Titillium+Web) font from Google, and create a dash with a text element for each different font weight.
Observe that when rendered in Dash Studio all the text is displayed with correct font weight.
Start the dash windowed (with HTML Engine disabled) confirm text still appears correctly.
Connect to the dash from a phone (or start it windowed with HTML engine enabled), and observe that the font weights are incorrect.

This is not specific to this font. Several other modern fonts (including [Roboto](https://fonts.google.com/specimen/Roboto?query=roboto), and [Formula 1 Display](https://blogfonts.com/formula1-display-bold.font) have similiar problems).

**Expected behavior**
Displayed font weights in HTML mode should be as correct as possible.

**Screenshots of the problem**
![phone-before](https://user-images.githubusercontent.com/1450142/179386965-29902675-f9f3-488c-8504-c2e67bc7f0f1.png)
![desktop firefox-before](https://user-images.githubusercontent.com/1450142/179387059-7094556a-a965-4f8a-aaef-0feb97384334.png)

**Screenshots of the expected behaviour**
![phone-after](https://user-images.githubusercontent.com/1450142/179387046-a972a7da-1cae-457f-9cdf-2a9861373de5.png)
![desktop firefox-after](https://user-images.githubusercontent.com/1450142/179387061-62ad8834-2c84-4039-8346-3ed72b226b0f.png)

**Additional context**
This is being caused by the \SimHub\Web\FontFaces.css being incorrectly generated. For example Titillium Web consists of the following ttf files:
```
TitilliumWeb-SemiBoldItalic.ttf
TitilliumWeb-Black.ttf
TitilliumWeb-Bold.ttf
TitilliumWeb-BoldItalic.ttf
TitilliumWeb-ExtraLight.ttf
TitilliumWeb-ExtraLightItalic.ttf
TitilliumWeb-Italic.ttf
TitilliumWeb-Light.ttf
TitilliumWeb-LightItalic.ttf
TitilliumWeb-Regular.ttf
TitilliumWeb-SemiBold.ttf
```

And here are all the entries for that font generated in FontFaces.css:
```
@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/TitilliumWeb-Black.ttf');
    
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/TitilliumWeb-Bold.ttf');
    font-weight: bold;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/TitilliumWeb-BoldItalic.ttf');
    font-weight: bold;
    font-style: italic;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/TitilliumWeb-ExtraLightItalic.ttf');
    font-style: italic;
}
```

As you can see the entries for Bold and BoldItalic are correct, but the entries for Normal and Italic are pointing to the wrong ttf files, and there are no entries for most of the available variants.

**Solution**
I've written a quick and dirty little utility that regenerates a (more) correct Fontfaces.css. For example this snippet is what it generates for Titillium Web:
```
@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/titilliumweb-black.ttf');
    font-weight:900;
    font-style:Normal;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/titilliumweb-bold.ttf');
    font-weight:700;
    font-style:Normal;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/titilliumweb-bolditalic.ttf');
    font-weight:700;
    font-style:Italic;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/titilliumweb-extralight.ttf');
    font-weight:275;
    font-style:Normal;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/titilliumweb-extralightitalic.ttf');
    font-weight:275;
    font-style:Italic;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/titilliumweb-italic.ttf');
    font-weight:400;
    font-style:Italic;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/titilliumweb-light.ttf');
    font-weight:300;
    font-style:Normal;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/titilliumweb-lightitalic.ttf');
    font-weight:300;
    font-style:Italic;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/titilliumweb-regular.ttf');
    font-weight:400;
    font-style:Normal;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/titilliumweb-semibold.ttf');
    font-weight:600;
    font-style:Normal;
}

@font-face {
    font-family: "Titillium Web";
    src: url('/Fonts/titilliumweb-semibolditalic.ttf');
    font-weight:600;
    font-style:Italic;
}
```
This results in the improved font rendering in the expected behaviour images above. I'm sure it's still not perfect, given the historical weirdness of some fonts on windows, but it is working much better for every font I've used so far. 

Having to remember to run the utility every time after starting SimHub (as SimHub detects that if the file doesn't match the expected checksum and replaces it on startup) is a bit of a pain, and obviously it doesn't help anyone else which makes sharing dashes that use any of the effected font weights pretty much impossible. So it would be great if you could look at fixing this.

To make that as easy as possible, here is the code for my utility. It's structured in a way that should make it fairly simple to integrate the relevant logic into Simhub, so feel free to make use of it. All the important code is in the App.xaml.cs codebehind (I did say it was quick and dirty!)

[fonttest2.zip](https://github.com/SHWotever/SimHub/files/9127158/fonttest2.zip)

cheers
ak

**Comment by SHWotever** [comment]
Hi !

The fix has been released with simhub 8.1.0

Best regards,
Nicolas
