### ISSUE TITLE
[Feature request] Ability to include Javascript extension files in an exported Dash

### ISSUE THREAD

**Issue by akamal** [SHWotever/SimHub#1124]
**Is your feature request related to a problem? Please describe.**
The ability to create custom javascript extensions files is a fantastic feature that makes dash development so much better, thanks for that! But it does complicate deploying\sharing a dash that depends on those extensions as they are not included with an a exported dash, and have to be packaged seperately and manually copied to the JavascriptExtensions directory.

**Describe the solution you'd like**
It would be great if we could add a .js file to the the dash directory, have it be included in the .simhubdash archive when exporting the dash, and then automatically copied to \SimHub\JavascriptExtensions when that dash is installed. (Similar what currently happens with fonts).

**Describe alternatives you've considered**
The obvious work arounds I can think of are:
1. I could manually package a dash as a zip file with the root directory being the SimHub directory, with the JavascriptExtensions directory included along with the necessary .js files. That would then put everything in the right place if the extracted directly into the SimHub directly. While this would work, it depends on people actually knowing how to do that, and it seems a shame to give up on the nice installation experience double clicking a .simhubdash current has. 
2. Create an fullblown installer package for the dash, using Nullsoft Installer or similar. This would work, but feels like using a sledgehammer to crack a walnut, and again gives up on the current .simhubdash installation experience. Also having to run an executable installer to install a dash is likely to be off putting for a lot of people - I'd certainly be suspicious of it.

**Additional context**
If any .dll files in the dash directory at export time could also be included in the archive and copied to the SimHub root directory on installation, to make including plugins with a dash possible as well, that would be fantastic!

**Comment by AzeTheGreat** [comment]
I just tested this, and it looks like exported dashes now contain the JavascriptExtensions folder.  I believe this issue can be closed.
