### ISSUE TITLE
[Feature request] 'new' rFactor 2 Vehicle Infos

### ISSUE THREAD

**Issue by dweiss96** [SHWotever/SimHub#1126]
**Is your feature request related to a problem? Please describe.**
Simhub seems to be missing some Properties the SharedMemoryPlugin exposes in the `VehicleInfo` as well as in general the `VehicleInfo` for opponents. This data should be the same the new broadcast overlays are using according to rFactor 2 developers.

**Describe the solution you'd like**
I would like to have these properties accessible from within SimHub without having the need to write my own plugin/ hope for the GarySwallowPlugin to include these properties.

**Describe alternatives you've considered**
The alternative would be to write a custom plugin exposing these properties (and replacing the rFactor2 `GameRawData` completely)

**Additional context**
explicit missing SharedMemoryPlugin properties missing with github links:
[TheIronWolfModding/rF2SharedMemoryMapPlugin rF2Data.cs#L484-L488](https://github.com/TheIronWolfModding/rF2SharedMemoryMapPlugin/blob/e39fa0a2e8673c041adae3c1f43fbc93d97397a5/Monitor/rF2SMMonitor/rF2SMMonitor/rF2Data.cs#L484-L488)
[TheIronWolfModding/rF2SharedMemoryMapPlugin rF2Data.cs#L477-L478](https://github.com/TheIronWolfModding/rF2SharedMemoryMapPlugin/blob/e39fa0a2e8673c041adae3c1f43fbc93d97397a5/Monitor/rF2SMMonitor/rF2SMMonitor/rF2Data.cs#L477-L478)
[TheIronWolfModding/rF2SharedMemoryMapPlugin rF2Data.cs#L477-L478](https://github.com/TheIronWolfModding/rF2SharedMemoryMapPlugin/blob/e39fa0a2e8673c041adae3c1f43fbc93d97397a5/Monitor/rF2SMMonitor/rF2SMMonitor/rF2Data.cs#L504-L506)
[TheIronWolfModding/rF2SharedMemoryMapPlugin rF2Data.cs#L477-L478](https://github.com/TheIronWolfModding/rF2SharedMemoryMapPlugin/blob/e39fa0a2e8673c041adae3c1f43fbc93d97397a5/Monitor/rF2SMMonitor/rF2SMMonitor/rF2Data.cs#L514)
[TheIronWolfModding/rF2SharedMemoryMapPlugin rF2Data.cs#L477-L478](https://github.com/TheIronWolfModding/rF2SharedMemoryMapPlugin/blob/e39fa0a2e8673c041adae3c1f43fbc93d97397a5/Monitor/rF2SMMonitor/rF2SMMonitor/rF2Data.cs#L847)

For the `rF2VehicleScoring` array you can expect to have no more than 104 entries since this is the maximum number of players possible.

**Comment by St54Kevin** [comment]
I agree the rf2 implementation needs a revision for the data available

**Comment by pedrobarbosasr** [comment]
Totally agree.

**Comment by St54Kevin** [comment]
Did somebody found time to have a look into new things to add?

**Comment by SHWotever** [comment]
hi ! I close this a fresh dataset of opponents data has been added. It does not match the requested data but it's focused on providing a coherent experience across games.
