### ISSUE TITLE
Dash Studio - Blur radius Fx in HTML mode

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1128]
**Describe the bug**
Hi,
The blur radius formulas don't seem to work properly in HTML mode.

**Simhub version**
8.0.4

**To Reproduce**
1. Have a component with blur radius controlled by a formula.
2. Run the dash in HTML mode.
3. The component blur radius doesn't update properly. It stay blurry in my case

Here is a test dash using this Fx:
![image](https://user-images.githubusercontent.com/50543913/180489072-82356f9e-6a93-468b-bb51-389c92392809.png)

[Blur test.zip](https://github.com/SHWotever/SimHub/files/9169485/Blur.test.zip)

**Screenshots**
HTML on top
![image](https://user-images.githubusercontent.com/50543913/180489542-04096860-f4fd-4789-b4e3-a29b6e859789.png)

**Log files**
No error in the log

**Additional context**
The blur radius works fine in desktop mode.
On a side note the blurring seems to be a little stronger in HTML mode.

Bon week-end!

**Comment by SHWotever** [comment]
After a (too) long time, it's fixed ;)

**Comment by Romainrob** [comment]
Cool! I just tried it and it updates fine now.
Thanks for the fix!
