### ISSUE TITLE
Microsoft .Net Framework 4.8 required but upon install error 0x800f081e 

### ISSUE THREAD

**Issue by Miro228** [SHWotever/SimHub#1130]
Hi, this is a follow-up post to my previous one that I did not get around to solving as life got in the way however now things are back to normal I would like to resolve it. 

From the start:
So I was trying to install Sim Hub and towards the end of the installation I'm greeted with this error message:
![image](https://user-images.githubusercontent.com/97639741/180637168-230b748d-8756-4049-9cfc-6a6ecfab8fc5.png)

So I click yes and follow the prompts to install Microsoft .NET Framework but however after all the files download and it gets to 100% I get this error screen.

![image](https://user-images.githubusercontent.com/97639741/180637176-bf07bfcc-9fad-43df-a52a-03de43a22aae.png)

I was previously asked about what operating system I use and it is Windows 10, however, they also said to update my system which is something that I have been unable to do for a long time. When I go into the windows settings and get to the windows update page I get this:

![image](https://user-images.githubusercontent.com/97639741/180637230-530f1cbc-eade-4d0f-ab01-d5e11b9f3700.png)

and I've tried so many YT videos to fix it at this point I have no idea what I have and haven't done, all I can tell you with certainty is that by clicking retry, I get this loading page

![image](https://user-images.githubusercontent.com/97639741/180637275-460d64eb-033f-4645-ba8a-405dd0acc815.png)

followed by this message:
![image](https://user-images.githubusercontent.com/97639741/180637283-56768f41-8a82-433f-85dd-333d86c051f3.png)

If somebody could help that'd be greatly appreciated. Thanks in advance.
PS. I have attached the log file from .NET error screen.

[Microsoft.NET.error.log.full.txt](https://github.com/SHWotever/SimHub/files/9175327/Microsoft.NET.error.log.full.txt)
n

**Comment by BuToNz** [comment]
Try these fixes: https://www.windowslatest.com/2018/06/23/fix-windows-update-issues-on-windows-10/

The Framework installer requires Windows Update to be functional to download the files. Once your Windows Update issues are fixed it'll no doubt work.
