### ISSUE TITLE
FPS..

### ISSUE THREAD

**Issue by RodentYell** [SHWotever/SimHub#1131]
Is there away to improve fps when running Simhub? I'm just finding more and more that it is using alot of my fps, without Simhub running on ACC single car in free practice at Nurburgring I'll get anywhere between 135/170fps, with Simhub running I'll get anywhere between 98/132 fps, thats alot of difference to me..

**Comment by BuToNz** [comment]
Sounds like you are CPU limited since we're talking about high framerates. What is your CPU?
