### ISSUE TITLE
Demande de prise en charge

### ISSUE THREAD

**Issue by gourmand72** [SHWotever/SimHub#1132]
Bonjour, pouvez vous svp, inclure le jeu CITY CAR DRIVING, pour qu'il soit pris en charge par SIMHUB ?
Cordialement

**Comment by SHWotever** [comment]
Bonjour,

Malheuruesment la télémétrie est seulement disponibles dans la version "à usage commercial". Très peu d'utilisateurs sont prèts à investir les milliers d'euros nécessaires pour cette version.
