### ISSUE TITLE
F7 for focus

### ISSUE THREAD

**Issue by Quirky1869** [SHWotever/SimHub#1133]
**Describe the bug**
Hello guys with the 2.0.4 version I can't click on F7 for focus on an item

**Simhub version**
2.0.4

**To Reproduce**
1. Go to "Edit dashboard"
2. Click on text idem on toolbox (for example) and on the right (on "screen hierarchy") click on your new text item and click on "F7", after click on F7 I can't deplace my item with the keyboard arrows.
//3. Scroll down to '....'
//4. See error

**Expected behavior**
Just fix F7 on Edit Dashboard :)
With the 2.0.3 version i didn't have this issue

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
[SimHub.log](https://github.com/SHWotever/SimHub/files/9221682/SimHub.log)

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Thanks for the report, I fixed it for the next release.

Nicolas
