### ISSUE TITLE
Shacker not detected

### ISSUE THREAD

**Issue by AL2964** [SHWotever/SimHub#1138]
Hi,
Today (august 10, 2022) I have only 2 of my 4 shackers working since a pc update was done. 
Before that , everything was working properly.
What should i do please ? I can't find a solution.
Thank's
Alan

**Simhub version**
Make sure to run the latest version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by SHWotever** [comment]
Hi ! 

Please make sure to review your drivers configuration, when drivers gets updated they often falls back to default stereo setup.

Nicolas

**Comment by AL2964** [comment]
Hi Nicolas,
Thanks for your help. It worked 👍Sincerely,
Alan

Envoyé depuis Yahoo Mail pour Android 
 
  Le sam., août 13, 2022 à 17:39, ***@***.***> a écrit:   


Hi !

Please make sure to review your drivers configuration, when drivers gets updated they often falls back to default stereo setup.

Nicolas
