### ISSUE TITLE
Keyboard Modifiers[Feature request]

### ISSUE THREAD

**Issue by LCSLeecarL** [SHWotever/SimHub#1139]
Adding Keyboard support for Modifiers "Shift/Alt/Ctrl"

ie: Ctrl+Shift+Y

Useful for expanding touchscreen capabilities without adding a physical input board, and not conflicting with most-used keyboard functions.

**Comment by SHWotever** [comment]
Hi ! I missed that request lost in the hyperspace ;) The combo capabilities have been added a long time ago ;)
