### ISSUE TITLE
Upgrade Jint to 3.x

### ISSUE THREAD

**Issue by sierses** [SHWotever/SimHub#1144]
Jint 2.x only supports up to ES5. Since then, there have been many additions to the JS language.
Jint 3.x supports many of the new JS features which would make custom code a lot more powerful for both dashes and effects.
It also claims to be significantly faster which should give more available headroom to current custom code.

**Comment by SHWotever** [comment]
Hi ! The library has been updated to the latest version. 

Nicolas
