### ISSUE TITLE
euro truck simulator 2 de simhub yazılımını çalıştıramadım

### ISSUE THREAD

**Issue by tcali09** [SHWotever/SimHub#1145]
plugins klasörünü uyguladığım halde euro truck simulator 2 oyunu verileri telefona veya arduino karta veriler gelmiyor yardımcı olursanız sevinirim

**Comment by SHWotever** [comment]
Hi !

Could you join the log files ? Are you using the official steam version of the game ? 

Nicolas

**Comment by tcali09** [comment]
Oyunun resmi steam sürümünü kullanıyorum
