### ISSUE TITLE
[Feature request] Add support to Gran Turismo 7

### ISSUE THREAD

**Issue by alteredeg0** [SHWotever/SimHub#1146]
First of all thank you for all you work creating this awesome software. Without you and SimHub the simracing scene wouldn't be the same.

For years the Gran Turismo series has been left out of a lot of features that expand the racing experience beyond a controller or a steering wheel and pedals due to the lack of telemetry data.

Recently some users from GTPlanet forum discovered that there is UDP telemetry in GT7 edition intended tu be used in motion platforms, and the user/dev [Nenkai](https://github.com/Nenkai) did create and [API](https://github.com/Nenkai/PDTools) to retrive these data. 
Since then some others developers had expanded the work and create different tools around this API, some popular Smartphone Dashboard apps had added support and there's companies as Symdeck anouncing that they are adding support for this game to their products.

Would be possible to add support to this game in SimHub? I think the GT series has a big fan base (including me) and this can expand the sim racing scene to new people.

My best regards and kudos to you!

**Comment by sayapinsergej** [comment]
I support, I hope the developers will hear our request. That would be really cool!

**Comment by SHWotever** [comment]
Hi !

I started the implementation of GT7 unfortunately there are a few issues which might slow down/block the release of it.

- GT7 is a console only game, while simhub is a PC software intended for PC only games (supported consoles games were only a "side effect". That requires a real philosophy change.
- Telemetry lacks some important data like current lap time or current track id/name.
- Some features (like gear behavior) can only be tested with ps4/5  compatible gears (wheels and shifter), controllers won't show the whole specificities.

The last point, but the most problematic.
- From my tests on GT7 on a PS4, the telemetry is having lags ant cuts. Regularly the telemetry stops for a few seconds, that's not a good basis.  
This last point for me is a real deal breaker. I'm not sure it's the case on PS5 too (but ps5 is almost impossible to get).

**Comment by alteredeg0** [comment]
Thank you so much @SHWotever!

Maybe you already know it but there's a bunch of people in the gtplanet forum looking into some of the problems you describe.
Regarding the lap time this dev came to an approach that seems to work well: https://www.gtplanet.net/forum/threads/gt7-is-compatible-with-motion-rig.410728/post-13810797
The entire post is a gem.

I have a PS5 and can set up a dedicated PC for SimHub and GT7, and even when I'm not a good programmer I'm a systems and DevOps engineer with a lot of experience setting up, testing and debugging software, so if you want me to run any test please let me know because I would be more than happy to help you in anything I can.

Kudos

**Comment by mdriverch** [comment]
> Hi !
> 
> I started the implementation of GT7 unfortunately there are a few issues which might slow down/block the release of it.
> 
>     * GT7 is a console only game, while simhub is a PC software intended for PC only games (supported consoles games were only a "side effect". That requires a real philosophy change.
> 
>     * Telemetry lacks some important data like current lap time or current track id/name.
> 
>     * Some features (like gear behavior) can only be tested with ps4/5  compatible gears (wheels and shifter), controllers won't show the whole specificities.
> 
> 
> The last point, but the most problematic.
> 
>     * From my tests on GT7 on a PS4, the telemetry is having lags ant cuts. Regularly the telemetry stops for a few seconds, that's not a good basis.
>       This last point for me is a real deal breaker. I'm not sure it's the case on PS5 too (but ps5 is almost impossible to get).


I would provide my help and PS5.

**Comment by sayapinsergej** [comment]
Hi! How are things going?

**Comment by sayapinsergej** [comment]
Hi! Has development stopped?

**Comment by SHWotever** [comment]
Hi ! Indeed I put gt7 aside for the reasons I was listening previously. I co

**Comment by sayapinsergej** [comment]
It's a pity ((I think many have been waiting for this.  And another question, why doesn't Simhub work with Project Cars 2 (PS4)?

**Comment by SHWotever** [comment]
Hi !

About pc2 ,You can switch the telemetry mode to UDP in simhub game settings, you will need to open your firewall and configure the game too.

Concerning gt7 I will do some additional investigations but if It happens that unstable telemetry is coming from the game, I will probably not continue.

**Comment by sayapinsergej** [comment]
Hello! How are things going with development? Maybe release a test version and distribute it to everyone?

**Comment by SHWotever** [comment]
Hi !

After lot of hesitations I finally released it ;) I took me some time so solve the mathematical challenges of quaternions and rewrite my own code (as I can't use Nenkai one). But it's finally here. GT7/GTSport (GT6 won't be supported, it's dated and only on PS3 with some mess about little endian/big endian)

**Comment by sayapinsergej** [comment]
Incredible news! A New Year's gift! SHWotever, thank you so much!
