### ISSUE TITLE
[Feature request] - Include pitting cars and pace car to OpponentsAhead/BehindOnTrack

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1147]
Hi, 
In these lists, the cars in the pit lane as well as the pace car are filtered out:
OpponentsAheadOnTrack
OpponentsBehindOnTrack
OpponentsAheadOnTrackPlayerClass
OpponentsBehindOnTrackPlayerClass

Would it be possible to have toggle options to include the pace car and pitting cars in the lists so they can appear on the relative.
Or maybe have additional non "OnTrack" OpponentsAhead/behind lists that includes all the cars.

Note that this is behavior applies to iRacing. I noticed it while working on my leaderboard focused plugin.
I don't know if this applies to all the games or the built in lb components/properties and persistent tracker props.

As a bonus idea (lucky you ;)), having an option to "center "the lists (and therefore the relative) on the spectated car instead of always the player car could be nice.
For iRacing, irData.Telemetry.CamCarIdx gives the car idx of the currently spectated car. Idk how pertinent this would be for other games, or if many offer this data.

In any case, thanks in advance for considering these ideas.
Bonne soirée!

**Comment by SHWotever** [comment]
Hi ! I close this as it's now possible through settings to choose who you want to see (pit, pit lane, only track). Concerning the pace car I don't plan to include it too many data would be missing and it would dig a "hole"in data (gap etc ..)
