### ISSUE TITLE
Plase help about Ardunio library 

### ISSUE THREAD

**Issue by Aimen37** [SHWotever/SimHub#1153]
it was a tutorial video but not all libraries are in ardinio in simhab and there is no library on the internet that I can't find: flowserialread

**Comment by SHWotever** [comment]
Hi ! You don't need any libraries, everything is bundled with the sketch setup utility : https://github.com/SHWotever/SimHub/wiki/Arduino--Setup#sketch-configuration

**Comment by Aimen37** [comment]
thanks but when printing the code to arduino it gives an error and the error is FlowSerialRead.h: No such file or directory

**Comment by SHWotever** [comment]
Hi !

Could you detail the context where you are having the error ? when using the built in setup utility I can't see any particular reason for the file to be missing :
![image](https://user-images.githubusercontent.com/2207331/189483916-802c0481-68a9-455e-ad04-921ec1583a01.png)
