### ISSUE TITLE
[RF2] - Slow refresh rate / Freezes

### ISSUE THREAD

**Issue by DesmoGiec** [SHWotever/SimHub#1157]
**Describe the bug**
Always happens that simhub dashboard freezes and/or have really slow refresh rate

**Simhub version**
8.1.1 (but always did, even with older realeses)

**To Reproduce**
Just start any dashboard..

**Expected behavior**
--

**Screenshots**
I made an explication video
https://www.youtube.com/watch?v=BhYTRYSFhkk

**Log files**

- [2022-09-26 22:08:12,713] INFO - Starting SimHub v8.1.0 (build time : 03/09/2022 15:18:19)
- [2022-09-26 22:08:12,714] INFO - Administrator privileges : True 
- [2022-09-26 22:08:12,714] INFO - OS version : Microsoft Windows NT 10.0.22621.0, Windows 10.0.22621
- [2022-09-26 22:08:12,714] INFO - License status : Licensed
- [2022-09-26 22:08:12,714] INFO - Process priority : Normal
- [2022-09-26 22:08:17,849] INFO - (Re)Starting RFactor2 Game Manager and plugin manager
- [2022-09-26 22:08:17,850] INFO - Creating RFactor 2 game manager (RfactorReader.RF2Manager)
- [2022-09-26 22:08:17,866] INFO - RFactor2 game manager created
- [2022-09-26 22:08:17,874] INFO - Checking configuration status for RFactor2
- [2022-09-26 22:08:17,874] INFO - Detected install path : C:\Program Files (x86)\Steam\SteamApps\common\rFactor 2
- [2022-09-26 22:08:17,903] INFO - Configuration status for RFactor2: GameConfigured
- [2022-09-26 22:08:17,903] INFO - Creating plugin manager with plugins : JoystickPlugin, GraphicalDashPlugin, DevicesPlugin, KeyboardEmulatorPlugin, LapHitoryPlugin
- [2022-09-26 22:08:17,925] INFO - Creating SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
- [2022-09-26 22:08:17,927] INFO - Creating SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
- [2022-09-26 22:08:17,929] INFO - Creating SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
- [2022-09-26 22:08:17,929] INFO - Creating SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
- [2022-09-26 22:08:17,931] INFO - Creating SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
- [2022-09-26 22:08:17,933] INFO - Creating SimHub.Plugins.Web.WebPlugin plugin
- [2022-09-26 22:08:17,934] INFO - Creating SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin
- [2022-09-26 22:08:17,935] INFO - Creating SimHub.Plugins.InputPlugins.JoystickPlugin plugin
- [2022-09-26 22:08:17,936] INFO - Creating SimHub.Plugins.Devices.DevicesPlugin plugin
- [2022-09-26 22:08:17,937] INFO - Creating SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin
- [2022-09-26 22:08:17,937] INFO - Creating SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin
- [2022-09-26 22:08:17,938] INFO - Initialising SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
- [2022-09-26 22:08:18,385] INFO - Initialising SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
- [2022-09-26 22:08:18,412] INFO - Initialising SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
- [2022-09-26 22:08:18,413] INFO - Initialising SimHub.Plugins.Devices.DevicesPlugin plugin
- [2022-09-26 22:08:18,423] INFO - Initialising SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin
- [2022-09-26 22:08:18,424] INFO - Initialising SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
- [2022-09-26 22:08:18,425] INFO - Initialising SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
- [2022-09-26 22:08:18,425] INFO - Initialising SimHub.Plugins.InputPlugins.JoystickPlugin plugin
- [2022-09-26 22:08:18,476] INFO - Initialising SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin
- [2022-09-26 22:08:18,486] INFO - Initialising SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin
- [2022-09-26 22:08:18,562] INFO - JoystickManager : Starting game controllers detection
- [2022-09-26 22:08:18,675] INFO - JoystickManager : Found CSL_Pedals_Load_Cell_Kit
- [2022-09-26 22:08:18,689] INFO - JoystickManager : Found FANATEC_Wheel
- [2022-09-26 22:08:18,692] INFO - JoystickManager : Found FANATEC_Wheel
- [2022-09-26 22:08:18,692] INFO - Loading font list
- [2022-09-26 22:08:18,694] INFO - JoystickManager : End of detection
- [2022-09-26 22:08:18,890] INFO - Font list loading successful
- [2022-09-26 22:08:18,917] INFO - Initialising SimHub.Plugins.Web.WebPlugin plugin
- [2022-09-26 22:08:19,002] INFO - Web suggested IP :192.168.1.201
- [2022-09-26 22:08:19,043] INFO - Regenerating Web font-faces
- [2022-09-26 22:08:19,419] INFO - Font-faces definitions extracted successfully
- [2022-09-26 22:08:19,421] INFO - Font-faces updated successfully
- [2022-09-26 22:08:19,436] INFO - Plugin manager correctly initialised
- [2022-09-26 22:08:19,437] INFO - Loading plugins controls
- [2022-09-26 22:08:19,491] INFO - Game connected
- [2022-09-26 22:08:19,492] INFO - Game successfully loaded
- [2022-09-26 22:08:20,504] INFO - Game paused : true
- [2022-09-26 22:08:48,254] INFO - Game paused : false
- [2022-09-26 22:08:48,254] INFO - Session restarted
- [2022-09-26 22:08:48,254] INFO - New invalid lap detected : 00:00:00, (LapId :8458a43b-6aea-41d8-81b0-a25ab868aa95)
- [2022-09-26 22:08:48,260] INFO - Fuel stats tracking resetted
- [2022-09-26 22:08:48,260] INFO - CurrentLap invalidated for Fuel stats
- [2022-09-26 22:08:49,254] INFO - Game paused : true
- [2022-09-26 22:09:12,820] INFO - Game paused : false
- [2022-09-26 22:09:14,221] INFO - Game paused : true
- [2022-09-26 22:09:55,422] INFO - Game disconnected
- [2022-09-26 22:09:58,416] INFO - Checking configuration status for RFactor2
- [2022-09-26 22:09:58,416] INFO - Detected install path : C:\Program Files (x86)\Steam\SteamApps\common\rFactor 2
- [2022-09-26 22:09:58,416] INFO - Configuration status for RFactor2: GameConfigured
- [2022-09-26 22:10:29,604] INFO - Game connected
- [2022-09-26 22:10:30,621] INFO - Game paused : true
- [2022-09-26 22:10:52,971] INFO - Game paused : false
- [2022-09-26 22:10:55,987] INFO - Game paused : true
- [2022-09-26 22:10:56,171] INFO - Game paused : false
- [2022-09-26 22:10:57,387] INFO - Game paused : true
- [2022-09-26 22:11:33,756] INFO - Game paused : false
- [2022-09-26 22:11:58,571] INFO - Game paused : true
- [2022-09-26 22:12:00,688] INFO - Game paused : false
- [2022-09-26 22:12:06,688] INFO - Game paused : true
- [2022-09-26 22:12:20,287] INFO - Game paused : false
- [2022-09-26 22:12:30,820] INFO - Game paused : true
- [2022-09-26 22:12:36,007] INFO - Game paused : false
- [2022-09-26 22:13:20,300] INFO - Window destroyed
- [2022-09-26 22:13:20,301] INFO - Window destroyed
- [2022-09-26 22:13:20,301] INFO - Window destroyed
- [2022-09-26 22:13:20,301] INFO - Window destroyed
- [2022-09-26 22:15:56,124] INFO - New invalid lap detected : 00:00:00, (LapId :049f2cd5-12a9-457d-8160-7e02341e628b)
- [2022-09-26 22:15:56,125] INFO - Fuel stats tracking resetted
- [2022-09-26 22:15:56,125] INFO - New fuel stat aggregated 4.50/lap
- [2022-09-26 22:15:59,805] INFO - Game paused : true
- [2022-09-26 22:16:00,205] INFO - Game paused : false
- [2022-09-26 22:16:57,821] INFO - New invalid lap detected : 00:00:00, (LapId :3360694e-88ed-421b-b9f8-d9146cd49987)
- [2022-09-26 22:16:57,821] INFO - New fuel stat aggregated -11.59/lap
- [2022-09-26 22:16:58,322] INFO - CurrentLap invalidated for Fuel stats
- [2022-09-26 22:17:18,605] INFO - Game paused : true
- [2022-09-26 22:17:58,769] INFO - Game focused : enabling 'no activate' mode for simhub window
- [2022-09-26 22:17:58,789] INFO - Game paused : false
- [2022-09-26 22:18:00,537] INFO - Game paused : true
- [2022-09-26 22:18:00,772] INFO - Game not focused : disabling 'no activate' mode for simhub window
- [2022-09-26 22:18:08,018] INFO - Window destroyed
- [2022-09-26 22:18:16,090] INFO - Game focused : enabling 'no activate' mode for simhub window
- [2022-09-26 22:18:16,138] INFO - Game paused : false
- [2022-09-26 22:19:03,953] INFO - Game paused : true
- [2022-09-26 22:19:11,673] INFO - Game disconnected
- [2022-09-26 22:19:11,694] INFO - Game not focused : disabling 'no activate' mode for simhub window
- [2022-09-26 22:19:48,808] INFO - Window destroyed
- [2022-09-26 22:28:38,737] INFO - Application exit
- [2022-09-26 22:28:38,751] INFO - Stopping game manager
- [2022-09-26 22:28:38,753] INFO - Stopping plugin manager
- [2022-09-26 22:28:38,754] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin
- [2022-09-26 22:28:38,754] INFO - SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin settings saved
- [2022-09-26 22:28:38,754] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.SystemInfosProvider
- [2022-09-26 22:28:38,757] INFO - SimHub.Plugins.DataPlugins.SystemInfosProvider plugin settings saved
- [2022-09-26 22:28:38,757] INFO - Saving plugin settings SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin
- [2022-09-26 22:28:38,761] INFO - SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin settings saved
- [2022-09-26 22:28:38,761] INFO - Stopping plugin SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin
- [2022-09-26 22:28:38,762] INFO - Stopping plugin SimHub.Plugins.DataPlugins.SystemInfosProvider
- [2022-09-26 22:28:38,762] INFO - Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin
- [2022-09-26 22:28:38,762] INFO - Stopping plugin SimHub.Plugins.Devices.DevicesPlugin
- [2022-09-26 22:28:38,765] INFO - Finalizing plugin SimHub.Plugins.Devices.DevicesPlugin
- [2022-09-26 22:28:38,767] INFO - Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin
- [2022-09-26 22:28:38,767] INFO - Stopping plugin SimHub.Plugins.AudioControl.AudioPlayPlugin
- [2022-09-26 22:28:38,767] INFO - Stopping plugin SimHub.Plugins.DataPlugins.Shell.ShellPlugin
- [2022-09-26 22:28:38,767] INFO - Finalizing plugin SimHub.Plugins.DataPlugins.Shell.ShellPlugin
- [2022-09-26 22:28:38,767] INFO - Stopping plugin SimHub.Plugins.InputPlugins.JoystickPlugin
- [2022-09-26 22:28:38,768] INFO - Stopping plugin SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin
- [2022-09-26 22:28:38,768] INFO - Stopping plugin SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin
- [2022-09-26 22:28:38,768] INFO - Finalizing plugin SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin
- [2022-09-26 22:28:38,769] INFO - Stopping plugin SimHub.Plugins.Web.WebPlugin
- [2022-09-26 22:28:38,769] INFO - Finalizing plugin SimHub.Plugins.Web.WebPlugin
- [2022-09-26 22:28:38,769] INFO - Stopped all plugins
- [2022-09-26 22:28:38,769] INFO - Performance dump
- [2022-09-26 22:28:38,769] INFO - SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin::DataUpdate	73147calls	272.576ms	73147calls	0.004ms/call
- [2022-09-26 22:28:38,769] INFO - SimHub.Plugins.Devices.DevicesPlugin::DataUpdate	73147calls	96.064ms	73147calls	0.001ms/call
- [2022-09-26 22:28:38,769] INFO - SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin::DataUpdate	73147calls	450.852ms	73147calls	0.006ms/call
- [2022-09-26 22:28:38,769] INFO - SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin::DataUpdate	73147calls	2219.947ms	73147calls	0.030ms/call
- [2022-09-26 22:28:38,769] INFO - SimHub.Plugins.Web.WebPlugin::DataUpdate	73147calls	224.821ms	73147calls	0.003ms/call
- [2022-09-26 22:28:38,769] INFO - SimHub.Plugins.DataPlugins.SystemInfosProvider::DataUpdate	73147calls	104.389ms	73147calls	0.001ms/call
- [2022-09-26 22:28:38,769] INFO - JoystickPlugin::PollThread	59793calls	2002.179ms	59793calls	0.033ms/call
- [2022-09-26 22:28:38,770] INFO - SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin::DataUpdate	73147calls	19.987ms	73147calls	0.000ms/call
- [2022-09-26 22:28:38,770] INFO - JoystickManager::DetectJoysticks	1calls	254.604ms	1calls	254.604ms/call
- [2022-09-26 22:28:38,849] INFO - Final Exit

**Additional context**
OS: W11
GPU: RX6800
RF2 running in a borderless window
Purchased version of simhub
It seems that losing focus on the game dashboard refresh just goes as it is to be

Thanks

**Comment by SHWotever** [comment]
Hi !

This looks like some performances botteleneck  could you check your GPU load ? Also make sure that the game fps are capped (vsync ...) so simhub has some remaining GPU power.

**Comment by DesmoGiec** [comment]
Sorry for the late reply, I wasn't home. I've found a "solution". I've tried in windowed mode, which will work as the same as borderless to me, and simhub just goes perfectly fine.
Still, on borderless gpu is never @ 100%, but I play without vsync, using freesync.
Well, in windowed works, so that's ok for me.
Thanks :)
