### ISSUE TITLE
[Feature request] Mono setting for Bass Shaker should output to all channels instead of two.

### ISSUE THREAD

**Issue by cybersteel8** [SHWotever/SimHub#1159]
**Is your feature request related to a problem? Please describe.**
Yes. I have a bass shaker on Channel 4 of my sound device, and selecting Mono only sends audio to Channels 1 and 2, so I cannot use the Mono setting in this scenario even though Mono is the ideal setting for this use case.

**Describe the solution you'd like**
Mono will send audio to all channels so it doesn't matter which channel the bass shaker is on. Or, better yet, a means to select which channels Mono will send the signal to. I understand that it will send the same signal to all of the channels I choose - that is what I want.

**Describe alternatives you've considered**
I currently have to use a Custom Channel Map and set all the channels to Off and then manually select On for all of the items in the column for Channel 4 to achieve the same thing Mono would do.

**Comment by SHWotever** [comment]
Hi ! Unfortunately "mono" must only send data to the two first channels. when sending two more, in a stereo setup which is the target of it, the sound card would "simplify" the audio and redirect the two lost channels over the first oned, actually doubling the gain and causing distortion. In your case the best is to use the  "custom" option so you can allocate everything to the 4 channels.

**Comment by cybersteel8** [comment]
Thanks for your explanation! The custom channel map has been working completely fine so I accept that as a solution 😃
