### ISSUE TITLE
f1 graphichs

### ISSUE THREAD

**Issue by pllossi** [SHWotever/SimHub#1160]
I have installed f1 graphics but they didn't work.
I checked the datas fron f1 and from sim hub and they were correct but didn't work on f1 2020
Version 
the last one

**Comment by SHWotever** [comment]
Hi !

What are you calling "F1 graphics" ? 



Nicolas

**Comment by SHWotever** [comment]
Hi ! I'm sorry this is a third party content, do not hesitate to contact the author of you have questions about it.
