### ISSUE TITLE
Screen Layering conditional formatting doesn't work as expected

### ISSUE THREAD

**Issue by talkiet** [SHWotever/SimHub#1161]
When attempting to set a conditional overlay trigger, the true or false status of the condition has no effect on whether the overlay is displayed when the "Hide when not in race" checkbox is not set.

The reason for this is I would like most overlays to hide when not in a car (iRacing) but one to display permanently.

8.1.1

To reproduce, modify the screen layer for any overlay to use "conditional overlay layer", and then use this as the condition (Javascript)

if($prop('GameRawData.Telemetry.IsOnTrack')) {return true;}
else {return false;}

When you get in and out of the car, the overlay will remain in view (provided "hide when not in race is deselected in the overlay layout editor window). I have done this live with the binding window open and observed that the raw result is switching between FALSE and TRUE when out and in the car repsectively.

**Comment by SHWotever** [comment]
Hi !

This is a little misunderstanding, Simhub always display a screen, if none are active it will fallback to the very first available, no matter if it's a layer or anything else.

I've added a dashboard validity check for the next version to clarify this requirement.
