### ISSUE TITLE
[Feature request] Modifiers for Mappings

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1163]
Example Scenario.
You got a button box with an encoder and a button.

Using the button as an upcounting modifier would increase the usage of the encoders .

modifier = 0
encoder right = vocore.next.screen
encoder left = vocore.prev.screen

click on button increases modifier to 1

modifier = 1
encorder right = vocore.next,dashboard
encoder left = vocore.prev.dashboard

and so on. 

If this could be combined with keyboard mappings it would be even better

modifier = 2
encorder right = F1
encoder left = F2

**Comment by twitchexodium** [comment]
To be honest you can do something like this. Even if it’s not that super easy but with JavaScript and Autohotkey you can definitely archived this. I personally use 2 rotary’s. The left one on 1 is just for the car functions and all buttons are for different thing inside the car, if it’s on 2 I use only dash stuff, and the right rotary is then for the different screens of the dash. With the js engine you can build all mappings like you want to have it with the knowledge :)

**Comment by FullPace** [comment]
That might be the case but how many Simhub users know how to code JS and Autohotkey. What makes Simhub great is that you don’t need a programmer‘s degreee to use it ;)

**Comment by twitchexodium** [comment]
That’s definitely true. Just wanna say :)
And I’m a musician without that study programming skills

**Comment by FullPace** [comment]
I get your point. Would you share your code so I can try?

**Comment by SHWotever** [comment]
Hi ! I close this as it's now possible through the control mapper plugin on the latest beta.
