### ISSUE TITLE
[Feature request] Support for PES games

### ISSUE THREAD

**Issue by its999maggle** [SHWotever/SimHub#1166]
Hi,
Will keep it short, we've managed to export variables from pes games in realtime and I can write an API for it.

The plan is to use to for overlays for now. Can't get into much depth here due to it being a private project for now.
Please get in touch with me, I'm in your discord server in the code channel.
Thanks.

**Comment by SHWotever** [comment]
Hi ! 

I'm keeping focused on racing games for now, the previous experiments I did with other games categories (dota, csgo) have shown that there was very very little interest for it unfortunately.
