### ISSUE TITLE
SimHub laggy during AMS2 but ok with Dirt2, was working previously with both Games

### ISSUE THREAD

**Issue by Dreese001** [SHWotever/SimHub#1168]
**Describe the bug**
SimHub appears to be receiving data from the AMS2 but its laggy, where I'm in 6th gear and Simhub is still moving from 3rd to 4th gear and Taco is not responding
SimHub Dash Studio is unusable with AMS2

**Simhub version**
8.1.2

**To Reproduce**
1. Start "AMS2" game
2. Click on 'SimHub' on Android mobile
3. Select 'Favourite Dash Studio' in SimHub
4. Rev the car during game and the tachometer and speedo are not in sync with AMS2

**Expected behavior**
SimHub Dash Studio to be in sync with AMS2

**Log files**
[LapLog.txt](https://github.com/SHWotever/SimHub/files/9848608/LapLog.txt)
[SimHub.log](https://github.com/SHWotever/SimHub/files/9848609/SimHub.log)

**Additional context**
- SimHub dashboard successfully appearing on PC and Android Mobile Phone versions of Simhub

- Both devices are in the same wifi network.

- No issues when using SimHub Dash Studio with Dirt 2

Thanks Team

**Comment by SHWotever** [comment]
Hi !

I see you are using UDP, can you reduce the UDP rate in the game settings sometimes it's drowning the network , reducing the rate (higher value in the game setting) will make it smoother.

Nicolas

**Comment by Dreese001** [comment]
Thanks heaps Nicolas, UDP3 is working smooth as butter on Wifi
