### ISSUE TITLE
CUSTOM SERIAL DEVICE Arduino UNO or NANO old bootL is not responding

### ISSUE THREAD

**Issue by basthard300** [SHWotever/SimHub#1170]
Hi,
 maybe and probably I don't see the error, but my arduino UNO or NANO does not read or does not respond to the reading an  of the any single string.
I state that I am not an expert and therefore I am attaching the code and I hope that someone can help me, long ago it worked, then I lost the data and I am trying to make it go again.
My SIMHUB version on win 11 is 8.1.2

The line of code I entered in SIMHUB is:
**format ([ACCCDS_Physics.abs], '0')**

'#ifndef _SHCUSTOMPROTOCOL_H_
#define _SHCUSTOMPROTOCOL_H_
#include <Servo.h>
#include <Arduino.h>

class SHCustomProtocol {
private:

public:

  int ABS;                                //Name of String
  Servo servo0;                           //Servo Name
  int pos = 0;                            //Start servo Position
void setup() 
{

  //Serial.begin(9600);                   //Opening serial Port
  servo0.attach(11);                    //PIN of PWM servo signal
  pinMode(13, OUTPUT);                  //PIN led ABS Status (ARDUINO ONBOARD LED)

}

void read()

{

int ABS = FlowSerialReadStringUntil('\n').toInt();

  if(ABS == 1);{
    servo0.write (179);                 //TOP servo position (179°)
    digitalWrite (13, HIGH);            //Led ABS Active 
    delay (2);                         //time in (ms)(=servo speed)
    //Serial.println ("ABSACTIVE");       //serial monitor 
}
}

void loop() {
}

void idle() {
}
};

#endif'

the expectation should be simple, the movement of the servo with the change of the incoming signal from SIMHUB!!! 
simply no??

unfortunately I have no logs that indicate errors, nor the log in the window of the CUSTOM SERIAL DEVICE section because nothing returns, not even with the original code in the DisplayClientV2 file.
I tried to reset the COM from regedit, change cables, sketch, but nothing !!
help would be grateful,
Paul

![page1](https://user-images.githubusercontent.com/61467596/198014755-9e352966-23b1-4bfc-82e6-7ef4f141ff46.png)

![page2](https://user-images.githubusercontent.com/61467596/198014776-a59d3a9a-4226-477c-97f4-7ef0bce8c4ff.png)

**Comment by SHWotever** [comment]
Hi At first sight it feels correct, that said the property in use ACCCDS_Physics.abs is not a standard one and comes from a third party plugin. Does this plugin is installed and running ? Can you find that property in the "available properties" tab ? 
Nicolas

**Comment by basthard300** [comment]
First of all thanks for your answer,
I wanted to reiterate that I have tried more than one plugin, both official and unofficial.
I noticed that in the window, running the game, you see the value change over time so I don't know where it gets lost!

I add it stamps I made while playing and the signal goes to 1 repeatedly

the plugin in this monento is precisely
**format ([ACCCDS_Physics.abs], '0')**

so what do I do ??

tks


![page3](https://user-images.githubusercontent.com/61467596/198350740-4ac69a8d-ca47-4b51-ae9d-018f5878da16.png)

**Comment by SHWotever** [comment]
Hi ! 

It looks like there is a mix, the code you sent is about a simhub arduino sketch extension https://github.com/zegreatclan/SimHub/wiki/Custom-Arduino-hardware-support 

But the last screenshot is coming from the custom device (where you have to build yourself the whole sketch ) : https://github.com/SHWotever/SimHub/wiki#custom-serial-devices-support )

If the code is integrated with first method that would explain why it does not work. you need to make sure to disable it in "custom serial devices" so the other feature can catch the arduino (it looks like it was already configured like that in your first screenshot which was showing that the com3 was already in use (by custom serial device)

To take it in order I would 
- Disable the "custom serial device" (top right checkbox, or delete the device)
- Clear the custom formula inside the arduino settings (so your custom code is not triggered) it should connect then if the custom code is faulty.
- Make sure the device is now connecting.
- If its now connecting : try to put back the custom formula
- If it's not connecting : Try to put an original arduino code without your modifications to make sure it's working normally (if you did not save the original empty shcustomprotocol.h file, you can reinstall simhub to restore it)

NB : I also see some delays in your code, delays must be removed as it will block the arduino, 2ms could not be harmless overall, but that could be an issue, original shcustomprotocol.h asks not to use any delays at all.

**Comment by basthard300** [comment]
hi Nicolas,
I don't want to sound repetitive but the situation is this:
and I would like to understand if I did it right.

reset everything;

Sketch loaded on arduino UNO, the default one in the DisplayClientV2 folder
(the version format ([DataCorePlugin.GameData.NewData.SpeedKmh], '0') + ';' + isnull ([DataCorePlugin.GameData.NewData.Gear], 'N '));

set in SIMHUB "Multiple Arduino" in the ARDUINO window, **where I had to turn it off to have it available in the CUTOM DEVICE** section;

![multiplo arduinio](https://user-images.githubusercontent.com/61467596/198817273-be7186e1-bcef-484d-9708-a45a77620b4e.png)

**what's the difference with this type of connection ??? because a different message appears in the "device scan"**

![multiplo arduinio vers 2](https://user-images.githubusercontent.com/61467596/198817315-d61e4d9b-5ae9-4193-a4a1-d6b3145071ef.png)


In the CUSTOM window I entered the code written above and checked only "LOG INCOMING DATA" and "AUTOMATIC RECONNECT";

![custom device](https://user-images.githubusercontent.com/61467596/198817324-6a213c6d-c1c8-49c5-b630-b8000948b60f.png)


The card with, as the frequency varies next to the RULE, flickering on the board, but nothing comes to me in the log.

**WHAT AM I DOING WRONG, IT SEEMS SIMPLE TO ME !!!**

TKS AGAIN

WAITING FOR NEWS

PAUL

**Comment by SHWotever** [comment]
Hi ! 
sorry if i've been unclear,
You are still trying to mix both features,

Make sure to disable first the custom serial device plugin, you don't need it, this feature is intended for full user made sketches which is not your case : 
- Disable totally this plugin as you can't use it for your case ; 
![image](https://user-images.githubusercontent.com/2207331/198819091-e524045c-79db-47f3-8a3b-d8803604546a.png)

- Restart simhub 
- Fill your custom formula inside the arduino custom protocol input of your device : 
![image](https://user-images.githubusercontent.com/2207331/198819240-cf38b958-6b1b-499c-9aab-70a46b96a870.png)

- Click apply changes
![image](https://user-images.githubusercontent.com/2207331/198819459-3f3371fa-b360-4ceb-bd69-65ba494ce662.png)

- The message will now be logged here : 
![image](https://user-images.githubusercontent.com/2207331/198819273-42644687-902a-471d-896f-8498797e244b.png)


The difference about the two features :
- Arduino custom protocol : allows to expand the simhub existing sketch by adding new data exchange, that's your case as you are using the custom protocol feature.
- Custom Serial device : Does not assume it's an arduino, the sketch is totally under end user hand and it simply allows to send data to this serial port. It's not your case here that's why you can't use it, as you are expanding the main simhub arduino sketch and not using your own simple serial device and sketch.

**Comment by basthard300** [comment]
hi Nicolas,
you were right and I'm a donkey
anyway, thanks for the explanation but above all forgive me.
Now let's move on with the design of our haptic pedal with active ABS
See you
Many MANY MANY TKS Dude
