### ISSUE TITLE
DFRobot LCD1602 RGB Backlight Module V1.0

### ISSUE THREAD

**Issue by TankForYou** [SHWotever/SimHub#1171]
I have been trying to connect this display, scanned and tried all ports, used both libraries.
Unfortunately it doesn't work.
Either I am doing something wrong, after countless trials, or its simply not included.
I am running Arduino UNO, with this display module.
Wiring: SCL -> 5 SDA ->4 direct from display to Arduino, since it has as I understand integrated l2c module in it.
I have tested functionality via Arduino IDE, where it works without any problem using DFRobot RGBLCD1602 library:

https://github.com/DFRobot/DFRobot_RGBLCD1602

**Comment by SHWotever** [comment]
Hi !

I close this as I didn't got any other requests for more than year about similar models.

Nicolas
