### ISSUE TITLE
Session identifier changes during an F122 race.

### ISSUE THREAD

**Issue by rubenmamo** [SHWotever/SimHub#1173]
I'm writing a plugin to export specific data of a single race for F1 22 (on XBOX One) using the Sim Hub Plugin. I'm noting that the session id seems to change during some of the races but not all of them. Is there an other identifier that can be used to group a single race together?

My use case is to export specific data for multiplayer races.

**Comment by SHWotever** [comment]
Hi ! The session id is generated by simhub, 
It will change when the game drops connection or at the restart of a race (currentlap/best lap time reset). Unfortunately no games offers such identifier natively so it's approximate and overall it's more a "race" id.

**Comment by rubenmamo** [comment]
Thanks for the reply. Appreciated
