### ISSUE TITLE
WRC Generations Telemetry

### ISSUE THREAD

**Issue by Disco1nferno** [SHWotever/SimHub#1175]
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by Disco1nferno** [comment]
Telemetry is not working in practise mode or the test area. Version 8.1.3

**Comment by SHWotever** [comment]
Hi !

Indeed the game doesn't give telemetry in those modes.

Nicolas
