### ISSUE TITLE
bug in version 8.1.3

### ISSUE THREAD

**Issue by hugodanilosanchezmayorga** [SHWotever/SimHub#1176]
**Describe the bug**
the ws2812 rgb leds at times while I play turn on with higher colors in a rigged way, I have checked the arduino and the rgb light modules and everything is fine, I have downgraded to the previous version of simhub 8.1.2, and the problem is solve but I lose the telemetry of wrc generations, I bought the license and simhub is an excellent software, please solve this bug in the current version 8.1.3, thanks

**Simhub version**
8.1.3
![Screenshot_1](https://user-images.githubusercontent.com/99372898/200467538-dfbcdbad-0939-4ddd-9526-c9dfeb675184.png)

**Comment by SHWotever** [comment]
Hi !

I checked the code and I couldn't find any changes related to the Arduino code. Can you send me the logs when this happens? That could help me to understand wha

**Comment by hugodanilosanchezmayorga** [comment]
ok

**Comment by hugodanilosanchezmayorga** [comment]
after reading your message that they did not find an error in the arduino programming, the only thing that I did not try was to change the USB connection cable and after that everything worked perfectly, that was the big mistake, the USB cable was broken Anyway, I appreciate your prompt response and I congratulate the work you do, keep it up, congratulations and thank you very much for so much fun. bug fixed.
