### ISSUE TITLE
Regarding the issue of missing modules when the dashboard is displayed on the phone.

### ISSUE THREAD

**Issue by chengji668** [SHWotever/SimHub#1177]
**Describe the bug**
When I use my phone to display the simhub dashboard, the pattern information is missing. Version 8.1.3, when playing Eurocard 2, the dashboard works fine on the pc monitor, but when applied to the phone there is a problem that some of the patterns are missing, I have tried uninstalling and reinstalling the file, but the problem still occurs, so I need to ask you for help.
**Simhub version**
Make sure to run the latest version
8.1.3
**To Reproduce**
After importing the dashboard, the preview pattern is the correct pattern. When using it, if it is displayed in the window or auxiliary display, everything is normal, but when it is displayed by scanning the code or entering the URL on the cell phone, part of the pattern is missing, and I have downloaded the app on the cell phone to use it, but I still have the problem.
**Expected behavior**
This dashboard is used in such a way that the phone and computer display the same pattern and no missing, thank you.
**Screenshots**

![image](https://user-images.githubusercontent.com/75066250/201288972-adbce4c8-a240-4460-b9dc-2e4a297b578d.png)
![image](https://user-images.githubusercontent.com/75066250/201289309-8c47cb52-e6e7-4b23-809c-b869680c7abf.png)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
[SimHub.log](https://github.com/SHWotever/SimHub/files/9987939/SimHub.log)
[Logs.zip](https://github.com/SHWotever/SimHub/files/9987947/Logs.zip)

**Additional context**
The dashboard file is too big to upload, if you need the file, please reply me your email, thanks.

**Comment by chengji668** [comment]
[http://192.168.2.33:8888/](url)

**Comment by chengji668** [comment]
![image](https://user-images.githubusercontent.com/75066250/201307611-0af7edaf-ba17-462c-82b9-38fbd005df7e.png)
Connected to the dashboard, thanks.

**Comment by SHWotever** [comment]
Hi ! I mean the dashboard design/template you got installed ;)

**Comment by chengji668** [comment]
How does it need to be done? I am currently opening the dashboard file that is having problems, thanks.

**Comment by SHWotever** [comment]
Hi ! Think it was the same issue as this one (linked to special characters) : https://github.com/SHWotever/SimHub/issues/1289

It has been fixed in the previous releases.

Nicolas
