### ISSUE TITLE
`SHCustomProtocol::read()` message not displaying

### ISSUE THREAD

**Issue by MRVDOG** [SHWotever/SimHub#1178]
**Describe the bug**
Trying to configure my micro controller (NodeMCU ESP2866MODH) with custom code to control my Philips hue lights over wifi that will trigger when in-game events happen, Using the Custom serial devices plugin.
created a custom setting and set that up as an update message, but it's not logging anything.
I added some logs to the `DisplayClientV2.ino` loop
```
...
String test = (String)FlowSerialAvailable();
String str = "Available: " + test;
FlowSerialDebugPrintLn(str);

String test2 = (String)FlowSerialTimedRead();
String str2 = "Read: " + test2;
FlowSerialDebugPrintLn(str2);
```
but no matter what I do, they're always `0` and `-1` (see screenshot)
not sure what I'm doing wrong

**Simhub version**
Simhub v8.1.3 with Custom serial devices

**To Reproduce**
see screenshots

**Expected behavior**
I expect `Available` to be `> 0`
`Read` to be something other than `-1`
and `Message received: no` <-- from `SHCustomProtocol.h`

**Screenshots**
![Reprduction screenshot](https://mrv.sh/0Zy8bnMy.png)

**Comment by SHWotever** [comment]
Hi ! I think you are mixing, custom serial devices are from sketchs built from scratch or any "non arduino" devices.

If you are using simhub sketch you need to disable this plugin (custom serial devices) and set your formula inside the arduino section :
![image](https://user-images.githubusercontent.com/2207331/201487739-ffbcb285-e66b-4e86-af90-df23a1aacfbc.png)

**Comment by MRVDOG** [comment]
hmm, okay, makes sense, will try from there, thank you :)
