### ISSUE TITLE
[Feature request] Rear view mirror support

### ISSUE THREAD

**Issue by BrandonStudio** [SHWotever/SimHub#1179]
**Is your feature request related to a problem? Please describe.**
I'm playing Forza Horizon (4/5), it would be better to have a rear view mirror to see vehicles behind. It seems there is no way to add a custom view in dash studio, is it possible add support to show a mirror content or a custom view content on simhub?

**Describe the solution you'd like**
Add a component to show rear view mirror content.

**Describe alternatives you've considered**
None.

**Additional context**
()

**Comment by SHWotever** [comment]
Hi !

Unfortunately this not possible at all,

It would require to "hack" the game to get a rear view, which above of the technical challenge would probably be considered as a cheat.
