### ISSUE TITLE
[BUG] MapOverlay in a browser, driver position under other drivers.

### ISSUE THREAD

**Issue by Dumedo** [SHWotever/SimHub#1180]
### **Only tested in RF2 and RF2 simhub replay**

**Describe the bug**
If I run standard MapOverlay in windowed mode or any other mode from the thumbnail icon in dashstudio I got my car position over other cars, but if I run the same MapOverlay from a browser or from OBS browser my position is under other cars.

**Simhub version**
Any version as far as I remember, from 2019

**To Reproduce**
1. Go to 'dashstudio'
2. Click on 'the thumbnail icon of the original MapOverlay'
3. Run dashboard in any way you like, windowed or on a monitor, let it run.
4. Then run it again but on a browser, click on "More", "copy OBS browser address.. "
5. Run a replay or start racing with other cars
6. See error: when you are close to other cars the windowed mode shows your car above other cars, when in browser mode your car is under other cars and most of the time you can't see your position.

**Expected behavior**
Browser version should have exactly the same behaviour than the windowed version.

**Screenshots**
Windowed version
![image1](https://user-images.githubusercontent.com/13032033/201516762-1a0a17de-3d98-4395-b8e6-cc0b2e1dab0a.png)

Browser version
![browser](https://user-images.githubusercontent.com/13032033/201516778-168e394e-3447-4f8d-bafb-92f49b53ea49.png)

**Log files**
No log file

**Additional context**
I use the standard Map Overlay on OBS from 2019, and I thought that seeing my car circle under other cars was the normal behaviour.
Then some days ago I saw some streaming where the overlay shows driver car over other cars, it was a direct overlay from SimHub not from OBS. So I did some test and found this bug.

**Comment by SHWotever** [comment]
Hi ! 

The change has been released in the latset version.

**Comment by Dumedo** [comment]
Thank you!!!
