### ISSUE TITLE
Shakelt Bass Shakers

### ISSUE THREAD

**Issue by Davidstoakes** [SHWotever/SimHub#1183]
Hi,
I was using a Buttkicker with SimHub and was working fine. Midway through a race the Buttkicker stopped working. Thinking it was the hardware, I contacted the supplier, and we ran through some test. The Buttkicker worked with other sources. I downloaded the Haptic software and again, the Buttkicker worked.

I have uninstalled the SimHub software and reinstalled, but did not work. I have also reinstalled the previous version of SimHub, but gain it did not work.

Apart from the Buttkicker, SimHub appears to be working fine.

Using current version of SimHub.

**Comment by SHWotever** [comment]
Hi !

Can you give some screenshots of the settings ? 

As a first thought, I would think the audio interface has changed (new usb port, driver update ...) and the audio interface got recognized by simhub as a new one. 

If so you can show disconnected devices here if you need to transfer your settings from the old device : 
![image](https://user-images.githubusercontent.com/2207331/202857924-1f38fdbd-0445-41bf-9633-932d8ccc5d75.png)

**Comment by Davidstoakes** [comment]
Hi,

 

Here is the screen shot as requested.

Something to add to this; I have now found the Buttkicker has started working again, but for some reason at 9PM it stops! When I hit the test tabs on say “road vibration” there is no response from the Buttkicker, but I can hear a noise from my TV. My TV is connected via a HDMI cable.

 

Regards,

 

David

**Comment by Davidstoakes** [comment]
Hi,

 

Another thing to note is when I received the Buttkicker, I only had Simhub, and that was operating the Buttkicker. When it failed I downloaded HaptiConnect and tested it, which it worked. Now if I delete HaptiConnect, Simhub doesn’t make the Buttkicked work. I had to reinstall HaptiConnect to make it work again.

 

Regards,

 

David

**Comment by SHWotever** [comment]
Hi ! This looks like some audio settings not being correct as I first thought. Unfortunately your Screenshot have not been included (it only works directly from the github issue page, not through mails)

Nicolas
