### ISSUE TITLE
ATS Map not complete and requires update

### ISSUE THREAD

**Issue by DopeEx** [SHWotever/SimHub#1184]
**Describe the bug**
On the ATS Map the last extensions Wyoming, Montana and Texas are missing. 

**Simhub version**
8.1.3

**To Reproduce**
Use ETS2/ATS Map component in a dashboard or in Dashboard Studio

**Comment by SHWotever** [comment]
Hi ! Both ets2 and ATS maps have been refreshed with all the latest DLC to date, to reload them you need to click on the following link inside simhub : 
![image](https://user-images.githubusercontent.com/2207331/231162545-09154972-963b-4a0a-893d-fa694f82e47b.png)
