### ISSUE TITLE
[BUG] User.PluginSdkDemo not compiling in Visual Studio Community 2022

### ISSUE THREAD

**Issue by bgoyette** [SHWotever/SimHub#1186]
**Describe the bug**
The provided plugin SDK demo User.PluginSdkDemo does not compile in Visual Studio Community 2022.

**Simhub version**
8.1.3

**To Reproduce**
1. Fresh install of Visual Studio Community 2022
2. Open User.PluginSdkDemo.sln
3. Build

**Expected behavior**
The project should build without errors.

**Screenshots**
![2022-11-27 06_23_25-Window](https://user-images.githubusercontent.com/5952846/204140307-9b0ff1ec-5e13-4dff-9cdb-995e462036a5.png)

**Additional context**
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044

Microsoft Visual Studio Community 2022
Version 17.4.1
VisualStudio.17.Release/17.4.1+33110.190
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

C# Tools   4.4.0-6.22559.4+d7e8a398ef479a908e76bded82150c39251d0c9c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-6.22559.4+d7e8a398ef479a908e76bded82150c39251d0c9c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by SHWotever** [comment]
Hi ! I see indeed that there is a little framework target issue; can you simply retarget the project .net 4.8, this should be enough : 
![image](https://user-images.githubusercontent.com/2207331/204149752-d01a9da8-0f1d-4b1f-9ad4-d81e23a3687c.png)
