### ISSUE TITLE
Leoxz Simbridge makes Simhub crash

### ISSUE THREAD

**Issue by Mattiww** [SHWotever/SimHub#1189]
Simbridge version 1.2.3 makes SImhub 8.1.2 and 8.1.3 crash, only way to get simhub to stop crashing is disableing the plugin.  it crashes ingame or just idleing at desktop with nothing else running. nothing suspicious in the log, except the last rows always simbridge. tried reinstalling simhub completly, and also tried installing on other disk. dont know if this really is your problem, but u might be able to bring some help.

[SimHub.log](https://github.com/SHWotever/SimHub/files/10134528/SimHub.log)

thanks.

**Comment by SHWotever** [comment]
Hi ! Unfortunately simbridge is a third party component where I don't have any control, do not hesitate to contact the developer/manufacturer so they can take a look. Seeing the last change log they seems to be aware of some crashes and have been trying to fix it.

Nicolas
