### ISSUE TITLE
Shake It Bass Shaker may be preventing PC from entering Sleep Mode

### ISSUE THREAD

**Issue by richardckoh** [SHWotever/SimHub#1190]
**Describe the bug**
I have been trying to diagnose why my PC will not enter sleep mode  (currently on Win 11 fully updated, but the problem also existed in Win 10).  When using the command powercfg to see requests being made:

- if Simhub is running, there is a request from the system coming from my USB sound card (I'm not sure if this is the right way to explain it, but I will include screenshots below), and my PC cannot enter sleep mode 
- if Simhub is closed, the request is not present in powercfg, and my PC can enter sleep mode
- if Simhub is open, but I deselect the USB sound card from the ShakeIt Bass Shaker / Sound Output / Output Selection menu, the request is not present in powercfg, and my PC can enter sleep mode.

I'm not the most technically knowledgeable person when it comes to this stuff, and basically just rely on my Google searching skills and following basic troubleshooting guides, but it seems to me that the ShakeIt Bass Shaker plugin seems to be making constant requests (?) from my sound card preventing Windows from allowing my monitors to turn off and PC entering sleep mode.

I'm not sure if this is a bug or maybe it's more of a request, but would there be a way to prevent these requests from happening while Simhub is running? I would like to be able to keep Simhub running and for my PC to go to sleep if possible for convenience's sake.

**Simhub version**
8.1.3

**To Reproduce**
See above description

**Expected behavior**
I can leave Simhub running without having to deselect the soundcard I use for the ShakeIt Bass Shaker plugin and have my PC able to enter sleep mode.

**Screenshots**
See attached files

**Log files**
Not sure if applicable

**Additional context**
![Screenshot 2022-12-03 143754](https://user-images.githubusercontent.com/119720911/205426150-5bea5a63-9bcd-4fbc-bc52-8974a45ccddb.png)
![Screenshot 2022-12-03 143840](https://user-images.githubusercontent.com/119720911/205426151-b9ce8e14-8320-47b3-b212-5ac82f637640.png)

**Comment by SHWotever** [comment]
Hi ! Indeed windows will suspend sleep when audio is in use which is the case when bass shakers audio is active.

I will look if i can improve it by adding a sleep mode inside the audio interfaces.
