### ISSUE TITLE
Problème couleur des leds sur cube control CSW3

### ISSUE THREAD

**Issue by Patfev** [SHWotever/SimHub#1192]
![20221211_183732](https://user-images.githubusercontent.com/120331002/206919772-5c9be7b7-3bb4-47a7-9fc9-5dc0c6a44bea.jpg)
**Describe the bug**
https://discord.com/channels/299259397060689920/306850631271055362/1051535557378986104
**Simhub version**
Make sure to run the latest version
8.01.3
**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by Patfev** [comment]
[Any Game - Pat ledsprofile.txt](https://github.com/SHWotever/SimHub/files/10202847/Any.Game.-.Pat.ledsprofile.txt)

**Comment by Patfev** [comment]
Bonjour, merci pour ton retour.Je n'ai pas l'impression que ce soit matériel car les leds sont bien blanches dans l'éditeur de données de test.
Peu être est ce le firmware de la roue qui pose problème?
![20221211_181539](https://user-images.githubusercontent.com/120331002/207053126-7a01a0ad-63ec-48b2-adba-8dc23bc9c81d.jpg)

**Comment by SHWotever** [comment]
Ah je viens de le voir, dans le profil les leds étaient en effet bleutées ce qui rendait "blanc", mais en mettant un blanc "pur" elles virent au rose. Clairement le composante rouge est trop forte comparée au deux autres (bleu/vert) . J'ai vérifié il n'y a pas de défaut coté "communication" c'est le matériel qui malheureusement déforme la couleur. Il  y avait bien une MAJ du firmware do volant qui doit améliorer la qualité des couleurs : https://www.cubecontrols.com/csx-3-and-f-pro-firmware-version-25-10-2022-patch-note/

![image](https://user-images.githubusercontent.com/2207331/207058360-54ee24c2-cb1d-486b-bcb3-33fd00de56d2.png)

Malheureusement ce n'est pas beaucoup mieux, je pense qu'il faudra attendre une nouvelle MAJ du firmware. 

Nicolas
