### ISSUE TITLE
[Feature request] Contrast control for USB screens

### ISSUE THREAD

**Issue by RodentYell** [SHWotever/SimHub#1194]
Is it at all possible we could have a contrast setting slider to run along the brightness one? have recently brought a latest version of a vocore screen which appears to have the brightness turned up now but it looks like the contrast has as well, so when turning the brightness down the black colours dont really go a dark black so a contrast slider would solve this.

**Comment by SHWotever** [comment]
Hi ! I've added a contrast control however reducing contrast makes things grayish, it works good for increasing it but it won't be of much help to reduce it (unless it's only very few %)

**Comment by RodentYell** [comment]
Thank you
