### ISSUE TITLE
Ambient light via Bluetooth - Object reference error

### ISSUE THREAD

**Issue by innoculis** [SHWotever/SimHub#1195]
I understand this feature is experimental, I still thought this should be documented.  Using the same bluetooth flood light described in the wiki, I can connect to it without issue.  It connects, changes its color, but then it drops its connection (green line goes red) and it fails to respond to changes onscreen.  It red line will blink green sometimes when changing between enabling/disabling live preview. Looking in the log, I see this repeatedly:

ERROR - System.NullReferenceException: Object reference not set to an instance of an object.
   at Simhub.Plugins.SimuLight.SimuLightPlugin.UpdateAreas(IAreaContainer areaBuilder, Bitmap capture)
   at Simhub.Plugins.SimuLight.SimuLightPlugin.ProcessBluetooth()
   at Simhub.Plugins.SimuLight.SimuLightPlugin.ProcessCapture()
   at Simhub.Plugins.SimuLight.SimuLightPlugin.Worker()
   at Simhub.Plugins.SimuLight.SimuLightPlugin.Gl_Elapsed(Object sender, ElapsedEventArgs e)
   at GameReaderCommon.GameLoop.MainLoop()
   
I removed any pairings, restarted my PC, reinstalled bluetooth drivers (BT does support BT5 and BLE), updated SimHub from 8.1.2 to 8.2, nothing made a difference.  It makes no difference whether I am in a live preview, a game, or in standby, the light does not react.

**Simhub version**
8.2.0 happend on 8.1.2 as well.

**To Reproduce**
Connect SHOPLED 15w RGB floodlight, and watch it drop right away.

**Expected behavior**
Expected to change colors along with the referenced area selected on the display, but nothing happens.

**Screenshots**
![BTscan](https://user-images.githubusercontent.com/109486502/209251133-bd6fe692-d6d8-44f4-9a6b-68f565b174a7.png)
![connected](https://user-images.githubusercontent.com/109486502/209250855-9e74a921-2cdf-4d56-a910-0e6b5820e8fc.png)

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/10291254/SimHub.log)
[bluetooth.log](https://github.com/SHWotever/SimHub/files/10291263/bluetooth.log)

**Additional context**
Please let me know if I can get any more info about this issue to you.  Thank you!

**Comment by SHWotever** [comment]
Hi !

It looks like the screen capture can't start (not properly handled I admit it), I see that you have some obs related things, I know that you only have a limit about how many screen captures you can run at the same time. Could you check when obs and any other capture softwares are not running ? I feel like the issue is about this capture limit.

Nicolas
