### ISSUE TITLE
Problems getting property with PluginManager.GetPropertyValue()

### ISSUE THREAD

**Issue by andreasdahl1987** [SHWotever/SimHub#1197]
My plugin uses this method quite a lot. Set up like this:
![image](https://user-images.githubusercontent.com/40788634/209409160-68a9b231-38e7-4bba-873d-2549534cf5ce.png)

And then here, I use it to try to find a controller, looking for the Z axis property that the JoystickPlugin creates. 
![image](https://user-images.githubusercontent.com/40788634/209409189-f107c678-6262-4337-81d4-ecb41b4cf014.png)

Base.Settings.DDC gets its value from here:
![image](https://user-images.githubusercontent.com/40788634/209409261-a14c5b65-759b-481f-a458-4d33372b130a.png)

The point of finding a controller is that my firmware uses some of the joystick axis as bit fields to send information to simhub. My plugin extracts the info from the bit fields and makes properties. 

The problem is that this sometimes doesnt work. I have 1 controller that is named Arduino_Leonardo in the joystickPlugin properties, and that one works. Another controller is called SparkFun_Pro_Micro, and that one is never found. The properties are there in simhub with values and all...but my plugin returns null when trying to get this Z axis property. The same controller flashed using a leonardo board core...and it works (since it now is named Arduino_Leonardo)! 

I have no clue why this is happening. Have you got an idea?

**Comment by andreasdahl1987** [comment]
@SHWotever Maybe a better approach would be to get direct access to the data in the joystick plugin. Is this possible with the plugin manager? 

Andreas

**Comment by SHWotever** [comment]
Hi ! I need to take a look. I recently worked on this though, and I think I understand the issue. 

Controller discovery is asynchronous to avoid locking simhub during the device scan (which can be slow depending of the load and devices, typical is around 500ms, which is a long time) I even gave it a few additional seconds before it starts to give more room to mandatory features during startup.
That means that indeed the data won't be here in the first data updates, but after a few seconds it should come.

**Comment by SHWotever** [comment]
I added this new method for the next version : 

![image](https://user-images.githubusercontent.com/2207331/231403563-e6b8fde4-ac66-49fd-8cb4-257399b02ac1.png)

It reports the value straight from the plugin internals.
To use the laststate value which gives the complete joystick state, you will need to add a reference to both SharpDX.dll and SharpDX.DirectInput.dll as well as ACToolsUtilities.dll

**Comment by andreasdahl1987** [comment]
Halleluja!

**Comment by andreasdahl1987** [comment]
Was this added in the release on 13th of april? Couldnt find it in the patch notes and couldnt find the method either.

**Comment by SHWotever** [comment]
Hi ! Yes it was, since it was a last minute change and since I'm not available this whole week I preferred to avoid advertising it in the change log.
I checked using the latest version i got it without troubles, does the reference to simhub.plugin dll is up to date ? If you are using a separate copy you probably need to refresh it. In theory on a fresh SDK it's done to use the latest one using a relative path but you might have reconfigured it.
pluginManager.GetConnectedGameControllers()

**Comment by andreasdahl1987** [comment]
I'll update the reference and give it another go :)

**Comment by andreasdahl1987** [comment]
Working after refreshing the simhub.plugin.dll :D Awesome!

**Comment by andreasdahl1987** [comment]
Closing as the issue has been resolved with the added method.
