### ISSUE TITLE
Simhub freezes with Simbridge in use

### ISSUE THREAD

**Issue by deeply1985** [SHWotever/SimHub#1198]
**Describe the bug**
Bought the Leo Xf1 Sport Wheel which uses Simbridge as simhub plugin. Everytime i use it Simhub freeze several times while using the wheel. Simhub tries to connect and reconnect the wheel often during use. attached in the logs .

**Simhub version**
8.1.3

**To Reproduce**
Use the wheel and go ingame, in this case iRacing. 

**Expected behavior**
Help even it is difficult :)

**Screenshots**

**Log files**
[SimHub Logs.zip](https://github.com/SHWotever/SimHub/files/10298134/SimHub.Logs.zip)

**Additional context**
The behaviour just happen if iam in the game. If i use it just in windows simhub dont freeze.

**Comment by SHWotever** [comment]
Hi !

Unfortunately I can't fix third party plugins, I don't have the source code or the actual device to test. But indeed the logs always shows it dies in the plugin

Do not hesitate to contact the manufacturer so they can investigate it
