### ISSUE TITLE
Incorrect  or missing GameRaw.Data.Telemetry.LatAccel, LongAccel, and VertAccel

### ISSUE THREAD

**Issue by thogue95** [SHWotever/SimHub#1199]
Some people have been reporting to me that their version 8.1.3 was showing System.single[] as values returned for GameRaw.Data.Telemetry.LatAccel, LongAccel, and VertAccel as shown in the attached image.  

After having them upgrade to 8.2.0, GameRaw.Data.Telemetry.LatAccel, LongAccel, and VertAccel are all missing as shown in the attached image.  When I I personally upgraded to 8.2.0 and those variables are showing correctly in my Available Properties so it appears for some reason sometimes those properties are not showing up.

Game that is supplying those properties is iRacing.

![SimHub Error Markup](https://user-images.githubusercontent.com/8271391/209436220-dd7f33de-ab70-41d7-bf18-bd51d4137bf4.png)

![SimHub Missing Properties in 8-2-0](https://user-images.githubusercontent.com/8271391/209436247-68cd20a6-f6fb-4c47-9bea-3af93bd86e31.png)

**Comment by SHWotever** [comment]
Hi ! If I'm not wrong those values gets reported as arrays when you have 360hz telemetry enabled, simhub does not supports it directly. Could you check that your game settings do not have this feature enabled? https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#iracing

**Comment by thogue95** [comment]
Thanks for the fast response.  Will update when I get answers from the people I am helping.  Merry Xmas!

**Comment by thogue95** [comment]
Configuration error.  Not a bug.

**Comment by thogue95** [comment]
Closing and reopening with a more concise description of the issue.
