### ISSUE TITLE
Shakeit wind : Idle goes from 0 to value

### ISSUE THREAD

**Issue by dureiken** [SHWotever/SimHub#1200]
Hi, I have a problem with my arduino and pwm fan control : when I launch simhub, without game, idle wind is appllied and works, but it goes constantly from 0 to the value I use, instead of staying at 30% for example. 

More strange : if I launch once a ride on NoLimits 2, when exiting the game it works fine ! idle stays at 30%

thanks for your work and help

**Comment by SHWotever** [comment]
Hi ! 

30% is often the low stop limit on many PWM fans, obviously it depends of the fan itself. Can you try to set it higher ? Exiting a game could be enough to have trigerred fan start and getting it holding up at 30 %.
