### ISSUE TITLE
8.2.0 DataCorePlugin not presenting GameRawData.Telemetry.LatAccel, LongAccel, VertAccel

### ISSUE THREAD

**Issue by thogue95** [SHWotever/SimHub#1202]
I have several people that are experiencing DataCorePlugin not presenting GameRawData.Telemetry.LatAccel, LongAccel, VertAccel.  They saw this prior to upgrading to 8.2.0 and after.  Had them make sure they did not have 360Hz Telemetry logging enabled.   One did have it enabled but had them change it to disabled.   I had them follow the Light Reinstall on the SimHub Troubleshootings wiki page but no help.

 I have 8.2.0 installed on my computer and it shows up as expected.

**Simhub version**
Version 8.2.0

**Screenshots**
![SimHub Missing Properties in 8-2-0](https://user-images.githubusercontent.com/8271391/210014834-5e9c523e-215a-4619-8a46-d426738c00fc.png)

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/10322249/SimHub.log)

**Additional context**
iRacing app.ini file

[iracing-app-ini.txt](https://github.com/SHWotever/SimHub/files/10322258/iracing-app-ini.txt)

**Comment by SHWotever** [comment]
Hi ! 

That's strange, as is I can't reproduce it, I will investigate and eventually force it, iracing is a bit specific with no specific telemetry list and constantly changing.
Alternatively you can use the "standard" game data heave sway surge which are extracted and normalized accross all games (when available), on your screenshot it appears to be working (meaning the underlying data is available), The only difference being Heave which has gravity removed (-9.80665) compared to the original game reported value.

**Comment by thogue95** [comment]
Thanks for looking.  I will give heave, sway and surge a try.  Are those units in m/s^2?

**Comment by thogue95** [comment]
I was able to get my overlays working perfectly using the existing heave, surge and sway.  I would suggest those are sufficient and not worth any time to investigate.  Thanks again for the response that got me up and running.
