### ISSUE TITLE
Cannot anymore access to Arduino Sketch setup

### ISSUE THREAD

**Issue by TipiCaribou31** [SHWotever/SimHub#1203]
**Describe the bug**
Cannot anymore access to the tool to configure manually my arduino.
I already configure it once with an oldest version. I update Simhub, connect my arduino, and I cannot anymore access to the sdketch configurator, choosing my material and upload code to my arduino

**Simhub version**
8.2.0

**To Reproduce**
1. Go to 'Arduino'
2. Click on 'My devices' tab
3. Click on 'Open Arduino config tool'
4. the page load and stop here, I,m back on the previous page 'My devices'

**Expected behavior**
Select if I want to start from beginning or start an old configuration

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

[SimHub.log](https://github.com/SHWotever/SimHub/files/10327985/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! Sorry for the very late response, have you tried to reinstall simhub in order to get back a fresh sketch ? I feel like the sketch got corrupted and the setup tool is not capable of reading it, simply crashing when starting.
