### ISSUE TITLE
GT7 Data mapped to wrong property

### ISSUE THREAD

**Issue by etsmc** [SHWotever/SimHub#1206]
It appears that the tyre temperature data coming from the game is mapped to 
DataCorePlugin.GameData.TyrePressureFrontLeft
DataCorePlugin.GameData.TyrePressureRearLeft
DataCorePlugin.GameData.TyrePressureRearLeft
DataCorePlugin.GameData.TyrePressureRearRight

According to this, tyre pressure is not output
https://www.gtplanet.net/forum/threads/gt7-is-compatible-with-motion-rig.410728/post-13799643

Is it possible to re-map the data to the following?
DataCorePlugin.GameData.TyreTemperatureFrontLeft
DataCorePlugin.GameData.TyreTemperatureFrontRight
DataCorePlugin.GameData.TyreTemperatureRearLeft
DataCorePlugin.GameData.TyreTemperatureRearRight

**Comment by SHWotever** [comment]
Hi ! 

Thanks for the report ! 
It's fixed for the next release .

Nicolas
