### ISSUE TITLE
[Feature request] - "IsInPitLane" properties - Persistant tracker

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1209]
Hi,
Could you please add "IsInPitLane" properties for the persistent tracker ahead/behind drivers ?
This would be useful for relative leaderboards (to grey out their lines) and radars (filtering them out).
Thanks for considering the idea.

**Comment by SHWotever** [comment]
Hi ! I took a look, but "ahead and behind" properties already filters people being in pit lane or in pits (when the data is available) Those data are relative to an "on track" status, just showing people in front and behind of you on the track no matter if they lapped you or not.

**Comment by herve4545** [comment]
Hello
Ce sujet m'intéresse aussi
Personnellement, je n'ai pas vu d'information indiquant si un des ahead/behind est dans les stands. Quelle est le nom de ce paramètre ?
Rien vu de tel sur R3E, RF2 ou AMS2
Merci

**Comment by SHWotever** [comment]
Hello ! C'est normal car les ahead/behind sont filtrés, si ils sont dans les stands ou la ligne de stands ils ne sont pas dans liste donc l'information ne sert à rien ici. Si jamais le jeu ne donne pas l'info par contre pas moyen de filtrer, et comme précédemment l'info ne servirait à rien car manquante de toute facon.

**Comment by herve4545** [comment]
Sauf erreur de ma part....dans R3E et RF2, les voitures dans les stands apparaissent dans les ahead/behind. Je les vois s'afficher sur mon dash où j'affiche les 5 ahead/behind

Perso, je ne connais pas de jeu où ces 5 ahead/behind sont filtrés dès lors qu'ils sont aux stands

J'espère avoir été clair :)

**Comment by cicci8ino** [comment]
> Hi ! I took a look, but "ahead and behind" properties already filters people being in pit lane or in pits (when the data is available) Those data are relative to an "on track" status, just showing people in front and behind of you on the track no matter if they lapped you or not.

If possible, it would be interesting to add another parameter to OpponentAtPosition function 
data.NewData.OpponentAtPosition(int position, bool relativeToPlayer, bool positionOnTrack, bool playerClassOnly, bool filterInPitlane). If people are entering/exiting the pitlane or serving a pit, I would not exclude from the list a priori.

**Comment by Romainrob** [comment]
> Hi ! I took a look, but "ahead and behind" properties already filters people being in pit lane or in pits (when the data is available) Those data are relative to an "on track" status, just showing people in front and behind of you on the track no matter if they lapped you or not.

Hi, that's actually how I remembered it working for iRacing.
A least when working on a plugin with
OpponentsAheadOnTrack
OpponentsBehindOnTrack
OpponentsAheadOnTrackPlayerClass
OpponentsBehindOnTrackPlayerClass

But the PersistantTrackerPlugin.DriverAhead/Behind_XX properties don't seem to behave the same.

Here for example:
![image](https://user-images.githubusercontent.com/50543913/220364793-7cd1fee5-8369-4542-8e2e-13e97d79014d.png)

Jesse is in the pits. He doesn't appear on the relative using my plugin. OpponentsBehindOnTrack seems to filter him out.
But he appears in the PersistantTrackerPlugin.DriverBehind_00 properties
The same goes for Roland and Maxim a few seconds later.

**Comment by cicci8ino** [comment]
I can confirm this. I'm using PersistantTrackerPlugin data because I don't
need people in the pitlane to be filtered out.

Il mar 21 feb 2023, 15:01 Romainrob ***@***.***> ha scritto:

**Comment by SHWotever** [comment]
Hi ! I fixed the filter for the next version, indeed properties were coming from an unfiltered view :(
