### ISSUE TITLE
"ACC" valeurs AllTime et BestTime affichent les temps même si invalides.

### ISSUE THREAD

**Issue by Nada1414** [SHWotever/SimHub#1210]
Les valeurs PersistantTrackerPlugin.AllTimeBest, DataCorePlugin.GameData.AllTimeBest, DataCorePlugin.GameData.Sector1BestLapTime, DataCorePlugin.GameData.Sector1BestTime (+secteur 2 et 3) ne tiennent pas compte si le tour est valide.
Merci

**Comment by SHWotever** [comment]
Hello !

MErci pour le feedback ! C'est corrigé dans la dernière version !

**Comment by Nada1414** [comment]
Merci pour ce super soft.
