### ISSUE TITLE
GT7 Map: Waiting for valid lap

### ISSUE THREAD

**Issue by Bob2345de** [SHWotever/SimHub#1212]
Firstly, many thanks for such a great app and for integrating GT7!  Total game changer for PS5 users....

I have included a Dynamic Map element on a dashboard, but no matter how many laps I drive on any track (have tried 4) the data doesn't seem to get captured. The frame on the dash says "waiting for valid lap" (or similar). I do notice that that text blinks once when starting a new race, but nothing else happens (empty frame).  Is this due to missing data in the GT7 telemetry stream, or should this work? Also, have tried offline online map settings in the dashboard setup with no noticable difference.

Shakeit Wind and Bass Shaker setups are working fine, so I don't think it's a general connectivity issue.

Am using the lastest version as of today and it is licensed.

Thanks again!

**Comment by SHWotever** [comment]
Hi ! Unfortunately gt7 and GTsport does not give any information about the current track name/Id/length preventing to generate a map.

**Comment by Bob2345de** [comment]
Thought that that might be it!. We should be happy with what we have!
Best regards
