### ISSUE TITLE
Simhub Closing by itself after minimized 

### ISSUE THREAD

**Issue by tiagomacedo88** [SHWotever/SimHub#1213]
**Describe the bug**
Simhub is closing by it self after minimized. I can do everything that I need with the Simhub while it`s open, but if minimize it and maximize it again, the Simhub just closes by itself. 

**Simhub version**
8.2.1

**Expected behavior**
I expect to minimize the simhub and when open it gain, the Simhub would just work as fine.

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
[SimHub.log](https://github.com/SHWotever/SimHub/files/10480115/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! Could you give all the log files available in the folder adter it happens ? Unfurtunately this log did not gave information about the issue.

**Comment by tiagomacedo88** [comment]
Hi there,
Please find the log file from today. I have simulated the issue 3 times. Please let me know if you can see it now on the logs.
[SimHub.log](https://github.com/SHWotever/SimHub/files/10545619/SimHub.log)

**Comment by SHWotever** [comment]
hi ! I fixed something which could be related recently, in the meanwhile I did not had any other reports so I guess it's more a contextetual issue (other overlay software etc ..) I close it but do not hesitate to tell if somehow you still have the issue on latest version.
