### ISSUE TITLE
[Feature request] Add ability to control rev LEDs on Thrustmaster 488 Challenge Edition wheel

### ISSUE THREAD

**Issue by RevanProdigalKnight** [SHWotever/SimHub#1214]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to control the rev LEDs on my Thrustmaster 488 Challenge Edition wheel using SimHub because it has the best documented scripting environment of all the solutions I've tried, which will allow me to circumvent some bugs that I've encountered in some games' telemetry.

**Describe alternatives you've considered**
I have considered writing my own plugin for SimHub, but haven't really had time to look for documentation or configuration of a project beyond browsing a bit through the [SimHub SLI Plugin](https://github.com/simelation/simhub-plugins/tree/main/packages/simhub-sli-plugin) repository. I'm sure given time I could do it, but it won't be any time soon.

**Comment by SHWotever** [comment]
Hi !

Unfortunately I wished for a long time to add support for it, but impossible to find the separate wheel in order to test it and do the required reverse engineering, making it impossible to support it. 

Nicolas

**Comment by RevanProdigalKnight** [comment]
Yes, it's quite annoying that Thrustmaster has decided not to offer the wheel separately from the TS-PC servo motor, even though I'm pretty sure that would increase their sales. I guess I'll start developing a plugin when I have time.

**Comment by RevanProdigalKnight** [comment]
Responding for those who search in the issues and find this - I have created a [plugin](https://gitlab.com/prodigal.knight/simhub-thrustmaster-wheel-led-controller)
