### ISSUE TITLE
Simhub always reverts to un-configured state when opening or running F1 2021 

### ISSUE THREAD

**Issue by Binto100** [SHWotever/SimHub#1215]
Simhub version 8.2.1, new computer.  I had this same problem on the prior machine with f1 2021.  I configure f1 2021 in Simhub, but the instant I go into the f1 2021 sim, Simhub reverts to a non-configured state and will not drive my Vcore screen.  It works perfectly on PC2 and I have not tried it in ACC.

**To Reproduce**
1) Start Simhub and configure f1 2021
2) Start F1 2021 and check Simhub.  Note that Simhub has returned to an un-configured state.
3) Reconfigure Simhub and go back into f1 2021 sim.  Simhub instantly reverts to an un-configured state.
4) Pull hair out.

Steps to reproduce the behavior:  Behavior does not change, Simhub always reverts to an un-configured state when running f1 2021.

**Expected behavior**
I expect Simhub to stay configured and run dashboards on my Vcore screen when in f1 2021

**Screenshots**  None.

**Log files**.  See below.
Add any other context about the problem here:  please note I had to change the log files and add an extension.
[SimHub.log_5.log](https://github.com/SHWotever/SimHub/files/10493419/SimHub.log_5.log)
[SimHub.log_4.log](https://github.com/SHWotever/SimHub/files/10493420/SimHub.log_4.log)
[SimHub.log_3.log](https://github.com/SHWotever/SimHub/files/10493421/SimHub.log_3.log)
[SimHub.log_2.log](https://github.com/SHWotever/SimHub/files/10493422/SimHub.log_2.log)
[SimHub.log_1.log](https://github.com/SHWotever/SimHub/files/10493423/SimHub.log_1.log)

**Additional context**
Thank you.

**Comment by SHWotever** [comment]
Hi ! Looking at the logs I see that the games is properly configured from time to time. Currently simhub never changes the game settings file until you click on configure, 

I tested with the steam version, even after the games rewrites the config files it stays configured and is recognized correctly.
Which game version are you using (steam, Game pass ...) ? 

As is I would think another application does reconfigure the game for it's own need without asking you, actually making simhub say the game is not configured anymore (for its own needs).
Can you send the following file after it gets "unconfigured" , and before reconfiguring it in simhub ? 
![image](https://user-images.githubusercontent.com/2207331/214520947-feaf4be3-d747-415c-af57-90c091705ed2.png)


It will allow to show if it's simply a bad detection or if the telemetry settings are totally different (pushing in the way of another app changing it)

**Comment by Binto100** [comment]
Greetings and thanks for your quick reply.

 

The file you requested is attached.

 

I run SRS (SimRacingStudio) for my PT platform and it has a supported games feature/configure section also; F1 2021 also becomes unconfigured at the same time as Simhub.

 

The way to this file was:

Open F1 2021 on SRS and configure.

Open Simhub and configure F1 2021 (allow Simhub to configure).

Launch F1 2021.

End of fun.

 

If I shut down SRS while F1 is open and go to SH it will again say it needs to be configured.  I configure it and as soon as I launch F1 it goes back into an

unconfigured state.

 

I note under graphics cards in the xml file it says: 

<resolution width="3840" height="1080"

But I’m running a Samsung 49” which is 5120 * 1440.  I changed the xml file for the correct resolution with no improvement. 

 

Appreciate your thoughts.  Thanks.  I also included the other two files in the directory.

 

Bruce

**Comment by Binto100** [comment]
﻿Sorry forgot to say I use Steam.BruceSent from my iPadOn Jan 25, 2023, at 2:00 AM, Wotever ***@***.***> wrote:﻿
Hi ! Looking at the logs I see that the games is properly configured from time to time. Currently simhub never changes the game settings file until you click on configure,
I tested with the steam version, even after the games rewrites the config files it stays configured and is recognized correctly.
Which game version are you using (steam, Game pass ...) ?
As is I would think another application does reconfigure the game for it's own need without asking you, actually making simhub say the game is not configured anymore (for its own needs).
Can you send the following file after it gets "unconfigured" , and before reconfiguring it in simhub ?

It will allow to show if it's simply a bad detection or if the telemetry settings are totally different (pushing in the way of another app changing it)

**Comment by SHWotever** [comment]
Hi ! Mostery solved ;) So it's perfectly normal, the game can only be configured to have one "receiver" either simhub or srs. You can configure an UDP redirection in one of the app you will choose as a master (I think srs offers it too) then do not "configure" telemetry in the secondary app and let it receive telemetry through this redirection  : https://github.com/SHWotever/SimHub/wiki/Sharing-UDP-data-with-other-applications

If you choose srs as a master you have a "don't ask me again" button in simhub to ignore the game configuration which doesn't matter anymore if telemetry is forwarded by another application.

**Comment by Binto100** [comment]
Thank you so much!  I will give that a go this morning. BruceSent from my iPadOn Jan 25, 2023, at 10:57 PM, Wotever ***@***.***> wrote:﻿
Hi ! Mostery solved ;) So it's perfectly normal, the game can only be configured to have one "receiver" either simhub or srs. You can configure an UDP redirection in one of the app you will choose as a master (I think srs offers it too) then do not "configure" telemetry in the secondary app and let it receive telemetry through this redirection  : https://github.com/SHWotever/SimHub/wiki/Sharing-UDP-data-with-other-applications
If you choose srs as a master you have a "don't ask me again" button in simhub to ignore the game configuration which doesn't matter anymore if telemetry is forwarded by another application.

**Comment by Binto100** [comment]
﻿👍🏻Worked perfectly after a couple false starts.  SRS said it wasn’t configured but I was confidant of the forwarding and listening addresses so I just ignored it and off we went. Thanks again, that is excellent service.BruceSent from my iPadOn Jan 25, 2023, at 10:57 PM, Wotever ***@***.***> wrote:﻿
Hi ! Mostery solved ;) So it's perfectly normal, the game can only be configured to have one "receiver" either simhub or srs. You can configure an UDP redirection in one of the app you will choose as a master (I think srs offers it too) then do not "configure" telemetry in the secondary app and let it receive telemetry through this redirection  : https://github.com/SHWotever/SimHub/wiki/Sharing-UDP-data-with-other-applications
If you choose srs as a master you have a "don't ask me again" button in simhub to ignore the game configuration which doesn't matter anymore if telemetry is forwarded by another application.

**Comment by SHWotever** [comment]
Nice ! Thanks for the feedback !
