### ISSUE TITLE
Replay button not working sometimes

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1216]
**Describe the bug**
Hi,
This one has been going on for while but I never was able to reliably replicate it.
At times the replay buttons on the top right stop working. Nothing happens when clicking "Replay".
It can be frustrating when working on a dash, having to close everything and restart SimHub to start a replay.

**Simhub version**
8.2.1 and some previous versions.

**To Reproduce**
I'm not sure.
I mainly notice this when the dash editor is open, and most often right after changing game.
But it could be a coincidence.

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/10500001/SimHub.log)

Good hunting!

**Comment by Romainrob** [comment]
Actually, I just played with it a little and I can break it at will now :D
1. Start SimHub
2. Click replay
3. Click cancel
4. Click replay again and nothing happens

**Comment by SHWotever** [comment]
Hi ! Indeed the "cancel" was the key, when the replay window is opened the replay buttons are disabled and were enabled back at closing, the cancel button was escaping it :D

**Comment by Romainrob** [comment]
Nice! I'm glad to here you fixed it :D
