### ISSUE TITLE
Rfactor 2 - vocore et la lettre ü

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1217]
Hello
cette lettre semble poser problème à vocore ou simhub 
dans rf2, il y a un pilote qui s'appelle Ammermüller en Porsche Cup 992
La lettre ü ne s'affiche pas correctement sur mon dash vocore
si j'ajoute un texte avec la lettre ü ou Ü en dur, cela s'affiche correctement
[_HERVE_MY_DASH_1_FULL+.zip](https://github.com/SHWotever/SimHub/files/10507192/_HERVE_MY_DASH_1_FULL%2B.zip)
![3](https://user-images.githubusercontent.com/58605557/214782142-bf5e16de-9762-479e-9629-b9371b6e82a6.jpg)

**Comment by SHWotever** [comment]
Hello ! Je pense que c'est l'extracetion depuis le jeu ... je regarde çà !

![image](https://user-images.githubusercontent.com/2207331/214783341-d2a93a37-5016-4ee6-a286-dc7d3f4408cb.png)

**Comment by herve4545** [comment]
j'affiche le nom du pilote avec cette commande
apparemment, cette command poserait problème

var driverBehindRaw = $prop('PersistantTrackerPlugin.DriverBehind_02_Name');

return (driverBehindRaw == null) ? '----' 
: driverBehindRaw[0] + '. ' + driverBehindRaw.substr(driverBehindRaw.indexOf(' ') + 1, 
driverBehindRaw.length);

**Comment by SHWotever** [comment]
Je pense que ca viens de "plus haut" lors de la lecture des données depuis le jeu. Comme tu l'as montré la propriété est déja "foireuse" et elle ne passe pas par ton script. En tout cas c'est completement de mon coté ;)

**Comment by herve4545** [comment]
test OK avec 8.2.2 :+1:
