### ISSUE TITLE
Automobilista 2 and Project Cars 2 won't configure

### ISSUE THREAD

**Issue by Shiveeno** [SHWotever/SimHub#1218]
I followed all the instructions but the games will not configure and it opens up and detects when a race has started.

Version: 8.2.1

I have restarted the application and my pc multiple times, but there is no troubleshooting help for these games.

Here's log since it won't let me send the file
<HTML>
<BODY>
<TABLE><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.SystemInfosProvider plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.AudioControl.AudioControlPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.Devices.DevicesPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.AudioControl.AudioPlayPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.InputPlugins.JoystickPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Starting Arduino in Single USB mode</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Matrix custom font custommatrixfont8x8 loaded</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.Web.WebPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Plugin manager correctly initialised</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Loading plugins controls</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>JoystickManager : Starting game controllers detection</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Game successfully loaded</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>JoystickManager : Found Logitech_G_HUB_G29_Driving_Force_Racing_Wheel_USB</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>JoystickManager : End of detection</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>(Re)Starting CodemastersGridLegends Game Manager and plugin manager</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping old game manager</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping old plugin manager</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.DataPlugins.SystemInfosProvider</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.DataPlugins.SystemInfosProvider plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.SystemInfosProvider</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.AudioControl.AudioControlPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.Devices.DevicesPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.AudioControl.AudioPlayPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.Shell.ShellPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.InputPlugins.JoystickPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.Web.WebPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopped all plugins</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating Codemasters Grid Legends game manager (CodemastersReader.CodemastersGridLegendsManager)</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>CodemastersGridLegends game manager created</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Setting listening UDP to 20777</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Checking configuration status for CodemastersGridLegends</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Detected install path : F:\SteamLibrary\SteamApps\common\GRID Legends</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Configuration status for CodemastersGridLegends: GameNotConfigured</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating plugin manager with plugins : SerialDashPlugin, AudioControlPlugin, JoystickPlugin, GraphicalDashPlugin, DevicesPlugin, KeyboardEmulatorPlugin, ShakeITBSV3Plugin, ShakeITMotorsV3Plugin, ShakeItWindPlugin, LapHitoryPlugin, ThrustmastersPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.AudioControl.AudioPlayPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.SystemInfosProvider plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.Web.WebPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.AudioControl.AudioControlPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.InputPlugins.JoystickPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.Devices.DevicesPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.SystemInfosProvider plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.AudioControl.AudioControlPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.Devices.DevicesPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.AudioControl.AudioPlayPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.InputPlugins.JoystickPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Starting Arduino in Single USB mode</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Matrix custom font custommatrixfont8x8 loaded</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.Web.WebPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Plugin manager correctly initialised</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Loading plugins controls</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>JoystickManager : Starting game controllers detection</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Game successfully loaded</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>JoystickManager : Found Logitech_G_HUB_G29_Driving_Force_Racing_Wheel_USB</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>JoystickManager : End of detection</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>(Re)Starting ETS2 Game Manager and plugin manager</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping old game manager</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping old plugin manager</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.DataPlugins.SystemInfosProvider</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.DataPlugins.SystemInfosProvider plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Saving plugin settings SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin settings saved</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.SystemInfosProvider</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.AudioControl.AudioControlPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.Devices.DevicesPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.AudioControl.AudioPlayPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.DataPlugins.Shell.ShellPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.InputPlugins.JoystickPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopping plugin SimHub.Plugins.Web.WebPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Stopped all plugins</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating Euro Truck Simulator 2 game manager (ETS2Reader.ETS2ManagerV2)</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>ETS2 game manager created</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Checking configuration status for ETS2</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Detected install path : None</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Configuration status for ETS2: GameNotDetected</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating plugin manager with plugins : SerialDashPlugin, AudioControlPlugin, JoystickPlugin, GraphicalDashPlugin, DevicesPlugin, KeyboardEmulatorPlugin, ShakeITBSV3Plugin, ShakeITMotorsV3Plugin, ShakeItWindPlugin, LapHitoryPlugin, ThrustmastersPlugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.AudioControl.AudioPlayPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.SystemInfosProvider plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.Web.WebPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.AudioControl.AudioControlPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.InputPlugins.JoystickPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.Devices.DevicesPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Creating SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.SystemInfosProvider plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.AudioControl.AudioControlPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.Devices.DevicesPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.AudioControl.AudioPlayPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.InputPlugins.JoystickPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Starting Arduino in Single USB mode</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Matrix custom font custommatrixfont8x8 loaded</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Initialising SimHub.Plugins.Web.WebPlugin plugin</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Plugin manager correctly initialised</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Loading plugins controls</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>JoystickManager : Starting game controllers detection</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>JoystickManager : Found Logitech_G_HUB_G29_Driving_Force_Racing_Wheel_USB</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>JoystickManager : End of detection</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Game successfully loaded</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Checking configuration status for ETS2</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Detected install path : None</TD></TR><TR><TD>&nbsp;</TD><TD>INFO</TD><TD>Configuration status for ETS2: GameNotDetected</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by SHWotever** [comment]
Hi ! Those two games can't be configured automatically you have to configure them manually, you will find a little pop-up to show the instructions, or if you dismissed it already you can access the configuration instructions from the game settings menu :

**Comment by SHWotever** [comment]
https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#manual-game-configuration
