### ISSUE TITLE
Road Rumble for Assetto Corsa

### ISSUE THREAD

**Issue by ez363** [SHWotever/SimHub#1220]
Hi,

Is it possible to activate the "road rumble" effect on assetto corsa ?

This effect is present on the steering wheel but I would like to feel it on my bass shakers as well.

Thanks for your comments.

Vincent

**Comment by SHWotever** [comment]
Hi ! Unfortunately the data is not available in telemetry, only in the FFB sent to the wheel which can't be used to craft shakers effects.

**Comment by ez363** [comment]
OK, thanks for your quick answer.
