### ISSUE TITLE
[Feature request] - 5 Ahead/Behind avec 1 ou plusieurs tours de retard

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1221]
Hello
Parmi les 5 ahead/behind, on n'a pas l'information s'ils ont 1 ou plusieurs tours de retard
Je les détecte au travers de formules de calcul (pour les afficher sur un fond bleu), malheureusement incomplètes pour quelques cas

cette information "tour de retard" (ex : +1 LAP) est disponible au travers du leaderboard

comment la récupérer sur un dash pour les 5 ahead/behind ?
Merci

**Comment by SHWotever** [comment]
Hello ! 

J'ai ajouté les deux données LapsToLeader et LapsToPlayer ils sont à 0 si le joueur est dans le meme tour respectivement du leader ou du joueur

**Comment by herve4545** [comment]
Hello
Fantastique
Merci

**Comment by herve4545** [comment]
tous mes cas de test sont OK :+1: 

seul ce cas ci-dessous m'interpelle. J'arrive à le traiter mais...
le 6eme "nathan harrisson" est à un tour de moi et le driverbehind_02_laptoplayer est à -1. pour moi, il devrait être à 1

c'est un cas de test que je rejoue avec un vieux replay ; c'est peut-être pour ca

**Comment by herve4545** [comment]
raceroom
apparemment ca ne fonctionne pas sur raceroom
j'ai pris une lmp2 et j'ai mis des porsche cup et des frj en AI
je leur prend 1 tour, puis 2 tour et....
PersistantTrackerPlugin.DriverBehind_00_LapsToLeader = 0
PersistantTrackerPlugin.DriverBehind_00_LapsToPlayer = -1

sur ton dash simhub-leaderboard, le gap n'est jamais à +1 lap ou +2 lap non plus. On dirait que ca n'a jamais fonctionné pour raceroom. 
Peut-tre que j'ai loupé quelque chose car su rf2, tout fonctionne bien

**Comment by herve4545** [comment]
meme problème que sur raceroom pour ams2
PersistantTrackerPlugin.DriverBehind_00_LapsToLeader reste à 0 par exemple

**Comment by herve4545** [comment]
je refais mes tests
Le problème est peut-être chez moi
mauvais compréhension de ma part
