### ISSUE TITLE
Missing SimHub.Licensing assembly referenced by SimHub.Plugins

### ISSUE THREAD

**Issue by RevanProdigalKnight** [SHWotever/SimHub#1222]
**Describe the bug**
I'm trying to create a plugin to control the LEDs on Thrustmaster Ferrari 488 Challenge Edition wheels, but when editing the XAML file for plugin settings, the editor in Visual Studio 2022 complains about a missing dependency and shows the following.

![image](https://user-images.githubusercontent.com/5728037/216781724-bd487475-3438-4eef-a25f-8ff310c19586.png)

Using the "Analyze Assembly Dependencies" extension for Visual Studio yields the following:

![image](https://user-images.githubusercontent.com/5728037/216781632-9ca1eccc-fd8f-4e99-824c-4051d6762ebd.png)

**Simhub version**
8.2.1

**Comment by SHWotever** [comment]
Hi ! Indeed this dll has been protected for "sad reasons" and is not physically present anymore, 
I tried with the fresh SDK and I could not reproduce it. In theory this dll get called in few few occasions and should not be during design time. 

I feel like instantiating your plugin at design time as a resource is the culprit : 
![image](https://user-images.githubusercontent.com/2207331/216783266-3fb58d1d-01fd-4926-8a36-b0c2033fa1e3.png)
Overall it should not be a direct resource of your design, the plugin is instantiated by simhub core.

**Comment by RevanProdigalKnight** [comment]
I still experience the issue even with that block commented.

![image](https://user-images.githubusercontent.com/5728037/216788022-dd979cf9-c807-461e-93c8-e56850522302.png)

**Comment by RevanProdigalKnight** [comment]
> I tried with the fresh SDK and I could not reproduce it. In theory this dll get called in few few occasions and should not be during design time.

I just tried opening one of the example SDKs in Visual Studio and I get the exact same error. Are you sure you don't have an old copy of `SimHub.Licensing.dll` in your installation directory which is "fixing" the issue?

I've never had a version of SimHub prior to 8.2.0 installed.

![image](https://user-images.githubusercontent.com/5728037/216840717-b864d802-2102-4dea-9f02-d24a220b9d56.png)

**Comment by SHWotever** [comment]
Hi !

Yes indeed I double checked that it wasn't here, I will test on another computer if somehow my simhub development environment has an influence on it ;)

In theory it shouldn't prevent compilation?

**Comment by SHWotever** [comment]
I double checked,

When the SDK is not compiled yet I have a similar message  as yours, which is pretty classic on a fresh project.
![image](https://user-images.githubusercontent.com/2207331/216842367-bf38c9b4-4baf-4173-8a04-4b412f3a98af.png)

 but once it get compiled it works (designer might need to be closed and reopened :
 
![image](https://user-images.githubusercontent.com/2207331/216842390-13530323-484f-4c46-b761-1977f01d79eb.png)

I think your dependency graph is not related to the designer issue.

As a side note the default SDK is bulding into the simhub folder which contains all the related dependencies. I've not polluted the sdk project by linking all the dependencies which are numerous around Simhub.plugins.dll. Building into the simhub folder allows the designer to find all the missing dependencies.

**Comment by RevanProdigalKnight** [comment]
Ah, I haven't used Visual Studio in a long time so I forgot that it needs to compile in order to work...

I guess following the "no pollution" design of the [SimHub SLI Plugin](https://github.com/simelation/simhub-plugins/tree/main/packages/simhub-sli-plugin) wasn't the best idea. I'll try moving my project into the PluginSdk folder and see if it works better there.

**Comment by RevanProdigalKnight** [comment]
Hmm, this is interesting... moving it into the PluginSdk folder has stopped it complaining about the missing DLL, but it's still weird, even after compiling and restarting all of Visual Studio

![image](https://user-images.githubusercontent.com/5728037/216847018-64d4672c-7a54-49de-a8a9-daad7ad792e1.png)

**Comment by RevanProdigalKnight** [comment]
Nevermind, I figured out I hadn't deleted the old `obj` folder. Deleting that and recompiling has fixed the issue.

Thanks for your help, and (hopefully) not getting really frustrated with my stupidity/cluelessness.
