### ISSUE TITLE
[Feature request] Shared CLK pin for TM1637

### ISSUE THREAD

**Issue by eschmitty** [SHWotever/SimHub#1223]
I just wanted to point out that it is possible to share the Arduino CLK pin for multiple TM1637 modules. This works fine with the setup tool although the tool does complain that you have a pin conflict. I tested 5 RobotDYN modules sharing the same CLK pin and they function perfectly. While the pin conflict issue could be resolved in the tool, I think this is at least worth a mention in the docs and/or in the Arduino setup tool. I attached a picture showing how I set it up on a breadboard with a pro micro. 
![signal-2023-02-05-141445](https://user-images.githubusercontent.com/30362930/216840004-1bc5dc4d-1ba7-4688-82dc-032ed369fb24.jpeg)

**Comment by SHWotever** [comment]
Hi ! Thanks for the information. I knew that some wiring could be optimized by sharing some pins, but the idea was to give something simple and touble free. I've read that some tm1637 were accepting clk pin sharing, some not, some dio, I feel like it's playing with the limits of the chip and how it does handle it. 

I added a little mention about it in the wiki with the required reserves about it working universally.
