### ISSUE TITLE
Assetto Corsa ABS/TC [Feature request]

### ISSUE THREAD

**Issue by shoftmadder** [SHWotever/SimHub#1224]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to add actions when ABS or Traction Control is occurring in Assetto Corsa (e.g. lights, vibrations)

**Describe the solution you'd like**
I'd like the ABS and Traction Control information to be made available in SimHub, so that I can use it to trigger effects

**Describe alternatives you've considered**
I've considered writing my own plugin for SimHub to provide the values, but it'd be nice to have it integrated "properly"

**Additional context**

The data is not available in stock Assetto Corsa Python or Shared Memory.  However:

- It is available through the [UDP telemetry](https://docs.google.com/document/d/1KfkZiIluXZ6mMhLWfDX1qAGbvhGRC3ZUzjVIt5FQpp4/pub):

```
struct RTCarInfo
{
        [snip...]
        bool isAbsEnabled;
        bool isAbsInAction;
        bool isTcInAction;
        bool isTcEnabled;
        [snip...]
}
```

- It is available through Python if the [Custom Shaders Patch is installed](https://github.com/ac-custom-shaders-patch/acc-extension-config/wiki/Python-Apps-%E2%80%93-New-functions):
```
def ac.ext_getStateAbs(carIndex: int) -> int:
def ac.ext_getStateAbsActive(carIndex: int) -> bool:
def ac.ext_getStateTc(carIndex: int) -> int:
def ac.ext_getStateTcActive(carIndex: int) -> bool:
```
I assume `carIndex` is 0 for the player car, as noted in the [ACPythonDocumentation](https://assettocorsamods.net/attachments/acpythondocumentation-pdf.1135).  Obviously these functions will not exist if Custom Shaders Patch is not installed, so calls would need to be wrapped in a try/catch block.

Could the information be made available in SimHub?

**Comment by SHWotever** [comment]
Hi ! Thanks for pointing it, I can't believe how heterogeneous can be AC sometimes, I've often seen this documentation and read it in diagonal many times and simply concluded that it was too poor for any interest (mostly to bring AC consoles support) 

To get the full data from AC it starts to be an absolute mess, from internal APPS, shared memory, game config files ... now I added UDP :D But for those two data it was worth it :D

isAbsEnabled and isTcEnabled are still only true false bytes, so it won't improve these values, shared memory mostly works but there is some flaws in the provided data.

About Custom Shaders, I prefer to stay away from it, as good as it is, I can only rely on the vanilla game.
