### ISSUE TITLE
Blue screen only while sim hub is loaded

### ISSUE THREAD

**Issue by curac268** [SHWotever/SimHub#1226]
**Describe the bug**
Blue screen

**Simhub version**
8.2.1

**To Reproduce**
cant reproduce 

**Expected behavior**
Computer restart

**Screenshots**

**Log files**
Microsoft (R) Windows Debugger Version 10.0.25200.1003 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Windows\Minidump\010423-10281-01.dmp]
Mini Kernel Dump File: Only registers and stack trace are available

Symbol search path is: srv*
Executable search path is: 
Windows 10 Kernel Version 22621 MP (16 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Machine Name:
Kernel base = 0xfffff801`52600000 PsLoadedModuleList = 0xfffff801`53212fc0
Debug session time: Wed Jan  4 18:28:56.123 2023 (UTC + 1:00)
System Uptime: 0 days 7:31:18.717
Loading Kernel Symbols
..

Press ctrl-c (cdb, kd, ntsd) or ctrl-break (windbg) to abort symbol loads that take too long.
Run !sym noisy before .reload to track down problems loading symbols.

.............................................................
................................................................
................................................................
.....................................
Loading User Symbols
Loading unloaded module list
.........
For analysis of this file, run !analyze -v
nt!KeBugCheckEx:
fffff801`52a28700 48894c2408      mov     qword ptr [rsp+8],rcx ss:ffffbf8d`0986e7b0=000000000000001e
6: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

KMODE_EXCEPTION_NOT_HANDLED (1e)
This is a very common BugCheck.  Usually the exception address pinpoints
the driver/function that caused the problem.  Always note this address
as well as the link date of the driver/image that contains this address.
Arguments:
Arg1: ffffffffc0000005, The exception code that was not handled
Arg2: fffff801528177c4, The address that the exception occurred at
Arg3: 0000000000000000, Parameter 0 of the exception
Arg4: 0000000000000000, Parameter 1 of the exception

Debugging Details:
------------------

*************************************************************************
***                                                                   ***
***                                                                   ***
***    Either you specified an unqualified symbol, or your debugger   ***
***    doesn't have full symbol information.  Unqualified symbol      ***
***    resolution is turned off by default. Please either specify a   ***
***    fully qualified symbol module!symbolname, or enable resolution ***
***    of unqualified symbols by typing ".symopt- 100". Note that     ***
***    enabling unqualified symbol resolution with network symbol     ***
***    server shares in the symbol path may cause the debugger to     ***
***    appear to hang for long periods of time when an incorrect      ***
***    symbol name is typed or the network symbol server is down.     ***
***                                                                   ***
***    For some commands to work properly, your symbol path           ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: ExceptionRecord                               ***
***                                                                   ***
*************************************************************************
*************************************************************************
***                                                                   ***
***                                                                   ***
***    Either you specified an unqualified symbol, or your debugger   ***
***    doesn't have full symbol information.  Unqualified symbol      ***
***    resolution is turned off by default. Please either specify a   ***
***    fully qualified symbol module!symbolname, or enable resolution ***
***    of unqualified symbols by typing ".symopt- 100". Note that     ***
***    enabling unqualified symbol resolution with network symbol     ***
***    server shares in the symbol path may cause the debugger to     ***
***    appear to hang for long periods of time when an incorrect      ***
***    symbol name is typed or the network symbol server is down.     ***
***                                                                   ***
***    For some commands to work properly, your symbol path           ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: ContextRecord                                 ***
***                                                                   ***
*************************************************************************
*************************************************************************
***                                                                   ***
***                                                                   ***
***    Either you specified an unqualified symbol, or your debugger   ***
***    doesn't have full symbol information.  Unqualified symbol      ***
***    resolution is turned off by default. Please either specify a   ***
***    fully qualified symbol module!symbolname, or enable resolution ***
***    of unqualified symbols by typing ".symopt- 100". Note that     ***
***    enabling unqualified symbol resolution with network symbol     ***
***    server shares in the symbol path may cause the debugger to     ***
***    appear to hang for long periods of time when an incorrect      ***
***    symbol name is typed or the network symbol server is down.     ***
***                                                                   ***
***    For some commands to work properly, your symbol path           ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: ExceptionRecord                               ***
***                                                                   ***
*************************************************************************
*************************************************************************
***                                                                   ***
***                                                                   ***
***    Either you specified an unqualified symbol, or your debugger   ***
***    doesn't have full symbol information.  Unqualified symbol      ***
***    resolution is turned off by default. Please either specify a   ***
***    fully qualified symbol module!symbolname, or enable resolution ***
***    of unqualified symbols by typing ".symopt- 100". Note that     ***
***    enabling unqualified symbol resolution with network symbol     ***
***    server shares in the symbol path may cause the debugger to     ***
***    appear to hang for long periods of time when an incorrect      ***
***    symbol name is typed or the network symbol server is down.     ***
***                                                                   ***
***    For some commands to work properly, your symbol path           ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: ContextRecord                                 ***
***                                                                   ***
*************************************************************************

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 2671

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 6958

    Key  : Analysis.IO.Other.Mb
    Value: 5

    Key  : Analysis.IO.Read.Mb
    Value: 0

    Key  : Analysis.IO.Write.Mb
    Value: 24

    Key  : Analysis.Init.CPU.mSec
    Value: 187

    Key  : Analysis.Init.Elapsed.mSec
    Value: 26475

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 89

    Key  : Bugcheck.Code.DumpHeader
    Value: 0x1e

    Key  : Bugcheck.Code.Register
    Value: 0x1e

    Key  : Dump.Attributes.AsUlong
    Value: 1008

    Key  : Dump.Attributes.DiagDataWrittenToHeader
    Value: 1

    Key  : Dump.Attributes.ErrorCode
    Value: 0

    Key  : Dump.Attributes.KernelGeneratedTriageDump
    Value: 1

    Key  : Dump.Attributes.LastLine
    Value: Dump completed successfully.

    Key  : Dump.Attributes.ProgressPercentage
    Value: 0

FILE_IN_CAB:  010423-10281-01.dmp

DUMP_FILE_ATTRIBUTES: 0x1008
  Kernel Generated Triage Dump

BUGCHECK_CODE:  1e

BUGCHECK_P1: ffffffffc0000005

BUGCHECK_P2: fffff801528177c4

BUGCHECK_P3: 0

BUGCHECK_P4: 0

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000000000000000

READ_ADDRESS: fffff8015331c468: Unable to get MiVisibleState
Unable to get NonPagedPoolStart
Unable to get NonPagedPoolEnd
Unable to get PagedPoolStart
Unable to get PagedPoolEnd
unable to get nt!MmSpecialPagesInUse
 0000000000000000 

BLACKBOXBSD: 1 (!blackboxbsd)

BLACKBOXNTFS: 1 (!blackboxntfs)

BLACKBOXPNP: 1 (!blackboxpnp)

BLACKBOXWINLOGON: 1

CUSTOMER_CRASH_COUNT:  1

PROCESS_NAME:  SimHubWPF.exe

TRAP_FRAME:  ffff800000000000 -- (.trap 0xffff800000000000)
Unable to read trap frame at ffff8000`00000000

STACK_TEXT:  
ffffbf8d`0986e7a8 fffff801`52b3976a     : 00000000`0000001e ffffffff`c0000005 fffff801`528177c4 00000000`00000000 : nt!KeBugCheckEx
ffffbf8d`0986e7b0 fffff801`52a33972     : ffffbf8d`0986efc0 ffffbf8d`0986e880 fffff801`52600000 fffff801`52a2e4ec : nt!HvlpVtlCallExceptionHandler+0x22
ffffbf8d`0986e7f0 fffff801`5280c213     : ffffbf8d`0986f9e0 ffffbf8d`0986f7a8 fffff801`52a2e4ec fffff801`526e9d68 : nt!RtlpExecuteHandlerForException+0x12
ffffbf8d`0986e820 fffff801`52810087     : ffffffff`ffffffff ffffbf8d`0986f850 ffffbf8d`0986f850 ffffbf8d`0986efc0 : nt!RtlDispatchException+0x2f3
ffffbf8d`0986ef90 fffff801`52a3defc     : 00000000`00001000 ffffc184`40106140 ffff8000`00000000 ffffc184`40106880 : nt!KiDispatchException+0x317
ffffbf8d`0986f670 fffff801`52a3940e     : ffffc184`48cf8660 00000000`00000000 fffff801`528cfb20 ffffc184`426fd690 : nt!KiExceptionDispatch+0x13c
ffffbf8d`0986f850 fffff801`528177c4     : ffffc184`48cf86d8 00000000`01197000 00000000`00000001 fffff801`52db9300 : nt!KiPageFault+0x44e
ffffbf8d`0986f9e0 fffff801`52a2e4ec     : 00000000`2553eb00 00000000`00000000 00000000`00000004 00000000`00000000 : nt!KiDeliverApc+0xa4
ffffbf8d`0986faa0 00007ffe`0234f764     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiApcInterrupt+0x35c
00000000`0bcde158 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x00007ffe`0234f764

SYMBOL_NAME:  nt!KiDeliverApc+a4

MODULE_NAME: nt

IMAGE_NAME:  ntkrnlmp.exe

IMAGE_VERSION:  10.0.22621.963

STACK_COMMAND:  .cxr; .ecxr ; kb

BUCKET_ID_FUNC_OFFSET:  a4

FAILURE_BUCKET_ID:  AV_R_nt!KiDeliverApc

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {82e737f7-350b-934b-c920-0a3e8dd7376b}

Followup:     MachineOwner
---------
**Additional context**
![Snimka zaslona 2023-02-13 213115](https://user-images.githubusercontent.com/125311662/218568248-1da13ff6-c1e8-4d12-b199-6c6bdc65554c.jpg)

I am using WInd simulator, one Arduino Micro for 3 swithces for handbrake and seqential shifter.
One arduino MIcro for RPM and Gear indicator.

Problem start before wind simulator.
can i have two indicators on one PRO micro, like i have RPM and Gear indicator?

Also problem startd when i have also two devices , one for RPM and one for Gear indicator.

Regards

**Comment by SHWotever** [comment]
Hi ! Most of the time bsod are related to hardware or drivers., Can you check that all your drivers are up to date ? Could you also double check that you don't have any shorts ? With 12v for fans around a short going back to the USB could be enough to make windows unstable. To check it unplugging power from the wind board would be a good test. A bad usb hub could be also a cause if you are using one to connect the Arduino could you remove it ?

Concerning merging features on a single board yes it's possible, except shields like motor shields where I highly discourage to mix with anything else (piggy backing it would be a good way to get shorts etc ...)

**Comment by SHWotever** [comment]
Maybe another possibility, does one of your Arduino uses prolific usb to serial chip (usually it's ch340 or ftdi, but with the chips shortage nothing is impossible) ? Those chips are notorious for causing BSOD with no particular reasons.

**Comment by curac268** [comment]
Will check, tnx for inputs.

Ps. Wind simulator is on 12v power source, not from arduino. Problem
started before wind simulator.

Thinking the fault is usb hub, how to check dont know. Cant insert so much
inputs on laptop. Its 13 port usb hub from orico, with push button for
single usb ports manualy. This one is the model - orico ct2u3 13ab.

Regards

**Comment by SHWotever** [comment]
Orico is usually reliable, but BSOD can be caused by many things, bad drivers, bad bios update (I had the case myself a few days ago), overheating machine. As is I don't think that simhub is directly the cause of your issue, I close the ticket, but do not hesitate to give a follow up when you will get it tracked down to the root issue.

**Comment by curac268** [comment]
Changed Power supply of USB hub - same errors.

Removed USB hub, still BSOD. Tried to change  setting - system info - turned on HWinfo64 - blue screen again.


Laptop is not overheating, its idle max 46 Celsius. on DIY aluminium 2x Vardar 140mm Fans with controller. Max temperature is 68 Celsius. Using mobile dash with temperature sensors all time. 

Strange that laptop don t have any other errors, when sim hub is closed nothing hapened.  Everything is working days. 
Did clean install win11, again same problems. Did reinstalled Sim hub, same problem.
Have purchased Sim hub from beginning, not free version.

Very annoying problem.

![Snimka zaslona 2023-02-16 191339](https://user-images.githubusercontent.com/125311662/219452281-9421fdab-fe71-4787-98c6-784669a73a4f.jpg)

**Comment by curac268** [comment]
Problem was WIFI Keyboard dongle, when on USB hub. ( if someone have same keyboard, it is Asus Falchion) .

**Comment by curac268** [comment]
I found what the problem was, everything worked normally for two days. 

The sim hub is the reason.

Sim hub tries to scan devices that are not in use, it scans them all the time while the program is running.

eg. other steering wheels using arduino.
I got another computer where everything works fine and figured out what the problem was.


Can you explane why is this happening.
I have 4 steering wheels, 2 I made myself and I use them occasionally if I drive formula or gt4 cars.

While I'm using other steering wheels, the sim hub keeps trying to scan the com ports for steering wheels that aren't connected, after some time computer make a blue screen with simhubwpf.exe file.

regards.

**Comment by SHWotever** [comment]
Hi ! Indeed simhub scans for arduino devices as it's not possible to recognize them without scanning serial ports. 
If you have blue screens that still means something is sneaky in the hardware and some serial ports/drivers does a BSOD after opening/closing.

You can secure your "non simhub" devices by excluding them from the scan engine, I guess the issue is triggered by a "non arduino serial port" ,Good quality arduino (clone or official) uses CH340G or FTDI which and are not known for BSOD, excluding it should help  : https://github.com/SHWotever/SimHub/wiki/Troubleshoot-other-hardware-Serial-ports-conflicts 

Just to explain why and how it scans  
- In single arduino mode : it scans until it finds one device (there could be a few scans ending after since it test devices in parrallel to find a simhub compatible one)
- In multiple arduino mode : it scans until it finds all the configured devices, if one or more are missing it will pause for a few seconds then try again.

**Comment by curac268** [comment]
Deleted two not used device(wheels), no more blue screens.

Cant have all 4 wheels connected at the same time , so i need to delete not used ones.

They are cloned arduino-s, and they are working fine. Don t want to buy 4 original device, if i only need to delete not used one. Definitely all time scanning for com ports kill app, and windows protect him self and send blue screen.

Maybe adding on arduino scan settings tabs -scan only and never to be in same  filter. 

I can only choose scan only or never scan.

If i can chose scan 4-5-6 and don t scan not used one, problem solved.

Regards
Tomislav
