### ISSUE TITLE
Porsche Cup - Turbo or not Turbo

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1227]
IRL, la Porsche Cup ne possède pas de turbo

Dans Raceroom, ACC et Dirt Rallly 2.0, c'est correct
Dans AMS2 et Rfactor 2, les données turbo sont renseignées. Est-ce une erreur des jeux ou dans simhub

ex : rf2
![1](https://user-images.githubusercontent.com/58605557/218975353-1fcf75e0-9a97-4e23-b3b4-d71b6932266a.jpg)

**Comment by SHWotever** [comment]
Hello, vu que mturbopressure est alimenté, ce qui est la valeur qui vient du jeu lui même avant traitement visiblement c'est une erreur du jeu. Après la valeur me paraît hyper fantaisiste, ça ne serait pas la première fois que je croise ce type de valeurs quand elles ne sont pas alimentées par le jeu a l'instant t

**Comment by herve4545** [comment]
oui, c'est assez fantaisiste
OK merci
