### ISSUE TITLE
 desired function

### ISSUE THREAD

**Issue by KG2004** [SHWotever/SimHub#1230]
I would like Simhub to be compatible with asset corsa replays.

Because you're not recording your best rides all the time.

Can you please think about it

From a boy who loves cars in Japan.

※This article uses Google translation.

**Comment by SHWotever** [comment]
Hi ! Not supporting replays is intentional to get an homogeneous support across games. Moreover allowing replays would mess  the simhub internal statistics.

**Comment by KG2004** [comment]
> やあ ！リプレイをサポートしないのは、ゲーム間で均一なサポートを得るために意図的なものです。さらに、リプレイを許可すると、simhub の内部統計が台無しになります。

I'm so sad because I can't shoot unless it's a replay.

However, I'm sad that there was only a lap timer like F1TV here.

Thank you for answering!
