### ISSUE TITLE
8.2.2 : ahead et behind bestlaptime disparus

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1232]
sur la v8.2.2, les ahead et behind bestlaptime ont disparu
ils reviennent si je réinstalle la v8.2.1

![8 2 1](https://user-images.githubusercontent.com/58605557/220316825-7e6191dc-1921-4d1c-a05b-83219aa15c6a.jpg)
![8 2 2](https://user-images.githubusercontent.com/58605557/220316852-1592fe26-2559-4091-b5de-2bc29754cd36.jpg)

**Comment by SHWotever** [comment]
Hello ! Effectivement la déclaration a été perdue faute a des copier coller malencontreux :(, c'est corrigé pour la prochaine version !

**Comment by herve4545** [comment]
OK sur 8.2.3
