### ISSUE TITLE
Dash Navigation - Possible bug

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1233]
**Describe the bug**
Hi, while working on a new dash, I ran into a weird issue.
On this dash, when not on the "Pit" screen, if I click on an empty space of the screen, between the buttons, it navigates back to the "Pit" screen. I don't understand why.
It seems to only occur in desktop mode.
I assume it has something to do with the new navigation system.
I tried to boil the dash down and it's still happening.
Here is the boiled down version:
[Navigation test.zip](https://github.com/SHWotever/SimHub/files/10813026/Navigation.test.zip)

**Simhub version**
8.2.2

**To Reproduce**
1. Import the dash
2. Start it in desktop mode
3. Got to to any screen other than pit
4. Click in the empty zone and you're back on the pit screen

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/10812977/SimHub.log)

Happy hunting!

**Comment by SHWotever** [comment]
Hi !

Thanks for the example, I caught it, window dragging when not fullscreen and buttons were strangely interfering triggering some unwanted "mouse up" events on the button . I fixed it for the next version ;)

**Comment by Romainrob** [comment]
Hi,
All good on 8.2.3 👍 
Thanks for the fix!

**Comment by Romainrob** [comment]
Hi, sorry to reopen this one but I just noticed the same issue, in HTML mode this time.
When sliding left or right in an empty area, the dash returns to the pit screen.

**Comment by Romainrob** [comment]
Hi, sorry to reopen this one but I just noticed the same issue, in HTML mode this time.
When sliding left or right in an empty area, the dash returns to the pit screen.

**Comment by Romainrob** [comment]
Hi,
In addition I noticed the dash changing screen in a strange way when entering/exiting the car in iRacing despite all the screen only having the "Game" role.

**Comment by SHWotever** [comment]
Hi ! I guess this got fixed with your tip about pit, since pit and pitlane are not merget anymore ;)
