### ISSUE TITLE
8.2.2 Assetto Corsa - redline outputs pit limiter

### ISSUE THREAD

**Issue by samdale12** [SHWotever/SimHub#1238]
I’m sure you’re already aware of it, but no sign of an issue here in my search. The latest release (8.2.2) appears to be outputting a ‘pit limiter’ signal (and triggering associated Dash Studio and RGB LEDs outputs) when engine redline (or rev limiter?) is reached. Evident on multiple dashes and multiple RBG LED profiles.

**Comment by SHWotever** [comment]
Hi ! Well seen ! I got confused by the naming of the UDP data when I added it in the last release, I'm rollbacking it for the next version  ;)
Thanks !
