### ISSUE TITLE
[BUG] Vocore Touch Buttons

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1241]
**Describe the bug**
When using Vocore touch and dash studio  switching pages via touch buttons only works until dashboard is saved in dash studio.
After saving the touch buttons lose functionality until vocore is reconnected / dash studio is restarted. it's a bit annoying when testing dashboard functionality ;) 

**Simhub version**
latest 

EDIT: After some more testing I doubt it's a sim hub problem rather than a malfunctioning vocore screen.

**Comment by SHWotever** [comment]
Hi !

Could you give more details about the screen model ? I tested to save dashboards in various ways which triggers the dash reload on the screen but on all my attempts touch was still working after it. I also tried both "basic mode" (left/right navigation) or advanced with buttons on the screen. but I've not been able to reproduce it yet (I tested with 4" , 5" and 6.5" screens)

**Comment by FullPace** [comment]
As I mentioned in the edit part of the first post, it turned out this was not a Simhub issue. The metal frame of the device had direct contact to the display and this was recognized as a permament touch… this issue can be closed 🙂

**Comment by SHWotever** [comment]
Ah thanks :D I understood that it was just a suspicion :D
