### ISSUE TITLE
Pressing GraphicalDashPlugin.NextScreen goes to next screen on all available dashes/displays

### ISSUE THREAD

**Issue by NickoLopez** [SHWotever/SimHub#1244]
**Issue:**
Pressing GraphicalDashPlugin.NextScreen goes to next screen on all available dashes/displays
Latest Simhub Version

**Steps to reproduce the behavior:**
1. Bind GraphicalDashPlugin.NextScreen to a button (keyboard or wheel)
2. Open a dash with multiple pages on 1 screen/phone/window
3. Open a second dash with multiple pages on another screen/phone/window
4. Press the NextScreen button
4. See the two dashes going to the next screen

**Expected behavior**
It'd be nice to have a way to bind buttons per dash instances, for instance: 
GraphicalDashPlugin.NextScreen1, GraphicalDashPlugin.NextScreen2, ..., GraphicalDashPlugin.NextScreenAll

**Comment by FullPace** [comment]
Sounds like you mapped multiple devices to the global next screen function instead of the next page per device (devices > your screen > controls tab )

**Comment by SHWotever** [comment]
Hi !

This has been reworked in the incoming v9 version, it's now possible to have multiple controls depending of the location on the screen.
