### ISSUE TITLE
[Feature request] Control media cover art downscaling

### ISSUE THREAD

**Issue by jchitpin** [SHWotever/SimHub#1246]
**Is your feature request related to a problem? Please describe.**
I've been working on a music player dashboard and the media cover tool always downsizes my image to 97 by 96 pixel image before resizing that temporary image to my desired size.

**Describe the solution you'd like**
Is it possible to reduce or control the image downscaling when using the media cover tool? Could this be added as a media cover property?

![Example-dashboard](https://user-images.githubusercontent.com/28490322/223870742-03bb7095-b627-404b-9e55-742b97c892b6.png)

**Comment by SHWotever** [comment]
Hi ! the pictures are at the maximum size windows gives it (and i think under the hood it's the player app which scales it first) so quality hevily relies on the player app.

**Comment by jchitpin** [comment]
Thanks for the reply and awesome work with SimHub :)
