### ISSUE TITLE
[Feature request] Long / Short Press in Controller Mapper

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1251]
Would it be possible to have short and long press for Inputs in the controller mapper, so we can map buttons to more than 1 function. just like in keyboard mapper just mapped to other vjoy outputs.

For example
Button 1 short press = vjoy traction +
Button 1 long press = vjoy traction -

**Comment by SHWotever** [comment]
Hi !

I will think about it. Currently I deliberately wanted something extremely simple with buttons to buttons mapping and no extra options, the goal was really to allow wheel hotswapping. Of course those options would be interresting to expand the possibilites, but if somehow that makes it  as complex as joystick gremlins or similar tools I'm not sure it's the right direction.

**Comment by FullPace** [comment]
I see. I basically did the same thing before with buttons to keys and the keyboard plugin, mapping  same functions to the same keyboard keys. With the extra options I could see all my mappings in one place instead of two different locations. that would be very convinient.

**Comment by SHWotever** [comment]
Hello ! I close this , this is available in the latest beta, as well as many other "modifiers"
