### ISSUE TITLE
[QUESTION] Force delete Web Component Cache 

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1252]
I'm wondering how simhub caches content of the web component.
I use it to display an image when an update for the dashboard is available.
but even renaming img with paramenters like update.jpg?=v102 does not help
to make simhub reload the content. once it's cached it's there forever ...

Any tips how to force reload contents?

**Comment by SHWotever** [comment]
Hi ! It uses internally a chromimum based webbrowser so all the the usual caching rules applies (cache control etc ....)
In theory cache busting like you did ?v=102 should be sufficient, but it really depends of  how the request gets processed (redirects ...)

Do you have a sample with the issue so I can take a look how the requests gets processed ?

**Comment by FullPace** [comment]
Here's all I have: 
1.) Dashboard (web component is on idle screen)
https://www.racedepartment.com/downloads/pacelogic-pro.58473/

Attached are the html files I use,
You can load them from local Simhub "Web" folder as well. The problem remains.

To reproduce:
Open dashboard once, then change web component html file (you can also delete all content in body)
re-open dashboard --> Old content of web component is still there. 

Only if you change the url to the other filename it changes content once. 


[HTML Files.zip](https://github.com/SHWotever/SimHub/files/11010697/HTML.Files.zip)

**Comment by SHWotever** [comment]
Thanks ! I tested the url https://www.fullpace-simracing.com/assets/external/pacelogic-pro-v1.1.html

Despite the html head caching instructions, chrome is caching it :

![image](https://user-images.githubusercontent.com/2207331/226170569-21854488-bd4c-4909-bd19-7cf674dc372d.png)

That means that simhub behavior is normal about that page.

From my experience you are having contradictory headers, on one side you have html headers asking not to cache , but the requests header themselves exposes some caching headers : 
![image](https://user-images.githubusercontent.com/2207331/226170701-dca2567d-9bf4-4bd1-880d-91a507be2667.png)

To get sure not to cache you need to add a no cache response headers :
Cache-Control: no-cache

This is usually done in htaccess files or web.config for a microsoft server . https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Cache-Control

In theory if you are using a php server just changing the extension to .php should trigger default "no caching" rules in your server as .php is a dynamic file extension.

**Comment by SHWotever** [comment]
In the context of a vocore screen I have hand on the browser itself so I could force the cache to be flushed etc ... but on a browser like a phone or chrome it's the natural browser behavior which will occur so the only proper and consistent way is to make the request response non cacheable as i've explaned above.

**Comment by FullPace** [comment]
Thank you, I'll try changing to php and see if this helps. I played with a lot of header commands, to  see if any of them improves the refreshing of the cache. Since this is all bandwith on my server, caching isn't bad at all. It would just be nice to have control over the cache the notify about the updates.

The dashboard is indeed made for a Vocore device but I think it's such a special need, it's probably not worth puttin extra time into it.

**Comment by SHWotever** [comment]
With the proper htaccess it's possible to target only the ressources you want to avoid. Alternatively using a dedicated folder with its own htaccess can do the trick. 
Caching can be hell sometimes. Simhub internally use lot of cache busting query strings, the balance between caching at the right time Vs refreshing at the right time is always hard to reach.

**Comment by FullPace** [comment]
I tried changing the link to .php but it's not loading anything. I guess web component only supports html then?

**Comment by SHWotever** [comment]
Ah simhub embedded server is not a php compliant server, simhub is using a light asp.net internal server it won't recognize .PHP indeed, only a real php server will do it. Your site https://www.fullpace-simracing.com/ might be one, it's the most common technology available in hosting services.

**Comment by SHWotever** [comment]
And overall simhub internal server has a deliberately extremely aggressive caching strategy to improve loading time when reloading dash's etc.
