### ISSUE TITLE
SimHub Setup not working

### ISSUE THREAD

**Issue by Lior4410** [SHWotever/SimHub#1253]
**Describe the bug**
SimHub Setup not working

**Simhub version**
8.2.3

**To Reproduce**

**Expected behavior**
To Setup the programm 

**Screenshots**

https://user-images.githubusercontent.com/86972369/226163424-8bfcfc3e-3d5b-4218-aaec-d327242a7db5.mp4

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
No Files Logs

**Additional context**

**Comment by SHWotever** [comment]
Hi ! It's really strange indeed. Was simhub already installed or is it a first update ?

Could you try to create a tmp directory at your drive root (ie c:\tmp) 
Then run the installer using the following arguments ? 
```/LOG="C:\tmp\install.log"```

![image](https://user-images.githubusercontent.com/2207331/226164570-653829a7-d0f0-47e5-92cd-fd9ef0e73a52.png)

Then send me the log generated into c;\tmp ?

**Comment by Lior4410** [comment]
simhub was not installed its 1st time in installing it 
![image](https://user-images.githubusercontent.com/86972369/226164886-e0397bd9-930b-40ef-9aa0-c7035a784420.png)
maybe you can remote my pc and fix it

**Comment by SHWotever** [comment]
Hi ! Your command line is apparently wrong. you need to go in the folder itself then run the command
for instance 
```
> cd 'c:\users\lior4\downloads\Simhub.8.02.3 (2)\'
> SimHubSetup_8.2.3.exe /LOG="C:\tmp\install.log"

```

I'm sorry for security reasons I don't do remote connections to others computer.

**Comment by Lior4410** [comment]
![image](https://user-images.githubusercontent.com/86972369/226165660-1f46df82-bcbd-4c53-81ef-01994f4b9086.png)

**Comment by SHWotever** [comment]
Have you created the c:\tmp folder first so it can receive the log files ?

**Comment by Lior4410** [comment]
now its working 
![image](https://user-images.githubusercontent.com/86972369/226165904-6aa59984-eaaf-40f1-a70b-dabd91696a4e.png)
[install.log](https://github.com/SHWotever/SimHub/files/11010593/install.log)
