### ISSUE TITLE
[BUG?] AMS 2 fuel and leaderboard calculation

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1254]
I play a lot of AMS2 lately and I know they change a lot of stuff at the moment, so I'm not sure if it's a really bug.

 Sometimes the calculations don't work.

For example mid race I get a low fuel alert but there are still 20L left in the tank. Computed values like
average Liters per lap, current comsumption or laps remaining show zero anyway.
This happens accross multiple dashboards.  

I have a short replay saved when it showed 0 for computed values, if that helps.

For the leaderboards I often need to drive a complete lap until they are calculated. once they are calculated and I restart the session it works right ahead.

**Comment by FullPace** [comment]
Did you have any chance to investigate this yet? This still happens in every other race. I also realized checkered flags are shown only in 2 out of 10 races.

**Comment by FullPace** [comment]
Latest update of AMS2 might have brought an improvement. In last race fuel calculation was working and also checkered flags seem to be much more reliable. Will test leaderboards tonight. Hopefully Reiza improved the telemetry quality.

**Comment by SHWotever** [comment]
Hello I did not had a chance to look at it, but just in case something went wrong do not hesitate to keep the log files, every time simhub will aggregate some data to estimate the consumption it will write a log (fuel stats aggregated etc..) in theory it's made to avoid false positives breaking estimates such as pits, refuel, teleportation etc ... one security I had to remove is negative consumption for electric cars with regen , if we are in such case it will be visible from the logs
