### ISSUE TITLE
[Feature request] Add support for Thermaltake LCD Panel - 500 series, 3.9 inch

### ISSUE THREAD

**Issue by HKusp** [SHWotever/SimHub#1255]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SHWotever** [comment]
Hi ! thanks for the suggestion, 
I took a look but the screen is hardly availalble in France, I will watch if it is more widely available in the future (and if it stays sold too)
But overall I feel that the price/ screen quality ratio is not correct and may not attract enough users (corsair nexus was in this category, I almost never hear anyone using it, but reverse engineering effort was big)
Have you considered a nextion, an ax206, it has a much more lower price point and will get integrated easier in a simrig.

**Comment by HKusp** [comment]
Thanks for looking at the request.
It’s a perfect size for RACELOGIC TIMER replica, and easy to mount for simrig.
There is a display workaround, but was hoping for native support.

**Comment by SHWotever** [comment]
Hi !

The support has been added for the next version !
