### ISSUE TITLE
Headlights and wet toggle

### ISSUE THREAD

**Issue by ez363** [SHWotever/SimHub#1256]
Hello,

How to find the right property to turn on the lights in Assetto Corsa?
moreover, is it possible to have a data on the % of water on the track?
I would like to be able to get this data on my dashboard like with the application "GT7HUD" which allows it (in LUA code).
I wonder why this is possible with LUA and not with SIMHUB?
I also tried to get this data via this application but it does not work (language problem I guess).

Thank you for your answer.

**Comment by SHWotever** [comment]
Hi ! GT7HUD is using CSP extensions, Simhub can't assume it's installed and have to only rely on vanilla game features. 
LUA is something provided by CSP, even if it's a must have extension it's too "invasive" to ask users to have it installed as a simhub prerequisite I'm sorry.

**Comment by ez363** [comment]
OK thanks for your quick answer.
