### ISSUE TITLE
Shortcut second widget

### ISSUE THREAD

**Issue by ez363** [SHWotever/SimHub#1257]
Hello,

New question concerning the management of widgets on my dashboard.
I want to add a second widget that I can control from my steering wheel.
This one like the first one, would be a sequence of informative panels (1 for the times, another for the radar, ...)
Today I have one and I change panel at each press of a button on my steering wheel.
Is it possible to have a second one?
And if yes, how to manage it?
I would have liked a button for the right panels and one for the left panels.
One "next screen" per side in fact.

Thanks

**Comment by SHWotever** [comment]
Hi !

You can set the next screen command for each widgets : 

![image](https://user-images.githubusercontent.com/2207331/226941519-bb044f89-4496-407d-ba9a-45486fe6d8af.png)

Typically ActionA,B,C,D are the best to control them independently

**Comment by ez363** [comment]
Ok, understand. Need to try, but ok for me.

Thanks again.
