### ISSUE TITLE
[BUG] SimHub v8.3.3 download from main site gets detected as severe threat in Windows

### ISSUE THREAD

**Issue by justforgithubandyou** [SHWotever/SimHub#1261]
**Describe the error** 
SimHub v8.3.3 triggers Windows Defender as a severe threat. I had trouble even downloading it. Running windows 11 with windows defender.

**Simhub version** 
Current= none. Was trying to install for the first time (v8.3.3)

**Reproduce** 
1.Download it.
2. Windows detects it as a threat as a download before it's even finished downloading. "Keep it anyway"
3. Windows Defender quarantines it as a severe threat when trying to run the program.

**Expected behavior** 
The installer to install without triggering Windows Defender.

**Screenshots** 
![image](https://user-images.githubusercontent.com/103540465/227796477-632f1dad-76f8-4a08-8a6a-ce9cdb2f993f.png)

**Log files** 
SimHub isn't installed.

**Comment by SHWotever** [comment]
Hi ! Defender had issues yesterday about false positives. They cleared it on the previous version, and on the next one it's still not triggering anything at date.
The details of previous yesterday submission : 
https://www.microsoft.com/en-us/wdsi/submission/c6806427-fcfa-4e7d-bf09-0c758dabe24f  

Could you try to flush and update defender as recommended by microsoft ? 
```

From an elevated command prompt, change to directory "%programfiles%\windows defender" and execute mpcmdrun.exe with option GetFiles:
cd "%programfiles%\windows defender"
mpcmdrun.exe -GetFiles
```

As a side information here is the scan from virus total I did before uplodading which came back perfectly clean : 
https://www.virustotal.com/gui/file/f4ef04c97eeede73b09d353baef3371250c16abe6aba8d37fede73bc6501c4e1?nocache=1

If you have specific issues maybe with an older defender database do not hesitate to report the false positive to defender team : https://www.microsoft.com/en-us/wdsi/filesubmission

Currently I don't have any false positives (tested on 4 computers) so I can't report it myself and give the appropriate information to Microsoft if required for your specific case.

**Comment by SHWotever** [comment]
I just submited the file to defender, I confirm that they does not detect it on up to date databases : 
![image](https://user-images.githubusercontent.com/2207331/227799291-703690a1-9133-422f-95b2-9ddac70c6d08.png)

**Comment by justforgithubandyou** [comment]
Okay, I’ll try this very soon and see if that fixes it.

**Comment by justforgithubandyou** [comment]
Although my device was just updated last night, this fixed it lol. Automatic updates aren't automatic it seems
