### ISSUE TITLE
RAR files not importing into simhub

### ISSUE THREAD

**Issue by WillixMax** [SHWotever/SimHub#1263]
**Describe the bug**
When downloading a file from race department like this [one ](https://www.racedepartment.com/downloads/simhub-universal-all-in-one-dashboard-gt3-f1.40581/) it downloads as a .rar file I then open the file using the SimHubWPF.exe. after doing so the app just pops up without adding the file or importing the dash.

**Simhub version**
8.3.3

**To Reproduce**
1. Go to '[race department dashboard link](https://www.racedepartment.com/downloads/simhub-universal-all-in-one-dashboard-gt3-f1.40581/)'
2. Click on Download
3. view download in folder
4. right click the file select open with SimHubWPF.exe
5. notice simhub pops up but doesnt show notification to import dashboard

**Expected behavior**
Simhub notification to import dashboard pops up and shows the dashboard in the app

**Screenshots**
![image](https://user-images.githubusercontent.com/92237305/228087667-9b3fedc2-99cd-4baa-83e3-90b9d6441b5f.png)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
[SimHub.log](https://github.com/SHWotever/SimHub/files/11083720/SimHub.log)

**Additional context**
other dashboard that I have imported use the .simhubdashboard file type and upload just fine using the same SimHubWPF.exe but for some reason the .rar files refuse to load in. Also when using the import dashboard function in the app it doesnt see the downloaded dashes in the downloads folder.

**Comment by WillixMax** [comment]
I think i may have resolved the issue. File may simply need to be unzipped by a third party zip software like 7zip and winzip if there is an easier way please let me know.

**Comment by SHWotever** [comment]
Hi it looks like your file associations were messed up, the dashs extensions are not rar and this format is not supported by simhub. I downloaded it and it's indeed a rar file so you have to uncompress it yourself first as you did. Then the files inside are indeed files which can be installed as dashs files like you ended doing.
