### ISSUE TITLE
74HC595 Chip Communication Issue

### ISSUE THREAD

**Issue by ZainKergaye** [SHWotever/SimHub#1265]
**Describe the bug**
I have tested for communication between the 74HC595 Chip and Arduino Nano (Old Bootloader). So far, I've tried every possible configuration and nothing seems to be working. Tried switching the pins to PWM supported ones, Wired the seven segment in relations to the version in the folder to no avail. I've tested with a multimeter trying to see what signals are even being put through but have found nothing. On the configuration I have just done the basics on just enabling the chip. I can't seem to get any communication. 

**Simhub version**
Latest version

**Expected behavior**
I am expecting communication but there is none.

**Comment by SHWotever** [comment]
Hi ! 74HC595  is bit hard to get working, lot of wiring, resistors etc ... but it has been left unchanged for many years so I doubt an issue has been introduced recently about it. Do you have more infos, pictures of the wiring ... Have you been able to make it work with some default arduino samples first ?

Nicolas

**Comment by SHWotever** [comment]
Maybe a very dumb question, before I dig in code, have you tried in game ? I've not touched this feature for many years but from memory out of game it just stays cleared. Only once in the game it will activate the display.

**Comment by ZainKergaye** [comment]
Here are links to a video of me playing in a game and with the arduino code working:
https://youtube.com/shorts/J98zXF7-_1I?feature=share
https://youtu.be/c65T3jIIQFo

**Comment by ZainKergaye** [comment]
I found the issue; I forgot how I found it but here is the working code segment in the DisplayManager.ino: 
`// --------------------------------------------------------------------------------------------------------
// 74HC595 Shift register, one 7seg module for gear indicator ---------------------------------------------
// DIY : http://lucidtronix.com/tutorials/2
// --------------------------------------------------------------------------------------------------------
// 0 disabled, 1 enabled
#define ENABLE_74HC595_GEAR_DISPLAY 1 //{"Group":"74HC595 Gear Display","Name":"ENABLE_74HC595_GEAR_DISPLAY","Title":"74HC595 gear display enabled","DefaultValue":"0","Type":"bool"}
#ifdef INCLUDE_74HC595_GEAR_DISPLAY
// Reverse led state
int RS_74HC595_INVERT = 0;
#define RS_74HC595_DATAPIN 4          //{"Name":"RS_74HC595_DATAPIN","Title":"DATA digital pin number","DefaultValue":"2","Type":"pin","Condition":"ENABLE_74HC595_GEAR_DISPLAY >0"}
#define RS_74HC595_LATCHPIN 3         //{"Name":"RS_74HC595_LATCHPIN","Title":"LATCH digital pin number","DefaultValue":"3","Type":"pin","Condition":"ENABLE_74HC595_GEAR_DISPLAY > 0"}
#define RS_74HC595_CLOCKPIN 2         //{"Name":"RS_74HC595_CLOCKPIN","Title":"CLOCK digital pin number","DefaultValue":"4","Type":"pin","Condition":"ENABLE_74HC595_GEAR_DISPLAY > 0"}
// RS_74HC595 DIGITS
// 0,1,2 ....
byte RS_74HC595_dec_digits[] = {1,79,18,6,76,36,32,15,0,4};
// Empty
byte RS_74HC595_ClearDigit = 0000000;
// R
byte RS_74HC595_ReverseDigit = 57;
// N
byte RS_74HC595_NeutralDigit = 9;
#endif // INCLUDE_74HC595_GEAR_DISPLAY

// --------------------------------------------------------------------------------------------------------
// 6c595 Shift register, one 7seg module for gear indicator ---------------------------------------------
// DIY : https://www.xsimulator.net/community/threads/12cm-12v-7segments-gear-indicator-with-gamedash.5747/
// --------------------------------------------------------------------------------------------------------
#ifdef INCLUDE_6c595_GEAR_DISPLAY
#define ENABLE_6C595_GEAR_DISPLAY 0 //{"Group":"6c595 Gear Display","Name":"ENABLE_6C595_GEAR_DISPLAY","Title":"6C595 gear display enabled","DefaultValue":"0","Type":"bool"}
#define RS_6c595_DATAPIN 11         //{"Name":"RS_6c595_DATAPIN","Title":"DATA digital pin number, can't be changed !","DefaultValue":"11","Type":"pin","Condition":"ENABLE_6C595_GEAR_DISPLAY>0"}
#define RS_6c595_LATCHPIN 13        //{"Name":"RS_6c595_LATCHPIN","Title":"LATCH digital pin number, can't be changed !","DefaultValue":"13","Type":"pin","Condition":"ENABLE_6C595_GEAR_DISPLAY>0"}
#define RS_6c595_SLAVEPIN 10        //{"Name":"RS_6c595_SLAVEPIN","Title":"SLAVE digital pin number","DefaultValue":"10","Type":"pin","Condition":"ENABLE_6C595_GEAR_DISPLAY>0"}
byte g_6c595fontArray[] = {
	// dp-a-b-c-d-e-f-g
	0b10100001, // 0
	0b00101000, // 1
	0b11001101, // 2
	0b01101101, // 3
	0b00101011, // 4
	0b01100111, // 5
	0b11100111, // 6
	0b00101100, // 7
	0b01111111, // 8
	0b01111111, // 9
	0b00000000, // OFF empty
	0b10000001, // REVERSE SPEED
};
byte g_6c595LEDarray; //computed order that will be sent to the LED display
#endif

#include "SHLedsBackpack.h"

#ifdef INCLUDE_74HC595_GEAR_DISPLAY
void RS_74HC595_SendData(byte data) {
	// take the latchPin low so
	// the LEDs don't change while you're sending in bits:
	digitalWrite(RS_74HC595_LATCHPIN, LOW);
	// shift out the bits:
	shiftOut(RS_74HC595_DATAPIN, RS_74HC595_CLOCKPIN, LSBFIRST, data);
	//take the latch pin high so the LEDs will light up:
	digitalWrite(RS_74HC595_LATCHPIN, HIGH);
}

void RS_74HC595_SetChar(char c) {
	byte data = 0;
	if (c == ' ') {
		data = RS_74HC595_ClearDigit;
	}
	else if (c == 'R') {
		data = RS_74HC595_ReverseDigit;
	}
	else if (c == 'N') {
		data = RS_74HC595_NeutralDigit;
	}
	else {
		int value = c - '0';
		if (value >= 0 && value < 10) {
			data = RS_74HC595_dec_digits[value];
		}
	}

	if (RS_74HC595_INVERT == 1) {
		data = data ^ 0xFF;
	}
	RS_74HC595_SendData(data);
}

void RS_74HC595_Init() {
	//set pins to output so you can control the shift register
	pinMode(RS_74HC595_DATAPIN, OUTPUT);
	pinMode(RS_74HC595_LATCHPIN, OUTPUT);
	pinMode(RS_74HC595_CLOCKPIN, OUTPUT);
	RS_74HC595_SetChar(' ');
}
#endif // INCLUDE_74HC595_GEAR_DISPLAY`

I'll make a PR for this.

**Comment by ZainKergaye** [comment]
Not sure where to contribute code to so If @SHWotever sees this then add that code. Thanks

**Comment by ZainKergaye** [comment]
[DisplayClientV2.zip](https://github.com/SHWotever/SimHub/files/11202146/DisplayClientV2.zip)


Here you are, you might see me tinkering with the other gauges; sadly they don't work
