### ISSUE TITLE
USBD480 not working since v.8.01.0

### ISSUE THREAD

**Issue by PelkoSVK** [SHWotever/SimHub#1267]
My new wheel with USBD480 screen is not working on Simhub since version 8.01.0.
On any earlier version (8.00.4 bellow) it is working flawlessly, even leds.

Problem:
Simhub is "searching" for this USBD480 and at the same time screen is flashing randomily. This search never stops.

Here is the video:
https://youtube.com/shorts/f1wTFpIt3pw

I have tried many different cables, two different computers, many different usb ports. There must be some bug in 8.01.0 and newer versions. 

Thank you

**Comment by SHWotever** [comment]
Hi ! Could you join the simhub log files? So I can take a look at what is happening?

**Comment by PelkoSVK** [comment]
Thank you for fast response.
Here it is. I am curious what you find out 👍 
https://pastebin.com/ZwakJ7hC

**Comment by SHWotever** [comment]
Hi ! I took a lok and I think that the profile is just corrupted, I had issues with some intermediate version fixed since, could you try to reinstall the latest version, delete the device and add it again ?

**Comment by PelkoSVK** [comment]
I have tried it with the latest 8.3.3 hotfix version several times but nothing - it is still the same - it wants to connect but without an success.
Something in 8.01 must have changed which broken this functionality. 
I am suprised that I am pretty much the only one with this problem, which is kind of a strange.

**Comment by SHWotever** [comment]
In fact this version of the usbd480 with integrated leds is extremely rare, it was only sold by SRH, and I did not had a chance to get one myself before it got discontinued making it extremely difficult to know if it's working or not.

I will look again if I can find some clues, 
In the meanwhile can you export the device from the lastest version ? 
![image](https://user-images.githubusercontent.com/2207331/229361786-d7ad27b3-bed5-4d66-9a06-6b81f64cad0a.png)

Maybe something is not initialized as I would expect it.

Nicolas

**Comment by SHWotever** [comment]
I think I unserstood ;) 

You are using the standard usbd480 profile while you are having the SRH LCD pro with embedded leds, 
This indeed tries to trigger the leds code while you are using a classic usbd480 device profile (with no leds) That would explain the crash. Can you try to remove the usbd480 profile and add an SRH G-force lcd pro instead ?

**Comment by PelkoSVK** [comment]
Omg you are right, it works! I bought recently this wheel (Sam maxwell smz1 f2) and I thought it is just a regular usbd480. Had no idea that I should use SRH LCD pro. 
Now everything works, LCD and also leds. Thank you, I did not wanna use their dashboard, so now I am happy camper :-)
