### ISSUE TITLE
Simhub loads very slow

### ISSUE THREAD

**Issue by hakanuzunoglu** [SHWotever/SimHub#1268]
When the loading screen states "Loading Arduino UI" it gets stuck for more than a minute

**Comment by hakanuzunoglu** [comment]
[SimHub.log](https://github.com/SHWotever/SimHub/files/11123176/SimHub.log)
There you go. Slow down happens at 17:48 pm

**Comment by hakanuzunoglu** [comment]
It was saying WMI repository is consistent. I reset anyway. It was still slow, but faster than last time.
[SimHub.log](https://github.com/SHWotever/SimHub/files/11123428/SimHub.log)

**Comment by hakanuzunoglu** [comment]
Well I have around 20 devices connected through USB, 4-5 arduinos as well. Will remove one by one and test. Thank you

**Comment by SHWotever** [comment]
I tried to redece to the scrict minimum the informations coming back from WMI for serial ports, hopefully if the faults was coming from a slow device it should help to get faster response.

Nicolas

**Comment by hakanuzunoglu** [comment]
Thank you. Is it with a new release?

**Comment by SHWotever** [comment]
It's not yet released. I don't know the exact release date yet. 

I've built a small test version including the fix : https://www.simhubdash.com/unofficial/SimHub.8.03.4b1_WMITest.zip

Please note this is a work in progress version, it may contain unstable changes, I'm still really early in the next release process and everything has not been deeply tested yet.

Let me know, I would perfectly understand if you prefer to wait for the next stable release.

**Comment by SHWotever** [comment]
Hi ! I've released the above improvement in the latest simhub version (8.3.6) can you confirm it's better now ?

**Comment by hakanuzunoglu** [comment]
While switching games it is almost instant.

The other loading time is better now, but not as fast as usual. I will
confirm further.
