### ISSUE TITLE
Simhub no me va

### ISSUE THREAD

**Issue by K0staaa** [SHWotever/SimHub#1272]
**Describe the bug**
![image](https://user-images.githubusercontent.com/130092087/230467513-54a0ef0e-b140-4edc-8f18-ef5abb911a6c.png)
Nada mas entro a Simhub y me sale esto y no me deja hacer nada
**Simhub version**
Make sure to run the latest version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by K0staaa** [comment]
Ayudadme porfa

**Comment by SHWotever** [comment]
Hi ? In order to help you could you join the log files available in C:\Program Files (x86)\SimHub\Logs ?

**Comment by K0staaa** [comment]
ok, y ahora que tengo que hacer??
![image](https://user-images.githubusercontent.com/130092087/230479813-131dab72-b027-45d9-9af4-c7b5403b407c.png)

**Comment by SHWotever** [comment]
Hi ! Ideally make a zip with all the files so I can review them all.

**Comment by K0staaa** [comment]
[SimHub.log.zip](https://github.com/SHWotever/SimHub/files/11174155/SimHub.log.zip)

**Comment by SHWotever** [comment]
Thanks for the logs.
Apparently you have installed a third party plugin named GarySwallow. It seems to miss some files to start correctly 
Could you try to delete this file : GarySwallow.PluginSdk.dll  it should solve the issue. 

Then once it's fixed you can reinstall correctly the plugin if you need it.

Nicolas

**Comment by K0staaa** [comment]
ahh si, instalé el garyshallow para una cosa del formula 1 pero lo borrare voy a hacerlo y ahora te digo

**Comment by K0staaa** [comment]
me sigue apareciendo lo mismo

**Comment by SHWotever** [comment]
Can you send me the new log files ?

**Comment by K0staaa** [comment]
los de antes?

**Comment by SHWotever** [comment]
The last one will be enough ;)

**Comment by K0staaa** [comment]
[SimHub.log (2).zip](https://github.com/SHWotever/SimHub/files/11174364/SimHub.log.2.zip)
aqui tienes

**Comment by SHWotever** [comment]
Apparently the plugin is still here, are you sure you removed the dll GarySwallow.PluginSdk.dll in C:\Program Files (x86)\SimHub ?

Make sure to kill the simhub process first using the task manager  then delete the file (renaming it is not enough, you need to delete it)

**Comment by SHWotever** [comment]
You need to  close simhub first using the task manager. As long as simhub is running the file will be locked.

**Comment by K0staaa** [comment]
ok, ya lo elimine, ahora que tengo que hacer?

**Comment by SHWotever** [comment]
You can restart simhub it should not get stuck anymore.

**Comment by K0staaa** [comment]
ya se soluciono

**Comment by K0staaa** [comment]
muchisimas gracias de verdad ns como agradecertelo, llevaba tiempo buscando la forma de arreglarlo

**Comment by K0staaa** [comment]
ya podria descargar otra vez el gary swallow?

**Comment by SHWotever** [comment]
You can try to reinstall it, but make sure to follow exactly the install instructions. 
If somehow it does not work you can delete it again like you just did by removing the dll file.

**Comment by K0staaa** [comment]
ok muchisimas gracias
