### ISSUE TITLE
[BUG?] Page conditions in widgets without function?

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1273]
I created a widget with different pages. One page shows ERS status for AMS 2 and AC. 
From the description I understand if the condition is false the page should not show up yet
if I test the dashboard the page is always showing up, not matter if the condition is true or false.

Is this a bug ?
Here are some screenshots (I test with isnull and without)
https://imgur.com/a/KLFk1Nd

**Comment by hakanuzunoglu** [comment]
Can confirm, it works as described on main screens but not widgets.

**Comment by SHWotever** [comment]
Hi !

Indeed I confirm roles and activations were ignored in widgets, I added an option to run them :

![image](https://user-images.githubusercontent.com/2207331/231741681-0226b0bc-cc2d-4459-9b98-7e6d6225e838.png)

On previously created dashboards it will stay disabled until explicitely checked to avoid regressions, on newly added widgets components it will be enabled by default.
