### ISSUE TITLE
CSX3 / VCORE display not working

### ISSUE THREAD

**Issue by TheSimDoc** [SHWotever/SimHub#1274]
**Describe the bug**
The VCORE display on my CSX3 does not work anymore woth SimHub.

**Simhub version**
8.3.6

**To Reproduce**
CXS3 status on top is "Parially Connected". Connection Status is "Searching Device ..."
The display shows some artefacts of the intended dashboard  or loading screen.
Testing the screen with v2scrctl.exe works as long as SimHub didn't access the display.
The rest of the CSX3 works as expected (LEDS, Buttons).
Reinstallation of display driver does not help.

**Expected behavior**
A working display.

**Screenshots**
![image](https://user-images.githubusercontent.com/4328198/230742614-7fb7c761-eb87-4ece-af8e-e79c7a0ddf78.png)

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/11184243/SimHub.log)

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Apparently the screen does not hold when bandwidth is going higher (test app only sends a single static frame)
I've linked a few advices about how to solve similar issues: 
https://github.com/SHWotever/SimHub/wiki/Dashstudio---USB-Displays#vocore-testing

Of you were using a hub or an extension cable it might have been working perfectly earlier but not anymore .

If it's not enough do not hesitate to contact cube control support so they can sort this issue with their hardware.

Nicolas
