### ISSUE TITLE
Add a fourth monitor in the Monitor Options

### ISSUE THREAD

**Issue by Weini1972** [SHWotever/SimHub#1275]
Could you be so kind and add a fourth monitor in the Monitor Option under the Dash Studio/Settings window?
Would be great!
Thanks a lot :-)

**Comment by SHWotever** [comment]
Hi ! This will be possible in the incoming v9 version (with much more possibilities)

**Comment by Weini1972** [comment]
Hi.

 

Thanks for your fantastic work and great support.

It works great and is now so much more fun to race with your tool.  

I have sent you a donation for this.

I think it can only be too small for what you offer in support.

 

Kind regards

Hans

 

Gesendet: Mittwoch, 30. August 2023 um 16:12 Uhr
Von: "Wotever" ***@***.***>
An: "SHWotever/SimHub" ***@***.***>
Cc: "Weini1972" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [SHWotever/SimHub] Add a fourth monitor in the Monitor Options (Issue #1275)


 

Hi ! This will be possible in the incoming v9 version (with much more possibilities)

**Comment by Weini1972** [comment]
Hi,

 

Its me again. Sorry :-)

 

Just for your Information.

I send you the donate over the get a new licence oder, becaus i can`t find an other way.

 

Thans a lot  once more

 

Regards

Hans

 

 


Hi.

 

Thanks for your fantastic work and great support.

It works great and is now so much more fun to race with your tool.  

I have sent you a donation for this.

I think it can only be too small for what you offer in support.

 

Kind regards

Hans

 

Gesendet: Mittwoch, 30. August 2023 um 16:12 Uhr
Von: "Wotever" ***@***.***>
An: "SHWotever/SimHub" ***@***.***>
Cc: "Weini1972" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [SHWotever/SimHub] Add a fourth monitor in the Monitor Options (Issue #1275)


 

Hi ! This will be possible in the incoming v9 version (with much more possibilities)
