### ISSUE TITLE
Arduino disconnecting after 8.3.6

### ISSUE THREAD

**Issue by alexdoro23** [SHWotever/SimHub#1276]
After 8.3.6 my arduino keeps disconnecting after I move from a game to another.
I have a 10.5 DDU with 28 leds.

First time this happens. 
To solve it I have to restart simhub [everytime.
![8 3 6 arduino disconnecting](https://user-images.githubusercontent.com/130524782/231332799-249c49bd-752c-49e1-8019-41108f8035f2.png)

**Comment by SHWotever** [comment]
Hi !

I found an issue affecting the ATMEGA32U4 (pro micro, leonardo) can you confirm it's the model of arduino you are using ?

**Comment by herve4545** [comment]
je l'ai également reproduit sur mon onesimpro vocore 5 + 20 leds sur simhub V8.3.6

je débranche et rebranche le cable usb et le problème est résolu

![1](https://user-images.githubusercontent.com/58605557/231401655-437bb972-3046-430c-b250-e21eb51a7005.jpg)
[SimHub.log](https://github.com/SHWotever/SimHub/files/11209033/SimHub.log)

**Comment by alexdoro23** [comment]
Bug still persists for me.

**Comment by alexdoro23** [comment]
I will check but the driver is ch34 something.Its the simracingaddict DDU 10.5 with 28 ledsSent from Android deviceEm 12 de abr. de 2023 04:27, Wotever ***@***.***> escreveu:
Hi !
I found an issue affecting the ATMEGA32U4 (pro micro, leonardo) can you confirm it's the model of arduino you are using ?

**Comment by herve4545** [comment]
@alexdoro23 
![1](https://user-images.githubusercontent.com/58605557/231711090-a1313522-6bb7-46ed-98df-917ea6238d34.jpg)

**Comment by SHWotever** [comment]
Hi ! I released an update, I guess it was an atmega32u4 too as it's the only kind of arduinos where I could detect this issue.

**Comment by SHWotever** [comment]
Thanks for the feedback !

**Comment by herve4545** [comment]
issue resolved for me
