### ISSUE TITLE
Bug in version 8.3.6

### ISSUE THREAD

**Issue by hugodanilosanchezmayorga** [SHWotever/SimHub#1277]
**Describe the bug**
Fixed the problem of not turning off the led spotlights when turning off windows very well, but now with version 8.3.6 when playing wrc generations, the second screen where the dashboard model is loaded tends to turn off and reconnect in such a way that it pauses the game and minimizes it, I hope it is solved thanks.

**Simhub version**
8.3.6

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Can you join the simhub log files when this happens do I can take a look ?

**Comment by SHWotever** [comment]
Log files are available in C:\Program Files (x86)\SimHub\Logs

**Comment by herve4545** [comment]
Hello
I have the same issue on my vocore on rf2
leds turn off
I disconnect and reconnect usb cable

[SimHub.log](https://github.com/SHWotever/SimHub/files/11208515/SimHub.log)

**Comment by SHWotever** [comment]
@herve4545 Looks like more related to this issue ? https://github.com/SHWotever/SimHub/issues/1276

**Comment by herve4545** [comment]
Oui peut-être
Je regarderai la prochaine fois que ca se produit
