### ISSUE TITLE
Name Style in Leaderboards

### ISSUE THREAD

**Issue by Weini1972** [SHWotever/SimHub#1280]
Is it possible to extend the option of 
Full and Initials to add first letter first name. complete last name in the NameStyle field in the LeaderboardOpponentNameText (OpponentName) text box?

So that in the leaderboard e.g. the driver name then J. Krohn is displayed instead of the full name Jesse Krohn.
Should be valid for player and opponent.
![Screenshot Leaderboard](https://user-images.githubusercontent.com/96842558/232337069-886ec609-e57b-4f13-8843-b4573349cee5.jpg)

Thanks a lot!

**Comment by SHWotever** [comment]
Hi ! I added the new name style (ShortName) for the next version.

**Comment by Weini1972** [comment]
Hi!


 

Thank you very much for this!

There is now much more room and thus more options to display multiple functions in one dashboard.

 

Kind regards

Hans

 

Gesendet: Dienstag, 27. Juni 2023 um 13:45 Uhr
Von: "Wotever" ***@***.***>
An: "SHWotever/SimHub" ***@***.***>
Cc: "Weini1972" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [SHWotever/SimHub] Name Style in Leaderboards (Issue #1280)


 

Hi ! I added the new name style (ShortName) for the next version.
