### ISSUE TITLE
[Feature request] VTOL VR game support

### ISSUE THREAD

**Issue by bizibiz** [SHWotever/SimHub#1281]
Hello Wotever,

First, as an official licence owner, thanks for your great app, I'm using it for all my sims.

However, I'm falling in love for VTOL VR recently. Can you please consider to add this game as it support telemetry export via UDP ? I would love to feel some vibrations (using shakeIt) under extreme G-forces.

Please find here the link to the extension allowing the telemetry to be read out :
https://vtolvr-mods.com/mod/usetddjq/
and the GitHub rep here :
https://github.com/nebriv/vtolvrTelemetry

Many thanks if you can consider it.
Regards.

**Comment by bizibiz** [comment]
Sorry, maybe this link could be more helpful.

https://github.com/nebriv/vtolvrTelemetry

Regards.

**Comment by SHWotever** [comment]
Hi ! Currently I'm keeping SimHub focused on Sim racing games, opening the pendora box with VTOL would involve to add supports for FS, XPlane and many others. But it's not only a matter of adding a game, I have to build all the "features" around it, dash studio, shakers etc .... From my experience there are lot of subtilities in Flight sims( engines, flaps, controls) ... And it will be hard to do both sim racing and flight sims at the same time. Motion dedicated software can do it as they only use few data, but Simhub is much wider now.

**Comment by bizibiz** [comment]
Hi, thanks for your reply.

I'm not a dev but I've some basic programming skills, can we develop a custom plugin to support VTOL VR in SimHub and pass the values to GameData.GlobalAccelerationG ?

**Comment by SHWotever** [comment]
Hi ! 

The game reader api is not public i'm sorry.
