### ISSUE TITLE
Edit layout button (adalight) is not clickable

### ISSUE THREAD

**Issue by Paul-VW** [SHWotever/SimHub#1285]
**Describe the bug**
Version 8.3.7 shows up as 8.3.6

**Simhub version**
8.3.7

**To Reproduce**
Bottom left statusbar shows wrong version, logfile shows wrong version

**Comment by SHWotever** [comment]
Hi !

Looks like something is happening in the installer. 

Can you try to do the follwing steps ?
- Close simhub 
- Delete simhubwpf.exe (in the install directory, usually c:\Program Files (x86)\SimHub) 
- Install 8.3.7 from a fresh download (ie https://github.com/SHWotever/SimHub/releases/download/8.3.7/SimHub.8.03.7.zip)
- Make sure the files are installed in this folder (new  simhubwpf.exe will be written)
- Now start simhub directly using simhubwpf.exe 

-Does the new files get properly written and the version shown is correct ?
- If not have you moved the simhub installation folder manually ? In such case the installer will remember the proper install folder and won't overwrite your moved folder.

**Comment by Paul-VW** [comment]
Removed the simhubwpf.exe-file and re-installed. Version is now correct, so that seems to solve this issue.

Unfortunately still not able to edit led layout in adalight (Ambient Light). I was hoping that 8.3.7 would solve that issue, but unfortunately still no luck with that part.

**Comment by SHWotever** [comment]
Hi !

Thanks  for the report, I fixed the edit layout button for the next version.
