### ISSUE TITLE
PC performance down due to simhub error

### ISSUE THREAD

**Issue by korcorn** [SHWotever/SimHub#1286]
**Describe the bug**
cpu performance of wmi provider host in windows is very high due to simhub error, resulting in poor performance of pc.

**Simhub version**
Recognized from 8.3.6, 8.3.7 and not tested from previous versions

**To Reproduce**
Can be checked in Task Manager after running simhub

**Expected behavior**
PC performance down

**Screenshots**
![image](https://user-images.githubusercontent.com/131471502/233675152-bc15d13e-a8fd-4939-877f-b7a9360c9f82.png)
![image](https://user-images.githubusercontent.com/131471502/233675207-79125890-5e9c-4f92-942d-c7b8549f0f44.png)
![image](https://user-images.githubusercontent.com/131471502/233676548-f2829a1b-65e2-40c0-9c9e-4fb2c4822249.png)
![image](https://user-images.githubusercontent.com/131471502/233675245-4a4c5288-5ff3-47b7-b279-782ab581641c.png)
![image](https://user-images.githubusercontent.com/131471502/233675323-c1dbcab8-0304-4fac-a538-79274e8add9f.png)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**
[SimHub.log](https://github.com/SHWotever/SimHub/files/11297183/SimHub.log)

**Comment by SHWotever** [comment]
Hi !

I see two issues, ther errors from the simhub log comes from a third party plugin Gary Swallow plugin you can disable it in the setttings.

About WMI indeed it seems that your windows wmi repository is broken and is missing some indicators. You can disable those requests by disabling the simhub system infos provider in the settings here, then simply restart simhub, it will be enough to disable this request : 
![image](https://user-images.githubusercontent.com/2207331/233678521-fbd96645-fe3a-4dd2-a7e4-4a19b99305ae.png)

Alternatively there are guides available online about how to fix a WMI repository.

**Comment by korcorn** [comment]
Thank you for your quick response.
It has been resolved.
