### ISSUE TITLE
Can't do a PR but please add warnings for Arduino nano servo users. 

### ISSUE THREAD

**Issue by ZainKergaye** [SHWotever/SimHub#1288]
Recently I've been trying to get a dashboard from scratch and I hit a block that confused me. The PWM frequency was going 2x the usual for any basic hobby grade servo. Turns out the analogWrite function referenced in your SHPWMPin.h library, detailed by the official docs, does this on purpose. Took me like 2 weeks to figure out. Please update description so others don't fall into my trap. 

Board: Arduino Nano (old bootloader) 
Reference: https://reference.arduino.cc/reference/en/language/functions/analog-io/analogwrite/

**Comment by ZainKergaye** [comment]
Nvm i'm still getting the project fixed; give me a week or so.

**Comment by SHWotever** [comment]
Hi ! SHPWMPin with frequency tuning is only part of the simhub core, this is not a end user function,frequency tuning is not used in most cases, frequency tuning only happens for the boost gauge. I'm not sure what kind of warnings I would/should add.

About servos there is some libraries taking care of it https://github.com/arduino-libraries/Servo, I'm not sure servos are handling nively native PWM frequencies of atmega. Looking at the library it make uses of timers to get something more appropriate with servos.

**Comment by ZainKergaye** [comment]
Nah I fixed the issue on my side, I didn't know custom protocol was a thing. I got it all sorted out now. Thanks tho.
