### ISSUE TITLE
Javascript binding 

### ISSUE THREAD

**Issue by nipsterx93** [SHWotever/SimHub#1295]
Hello, 

I'm facing a strange issue when I try to write any formula inside the dashboard bindings menu. It seems like it doesn't matter what code I write, on the Raw Result I'll always get "Expression error:Line 33': Unexpected token *" even though in many cases I do not have a line 33. 

I get this error as soon as I start typing, plus, even tested formulas ( from other users) wont work at all. 

Ncalc works fine, Javascript doesn't work at all. 

It would be amazing if you could dig into this. Thanks.

**Comment by SHWotever** [comment]
Hi ! do not hesitate to check you don't have any invalid scripts inside the javascriptextensions folder. Those scripts get loaded on top of any JS formulas, it's likely to be your culprit.

**Comment by nipsterx93** [comment]
Hi, thanks for the answer. I believe you are spot on, I reinstalled SimHub
and now it works perfectly so I guess there was some Javascript extension
that caused the issue. Thanks for your support.

Il lun 8 mag 2023, 11:03 Wotever ***@***.***> ha scritto:

**Comment by SHWotever** [comment]
Thanks for tyour feedback !
