### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by Royzhang14444** [SHWotever/SimHub#1296]
**Is your feature request related to a problem? Please describe.**
Hi, I plan to build a shakelt motor radar, which means that I want to put two motor under my car seat and if there is a car on the left, the left motor will shake, etc. The problem is that in the availabe properties, I cant find a property that can capture whether there is a car on my left or right. Could you please let me know which property should I use?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FullPace** [comment]
search for spotter

**Comment by SHWotever** [comment]
Hi Indeed this feature is already available : 
![image](https://user-images.githubusercontent.com/2207331/236782682-8d1507c2-eb1d-45e5-857e-c4167104ebc6.png)
