### ISSUE TITLE
[Feature request] - Allow UDP connections from remote host on all UDP Telemetry supported games

### ISSUE THREAD

**Issue by Shambler2** [SHWotever/SimHub#1297]
Hi, thanks for the fantastic software, looking forward to using it with my sim-rig!

### SimHub Use case / Background Info:
My sim-rig setup is a little different to most, I have a gaming PC setup in one room, with the racing setup in another room, and use NVIDIA gamestream or Parsec to stream game video & audio to a miniPC on the sim-rig. To support the wheel, I use Virtualhere to attach the Logitech G27USB device over the network to the gaming PC. I have configured it this way due to extreme space limitations and to utilise my already available gaming PC. My primary use case for SimHub is to provide tacticle feedback (ShakeIt), and not dash features which I understand I could use web-hosted dash features as per issue #371 

### Issue faced:
The issue I'm currently facing is that when opening the UDP listening port for certain games (e.g. BeamNG), SimHub only opens the UDP listener to localhost (confirmed with netstat). I've observed that when testing Forza Horizon 5(FH5), SimHub will instead open the listener to all networks (0.0.0.0), presumably to allow an Xbox copy of the game to provide the needed telemetry. 

Because of the restricted UDP listener, I am unable to connect to the game's telemetry on this miniPC, and utilise the sound card attached to the miniPC to provide the required effects.

### Requested Feature/change: 
I'm hoping one of the following changes could be made in a future release to support my scenario:
- Allow UDP connections from any network address on all games that utilise UDP telemetry ONLY (realise this wouldn't work for games which SimHub monitors the processes memory)
- Alternatively, allow the user to open UDP connections from any host in a config file or on the configuration page (if concerned about security with defaulting to accepting connections from remote hosts)

### Testing/Workarounds already identified
- I've confirmed with my testing that FH5 already behaves as required, and that it is fully functional in my setup.
- I've confirmed that the Windows Firewall is not blocking traffic on either end, both with explicit firewall exceptions configured, and also completely disabling all firewalls on both ends
- I've confirmed that BeamNG successfully streams the required telemetry data to the miniPC as per its inbuilt Outguage support 
- I have also been able to confirm that with the use of 3rd party software to proxy UDP data that I can listen and forward the required data for BeamNG to SimHub, though with additional latency compared to the native support SimHub provides for FH5

Thanks very much! Happy to test anything with my setup if it helps!

**Comment by SHWotever** [comment]
Hi ! I checked BeamNG (and lfs as they use the same protocol) where indeed bound to 127.0.0.1, I changed it to be 0.0.0.0 for the next version, it was not an intentional choice, just a "it is on the same computer" reflex :)

**Comment by Shambler2** [comment]
Excellent! Glad it was a simple fix, appreciate how fast it can be sorted out

**Comment by SHWotever** [comment]
Hi ! I close it ;) This was released in the lastest simhub update.

**Comment by Shambler2** [comment]
Hi! I realised I never provided feedback after the new version was released - everything works perfectly, so thankyou!

Now I need to work out how to make games like AC work with my weird setup :)
