### ISSUE TITLE
[Feature request] support for more hardware sensors from Aida, etc.

### ISSUE THREAD

**Issue by betaeffect** [SHWotever/SimHub#1301]
It would be nice, if SimHub could support more than the five or so sensorinputs from Aida or other hardwaremonitoring-software to show on a dashboard. 

In the latest version, Aida supports the VoCore display but with another driver than SimHub, so I have to reinstall the USB-drivers everytime I want to us my dashboard as a hardware-monitoring-display.

If SimHub would support more custom sensorinputs, like networkspeed, clockspeeds, etc from Aida, I don't have to reinstall drivers all the time.

**Comment by SHWotever** [comment]
Hi ! You have access to all the available properties already. SimHub offers a short list of "standard" properties for easy provider switching, But everything give by aida is accessible directly :
You need to activate everything you need first in aida :
![image](https://user-images.githubusercontent.com/2207331/236837422-432f02b0-e056-4704-9548-264510e4840e.png)

Then restart simhub to update the list : 
![image](https://user-images.githubusercontent.com/2207331/236837660-27c70654-0003-4e44-9fb4-9ca3b9c5c2f9.png)

Then you can use everything in a dashboard etc ...

NB : That's sad that aida uses a different driver, the one I'm using and I've built is now recommended by vocore themselves as it's more stable than any others.
