### ISSUE TITLE
dirt rally 2.0 problem

### ISSUE THREAD

**Issue by cflot** [SHWotever/SimHub#1302]
hello
Suddenly from previous week (maybe after windows 10 latest update - not sure) in Dirt Rally 2.0 (exactly when I start any stage), all my USB devices (sometimes wheel, sometimes pedals etc) start to disconnect when the Simhub is open. When I close it all runs fine.
I reinstall everything (usb drivers, fanatec wheel drivers) but the problem continues.
I didn't have any problem till the 8.3.9 version. 
The interesting is that tonight I install again the oldest 8.3.6 version (which worked fine) and the problem exists.
My racing setup is
Fanatec Clubsport V2.5 Wheel (USB)
Fanatec Handbrake (USB)
Pedals VPP (BUO836A) (USB)
SSH Shifter (USB)
Arduini micro racing panel (USB)
Tachometer Simdash (USB)

**Comment by SHWotever** [comment]
Hi ! 

Based on your diagnostic it's not a software issue as the older version does not change it. I would try to remove any simhub driver devices one by one. It looks like a failing/overloaded usb hub for instance.

Can you also send me the log files to see the global simhub trace ?

**Comment by cflot** [comment]
I found these 3 log files in simhub dir...hope to be the right ones (otherwise please send my instructions where to find them).
Everything worked fine till previous week, I didn't install anything new just the 8.3.9 version and win10 latest update automatically.I also changed the usb hub that I use for my racing equipment - the same happens.
Exactly the previous Thursday night, I opened Dirt Raly 2.0 did 2 stages with Simhub and basshakers without pronlem, but in third suddenly the devices started to disconnect.From then every time that a stage is started the same happens.Hope to find the solutionRegards

   On Monday, May 8, 2023 at 10:31:08 PM GMT+3, Wotever ***@***.***> wrote:  
 
 


Hi !

Based on your diagnostic it's not a software issue as the older version does not change it. I would try to remove any simhub driver devices one by one. It looks like a failing/overloaded usb hub for instance.

Can you also send me the log files to see the global simhub trace ?

**Comment by SHWotever** [comment]
Hi ! Unfortunately attachments does not work with emails, can you join it directly on GitHub?

If you are using a usb hub have you tried to move some of the devices away from it ? If it totally give sup (which would explain the global failure of all the devices at once) it often means one or more devices is stressing it too much. The best way is to proceed by elimination, moving and or unplugging it one by one.

**Comment by cflot** [comment]
maybe as rar?
   On Monday, May 8, 2023 at 11:00:19 PM GMT+3, Wotever ***@***.***> wrote:  
 
 


Hi ! Unfortunately attachments does not work with emails, can you join it directly on GitHub?

If you are using a usb hub have you tried to move some of the devices away from it ? If it totally give sup (which would explain the global failure of all the devices at once) it often means one or more devices is stressing it too much. The best way is to proceed by elimination, moving and or unplugging it one by one.

**Comment by SHWotever** [comment]
As a zip directly on the GitHub website ;) Direct email reply doesn't allow any attachments to go through.

**Comment by SHWotever** [comment]
Hi ! 

I took a look at the logs and I confirm my first diagnostic, I see all the devices failing, this really looks like an usb/emi issue. 
The best way is to proceed by elimination, moving and/or unplugging devices one by one. Such failures are most of the time linked to failing usb connections (overloading/parasites/EMI) and can often be solved by rearranging all the USB connections.

And as you pointed rollbacking to an older version did not help, which makes sense as it's linked to the hardware.

**Comment by cflot** [comment]
hello againIs it possible a damaged bass shaker to create the problem?Regards
   On Sunday, May 14, 2023 at 09:26:34 PM GMT+3, Wotever ***@***.***> wrote:  
 
 


Closed #1302 as completed.
