### ISSUE TITLE
ACC+SIMHUB plantage 

### ISSUE THREAD

**Issue by maboule77** [SHWotever/SimHub#1303]
**Describe the bug**

Bonjour , je vient demande de l'aide , car j'en ai marre de m'entendre dire que je dois mettre à jour ma GPU ! 
Voilà mon souci , si je joue a ACC tout va bien , mais entre temps j'ai mit 4 bass sheker via carte son nobsound ! 
quand je paramètre mon profil dans Sim hub tout va bien , les cartes son,  sont reconnue en bluethoot , les bass shekers réponde au test , toute es parfait ! 
Sauf que quand je lance les deux ensemble ( Acc et simhub ) , cela plante  , j'ai l'écran de teste du jeux et puis plus rien cela frisse , je dois passer par crtl alt del pour sortir ! 
Et ensuite à la relance de ACC même sans Simhub allumer il ne veux plus non plus ! 
J'ai tester de le lancer depuis Steam , depuis Moza , depuis Simhub , c'est à chaque fois la même chose ! 
Je ne sais plus quoi faire et ou chercher non plus car suis pas un grand informaticien :( , on fait le bea ba ! 

Matériel Core I7 13700 k , 32 gp de ram , et une 3090 geforce nvidia 

pédalier P2000 simagic 
volant et freins à mains Moza R16 + roues gt et road 
Triple screen gigabyte 32

**Simhub version**
Make sure to run the latest version , oui télécharger sur votre site 

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen. je veux juste jouer !

**Screenshots**
If applicable, add screenshots to help explain your problem. un triple screen qui reste figé , il ne faut pas de photo 

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
[SimHub.7.txt](https://github.com/SHWotever/SimHub/files/11426557/SimHub.7.txt)
[SimHub.8.txt](https://github.com/SHWotever/SimHub/files/11426558/SimHub.8.txt)
[SimHub.9.txt](https://github.com/SHWotever/SimHub/files/11426559/SimHub.9.txt)
[SimHub.10.txt](https://github.com/SHWotever/SimHub/files/11426560/SimHub.10.txt)
[SimHub.11.txt](https://github.com/SHWotever/SimHub/files/11426561/SimHub.11.txt)
[SimHub.PackageManager.Standalone.1.log](https://github.com/SHWotever/SimHub/files/11426562/SimHub.PackageManager.Standalone.1.log)
[SimHub.PackageManager.Standalone.2.log](https://github.com/SHWotever/SimHub/files/11426563/SimHub.PackageManager.Standalone.2.log)
[SimHub.PackageManager.Standalone.3.log](https://github.com/SHWotever/SimHub/files/11426564/SimHub.PackageManager.Standalone.3.log)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/11426565/SimHub.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/11426566/SimHub.1.txt)
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/11426567/SimHub.2.txt)
[SimHub.4.txt](https://github.com/SHWotever/SimHub/files/11426568/SimHub.4.txt)
[SimHub.5.txt](https://github.com/SHWotever/SimHub/files/11426569/SimHub.5.txt)
[SimHub.6.txt](https://github.com/SHWotever/SimHub/files/11426570/SimHub.6.txt)

**Additional context**

**Comment by maboule77** [comment]
Merci de la réponse rapide , vous êtes plus réactif que les grandes boites !! 
J'ai effectivement quelques soucie avec les cartes NS , elle devrais t'être câbler en usb ( car de plus j'ai tiré 7 usb depuis mon pc pour que chaque périphérique soit brancher en filaire ) , mais mon windows les reconnais et ensuite il l'est mets en défault , d'ou je suis obligé de passer en bluethoot avec les NS ! 
Je vais donc voir comment mettre ou réussir à les branchers en USB ! 
En espèrant que je trouve sous peux et rapidement , fait 4 mois déjà que l'on galère avec le simu !

**Comment by herve4545** [comment]
si ca peut aider
j'ai 10 bass_shakers avec 5 amplis comportant une carte son
chaque ampli est branché sur cette carte PCI-e Carte USB 3.0 5 Ports
https://www.amazon.fr/gp/product/B00FPIMJEW/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

les amplis
https://www.amazon.fr/gp/product/B071S6ZWRQ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

j'ai renoncé à tout brancher sur un hub usb car trop de déconnexions

**Comment by maboule77** [comment]
merci bcp des info et aide , quand tout fonctionnera ( je me le souhaite ) , je soucrirais mon affilitation pour kkl café alors

**Comment by maboule77** [comment]
MAJ , les ampli enfin reconnue en usb dans SimHub ! 
donc j'ai bien un soucie d'alimentation d'usb ! :( 
Donc me reste à prendre des autres cables usb amplifier , et je pense que cela devrais le faire !
