### ISSUE TITLE
Update/rollback port driver for Simhub

### ISSUE THREAD

**Issue by paulkebab1** [SHWotever/SimHub#1305]
I have this bug too, wherein the Arduino doesnt recognise the port. I followed the advice given by SHWotever but there was no option to rollback the driver, and I didn't want to use a system restore point. 
There is a driver download page here at Microsoft https://www.catalog.update.microsoft.com/Search.aspx?q=CH340 I just picked the latest 2019 driver and downloaded it. Force Windows to use it from device manager and Arduino works again.

**Comment by SHWotever** [comment]
Hi ! Was your ch340g chip unlabeled? I'm still trying to collect informations about the kind of chips affected and confirm that it's tied to fake chips, even if on the simhub side there is nothing I can do (it's an hardware vs driver issue)

**Comment by paulkebab1** [comment]
The chip in mine is labelled AIMEL MEGA 328P then numbers. Up until the Windows update it was perfect, the seller I purchased it from pointed me back here to resolve the issue.

**Comment by paulkebab1** [comment]
There was an update earlier this morning (KB5026372) which hasn't updated the port driver thankfully but I have the old driver on my desktop ready to downgrade to.

**Comment by SHWotever** [comment]
The 328p is the MCU, the serial chip is different, the location depends of the board.

The seller redirected you to me to solve a fake chip issue? That's really unfair. You probably paid a significant price (it's often the case unfortunately) and you got a very low cost arduino with fake serial chip with no help :(

**Comment by paulkebab1** [comment]
Ah if you mean the 16-pin chip on the reverse side of the board.. no there is no number.

**Comment by SHWotever** [comment]
Indeed that's it. Another counterfeit chip :( it's hitting hard since those last days I'm not sure if the manufacturer did broke them intentionally, bit the result is here.

I will add more warnings about that, that's the best I can do ;)

**Comment by paulkebab1** [comment]
So is it just a case of swapping this chip out with a genuine one?
________________________________

**Comment by SHWotever** [comment]
Hard to swap the chipit needs some good soldering knowledge, the easiest way is to swap the whole Arduino with a proper one (lot of clones don't use fake chips, I don't claim that clone= fake, better be accurate here :D) and flash it with the right firmware.

**Comment by SHWotever** [comment]
If you are interested I opened a Reddit thread a few days ago about those fake chips issues https://www.reddit.com/r/arduino/comments/139vfux/is_ch340g_a_new_ftdigate_latest_windows_drivers/

That's totally out of my responsibility, but I'm still interested to understand perfectly how wide is this issue.

**Comment by paulkebab1** [comment]
OK many thanks for that, the chip is about £2 and I can plant that at work so I'll take a chance if the driver keeps playing up.
