### ISSUE TITLE
rFactor2 closes after about 1 and 2h

### ISSUE THREAD

**Issue by MadMaxHDX** [SHWotever/SimHub#1309]
Describe the bug
After I am in a lobby for about 1 to 2 hours and drive on the server, rFactor2 freezes at some point but the sound continues. After that, rFactor2 closes without an error message. I've had the whole thing several times now and uninstalled Simhub because it didn't happen before. I got the Ascher Dashboard and therefore never used Simhub before. 

**Simhub version**
8.3.10 – 08/05/2023

**To Reproduce**
Drive rFactor2 about 1 to 2H

Is anybody else having these problems?

**Comment by SHWotever** [comment]
Hi !

This looks like a graphics crash. Simhub does not have any direct interactions with the game except the plugin (which might be still running despite having simhub uninstalled. Are you stil having this issue, does disabling the plugin solves it ? When using an usb display simhub uses very little the gpu (just the UI is running on it, but it's a standard ui framework from Microsoft) I've updated the rf2 plugin to the latest version recently but I didn't had similar reports yet. As is I would think just as an unfortunate coincidence.
