### ISSUE TITLE
Updated to 8.3.10, SH doesn't work with LFS anymore

### ISSUE THREAD

**Issue by kizuna-7** [SHWotever/SimHub#1310]
Hi, since upgrading to 8.3.10 I'm getting those messages on LFS.
May 17 17:37:03 InSim - TCP : bind failed
May 17 17:37:03 InSim : not initialised

I'm aware of the change "OutGauge (LFS, BeamNg) now binds to any IP instead of being restricted to 127.0.0.1 (local computer)" but I don't understand what I have to do in order to get it working again like it was previously.

Thank you.

**Comment by SHWotever** [comment]
Hi !

Apparently it's the game itself which can't start the insim module 
Simhub uses two endpoints :
- "insim" which runs on TCP port 29999 
- "outgauge" which runs on UDP. 
It's the last one which has been changed, but the first one which can't start in your case.
I just verified just in case everything went fine on a fresh LFS setup, both were connecting. 

As it is I would think another application is using the TCP port 29999 preventing LFS to start this module. 

To check it you can start perfmon (win+r, type _resmon.exe_ and validate)
Then go in the network tab sort by "local port", and look for anything using 29999, in my case it's LFS as it was free to take and LFS initilization went fine, but I guess in you cae something else is "stealing" it : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/dad799c4-8ce3-420a-bdb3-6f081848a915)

Let me know.
Nicolas

**Comment by kizuna-7** [comment]
Thanks for the quick reply.
The only process that uses 29999 in connexions TCP tab is LFS.exe.

I tried to change the game telemetry udp port in the telemetry settings to something else out of curiosity (cfg.txt edited by the automatic game configuration) and now /insim 29999 works as expected, and SH also works as expected.
![CaptureSH](https://github.com/SHWotever/SimHub/assets/133895506/82af2a9c-15f5-4d68-9dcf-19d01c1f1561)

**Comment by SHWotever** [comment]
Strange indeed on your capture it clearly shows this time it was a bind fail on the UDP channel. So the solution slightly shifted to changing the UDP port for a free one.

At least it works ;)

I also see on your screenshot a VPN, take care of such software they often block/redirect communications to make sure everything goes through it, it could have been part of the "struggle" (just from experience, it really varies depending of the Vpn software, I can't tell about this specific one)
