### ISSUE TITLE
Gros soucie de triple screen 

### ISSUE THREAD

**Issue by maboule77** [SHWotever/SimHub#1313]
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**
[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/11523937/SimHub.3.txt)
[SimHub.4.txt](https://github.com/SHWotever/SimHub/files/11523938/SimHub.4.txt)
[SimHub.5.txt](https://github.com/SHWotever/SimHub/files/11523939/SimHub.5.txt)
[SimHub.6.txt](https://github.com/SHWotever/SimHub/files/11523940/SimHub.6.txt)
[SimHub.PackageManager.Standalone.1.log](https://github.com/SHWotever/SimHub/files/11523941/SimHub.PackageManager.Standalone.1.log)
[SimHub.PackageManager.Standalone.2.log](https://github.com/SHWotever/SimHub/files/11523942/SimHub.PackageManager.Standalone.2.log)
[SimHub.PackageManager.Standalone.3.log](https://github.com/SHWotever/SimHub/files/11523943/SimHub.PackageManager.Standalone.3.log)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/11523944/SimHub.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/11523945/SimHub.1.txt)
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/11523946/SimHub.2.txt)

"Bonjour M. Wotever !

Je viens vers vous car je ne sais plus où chercher. ( et on ma conseiller de loin de vous soumettre mon problème ) 

Il y a quelques jours, j'ai rencontré un problème avec les jeux ACC et Project Car 2. J'ai lu partout que le problème venait de Steam et qu'il fallait donc le réinstaller. C'est ce que j'ai fait en utilisant Revo et Everything pour m'assurer de tout supprimer.

J'ai réinstallé les jeux et ils ont fonctionné à nouveau, mais malheureusement, seulement pendant quelques jours.

Maintenant, je suis confronté aux mêmes problèmes. J'ai donc décidé de formater complètement mon ordinateur et de repartir à zéro. En utilisant simplement un écran, le jeu se lance correctement.

Ensuite, j'ai configuré mes trois écrans de simulation en mode Surround, et le jeu se lance également. Cependant, lorsque je lance le jeu avec SimHub pour mes bass shakers, je suis bloqué. Le jeu se lance et reste figé sur l'écran de démarrage pour Project Car 2, et j'ai un écran noir (en fait trois écrans noirs) avec ACC.

Je suis perdu à ce stade, car j'ai passé en revue toutes les informations sur internet concernant les problèmes graphiques. Mes pilotes Nvidia sont à jour, mes paramètres de champ de vision sont corrects, et mes résolutions sont bien configurées. Malgré tout cela, les jeux continuent de planter.

Cependant, je me demande si le problème ne pourrait pas être lié à SimHub Je ne sais plus si cela pourrait créer une interférence graphique ou si cela a un impact sur SimHub."

Merci d'avance pour l'aide , un sim raceur en désaroi :)

**Comment by SHWotever** [comment]
Bonjour, normalement il ne devrait pas y avoir d'impacts simhub et les les jeux sont indépendants (il y a juste un échange de données mais pour ces deux jeux ils sont fournis par les jeux eux même, pas de plugin ou d'éléments invasifs qui pourraient parasiter le bon fonctionnement du jeu). Pour valider que simhub n'est pas la cause ce qui serait le plus probable au vu des éléments, c'est assez simple a vérifier, une fois simhub fermé il n'y au aucun élément résiduel qui pourraient tourner, si rien ne change il faudra chercher ailleurs. Étant donné que deux jeux ont le même problème ça ressemble en effet a un problème de driver ou pire matériel. J'ai déjà eu ce type de problème dans le passé la quête peut être complexe, me concernant c'était le bios de la carte mère(je ne dis pas que c'est le cas ici, mais ça illustre combien ça peut être une recherche vaste). 

Si les écrans virent au noir je penserai à un problème de câble et de refresh rate, certain cables ou écran "lâchent" quand la résolution combinée a un haut refresh rate demandent trop de bande passante.

**Comment by maboule77** [comment]
Je comfirme que je cherche une aiguille dans la botte la ! 
Le pire c'est que cela fonctionne un temps , je change et touche à rien , et puis bam cela beug !!! 
Bon on va continuer à chercher alors , merci des pistes et info (y) , cela m'aide malgré tout

**Comment by SHWotever** [comment]
Pas de soucis !
