### ISSUE TITLE
[BUG] Dashstudio - Can't assign simulated keys on buttons

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1314]
As the title states:
it is not possible to assign any key to the "simulated key" boxes  on buttons in Dashstudio (latest version of Simhub).
This has been confirmed by a others as well.

**Comment by SHWotever** [comment]
Hi ! 

Thnaks for the report, indeed this was a behaviour change in the library used to build the property grid, I fixed it for the next release.
