### ISSUE TITLE
Z-Order options messed up on Dash Studio

### ISSUE THREAD

**Issue by arthurferrai** [SHWotever/SimHub#1316]
**Describe the bug**
Z-Order options of any dash element show "Move to front" 4 times

**Simhub version**
8.3.11

**To Reproduce**
1. Either create a new non-empty dashboard or open an existing dashboard and add a new component
2. Left-click the component
3. Point to "Z-Order"

**Expected behavior**
Either only one "Move to front" or other Z-order operations.

**Screenshots**
![image](https://github.com/SHWotever/SimHub/assets/5352649/e1314e9c-8e49-4744-a5fa-8d3f954e79ba)

**Log files**
[Logs.zip](https://github.com/SHWotever/SimHub/files/11545282/Logs.zip)

**Additional context**
I think it also happens on older versions (at least one before current).

**Comment by SHWotever** [comment]
Hi ! thnaks for the report it's fixed for the next release !
