### ISSUE TITLE
Oled Trouble 

### ISSUE THREAD

**Issue by leogol16** [SHWotever/SimHub#1317]
Hi im new and my english is not good!!! 
my oled settings show only RPM progress bar, i want show gears too!

thanks

this is PART1.INI
-----------------------------------------------

[variable]
name='blinkrpm'
value=0
;;blink('rpm',200,[SerialDashPlugin.ComputedRPMPercent]>[SerialDashPlugin.BlinkTriggerRatio])

[variable]
name='blinkrpm2'
value=blink('rpm',200,[SerialDashPlugin.ComputedRPMPercent]>[SerialDashPlugin.BlinkTriggerRatio] || ([context.lowergearratio]> 0 && [context.lowergearratio] < 92))

[Text]
X=0
Y=30
Color=2
Text=[DataCorePlugin.GameData.NewData.Gear]
FontSize=2
FontType=2
Align=3

[Progressbar]
X=0
Y=20
Color=2
Width=128
cornerradius=6
Height=10
Minvalue=0
Maxvalue=100
value=[SerialDashPlugin.ComputedRPMPercent]
visible=![context.blinkrpm]

;visible=blink(1000) || ([SerialDashPlugin.ComputedRPMPercent]<96) 

---------------------------

**Comment by SHWotever** [comment]
Hi ! Could you give more details about the setup ? Arduino model, arduino setup ? Usually when fonts won't draw it's a memory issue with the arduino.

**Comment by leogol16** [comment]
hi!!! arduino nano v 3 whit connector USB C 

![20230529_204512](https://github.com/SHWotever/SimHub/assets/128564311/144c1aaa-fad9-4a2e-a946-5e22fb23796a)
![20230529_204520](https://github.com/SHWotever/SimHub/assets/128564311/c1841ff4-db27-4a42-9183-71bed7a6ef18)
![20230529_205331](https://github.com/SHWotever/SimHub/assets/128564311/6d774124-5f44-4e5f-8221-1465bea86194)

its the information ok? any more need?

THANKS!!!!

**Comment by SHWotever** [comment]
Hi ! Can you try with LEDs and tm1637 disabled in the setup tool ? The nano v3 has just enough memory for the screen  : https://github.com/SHWotever/SimHub/wiki/Arduino-SSD1306-0.96''-Oled-I2C#restrictions
