### ISSUE TITLE
Volume keys not working when assigned to SimulatedKey

### ISSUE THREAD

**Issue by arthurferrai** [SHWotever/SimHub#1318]
**Describe the bug**
When I try to bind volume keys to a button on a dashboard, they aren't triggered correctly.

**Simhub version**
8.3.12

**To Reproduce**
1. Either create a new dashboard or edit an existing one
2. Add a button
3. Assign either "VolumeUp" or "VolumeDown" either by button pressing or selecting from list
4. Test dashboard or run it from external screen

**Expected behavior**
When pressing the button with volume change key, the sound volume should change.

**Screenshots**
![image](https://github.com/SHWotever/SimHub/assets/5352649/558063d6-9405-4859-98f1-5d05d3c7f990)

**Log files**
[Logs.zip](https://github.com/SHWotever/SimHub/files/11576848/Logs.zip)

**Additional context**
I've tried with other buttons (such as "Win + Ctrl + Right") and it works as expected. Also, when triggering the buttons using external display, when I open a text editor, VolumeUp triggers "b" while VolumeDown triggers "c".

**Comment by SHWotever** [comment]
Hi !

Windows does not react very well to emulated "special keys" volume control being one of the most used it's available directly as an action :

![image](https://github.com/SHWotever/SimHub/assets/2207331/92edda6c-e2e3-401f-98bc-7f5373a8acfd)
