### ISSUE TITLE
Buttkicker Gamer Pro + ACC with Road Rumble delay

### ISSUE THREAD

**Issue by Snydder** [SHWotever/SimHub#1319]
**Describe the bug**
When enabling the road rumble effect using a buttkicker gamer pro in ACC, there will be a full second delay (or more) before the effect stops playing. 

**Simhub version**
8.3.12

**To Reproduce**
1. Create a new profile 
2. Select your output device (Buttkicker Gamer Pro via USB)
3. Enable the Road Rumble effect 
4. Change to mono
5. Launch ACC 

**Expected behavior**
Effect should be in perfect sync with the game action; It should stop playing exactly after leaving the kurb with all tyres, precisely.

**Log files**
-

**Additional context**
Also happens with the buttkicker connected via sound card.

**Comment by SHWotever** [comment]
Hi ! I will take a look ! Can you give me more details about track and car used ? Acc does not gives the exact material each wheel is so currently it's using an oscillation detection on the suspension which is big approximation.

**Comment by Snydder** [comment]
Hi! This is what I tested so far: 
Imola with:
Porsche 992 GT3 R, Maserati granturismo mc gt4, Ferrari 296 GT3

Monza Circuit with: 
BMW M4 GT4, Audi R8 LMS evo, Mclaren 650s GT3.

The effect has a slight delay to get triggered, and a long delay to stop playing. A single frequency is getting played throughout the duration for the most part, except when you hit some harder kerbs faster. 

The force feedback on kerbs seems to be good. Is it possible to convert that to bass shaker output?

**Comment by SHWotever** [comment]
Hi ! Thanks! The data is not available through telemetry. there is a data given the name would have stated to be the right one :  "kerbsvibration" but it rarely triggers and most of the time shortly when you enter or leave the kerb, it's completely off our needs unfortunately. That's why I had to create something from scratch

**Comment by Snydder** [comment]
Ah I see. Thanks. If somehow the trigger in / out can be tightened up I think it would improve the effect a lot. Using the suspension effect from hapticonnect as a replacement to this one for now seems to be a workaround.
