### ISSUE TITLE
G-Force Cross Game PCars + AC

### ISSUE THREAD

**Issue by PuReAdDicT** [SHWotever/SimHub#132]
PCars

Top Property
723 + if([DataCorePlugin.GameRawData.mLocalAcceleration02]<-6, rand(20)-10,0)

Works until play AC, then Top Property of this item goes to 0

AC matching property

DataCorePlugin.GameRawData.Physics.AccG02

**Comment by SHWotever** [comment]
Hello ! Gforces have been extracted (in ms²) in the latest version.

![image](https://user-images.githubusercontent.com/2207331/111075142-df61b880-84e6-11eb-8659-b4ede095bb9e.png)

Nicolas
