### ISSUE TITLE
First Chance Exception Error

### ISSUE THREAD

**Issue by SquidOwens** [SHWotever/SimHub#1322]
**Describe the bug**
When using the Dallara IR-18 in rFactor 2 not all data is shown on the overlays like how many laps are done and the pit count of the drivers. The output of the Throttle, Brake and Clutch are also not very smooth. It works fine with other cars so i'm not sure what the issue is

**Simhub version**
8.3.13

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/11601594/SimHub.txt)
[SimHub.PackageManager.Standalone.2.log](https://github.com/SHWotever/SimHub/files/11601598/SimHub.PackageManager.Standalone.2.log)
[SimHub.PackageManager.Standalone.3.log](https://github.com/SHWotever/SimHub/files/11601599/SimHub.PackageManager.Standalone.3.log)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/11601600/SimHub.1.txt)
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/11601601/SimHub.2.txt)
[SimHub.PackageManager.Standalone.1.log](https://github.com/SHWotever/SimHub/files/11601604/SimHub.PackageManager.Standalone.1.log)

**Additional context**
I have tried reinstalling simhub and the plugins i use and clear everything but it doesn't fix the issue.

**Comment by SHWotever** [comment]
Hi ! Could you try to disable third party plugins? Apparently Gary swallow plugin is the culprit here. Unfortunately this is a third party plugin and I don't have any control about it.

**Comment by SquidOwens** [comment]
Hi, It was the plugin that was causing the issue so i'll try and get in contact with the author to see if he can sort out the issue with it
