### ISSUE TITLE
Tray icon shortcuts for overlay layouts

### ISSUE THREAD

**Issue by KEALHOVIK** [SHWotever/SimHub#1324]
It's kind of too much of a hassle to always open SimHub, go to Dash Studio, select Overlays tab, and load your overlay. Auto load feature doesn't help any too, as it just starts the layout editor with windows which isn't good when you play a game only once a week or so and don't want that thing hanging in task bar all the time.

I thing that the easiest thing to implement would be to add saved overlay layouts to the menu that pops up on right clicking SimHub icon in the tray. Autoload on game detection would've work too, as well as assigning overlay to be launched with a game if it is started from SimHub (which is already working).

As it is now, i use dashboards on my phone, i don't like it either as it is also some hassle to always open it and it blocks parts of the screen. But it's still less pain then opening the program and navigating menus and tabs.

**Comment by SHWotever** [comment]
Hi ! This has been added in the incoming v9 version.
