### ISSUE TITLE
Bass Shaker Outputs only to 1 single Shaker

### ISSUE THREAD

**Issue by Zer0select** [SHWotever/SimHub#1326]
**Describe the bug**
All Bass Shakers working fine before, but now will only output into 1 single bass shaker. All Test on Windows Sound Test Confirms that it is all outputing to each Shaker and is working fine, but when going into Simhub to test each individual Shaker Channels (total 6) it will only shake the same Bass Shaker (physically) no matter which channel you pick .

Did find this line in the System Log which seems to be the problem but can't find no solution to fix it.

[2023-06-09 18:26:26,990] INFO - BassShakers: Requiring audio interfaces rebuild after game start or audio settings change

Have attempted to reboot Simhub, PC and reinstall Simhub. Problem still presists. Also while in game try to check the audio settings ingame to see if it was set to the same audio output as the shaker, it was not. All is good in game.

**Simhub version**
Running Latest 8.3.13

[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/11710538/SimHub.2.txt)

**Comment by SHWotever** [comment]
Hi !

Can you export your shaker settings and output settings so I can take a look ? Is it is I would think about a little configuration issue inside simhub.

**Comment by SHWotever** [comment]
Nb : the information message is perfectly normal, it restarts automatically the sound output after the game is started to workaround some vr headset messing up with audio output.

**Comment by Zer0select** [comment]
Not sure if this needed
![outputsettings](https://github.com/SHWotever/SimHub/assets/136131271/6d968f2e-4870-4474-8b06-c3128bddf302)
![shaker outputs](https://github.com/SHWotever/SimHub/assets/136131271/bf3e3f8b-7d5a-489d-8122-a984ff5cb3ed)

**Comment by Zer0select** [comment]
Also wanted to add I have a total of 6 Shakers. Yet for some reason 7 of the channels when testing shakes the shaker. This has been always going on even when working properly.
![windowsaudiosetting1](https://github.com/SHWotever/SimHub/assets/136131271/066e1a48-2e7b-4384-8a33-933ca47a1b3e)

**Comment by Zer0select** [comment]
![disabled shaker](https://github.com/SHWotever/SimHub/assets/136131271/db5ae507-6a82-4798-9475-0c6dc7b45c53)

**Comment by Zer0select** [comment]
Ok I think its a different problem. All the Shakers do work, but the actual problem is that both the LF and RF shakers will activate on any of the tests except Channel 4. 

How its setup now is 

Channel 1 = Left Front (Testing both LF and RF Shakes)
Channel 2 = Right Front (Testing both LF and RF Shakes)
Channel 3 = Nothing (Testing both LF and RF Shakes)
Channel 4 = Nothing  (Nothing)
Channel 6 = Side Left (Testing LF, RF, and SL Shakes)
Channel 5 = Side Right (Testing LF, RF, and SR Shakes)
Channel 7 = Left Rear (Testing LF, RF, and LR Shakes)
Channel 8 = Right Rear (Testing LF, RF, and RR Shakes)

I'm at a loss why it would be like this.
I have no other Audio Control Panel.

**Comment by Zer0select** [comment]
Ok i think i found a Solution. So I had to INSTALL the Creative App and from there I and setup the Speaker setup to 7.1 from there. Before i never had this install. Thank You Again So Much! You can Close this Ticket.

**Comment by SHWotever** [comment]
Thanks for the feedback ! 

As a toot cause I would think about a sneaky windows driver update, it's notorious for installing drivers updates automatically and almost silently that would explain the sudden behavior's change.
