### ISSUE TITLE
win11再インストールで

### ISSUE THREAD

**Issue by DOMORA7** [SHWotever/SimHub#1327]
先日まで寄付をしてSIMHUBを使用していました。SSDが壊れ新しいのを買ってWIN11を新規インストールしたのですが、SIMHUBがライセンスを求めて使用できないです。LOAD MY LIOCENSE FILEに入っていたのかもしれませんがSSDが壊れているので駄目です
自分のライセンスコードを再発行できますか？PAYPALで支払ったのですが、随分前なので履歴が見つからないです

**Comment by DOMORA7** [comment]
取引ID
9VH40196PD180305Eです
![S__5546006](https://github.com/SHWotever/SimHub/assets/136148041/c100f08f-763b-4457-8d30-dc7f24ceb0f9)

**Comment by SHWotever** [comment]
Hi !

I forwarded you a copy of your license to your PayPal email: daisenxxx@gmail.xxx (I replaced some characters for your privacy)

Do not hesitate to use the official contact form for questions related to the license: https://www.simhubdash.com/simhub-contact/

Best regards,
Nicolas
