### ISSUE TITLE
drivercarclass(repeatindex()) error

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1329]
Lorsque j'utilise drivercarclass(repeatindex()) dans un leaderboard, j'ai l'erreur indiquée dans la log
on dirait un dépassement d'indice
Je ne comprends pas
en pièce jointe, le dash concerné
l'attribut qui ressort en erreur est "CAR-CLASS"
[SimHub.txt](https://github.com/SHWotever/SimHub/files/11735578/SimHub.txt)
![1](https://github.co
[test.zip](https://github.com/SHWotever/SimHub/files/11735597/test.zip)
m/SHWotever/SimHub/assets/58605557/2e49617b-3f45-47b3-8c4a-a5463008ac70)

**Comment by SHWotever** [comment]
Hello !

L'erreur provient du fait que repeat index doit aller plus loin que la grille, il n'y a donc pas de carclass (null) .

On ne peux donc pas utiliser indexof

L'astuce dans ce cas est d'ajouter un petit cas de sortie par defaut, ici j'ai mis "default" mais on peux changer avec ce qui arrangera : 

```js
var car_class = drivercarclass(repeatindex());

if(car_class == null){
  // Pas de car class
  return 'default';
}
var chemin=lcase(car_class); 
...
```

**Comment by herve4545** [comment]
maintenant, ca fonctionne très bien
merci
