### ISSUE TITLE
Windows defender false positive

### ISSUE THREAD

**Issue by Landi2022** [SHWotever/SimHub#1333]
**Describe the bug**
When I download the zip file, the Windows 11 virus detector tells me that there is a trojan in the zip file

**Simhub version**
SimHub V8.4.2

**Expected behavior**
I don't get a message that I've downloaded a trojan

**Screenshots**
![grafik](https://github.com/SHWotever/SimHub/assets/107491609/4e750224-1349-43cc-a5bd-43d3b73f83d2)
![grafik](https://github.com/SHWotever/SimHub/assets/107491609/395e62c5-0c0e-425f-af2a-19e0a3a277e1)
![grafik](https://github.com/SHWotever/SimHub/assets/107491609/0bea7e39-9ffb-4610-b756-776523942472)

**Comment by SHWotever** [comment]
Hi ! This is a false positive from windows defender, you can check the installer scan here : https://www.virustotal.com/gui/file/3baba8bd74a5c07f527760fdaa15abe186a801d28a7ee76e9d929285d3ddb03d

I'm reporting it to Microsoft so they fix it, it usually takes a few hours.

**Comment by SHWotever** [comment]
Hi ! 

I reported it to microsoft but from there scan there is no issues :
Can you make sure to update the virus definition and cache as shown here : https://www.microsoft.com/en-us/wdsi/defenderupdates
```bat
cd %ProgramFiles%\Windows Defender
MpCmdRun.exe -removedefinitions -dynamicsignatures
MpCmdRun.exe -SignatureUpdate
```

![image](https://github.com/SHWotever/SimHub/assets/2207331/54e244cd-17d3-431e-b986-a71a9b0fabbe)
