### ISSUE TITLE
F1 23 Red Flag reset

### ISSUE THREAD

**Issue by Landi2022** [SHWotever/SimHub#1335]
**Describe the bug**
Once the red flag came up in F1 23, it doesn't go away in the overlay with the [GameRawData.RedFlagShown] function, which means that as soon as an overlay for the red flag is displayed, it doesn't go away even with a green flag

**Simhub version**
SimHub V8.4.3

**To Reproduce**
1. Go in the Game 'F1 23'
2. Than Trigger a 'Red Flagg'
3. Now show in the SimHub overlay

**Expected behavior**
The Red Flag overlay is going away

**Screenshots**
https://github.com/SHWotever/SimHub/assets/107491609/b709798a-07e1-4fb6-a841-5bed1c658c4b

**Log files**
[LapLog.txt](https://github.com/SHWotever/SimHub/files/11778707/LapLog.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/11778708/SimHub.1.txt)
[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/11778709/SimHub.3.txt)

Join log files available in C:\Program Files (x86)\SimHub\Logs
[SimHub.txt](https://github.com/SHWotever/SimHub/files/11778706/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! 
Thnaks for the report this is indeed I did not had a chance to test during the first days, there is a red flag message sent by the game but no reset, I guess I will couple it with the startline messages to reset it, this should do the trick.

**Comment by Landi2022** [comment]
So what should I write in the code now, unfortunately I didn't quite understand it

**Comment by SHWotever** [comment]
You can't now, I will do the reset in the simhub code for the next update ;)

**Comment by Landi2022** [comment]
When come the next update fore simhub

**Comment by SHWotever** [comment]
Probably within next week ;)

**Comment by SHWotever** [comment]
Hi ! the fix has been released with the last update ;)
