### ISSUE TITLE
Every time an overlay window is shown, it uses a different window class

### ISSUE THREAD

**Issue by fredemmott** [SHWotever/SimHub#1336]
**Describe the bug**

:wave: Hi - I make OpenKneeboard, a tool intended for VR flightsims, but some people are using it to capture the simhub dashboard windows and bring them into VR. There's a small quirk in that people need to remove and add the simhub overlay from OpenKneeboard's settings every time they run.

It turns out that every time SimHub creates an overlay window, it uses a different window class (as reported by `GetClassName()` or the spy++ utilitiy in visual studio). For example, I started the AIM GS-DASH overlay 3 times, and the window classes were:

```
HwndWrapper[SimHubWPF.exe;;04aad3e3-8f94-439a-bd34-9d29588ea64a]
HwndWrapper[SimHubWPF.exe;;b8b8423f-32c9-47ab-a59f-5f5804e1d37c]
HwndWrapper[SimHubWPF.exe;;6fa9cb5b-c5de-44f7-a939-b6dcc459b92a]
```

Would it be possible for SimHub to use a consistent window class name for these? e.g. something like 'SimHub overlay' or 'SimHub overlay - "AIM GS-DASH"' ?

I've [added an option](https://github.com/OpenKneeboard/OpenKneeboard/commit/5e2bcffec7a19b04d1c9952aa39f6c77c3004006) to my tool to ignore the window class, but that's not a great solution

**Simhub version**

8.4.3

**To Reproduce**

1. Show a dashboard with SimHub
2. use spy++ from visual studio to inspect the window class
3. close dashboard window
4. show dashboard window again
5. use spy++ again, see new window class

**Expected behavior**

Either:

- a consistent window class for all overlays, e.g. "SimHub Overlay"
- a consistent window class for each window for a given overlay type, e.g. "SimHub Overlay - AIM GS-Dash"

**Screenshots**

n/a

**Log files**

[SimHub.txt](https://github.com/SHWotever/SimHub/files/11778963/SimHub.txt)

Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

By default, I match windows by application and window class, to avoid capturing menu bars instead of the actual window in classic win32 apps with HWND-based controls, and I ignore the window title because it's common for the title bar to show some transitive state. For example, users often want to capture discord, and discord's window title includes the current server and channel.

**Comment by fredemmott** [comment]
While it's possible for SimHub to work around it, this seems to be a 'quirk' of WPF. I've made OpenKneeboard ignore window classes and match titles by default when the window class starts with `HwndWrapper[` (i.e. is likely a WPF app)

**Comment by SHWotever** [comment]
Hello ! I took a look at first sight I can't see any ways to changes it through WPF, I'm working on a whole new window system already overloading lot of wpf standard behavior's (fullscreen, taskbar bugs handling, screen resolution changes) I'm not afraid of one more raw Win32 api calls, but I could not the api for that yet. If you know it I'm interested ;)

NB : the window content can be changed using actions, so it's not a definitive content being shown so if that property is read-only at creation time for instance it would not be relevant.

**Comment by fredemmott** [comment]
AIUI the window class for a given window is immutable - it needs to be passed into `CreateWindow()`/`CreateWindowEx()`. The usual workarounds for WPF are along the lines of putting the WPF content inside a manually created window via the `HwndSource` class

**Comment by SHWotever** [comment]
Ah so it won't be relevant, the shown dashboards can be changed on the fly (soon it will be completely automated), 

I decompiled the wpf window code and the class name is set extremely deep. Even using the windowbase class in order to save a few behaviours would not do the trick as the name is completely hard coded in the MS HwndWrapper class : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/9a0f17f9-8021-499f-ab8b-2de880168637)

Overall being able to set the class name can hardly justify to go full low level and having to recode all the already available behaviors in a standard WPF window. 

I'm sorry at this point I can't see any "smart way" to be able to set the data and any WPF applications you might want to integrate would suffer from the same limitation.

**Comment by fredemmott** [comment]
Fair enough, yeah, this seems like a lot of work for a niche case. I'm mostly annoyed at Microsoft for not following normal windows behavior in their own framework :p

As a workaround, the next version adds the option at the bottom here, and defaults to these values for WPF apps:

![image](https://github.com/SHWotever/SimHub/assets/360927/500f0664-d72c-4d52-92b2-a33fdf45ecaa)

**Comment by SHWotever** [comment]
Little question, are you able to capture webview2 powered hybrid apps ? My future version will probably use it as the default rendering engine as it performs very well in "stressful" situations (maxed GPU usage, gsync....) But this Microsoft component is really tricky, and I had to compose windows to be able to overlay things over it as it falls in the "airspace issue" https://github.com/MicrosoftEdge/WebView2Feedback/issues/286

**Comment by fredemmott** [comment]
As a general rule, if OBS can capture it, OpenKneeboard can - they both use Windows::Graphics::Capture - if you know an example app, I'm happy to test.

**Comment by SHWotever** [comment]
Thanks ! That should do the trick ! The old rendering engine will still be available anyway so there won't be any unreversible issues for your use case.
