### ISSUE TITLE
F1 23 Enable DRS

### ISSUE THREAD

**Issue by Landi2022** [SHWotever/SimHub#1340]
**Describe the bug**
The [GameRawData.RaceControlDRSEnabled] function does not work in F1 23

**Simhub version**
SimHub V8.4.3

**To Reproduce**

1. Go in the Game 'F1 23'
2. Than Trigger a 'DRS'
3. Now show in the SimHub overlay

**Expected behavior**
The DRS overlay is showing

**Screenshots**
I dont have a screenshot

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

[LapLog.txt](https://github.com/SHWotever/SimHub/files/11782462/LapLog.txt)

**Additional context**

**Comment by SHWotever** [comment]
Hi ! I checked a few of my replays and the data was never sent
Do you know some conditions where it should be sent ? As is without any data sent I would think it should be considered as enabled by default until race control disable it and reenable it (which is the opposite at this time in simhub it's false until the game sends the enabled event). 

Maybe would you have a simhub replay with those events ?

**Comment by Landi2022** [comment]
So I tried it with the Visible function, I just packed the code in there and tried it with a repetition. Unfortunately, this didn't work then シ

**Comment by SHWotever** [comment]
I confirm I never got any data in any of my replays neither, it might be a bug in the game or a misunderstanding of the data. In the wait I will swap the default status to make it enabled by default until an event disable it as it would makes more sense.

**Comment by SHWotever** [comment]
Just a side note  the GameRawData.RaceControlDRSEnabled is a race control flag for all the players, for your own car you have another standard data :  drsenabled and drsavailable

**Comment by SHWotever** [comment]
Hi ! 

For your own DRS state you must use this :

![image](https://github.com/SHWotever/SimHub/assets/2207331/fcdefe06-f09b-4034-b306-0f649417c092)

Racecontrol data is specific and occurs way later (rain etc ...) I decided to changed it to reflect better what the game gives :
- Null : no information received
- True : Race control DRS enabled event received 
- False : Race control DRS disabled event received
