### ISSUE TITLE
F1 23: Time Delta Between Cars Is Incorrect

### ISSUE THREAD

**Issue by pencelguy** [SHWotever/SimHub#1341]
**Describe the bug**
Time deltas from the car in front and behind from simhub external device are not the same as the ones on the timing boardings in- game. It'll either be 3-5 tenths off or by a couple of seconds, it varies depending on the corner and while racing. 

**Simhub version**
8.4.2

**To Reproduce**
1. Go into any race
2. Start the race
3. Look at time deltas from car in front and behind in-game and from simhub external device.

**Expected behavior**
Time deltas to the car in front and behind should match the in-game's delta times. 

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**
[LapLog.txt](https://github.com/SHWotever/SimHub/files/11783628/LapLog.txt)

**Comment by SHWotever** [comment]
Hi ! Front and behind delta is not given by the game (it's a "on track" delta computed by Simhub), since it's only a "track" position delta it will indeed differ from what is shown in game. The complete leaderboards will give the game delta in F123 (this data is finally available int the lastest F1 23)

**Comment by pencelguy** [comment]
> Hi ! Front and behind delta is not given by the game (it's a "on track" delta computed by Simhub), since it's only a "track" position delta it will indeed differ from what is shown in game. The complete leaderboards will give the game delta in F123 (this data is finally available int the lastest F1 23)

So should I rely on the in-game deltas or sim hub’s deltas to determine if the car behind me or I am within a second to the car in front for drs?

**Comment by SHWotever** [comment]
à

**Comment by SHWotever** [comment]
Currently this data is not available from the game we only have the race delta while on DRS it's indeed the front delta(which is computed by simhub) and so won't match what the game has estimated. Currently the only reliable information is the DRSAvailalble data but it won't give you the reason (distance, zone ...)
