### ISSUE TITLE
Severe hang-ups when editing Dial Gauge

### ISSUE THREAD

**Issue by snozboqrd** [SHWotever/SimHub#1342]
**Describe the bug**
When editing Dial Gauges, the system halts to stop. It lags badly.

**Simhub version**
Latest 8.4.3 Licensed.

**To Reproduce**
1. Create a Dial Gauge
2. Edit Dial Gauge settings

**Expected behavior**
The expected before is a smoothly editing experience, just like it currently is with most other settings,

**Screenshots**
N/A

**Log files**
N/A

**Additional context**
N/A

**Comment by snozboqrd** [comment]
I think I funneled down to the ticks and labels settings. I changed a RPM dial, using in-game data which are in the thousands. The default setting was in single digits, so the interval of 1 created way too many ticks and labels.

**Comment by SHWotever** [comment]
Ah in such use case it's better to divide by 1000,  all rpms gauges shows "k"(thousands) of rpms almost never directly rpms
