### ISSUE TITLE
System Hangs LED modules not recognizable.

### ISSUE THREAD

**Issue by SimRacingME** [SHWotever/SimHub#1343]
**Describe the bug**
Through the last 3 updates, I have been having this hanging issue where the whole application hangs for a period of over 40 seconds sometimes. I do have a SIMDID Vocore display with LEDs and a GSI FPE with LEDs it's either the first or the second that sometimes Simhub doesn't recognize the LED port. When trying to remove and replace the USB the software hangs for a long period of time even if both devices are not attached.
**Simhub version**
8.4.3

**Expected behavior**
Simhub was smooth before.

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/11788104/SimHub.txt)

**Additional context**
You can see an abnormality mentioned in the log file, but I have no clue what's going on.

**Comment by SHWotever** [comment]
Hi ! I've took a look at the log and most of them shows a bottleneck inside the garyswallow plugin. Could you try to disable it first (and ideally any third party plugins) to see if this still happens ?

**Comment by SimRacingME** [comment]
I'll definitely do that and report back!

**Comment by SimRacingME** [comment]
You were not wrong Wotever. Thank you for your supreme support.
It was the plugins, we can close this now. 
Thank you

**Comment by SHWotever** [comment]
Thanks for your feedback !
