### ISSUE TITLE
[BUG] Toggle Record broken?

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1346]
VERY LOW PRIORITY :) 

I assigned a button to togglerecord (to record simhub replays) but it's not working anymore.
If I go back to controller actions I can assign the button just fine (also other buttons) but it doesn't trigger recording anymore.

![image](https://github.com/SHWotever/SimHub/assets/116221480/f040704b-6456-486e-903f-c1f1e40faad7)

**Comment by SHWotever** [comment]
Hi ! Could you join the log files after you tried ? I did a quick test with no particular issues.

**Comment by FullPace** [comment]
The log shows the start and ending of recording at the exact same time when I press the button
![image](https://github.com/SHWotever/SimHub/assets/116221480/4c5a1207-e954-475d-aa3a-f587fceb26b1)

**Comment by SHWotever** [comment]
Can you go inside the controllers settings and press/release the button to check it's only getting detected once ? You need to enable "show inputs" option
![image](https://github.com/SHWotever/SimHub/assets/2207331/17ac169d-7ef6-4b7c-8f17-bdc96dc177fd)

**Comment by FullPace** [comment]
Hello,

yes in controller input there are only two entries (1x pressed, 1x released) when I press the button.

I reinstalled windows today and tried without any other tools that could interfer (like joy2key etc) but it didn't make a difference.

**Comment by SHWotever** [comment]
Is it possible that the action is bound twice ? Maybe a second time through the control mapper ? Since you reinstalled I'm not sure if you went back from scratch or if you migrated your previous settings.

**Comment by FullPace** [comment]
oh yes, you are right. It was bound twice in controls and events. on 3rd and 9th position with exactly the same function.
maybe a little prompt would be helpful in that case ^^

thanks for the help!

**Comment by SHWotever** [comment]
In the last release i added the control editor in the settings for that action. I gives a better overview of the mapped controls. Overall the final goal will be to completely remove the controls screen (or at least make it so useless that there won't be any reasons to use it anymore :D)

**Comment by FullPace** [comment]
Please don't remove before multi shift and long / short presses are working. I rely heavenly on that :D (at least controller to keyboard mappings ) ^^
