### ISSUE TITLE
Simhub lags in iracing with fps drops

### ISSUE THREAD

**Issue by JOAOMORETTO110711** [SHWotever/SimHub#1350]
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by JOAOMORETTO110711** [comment]
https://github.com/SHWotever/SimHub/files/11855594/SimHub.txt
having some issues with led rgb matrix (iflag) when in iracing. 
i suspect that Racelabs is causing some kind of conflict. 
the lights of my rgb matrix blink sometimes during a lap, and I get stuttering/micro freezes. My wheel also stops showing the correct revlights when it happens.
Please check if the log attached shows something! Thanks

**Comment by SHWotever** [comment]
Hi ! I see lot of freeze and crashes caused by garyswallow plugin, could you try to disable it as well as any other third party plugins? Then try again and if somehow it still happens send me a fresh log ?

**Comment by JOAOMORETTO110711** [comment]
hello, I disabled all plguins that I could. but still having issues. 
please see log
thanks
[SimHubMoretto_Jun24.txt](https://github.com/SHWotever/SimHub/files/11857878/SimHubMoretto_Jun24.txt)

**Comment by SHWotever** [comment]
Hi ! The logs looks better nothing is happening anymore here. 

You said your wheels LEDs were also out of sync, is it using another application ? I see it's a moza and it probably make use of its own software? If you have many applications being affected that means the issue is in the game itself or something affecting the game (you were mentioning stutters and micro stutters, I guess you were talking about the game).

**Comment by JOAOMORETTO110711** [comment]
Hum, my iflags stopped working for a second around 2:14. I am using Moza and the lights stopped syncing right when the iflag stopped. After that the wheel never git back in sync.
I also had stuttering.
I am lost now, looks like I am having issues with the game or with the pc…
Very annoying! Thanks for the support
