### ISSUE TITLE
Dash/Overlay conversion - Not refreshing dash list

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1351]
Hi,
When converting a dash to overlay and vice versa the dash list doesn't update, 
It looks like nothing happened but restarting Simhub shows the converted dash in the correct list.

Simhub version 8.4.2
Bonne journée

**Comment by SHWotever** [comment]
Hello ! It's fixed for the next release ;)

**Comment by Romainrob** [comment]
Hi. Thank you very much my good Sir!
Bonne journée 😀

**Comment by SHWotever** [comment]
Hi ! the fix has been released with the last update ;)
