### ISSUE TITLE
Web page view - Unskippable cookie page + clickthrough weirdness

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1352]
Hi,
I have a couple issues with a web page view in this Twitch chat overlay

1. It's impossible to skip the cookie management page.
No matter where I click the page stays on top, or comes back instantly.

2. The handle bar at the top is in front of the web page but it's not clickable unless the web page view is set to clickthrough (despite been underneath the handle)

Simhub version 8.4.2

![image](https://github.com/SHWotever/SimHub/assets/50543913/10f817ac-0328-4a79-ad4e-9717935ff99b)

[RSC - Twicth chat TEST.zip](https://github.com/SHWotever/SimHub/files/11860046/RSC.-.Twicth.chat.TEST.zip)

Bonne fin de journée!

**Comment by SHWotever** [comment]
Hello ! 

J'avais fait toute une réponse et elle s'est perdue avant que je ne puisse la valider :(

Pour twitch apparement c'est un blocage "anti bot" visiblement le probleme se produit sur les navigateurs custom (comme celui embarqué dans simhub). Rien que je ne puisse faire, j'ai tenté de tricher et d'imiter un vrai chrome (user agent ...) mais pas moyen, la detection doit ètre plus subtile.

J'ai testé sur la nouvelle version en mode html ou j'ai remplacé le "navigateur" usilisé par la vue webview2 pour le rendu, et il se charge bien. J'imagine que ce moteur là n'est pas bloqué pour le moment.

Pour la handlebar, je vois le soucis, j'ai tout réécrit de ce coté là pour la nouvelle version et on peut bien déplacer l'overlay meme avec une vue html à l'intérieur.

**Comment by Romainrob** [comment]
Salut.
Parfait! Vivement la beta :)
Bonne journée!

**Comment by Romainrob** [comment]
Hi, this is indeed fixed on the V9 beta
Thank you!

**Comment by Salamandralex** [comment]
Hi, I have the same problem to add an overlay with the twitch chat. 
where I can found the v9 fix please?

**Comment by Romainrob** [comment]
Hi, in the release channel of the simhub discord.
Or
 https://www.simhubdash.com/unofficial/

**Comment by Salamandralex** [comment]
Thank you for the link, I downloaded it. 
now I can't connect to the chat, when I put it on webview2, twitch reject the connexion... "www.twitch.tv a refusé la connexion."
if I put the WPF mode, it's the same like before :/

**Comment by Romainrob** [comment]
I just tried it again.
It works on my end in html mode, running as on screen overlay.
With this address:
https://www.twitch.tv/embed/CHANNELNAME/chat?darkpopout&parent=127.0.0.1

**Comment by Salamandralex** [comment]
Nice ;) it works with your kind of address
