### ISSUE TITLE
Leaderbord : bestlap in my class

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1354]
Sur le leaderboard, pour une course multi class, je cherche a afficher le bestlap pour ma classe et cela ne semble pas fonctionner.

J'utilise leaderboardbestlap avec la "cible" MYCLASSONLY mais cela me renvoie systématiquement le bestlap pour le 1er de ma classe

Par ailleurs, j'affiche le bestlap tout classes confondues et cela fonctionne parfaitement
Je seche

**Comment by herve4545** [comment]
![1](https://github.com/SHWotever/SimHub/assets/58605557/14fed33b-49ee-4969-890a-6c552b5f3913)

**Comment by SHWotever** [comment]
Hello ! Ca me semble normal, c'est le best lap du joueur qui est premier dans le classement ca ne donne pas le meilleur temps de la classe. En non filtré on aurrait quelque chose de similaire meme si les probabilités que le premier du LB ai aussi le meilleur temps sont assez élevées ce qui explique ca se voit moins. 

J'ai rajouté pour la prochaine version la position de meilleur temps de la classe  (`BestLapOpponentSameClassPosition`)

Ca commence à 0 comme son petit frère le  `BestLapOpponentPosition` qui éxistait déja.

On pourra l'utiliser comme çà par exemple (ncalc), ca qui renverra bien le joueur avec le meilleur temps dans la classe (et -- quand il n'y a pas encore de temps) : 
```js
isnull(driverbestlap([BestLapOpponentSameClassPosition]+1),'--')
```

**Comment by herve4545** [comment]
Cool
Merci

**Comment by herve4545** [comment]
pendant que j'y pense
j'utilise aussi pas mal les données driver pour afficher le logo et la classe de la voiture
est-il possible d'avoir
drivercarname_sameclass(position)
drivercarclass_sameclass(position)
![2](https://github.com/SHWotever/SimHub/assets/58605557/a4c73c4a-be4e-4dba-a145-74752ab9784e)
![1](https://github.com/SHWotever/SimHub/assets/58605557/033c678f-9814-44dc-994a-14193e3922aa)

**Comment by SHWotever** [comment]
Une fois que l'on à la position comme dans mon exemple précédent on peut tout réutiliser 
```
isnull(drivercurrentlap([BestLapOpponentSameClassPosition]+1),'--')
isnull(drivercarclass([BestLapOpponentSameClassPosition]+1),'--')
etc ...
```

**Comment by herve4545** [comment]
Ah ok
Je connaissais pas
