### ISSUE TITLE
Red Flag Reset

### ISSUE THREAD

**Issue by Landi2022** [SHWotever/SimHub#1357]
Describe the bug
Once the red flag came up in F1 23, it doesn't go away in the overlay with the [GameRawData.RedFlagShown] function, which means that as soon as an overlay for the red flag is displayed, it doesn't go away even with a green flag in the replay

Simhub version
SimHub V8.4.5

**Third party plugins**
Gary Swallow Newest Version and F1 TV HUD

To Reproduce

    Go in the Game 'F1 23'
    Than Trigger a 'Red Flagg'
    Now show in the SimHub overlay
    See error

Expected behavior
The Red Flag overlay is going away in the replay

Screenshots

Log files

Join log files available in C:\Program Files (x86)\SimHub\Logs

**Comment by SHWotever** [comment]
Hi does the replay has been recorded with the latest version ? Since it's controlled by events and can't be recomputed later the fix done will only fix newer replays or live sessions.
