### ISSUE TITLE
VR stutters with Simhub using bass shakers

### ISSUE THREAD

**Issue by Battaglia-M** [SHWotever/SimHub#1360]
Hi.  I have been using Simhub with 1 pair of bass shakers & amp (Dayton Audio BSA-200 Amp with 2 BST-1 Bass Shakers Bundle) for the front corners of my sim rig since April.  Back then I was using the most version of Simhub, and I also acquired a license for it.  No performance issues at all, while using my HP Reverb G2 VR headset, FPS constant around 89.6 (max 90).

Last week I acquired another pair of bass shakers & amp (same brand & model) to put in the back corners of my sim rig, and I updated Simhub to version 8.4.6.  Once I start to race, I immediately noticed that my FPS was around 20!  I tried Automobilista 2, rFactor 2 and Asseto Corsa, all of which I have been using for months, with the bass shakers, and had zero problems.

I thought it could be a NVIDIA driver issue, so I updated to the latest version.  I also noticed there were no Windows upgrades (Windows 10 Professional 64 bits).  I thought it could be something with SteamVR (since it affected many games), so I tried to use OpenComposite + OpenXR, and the FPS loss still persisted.

When I uninstalled Simhub, turned off both amps, and changed Windows Sound settings back to 2-channels, the problem seemed to have gone away (I will do further testing today).  One thing that I noticed, and I don't think it makes sense given my PC (details below), is that the CPU usage stays almost "stuck" at 100%, so I'm thinking there is some process that is eating away all my CPU, all 32 threads of it, apparently.  Not sure if there is a process that runs within Simhub that is draining all my CPU performance, while in VR.

**My PC & software information:**
- ASUS ROG Crosshair X670E Hero (all latest drivers)
- AMD 7950X CPU (no OC)
- CORSAIR iCUE H170i ELITE CAPELLIX Liquid CPU Cooler
- G.SKILL Trident Z5 Neo EXPO Series for AMD 32 Gb (2x 16) DDR5 RAM
- Seasonic PRIME 1300 Platinum SSR-1300PD 1300W 80+ Platinum PSU
- 2x SAMSUNG 980 PRO SSD 2TB PCIe NVMe Gen 4 Gaming M.2
- Corsair 7000D full tower
- VR headset: HP Reverb G2 (v1)
- 2 bass shaker kits: Dayton Audio BSA-200 Amp with 2 BST-1 Bass Shakers Bundle
- Acer FHD 27" Monitor (supports up to 144 Hz)
- Windows 10 Professional (64-bits) updated
- NVIDIA driver updated to latest version as of 07/02/2023

**To Reproduce**
1. Go to Sound Control Panel in Windows 10
2. Select Realtek Sound
3. Change from Stereo to 4-speaker configuration, and select "OK"
4. Open Simhub, go to bass shaker option, and select the correct sound output
5. Select the option for 4-channels (4-corners)
6. Adjusted sound settings to 100% in the front and 50% in the back
7. Minimize Simhub
8. Start WMR & SteamVR
9. Open Steam, select rFactor 2, and select the option to start in SteamVR mode
10. Once the game fully loads, go into Single Player, select any car & track, and select "DRIVE"
11. Click "DRIVE" to start driving during a practice session, alone (private session = enabled)
12. Once you gain control of the car, monitor FPS.  It should be really bad right from the start, but you can see the fluctuations more clearly during 1 lap
13. Used fpsVR Steam software to monitor FPS performance while using VR (I can share logs here, if needed)

On a side note, I tried to disable plugins that are not needed, leave only bass shakers (I do not use any sort of dashboards), but it did not seem to have any effect.

**Comment by SHWotever** [comment]
Hi ! The fact that it started when adding new shakers and raising to two 4 channels makes me think about an usb bandwidth issue, which could explain the FPS Drop, you have not specified the sound card you were using with the shakers (BSA-200 Amp is an analog amp apparently),  if you are using an usb sound card that would explain the difference when getting more channels. If you are using an usb sound card I would try to move it to another usb port ideally far away from the VR headset. 
About your CPU clue can you check the task manager whenr running you will see simhub usage.

Do not hesitate to join the simhub log files as asked in the bug template, it's really important to check if nothing bad is happing inside simhub  :

> **Log files**
> Join log files available in C:\Program Files (x86)\SimHub\Logs
> Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

**Comment by Battaglia-M** [comment]
Hi, thank you for the quick reply.  I am using ASUS's own onboard soundcard, and I use 2 outputs in 4-channel configuration (using Windows 10 Sound Control Panel).  I have 2 cables that go directly from the mobo to the amplifier (no USB cables/connection used). The cables were bought from Amazon, and the link can be found below:

https://www.amazon.com/dp/B00LBK3870?psc=1&ref=ppx_yo2ov_dt_b_product_details

The mobo audio specs, as per ASUS's site, are:

ROG SupremeFX 7.1 Surround Sound High
Definition Audio CODEC ALC4082
- Impedance sense for front and rear
headphone outputs
- Supports: Jack-detection,
Multi-streaming, Front Panel Jack-retasking
- High quality 120 dB SNR stereo playback
output and 113 dB SNR recording input
- Supports up to 32-Bit/384 kHz playback"
Audio Features 
- SupremeFX Shielding Technology
- ESS® ES9218 QUAD DAC
- Gold-plated audio jacks
- Rear optical S/PDIF out port
- Premium audio capacitors
- Audio cover

I will run the setup again later today, and I will collect the fpsVR logs as well as check CPU usage, and share here.

Would it make sense for me to rollback to a version of Simhub around April, and see if that solves the problem?

**Comment by SHWotever** [comment]
It could be interresting to rollback to check if it's not a regression, that would allow to exclude a specific simhub issue and focus on the sound card. 
As you said going back to only two channels seems to solve it, which makes me think the issue is around the sound card. Have you updated the driver for it ? Sound card is often the forgotten one, we keep GPU drivers updated, but rarely sound card.

The release history : https://github.com/SHWotever/SimHub/releases

**Comment by SHWotever** [comment]
Can you join the simhub log files ? 

> Log files
> Join log files available in C:\Program Files (x86)\SimHub\Logs
> Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

**Comment by Battaglia-M** [comment]
[SimHub_v8_4_6_2_corners_front_practice_rFactor2.txt](https://github.com/SHWotever/SimHub/files/11943766/SimHub_v8_4_6_2_corners_front_practice_rFactor2.txt)
[SimHub_v8_4_6_4_corners_practice_rFactor2.txt
![fpsVR_SH_v8_4_6_2_corners_front_practice_rFactor2](https://github.com/SHWotever/SimHub/assets/138511978/84daa496-077f-4eb5-8d8f-45d59063f363)
![fpsVR_SH_v8_4_6_4_corners_practice_rFactor2](https://github.com/SHWotever/SimHub/assets/138511978/ef9a4378-749d-43bd-8aa8-c3034e407340)
![fpsVR_no_SH_practice_rFactor2](https://github.com/SHWotever/SimHub/assets/138511978/db65536a-a0d0-42c7-bd25-f4ee2a3b49a1)
![fpsVR_SH_v8_3_5_4_corners_practice_rFactor2](https://github.com/SHWotever/SimHub/assets/138511978/b49585bb-1e48-4f0e-871e-96f9bea9de02)
](https://github.com/SHWotever/SimHub/files/11943767/SimHub_v8_4_6_4_corners_practice_rFactor2.txt)
[SimHub_v8_3_5_4_corners_practice_rFactor2.log](https://github.com/SHWotever/SimHub/files/11943768/SimHub_v8_3_5_4_corners_practice_rFactor2.log)

**Comment by Battaglia-M** [comment]
Attached both SimHub log files and fpsVR files.  I did tests with version 8.4.6 on 4 corners (4 channels) and 2 corners (2 channels).  Then tried without it, then went back to my April version (8.3.5).
I felt that the fps drop did not happen at all on version 8.3.5 (4 corners), and it was much smaller on v 8.4.6 with 2 channels only.

I did update my audio drivers as well.

I am doing a full re-install of WMR, SteamVR and Steam, just to ensure it is nothing corrupted on that side.

**Comment by SHWotever** [comment]
Very strange, the only major shakeit change I did between those two versions is fmod (the audio engine) update (the previous version was severly outdated, while it was not an issue for the audio result, there were a few bugs in the old version breaking fmod on some systems with exotic audio devices). 

Can you check in the audio settings (there is probably a dedicated control panel) that there is no advanced options being enabled (spacialization ...) ? I know that asus comes with a lot of "sneaky components", maybe there is some kind of incompatibility here between multi channels and some advanced processing.  The simhub logs shows nothing specific, that would have been easier

**Comment by Battaglia-M** [comment]
I will check it first thing tomorrow.
Would it make sense to have a second audio card, or maybe an external one, dedicated to the bass shakers? If so, could you recommend any (last time I bought a sound card was a Sound Blaster Live back in 1998......).

**Comment by Battaglia-M** [comment]
![Sound Control Panel 1](https://github.com/SHWotever/SimHub/assets/138511978/3bb1cdac-71b0-4f44-bd20-cda69278fd2b)
![Sound Control Panel 2](https://github.com/SHWotever/SimHub/assets/138511978/35f71156-10da-4996-a8d1-a4dcd08cadde)
![Sound Control Panel 3](https://github.com/SHWotever/SimHub/assets/138511978/fa6dd7a9-9267-48c8-ae14-75ee70c68d9d)
![Sound Control Panel 4](https://github.com/SHWotever/SimHub/assets/138511978/a0d3d2b6-0094-4789-92f7-d3d7b59ed12e)
![Sound Control Panel 5](https://github.com/SHWotever/SimHub/assets/138511978/22d737f7-d4c8-43b7-bf4e-335fa4ae1a81)
![Sound Control Panel 6](https://github.com/SHWotever/SimHub/assets/138511978/91a206c3-67eb-459a-998b-c53ef93ad2ac)

**Comment by Battaglia-M** [comment]
![Simhub Sound Settings](https://github.com/SHWotever/SimHub/assets/138511978/3784a762-1afb-4445-b178-531b80b91bca)

**Comment by Battaglia-M** [comment]
Sound configuration.  I did notice a couple of things:

1) Sound Control Panel: there is one screen that has an option for "Signal Enhancements".  I will disable it and test

2) Simhub shows a red message saying that I'm using my default audio card, and a dedicated one is recommended

**Comment by SHWotever** [comment]
Indeed this means that the sound card is your windows primary one, it's just an alert some people don't get that bassshakers sound is not intended to be redirected to their classic headset/loudspeakers which is likely to be the case when you use the windows primary sound card (except in VR indeed ...)

I think I also see a suspicious setting, your default audio settings looks "mad" (192000Hz 32bits) this is way ahead of the standard, 

and could explain why it consumes so much when adding more channels. This requires to generate a lot of useless data
Can you get it back to standard value ? 48000 16bits or 44100 16 bits 
![image](https://github.com/SHWotever/SimHub/assets/2207331/c31e64fd-b947-40a1-80dd-919c3d462c48)

About advanced settings realtek comes with an additionnal control panel where more "advanced effects" could be hidden :
![image](https://github.com/SHWotever/SimHub/assets/2207331/b66d643d-1d05-4c63-83b1-03adabe21e41)

**Comment by Battaglia-M** [comment]
I decided to acquire an external USB sound card.  Check some reviews, and found a lot of people are using a Vantec NBA-200U 7.1 USB sound card, so I bought it.  Will install it and do some testing between today & tomorrow.

**Comment by Battaglia-M** [comment]
I installed the external USB sound car and ran some tests with the latest version of Simhub (8.4.8) and with both amps (all 4 shakers) turned on, and I had zero problems. I believe the real problem was indeed the onboard sound card.

Thank you very much!!
