### ISSUE TITLE
rf2-porsche cup 992-gear shift et v8.4.7

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1363]
Hello
un problème sur les bass-shakers
sur rf2 en porsche cup 992, le gear shift n'est pas bref (80ms) comme sur les autres voitures mais il "déraille" et dure environ 1sec.

cela se produit uniquement sur la 8.4.7. 
cela ne se produit pas sur la 8.4.6

ce "déraillement" du gear shift se produit uniquement dans les cas suivants :
- passage de point mort vers 1er rapport
- passage du 1er rapport vers le 2eme rapport
- passage du 2eme rapport vers le 1er rapport
- passage du 1er rapport vers le point mort
- passage du 5eme rapport vers le 6eme rapport
- passage du 6eme rapport vers le 5eme rapport
[Logs.zip](https://github.com/SHWotever/SimHub/files/11982573/Logs.zip)

j'ai essayé plusieurs autres voitures et je ne rencontre pas ce souci
j'ai essayé quelques voitures sur raceroom et je n'ai pas rencontré de problème

**Comment by SHWotever** [comment]
Hello !
J'ai acheté la voiture pour tester mais sans succès J'ai vérifié je n'ai pas eu ce soucis, est tu sur que ce bien l'effet "gear" qui fait ce résultat? 
![image](https://github.com/SHWotever/SimHub/assets/2207331/9377036e-8359-4e11-9805-ebab6307c3f5)

Peut ètre si tu as un replay simhub quelque chose se cahce peut ètre dans les données que je n'ai pas ?

**Comment by herve4545** [comment]
merci pour le retour
du coup....j'étais resté sur la 8.4.6
je viens de ré-installer la 8.4.7 et le problème a disparu
Les mystères de l'informatique
Désolé pour le dérangement

**Comment by herve4545** [comment]
comment ça...tu ne possédais pas cette voiture :)
Une des meilleures de rf2 :+1:

**Comment by herve4545** [comment]
Hello
Finalement, le problème est revenu
très présent entre point mort et 1ère sur ce replay
V8.4.7
https://drive.google.com/file/d/1NHbvtrlS3nVwcjTLWCT2_LaKecg1V_K-/view?usp=drive_link

**Comment by SHWotever** [comment]
Hello !

Je viens de tester le replay je n'ai pas vu de soucis sur le gear shift, je pense que c'est un autre effet (wheel slip je dirais) visiblement après les changements de vitesse les vitesses des roues sont "bizarres" (c'est encore une voiture ou la telemetrie est "censurée")

Elle a l'air de perdre le grip complementement après les changements de rapport : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/9e78c0c9-5aab-4c97-9e3c-1e797fff41d4)

En terme de "durée" ca ressemble a ce que tu décrit. 

Auquel cas vu la "physique" de la voiture il faudrait baisser le gamma pour "filtrer" plus fort le slip :

![image](https://github.com/SHWotever/SimHub/assets/2207331/c1d9e3ee-71cf-461e-a913-e26d1ac4a4de)

**Comment by herve4545** [comment]
Hello
merci pour ton retour mais j'utilise pas le wheel slip pour rf2
je vais continuer à fouiller
je vais faire un profil spécifique pour cette voiture et voir ce qui se passe

**Comment by herve4545** [comment]
Hello
J'ai reproduit le problème avec un mod
Sans doute plus de données à visualiser car non censurées
le mod flat6 de enduracer.
ca se produit sur sebring et entre les rapports 5eme et 6eme
j'ai désactivé les différents paramètres bass-shaker et à chaque fois, le problème se produit avec gear shift

https://drive.google.com/file/d/10LDNO52e4622sYBZnjSIFrX6ZBUgamhK/view?usp=drive_link

**Comment by herve4545** [comment]
Hello
j'ai reproduit le problème avec 2 voitures officielles de S397
Audi R8 gt3 2019
bmw m6 gt3
avec de très gros freeze entre les rapports 5/6 et 6/5

pour la bmw m6 gt3 : lorsque le problème s'est produit, j'ai fermé et relancé simahub sans quitter le jeu et le problème a disparu
Mais je sentais qu'il était présent car, quelques fois, le passage 5/6 etait très lègèrement plus long que pour les autres rapports
Pour la bmw m6, j'ai beaucoup roulé avec cette voiture pendant le mois d'avril sans jamais rencontrer ce problème.
Cette voiture n'a pas été mise à jour depuis le 21/03/2023

A noter que je roule tous les jours depuis plusieurs mois sur les GTE et je n'ai jamais rencontré ce problème. Vraiment bizarre

Je suis incapable de préciser à partir de quand ou quelle version simhub le problème est apparu
je vais essayer avec 8.4.6 pendant quelques jours pour voir


Ca n'a rien à voir avec rf2, mais ça ; ça ne peut pas avoir un impact
Added support for two Reiza Studios "oldies" (rfactor 1 based) :
Copa Petrobras de Marcas
Formula truck 2013

**Comment by SHWotever** [comment]
Hello ! J'ai pas eu le temps de regarder encore,

Juste pour mon information ca se produisait aussi dans les replay simhub ? Est ce que tout les reste restait fluide ? Dashboards etc ... ?

Pour les "oldies" non pas de consequences ce sont juste des entrées et de la configuration automatique pour ces jeu mais cela s'appuie sur le plugin RF1 et le code associé sans aucun changements pour RF2.

**Comment by herve4545** [comment]
mes tests du jour
1) tests sur V8.3.13
je roule 30 min avec gte et pas de freeze sur gte comme d'habitude
j'enchaine avec bmw m6 et gros freeze en passant la 6eme
je ferme et relance simhub et le problème a disparu et, malgré mes efforts, je n'ai pas pu le reproduire .....avec la bmw m6 mais aussi avec la porsche cup 992

2) tests sur V8.3.6
je roule 45 min avec gte et pas de freeze sur gte comme d'habitude
j'enchaine avec bmw m6 et freeze présent (mais moins fort que pour le test 1) en passant la 6eme
je fais reset calibration mais le problème est toujours présent. je fais plusieurs reset calibration mais ca ne résoud pas le problème
je ferme et relance simhub et le problème reste présent mais à un degré moindre

Je ne sais pas trop quelle conclusion en tirer si ce n'est qu'il semble quand même que fermer simhub aide à résoudre ou à diminuer ce problème de freeze

**Comment by herve4545** [comment]
aujourd'hui, j'ai refais un test sur la bmw m6 après avoir roulé en gte
résultat : gros gros freeze quand je passe de 5 vers 6 et de 6 vers 5
info complémentaire : le chiffre 6 mets un peu de temps à s'afficher sur mon dash lors de ce gros freeze

si je ferme et relance simhub, le problème de freeze disparait

**Comment by DAZ-64** [comment]
Salut, copier/coller du Forum RFR.

""Salut, j'ai également un problème de freeze depuis plusieurs semaines ! ce weekend j'ai remarqué que cela se produisait à chaque passage en 6eme pied au plancher sur ligne droite rencontré en 1er sur la "BMW M4 Class 1" pareil avec la "bmw m6 gt3" et "ferrari 488 gt3"---- sur Le Mans et Spa, ça ressemble plus a des saccades que des freeze durant 3/4s sans perte de FPS. J'ai également des bass-shakers je testerai désactivé ce week-end.""

aucun problème en BTCC, chez moi cela ce produit sur des véhicule avec des haute vitesse de pointe, je testerai en désactivent SimHub dans un premier temps, puis sans bass-shakers.

**Comment by herve4545** [comment]
Problème toujours presenet5sur la BMW M6 par exemple

**Comment by herve4545** [comment]
Hello
Testé ce jour avec la BMW M6 GT3 et Porsche Cup 992
Le problème a disparu
Les voitures concernées n'ayant pas reçu de mise à jour ; peut-être est-cd-dû à la mise des shakeit en v9.1.13
Je ferme
