### ISSUE TITLE
A better Map

### ISSUE THREAD

**Issue by Landi2022** [SHWotever/SimHub#1364]
**Is your feature request related to a problem? Please describe.**
The map is pretty confusing. By that I mean that the driver on the map is not even pointed out to the one you are looking at. Also, no team colors are displayed

**Describe the solution you'd like**
I wish that the map is clearer

**Describe alternatives you've considered**
I have no alternatives

**Additional context**

**Comment by FullPace** [comment]
What exactly do you mean?
The driver is always focus, even on small cut outs of the map and you can select a highlight color to make it pop even more.
![image](https://github.com/SHWotever/SimHub/assets/116221480/086f5dee-e885-4e32-9ded-c9b7e3f40a82)

**Comment by Landi2022** [comment]
> What exactly do you mean?
> 
> The driver is always focus, even on small cut outs of the map and you can select a highlight color to make it pop even more.
> 
> ![image](https://github.com/SHWotever/SimHub/assets/116221480/086f5dee-e885-4e32-9ded-c9b7e3f40a82)
> 
> 
> 
> 

So with me, the driver is not displayed in green or highlighted in another color

**Comment by FullPace** [comment]
You can adjust in the map settings. there are aome drop down menus for player and opponents with a lot of optiona

**Comment by SHWotever** [comment]
Hi ! I close this, there are now class colors, and indeed as pointed fullpace opponents vs player style can be tuned.
