### ISSUE TITLE
Leaderboard - ajout de donnees

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1366]
Objet :
Enrichir les données du leaderboard avec

Type de pneu (soft, hard, etc...)
mfrontTireCompoundName
mrearTireCompoundName
Sector1lastlaptime et sector1bestlaptime
Sector2lastlaptime et sector2bestlaptime
Sector3lastlaptime et sector3bestlaptime
nombre d'arrêts aux stands effectués 
si l'arrêt aux stands est en cours (ISINPIT)

Nota :
Ajouter aussi des infos pour les pneus car on ne peut pas afficher le type de pneu pour certains mods de Rf2
le DataCorePlugin.GameRawData.CurrentPlayerTelemetry.mFrontTireCompoundIndex ne suffit pas pour déterminer quel est le type de pneu utilisé par le véhicule
ex : Enduracer Alpine A110 GT4 en pneu WET vs Ferrari GTE avec le même CompoundIndex et pas le même type de pneu en réalité

Merci

mFrontTireCompoundName peut-être
edit : oui cet attribut permet d'afficher le type de pneu correct pour, au moins, certains mods. Secondmonitor l'utilise avec succès

**Comment by herve4545** [comment]
+ ces données
LapsToLeader et LapsToPlayer

**Comment by herve4545** [comment]
Il serait intéressant d'avoir ces états
Pit Request
In PitLane
Enter Pit
In Pit
Exit Pit

In Garage
Exit Garage

Merci

**Comment by herve4545** [comment]
un grand merci
J'ai plus qu'à me mettre au boulot

**Comment by herve4545** [comment]
Une petite question
Étant entendu que les 5 ahead/behind n'affichent pas les concurrents qui sont aux stands

Est ce que je peux quand même afficher les données ci-dessous pour ces 5 ahead/behind :
- DriverIsCarInPitLane : si la voiture du conducteur est dans la voie des stands
- DriverPitCount : combien de fois le pilote est allé aux stands

**Comment by herve4545** [comment]
sur rf2, j'ai commencé à intégrer les pitcount et les type de pneus sur mon dash_1 pour les 5 ahead/behind

en jeu, au départ d'une course, le pitcount n'est pas à 0 mais à 1 voire à 2 et, ce, sur practice ou race
bizarre, j'ai enregistré un replay pour ce practice et cette course, et, quand je rejoue le replay, les pitcounts n'ont plus les mêmes valeurs.
en course, ils étaient tous à 1 et sur le replay, ils sont tous à 0

sur ces mêmes 5 ahead/behind, j'ai intégré les types de pneus en me basant uniquement sur le driverfronttyrecompound(raceposition)
sur rf2 et r3e, ca fonctionne bien
sur ams2, je n'obtiens rien (je récupère null)

**Comment by herve4545** [comment]
le LeaderboardOpponentGap ne semble plus fonctionner dès lors que j'ai au moins 1 tour de retard sur le leader.
Dans ce cas, je recois 0.0 au lieu de +1lap

j'ai essayé celui-ci : return drivergaptoleader(maraceposition) mais même problème

**Comment by SHWotever** [comment]
Hello ! Pour les pits counts je suis sur le coup, vu qu'ils sont comptés et qu'ils ne viennent pas de la telemetrie il faut resetter les statistiques au bon moment et j'ai déjà repéré des cas où ça a loupé. 
Pareil si on "navigue" directement à un point du Replay si on ne passe pas le moment du pit stop il ne sera pas compté. Mais pour ça par contre on ne peux pas l'éviter.

Pour le gap je vais regarder je ne sais pas pourquoi pour le moment.

Pour ams2, c'est normal il n'y a pas la donnée. Avant je m'en tenais à ce qui était présent sur un nombre significatif de jeux... mais les données comme le compound c'est beaucoup plus rare. Et pour tout ce qui pourrais venir s'ajouter en plus il ne faut pas espérer avoir 100% des jeux qui en disposent, même parmis les plus récents. Si ça renvoie null, c'est simplement que ça n'est pas disponible sur ce jeu/a ce moment là (ce dernier cas surtout pour les données de pit stop pour le moment).

**Comment by herve4545** [comment]
pour les 
driverbestlapsector1(x) + '-' + driverlastlapsector1(x)
driverbestlapsector2(x) + '-' + driverlastlapsector2(x)
driverbestlapsector3(x) + '-' + driverlastlapsector3(x)

sur rf2, ils se cumulent s2 = s1+s2 et s3 = s1+s2+s3...d'après ce que j'ai compris
sur r3e, je n'ai pas réussi à récupérer une quelconque donnée


pour ams2 (comme pour acc d'ailleurs) je suis pas surpris par ta réponse. ces jeux sont pas terribles pour la shared memory
j'espère que le mans ultimate sera bien à ce niveau

**Comment by herve4545** [comment]
sur rf2
les s1/s2/s3 s'affichent lorsque le tour est terminé
ex : avant la fin du 1er tour, il n'y a rien qui s'affiche

j'ai pas mal de problème de coding de mon côté mais je pense quand même qu'il y a un souci sur ces sx

**Comment by SHWotever** [comment]
Hello, il faut que le tour soit fini en effet, c'est le dernier tour (sous entendu fini) comme le lastlaptime.

**Comment by herve4545** [comment]
Hello
Arf, dommage
ca serait bien que ce soit en temps réel comme pour [DataCorePlugin.GameData.SectorxTime]

sinon, je pense que ca va être un peu perturbant d'avoir ce décalaga d'affichage entre :

1) mon [DataCorePlugin.GameData.Sector1Time],'') que j'affiche sur le dash principal

2 )son équivalent affiché sur le leaderbord (driverlastlapsector1(moi))

**Comment by SHWotever** [comment]
C'est une question de cohérence entre les jeux, pour la plupart c'est une fois le tour fini, je vais m'en tenir à ça pour éviter que chaque jeu donne des choses différentes pour "soi disant" la même donnée ;)

**Comment by herve4545** [comment]
ok ca marche

**Comment by herve4545** [comment]
Hello
Avec la 9.0.5b3 qui me semble être une version très aboutie
Bravo pour le super travail

J'ai testé sur rf2
OK pour moi pour :
- les sectors
- le pitcount (il faut que je poursuive les tests)
- le pittime (il faut que je poursuive les tests)
- les types de pneus
- le InPit
- InPitLane (en testant le speed, on peut afficher le message 'Box')

Pour l'affichage en temps réel des sectors
j'ai constaté que r3, rf2, acc et ams2 permettent d'afficher les sectors en temps réel. J'ai testé rapidement avec secondmonitor.
Pour Iracing, je ne sais pas mais tu sembles bien connaître ce jeu
Pourrais-tu reconsidérer la question pour les afficher en temps réel :)

En tout cas, merci pour ces très grosses évolutions

![1](https://github.com/SHWotever/SimHub/assets/58605557/02a7921b-9bbc-46fc-9f78-a9b3679dec70)

**Comment by herve4545** [comment]
Pour ce problème,
le LeaderboardOpponentGap ne semble plus fonctionner dès lors que j'ai au moins 1 tour de retard sur le leader.
Dans ce cas, je recois 0.0 au lieu de +1lap

J'ai beau cherché, je ne trouve pas de bug chez moi
Jai downgradé en 9.0.4 mais ca ne fonctionne pas non plus. Je suis perdu

**Comment by SHWotever** [comment]
Hello a froid ça me paraît normal, le leaderboardposition est sur 1, je ne vois pas de formule pour le changer, donc le gap du leader au leader il n'y en a pas, ce qui me surprend c'est que de temps en temps il y ai de la donnée.je regarde demain au cas où ;)

Mais c'est sur que le leaderboard complet a droite et le composant seul sans position définie ne peuvent pas donner le même résultat
(Dans une répétition simhub s'occupe d'incrementer le leaderboardposition a chaque ligne), mais sans répétition c'est la première ligne sur tu as, qui est bien vide aussi pour le gap a droite dans le leaderboard complet.

Pour avoir sa propre ligne, deux possibilités, soit assigner raceposition a leaderboardposition via une formule, ou plus simple activer l'option         LeaderboardPositionRelativeToPlayer et mettre raceposition a zéro (dans ce mode la position 0 est centrée sur le joueur en cours, 0 le joueur, -1 le précédent, 1 le suivant etc ...)

**Comment by herve4545** [comment]
Oui pardon le gapmode devrait être sur fromplayer pour mon dash_1
Normalement Il etait bien sur fromplayer mais je n'ai pas fais attention lors de la copie d'écran car je faisais des tests

Si cane fonctionne plus, C'est peut être de ma faute....j'ai peut être fait une modif par erreur
Je regarderai demain

**Comment by SHWotever** [comment]
Je ne parlais pas du gapmode, si tu veux la même donnée qu'à droite c'est bien le gap "from leader", par contre si tu veux ta ligne de leaderboard "a toi" sans trop d'efforts et retrouver ce que tu montres a droite, c'est un peu plus bas dans les options
- LeaderboardPositionRelativeToPlayer actif (pour que la position soit centrée sur toi) 
- leaderboardposition a 0 ou 1 (j'ai un trou de mémoire :( )

**Comment by herve4545** [comment]
Hello
J'ai corrigé plusieurs erreurs sur mon dash pour ce gap_leader
Il semble que j'avais déjà cassé cette fonctionnalité il y a plusieurs mois

**Comment by herve4545** [comment]
Hello
A tout hasard,
Est ce qu'une donnée PIT REQUEST serait disponible dans les jeux ?
Merci

**Comment by herve4545** [comment]
Hello
Merci pour les sectors "temps réel"

**Comment by herve4545** [comment]
Hello
Une petite question sur les temps des sectors
on a les cudrivercurrentlapsector1time et drivercurrentlapsector2time
mais on a uniquement le driverlastlapsector3sectortime pour le sector3

ce qui veut dire que à chaque nouveau tour de piste, les sectors 1 et 2 sont réinitialisés jusqu'à leur prochaine alimentation alors que le sector 3 reste alimenté jusqu'à sa prochaine alimentation

pourquoi cette différence de traitement ? Ne serait-il pas possible d'avoir un "current" pour le s3

Cela vaut aussi pour ces attributs
[DataCorePlugin.GameData.Sector1Time]
[DataCorePlugin.GameData.Sector2Time]
[Sector3LastLapTime]

Merci

**Comment by SHWotever** [comment]
Pour le coup dès qu'on finit le s3 on passe au tour suivant, donc le temps du secteur n°3 pour le tour en cours n'existe jamais, dès que l'on a fini le tour tour tout passe en "last lap"

Donc au final ca existe mais c'est : driverlastlapsector3, ca ne peut pas exister sur le tour en cours (sauf Iracing qui à pas mal de circuits avec plus de 3 secteurs, mais c'est une autre histoire que je doit adresser aussi :D ... mais ca ne change pas la logique, le dernier secteur conclut le tour).

Si je prends l'exemple de rf2, suivant la même logique le s3 du tour en cours n'existe juste pas :

![image](https://github.com/SHWotever/SimHub/assets/2207331/18b70bf2-709e-4fd9-a616-7884187843e2)

Pour les pit requests, j'ai regardé, mais me faudra plus de temps pour comprendre la logique des différents jeux, ca varie pas mal, je n'ai pas encore tout compris :(

**Comment by herve4545** [comment]
OK Merci
En tout cas, c'est des super évolutions
On a un leaderboard très très complet
Bravo pour le super taf

**Comment by SHWotever** [comment]
Sur AMS2 j'ai juste les secteurs du tour en cours, effectivement il y a un petit soucis avec les unités (seconds vs millisecondes)
Pour le moment je n'ai pas tenté de combler les manques sur les secteurs (excepté Iracing pour le moment) 
Donc que ce soit current/last/best cela dépend de ce que le jeu fournit (a cet état de la béta), 
mais en aillant le "current", on peut commencer à déduire les autres en effet, je suis en train de préparer ça justement.

**Comment by herve4545** [comment]
pour rf2, j'ai pas mal roulé et tout fonctionne très bien pour les données que j'ai ajouté :)
![0](https://github.com/SHWotever/SimHub/assets/58605557/6b7dfe6f-765a-47bc-a736-cbaf44f05ff5)
![0 1](https://github.com/SHWotever/SimHub/assets/58605557/539ca3f2-010e-47a0-bb14-2ac64acbd3d4)

**Comment by herve4545** [comment]
Hello
Ok vu.....pour le Pit request a venir
Il pourrait être intéressant d'avoir également les DNF. A voir si c'est disponible
Merci

**Comment by SHWotever** [comment]
J'ai rien vu qui corresponde à cette donnée, si tu as un replay avec un cas identifié de DNF que je puisse creuser ca m'interresse ;)

**Comment by herve4545** [comment]
sur rf2
A partir du milieu de la video
je créé un paquet de dnf en roulant à contre-sens
![1](https://github.com/SHWotever/SimHub/assets/58605557/8d58f05f-9e25-4260-901f-05629baf1c4a)

https://drive.google.com/file/d/1ZbRR66Cz6UhBS-QYd5c-fee28sh_jOYw/view?usp=drive_link

**Comment by SHWotever** [comment]
En fait ... en fouillant ... j'ai trouvé la donnée sur RF2 et ams2, faut que je continue la quète :D

**Comment by herve4545** [comment]
finalement, rf2 est plus riche que je ne l'imaginais
pour les ingarage, inpit, inpitlane, outlap
c'est rf2 qui fonctionne le mieux

Pour inpitlane, y aurait-il une possibilité de le scinder en 2 avec :
- enter pit
- exit pit
pour nous les joueurs, il y a le pitmode et je ne sais pas si ca existe pour les IA

le "gainposition" me perturbe un peu MDR
quand je gagne des place, ca affiche +xx et quand je perds des places, ca affiche -xx
perso, j'aurai fait le contraire

ben oui, parmi toutes les données que j'ai ajouté, j'ai trouvé d'autre à redire :)

**Comment by SHWotever** [comment]
pour le gainposition c'est le nombre de "places gagnées" littéralement, si je prends deux places j'en ai bien gagnées "2", si je perd deux places mon gain devient négatif -2 places. Pour ce sujet il y aura deux camps :D J'en ai choisi un :D, vu que c'est juste un nombre un petit "-" devant et c'est arrangé ;)

Pour les pits, comme je disais plus tôt je m'arrête là, les leaderboards ne sont pas le sujet principal de simhub, et j'ai déjà fait pas mal de tours de passe passe pour le remplir, mais je ne veux pas m'engager dans ce niveau de détail au risque commencer à plomber les perfs :( . 

Je vais juste conclure avec les DNF que j'ai vu à deux/trois endroits, ainsi que les Pitrequests.
Après je ne cherche pas à tout extraire, l'idée ca n'est pas que l'on se trouve avec une majorité des données de leaderboard qui ne marchent que sur un jeu. pour le moment j'ai plutot pas mal choisi et le tout est plutôt cohérent, mais avec des enter/exit, là ca commence à être rare. En tout cas je stoppe ce sujet, je le stabilise, et plus tard si la demande se fait sentir j'engagerait un nouveau chantier ;)

**Comment by herve4545** [comment]
OK Ca marche
pas de soucis ; c'est déjà très très complet avec ce que tu as ajouté.
Oui tu as bien choisi. J'ai pas mal testé sur rf2 et le résultat est vraiment super.....et ca laisse augurer de bien belles choses avec LMU
pour r3e, ams2 c'est aussi très bien
pour acc....ce jeu est pauvre en données. je vais supprimer toutes les spécificités que j'avais intégré. de toute facçon, ce jeu sera remplacé l'année prochaine
Je vais pouvoir me passer de secondmonitor. J'en avais encore l'utilité pour les pits
