### ISSUE TITLE
I Racing eont Connrct

### ISSUE THREAD

**Issue by Tikbarb** [SHWotever/SimHub#1368]
**Describe the bug** - unable to read I Racing Data. it worked once or twice but now it always fails to read data  ive done all the troubleshooting manh times. tried disabling all third party. same issues  just eont load data, but rpm and fuel and stuff loads right  it recognizes that game is "connected" and mobile server loads  

**Simhub version**
Make sure to run the latest version
newest 

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

done
[LapLog.txt](https://github.com/SHWotever/SimHub/files/11996978/LapLog.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/11996979/SimHub.1.txt)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/11996984/SimHub.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/11996987/SimHub.1.txt)
[LapLog.txt](https://github.com/SHWotever/SimHub/files/11996988/LapLog.txt)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Does the issue happens on stock dashboards, from your log I see that the dashboards mostly uses a third party plugin iRacingExtraProperties which is indeed disabled and might have been crashing. Can you give a try to stock dashboards to check that the issue is in simhub or not ?
