### ISSUE TITLE
Option for dial gauges

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#137]
Possible to add this red needle option for dial gauges? 

https://youtu.be/Au7xYDyBpQY

Option to have it stay at max or drop down after certain amount of time? (Or is there some clever ncalc to solve it?)

Also apologies for poor video doing a quick YouTube search to find an example.

**Comment by zegreatclan** [comment]
I see ! I think a max function could solve this ;) something like max(value , keepdelay) when it detects a max it keep it for the specified time

**Comment by zegreatclan** [comment]
Ok ive made the "maximum" function , but it's not enough it needs to be coupled to some smoothing algorythms, because when the needle drops it drops instantly.

**Comment by Meekstaaa** [comment]
Hey again, 

Just looking at this and noticed you added a smooth function. It doesn't appear to work in Ncalc though.

Any tips?

**Comment by SHWotever** [comment]
Hi ! Unfortunately after all those years this request remained very very rare. I close it for readability purpose even if the the feature would be interesting.
