### ISSUE TITLE
[Feature request] Support the use of competitors in addition to opponents in iRacing SDK data for watch mode gaps

### ISSUE THREAD

**Issue by teknologika** [SHWotever/SimHub#1370]
**Is your feature request related to a problem? Please describe.**
Simhub currently does not display gaps when watching a race as the driver who is spotting or broadcasting the session is not in car on track and competing. The data is present in the "competitors" structure, not the "opponents" structure.

**Describe the solution you'd like**
Simhub should calculate the gaps between cars when watching 

**Describe alternatives you've considered**
I have built my on login that does a lot of this, however a developer essentially ends up re-developing the same code as the base Simhub iRacing plugins do.

**Additional context**
This makes Simhub a viable option when broadcasting races, and the broadcaster is in watch mode.

**Comment by teknologika** [comment]
This appears to be working in V9 releases.

**Comment by SHWotever** [comment]
I've tuned lot of things about opponents in the recent versions, 
I've not changed it "explicitly" for this issue as broadcasting is not my goal (I prefer to keep focused on "real time" "you as a driver" experience which is already a huge work :D), but there have been lot of background work which indeed could have fixed this case.

I close it, but do not hesitate if somehow it was a "false positive" fix :D
