### ISSUE TITLE
Cant install SimHub. Run time error 

### ISSUE THREAD

**Issue by gersonlizama** [SHWotever/SimHub#1372]
**Describe the bug**
When attempting to install version 8.4.8 a pop up error displays not allowing the install to take place.

**Simhub version**
Currently not running any version.

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**
1. launch installer .exe
2. run through installer steps
4. hit install and wait for error 
6. See error

**Expected behavior**
run time error at (3:841) swbemobjectset invalid class

**Screenshots**
![image](https://github.com/SHWotever/SimHub/assets/9085924/89854456-5581-47f2-a370-4fe3d3de8e14)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
Running on Windows 10 I have updated to the latest version and I have attempted to install the .NET frameworks. Version 4.8 is already installed and I have attempted to install version 4.8.1 but every time the installer finishes and I restart the computer the run time error still occurs. Tried multiple system restarts as well as deleting all previous simhub files.

**Comment by SHWotever** [comment]
Hi !

Apparently your windows WMI component is broken preventing the installer to work correctly (Simhub uses it too and would not work properly neither.)

You can find advices about hot to fix your windows WMI component here: https://www.thewindowsclub.com/how-to-repair-or-rebuild-the-wmi-repository-on-windows-10

Best regards,
Nicolas

**Comment by SHWotever** [comment]
I close it, as seen on discord it was indeed a broken WMI repository.
