### ISSUE TITLE
ATS Telemetry 

### ISSUE THREAD

**Issue by dylanb92010** [SHWotever/SimHub#1374]
Sorry if this is the wrong place to ask for assistance, (if it is please redirect me to the correct place) 
I need to know how to get these outputs from American Truck Simulator:
-Fuel Level
-Speed (MPH) 
-RPM 
-Gear

Any help is appreciated 

Also, how do I get the ATS map on the dashboard, I see the option on the left for "ETS2/ATS Map",, But whenever I use it, it only makes the ETS2 map and not the ATS map.

**Comment by SHWotever** [comment]
Hi !

It depends where you want to display it, but here are the properties :
![image](https://github.com/SHWotever/SimHub/assets/2207331/ecca7803-dea0-4062-b2f0-8a34d47b4665)


(NB :"speedlocal" uses the speed unit configured in the simhub settings.)

Concerning the map it will fallback to ets2 in the designer but load the correct one in running conditions (if ats is currently loaded in simhub). The design and color scheme used is a generic one for both ATS and ETS2

**Comment by dylanb92010** [comment]
Those didn't work, I think I am putting the property in the wrong place. Right now I have them set up in the "value" entry.

Also, am I supposed to mess with the Raw Result?

(Video of what I'm talking about
https://github.com/SHWotever/SimHub/assets/110776467/e78e89af-e53a-4683-bee3-ba250820ea40

**Comment by SHWotever** [comment]
Value is the right place.

About rpm take care you must divide it by 1000, gauges never shows rpms as is, but thousands of rpms.

You can check the existing dash to get samples. The Audi one contains everything about rpm and speed

**Comment by dylanb92010** [comment]
This is wierd, I tried using the Audi dash to see if it would even work and it didn't. Nothing happened when I moved my truck in game. I know that Simhub is working with ATS because I have a button box on Simhub and it works fine with ATS.

**Comment by dylanb92010** [comment]
Well, that would explain it. It does say game disconnected while i'm driving.

Ive had issues with the Steam client, so it isn't the Steam version.

**Comment by SHWotever** [comment]
Then you have to manually install the plugin.

Unfortunately for ethical reasons I can't give much support for non legit game versions I'm sorry.

**Comment by dylanb92010** [comment]
After reading further into the article that you sent me earlier, I figured out that I can't have a different Telemetry software installed, and I did. I also didn't have the C++ package installed. After fixing all of that it's working now. Thanks for the help.
