### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Glitzygamin** [SHWotever/SimHub#1376]
Hello. I downloaded sim hub and somehow it made my sims 4 game not open. When I try to click on it it says “the sims 4 is already running” please help. This is the only thing that I downloaded 

**Simhub version**
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi ! 

There is no known incompatibilities with "unknown" games (sims 4 is not known or supported by simhub) and I can't seen any ways where the simhub installation could interfere with such game. Can you confirm the game was closed and not running (using task manager), this kind of message looks very close to many apps preventing multiple process at the same time (simhub does the same) while the process is still runnng, Task manager or a simple reboot will tell if simhub installation is faulty (even if I can't believe simhub would have any far or close interactions with sims 4).
