### ISSUE TITLE
DashStudio - Text Effects > Shadow Color code (vocore)

### ISSUE THREAD

**Issue by stssamsts** [SHWotever/SimHub#1378]
Hi Nico
The shadows colors of text effects not affected by fx (Formula code) not working on VOCORE displays, (don't change) with a formula, example : Shadow color default : black, color code the speed text item, above 300 is red, bellow is black (same issue for value / color calculated tab) 

_SimHub V8.4.8_ (could be addressed for upcoming V9) 

I see you answered on every last #v9beta-feedback but not on mine so I post here for a fix later, I know you're overloaded of must important things, sorry to bother you with that..

**Merci infiniment pour tout**
(désolé pour le label "triage" je connais pas encore github dsl)

**Comment by SHWotever** [comment]
Hello ! I indirectly answered I already fixed it in the new bete yesterday;)

**Comment by stssamsts** [comment]
> Hello ! I indirectly answered I already fixed it in the new beta yesterday;)

Sorry I missed that 🙏 merci

**Comment by stssamsts** [comment]
Wotever already on it 🤝🏻
