### ISSUE TITLE
[Plugin Development question]

### ISSUE THREAD

**Issue by kaaac** [SHWotever/SimHub#1379]
Hello Again :)

How to force reload a plugin after leaving plugin settings page with changes?

:)

**Comment by SHWotever** [comment]
Hi !

I'm sorry I'm not sure to understand the question. Can you explain more deeper the use case ? "Leaving" is somehow unclear to me. 
But at the end overall there is no "plugin reload" method availalble. 
It's up to the plugin logic/ui to apply their own settings.

**Comment by kaaac** [comment]
Sorry for unclear question. I need to execute Init() function. As i saw some of plugins have some kind  behaviour of reload all simhub after leaving plugin settings screen.

**Comment by SHWotever** [comment]
Ah, the plugin reload occurs in a few specific cases :
- Everytime a new game is activated
- After exiting settings when :
    - Enabled plugins had been changed (activation, menu options ...)
    - If the current game UDP/TCP port has been changed.
    - If the current game UDP forward settings has been changed.
    - If the current game reader option had been changed.
    
Except those cases there is no manual/individual plugin reload available.
