### ISSUE TITLE
[Compatibilité 74HC595 8-Bit]

### ISSUE THREAD

**Issue by gegewrc2** [SHWotever/SimHub#1380]
Bonjour Whotever,

J'ai quelques modules de ce type et j'ai tenté de les utiliser avec simhub sans succès. Peux-tu stp me confirmer que ce n'est pas compatible avec simhub ?

Merci d'avance,

Bonne journée,

Gege  
![7segment](https://github.com/SHWotever/SimHub/assets/130239001/ac68dbc0-14ec-4fa5-9b7c-80a7e7f6bb3d)

**Comment by SHWotever** [comment]
Bonjour, 

Non cette puce (74HC595) n'est pas supportée.
L'annonce est plutot "malsaine" car elle liste un grand nombre de puces totallement différentes,

Mais si la variante est bien un 74HC595, il n'est pas supporté je suis désolé :
![image](https://github.com/SHWotever/SimHub/assets/2207331/155c072e-26d8-40e8-bf4a-6e88ae1e00fb)

**Comment by gegewrc2** [comment]
Merci pour ton retour rapide ! Dommage, j'aurais du etre plus attentif. J'ai en effet  vu tm1637 et tm1638 ds l'annonce et me suis fait  avoir. ;-) bonne fin de Wend.
