### ISSUE TITLE
Remember application window position and sizing

### ISSUE THREAD

**Issue by nickkudrycz** [SHWotever/SimHub#1381]
Hi,

Using SimHub on a quad monitor setup so that my 4k is screen 1, and my other three screens use NVIDIA's surround spanning to look like a single monitor #2 (7680x1440). The app opens up across monitors 1 & 2 requiring a manual grab and resize every time it opens.

It would be fabulous if it could remember the size and position after closing.
![Untitled](https://github.com/SHWotever/SimHub/assets/47116726/a8930e1d-ca1f-4100-a8c5-ecb4b0e59103)

You guys are great, thanks!

**Comment by SHWotever** [comment]
Hi ! I will check ! I think I know the issue. Since the target screen has probably a scale > 100% windows gets playful and resizes the window once it reaches the screen after simhub has placed and sized it, actually changing completely the final size during its restoration. I will test that !

**Comment by nickkudrycz** [comment]
yes, that could be it. one screen is 150% the other isn't.

**Comment by SHWotever** [comment]
I confirm that was it ;) The good old "place it twice" workaround counters this windows behaviour.
It's fixed for the next version ;)
