### ISSUE TITLE
SimHub freezes 

### ISSUE THREAD

**Issue by npastore28** [SHWotever/SimHub#1382]
**Describe the bug**
Simhub freezes for 1-2 seconds randomly, which affects using my wheel when shifting and performing other button related actions

**Simhub version**
8.4.10

**Third party plugins**
Leoxz Simbridge

**To Reproduce**
unable to reproduce, it happens when driving on the sim, randomly at least once every 30 seconds / 1 minute 
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12263739/SimHub.txt)

**Expected behavior**
I expect the freeze NEVER to happen as it affect sim racing experience

**Comment by SHWotever** [comment]
Hi !

You mentionned Leoxz Simbridge which is a third party plugin, Does it happens when the plugin is uninstalled ?

**Comment by npastore28** [comment]
Hi, Unfortunately I can’t verify this is the plug-in is needed for the wheel to work with simhub. If I remove simbridge the wheel is not recognised Shall I send you a video maybe ? Thanks On 4 Aug 2023, at 20:34, Wotever ***@***.***> wrote:﻿
Hi !
You mentionned Leoxz Simbridge which is a third party plugin, Does it happens when the plugin is uninstalled ?

**Comment by SHWotever** [comment]
Hi ! I get regular reports about this freeze and crashes with this plugin, Please make sure to contact directly the company so they can fix it : [support@leoxz.com](mailto:support@leoxz.com) , unfortunately I can't fix third party plugins on my end.
