### ISSUE TITLE
SIMHUB wont open Stuck on Creating Window

### ISSUE THREAD

**Issue by xmrrushx** [SHWotever/SimHub#1383]
New Windows 10 install ver 22H2 19045.3271 install. Getting everything set up again so i can race in iRacing. Simhub will not load regardless of the version installed. 

Looking at the logs i see a FATAL - System.Windows.Markup.XamlParseException

Not sure what this means and googling hasnt really pinned down where i should look. i've made sure C++ and dot.net are updated and looked to see if the WMI is corrupt. However i just installed a fresh version of window this week after a update failed to install over the last few months. 

**Simhub version**
8.4.10

**Third party plugins**
None - Fresh install

**To Reproduce**
Issue is on execution of simhubwpf.exe

**Expected behavior**
App opens

**Screenshots**

Loading Screen

![image](https://github.com/SHWotever/SimHub/assets/141515732/1f5f073c-ea81-4861-b4d4-8a27cc49c3f4)

Task Bar icon

![image](https://github.com/SHWotever/SimHub/assets/141515732/9700a8f7-9783-4b39-a68c-c1a129e89e0c)

**Log files**
[SimHub.6.txt](https://github.com/SHWotever/SimHub/files/12267769/SimHub.6.txt)

**Additional context**
Add any other context about the problem here

.

**Comment by SHWotever** [comment]
Hi ! From the logs apparently WindowsFormsIntegration.dll is missing, normally this is a dll integrated to the .net framework (4.8 for simhub) 

Can you verify 4.8 is correctly intstalled by launching the installer ? https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer 

If somehow it's already installed that would mean that the 4.8 installation is corrupted, as a last chance, here is a copy of the dll  can you try to put it in the simhub install directory ?
[WindowsFormsIntegration.zip](https://github.com/SHWotever/SimHub/files/12267811/WindowsFormsIntegration.zip)

**Comment by xmrrushx** [comment]
I tried doing a unintall re-install of .net no success

That .dll was not in the directory. Adding it and ensure it was not blocked also has not resolved it

i tried the .net repair tool before and not change as well. Im going to try an SFC. This is the second install of windows i had to do this week on this machine. Im starting to the SSD might be failing

**Comment by xmrrushx** [comment]
something was corrupt in windows. did another fresh os install and it works. thanks for trying
