### ISSUE TITLE
Beamng doesn't work (game disconnected) 

### ISSUE THREAD

**Issue by Skylul** [SHWotever/SimHub#1387]
So, i just got simhub yesterday and today I bought the upgraded version, or the full version and I tried it with truck simulator AND beamng and both did not work. I have been trying it for a while and trying to fix the problem, but it just won't work, I tried using it on my laptop screen and it didn't work (I tried the phone screen first) and nothing seems to work so if anyone has any ideas on how to make it work, please let me know.

**Comment by SHWotever** [comment]
Hi !

You can find a troubleshooting guide for the majority of the game connectivity issues here :https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting

Both games are different technologies:
-beamng uses UDP you need to enable telemetry in the game manually (the game configuration files have been recently changed and simhub can't configure it anymore automatically at this time)

About ats it requires the official steam version, often issues comes from non "official" ones. If you are using the official steam version and it sills does not work please make sure to follow those steps :https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#ets2--ats
