### ISSUE TITLE
iRacing Caddy LMDh shift lights out of sync with game and revs.

### ISSUE THREAD

**Issue by DELTAprime84** [SHWotever/SimHub#1389]
I have a Simcore UD2-J and am using the built-in Sim Hub support. I have noticed in the Cadillac LMDh in iRacing that the shift lights on the DDU reach the redline before the engine reaches the limit and before the in-game shift lights reach the redline. This happens most noticeably on any long straight where I reach 6th or 7th gear such as the Kemmel Straight at Spa.

Version 8.4.8

The only third party plugin I'm using is Lovely Dashboard

1 Drive Cadillac LMDh in iRacing.
2 Drive down a long straight, with the throttle fully depressed, shifting up gears when the in-game shift lights say to shift.

By 6th gear and in 7th gear it is very easy to notice the DDU's shift lights show the redline long before the in-game shift lights reach the optimal shift point.

Here is a video of the issue.
https://1drv.ms/v/s!AvaNaHI_rjtNi5B2vrQ8CISnDcAMgg?e=0HrG0m

[LapLog.txt](https://github.com/SHWotever/SimHub/files/12318456/LapLog.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/12318458/SimHub.1.txt)

**Comment by SHWotever** [comment]
Unfortunately the game does not provide the optimal shift point value, sur it defaults around 90% of max rpm,

You can tune it here per car when required :
![image](https://github.com/SHWotever/SimHub/assets/2207331/d30b3239-0474-4809-93e8-5fc97069f0f1)

Or you have the default setting available here : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/f6a7d43f-a4e3-4eeb-902f-5e4f6b65b948)
