### ISSUE TITLE
[Feature request] information on how to generate ledanimation files

### ISSUE THREAD

**Issue by arthmis** [SHWotever/SimHub#1390]
**Is your feature request related to a problem? Please describe.**
This isn't a problem per say but I was trying to create animations programmatically when I saw that the ledanimations were saved as JSON. After figuring out the format I was able to modify and create an animation that has the effect of breathing, basically led goes from no light to max brightness while retaining 1 color. 

The issue I'm having is having is that I'm not certain how to create the animation from scratch without using simhub to save the animation file. Within the JSON there are `FrameId`s and i'm not sure how to generate them.

**Describe the solution you'd like**
I would like to know information on how simhub generates the `FrameId`, if possible, so that I can build animations from scratch without needing to use simhub to create the actual animation file and doing manual work, like adding enough frames to the file before exporting.

**Describe alternatives you've considered**
The steps I take to create the animation is

1. export an animation with sufficient frames already
2. import that file in some program I created, process the JSON and modify it to create the animation effect
3. overwrite the `ledanimation` file
4. import that file back into simhub

I did try push frames with a blank `FrameId` but that doesn't seem to work.
**Additional context**
This is an example of the JSON format

```JSON
  "Frames": [
    {
      "FrameId": "207b8275-4903-4804-bfc6-2eeddedd4f0e",
      "Colors": {
        "2": {
          "7": {
            "X": 7,
            "Y": 2,
            "Color": "Red"
          },
          "5": {
            "X": 5,
            "Y": 2,
            "Color": "Red"
          },
        },
      },
      "FrameDuration": 100
    }
  ],
```

**Comment by SHWotever** [comment]
Hi !

This is a guid (unique Id) https://learn.microsoft.com/fr-fr/dotnet/api/system.guid.newguid?view=net-7.0

**Comment by arthmis** [comment]
ahhh ok I knew it was a guid but wasn't sure if generating it on my own would be enough. Thank you for the quick response!!
