### ISSUE TITLE
Crash sur dash studio

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1391]
Quelques crash sur le dash studio
Je fais des modifs et, au moment de la sauvegarde, ca plante

Cela se produit rarement mais 2 fois ce matin
[Logs.zip](https://github.com/SHWotever/SimHub/files/12333093/Logs.zip)

**Comment by SHWotever** [comment]
Hello ! J'ai regardé les logs ca ressemble a une fuite de mémoire, une fois la mémoire pleine ca finit par coincer. J'ai essayé de reproduire avec des dash que j'avais en stock mais je n'ai rien vu la mémoire finit toujours pas ètre libérée. Il doit y avoir un "déclencheur" que j'ai loupé 

Est ce que tu pourrais me décrire plus en détail ce que tu as fais avant que ca coince ? Peut ètre aussi avoir une copie des dash en l'état actuel, peut ètre que le "déclencheur" y est caché.

**Comment by herve4545** [comment]
avec ce dash et un replay en cours
le dash est en cours d'exécution :
1) sur mon vocore
2) sur mon écran windows (en wpf render engine)

je fais beaucoup de modifs en ce moment sur ce dash
donc, assez souvent, je fais ctrl+s pour sauvegarder les modifs afin que ca mette à jour le dash sur le vocore et sur mon écran windows

D'après ce que j'ai pu voir...
dès qu'il a eu trop de modifs, ca commence à ramer et ca finit par planter
je ne suis pas très sur....mais si je lance mon dash uniquement sur mon vocore, ca a l'air moins problématique

en copie :
le dash.....assez lourd
le javascript
je gère aussi pas mal d'images dans "....\SimHub\ImageLibrary\Herve45" mais je n'ai pas mis les fichiers concernés

[Z.zip](https://github.com/SHWotever/SimHub/files/12358049/Z.zip)

**Comment by SHWotever** [comment]
Hello ! J'ai releasé une beta, je n'ai pas vu de réelle "fuite" mais si on sauve plusieurs fois ou très souvent sur un dash "lourd" ca faisait monter la ram en flèche car il n'avais pas le temps de tout libérer, j'ai ajouté une purge forcée ça à l'air de bien mieux se comporter, j'espère que c'était bien çà la soucis 🤞

**Comment by herve4545** [comment]
je ferme
je n'ai pas eu de problème sur la b9.0.0b1
A voir à l'usage
