### ISSUE TITLE
Control Mapper support for Toggles

### ISSUE THREAD

**Issue by proosakos** [SHWotever/SimHub#1392]
**Is your feature request related to a problem? Please describe.**: Problem is that with control mapper I can't figure out how to map a toggle in iRacing, for example, ignition as a toggle switch. A click and hold on the helper app results in single press/unpress, so I can't select the toggle and then click enter so that iRacing knows it's a toggle.

**Describe the solution you'd like**
Support for toggle controls.

**Describe alternatives you've considered**
currently just not using control mapper for my toggles, which gets a bit confusing.

**Comment by SHWotever** [comment]
Hi ! Indeed toggle switches are really unnatural in most games and I did not thought about this use case, I made the changes to support "holding" a button for the next version.

**Comment by proosakos** [comment]
Thank you!
