### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by RaceX58** [SHWotever/SimHub#1393]
Hello,

It would be great to have a confirmation dialog after clicking on the "Forget this device" button in the Arduino --> My hardware section.

Several times I wanted to edit the "Custom protocol" field and clicked on the "Forget this device".... As a result I've lost the device and all the information on the custom protocol field.

Thanks in advance,

RaceX

**Comment by SHWotever** [comment]
Hi !

Good idea. I've added it for the next version.

Regards,
