### ISSUE TITLE
[Feature request] Media image on dashboard

### ISSUE THREAD

**Issue by arthurferrai** [SHWotever/SimHub#1398]
Since dashboard already has options to show music artist and music name, it would be nice to be able to also show album art image from media info as a dashboard widget.

**Comment by SHWotever** [comment]
Hi !
This already exists ;)

![image](https://github.com/SHWotever/SimHub/assets/2207331/e2e15218-0539-491f-9b23-9907e3ad5796)

Warning the picture quality (relsolution)  depends of how the player sends it, there is no control about at simhub level.
