### ISSUE TITLE
error 10035

### ISSUE THREAD

**Issue by thedude999** [SHWotever/SimHub#1401]
**Describe the bug**
game crashes 10035 error in dirt3 and dirt rally. all other non codemasters games are ok

**Simhub version**
9.0.1

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**
game crashes 10035 error
**Screenshots**
![10035](https://github.com/SHWotever/SimHub/assets/19838278/b9b9cb21-9342-4df3-94b3-1e02ccb3828a)
![config1](https://github.com/SHWotever/SimHub/assets/19838278/a88dbfcf-550b-42ee-a73e-5d3eadd8fcf8)
![config2](https://github.com/SHWotever/SimHub/assets/19838278/fa2fb086-86c0-48c6-8e98-7ad6624affa2)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/12513204/SimHub.2.txt)

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
hi this is a big of dirt3 itself, this is not related to simhub ;)

You can find an utility i've built to workaround this game issue here (see permanent workaround) :
https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#dirt-3
