### ISSUE TITLE
No monitors available when attempting to select targeted screen in Dashboard starting with version 9.0.1

### ISSUE THREAD

**Issue by SteveSobka** [SHWotever/SimHub#1402]
**Describe the bug**
Since upgrading to 9.0.1 I can no longer launch any of my Dashboards as my "Targeted Screen" show no monitors available.
I have two monitors (1 Nvidia Surround and 1 regular).  Windows sees them fine and I was able to select Monitor #1 prior to SimHub 9.0.1
I also tried going into DEVICES to create a generic monitor but that window is blank when I try to choose a monitor as well.

**Simhub version**
9.0.1

**Third party plugins**
All 3rd party plugins disabled and issue persists.

**To Reproduce**
1. Go to 'Devices'
2. Click on '+ Add new device'
3. Scroll down and select 'Generic Monitor (HDMI, DP ...)'
4. Click OK to add.
5. Under 'Startup Location > Target monitor' select button 'Click to define target monitor'.
6. When you see 'Choose target screen' there will be no monitors to select from and the OK button is grayed out.

**Expected behavior**
I would expect to see two monitors as I did in previous versions of SimHub Dash when I chose a specific monitor when launching a dashboard.

**Screenshots**
Screenshots included

**Log files**
Log Files attached.

**Additional context**
Worked fine before version 9.x
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12516872/SimHub.txt)

**Comment by SteveSobka** [comment]
**Screenshot of Windows showing my monitors:**
![image](https://github.com/SHWotever/SimHub/assets/64034696/93429472-cf05-4c26-abd2-4ed930afcf74)

**SimHub showing NO monitors:**
![image](https://github.com/SHWotever/SimHub/assets/64034696/763222d6-4b32-490c-8fae-769186926378)

**Comment by greennyreborn** [comment]
> Hi ! Monitor identification went much more complex than before and maybe a side case escaped me. Unfortunately at this point I have very low infos using the logs, I've built a beta version with more details : Can you try it and grab the logs as you did before ? I don't expect it to solve the issue, But hopefully it will give more insights : https://www.simhubdash.com/unofficial/SimHub.9.00.2b1.zip

I have the same setup and encounter the same problem, I will use this beta version and grab some logs

**Comment by SHWotever** [comment]
@greennyreborn If you can grab the logs that would be amazing, I really want to fix that one, advanced monitor data reading is really the pillar of accurate and "repeatable" monitor identification, any blind workarounds would just kill all the progresses made on this subject.

**Comment by SHWotever** [comment]
I hope to release a small hotfix today, I've included even more logs and code splitting on this subject, 
If you have a chance to grab the 8.0.2 version if it's already released to do that test that would help.

**Comment by greennyreborn** [comment]
> 

8.0.2 version? Do you mean 9.0.2?
I'd love to help

**Comment by SHWotever** [comment]
9.0.2 indeed, not released yet :D, my bad, I get lost for a few weeks every time I change the major version :D

**Comment by greennyreborn** [comment]
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12574962/SimHub.txt)

using 9.0.2b1 version

**Comment by SHWotever** [comment]
thanks a lot ! That seriously reduces the search scope !

**Comment by SHWotever** [comment]
I published the update,  https://www.simhubdash.com/download-2/ I added more logs and errors handling, at best it will avoid the issue, at worse it will give more insights about what is causing it.

Let me know ! If you have some fresh logs, even if it doesn't crash i'm interrested ;)

**Comment by greennyreborn** [comment]
> 

Sure, I'll be at my rigs in three hours

**Comment by greennyreborn** [comment]
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12577491/SimHub.txt)
It works like a charm!
Much appreciate

> I published the update, https://www.simhubdash.com/download-2/ I added more logs and errors handling, at best it will avoid the issue, at worse it will give more insights about what is causing it.
> 
> Let me know ! If you have some fresh logs, even if it doesn't crash i'm interrested ;)

**Comment by SHWotever** [comment]
Thanks ! I see no traces of anomaly, so my best guess is that on of  those screens had no serial number informations or edid (the monitor "signature" allowing to know the "physical model" and characteristics.)

Thanks for your log and feedback! Hopefully it has been fixed straight away thanks to your previous log.

Nicolas
