### ISSUE TITLE
SimHub - freeze - F1 23

### ISSUE THREAD

**Issue by Oli0055** [SHWotever/SimHub#1403]
I'm a French Canadian, so I'm sorry if this message is not perfect. I made my absolute best. 

**Describe the bug**
I'm in the F1 23 game, and Simhub is freezing every 2-3 minutes. 

**Simhub version**
Right now, I have 8.4.8, but even with the last version, the result is the same (9.00.1)

**Third party plugins**
I got 2 plugins 
F1 Tv : https://www.racedepartment.com/downloads/f1tv-tv-style-hud.61462/
Gary Swallow : https://www.racedepartment.com/downloads/simhub-tv-style-side-scrolling-leaderboards-timings-sidescreen.18746/

**To Reproduce**
I don't understand this part

To get the bug, I open SimHub, go to ''Dash Studio'' in SimHub, and load the ''new overlay layout'' I created with the plug-in overlays mentioned in this message. So all goes well, I'm in the F1 23 game in spectator mode, and at one point, all my overlays freeze. From then on, the SimHub software is completely frozen.

**Expected behavior**
If someone may find the problem. I've asked around in several discords, I've looked at the codes and I can't find anything on google. I am quite discouraged. I broadcast F1 races. So it's quite important for me to find the origin of the problem.

**Screenshots**
I have a link of my last night stream. At 9 min, 26 sec, my overlay is freezing. You can see it with the white line next to the #11 in the standing.  
https://www.twitch.tv/videos/1917377809

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12518248/SimHub.txt)

[SimHub.txt](https://github.com/SHWotever/SimHub/files/12518325/SimHub.txt)

**Additional context**
So, I'm in a session in the f1 23 game, and I'm using simhub to bring in new visuals and interesting data. So I'm using overlays. Overlays freeze far too often. Each time, I have to close simhub completely as I can't get back to the software. The log I've left you is the one when I reopen Simhub directly after having had the software freeze. 

I really appreciate your help. Sincerely, thank you for your help.

**Comment by Oli0055** [comment]
My pc is not overheating at all. I got a brand new and he's really powerfull

**Comment by SHWotever** [comment]
Hi ! Can you try to disable the third party plugins (Gary swallow plugin) to check if it still freezes ? The log you sent does not shows the actual freeze, but I know this plugin often cause issues. Since it's a third party one, unfortunately I can't fix it on my end, in such case you need to report it to the author.

**Comment by Oli0055** [comment]
It's seems that Simhub don't freeze yet. So if it's the case, it's the Gary Swallow Plugin who's making damage. Did you have in the past something similar with this plugin that can help me? 

If it's not, I should go to the author to report the bug. 

And Finally, you didn't find any information relevant to the log I sent you?

A Big Thanks again

**Comment by SHWotever** [comment]
Unfortunately I have no clues about what triggers the freeze in the plugin as I don't have the code. 
From the previous reports I've seen in the past catching the actual moment where it was freezing, it was not showing a deep execution stack allowing to spot at least the subject of the freeze so I can't make even a rough guess of what triggers it (and if a workaround is possible) I'm sorry.

**Comment by Oli0055** [comment]
allright, thank you for your help. Really appreciate :)

**Comment by SHWotever** [comment]
No problems ;)
