### ISSUE TITLE
[Feature Request] Overtake System Properties

### ISSUE THREAD

**Issue by selectyoungs** [SHWotever/SimHub#1404]
iRacing just released a super formula that has an overtake system that isnt on the available properties list, only thing that works is the push2pass true/false but since the overtake system is toggle on/off this push2pass isnt fully correct and isnt all the needed info. The super formula has 3 overtake readings that would be really helpful, 1st is Overtake remaining (in seconds), 2nd is overtake status (on/off/retime), 3rd is Overtake retime (time overtake is unavailable for after use). Im not sure what other cars or games use overtake systems but this would be a great property to see added.

**Comment by SHWotever** [comment]
Hi ! Unfortunatly I've never seen such data in the telemetry I'm sorry.

**Comment by alexdoro23** [comment]
I am looking for this functionality as well, it will be very important.  Maybe through iracing properties .dll

**Comment by SHWotever** [comment]
Just to reiter ;) If somehow the data gets added to telemetry it won't require any actions on simhub side and will appear automatically in the raw data (that's the worse aspect of iracing : moderately normalized data across cars, and the best feature at the same time : if somehow a data get added it will appear automatically in Simhub.
