### ISSUE TITLE
vocore error

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1405]
Depuis plusieurs jours, j'ai des erreurs dans la log concernant mon vocore

de temps à autre, je subis des déconnexions sur mon vocore. Je le débranche et je le rebranche et le problème est résolu
cela se produit pendant une course sur rf2

mon ecran vocore perd la connexion et je ne sais pas si c'est à cause
de simhub
de mon vocore
[SimHub.1.txt.zip](https://github.com/SHWotever/SimHub/files/12565808/SimHub.1.txt.zip)

de mon système
[SimHub.16.txt.zip](https://github.com/SHWotever/SimHub/files/12565795/SimHub.16.txt.zip)

ne pas tenir compte des erreur du plugin gary swallow....je le teste mais il renvoie trop d'erreurs

**Comment by SHWotever** [comment]
Hello !

J'ai vérifié les logs je vois bien que l'écran à "crashé" à 14:18:06,762, a cet endroit ce type de déconnection est "matérielle" : USB, ,hub, cable, EMI, manque de puissance sur l'usb. La réponse n'est pas universelle, il faut fouiller ;(

**Comment by herve4545** [comment]
ok. je ferme. je vais bientot reformater mon système. je verrai si cela produit un effet
