### ISSUE TITLE
plantage simhub

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1406]
assez souvent, j'ai des plantages de simhub

le cas de test :
J'ai un replay en cours et 2 ou 3 dash en cours également
au bout d'un moment, simhub plante
[SimHub.zip](https://github.com/SHWotever/SimHub/files/12565926/SimHub.zip)

**Comment by SHWotever** [comment]
Hello ! Visiblement il y a une fuite de mémoire. 
Est ce que tu aurais plus de précisions si un une fonction ncalc/js, un type de composant la provoque ? Malheureusement il me faut une première piste pour pouvoir le reproduire, mais de ce que je sais tes dashs sont un concentré de tout ce qui peut se faire :D, du coup difficile d'avoir un point de départ.

**Comment by SHWotever** [comment]
Visiblement il a fallu moins de 10 minutes, il doit y avoir quelque chose de "gros", peut être les images ?

**Comment by herve4545** [comment]
oui j'ai des images : les logos des voitures et les classes des voitures
le leaderboard affiche 25 concurrents ; donc, 25 images pour les logos et pour les classes des voitures
et le gros du code dans un fichier externe JS
j'ai pas l'impression que ce soit un ncalc/js qui pose problème mais le fait des faire des modifs et de les tester avec un replay
au bout d'un moment, ca rame et ca finit par planter
je fais une modif, je sauvegarde le dash et le dash en cours en html render se met  jour en temps réel.
le même replay est toujours en cours

en pièce jointe, mon leaderbard
https://drive.google.com/file/d/1CWoBmMVBhO98zRFO4BF4cMxskqUx7CN7/view?usp=drive_link

**Comment by SHWotever** [comment]
Hello ! J'ai pas mal regardé, je n'ai pas vu de fuite en tant que telle, mais le nombre très important de formules javascript était très consommateur en mémoire, si on rechargeait un peu trop souvent il n'y avait pas le temps de "purger" ce qui n'était plus utilisé et ca gonflait de manière dramatique. J'ai mis en place une "mutualisation" des formules js qui sont les mêmes (typiques des répétitions sur les leaderboards)  J'ai publié çà dans la dernière version. En bonus ca charge plus vite ;)

**Comment by herve4545** [comment]
Merci
Je vais regarder tout ca

**Comment by herve4545** [comment]
super 9.0.2
le chargement est très très rapide :)
