### ISSUE TITLE
Opponent Gap Quick Component Issues

### ISSUE THREAD

**Issue by john-ezra** [SHWotever/SimHub#1407]
**Describe the bug**
The opponent gap component does not work when the Gap Mode is set to To Leader, and the Leaderboard Mode is set to Player Class Only.

**Simhub version**
9.0.1

**Third party plugins**
No plugins used.

**To Reproduce**
1. Go to 'Dash Studio'
2. Click on 'Quick Components -> Leaderboard -> Opponent Gap'
3. Scroll down to 'Leaderboard, set Gap Mode to From Leader, and Leaderboard Mode to Player Class Only'

![Screenshot 2023-09-10 231814](https://github.com/SHWotever/SimHub/assets/47311764/1ea961a4-10cb-446a-ae00-d0bf5391c219)

**Comment by SHWotever** [comment]
Hi ! 

Thanks! I think I got it, when the overall leader is from the same class the "per class" computation was failing. I've fixed it for the next version.

Nicolas
