### ISSUE TITLE
Cycle through favorites dash not working 9.0.2

### ISSUE THREAD

**Issue by alexdoro23** [SHWotever/SimHub#1408]
The "cycle only through favorites dash" function stopped working once Ive updated from 8.4.11 to 9.0.2

**Comment by SHWotever** [comment]
Hi !

You now have full control of cycling per device/display, the global settings is only used for quick run (I will relabel it to get it clear)

You can control every device/monitor behaviour here :
![image](https://github.com/SHWotever/SimHub/assets/2207331/1ccff10d-b7c7-45eb-865d-189406f6cd88)
