### ISSUE TITLE
[BUG?] Font-Caching /_SHFonts behaviour

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1409]
Hi! 

Since I had the issue with transparent Icons and Background color (https://discord.com/channels/299259397060689920/1114448291325816882/1147455631280832572)

I thought it might be a good idea to pack all icons in an icon font, so the icons are more flexibel to use in size and color.
This worked just fine until I updaed the icon font with more icons. It seems like the dashboards for devices have a caching issue.

If I start the dashboard in windowed mode, the new icons appear just fine (also in dashboard editor) but if I start the dashboard on the actual device it's missing the updated icons and shows the plain text letters. At the same time it shows Icons from the previous version of the font fine though. so it's not missing icons in general.

I already deleted windows font cache and reinstalled the font but there must be another caching for the devices going on. Maybe it's the html render engine? Can we delete or reset it somehow? 

Also I'd like to know the behaviour of _shfonts in dashboard. From my understanding all fonts in that folder wereloaded automatically but it did not with the icon font on another machine. How does it work?

Cheers

**Comment by SHWotever** [comment]
Hi ! The devices uses a browser with an underlying cache, while simhub scans for new fonts etc, it would be a little too consuming to inspect every fonts for changes you can clear the browsers cache (webview for desktop HTML and cefsharp for devices by deleting the content of %localappdata%\SimHub) typically fonts very rarely gets updated :D

_shfonts tries to collect any non windows standard fonts, as long as it's TTF (woff and other special formats are not parsed or collected). fonts are listed from c:\windows\fonts and %localappdata%\Microsoft\Windows\Fonts
Warning fonts must have correct metadata, it's easy to create bad fonts with bad metadata, dafonts or others websites are full of these "approximate fonts" . The fonts are only collected once by file name, if the same font file already exists in the _shfonts folder it won't tries to updated it

When installing the dash on another computer if the font is not available on the remote computer (font name) it will get copied into C:\Program Files (x86)\SimHub\DashFonts and taken in priority as much as possible (but WPF or the browser can shortcut it if It finds a similarly named font available on the system). Hard to have full control on windows fonts :D

**Comment by FullPace** [comment]
Thanks that helped. 👍 

I know how hard windows font control is. We struggle with it for years, even with font managing software.
The fonts folder is totally mislocated in the system files. It only causes trouble with user rights...
