### ISSUE TITLE
9.0.2 - Out of memory error

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1410]
**Describe the bug**
Hi,
I'm catching up with the v9 update. It's really sweet!
Thanks for your hard work!

**Simhub version**
9.0.2

**Third party plugins**
Admittedly I still had all my plugins running. Hopefully they're not the source of the issue.

**To Reproduce**
While working on my big iRacing leaderboard while running a data replay I've had a memory leak issue.
I had the replay running and kept tweaking an Fx using repeatindex and saving tyhe dash often to refresh it

**Screenshots**
![image](https://github.com/SHWotever/SimHub/assets/50543913/f9f85002-dd1b-49e1-b733-67fce602df4f)

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12583426/SimHub.txt)

Have a nice day!

**Comment by Romainrob** [comment]
Actually simply starting SimHub with a dash on an android tablet en my iRacing layout on auto, both the cpu and ram usage are slowly creeping up.
![image](https://github.com/SHWotever/SimHub/assets/50543913/7482df4e-8f3b-478a-b8bf-0d54ae251e1c)

**Comment by SHWotever** [comment]
Hello ! Can you give me more details about that "simple" situation ? 
Unfortunately memory leaks are really hard to catch unless I can reproduce it consistently and I really need to reproduce the conditions. I worked on memory leaks this weekend and I could not find any yet (except latest js engine library being more memory hungry than before which led to optimisations. If I can reproduce the conditions that would help massively ;)

**Comment by Romainrob** [comment]
Ok, false alarm.
It seems one of my plugins acting up.
The weird thing is I've not changed in 6 months.

I've narrowed it down to this bit running formulas:

           SimHub.Plugins.OutputPlugins.Dash.TemplatingCommon.IFormulaEngine NcalcEngineBase = new SimHub.Plugins.OutputPlugins.Dash.TemplatingCommon.NCalcEngineBase();
            result1 = NcalcEngineBase.ParseValueOrDefault(Settings.Formula1, "");
            result2 = NcalcEngineBase.ParseValueOrDefault(Settings.Formula2, "");
            result3 = NcalcEngineBase.ParseValueOrDefault(Settings.Formula3, "");
            result4 = NcalcEngineBase.ParseValueOrDefault(Settings.Formula4, "");

**Comment by SHWotever** [comment]
Hum ! keep a copy of the ncalc NcalcEngineBase aside (class instance) and don't instantiate it everytime ;) the engine now includes some caching, that saves memory and computation but does also consumes a lot of you instantiate the NcalcEngineBase every time. overall even on the past versions this little changes would have been really beneficial :)

**Comment by Romainrob** [comment]
I see. That fixed it indeed.
I'll have to update some other plugins running formulas in some cases.
Sorry for the false alarm and thanks for you help.

**Comment by SHWotever** [comment]
No problems ;)
