### ISSUE TITLE
How can we use a button to mute the sound ?

### ISSUE THREAD

**Issue by Basiliadis** [SHWotever/SimHub#1412]
Hello ,

how can we use a button to mute the sounds when press it? I try the mute sound  from the keyboard but SimHUB does not recognize this button.

Thank you very much.

**Comment by SHWotever** [comment]
Hi ! 
Which kind of "sounds" ? 

Nicolas

**Comment by SHWotever** [comment]
If you are using the bass shakers it indeed won't reply to typical keyboard mute button as it's intended to be running on a secondary sound card not controlled by your keyboard (and to avoid any "mute issues" it will control and set it to the intended gain you configured inside simhub).
To get control over shakeit, you can assign controls here : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/f1d1b42f-a9c5-4cec-b346-3f00ddacfc88)

The "keyboard input" plugin is disabled out of box, you can enable it in the settings if you want to map a keyboard shortcut to it.

**Comment by Basiliadis** [comment]
thank you for fast reply. i just want to mute the the active sound card that i use for speakers or headset.I try to use mute button from my Logitech G19 keyboard  that i assign on a button that i create on my SimHUB dash but not work.

**Comment by SHWotever** [comment]
Oh ok ;) currently it's not available and the keyboard emulation is low level allowing to control games more universally, but as a downside windows will just ignore most of the special keys like "mute" etc.

At this time you have those two actions to control the volume (up and down)
![image](https://github.com/SHWotever/SimHub/assets/2207331/38b67cc0-1547-472f-bc1f-4eda858a8154)
