### ISSUE TITLE
[Feature request] - Ignoring pace laps for Avg fuel / Lap computation - iRacing oval

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1413]
Hi,
Would it please be possible to have DataCorePlugin.Computed.Fuel_LitersPerLap ignore pace laps during iRacing oval races?

I think the simplest way would be to ignore the lap whenever one of these flags is out:
- DataCorePlugin.GameRawData.Telemetry.SessionFlagsDetails.IscautionWaving (slowing down)
- DataCorePlugin.GameRawData.Telemetry.SessionFlagsDetails.Iscaution (under pace car)

These don't seems to be used during road events as they use the yellow flags instead.
Thanks in advance for considering the idea.

**Comment by RangeyRover** [comment]
I think this is relevant to the issue, I'm looking at a similar problem, but with average lap where some values should get discarded (first lap, pit laps, yellows, off tracks, incidents) but it's difficult to write for every scenario.

My solution is looking like its going to be the median of the laps. I think this would work tolerably well for oval racing, unless you've spent all the race under the safety car, in which case you've probably got too much fuel anyway.

I've done quite a bit of work on this for my own fuel calculator, mine tracks the leaders time to go which is converted to laps to go (using gary swallow plugin) based on leaders average lap time then calculates how far behind the racer is to the leader and adds that time on to get to the racers time to finish.

In the data sets I'm using to test from our races there is a significant difference in the mean to the median.

Example here from P1 Race with wet start and 2 pit stops, there is a 4 second lap difference mean to median. You can see that the leader is very close to median times at the end.
https://www.calculator.net/mean-median-mode-range-calculator.html?numberinputs=181.015%2C92.502%2C92.017%2C91.523%2C91.989%2C91.618%2C94.517%2C91.063%2C94.575%2C89.875%2C90.149%2C89.828%2C89.695%2C89.005%2C99.115%2C127.185%2C82.033%2C82.021%2C82.923%2C82.046%2C81.641%2C82.621%2C81.638%2C81.381%2C81.867%2C82.096%2C81.558%2C81.947%2C81.536%2C81.681%2C81.398%2C81.945%2C82.942%2C82.504%2C82.087%2C81.399%2C81.487%2C81.582%2C81.993%2C81.302%2C81.321%2C81.805%2C81.556%2C81.553%2C81.535%2C81.395%2C81.443%2C81.521%2C81.258%2C81.937%2C81.398%2C81.779%2C81.332%2C91.911%2C104.302%2C81.982%2C82.022%2C81.697%2C82.067%2C81.854%2C82.123%2C84.681%2C82.719&x=32&y=27

<img width="578" alt="Capture" src="https://github.com/SHWotever/SimHub/assets/48373653/992b6b99-a06e-458d-b7e7-35d792358c1e">

**Comment by teknologika** [comment]
https://github.com/SHWotever/SimHub/issues/1371

**Comment by SHWotever** [comment]
@teknologika Thanks for the notification it's indeed a duplicate.
