### ISSUE TITLE
WebView2 rendering bug

### ISSUE THREAD

**Issue by qh0814** [SHWotever/SimHub#1415]
**Describe the bug**
Border radius cannot be rendered correctly in WebView2

**Simhub version**
9.0.3

**Third party plugins**
none

**To Reproduce**
1.Use JavaScript code in the Binding editor
```
var lap = $prop('CurrentLap')
if(lap < 2){return 30}
else{return 0}
```
2.Using WebView2,border radius after the first lap still appears as 30
<img width="1065" alt="Snipaste_2023-09-15_14-36-27" src="https://github.com/SHWotever/SimHub/assets/36350623/6d01807e-ef2c-476b-a006-548c15c7d456">
3.Using WPF render engine,border radius will be rendered correctly
<img width="949" alt="Snipaste_2023-09-15_15-05-38" src="https://github.com/SHWotever/SimHub/assets/36350623/36909833-e5ee-4f95-b7c4-64848045ebdd">

**Expected behavior**
 border radius can be rendered correctly in WebView2
**Screenshots**

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12616675/SimHub.txt)

**Additional context**
Most of my dashboards use emoji, only WebView2 renders them correctly

**Comment by SHWotever** [comment]
Hi ! Thanks the the report it's fixed for the next version.

The complete issue was when it was dynamically switching from "anything" to 0, the "0" radius was not applying correctly.

Nicolas
