### ISSUE TITLE
Hi what a great job you do!! THANKS. Can you do in the track map colorized cars? know the are all white.. different color categories will help[Feature request]

### ISSUE THREAD

**Issue by briancito22** [SHWotever/SimHub#1417]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Thanks for your feedback and suggestion  !
I close it as it's a duplicate of this one : https://github.com/SHWotever/SimHub/issues/743

Nicolas
