### ISSUE TITLE
Ahead_xx_gap to payer 

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1420]
Hello
Je ne sais pas si c'est vraiment une anomalie mais le comportement est bizarre
Lorsque j'arrive assez près de la ligne de chronométrage, je vois que certain ahead_xx voient leur lap_to_player passer à 1 pendant a peine une seconde pour repasser a 0
Cela ne se produit pas systématiquement et pas pour les 5 ahead
Quand cela se produit, c'est toujours pour uniquement quelques ahead_xx parmi les 5 ahead

En résumé, à l'approche de la ligne de chronométrage, certains ia qui sont devant moi ont leur lap_to_player passer à 1 pendant une seconde avant de repasser a 0

Effectivement, lorsque les ia ahead passent la ligne de chronométrage, elles ont, a cet instant T, un tour d'avance mais (lap_to_player a 1) ne se produit pas a chaque tour et pas pour toutes les ia ahead

**Comment by SHWotever** [comment]
Hello ! Malheureusement parfois le jeu repasse la	progression sur le tour en cours à 0 quelques pouillèmes avant d'incrémenter la tour ou le contraire :

Par exemple 
- à l'instant t : Tour 0, position 90% du tour => 0.9tours
- à l'instant t +1 : Tour 1, position 90% du tour => 1.9 tours : Et là on ne peut plus savoir ou on en est :( c'est ta version du "glitch")
- à l'instant t +2 : Tour 1, position 5% du tour => 1.05 tours : Et là on retrouve enfin nos petits)

Parfois le contraire : 
- à l'instant t : Tour 0, position 90% du tour => 0.9tours
- à l'instant t +1 : Tour 0, position 1% du tour =>  0.1tours : Et là on ne peut plus savoir ou on en est :( c'est la version contraire du "glitch")
- à l'instant t +2 : Tour 1, position 5% du tour =>  1.1tours  : Et là on retrouve enfin nos petits)

Malheureusement à cet instant "T+1" dans les deux cas la donnée devient incohérente et c'est très difficile de l'éviter :( , je vais regarder quand même mais c'est un vrai casse tête.

RF2 j'imagine ? Chaque jeu est subtilement différent en la matière

**Comment by herve4545** [comment]
oui rf2 pardon

**Comment by SHWotever** [comment]
Hello ! Je cloture çà, j'ai ajouté une bonne dose de "contre mesures" dans les dernières betas pour ces données anormales provenant des jeux (RF2 n'est pas le seul dans ce cas pour le coup)
