### ISSUE TITLE
Haptic motor on throttle remains muted

### ISSUE THREAD

**Issue by Zsozsa** [SHWotever/SimHub#1421]
The haptic reactor on throttle remains muted during test in Simhub and in game, too. While haptic on the break pedal works perfect. My motor is working nice using Sim Pro Manager. I shut off Sim Pro Manager so that the programs don't collide but in vain. 

9.0.4.
Make sure to run the latest version

I disabled Sim Pro Manager. 
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

I reproducet it severar times restarting Simhub.

The haptic reactor should work on throttle, too. 

when I push on test now under "throttle". It seems on the screen that a signal was sent to the motor but that remains muted.

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Are you using a reverse version of the pedals maybe ? I didn't had the chance to test this model, in such case it would react to clutch instead of throttle.

Could you also join the log files as requested in the big report template?

**Comment by Zsozsa** [comment]
Yes, I use an inverted pedal. Sorry for not mentioning it. (I never thought it means difference.. :S ). 

I've found the logs. Wasn't difficult but I'm not yet too experienced at reporting. :)
Thank you for your work! SimHub is a fantastic program!

[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/12706231/SimHub.3.txt)
[SimHub.4.txt](https://github.com/SHWotever/SimHub/files/12706232/SimHub.4.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/12706233/SimHub.1.txt)
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/12706234/SimHub.2.txt)

**Comment by SHWotever** [comment]
I tried on my pedals and when switching on inverted the motors won't work except brake indeed, I will ask to simagic if there is a trick or a fix to the firmware to be done. In the wait disabling "inverted" in sim pro could do the trick

**Comment by Zsozsa** [comment]
Thank you very much! I give it a try! :)

**Comment by Zsozsa** [comment]
I've tried the trick. But in this case my throttle haptic remains muted even from SimHub, too. But I use inverted pedal set "natively", it can be the difference to you case.

**Comment by SHWotever** [comment]
When disabling "inverted" I guess it should react through the "clutch" (as I guess it's what the "inverted" setting does, swap clutch and throttle.) Have you tried the clutch ? 

If it doesn't work, I sent a message to simagic, I will have to wait for an answer(it's already late in the day in China and I'm not sure they look at it during the weekend)

**Comment by Zsozsa** [comment]
You are right! it works perfect with cluth! (standard pedal option) :) In Sim Pro and even in SimHub! Thank you for the workaround! I'm really happy now!

**Comment by SHWotever** [comment]
Hello ! Just a little followup : the bug has been confirmed on simagic side, I had a chance to test the incoming firmware update and I can confirm it worked perfectly in "reversed" mode.

I close this as there is nothing to be done on the Simhub side ;)
