### ISSUE TITLE
GSI Formula Pro Elite LED failure induced by idle behavior power off

### ISSUE THREAD

**Issue by kwilliams81** [SHWotever/SimHub#1422]
**Describe the bug**
As the title states I have a GSI Fomrula Pro Elite (current version with VoCore Screen) added to devices with the Idle Behavior for the LCD set to power off when game not running. When I start iracing the LED's for this wheel show not connected and if I toggle the device connected slider from green to grey to green the LED's connect and function as normal.

**Simhub version**
9.0.4

**Third party plugins**
Yeop_de_LEDLights_Larp_Package_20230917.2 

**To Reproduce**
1 -- Have a GSI Wheel base and set the idle behavior to power off.
2 -- Run an initial race in iracing and LED's should function.
3 -- Quit iracing or exit race
4 -- Start iracing again or choose another race/practice/test track and LED's will not fire and show partial connected

**Expected behavior**
LCD and LED's should run as expected when in iracing. Currently only the LCD runs as expected until I manually toggle the device in simhub then it re-enableds the LED's.

**Screenshots**
NA

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
Will test without Yeop_De_LEDLights dashboard to confirm similar behavior with LED's

[simhub.zip](https://github.com/SHWotever/SimHub/files/12707815/simhub.zip)

**Comment by SHWotever** [comment]
Hi ! Could you try without the external plugins first ? I'm not sure it will solve it, but that would unbloat the log files , currently there are way too many errors triggered by your third plugins to be able to "unroll" what is happening.
PS : Do not forget to include the "simhub.txr" file( it's the most recent one, next files .1.txt .2.txt ... are from older sessions)

Can you tell also when the leds get disconnected exactly ? The "idle" behavior from the screen is only related to the screen, the leds are unaffected. It means somehow the leds connection gets "physically" lost at a time and can't be reacquired automatically (which simhub does when it detects physical devices list changes).

**Comment by kwilliams81** [comment]
Actually hold on any work on this. I'm unable to reproduce it with these steps and at the moment I've been unsuccessful in reproducing this at all. What I did perform was changing the dashboard to the GSI default dashboard and then changing it back to Yeop and I'm unable to reproduce the issue. I'll close in 24 hours if I'm unable to reproduce.

**Comment by kwilliams81** [comment]
I'm not sure what happened but I'm unable to reproduce this behavior and everything is functioning as expected. I will close this out.
