### ISSUE TITLE
Different button in SimHub vs Windows

### ISSUE THREAD

**Issue by alehop69** [SHWotever/SimHub#1425]
**Describe the bug**
I´m using a Simucube Archer Wireless wheel plate, and if I push, for example, the button 3 of the plate, Windows recognises it as Button 3, but Simucube recognises it as Button 4. So the plate buttons don´t match in Simhub and in Windows... 

**Simhub version**
9.0.1

**Comment by SHWotever** [comment]
Hi !

It's just a matter of starting convention, windows starts from button "1", simhub from "0", many games also starts from "0" and won't match what windows shows, but overall no matter if it's shown "0" or "1" it will point to the same physical button, it's just a visual difference.

Best regards,
Nicolas
