### ISSUE TITLE
SimHub unable to pull any game data since CSGO updated to CS2.

### ISSUE THREAD

**Issue by OMDolton84** [SHWotever/SimHub#1426]
**Describe the bug**
Since the update to Counter Strike 2, SimHub has been unable to pull any telemetry from the game whatsoever.

**Simhub version**
9.0.4

**Third party plugins**
None.

**To Reproduce**
1. Open CS2
2. Attempt to run any display that worked with CSGO
3. Note complete lack of functionality

**Expected behavior**
Telemetry from the game to output and display normally.

**Additional context**
Back before the update to CS2, when the game was CSGO, telemetry output occurred as normal and data could be pulled from the game like with any other game supported by SimHub. However, something appears to have been changed during the update to CS2, meaning the original telemetry no longer functions as expected.

**Comment by SHWotever** [comment]
Hi !

Indeed the game have been slightly modified (values, config files), I did update it, I will release the fix tomorrow I hope.

**Comment by OMDolton84** [comment]
Will these values automatically update in any existing displays, or will I need to convert them over manually?

**Comment by SHWotever** [comment]
The new values are more about a few side cases like first game training etc ... it's undocumented yet so I tried to cover them as best as I could and make simhub more resilient to any lacks about it.
