### ISSUE TITLE
Restart race et pitcount >0 et pittime >0

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1428]
Hello

Cela s'est produit sur rf2 mais je pense que le problème est présent sur tous les jeux

Le cas :
J'ai fait restart race après avoir parcouru une dizaine de tours
Sur cette dizaine de tours, des IA avaient effectué un arrêt aux stands

Après le restart race, les données pitcount et pittime n'étaient pas réinitialisées à 0
Les IA ayant donc effectué un arrêt aux stands avant le restart avaient donc leur pitcount  à 1 et leur pitime à la valeur de leur arrêt

**Comment by SHWotever** [comment]
Hello ! J'ai glissé la correction dans la dernière beta ;)

**Comment by herve4545** [comment]
Oui vu.merci
