### ISSUE TITLE
file issue

### ISSUE THREAD

**Issue by driversean420** [SHWotever/SimHub#1429]
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Comment by SHWotever** [comment]
Hi ! Unfortunately your ticket was empty, do not hesitate to edit it to provide any significant informations so I can reopen it.
