### ISSUE TITLE
Screen Activation Functions Do Not Work Within Widgets

### ISSUE THREAD

**Issue by john-ezra** [SHWotever/SimHub#1430]
There is not a ton to explain for this one outside of what the title states.  When setting a function for screen activation within a widget, there is no change whether the function returns true or false.

To replicate the issue, create a widget with multiple screens, set the activation function for one of them to `return false`, even with this the screen will still be active.

**Comment by SHWotever** [comment]
Hi !

Can you check that EnableScreenRolesAndActivation is enabled on the widget instance ? This is somethig I fixed months ago, but to avoid suddenly changing the whole behaviours of all existing dashs it's disabled (unless you create a fresh widget instance then it's enabled out of the box)
