### ISSUE TITLE
'Load impact' is not working on Forza Horizon 5

### ISSUE THREAD

**Issue by MuKwang** [SHWotever/SimHub#1431]
'Load impact' is not working on Forza Horizon 5 after updating to 9.1.1. (Shakeit Motors) 

I can see the graph, but the motor doesn't work.

It works in other games.

**Comment by SHWotever** [comment]
Hi !

At this time there is no "load impact" effects out of the box in Simhub, could you give a scr

In all cases no matter the effect, if you see activity in the graphs that means that the effect is working. Depending of your profile "output settings" can be embedded inside the profile, can you check that your effect is properly configured on an output ?

If that does not help could you fill the issue template so I can investigate further ? https://github.com/SHWotever/SimHub/issues/new?assignees=&labels=triage&projects=&template=bug_report.md&title=
