### ISSUE TITLE
Automobilista 2 no longer working

### ISSUE THREAD

**Issue by xexets** [SHWotever/SimHub#1433]
**Describe the bug**
after simhub update nothing (shakers, wind and dashboard) no longer work with automobilista 2. manual configuration in game is correct. simhub works fine with other games (such as acc)

**Simhub version**
9.1.1

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**
open automobilista 2 start a race, no telemetry goes to simhub

**Expected behavior**
simhub working

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
[Logs.zip](https://github.com/SHWotever/SimHub/files/12840995/Logs.zip)

**Comment by xexets** [comment]
further to the above: this happens only in multiplayer Automobilista 2. If I play in single player Simhub works fine

**Comment by SHWotever** [comment]
Thanks for the report ! I see indeed where it had failed, unfortunately it has a domino effect and breaks all the next data update.
I fix it for next update !

I published a beta including the fix : https://github.com/SHWotever/SimHub/releases/tag/9.1.2b2
Do not hesitate to tell me if this get's it fixed, I tried to connect to a couple of servers and i did not had the case, so I guess it's also dependant of the server status, or somthing similar.

**Comment by xexets** [comment]
super! thank you so much, the beta linked works perfectly on RCO servers now!

**Comment by SHWotever** [comment]
Perfect. Thanks for your feedback!
