### ISSUE TITLE
Position Change Endurance Team racing Iracing

### ISSUE THREAD

**Issue by Luckybarl** [SHWotever/SimHub#1434]
Position change works, however for Iracing endurance races (Team events) when you leave session and come back later the position change now goes off where they currently are and not the original start position as it should. Can this be updated to always revert to starting positon?

*Describe the bug**

**Simhub version**
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi ! It's indeed the expected behaviour. For now the positions are self tracked from the connection to the server. If you leave it state is lost. Most games does not provide that starting grid so it's not possible to get it back.

**Comment by SHWotever** [comment]
Thanks for your feedback ! Have fun !
