### ISSUE TITLE
5 Ahead-Behind et problème de performance

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1437]
Hello
J'ai ré-écrit mon tableau des 5 ahead behind et je recontre des problèmes de performance

**l'ancien tableau**
il est écrit en langage traditionnel (voir copie d'écran)

**le nouveau tableau**
j'utilise un widget que j'appelle pour chaque ligne ahead-5, ahead-4, ahead-3, etc.... en fournissant une donnée en entrée du widget 
pour préciser si la ligne concernée est -5 ou -4 ou -3, etc....

**et je rencontre un problème de performance sur le nouveau tableau :**
les bestlap et laslap s'affichent en alternance toutes les 2 secondes avec la lettre B ou L devant chacun des temps
sur l'ancien tableau, le swap entre bestlap et lastlap est immédiat pour toutes les lignes
sur le nouveau tableau, on voit bien que chaque ligne swap l'une apès l'autre

Pas d'erreur de log
test sur rf2 sur la V9.1.2
j'ai aussi rétrogradé en V9.1.1 mais j'ai le même problème
refreshrate à 0

Nota : 
peut-être que ma solution ne convient pas mais je n'ai pas trouvé de solution pour appeler une seule fois le widget ; ce dernier étant à l'intérieur d'une boucle de 5 lignes pour les ahead et dans une boucle de 5 lignes pour les behind
Ouf..j'espère avoir été clair

https://drive.google.com/file/d/10wmmviy7T6lw2y3ibz4pQEozhVIyRzyD/view?usp=drive_link

![1](https://github.com/SHWotever/SimHub/assets/58605557/d8a2bc14-4a81-4236-9529-a9a2a2d10b1b)
![2](https://github.com/SHWotever/SimHub/assets/58605557/13a1e721-ee47-4f5c-a27e-c1f96b62f94d)

**Comment by herve4545** [comment]
Hello
J'ai finalement réussi à créer une version encore plus light

https://drive.google.com/file/d/128cCVsTS7s99Ev0fQHq87yRSa1ojmwS2/view?usp=drive_link

![0](https://github.com/SHWotever/SimHub/assets/58605557/bd7beb8e-7db4-4d4a-8a81-f30cad3590cf)

**Comment by SHWotever** [comment]
Hello ! J'ai eu un petit de mal à débugger, car même si tu l'as "simplifié" ca reste très difficile de s'orienter ;( 

J'ai regardé un peu le fichier d'extensions j'ai vu des repeatindex qui trainent il faudrait les retirer des extensions _HERVE_MY_ALL_DASH.js 

Pour optimiser les performances des choses répétitives il y à une mise en cache des résultats si repeatindex est détecté dans la formule  : le moteur fera attention à le prendre en considération. Mais si on accède à "repeatindex" directement depuis les extensions il ne peux pas le voir et du coup le résultat pourrait être basé sur un mauvais "repeatindex". A vu de nez ca pourrait être ça le problème.

Si ca ne suffit pas si tu sais réduire le cas de test à un texte, et juste ce qui sert dans le fichier JS, je pourrais analyser plus précisément, mais en l'état le fichier d'extensions fait 4000lignes je ne sais pas quoi regarder, ce qui sert ce qui ne sert pas :(

**Comment by herve4545** [comment]
ok
je vais faire un fichier js spécifque pour ce cas de test
je reviens vers toi

**Comment by herve4545** [comment]
J'ai créé un fichier JS spécifique pour ce cas et le problème a disparu
Dès que je remet le fichier JS d'origine, le problème réapparaît
J'en conclue donc que j'ai un problème de coding dans le fichier JS et que tu ne pourras pas m'aider :snif
Ouch, ca va être compliqué à débugger ce truc
Je vais faire des test pas à pas en enrichissant le fichier JS au fur et à mesure

**Comment by herve4545** [comment]
Bon,
Avant de commencer mes tests, j'ai renommé en .SAV le fichier JS qui se trouvait dans \SimHub\JavascriptExtensions

j'ai fait pas mal de test sur le fichier JS spécifique

1) J'ai supprimé tous les repeatindex du fichier JS de 4000 lignes

2) avec le fichier JS spécifique à ce dash sans aucune autre ligne de code = pas de problème de perf

3) avec le fichier JS spécifique à ce dash 
+ toutes les les lignes de code pour gérer les leaderboard
= les perfs commencent à se dégrader très légèrement

4) avec le fichier JS spécifique à ce dash 
+ toutes les lignes de code pour gérer les leaderboard
+ toutes les lignes de code pour gérer le fuel
 = les perfs se dégradent un tout petit peu plus

4) avec le fichier JS spécifique à ce dash 
+ toutes les lignes de code pour gérer les leaderboard
+ toutes les lignes de code pour gérer le fuel
+ toutes les lignes de code pour gérer les "divers"
 = les perfs se dégradent encore un tout petit peu plus

5) avec le fichier JS spécifique à ce dash 
+ toutes les lignes de code pour gérer les leaderboard
+ toutes les lignes de code pour gérer le fuel
+ toutes les lignes de code pour gérer les "divers"
+ toutes les lignes de code pour gérer les logos carclass et logos constructeurs
soit environ 4000 lignes
 = les perfs se dégradent encore un tout petit peu plus

---> Il semble donc que la quantité de lignes de code semble poser problème
J'ai fait pas mal de test dans tous les sens et ca semble être toujours le même constat

Ce qui m'échappe, c'est que le tableau des 5 ahead/behind codé à l'ancienne n'a pas ce problème de perf alors qu'il lit le même fichier JS de quasi 4000 lignes
Il y a donc autre chose mais je ne trouve pas
Serait-ce une taille de cache à agrandir ?

Si j'éclate ce fichier en plusieurs fichiers JS en faisant ceci :
1) chaque fichier JS contenant uniquement les lignes de code spécifiques à chaque dash et donc stocké dans le dossier JavascriptExtensions de chaque dash
2) un fichier JS contenant le code commun à tous les dash stocké dans le dossier \SimHub\JavascriptExtensions

Est-ce que cela résoudra les problèmes sachant que la quantité de lignes de code de tous ces fichiers JS restera donc la même


A noter : je suis expert dans les ctrl+c  ctrl+v  ctrl+z  ctrl+y  ctrl+s

**Comment by SHWotever** [comment]
Hello !
Oui effectivement plus on en met, plus a chaque binding il y a de code à charger ou à exécuter, c'est exponentiel.

Si tu as disons 500 bindings, le code sera exécuté 500 fois, le cache n'y pourra rien si ce sont 500 bindings différents.
2 lignes de codes de plus * 500 bindings c'est 2000 lignes de code en plus à executer. 
Les widgets empirent la situation, car si il y avait des pures répétitions de formules, elles ne seront pas détectées (le "cache" de chargement des formules s'arrête au niveau du widget)

Les chiffres sont purement théoriques, ca ne se compte pas en "ligne" dans l'absolu mais l'idée est là. L'impact de tes extensions dépend du nombre de bindings dans le dash pour la faire courte.

Il y a tout intérêt à réduire au maximum le code inutile. Mettre dans le dossier global exclusivement ce qui sert de manière globale.
Dans le dossier du dash uniquement ce qui sert pour le dash.
So tu avais 4000 lignes, que au final tu as "1000" en commun, et 500 par dash * 4, tu gagnes 2500 lignes de code pour chaque binding.

Dans la dernière beta pour réduire aussi les chargements d'extensions inutiles il est possible de choisir ce qui sera chargé pour chaque binding, 

![image](https://github.com/SHWotever/SimHub/assets/2207331/6e70cc5d-0209-4e42-927f-b4db49b1f45c)

Si tu fais du js dans un dinding mais que tu n'utilises pas les extensions, cette fois ci ce sera du pure gain.

**Comment by SHWotever** [comment]
J'ajouterais même, pour améliorer la "portabilité", il serait même intéressant de se débarrasser du global et d'en faire une copie dans chaque dash, si tu partages un de tes dash , il suffira de l'importer sans aucune copie de fichier à la main

**Comment by herve4545** [comment]
OK Merci
je vais regarder tout ça

**Comment by herve4545** [comment]
Je ne comprends pas le mot "bindings"

**Comment by SHWotever** [comment]
Les bindings c'est les formules qui sont associées à une propriété (par exemple texte, textcolor etc ...) 

Comme dans ma précédente capture, c'est le binding de la propriété "répétition" 
https://user-images.githubusercontent.com/2207331/275579069-6e70cc5d-0209-4e42-927f-b4db49b1f45c.png

**Comment by herve4545** [comment]
Ah mais oui bien sûr
Je ferme le ticket
