### ISSUE TITLE
Bass Shakers. Only mono working with USB soundcard

### ISSUE THREAD

**Issue by Festa21** [SHWotever/SimHub#1439]
Hey guys, i think ive discovered a bug trying to get a stereo audio signal for my bass shakers from my "sound blaster play 3" USB sound card

When i go to: shakeIt Bass Shakers/sound output/speakers(sound blaster play 3) and select "Front / Rear" (or any non-mono setting) and test Front, then Rear, it shows each channel working independently in simhub, but both shakers work equally. If i lower the test audio on front, then click "test now" the level will be less but the same on both shakers, the same happens for rear. This does NOT happen if i plug my transducer amp directly into my motherboard audio. It splits the audio signal and the "test now" audio levels etc work as expected.

I know the sound card and transducer amp are working correctly, because if i set my desktop audio to output music through the USB sound card and to my transducers, the left and right balance splits the audio signal between my transducers as expected.

For some reason i am getting the same "mono" signal through the sound card when using sim hub, even tho sim hub shows it is outputting on separate channels

If you have anything i can try, or you need more information, let me know

Thanks, Dave

**Comment by SHWotever** [comment]
Hi ! Could you check that your "faulty" sound card does not have any ameliorations (like virtual sourround etc ... ? ) it's often the major cause of unwanted mixings like that. channel "Testing" often bypass that. Maybe there are also drivers to get installed. Uome usb sound cards will have a weird behaviour until it's installed with proper drivers (outside of the shakers application range, G920 headset was on of this kind from memory with a fake "7.1" effect enabled out of the box until you disable it with drivers ).

Trying to record generated audio with a software like audacity should leverage any doubts about the generated sound as it normally captures audio before "enhancements".

**Comment by Festa21** [comment]
Hi, yea I got it figured out. You are 100% correct, once I installed the driver software and changed a setting from "headphones" to "2.0 stereo" I got the desired result

I appreciate the reply. Am stoked to have it working now

Thanks, Dave

________________________________
