### ISSUE TITLE
BeamNG SH telemetry mod gives wrong values

### ISSUE THREAD

**Issue by Farapture** [SHWotever/SimHub#1440]
Dashboard data, specifically numerical values (boolean seem fine, i.e. parking light works), are acting up and changing constantly with nonsensical numbers. It started happening after updating to 9.1.4 (can't recall the previous version). I also tried changing udp port but it still happens. Here are some screenshot of the values:

![immagine](https://github.com/SHWotever/SimHub/assets/101994863/def127db-41f0-4160-823d-173f1d020f32)
![immagine](https://github.com/SHWotever/SimHub/assets/101994863/1a9be294-f7e8-491d-946b-1ffca163c60b)

P.S. OutGauge seems to work fine

**Comment by SHWotever** [comment]
Hi ! Thanks for the report, indeed there was a data misalignment, I fixed it for the next version,

Nicolas
