### ISSUE TITLE
Dirt Rally 2.0 Shows Wrong Speed 

### ISSUE THREAD

**Issue by bodya1508** [SHWotever/SimHub#1442]
I use my diy dash with simhub and in the Dirt Rally 2 that there is a problem with the speed shown on the screen and on the instrument panel is different, the higher the speed, the bigger the difference seems to me. The parameters themselves are set correctly, both in the game and in simhub km/h. In other games such as AC Project cars Forza there is no such problem.

**Comment by SHWotever** [comment]
Hi ! 

Dirt rally only reports the ground speed, which is indeed different from the in game "hud", unfortunately even if we have the wheel speed, the behavior to "reproduce" the display varies a lot from car to car.
