### ISSUE TITLE
[Feature request] ETS2 Map update

### ISSUE THREAD

**Issue by DopeEx** [SHWotever/SimHub#1444]
**Is your feature request related to a problem? Please describe.**
The new map addon "West Balkans" has been released and is missing in the ETS2 map component in Simhub.

**Describe the solution you'd like**
It would be nice to get an update of the ETS2 map so that you have a working map for the new region.

**Describe alternatives you've considered**
Simhub Dashbards are the best there is no alternative!  ;)

**Additional context**
I know the new map addon "West balkans" is only out since today I just wanted to create a request to draw attention to it.

**Comment by SHWotever** [comment]
Hi !

The map has been updated with the new area, to update it simply click here and restart SimHub :
![image](https://github.com/SHWotever/SimHub/assets/2207331/8a9c242b-7225-4486-95d0-03c1bcac4630)

![image](https://github.com/SHWotever/SimHub/assets/2207331/374d733a-fafa-4fb5-a2b3-9d2b4b8eee0f)

Best regards,
Nicolas
