### ISSUE TITLE
Ajout de  RelativeGapclassToPlayer

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1445]
Hello
sur les versions actuelles, nous avons le RelativeGapToPlayer
Serait-il possible d'avoit le même type de donnée pour le gap dans la même carclass RelativeGapCLASSToPlayer ?
Merci

**Comment by SHWotever** [comment]
Hello !
Le "relative gap" se fait d'un "opponent" à "toi", du coup il n'y a pas de notion de classe, la valeur sera toujours la meme.

J'imagine que tu veux faire du "ahead behind" **filtré** sur ta classe, dans ce cas c'est déjà présent 

Au lieu d'utiliser la fonction suivante :
```js
getopponentleaderboardposition_aheadbehind(leaderboardposition)
```
il faut utiliser celle filtrée sur ta classe :
```js
getopponentleaderboardposition_aheadbehind_playerclassonly(leaderboardposition)
```
Par exemple pour le premier "ahead" de ta classe : 
```js
drivergaptoplayer(getopponentleaderboardposition_aheadbehind_playerclassonly(-1))
```

**Comment by herve4545** [comment]
Merci
Oui, c'est ce que je cherchais 
J'avais pas bien fouillé dans la pléthore de données disponibles
