### ISSUE TITLE
[Feature request] Saving Track Map for Forza Motorsports

### ISSUE THREAD

**Issue by bhabanism** [SHWotever/SimHub#1446]
**Is your feature request related to a problem? Please describe.**
New Forza Motorsports disappointingly has the same data out as the older version. I still have a request for an improvement. 
Problem - FM does not send the track name, so the generated track maps get overwritten everytime track changes as the file is stored with a id that is game-session specific and does not change between races/tracks. 

**Describe the solution you'd like**
 Please save the file for generated track using  Track Length, value for $prop('TrackLength') is get's calculated after a valid lap. 
Also will be good if the font colour of "Waiting for map generation" can be changed, it's black colour and with most of cockpit black it's hard to see in overlays.

**Describe alternatives you've considered**

**Additional context**

**Comment by SHWotever** [comment]
Hi ! The "track id" is now used since 9.4.1. It has been the on

**Comment by SHWotever** [comment]
Nb : I've not triggered the new version notification yet as it seems to make nervous antivirus for mysterious reasons. But you can download it here : https://www.simhubdash.com/download-2/
