### ISSUE TITLE
PLUS RIEN

### ISSUE THREAD

**Issue by 83400** [SHWotever/SimHub#1448]
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by 83400** [comment]
bonjour simhub ne s'ouvre plus du tout malgré désinstall et réinstall plusieurs fois,je ne sais plus quoi faire

**Comment by SHWotever** [comment]
Bonsoir,

Afin qu je puisse analyser ce qu'il se passe pouvez vous joindre les fichiers de log présents dans C:\Program Files (x86)\SimHub\Logs
(Le fichier simhub.txt est le plus important).

Comment attacher un fichier a la demande : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

Merci par avance,
Cordialement,
Nicolas

**Comment by 83400** [comment]
voila merci

________________________________
De : Wotever ***@***.***>
Envoyé : mardi 24 octobre 2023 21:14
À : SHWotever/SimHub ***@***.***>
Cc : 83400 ***@***.***>; Author ***@***.***>
Objet : Re: [SHWotever/SimHub] PLUS RIEN (Issue #1448)


Bonsoir,

Afin qu je puisse analyser ce qu'il se passe pouvez vous joindre les fichiers de log présents dans C:\Program Files (x86)\SimHub\Logs
(Le fichier simhub.txt est le plus important).

Comment attacher un fichier a la demande : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

Merci par avance,
Cordialement,
Nicolas

**Comment by SHWotever** [comment]
Bonsoir,
Pouvez vous l'attacher directement a la demande ? https://github.com/SHWotever/SimHub/issues/1448

Les pièces jointes ne sont pas supportées avec les réponses par email

Comment attacher un fichier a la demande : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

Merci par avance,
Cordialement,

**Comment by 83400** [comment]
[SimHub.PackageManager.Standalone.2.log](https://github.com/SHWotever/SimHub/files/13126589/SimHub.PackageManager.Standalone.2.log)
[SimHub.PackageManager.Standalone.3.log](https://github.com/SHWotever/SimHub/files/13126590/SimHub.PackageManager.Standalone.3.log)
[SimHub.PackageManager.Standalone.1.log](https://github.com/SHWotever/SimHub/files/13126591/SimHub.PackageManager.Standalone.1.log)

**Comment by SHWotever** [comment]
Avez vous le fichier de log simhub.txt s'il vous plaît ?

> Bonsoir,
> 
> Afin qu je puisse analyser ce qu'il se passe pouvez vous joindre les fichiers de log présents dans C:\Program Files (x86)\SimHub\Logs (Le fichier simhub.txt est le plus important).
> 
> Comment attacher un fichier a la demande : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
> 
> Merci par avance, Cordialement, Nicolas
