### ISSUE TITLE
wrong path to start program at pluginsdkdemo

### ISSUE THREAD

**Issue by kaaac** [SHWotever/SimHub#1449]
Hello.

In file User.PluginSdkDemo.csproj.user there is wrong path to start program:
```
<StartProgram>C:\Users\nguil\Dropbox\AC\Main\HubPackage\SimHub\SimHubWPF.exe</StartProgram>
```
checked at 2 separate installations

i tihink it is tiny tiny mistake :)

**Comment by SHWotever** [comment]
Hi ! This file was indeed wrong and is not distributed anymore in simhub installations, you probably inherited it from older installs :
![image](https://github.com/SHWotever/SimHub/assets/2207331/f1bfbac4-cf27-40bf-9baf-62e70f8f94e7)

**Comment by kaaac** [comment]
Yes! some version around beginning of version 9.
Have a nice day!
