### ISSUE TITLE
Access to Event Details in F1 23

### ISSUE THREAD

**Issue by kaaac** [SHWotever/SimHub#1450]
Hello!

How to access Event detailed data from F12023 telemetry? 

CodemastersReader provides those data but this is not available in GameData data from DataUpdate() void...

![image](https://github.com/SHWotever/SimHub/assets/74159167/8ffabf6a-5dd8-48cf-aade-23f8cd864c13)

Best Regards :)

**Comment by SHWotever** [comment]
Hi ! Events are accessible only to plugins, events are "stateless" and only gives data at a very specific time frame. 

All the events are cumulated in order of receiving in the rawdata EventHistory field, You need to look for items of type EventData<EventPenalty>.

**Comment by kaaac** [comment]
Thanks for answer!
In EventHistory as far i see there is only Event Code right? without details?

**Comment by SHWotever** [comment]
EventData is a two level object, depending of the kind of events :

![image](https://github.com/SHWotever/SimHub/assets/2207331/28b5deb6-4ba1-4dd9-ac48-fd1c2c2ce20f)

Depending of the details available you will find either instances of the second class or 3rd class  :
- `EventData<CodemastersReader.F12023.Packets.PacketHeader>` in case of event with no content
- `EventData<CodemastersReader.F12023.Packets.PacketHeader, CodemastersReader.F12023.Packets.EventXXX>` in case of parsed packet (IE : `EventData<CodemastersReader.F12023.Packets.PacketHeader, CodemastersReader.F12023.Packets.EventPenalty>` for penalty)

**Comment by kaaac** [comment]
Thank you for this answer!

Does it will be available from here?
![image](https://github.com/SHWotever/SimHub/assets/74159167/b5d5b67a-f676-4827-924b-47a0eaf8399b)

Maybe im trying by wrong way, but it seems **GameData data** have access only to F12023TelemetryContainer**Ex**, but Events are available from F12023TelemetryContainer (without **Ex**)

**Comment by SHWotever** [comment]
Both ;) 


F12023TelemetryContainerEx is a snapshot of the F12023TelemetryContainer data with some key values like player values made more directly available to help with later processing, 

![image](https://github.com/SHWotever/SimHub/assets/2207331/b0980640-a989-4e01-a8d2-785e7c85fe83)

**Comment by kaaac** [comment]
It's starting to get brighter :)
Does the recorded replay include the event history?

**Comment by SHWotever** [comment]
Huuumm ... good point :D They are, they are deserialized only using the base class. 
Json and inheritance, this need a fix to be complete packets, But in "live" they will be complete .

**Comment by SHWotever** [comment]
It's fixed in simhub replays for the next version ;)

**Comment by kaaac** [comment]
So, technically speaking, I could access full information about events during the session from event history, and after a future update I would be able to develop the plugin more easily using replays?

**Comment by SHWotever** [comment]
Exactly ;)

**Comment by kaaac** [comment]
Amazing!

Thank you!
