### ISSUE TITLE
[Feature request] Font Colour for "Waiting for map generation" in Map widgets

### ISSUE THREAD

**Issue by bhabanism** [SHWotever/SimHub#1453]
**Is your feature request related to a problem? Please describe.**
The "Waiting for map generation" text shown by Map widgets are currently black in colour and gets hidden behind the black areas in the cockpit view and is problem when trying to regenerate track map manually to get the feedback if the regeneration is triggered on button press or not. 
![mapgen](https://github.com/SHWotever/SimHub/assets/1041994/e8825624-0de7-486c-9ea8-ec421d23e834)

**Describe the solution you'd like**
Ability to change the **font colour** via dash studio will make it more visible. 
Another way will be to give a JS property - **isMapGenerating** and user can add LED/Image indicators and **hide** the text if user doesn't want to see it.

**Comment by SHWotever** [comment]
I'm not sure setting a color would help, white on black / black on white, there are always some situations where it will be wrong and unreadable. At the time I hesitated to put a semi transparent background so it keeps readable all the time, but it's super invasive

**Comment by bhabanism** [comment]
Agree fixed font colour won't solve the visibility in all scenario. May be a small glyph icon will be indicative enough. To start with we can have just a property isMapGenerating (true/false) and user can add additional element/text as they wish.

**Comment by SHWotever** [comment]
Hi ! I close this, I added a small half opaque background to the text allowing to see it no matter the conditions.
