### ISSUE TITLE
Empty folders generate C:\Users\_username_\AppData\Local\Temp

### ISSUE THREAD

**Issue by pakho0517** [SHWotever/SimHub#1457]
**Describe the bug**
Empty folders generate C:\Users\    username    \AppData\Local\Temp
![Screenshot 2023-11-04 163849](https://github.com/SHWotever/SimHub/assets/100706107/3ff6cf48-1156-4e59-8ebd-6fb2b32b6a81)

**Simhub version**
9.1.8

**To Reproduce**
1. Open Simhub

**Expected behavior**
None of those empty folders. Previous versions were not doing that

**Log files**
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/13256151/SimHub.1.txt)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/13256152/SimHub.txt)

**Additional context**

**Comment by SHWotever** [comment]
Hi ! I added the directory delete for the next release ;) Those hosts for a short time fonts for analysis that's why they appear after (this goes really fast)
