### ISSUE TITLE
[Feature request] EA Sports WRC Official Telemetry!

### ISSUE THREAD

**Issue by DJLevel3** [SHWotever/SimHub#1459]
**Is your feature request related to a problem? Please describe.**
EA Sports WRC has just released an update with UDP telemetry! I just got some rumble motors and a bass shaker and I would love to get some use out of them!

**Describe the solution you'd like**
I would like support for EA Sports WRC added to SimHub!

**Describe alternatives you've considered**
I am aware of the hack that adds telemetry by injecting itself into the game, but with official telemetry this should no longer be necessary.

**Comment by SHWotever** [comment]
Hi ! It's already on the work ;)

I close this as it's obviously 100% part of my roadmap ;)
