### ISSUE TITLE
Suddenly SimHub is stuck in the "waiting for data" state

### ISSUE THREAD

**Issue by tubben224** [SHWotever/SimHub#1460]
Hi there, 
I have been using SimHub for multiple years and have had a flawless experience. However, I have suddenly had problems with SimHub communicating with my game. I upgraded to 9.1.6 to play EA WRC. This worked flawlessly for several days before it suddenly stopped communicating to the game. I then upgraded to 9.1.10 only to experience the same issue. The state never changes to "connected". Any help would be greatly appreciated. 

I have attempted the following troubleshooting steps:
- restart PC
- run SimHub as administrator
- light reinstall of SimHub
- full uninstall / reset of SimHub
- roll back to older version of SimHub
- Fully disable AV and firewall
- Automatically configure game
- Manually configure game
- Change UDP port

**Simhub version**
9.1.10

**Log files**
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/13324320/SimHub.1.txt)
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/13324321/SimHub.2.txt)
[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/13324322/SimHub.3.txt)
[SimHub.4.txt](https://github.com/SHWotever/SimHub/files/13324323/SimHub.4.txt)
[SimHub.5.txt](https://github.com/SHWotever/SimHub/files/13324324/SimHub.5.txt)
[SimHub.6.txt](https://github.com/SHWotever/SimHub/files/13324325/SimHub.6.txt)
[SimHub.7.txt](https://github.com/SHWotever/SimHub/files/13324326/SimHub.7.txt)
[SimHub.8.txt](https://github.com/SHWotever/SimHub/files/13324327/SimHub.8.txt)
[SimHub.9.txt](https://github.com/SHWotever/SimHub/files/13324328/SimHub.9.txt)
[SimHub.10.txt](https://github.com/SHWotever/SimHub/files/13324329/SimHub.10.txt)
[SimHub.11.txt](https://github.com/SHWotever/SimHub/files/13324330/SimHub.11.txt)
[SimHub.12.txt](https://github.com/SHWotever/SimHub/files/13324331/SimHub.12.txt)
[SimHub.13.txt](https://github.com/SHWotever/SimHub/files/13324332/SimHub.13.txt)
[SimHub.14.txt](https://github.com/SHWotever/SimHub/files/13324333/SimHub.14.txt)
[SimHub.15.txt](https://github.com/SHWotever/SimHub/files/13324334/SimHub.15.txt)
[SimHub.16.txt](https://github.com/SHWotever/SimHub/files/13324335/SimHub.16.txt)
[SimHub.17.txt](https://github.com/SHWotever/SimHub/files/13324336/SimHub.17.txt)
[SimHub.18.txt](https://github.com/SHWotever/SimHub/files/13324337/SimHub.18.txt)
[SimHub.19.txt](https://github.com/SHWotever/SimHub/files/13324338/SimHub.19.txt)
[SimHub.PackageManager.Standalone.1.log](https://github.com/SHWotever/SimHub/files/13324339/SimHub.PackageManager.Standalone.1.log)
[SimHub.PackageManager.Standalone.2.log](https://github.com/SHWotever/SimHub/files/13324340/SimHub.PackageManager.Standalone.2.log)
[SimHub.PackageManager.Standalone.3.log](https://github.com/SHWotever/SimHub/files/13324341/SimHub.PackageManager.Standalone.3.log)
[SimHub.PackageManager.Standalone.4.log](https://github.com/SHWotever/SimHub/files/13324342/SimHub.PackageManager.Standalone.4.log)
[SimHub.PackageManager.Standalone.5.log](https://github.com/SHWotever/SimHub/files/13324343/SimHub.PackageManager.Standalone.5.log)
[SimHub.PackageManager.Standalone.6.log](https://github.com/SHWotever/SimHub/files/13324344/SimHub.PackageManager.Standalone.6.log)
[SimHub.PackageManager.Standalone.7.log](https://github.com/SHWotever/SimHub/files/13324345/SimHub.PackageManager.Standalone.7.log)
[SimHub.PackageManager.Standalone.8.log](https://github.com/SHWotever/SimHub/files/13324346/SimHub.PackageManager.Standalone.8.log)
[SimHub.PackageManager.Standalone.9.log](https://github.com/SHWotever/SimHub/files/13324347/SimHub.PackageManager.Standalone.9.log)
[SimHub.PackageManager.Standalone.Elevated.1.log](https://github.com/SHWotever/SimHub/files/13324348/SimHub.PackageManager.Standalone.Elevated.1.log)
[SimHub.PackageManager.Standalone.Elevated.2.log](https://github.com/SHWotever/SimHub/files/13324349/SimHub.PackageManager.Standalone.Elevated.2.log)
[SimHub.PackageManager.Standalone.Elevated.3.log](https://github.com/SHWotever/SimHub/files/13324350/SimHub.PackageManager.Standalone.Elevated.3.log)
[SimHub.PackageManager.Standalone.Elevated.4.log](https://github.com/SHWotever/SimHub/files/13324351/SimHub.PackageManager.Standalone.Elevated.4.log)
[SimHub.PackageManager.Standalone.Elevated.5.log](https://github.com/SHWotever/SimHub/files/13324352/SimHub.PackageManager.Standalone.Elevated.5.log)
[SimHub.PackageManager.Standalone.Elevated.6.log](https://github.com/SHWotever/SimHub/files/13324353/SimHub.PackageManager.Standalone.Elevated.6.log)
[SimHub.PackageManager.Standalone.Elevated.7.log](https://github.com/SHWotever/SimHub/files/13324354/SimHub.PackageManager.Standalone.Elevated.7.log)
[SimHub.PackageManager.Standalone.Elevated.8.log](https://github.com/SHWotever/SimHub/files/13324355/SimHub.PackageManager.Standalone.Elevated.8.log)
[SimHub.PackageManager.Standalone.Elevated.9.log](https://github.com/SHWotever/SimHub/files/13324356/SimHub.PackageManager.Standalone.Elevated.9.log)
[SimHub.PackageManager.Standalone.Elevated.log](https://github.com/SHWotever/SimHub/files/13324357/SimHub.PackageManager.Standalone.Elevated.log)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/13324358/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! Apparently the settings were correctly applied, 

Could you join me the following game settings file ? Documents\My Games\WRC\telemetry\config.json So I can check it ?

About the 9.1.6 being broken for EA WRC, the wrc telemetry patch was a temporary patch which got broken after the game update.

**Comment by tubben224** [comment]
Hello, the telemetry config seemed to be the problem! The port values were not being updated when the config was loaded. I reset the UDP port in SimHub to the default value of 29888 and copied the config file from the supplied folder. Working perfectly again!

In case you would like the telemetry config that was being loaded (no matter if it was automatic configuration or no matter what port number was set) I have attached below. 

Thank you for the help. 

[config.json](https://github.com/SHWotever/SimHub/files/13326292/config.json)

**Comment by SHWotever** [comment]
Thanks for your feedback.
