### ISSUE TITLE
simagic pedal problems

### ISSUE THREAD

**Issue by Jumperunited** [SHWotever/SimHub#1461]
hello, since the last update the simagic bug crank motors, in games so that the feeling is present we have to stay pressed on the clutch otherwise the effects do not work. as soon as we press the clutch all works but you have to keep pressing. I'm on a reversed Simagic p1000, there is no problem with the 9.1.7 update. this problem appeared from 9.1.8 best regards

**Comment by SHWotever** [comment]
Hi !

Thanks for the report, i've released a hotfix : https://github.com/SHWotever/SimHub/releases/tag/9.1.11

Let me know if everything works correctly.

Best regards,
Nicolas

**Comment by Jumperunited** [comment]
I tested it and it works perfectly now, a big thank you to you for your incredible responsiveness, good luck 👌
