### ISSUE TITLE
Matrix Display always on outside of the game

### ISSUE THREAD

**Issue by danfeliix** [SHWotever/SimHub#1462]
**Describe the bug**
Does simhub have the option to turn off the Matrix Display when the game (ETS2) is not running? As with the TM1638?

**Simhub version**
Simhub 9.1.8

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**
I would like all peripherals to turn off when the game is not currently running

**Screenshots**
![WhatsApp Image 2023-11-11 at 15 57 45](https://github.com/SHWotever/SimHub/assets/54558657/5dae8532-95a1-4f85-a0eb-960ae38054fb)

**Additional context**
Another thing that happens, even if I close the sim hub, the 20x4 LCD screen stays on all the time, it only turns off if I remove the USB cable

**Comment by SHWotever** [comment]
hi !

You have the setting available here :

![image](https://github.com/SHWotever/SimHub/assets/2207331/c59e0c51-e7d1-4d9b-a87a-e5abc22c98a3)

About the LCD I don't have control over the backlight.
