### ISSUE TITLE
SimHub+Rfactor2= lag

### ISSUE THREAD

**Issue by Kuelitropo** [SHWotever/SimHub#1463]
Hello, I wanted to ask if anyone else has the same problem that I have.
In Rfactor2 I load the overlays on the screen and it shows them the times and graphs but with a delay of about 5-10 seconds, I don't know if this is normal.
The version of SimHub is 9.1.8 and is licensed.
Thank you.
[SimHub.txt](https://github.com/SHWotever/SimHub/files/13328079/SimHub.txt)

**Comment by SHWotever** [comment]
Hi !
This is normal when your in game settings does not leave enough free GPU for Simhub : you can find a full performance guide here in the documentation : https://github.com/SHWotever/SimHub/wiki/DashStudio-performance

**Comment by SHWotever** [comment]
I would add that the GarySwallowDataPlugin Really put a lot (really a lot) of pressure, make sure to disable it.

**Comment by Kuelitropo** [comment]
Thank you very much for your reply.
It seems that the solution may lie there, I have lowered the Hz on the monitors from 165Hz to 120Hz and it seems that the lag has improved a lot.

**Comment by SHWotever** [comment]
Thanks for your feedback.
