### ISSUE TITLE
Forza Horizon/Motorsport GameData.Turbo property missing

### ISSUE THREAD

**Issue by Blumlaut** [SHWotever/SimHub#1464]
**Describe the bug**
GameData.Turbo is not filled, despite "GameRawData.Boost" existing, raw data is in psi (no matter which unit is used in the game settings)

**Simhub version**
9.1.11

**Third party plugins**
N/A

**To Reproduce**
In Dash Studio, "GameData.Turbo" property is not supported when running FH5/FM8, but "Boost" raw data works

**Expected behavior**
GameData.Turbo to properly use RawGameData.Boost and convert it to the locally configured units

**Screenshots**
not applicable

**Log files**
not applicable

**Additional context**
not applicable

**Comment by SHWotever** [comment]
Hi !
Thanks for noticing it ! It's fixed for the next version.
