### ISSUE TITLE
Simhub cannot handle two "Web device slot" devices

### ISSUE THREAD

**Issue by VictorMCFreitas** [SHWotever/SimHub#1465]
I have 2 devices configured as Web device slot. One tablet and one smartphone. In the devices tab only the tablet is recognized and say "connected" the smartphone says "searching devices" and, although both dashboards work as they should in games, I cannot configure buttons to change Action A/B/C/D or other control key of the smartphone. Is it a bug or I only can have only one of each device types to change control? 

**Simhub version**
SimHub 9.1.11

**Comment by SHWotever** [comment]
Hi !

I I checked everything was working as intended. 

Can you check those steps in order ? 

Make sure you have one Slot per device : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/929600a7-89ba-4020-a786-557992115487)


Make sure to connect to one of them on each device  (Slot # 1 for the first one # 2 for the second one):
![image](https://github.com/SHWotever/SimHub/assets/2207331/e9df5015-9a8a-4458-adb1-83e5c7365bcd)

Then each one should show as connected and you can see the device informations at the bottom :
![image](https://github.com/SHWotever/SimHub/assets/2207331/0635d8b6-9d3c-4526-bf48-5076eb0de6cc)

At this point individual controls as configured in this screen for each one should work as intended : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/69befd2d-2e7a-4e0e-aa46-489948f07f25)

**Comment by SHWotever** [comment]
If it does not work could you join the log files as requested in the template ? https://github.com/SHWotever/SimHub/issues/new?assignees=&labels=triage&projects=&template=bug_report.md&title=

**Comment by VictorMCFreitas** [comment]
Solved. I had, in Dash studio / Controls, more than one line of the devices. Deleted the extra lines and the smartphone device instantly appeared as Connected and started work as it should.

Thank you for your time. I will close this.

Victor Freitas
