### ISSUE TITLE
Simhub searchinh

### ISSUE THREAD

**Issue by XXTheZeroXX** [SHWotever/SimHub#1466]
Simhub keeps searching for my USB Vcore screens and flickering. They only show connected when I switch the ide behaviour when running to power off.
Can you pleases help?

**Comment by SHWotever** [comment]
Hi ! Usually it's an usb issue, idle will use less bandwidth as it's not refreshing the screen. Make sure to check your usb cables, avoid usb hubs, change the usb port on your motherboard. 

If it doesn't help could you join the log files as requested in the template : https://github.com/SHWotever/SimHub/issues/new?assignees=&labels=triage&projects=&template=bug_report.md&title= so I can diagnose it with more accurate informations.
