### ISSUE TITLE
nascar 2003 season bug!

### ISSUE THREAD

**Issue by SwiftyOne1** [SHWotever/SimHub#1468]
Hi, thank you for adding this game I know how difficult this old game can be to work with :) 
So here's what I have going on.... (Simhad version 9.1.11) I had to add the game manually as Simhub could not connect to it (I use the no CD exe ) The game starts up ok from Simhub but doesn't recognise my controllers (Fanatec DD2 base with the v3 peddles plugged into the wheelbase ) My attached two screenshots showing starting the game with Simhub and starting the game normally through the desktop Icon....
![Nascar no Simhub](https://github.com/SHWotever/SimHub/assets/43917632/992af000-4f2e-402c-a2c7-0768ad85bb38)
![Nascar Simhub](https://github.com/SHWotever/SimHub/assets/43917632/199d3b64-c3e4-4b87-95c4-212f02b435eb)
When starting the game normally you can see an arrow that I can click and go to another calibration screen to set up my wheel and peddles ....The game within Simhub only has the first calibration screen without the arrow so It doesn't recognise my wheel or peddles, I have to use the no cd exe as I don't have the cd...Thank you!

**Comment by SHWotever** [comment]
Hi ! 

Can you provide the simhub logs as requested in the issue template ? https://github.com/SHWotever/SimHub/issues/new?assignees=&labels=triage&projects=&template=bug_report.md&title=

About running the game from Simhub: it's not mandatory and you can run it the way you usually do,.
As it make sense I don't support "cracked" games, so I can t give In depth support for such versions.

**Comment by SwiftyOne1** [comment]
Hi Thanks for your help and you are correct in saying I can run the game quite normally without Simhub as I have been doing for many years...

**Comment by SwiftyOne1** [comment]
Thank you, I understand and yes, it makes sense ;)
