### ISSUE TITLE
Enable to save overlay layout

### ISSUE THREAD

**Issue by fernlop11** [SHWotever/SimHub#1469]
**Describe the bug**
Missing button to save overlay layout. Have to position all overlays over and over, if I want to race. It sucks. :)

**Simhub version**
9.1.12

**Comment by SHWotever** [comment]
Hi !

When you have finished editing the layout and validated it you can save it from the control window using the save layout button :

![image](https://github.com/SHWotever/SimHub/assets/2207331/b5bcd915-c039-4ec6-8a44-b7ad9b24ad22)

**Comment by fernlop11** [comment]
Hi
I must be an idiot because can't find that window that you're showing
🥴
Can't figure it out where a can find it!!
When run overlay layout window it is not the same window...🤔
Thx
