### ISSUE TITLE
[Feature request] Add Flag LED Support for Goovee/Ambient lights

### ISSUE THREAD

**Issue by Mr-Pearce** [SHWotever/SimHub#1472]
**Is your feature request related to a problem? Please describe.**
Currently the Ambient lights/Govvee lights are scanning a specific area on the monitor which works fine for it intent.
But to use them for e.g. a "Flag light" you need to position an scan box on a speciffic location the scan for yellow or red light indicating the yellow or red flag situation.

**Describe the solution you'd like**
But it would be really cool if we could use (e.g. F1 UDP Data) direct data from the game to light the leds as a flag light or red delta or different color codes from the game.

Edit: Just found the Arduino RGB led settings. That would be mega cool if we could use this for Govvee lights!!!

Direct light control from game data.

**Describe alternatives you've considered**
A Cool addition to this would be if we could use the same data for e.g. Motherboard argb lights. (Asus has an c# api for that)

**Additional context**

**Comment by SHWotever** [comment]
Hello !
This is indeed planned when I will get enough "bandwidth" for this experimental feature.
Concerning motherboard lights this goes out of the scope of Simhub : it's overall really a black hole, Motherboards , mouse, keyboard ...  this is too wide to even put the little toe in it ;)

**Comment by Mr-Pearce** [comment]
Nice. 
I just found that the Arduino LED Control could probably do everything i want 😅 except using govvee lights ;)

**Comment by Openhabber** [comment]
+1. Would be super cool to light govee lights by telemetry: green for throttle, red for braking, blinking when abs engages...

**Comment by Openhabber** [comment]
Addition: wouldnt it be possible to add a govee strip as a normal Device like arduino led stripe, to use those features instead? I meantime, all the features are already there,  just in a different plugin

**Comment by vick-k** [comment]
Just to inform you guys in case you don't know already that this feature is working now for the Govee lights. I am not sure in which version this has been added, but I discovered it recently. I can confirm that flags, spotter, etc. are working in version 9.2.12 (I am using H6056 light bars).

Just go to Ambient lights plugin, then next to the Capture layout, select Color effects. From there you can create different profiles and they can even switch automatically depending on the game/car.
