### ISSUE TITLE
Simhub with g-sync: periodic "stutters"

### ISSUE THREAD

**Issue by Pety100** [SHWotever/SimHub#1474]
**Describe the bug**
SimHub causes periodic stutters to rFactor 2 when g-sync is enabled.

If I turn off g-sync and just use fps limiter (or even If I do not use), the tearing is extremely bad but the stutters disappear. So SimHub + g-sync are not friends as it seems.

I use g-sync like described here:
https://blurbusters.com/gsync/gsync101-input-lag-tests-and-settings/14/

This means I use g-sync, fps limiter (3 fps below refresh rate) and v-sync on, everything set in NVCP. In NVCP g-sync is only enabled for fullscreen mode. I run rFactor 2 in borderless mode so overlays can appear in front of the game.

Without enabling simhub overlay, these settings are giving smooth experience, super stable framerate and frametimes as well. But when I enable a SimHub overlay, I experience periodic stutters about every second even though the framerates and frametimes are still super stable based on what MSI Afterburner shows. So I don't understand why...

I already tried everything. Look N Feel setting enabled and disabled, switching to html render, disabling fullscreen optimizations for the game and for the simhub exe ...etc. Nothing has helped. :(

**Simhub version**
9.1.12

**Third party plugins**
I did not download any extra plugins.

**To Reproduce**
1. Enable g-sync
2. Enable simhub overlay while running the game in borderless (rFactor 2)
3. See the stuttering

**Expected behavior**
I expect to have a smooth driving experience with cool overlays.

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/13453893/SimHub.txt)

**Additional context**
Config:
CPU: AMD Ryzen 5 3600
GPU: Gigabyte RTX 2060 6GB
RAM: 2x8GB
MB: AsRock Ab350 Pro4
Monitor: LG 24MP59G-P (connected through DP to g-sync work)

**Comment by SHWotever** [comment]
Hi !

Rf2 is extremely sensitive. Have you checked that the GPU load was not at max ? https://github.com/SHWotever/SimHub/wiki/DashStudio-performance

About gsync this technology does not support wpf (which is the underlying technology in Simhub) while this won't be an issue with secondary monitor, with overlays showing on the same monitor you will hit this gsync limitation
