### ISSUE TITLE
Conditional overlay bug

### ISSUE THREAD

**Issue by andreasdahl1987** [SHWotever/SimHub#1476]
**Describe the bug**
From 9.1.6 onward, conditional overlay layer seems to be broken for HTML rendering. Switching to WPF fixes the issue, but this is not possible for VoCore screens. 

![image](https://github.com/SHWotever/SimHub/assets/40788634/57f2555b-4fbf-441e-b4f1-051d5d583ca3)

Top is WPF render, bottom is HTML

![image](https://github.com/SHWotever/SimHub/assets/40788634/96f094af-5874-4fc7-8cb4-e793477b31f0)

**Simhub version**
9.1.6

**Comment by SHWotever** [comment]
Hi !

Your dashboard seems to have an issue, you don't have any screens available, when saving you should have that error indicating it's wrong : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/0c5dd7bc-dc14-4065-a008-eca7930e6d38)

simply adding a proper screen, even empty, should work 

Can you confirm ?

**Comment by Jarne-T** [comment]
I am trying to solve this problem in the dash and have added a regular screen as you said. It will let me save the dash without an error but with the HTML renderer it still will not show the overlays. It does show with the WPF renderer. This is the screen I added:

![image](https://github.com/SHWotever/SimHub/assets/39411342/772b3bec-3424-461f-bbff-41db4cff0d93)

**Comment by andreasdahl1987** [comment]
Even without the screen, this is working fine on v9.1.5 or earlier

**Comment by SHWotever** [comment]
It's fixed for the next version ;)

**Comment by SHWotever** [comment]
Hello ! The fic was released with 9.1.15 :
https://github.com/SHWotever/SimHub/releases/tag/9.1.15

**Comment by andreasdahl1987** [comment]
Cheers, can confirm this is now working perfectly!
