### ISSUE TITLE
USB Device Detection is switching

### ISSUE THREAD

**Issue by Mekika** [SHWotever/SimHub#1481]
**Describe the bug**
When i change from windows desktop screen to my simrace screen, my ascher dashboard and my bavariamsimtecwheel omega pro are swapping in simhub, when i deactivate my ascher dash, my wheel is switching off and also the opposite way, 

Solution: deactivating both devices in simhub, close simhub, reopen simhub, when i switch on one device in simhub, the right device is detected

**Simhub version**
V9.1.16

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**
as mentioned above

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Screens are not explicitely bound to a wheel or DDU, to link them consistently you just have to use this option and choose the correct screen identifier for each one :
![image](https://github.com/SHWotever/SimHub/assets/2207331/f26bb39b-3098-436c-8c35-b3a36f504115)

If somehow it shows 00-00 .... it means your screens does not have an unique screen identifier flashed, in such case I would recommend to contact both companies to get it flashed (and avoid messing up with warranty)

**Comment by Mekika** [comment]
Thanks for help, is working perfectly
