### ISSUE TITLE
[Feature request] ShakeIt effect for clutch biting (BeamNG)

### ISSUE THREAD

**Issue by Farapture** [SHWotever/SimHub#1482]
**Is your feature request related to a problem? Please describe.**
I'm currently using a custom effect for beamng, but it is input based (clutch axis) and although I tried to emulate what the biting feels in BeamNG, it's not that realistic and I need to tune it for each car build

**Describe the solution you'd like**
Would it be possible to make an effect for clutch biting based on car parameters (maybe engine rpm and clutch rpm difference, clutch friction coeff, etc..)?

**Comment by SHWotever** [comment]
hi unfortunately this is not something I can catch easily, obviously above of beamng this would be interesting for any games, but I never found a way those last years.
