### ISSUE TITLE
GT7 - RPM effect is on before and after the race has finished

### ISSUE THREAD

**Issue by Akibahara** [SHWotever/SimHub#1484]
RPMS effect:

RPM vibrations remain on before and after the race is completed.   When you disable RPM it is gone so this is the issue with this effect.

**Simhub version** - 9.1.16

**Third party plugins** - disabled

**To Reproduce**
1.  Enable RPM effect
2.  Start a race, exit from the race
3. RPM vibrations stay on before and after the race is completed.  Felt on menu before the race and after best time and reward screens.

**Expected behavior**

RPM vibrations should not stay on before or after the race is completed.   It should only be felt during a race.

[SimHub.txt](https://github.com/SHWotever/SimHub/files/13625300/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! Thanks for the feedback, it's fixed for the next version,

Nicolas

**Comment by Akibahara** [comment]
Thanks a lot better now!  

But there is still some effects felt for a few sec right before a race.  After the race has ended on the results screen the effect is still there.

**Comment by SHWotever** [comment]
Hi ! Indeed it's normal, the game doesn't reports clearly the end or the start so I rely on a few physics metrics (velocity/acceleration) being frozen for a time to trigger the disconnect. This has to be long enough not to disconnect in case of telemetry lag/network lag (which is more likely to happen on a console)

**Comment by Akibahara** [comment]
ok thanks again for all your help !

**Comment by Akibahara** [comment]
This issue came back with the latest version 9.1.29

**Comment by SHWotever** [comment]
Hi ! Unfortunately I had to remove the hack, there was no difference between standing still or the pre-race/post race events. The telemetry does not make a clear difference

**Comment by Akibahara** [comment]
Hi, I reverted back to the older 9.1.28 and the issue is gone.  I'll use the older version for now.  Thanks.

**Comment by SHWotever** [comment]
Unfortunately there is no satisfying solution,  keeping telemetry alive while standing still in race is a priority in my opinion
