### ISSUE TITLE
OBS browser address is messing up specific Linear Gauges

### ISSUE THREAD

**Issue by SRDShredder** [SHWotever/SimHub#1485]
**Describe the bug**
The Linear Gauges are meant to fade into the middle to match the RPM's. They work as intended on the SimHub Dash Studio and they also work when I have OBS set to 'Display Capture' source. But when I set it to the 'Browser' source, it flips all of the Linear Gauges that go from right to left.

**SimHub version**
9.1.16

**To Reproduce**
1. Make an overlay with Linear Gauges matched to the RPM's, brakes and throttle.
2. Assign images to the Linear Gauges so they match up in colour to the middle
3. Click the 'Copy OBS browser address to clipboard'
4. Paste that link into the OBS Browser source that's set up.
5. Notice that it doesn't work correctly through Browser source, but does work through Display Capture source.

**Expected behaviour**
The Linear Gauges going from right to left should be wiping in like the ones going from left to right.

**Screenshots**
I've got a video showing the issue.
https://streamable.com/t4n9uh

**Log files**
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/13628197/SimHub.1.txt)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/13628198/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! Thanks for the report ! It's fixed for the next version. 

Nicolas
