### ISSUE TITLE
Simhub dash changes screens by itself

### ISSUE THREAD

**Issue by mcshoot** [SHWotever/SimHub#1487]
While I'm driving iRacing my simhub dash starts to change screens by itself
Sometimes it goes to circulating frenzy which is pretty much impossible to stop

**Simhub version**
9.1.16

**Third party plugins**
Steering wheel is Pokornyi GTE Pro V2, Simucube Steering motor and Fanatec V3 pedals
Dashes are based on RLB's dashes

**To Reproduce**
Just start driving and usually first corner while steering, braking and downshifting will cause dash to change screens

**Expected behavior**
That I would change the screen when ever I need to see another screen

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

	INFO	Starting SimHub v9.1.16 (build time : 08/12/2023 10:57:35)
	ERROR	Windows Defender Controlled Folder Access : likely to be disabled
	INFO	Administrator privileges : True 
	INFO	OS version : Microsoft Windows NT 10.0.22621.0, Windows 10.0.22621
	INFO	License status : Licensed (8ad0dbc5-90b8-40b7-af33-961df657eab3)
	INFO	Process priority : Normal
	INFO	87 game readers loaded
	INFO	(Re)Starting IRacing Game Manager and plugin manager
	INFO	Creating IRacing game manager (IRacingReader.IRacingManager)
	INFO	IRacing game manager created
	INFO	Creating plugin manager with plugins : SerialDashPlugin, AudioControlPlugin, JoystickPlugin, GraphicalDashPlugin, DevicesPlugin, KeyboardEmulatorPlugin, NextionPlugin, AutoBrightness, Checklist, ExtraInputProperties, IRacingExtraProperties, LogitechBatteryLevel, PersistentOdometer, SimHUDProjection, Sounds, TheManyFacedDash, Updater, ShakeITBSV3Plugin, ShakeITMotorsV3Plugin, ShakeItWindPlugin, LapHitoryPlugin, ThrustmastersPlugin
	INFO	Creating SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
	INFO	Creating SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
	INFO	Creating SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
	INFO	Creating SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
	INFO	Creating SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
	INFO	Creating SimHub.Plugins.Web.WebPlugin plugin
	INFO	Creating RSC.AutoBrightness.AutoBrightness plugin
	INFO	Creating RSC.Checklist.Checklist plugin
	INFO	Creating RSC.ExtraInputProperties.ExtraInputProperties plugin
	INFO	Creating RSC.iRacingExtraProperties.IRacingExtraProperties plugin
	INFO	Creating RSC.LogitechBatteryLevel.LogitechBatteryLevel plugin
	INFO	Creating RSC.PersistentOdometer.PersistentOdometer plugin
	INFO	Creating RSC.SimHUDProjection.SimHUDProjection plugin
	INFO	Creating RSC.Sounds.Sounds plugin
	INFO	Creating RSC.TheManyFacedDash.TheManyFacedDash plugin
	INFO	Creating RSC.Updater.Updater plugin
	INFO	Creating SimHub.Plugins.AudioControl.AudioControlPlugin plugin
	INFO	Creating SimHub.Plugins.InputPlugins.JoystickPlugin plugin
	INFO	Creating SimHub.Plugins.Devices.DevicesPlugin plugin
	INFO	Creating SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin plugin
	INFO	Creating SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin
	INFO	Creating SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin
	INFO	Creating SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin
	INFO	Creating SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin
	INFO	Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin
	INFO	Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin
	INFO	Creating SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin
	INFO	Creating SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin
	INFO	Initialising SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
	INFO	Initialising SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
	INFO	Initialising SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
	INFO	Initialising RSC.AutoBrightness.AutoBrightness plugin
	INFO	Starting plugin : RSC - Auto Brightness 1.2.1
	INFO	Initialising RSC.Checklist.Checklist plugin
	INFO	Starting plugin : RSC - Checklist 1.0.5
	INFO	Initialising RSC.ExtraInputProperties.ExtraInputProperties plugin
	INFO	Starting plugin : RSC - Extra Input Properties 1.1.26
	INFO	Initialising RSC.iRacingExtraProperties.IRacingExtraProperties plugin
	INFO	Starting plugin : RSC - iRacing Extra Properties 2.2.5
	INFO	Initialising RSC.LogitechBatteryLevel.LogitechBatteryLevel plugin
	INFO	Starting plugin : RSC - Logitech Battery Level 1.2.0
	INFO	Initialising RSC.PersistentOdometer.PersistentOdometer plugin
	INFO	Starting plugin : RSC - Persistent Odometer 1.0.4
	INFO	Initialising RSC.SimHUDProjection.SimHUDProjection plugin
	INFO	Starting plugin : RSC - SimHUD Projection 1.1.5
	INFO	Initialising RSC.Sounds.Sounds plugin
	INFO	Starting plugin : RSC - Sounds 1.0.13
	INFO	Initialising RSC.TheManyFacedDash.TheManyFacedDash plugin
	INFO	Starting plugin : RSC - The Many Faced-Dash 1.4.0
	INFO	Initialising RSC.Updater.Updater plugin
	INFO	Starting plugin : RSC - Updater 1.0.2
	INFO	RSC.Updater - Checking for update
	INFO	RSC.Updater - RSC_Setup version : 1.3.2
	INFO	RSC.Updater - RSC_Setup update available : False
	INFO	RSC.Updater - Minimum SimHub version required : 9.0.0
	INFO	Initialising SimHub.Plugins.AudioControl.AudioControlPlugin plugin
	INFO	Initialising SimHub.Plugins.Devices.DevicesPlugin plugin
	INFO	Loaded device : Generic Vocore Screen (4",4.3",5",6.8") (Generic Vocore Screen (4",4.3",5",6.8"), E5D2A652-A53F-414C-88FE-BB92B59F3666)
	INFO	Initialising SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin
	INFO	Initialising SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin
	INFO	Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin
	INFO	Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin
	INFO	Initialising SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin
	INFO	Initialising SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
	INFO	Initialising SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
	INFO	Initialising SimHub.Plugins.InputPlugins.JoystickPlugin plugin
	INFO	Initialising SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin
	INFO	Initialising SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin plugin
	INFO	Initialising SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin
	INFO	Starting Arduino in Single USB mode
	INFO	Initialising SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin
	INFO	Initialising SimHub.Plugins.Web.WebPlugin plugin
	INFO	Web plugin listening to 8888 (User friendly port)
	INFO	Web plugin suggested IP :192.168.1.106
	INFO	Plugin manager correctly initialised
	INFO	Loading plugins controls
	INFO	JoystickManager : Found PE_GTE-PRO_V2, T500_RS_Gear_Shift, Simucube_2_Pro, FANATEC_ClubSport_Pedals_V3
	INFO	Game successfully loaded
	INFO	Game connected
	INFO	All time best found : 00:02:18.8430000 recorded at 12/12/2023 5:55:34 PM
	INFO	Device Status changed : Generic Vocore Screen (4",4.3",5",6.8") : Disabled
	INFO	Starting VOCORE remote USB display process
	INFO	RSC.iRacingExtraProperties - Reference lap file found: spa up.Audi R8 LMS EVO II GT3.json
	INFO	RSC.iRacingExtraProperties - Reference lap quality: Average distance between points: 9.99m - >20m: 0/694 - Max: 19.99m
	INFO	Device Status changed : Generic Vocore Screen (4",4.3",5",6.8") : Scanning
	INFO	Screen connected : model D500FPC9373-C 854x480, size 854x480, id 7B-07-14-0B-2E-1E-00-03, leds 0
	INFO	VOCORE : Creating browser instance
	INFO	VOCORE : Loading http://127.0.0.1:8888/Dash?v=3861#Geezer%20Racing%202|nocontrols|usbd480
	INFO	Device Status changed : Generic Vocore Screen (4",4.3",5",6.8") : Connected
	INFO	Web client connected : 127.0.0.1, SimHubBrowser
	INFO	Active dash on 127.0.0.1 : Geezer Racing 2
	INFO	Found one device on COM2 named {
  "ConnectedModel": "j",
  "Features": "GNIJPX",
  "TM1638ModulesCount": 0,
  "RGBLedsCount": 16,
  "UniqueId": "94462502-3d19-4a41-bb98-47aa4e88991e",
  "DeviceName": "PE GTE PRO V2 LED",
  "PortName": "COM2",
  "HasBoost": 0,
  "HasSpeedo": 0,
  "IsBluetooth": false,
  "HasTacho": 0,
  "HasI2CLcd": false,
  "HasRGBMatrix": false,
  "ExpandedFeatures": [
    "mcutype",
    "keepalive",
    "Gear"
  ],
  "MaxAheadDatagrams": 0,
  "DatagramMaxLength": 0,
  "MCUModel": "ATmega328P",
  "ReceivedDatagramsCount": 0
}
	INFO	Switching device named PE GTE PRO V2 LED to speed level 11 on COM2
	INFO	Switching device on port COM2 to speed level 11, 115200 bauds
	INFO	Connected to device on COM2 named PE GTE PRO V2 LED
	INFO	BassShakers: Requiring audio interfaces rebuild after game start or audio settings change
	INFO	Old map quality score : 8 / New map quality score : 6
	INFO	New fuel stat aggregated 3.86/lap

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
I have tried to clear from devices / controls / all buttons, no effect what so ever
I have turned off from Controls and event / controllers status everything else than my steering wheen, no effect what so ever

**Comment by SHWotever** [comment]
Hi ! This looks like a faulty button or a squeezed touchscreen. But you already disabled the explicit inputs I would reduce it right away to the touchscreen. Can you try to disable touchscreen in the dispatch settings? 

Could you also join the log files as requested in the template ? 

 ```
Log files
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

Log files don't show any activity

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
```

**Comment by SHWotever** [comment]
Another point, if disabling touch helps, it's likely that the screen or touch is faulty and is sending lot of  unexpected touch data. It might affect usb bandwidth and display refresh rate.

**Comment by mcshoot** [comment]
Hi, big thanks for helping me. It has worked well for 6 months and now suddenly started to act.
It seem to be a touch screen bit squeezed between the frame. 
Just tooked the steering wheel to pieces and made more space for screen.

TMc
