### ISSUE TITLE
[GT7] Fuel Calculations

### ISSUE THREAD

**Issue by etsmc** [SHWotever/SimHub#1488]
when in a race with fuel usage enabled in GT7 the following do not appear to be calculated
Computed.FuelLitersPerLap
Computed.Fuel_RemainingLaps
Computed.FuelRemainingTime

SimHub Version 9.1.9

**Comment by SHWotever** [comment]
Hi ! Thanks for the feedback, it's fixed for the next version,
GT7 was lacking some critical data to compute accurate statistics (lap progression) I added a basic per lap tracking for the next version 
Nicolas

**Comment by etsmc** [comment]
will this also work for Computed.FuelRemainingTime ?
thanks for looking at it so quickly.
