### ISSUE TITLE
WMI Provider Host (32bit) using 15-18% CPU and logging an error EVERY second in Event Viewer.

### ISSUE THREAD

**Issue by ghowse** [SHWotever/SimHub#1489]
Windows 10 Task Manager shows WMI Provider Host (32bit) consuming 15 to 18% CPU when SimHub is running.  Also, Event Viewer is logging a WMI-Activity Operational "Error" event continuously at 1 second intervals

**Simhub version**
9.1.16 Licensed version

**Third party plugins**
None.  Only enabled "Dash Studio" and Shakeit Motors.  Bug is still apparent with these plugins disabled.

**To Reproduce**
1. Go to 'Task Manager'
2. Click on 'CPU' header to sort processes.  WMI Provider Host is one of the highest consumers of CPU resources, around 15-18% 

1. Go to 'Event Viewer'
2. Navigate to 'Applications and Services Logs>Microsoft>Windows>WMI-Activity>Operational'.   
3. A new 'Error' entry is created each second

**Expected behavior**
WMI Provider Host immediately drops to 0% when I exit SimHub.  SimHub is costing my CPU a 15% burden which contributes to frequent ">99% CPU" messages in Assetto Corsa

**Screenshots**
![taskmgr](https://github.com/SHWotever/SimHub/assets/48821460/4be841de-d8fe-4df1-bb0f-8a2219a04ca6)
![eventvwr](https://github.com/SHWotever/SimHub/assets/48821460/fbf30e41-3056-4ea2-8407-a4a2d9aa071c)

**Log files**
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/13654693/SimHub.1.txt)

**Additional context**
I have followed the steps necessary to rebuild the WMI Repository https://techcommunity.microsoft.com/t5/ask-the-performance-team/wmi-rebuilding-the-wmi-repository/ba-p/373846

I have also followed the steps shown here https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-prevent-anymore-wmi-activity-errors/16d14557-9fd5-4e04-87b4-1325a234806a

**Comment by ghowse** [comment]
Just noticed the "triage" tag.  Might have been auto-tagged.  Triage is somewhat more urgent than my bug (which might be Microsoft's doing?)

**Comment by SHWotever** [comment]
Hi ! Triage is an automatic tag indeed allowing to spot what I've not analysed yet ;)

About this error it looks like a WMI metric i broken/missing, I found a few occurence of it on the microsoft forums but with no clear solution. Based on what I've seen repair/rebuild is not enough, based on this
https://serverfault.com/questions/894620/wmi-win32-perfformatteddata-perfos-memory-class-doesnt-exist  (and i've seen it somewhere else too)  could solve it : 
```
cd %windir%\system32\     
lodctr /R     
cd %windir%\sysWOW64\     
lodctr /R
```

As alternative you can disable the system informations metrics here and restart SimHub, it will stop trying to grab CPU load informations : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/94eba85e-55b9-46f6-945e-3b6242662bd5)

For the next version I added an automatic "fuse" : if those metrics fails a couple of time in a row they will get automatically disabled to avoid excessive WMI cpu usage.

**Comment by ghowse** [comment]
First of all, thanks for responding so quickly.

I am cautiously confident that these commands

cd %windir%\system32\     
lodctr /R     
cd %windir%\sysWOW64\     
lodctr /R

have done something.  The only change is that the first command failed on the first try (C:\WINDOWS\system32>lodctr /R

Error: Unable to rebuild performance counter setting from system backup store, error code is 2).

The second one was successful so I tried the first one again and it was successful too.

WMI Provider host is now on 0% and there are no errors in Event Viewer.

Looks like a fix but I'll reboot and do some more checks.  Will report back in a while.

Again, many thanks.
Cheers

**Comment by ghowse** [comment]
Rebooted intact.  Here is the SimHub log.
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/13659036/SimHub.1.txt)

**Comment by SHWotever** [comment]
Hi ! I forgot to mention that the commands should be ran with administrator privileges. without it returns an error 2 indeed.

**Comment by ghowse** [comment]
Yes, I ran it with admin privs.
