### ISSUE TITLE
Leoxz plugin issue

### ISSUE THREAD

**Issue by Ryane37** [SHWotever/SimHub#1490]
Have noticed when using the Leoxz plugin any other external displays start flickering and dashboard stutter on the wheel.
Have done 3 tests to check:

1) Simhub with Leoxz plugin enabled - display flickering on external dash and stutter on the Leoxz wheel display on all dashboards.

2) Disabled Leoxz plugin restarted simhub everything working fine displays and dash smooth.

3) Re enabled Leoxz plugin again restarted simhub same as before external dash not working flickering and within game all dashboards lag within the display on the Leox wheel.

**Comment by SHWotever** [comment]
Hi ! Leozx plugin is a third party plugin, I can't troubleshoot or fix it. For issue created by this plugin does not hesitate to contact them directly https://www.leoxz.com/pages/message-1 

Nicolas
