### ISSUE TITLE
[Feature request] New properties: Suggested gear, and Warning count

### ISSUE THREAD

**Issue by dexter323i** [SHWotever/SimHub#1493]
Hi!

Tite tells everything, but I can give you some more explanation.

**Suggested gear:** It is a very important info for inexperienced drivers. What is the recommened gear in the upcoming turn. F1 has this 
 in PacketCarTelemetryData:
int8_t                m_suggestedGear;       // Suggested gear for the player (1-8)  0 if no gear suggested
Gran Turismo also has it:
byte Gears; // Lower 4 bits: CurrentGear; upper 4 bits: SuggestedGear
maybe other games too.

**Warning count:** I have talked to F1 sim racers, and this is a key value! Few warnings mean they can drive a bit more bravely, but if you have too many warnings, then you should be extra careful. Use case scenario: You are at the very end of the race, you have no warnings yet, and you are only one "corner cutting" away from a successful overtaking... :)
In F1 - LapData packet:
uint8_t    m_totalWarnings;             // Accumulated number of warnings issued

I don't know other games, but someone told me ACC has track limit warnings, and iRacing has a thing called incident count. These might be also shown here as a warning count.

**Comment by SHWotever** [comment]
Hi ! Those data are specific to a very few games on the 80+ supported. Since it's not widely available across games you can access it directly for a game by using raw data : 

![image](https://github.com/SHWotever/SimHub/assets/2207331/c109c8d2-3a3c-41fb-8066-b0911465d7ad)
