### ISSUE TITLE
WebPageItem not being displayed on HTML renderer

### ISSUE THREAD

**Issue by suppoo** [SHWotever/SimHub#1494]
**Describe the bug**
HTML Renderer does not display webpages properly, just black background. WPF renderer works fine. Applies to physical DDUs too as most of them use HTML renderer

**Simhub version**
9.1.18

**To Reproduce**
1. Create / use dashboard with WebPageItem
2. Switch to HTML renderer and WebPage is no longer displayed properly

**Expected behavior**
Display the webpage just like with WPF renderer

**Log files**
Attached log file with debug on. Nothing really popped up there tho.

[2023-12-17 04:03:18,908] INFO - Starting dashboard DashTemplates\JRT Map\JRT Map.djson (WPF) : TopMost, No window activate
[2023-12-17 04:03:19,093] DEBUG - Dash refresh skipping started, previous frame not finished
[2023-12-17 04:03:21,159] DEBUG - Dash refresh skipping started, previous frame not finished
[2023-12-17 04:03:25,741] INFO - Web client connected : 127.0.0.1, SimHubWebView2
[2023-12-17 04:03:25,748] INFO - Active dash on 127.0.0.1 : JRT Map
[2023-12-17 04:03:27,010] INFO - Disposing FMOD output for Speakers (USB2.0 Device)
[2023-12-17 04:03:53,890] INFO - Web client disconnected : 127.0.0.1 JRT Map

^^^ part where I changed from WPF to HTML

**Comment by SHWotever** [comment]
Hi !

Do you have the adress of what you are trying to show ? Or at least a dump of the HTTP headers ? When running in WPF mode the browser will be a dedicated instance not hitting any specific restrictions. But when using the HTML mode in order to "nest" the webview in the page it needs to be an iframe and it will respect the "embedded" website restrictions in that matter like https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/X-Frame-Options or https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by SHWotever** [comment]
Hi ! Thnaks that was the headers indeed, as is I can't spot any explicit locks.

I did a quick test with https://time.is/ which has no locks, it rendered correctly : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/13043f84-63e9-4d7e-92b6-57b4d96b7132)

And with JRT track map page.
![image](https://github.com/SHWotever/SimHub/assets/2207331/bd97ddfd-3c1c-4d68-b5dc-eca4569b33b9)

Maybe just a little trick, HTML requires to have the files properly saved when switching dynamically from wpf to html wpf is always up to date (loaded from memory) while html needs to be saved first (it's done automatically when starting the dash from the editor if the last render engine is html.

**Comment by suppoo** [comment]
Okay it seems that time.is is working for me too in HTML renderer! Just gotta figure out why JRT map isnt working in my end.
Thanks for the help with troubleshooting and sorry for false issue!

**Comment by suppoo** [comment]
Okay it seems that HTML Renderer works with JRT now when I use my local IP address instead of file path. Just FYI if someone else has same issue

**Comment by SHWotever** [comment]
> Okay it seems that HTML Renderer works with JRT now when I use my local IP address instead of file path. Just FYI if someone else has same issue

Ah make sense, if you point the local file everything will be wrong, it must be served by jrt (and it's the same for PHP, .net , etc...)
Thanks for the feedback! Mystery closed ;)
