### ISSUE TITLE
Recognize Moza wireless wheels like Simucube and Fanatac as individual controllers

### ISSUE THREAD

**Issue by SteveSobka** [SHWotever/SimHub#1495]
In the Control Mapper, SimHub detects the Moza base and any wheel connected to it as 'the same wheel'.  Therefore, I cannot correctly bind the buttons of the source controller as each wheel has a different buttons and changing any of them will mess up the other wheel.  Some buttons (like shifters) are identified as the same button number wheel to wheel but not all.  It would be great if each wheel was seen as it's own device and not just the Moza Direct Drive base.

**Comment by SHWotever** [comment]
Hi !

Currently there is no sdk available allowing to to extract the current wheel being plugged. They promised such sdk for around October 23, but as far as I can tell it's not available yet. 

In the wait there is nothing I can do I'm sorry.

**Comment by HickBoy** [comment]
There is a BETA SDK released at the end of November 2023.  It's here: https://drive.google.com/file/d/1K1D19zgEtHBa32r71dalgh2gpUbAp5nV/view?usp=sharing

From the Moza Discord:
![image](https://github.com/SHWotever/SimHub/assets/3321706/5961de3c-28c9-4abc-9eeb-779a8516b782)

**Comment by optikalblitz** [comment]
Is it possible to resurrect @SteveSobka's request? Their SDK appears to be out of beta and I'd love if I could map my two different Moza wheels correctly! Thanks for considering, @SHWotever 

 https://mozaracing.com/moza-sdk

**Comment by SHWotever** [comment]
Hi, unfortunately the SDK still doesn't give any information about the wheel model being connected. You can only know the major device family (wheel, pedals... ). 
enum PRODUCTTYPE
{
    PRODUCT_WHEELBASE = 0,
    PRODUCT_STEERINGWHEEL,
    PRODUCT_DISPLAYSCREEN,
    PRODUCT_PEDALS,
    PRODUCT_METER,
    PRODUCT_ADAPTER,
    PRODUCT_HANDBRAKE,
    PRODUCT_GEARSHIFTER,
    PRODUCT_UNKNOWDEVICE,
};

With this information this still doesn't allow to make a deeper recognition.

**Comment by optikalblitz** [comment]
Thanks so much for the response; totally understand. I hope Moza can provide a better SDK one day to get on-par with other wheels that can be properly mapped! Cheers.
