### ISSUE TITLE
TrackLength is sometimes wrong in Richard Burns Rally

### ISSUE THREAD

**Issue by fixfactory** [SHWotever/SimHub#1496]
**Describe the bug**
The property `DataCorePlugin.GameData.TrackLength` will sometimes display a wrong value of `25.82192` instead of the actual stage length in the game Richard Burns Rally (RSF version with NGP).

When the bug occurs, the wrong value will be returned until the stage is ended. It reproduces about 1 out of 10 stages. It reproduces randomly on any stage.

I confirmed with a Wireshark UDP capture, and a simple program reading the UDP telemetry, that the UDP data sent by the game is correct.

**Simhub version**
9.1.15

**To Reproduce**
1. In Sim-Hub, make a simple overlay displaying `DataCorePlugin.GameData.TrackLength` (included below)
2. Start Richard Burns Rally (RSF version with NGP)
3. Drive the Rally School Stage 10 times
4. Notice that 1 out of 10 times, the Track Length displayed is `25.82192` instead of `2263.21`

**Expected behavior**
The property `DataCorePlugin.GameData.TrackLength` should always return a value of `2263.21` for that stage.
In terms of telemetry data, the TrackLength should be calculated as `stage_.driveLineLocation_ + stage_.distanceToEnd_` 

**Screenshots**
Bug:
![bug](https://github.com/SHWotever/SimHub/assets/5952846/8c68eb6b-5ab4-424a-bef3-684187b723bd)

No-bug:
![no-bug](https://github.com/SHWotever/SimHub/assets/5952846/2bb9d004-c173-4a1c-a210-bb690590f41f)

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/13705987/SimHub.txt)

**Additional context**
Overlay used: [Ben's Official Rally Odometer v2.zip](https://github.com/SHWotever/SimHub/files/13706025/Ben.s.Official.Rally.Odometer.v2.zip)
Sim-Hub replay recordings: [RBR-TrackLength-Bug-Replays.zip](https://drive.google.com/file/d/113L5Vz-rGs6XCZ7ASFI1IZeFr4qjwO2v/view?usp=sharing)

**Comment by SHWotever** [comment]
Hi !

Thanks, the data was collected from memory and frozen UDP is coming too late), but apparently if it's read a little too early it sometimes miss the correct values. I've added a little delay after the start of the race so the game has time to update those values.

**Comment by SHWotever** [comment]
Hi !
The fix has been released : [simhubdash.com/download-2](https://www.simhubdash.com/download-2/)
