### ISSUE TITLE
Arduino constantly disables in game when 8x8 screen enabled

### ISSUE THREAD

**Issue by Borjec1** [SHWotever/SimHub#1498]
**Describe the bug**
Good day to everybody. I sell custom made indicators for over 2 years right now and last 3-4 days i have big problems with 2 of my buyers.

Indicator is based on 8x8 gear indicator max7219 + 16 leds ws2812 2 plates. All 2 years everything worked perfect, right now i have issue - out of game everything works ok, neutral can be lit for hours, "led test" for 2812 plates work ok, everything no problem. When they enter the game (both tried dirt 2, ac, acc and mb something else) - 2 gear changes and arduino disconnects from simhub (im pretty sure not PC, because no sounds etc), then reconnects. We tried with both clients to change simhub versions, arduino drivers, cables, disable hubs, 2.0, 3.0 ports, 4 different PCs e.t.c. - nothing helps. If we totally disable 8x8 screen - all ok. If we enable only 8x8 screen - everything becomes like written above. If 8x8 + 16 leds - like written above.

**Simhub version**
Last and not last, tried everything

**To Reproduce**
1. Enable 8x8 screen
2. Go to game
3. Crash almost everytime when 2 changes to 3

Logs when it disconnects are attached
[SimHub.log](https://github.com/SHWotever/SimHub/files/13719421/SimHub.log)

**Comment by Borjec1** [comment]
So additional info. Second buyer tried swapping matrix fonts little deeper and found out that half of fonts dont even let arduino enable, it instantly disconnects when "connected" becomes green. Another half of fonts lets it enable, neutral pops up, but in game crashes. In his case "Traditional 6x4" and "Pixel 5x5" works ok.

**Comment by Borjec1** [comment]
+Some info about our case.

Animation font - **not** working
Custommatrixfont 6x4 - working
Custommatrixfont 8x8 - **not** working
Pixel 5x5 - working
Small 5x4 - working
Square large 8x8 - **not** working
Square 6x6 - **not** working
Thick hollow 8x8 - **not** working
Thick 8x8 - **not** working
Traditional large 8x6 - **not** working
Traditional 6x4 - working

**Comment by SHWotever** [comment]
Hi !  Based on the log and the symptoms (only the fonts with very few pixels/changes lighting up) . I would think about an usb power/bandwidth issue. The log shows that the Arduino stops responding. As you pointed already this is not linked to a simhub version (those code parts have no changed for a very long time).

I would check the windows update history to check for any drivers related to usb, at the end no matter if it's directly connected through motherboard board ports or usb hub, it has to go through the motherboard. 

Does it had an external power source? 8x8 Ws2812b combined to additional display must be really playing with the limits. I guess you have an external power supply to get power for everything? https://github.com/SHWotever/SimHub/wiki/Arduino--Setup#powering-considerations

How does it behaves when matrix brightness is set to a very low value?

**Comment by SHWotever** [comment]
Can you also tell me you are using Arduino boards with legit usb to ttl chip ? Lately fake ch340 have been seriously hit by some drivers update. I have a detection for a few specific fake chips inside simhub, but some of them might escape it. Can you confirm the ch340g chip is official? It should show the WCH logo as well as the name. Fake chips are unreliable overtime and it gets even worse since WCH is fighting it with "killer drivers"
![shopping](https://github.com/SHWotever/SimHub/assets/2207331/83068ab0-a3be-4198-8c34-755d1b658164)

**Comment by SHWotever** [comment]
Hi ! I double checked using this setup : 
- an arduino nano v3 (legit ch340 chip) 
- max7219 matrix (I used a 8*32, but it's the same, except I had to set it for 4 modules for the demo so it does not spread alternatively on the 4) But I also did the test with "code"
- 16 wd2812b leds enabled even if they are not plugged, with a typical led profile with startup animation, rpms ... ensuring a "normal" communication activity for that part

I could not spot any issues, as you can see I can use any of the fonts without disconnect : https://www.youtube.com/shorts/QR60-VDeaoY

Could you try to enable the matrix on some free pins ? IE if you are using the default D3 D4 D5 you can use D7/D9/D9. If the disconnect continues that will allow to ensure the matrix is not faulty. Otherwise it's likely to be an issue with the matrix, if you have a few fonts not working, that might be an issue with some specific "rows" or "columns" of the matrix. At this point that's my best bet. This test will allow to check that quickly. 

Overall by looking in details to your working/not working list I can spot a pattern about the used rows and columns,

With a quick reordering :
```
Custommatrixfont 6x4 - working
Pixel 5x5 - working
Small 5x4 - working
Traditional 6x4 - working
```

```
Animation font - not working (8*8 space used)
Custommatrixfont 8x8 - not working 
Square large 8x8 - not working
Square 6x6 - not working
Thick hollow 8x8 - not working
Thick 8x8 - not working
Traditional large 8x6 - not working
```

It looks like only the small fonts are working which tends to add another clue about a faulty matrix (If i'm not wrong that could be column #2 which is the common point about the "not working fonts").

**Comment by Borjec1** [comment]
> Hi ! I double checked using this setup :
> 
> * an arduino nano v3 (legit ch340 chip)
> * max7219 matrix (I used a 8*32, but it's the same, except I had to set it for 4 modules for the demo so it does not spread alternatively on the 4) But I also did the test with out of box "code"
> * 16 wd2812b leds enabled even if they are not plugged, with a typical led profile with startup animation, rpms ... ensuring a "normal" communication activity for that part
> 
> I could not spot any issues, as you can see I can use any of the fonts without disconnect : https://www.youtube.com/shorts/QR60-VDeaoY
> 
> Could you try to enable the matrix on some free pins ? IE if you are using the default D3 D4 D5 you can use D7/D8/D9. If the disconnect continues that will allow to ensure the matrix is not faulty. Otherwise it's likely to be an issue with the matrix, if you have a few fonts not working, that might be an issue with some specific "rows" or "columns" of the matrix. At this point that's my best bet. This test will allow to check that quickly.
> 
> Overall by looking in details to your working/not working list I can spot a pattern about the used rows and columns,
> 
> With a quick reordering :
> 
> ```
> Custommatrixfont 6x4 - working
> Pixel 5x5 - working
> Small 5x4 - working
> Traditional 6x4 - working
> ```
> 
> ```
> Animation font - not working (8*8 space used)
> Custommatrixfont 8x8 - not working 
> Square large 8x8 - not working
> Square 6x6 - not working
> Thick hollow 8x8 - not working
> Thick 8x8 - not working
> Traditional large 8x6 - not working
> ```
> 
> It looks like only the small fonts are working which tends to add another clue about a faulty matrix (If i'm not wrong that could be column #2 which is the common point about the "not working fonts").

As i said before - 3 different matrix were tested. And all of them were tested fully enabled for 64 pins, no problems until enabling "bad" fonts. Dont know what can be wrong in this matrix and arduino's which i use 1 year+. I'll get new arduinos and 8x8 plates soon, we'll see. Right now both of my clients 2+ days play with fonts written above - 0 problems.

**Comment by Borjec1** [comment]
Sooo i think problem is solved. Clients disabled everything in "rgb matrix" tab, looks like all fonts are working. Very strange, because as i know it did not affect 8x8 little screens before. Am i wrong?

**Comment by Borjec1** [comment]
Can you test your "setup" on not licensed simhub?

**Comment by SHWotever** [comment]
I just did a test with unlicensed, and it gave the same result, all fonts were working. And I left the licensed version running for a few hours this afternoon (with a replay) with no issues neither.

I really recommend doing the test I suggested (setting the matrix to free pins), that will rule out any doubts about simhub communication. From experience when buying in batch (it looks like it's what you did, if a part is faulty, others are likely to have the same fault). From the symptoms my feel gets oriented toward the matrix specifically. The font does not matter much it's just transformed to the same amount of data representing the on/off states of each row, but if a specific column/row is faulty then changing the font will trigger it.

By the way, please confirm me you are not selling anymore devices with Arduino bundled with fake chips ? In my guide, and when being asked about it I strongly recommend to ask for a refund when being victim of those fake chips.

**Comment by Borjec1** [comment]
> I just did a test with unlicensed, and it gave the same result, all fonts were working. And I left the licensed version running for a few hours this afternoon (with a replay) with no issues neither.
> 
> I really recommend doing the test I suggested (setting the matrix to free pins), that will rule out any doubts about simhub communication. From experience when buying in batch (it looks like it's what you did, if a part is faulty, others are likely to have the same fault). From the symptoms my feel gets oriented toward the matrix specifically. The font does not matter much it's just transformed to the same amount of data representing the on/off states of each row, but if a specific column/row is faulty then changing the font will trigger it.
> 
> By the way, please confirm me you are not selling anymore devices with Arduino bundled with fake chips ? In my guide, and when being asked about it I strongly recommend to ask for a refund when being victim of those fake chips.

I live in Russia, people here aren't ready to pay x10 price for original arduino. I have 500+ sells, 300+ 5 star feedback. This problems began only in last 3-4 orders.

**Comment by WeisyDj** [comment]
> Author

did you tried with external power'''''? you should follow the guide [https://github.com/SHWotever/SimHub/wiki/Arduino-RGB-Matrix](url) you can see about 500mAh max current, you are using tons of rgb leds each can suck 60 mAh
follow the guide, vcc(on the leds and the matrix 8x8, not arduino) to external power supply, and common gnd
