### ISSUE TITLE
[Feature request] Ambient lights - add selection of layouts

### ISSUE THREAD

**Issue by vick-k** [SHWotever/SimHub#1499]
**Is your feature request related to a problem? Please describe.**
I love the ambient lights plugin, but it takes time to set up when I am changing to a different car. Because I am resizing and rearranging the areas for each individual car, it becomes annoying at some point when you have to do the same thing over and over again.

**Describe the solution you'd like**
Add the option to save the current layout. Also, of course need to have a list with all saved layouts and choose the one you want, depending on the car you are going to drive.

**Describe alternatives you've considered**
Because the Ambient lights feature is experimental, and the above implementation will take time, if there is an easier implementation I will still appreciate it. For example, the current layout settings to be saved in a .json or some other config file. This way I can make copies of the config file and just use the one I want, depending on which car I am going to drive.

**Comment by marklloyd** [comment]
Could this be implemented in a way that auto switches on car detection?

Additionally, having some controls to map Lights on / off would be convenient.

**Comment by SHWotever** [comment]
Hi !

Area profiles have been added to the latest release as well as a series of bindable actions around : https://www.simhubdash.com/download-2/
