### ISSUE TITLE
RBR additional data

### ISSUE THREAD

**Issue by maorc287** [SHWotever/SimHub#1503]
I made a SimHub pluging to get additional data from Richard Burns Rally, but it is pretty slow and inefficient.
Can you implement it directly to SimHub?
Thanks 

maorc

**Comment by SHWotever** [comment]
Hi !

It depends of the data and how tight it's related to various mods. I see you have shared your code, I indeed see why you are having performance issues, but the address can be reusable.

Can you confirm all the data are working on a "vanilla" rbr. Currently I exclusively use direct memory reading for the original game memory adresses as it could be broken by mods updates

**Comment by maorc287** [comment]
Yes I tested it on “vanilla” RBR and its working fine

**Comment by SHWotever** [comment]
It's added for the next version ! Thanks for the "pointers" ;)

**Comment by maorc287** [comment]
Great! Thanks!
