### ISSUE TITLE
Simhub interferes with Amanero ASIO driver

### ISSUE THREAD

**Issue by Kurohitsugi9** [SHWotever/SimHub#1504]
**Describe the bug**
In short, when in Foobar I have an error saying "couldn't initialize ASIO driver", I have to stop Simhub to make it works again.
It's an Amanero Combo 384 USB (https://amanero.com/).

**Simhub version**
Simhub 9.1.1.19

**Third party plugins**
Only have Romainrob persistent odometer and updater. Others are from Wotever. Also had to disable Audio Control as it induced latency and wierd crackling on highest bitrate (384khz) and bit depth (32bits).

**To Reproduce**
1. Start a race using Assetto Corsa for instance using Simhub
2. Stop AC 
3. Start Foobar and start a music whatever format
4. Get foobar ASIO error
5. Stop Simhub
6. Play normally any song

**Expected behavior**
Simhub shouldn't impact driver audio unless on purpose specific plugin (bass shaker...)

 
 
**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

[SimHub.txt](https://github.com/SHWotever/SimHub/files/13799387/SimHub.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/13799388/SimHub.1.txt)
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/13799389/SimHub.2.txt)
[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/13799390/SimHub.3.txt)

**Additional context**

**Comment by SHWotever** [comment]
Hi ! When all audio related plugins are disabled it should not interfere with asio in  any direct ways. However with a 384khz, I guess it's highly usb endpoints demanding. I see that you are using in parallel a vocore screen which is a big consumer too as well as a couple of extra Arduinos. Could you ensure that you are not overloading your usb root ? Tools like usbdview will allow you to see how your devices are spread across each motherboard usb root. 

Alternatively since it looks to be a custom sound card, could you check that it doesn't show any usb serial port ? In such case this guide shows how to exclude it from Arduino scan : https://github.com/zegreatclan/SimHub/wiki/Troubleshoot-other-hardware-Serial-ports-conflicts

**Comment by Kurohitsugi9** [comment]
Hey, thanks for your answer. I'll investigate further using your tool and will provide feedback.

**Comment by Kurohitsugi9** [comment]
Hi there! I've drilled a little more into this. 
I get into the ASIO error only if Audio Control.
![image](https://github.com/SHWotever/SimHub/assets/27956510/1dc7d002-51e7-4d7e-b982-083e0afa4f3c)
Through usbdview I don't see any kind of trouble. Yes they're tons of different usb device but everything's ok as long as the plugin is off. 
The error is easily reproductible just by turning it on again.
I don't know if you want to troubleshout this any deeper, if yes I can provide you anything that can help you.

Thanks and happy new year!

**Comment by Kurohitsugi9** [comment]
Additionally, I've excluded all non required serial ports, no change though.

**Comment by SHWotever** [comment]
I guess your sound card does not support both recording with wasapi and playing with asio at the same time (maybe it needs exclusive access). Indeed I don't think it's a true issue. That's a reason why I made Simhub use a plugin architecture so it's possible to disable a whole feature in case of conflicts ;)

Thanks for your feedback !

Nicolas

**Comment by Kurohitsugi9** [comment]
Thank you for your answer. What is interesting, is the fact that I don't use both at the same time. 
In other words, it's like ASIO driver can't get exclusive mode back once wasapi through simhub has been used.
