### ISSUE TITLE
 Problem Simagic Haptic pedals Reactor Rfactor2 SimHub licensed

### ISSUE THREAD

**Issue by Cyril3333** [SHWotever/SimHub#1510]
I have a Simagic P2000 with Haptic Reactor pedals on the brake.

All games work perfectly with SimHub licensed except Rfactor2 which only works with SimHub free.
When i activate the license for SimHub , Haptic Reactor pedals no longer works, there is very slight vibration but too weak to be noticable.

I use the wheels lock setting.

Simhub version 9.1.12

Thanks for your help

**Comment by SHWotever** [comment]
Hi ! 

The wheel lock on RF2 is highly dependent of the assist in the game and can last a very short time, on the licensed version it reflects better the subtilities. 

However there was an issue with the p2000 which is much more linear that the p1000 I had for my test and which was hiding a gain bug. Forthe next version the max gains are doubled allowing to scale better and stronger the effect.

Alternatively if you were using the free version before I would also recommend to reset the calibration to deal with the update frequency change :

![image](https://github.com/SHWotever/SimHub/assets/2207331/c91e3f66-31e5-418a-a848-adcd87b8494d)

**Comment by SHWotever** [comment]
Hi !
The fix about p2000 power has been released : https://www.simhubdash.com/download-2/

**Comment by Cyril3333** [comment]
Hi !

Thank you for your fast response and the quality of your work.
The haptic feedback management for the P2000 is a success. I won't be able to do without itto drive cars without ABS.

I made the update 9.1.20 and reset calibration.
I tested different games and different cars with ABS and Without ABS to be objective as possible.

For Rfactor2, it's better. But even when i play barefoot, vibrations are still too low to give information.
I didn't find any solutions in settings.

Is it possible to increase gain further ?

**Comment by SHWotever** [comment]
Hi ! Rfactor 2 does not give abs data actually, there is an experimental feature which can be enabled here, but it relies highly of the official RF2 cars physics so it can miss other cars :
![image](https://github.com/SHWotever/SimHub/assets/2207331/c43a5921-0c31-4584-a0d0-f3ec7f3a16c4)


Overall abs pulses are always 100% except when the car is too slow, then it will be linearly dampened up to 0 below 30kmh,

Overall if you want to keep a minimum force for the effects you can tune the output here and set it :
![image](https://github.com/SHWotever/SimHub/assets/2207331/2fe55e7a-c4f8-4a6c-8f1c-249feb160745)
