### ISSUE TITLE
[Bug] Simucube 2 - Intermittent freezing of the steering input when second Arduino was removed

### ISSUE THREAD

**Issue by datoml** [SHWotever/SimHub#1513]
**Describe the bug**
I have two Arduinos connected to my PC.
One is the Simpush Racelogic Replica and the other is a DIY Flag / Eyebrows device.
Unfortunately the DIY Arduino broke and I had to remove it, but I didn't remove it from Simhub.
After doing my laps in iRacing, I noticed that my steering input randomly froze for a short time.
It seems like Simhub is trying to scan for the 2nd Arduino and this is blocking the Simucube's connection for a short time.
In the replay you can see that the steering was held perfectly when the freeze started and after about 200-400ms the wheel immediately jumps to the position I am holding now and the FFB is also back.
After I set Simhub so that only one Arduino is connected, the freezing was gone.
I drove for about 2 hours yesterday and had no problem at all.
Could it be that Simhub is also scanning the Simucube's com port?
Mika from Simucube told me that Simhub shouldn't be interfering here, but it must have something to do with it as it's working again now.

**Simhub version**
9.1.20

**Third party plugins**
All disabled

**To Reproduce**
1. Add two Arduino's to Simhub.
2. Unplug one of them but don't remove it from Simhub.
3. Start iRacing and drive some laps
4. You should notice that inputs are odd and sometimes the wheel is frozen

**Expected behavior**
Removed Arduino should not interfere with Simucube 2 Wheelbase

**Comment by SHWotever** [comment]
Hi ! 
Indeed simhub does not scan for simcube, it's an exception hardcoded to avoid interfering with it even when not excluded from the arduino scan settings. 

You can see it in the scan window, you will see "port already in use for ... " meaning that it won't scan it.
With the other devices you mentioned along, I would think more about a more classical usb/power overload.

**Comment by datoml** [comment]
Thanks for your answer.
I have changed the USB port and hope that it no longer occurs.
The first few rounds were promising. :)
