### ISSUE TITLE
Dashboards cause iRacing to crash

### ISSUE THREAD

**Issue by asciiuk** [SHWotever/SimHub#1514]
**Describe the bug**
If I load a dashboard for my Leoxz XF1 Pro rim in Simhub iRacing now crashes when you get in the car. If I have no dash operational iRacing works as intended.

**Simhub version**
9.1.20

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)
Leoxz Simbridge
Yeop GT

**To Reproduce**
1. Load Simhub and iRacing
2. Launch session in iRacing, can be test drive or from series list
3. Click Race
4. iRacing starts to stutter, I can see dashboard on my wheel screen flicker from one dashboard back to my active one, iRacing shows C/S/P meters and C is full, S has 2nd half red and P will show full grey. Can't drive car at all and iRacing goes back to replay screen with no option to get back into car. Have to close iRacing and relaunch to retry.

If I switch my display off or chose to not have any dashboard loaded iRacing will run as normal.

**Expected behavior**
Load into car and dashboard displays as normal, drive out the pits.

**Screenshots**
![Capture](https://github.com/SHWotever/SimHub/assets/156790915/49926c17-68c9-4f26-8883-11d1c36cd9ae)
![Capture1](https://github.com/SHWotever/SimHub/assets/156790915/77f1e40f-ffd1-4f26-9323-6844b09ef271)
![Capture2](https://github.com/SHWotever/SimHub/assets/156790915/445fe44f-eb33-4718-acb7-9efaf02975d7)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

[SimHub.txt](https://github.com/SHWotever/SimHub/files/13948879/SimHub.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/13948881/SimHub.1.txt)

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
I've removed any CPU/GPU overclocks, reinstalled iRacing, reinstalled Simhub, reinstalled plugins/dashboards etc.

**Comment by SHWotever** [comment]
Hi ! 
Leaozx is completely relying on their own made plugin. For issues related to their devices/plugin you can contact them directly at https://www.leoxz.com/pages/message-1 as I can't fix their code on my side.

NB : Considering the symptoms it looks like the wheel/plugin is switching back and forth from dashboard to dashboard creating an heavy system load, I would think about a button being broken sending wrong inputs. In all cases this is something handled right in the plugin or hardware and I have no hands on it. If the plugin has an assignable command for switching I would try to clear it to stop it from switching dashboards, that will solve it.

Nicolas

**Comment by asciiuk** [comment]
Hi Nicolas, thank you so much for your time and prompt response! I'll double check the change dashboard key mapping now although after the reinstall I believe it defaults to no assigned key mappings for switching dashboards. But i'll see if I can find any odd inputs from the wheel causing it and if not I'll get the issue logged with Leoxz. Cheers
