### ISSUE TITLE
Game Crashes shortly after starting since Sim Hub is installed

### ISSUE THREAD

**Issue by CaptainSlow36** [SHWotever/SimHub#1515]
Since i have installed Sim Hub today, nearly every game crashes (some realy early some more later).
For example EA WRC and Dirt Rally 2.0 crashes about 6 seconds after starting. Assetto Corsa crashes after starting a race and i get a permanent screen of a meadow. Fps games also have trouble, like Battlefield 2042 where i get a 10 Minute Black screen after starting, but after some time this game continues and i can play it normaly.

I tried to repair the vaulty games, but it had nu succes, i also closed sim hub via task manager and nothing change, same problem again.

I think that the Installation process of simhub maby crashed some softwares which are needed for many games?
Do you have knowledge about this problem from before and can help me out please?

With best regards,
Elias

**Simhub version**
9.1.22

**Third party plugins**
Tried also with all not necessary programms closed like Afterburner and sim programms

**Log files**
Should be attached
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/13998127/SimHub.2.txt)

**Comment by SHWotever** [comment]
Hi !

Simhub does not install any resident process or "suspicious" things in background. 

It's just installing the app and microsoft official dependencies if missing which in most cases are already installed nowadays (vc++,.net) . 
When simhub is not running there is nothing remaining. The fact that you have issues with FPS games completely unrelated to simhub, while simhub is closed makes me think about a motherboard/graphics card issue or eventually drivers, and the simhub installation at the same time was just a coincidence.

To verify it you can uninstall simhub and delete the whole c:\Program Files (x86)\SimHub folder to get rid of any remaining traces (some user settings files are kept here).

Best regards,

Nicolas
