### ISSUE TITLE
Corsair Nexus not available

### ISSUE THREAD

**Issue by Weini1972** [SHWotever/SimHub#1516]
Thank you for your great work and support with the last update. 
One note: Since version 9.1.20 the Corsair Nexus is no longer in the device list and is no longer supported by SimHub as a display. Do you have a solution for this?
Under Version 9.1.19, everything works fine.

Thanks a lot once more
Kind Regards 
Hans

**Comment by SHWotever** [comment]
Hi !

Thanks for the head up, it had been inadvertently crushed during the thermaltake addition, it's back for the next version,

Best regards,
Nicolas
