### ISSUE TITLE
gmail PLUGIN

### ISSUE THREAD

**Issue by alinou83** [SHWotever/SimHub#1519]
Salut Nicolas,
Je t'écris de la part de Romainrob , qui n'a pas pu répondre a ma question, et il m'a dit que le mieux c'était de t'écrire.
Je souhaiterais utiliser le PLUGIN GMAIL, mais apparemment, il ne fonctionne pas.
Pourrais-tu me dire si ce plugin fonctionne, et s'il fonctionne ? de quelle manière fonctionne-t-il.
Il n'y a aucune vidéo, ni tuto sur YouTube ou autre ???
Merci pour ta réponse
Alain SABBAGH
alainsabbagh@gmail.com

**Comment by SHWotever** [comment]
Bonjour, malheureusement il ne fonctionne plus, les accès a gmail sont beaucoup plus sécurisés depuis quelques années. Il n'est maintenant officiellement impossible de créer les "crédentials" nécessaires pour cet accès simplifié. 
Cordialement

**Comment by alinou83** [comment]
Bonjour, merci beaucoup de m'avoir répondu aussi vite.
Cordialement
Alain Sabbagh
