### ISSUE TITLE
Add support for ESP32

### ISSUE THREAD

**Issue by brunofresco** [SHWotever/SimHub#1520]
Hello

Is it possible to ass ESP32 support as it is arduino compatible it should run on the same code and it supports wireless it could be handy

**Comment by SHWotever** [comment]
Hi ! 

Unfortunately the esp32 is a much less "normalized" ecosystem compared to the official arduinos. Many models, with many subtilties. 
I will maybe investigate on the pi pico, even if it lacks of wireless support which seems to meet a much better standard (with usb capabilties).
