### ISSUE TITLE
GT7 telemetry data disappears when car is stationary

### ISSUE THREAD

**Issue by OMDolton84** [SHWotever/SimHub#1521]
**Describe the bug**
SimHub appears to default to the "waiting for data" state when car is at standstill after a few seconds in GT7.

**Simhub version**
9.1.24

**Third party plugins**
None.

**To Reproduce**
1) Open any dash with GT7 as active game
2) In GT7, reduce speed to zero and wait a few seconds
3) See dash lose all telemetry data
4) Check "Games" tab in SimHub, see "Waiting for data" under game state

**Expected behavior**
For SimHub not to have all telemetry disappear from my dash after a few seconds of standstill. This also occurs when on the grid waiting for a race to start.

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/14022700/SimHub.txt)

**Additional context**
When using other dash apps (E.G. SimDashboard), this issue doesn't occur.

**Comment by SHWotever** [comment]
Hi ! Thas fix has been released in the last version,

Nicolas
