### ISSUE TITLE
[Feature request] - Pit Enter At Lap

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1522]
Dans le cadre d'une utilisation sur un leaderboard, serait il possible de disposer de la donnée PitEnterAtLap

Comme tu me l'as déjà précisé, j'ai essayé d'utiliser currentlaphighprecision mais sans succès car cette donnée évolue au fil des tours alors que PitEnterAtLap est une information à l'instant T

j'ai aussi essayé d'utiliser une fonction "root" pour stocker l'information mais cela ne fonctionne pas car elle est valable pour tous les concurrents. Dès qu'un concurrent rentre aux stands, la valeur évolue
je n'ai pas trouvé comment stocker une valeur indicée sur le concurrent avec la fonction root. Cela ne semble pas exister
J'ai beau cherché, je ne trouve pas de solution
Merci

![3](https://github.com/SHWotever/SimHub/assets/58605557/9fbdc6e9-98ec-4c31-ad4c-97d6a9665462)

**Comment by SHWotever** [comment]
Hello ! Je l'ai jouté pour la prochaine version

**Comment by herve4545** [comment]
Super
Merci
