### ISSUE TITLE
My dashboards I created won't load since updating to 9.1.28

### ISSUE THREAD

**Issue by Davidstoakes** [SHWotever/SimHub#1524]
I have just updated SimHub to the latest version 9.1.28 and now the dashes that I have created are not loading up. I can see the boards in the folder, but they are not showing up once SimHub is launched.

![image](https://github.com/SHWotever/SimHub/assets/118506295/19884dca-b5ac-4376-9fd9-8f5047245950)
![image](https://github.com/SHWotever/SimHub/assets/118506295/eea4aa60-e26e-4430-b596-b79e8bc6a7ff)
![image](https://github.com/SHWotever/SimHub/assets/118506295/1755f8e0-3766-4566-90e3-899bd0866108)
![image](https://github.com/SHWotever/SimHub/assets/118506295/2ec9c8e4-b837-4680-b72c-80816a0de537)

![image](https://github.com/SHWotever/SimHub/assets/118506295/8eb39fd0-4719-49fb-8b1c-b5960a1cc862)

How do I rectify this please.

Regards Dave

**Comment by Davidstoakes** [comment]
Since posting, the three png files are now not there.

**Comment by SHWotever** [comment]
Hi ! Apparently you modified directly a stock dashboard, these have the latest version installed after each updates. So if you modified in place the default one it got "updated" to the latest version.

**Comment by SHWotever** [comment]
There is a _backups folder containing a few previous versions backup done after each saving. You could recover some past parts here.

**Comment by Davidstoakes** [comment]
Thankyou for getting back to me. I wasn't aware that would happen.
Now that I know that, I'll create a button box from scratch. 

Cheers
