### ISSUE TITLE
Antivirus Detects simhub as Threat 9.1.28

### ISSUE THREAD

**Issue by 4xvgal** [SHWotever/SimHub#1525]
**Describe the bug**
updated version 9.1.28 
and my Eset nod32 antivirus delete simhubwpf.exe 

**Simhub version**
Make sure to run the latest version
[9.1.28](https://github.com/SHWotever/SimHub/releases/tag/9.1.28)
**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).
my eset AV log
<?xml version="1.0" encoding="utf-8" ?>
<ESET>
  <LOG>
    <RECORD>
      <COLUMN NAME="TIME">2024-01-29 오전 1:40:45</COLUMN>
      <COLUMN NAME="검사기">시작 검사기</COLUMN>
      <COLUMN NAME="개체 형식">파일</COLUMN>
      <COLUMN NAME="개체">c:\program files (x86)\simhub\simhubwpf.exe</COLUMN>
      <COLUMN NAME="탐지">Suspicious Object</COLUMN>
      <COLUMN NAME="동작">삭제하여 치료됨 (다음에 다시 시작 후)</COLUMN>
      <COLUMN NAME="사용자"></COLUMN>
      <COLUMN NAME="정보"></COLUMN>
      <COLUMN NAME="해시">F4F9A1B7FC9671900CA12BD51C376B19EF66B6C0</COLUMN>
      <COLUMN NAME="첫 번째 화면">2023-09-15 오후 5:36:47</COLUMN>
    </RECORD>
 </LOG>
</ESET>
How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
i'll keep using older version

**Comment by SHWotever** [comment]
Hi !

This is definitely a false positive as explained here : https://github.com/SHWotever/SimHub/wiki/SimHub-Troubleshootings#simhubexe-disappears-or-antivirus-detects-simhub.  
Every new version is checked through virus total as shown here : https://www.virustotal.com/gui/file/27ee1f1596ff8265fae2ff94767dafdffa6bd2a7858c7bc0cab4e39e72f8ef60

It's also systematically submitted to windows defender to avoid any false positives. 
Here is the report of the microsoft analysis : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/404aa3c0-e02d-4595-944d-f9f7784c9ca7)

If unfortunately your antivirus wrongly classify simhub does not hesitate to report it to them so they can fix it. 
You can find instructions about submitting it to your antivirus software here : https://support.eset.com/en/kb141-submit-a-virus-website-or-potential-false-positive-sample-to-the-eset-lab#SubmitFile

**Comment by excessnet** [comment]
Got a return from ESET, but I'm already on the latest version and it still trigger. Waiting for another reply.

```
Hello,

Thank you for your submission.
It is a false positive that was fixed already in the latest update. Please update your ESET product.

Regards,

ESET Malware Response Team
```

**Comment by excessnet** [comment]
It has been fixed in the latest update of ESET! :)
