### ISSUE TITLE
Route Advisor nextion display

### ISSUE THREAD

**Issue by choromeeua** [SHWotever/SimHub#1527]
How can it be possible to use est2's Route Advisor on the nextion display, any future updates for this compatibility?

**Comment by SHWotever** [comment]
Hi ! 

The nextion support has been stopped for almost 3 years now :
https://github.com/SHWotever/SimHub/wiki/Nextion---End-of-support

However the nextion technology doesn't allow such features (that's one of the many reasons, as well as a lack flexibility, and the manufacturer making harder and harder to make the editor fit the needs of simhub which made me stop it.

Nicolas
