### ISSUE TITLE
simagic pedal p1000 problems

### ISSUE THREAD

**Issue by jfrpadron** [SHWotever/SimHub#1528]
Hello, 
after update to v 9-1-28,I cannot adjust the shakelt motors vibration intensity, from 38 on the global main they start to vibrate at high intensity and less than 38 they no longer vibrate. I have tried different games and the same thing happens.If can I add mor info please tell me.
Thanks and greetings

**Comment by SHWotever** [comment]
Hi ! 

There was a bug in the p1000/2000 implementation it was driven at half its power. The control instructions are now scaled properly, But it also revealed that the p1000 is not as linear as the 2000 can be (basically it feels already at 100% when you reach 50%).

To get back a similar scale as before, you can tune the output and lower the threshold and minimum force by two	: 
![image](https://github.com/SHWotever/SimHub/assets/2207331/eb31b25e-fc0c-4f85-b76a-247ebe0b60bd)

Then set the motors gains to 50% : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/6dab8ab9-f329-4ee9-8229-3407da621f4c)

I've reached already simagic about this scaling issue which makes p1000 and 2000 react so differently while the hardware is "almost" the same. I'm waiting for informations.

**Comment by jfrpadron** [comment]
Thanks so much ,I will try the setup you are telling me and wait for next updates I guess its gonna be ok.regards Sent from Mail for Windows From: WoteverSent: 29 January 2024 16:53To: SHWotever/SimHubCc: jfrpadron; AuthorSubject: Re: [SHWotever/SimHub] simagic pedal p1000 problems (Issue #1528) Hi !There was a bug in the p1000/2000 implementation it was driven at half its power. The control instructions are now scaled properly, But it also revealed that the p1000 is not as linear as the 2000 can be (basically it feels already at 100% when you reach 50%).To get back a similar scale as before, you can tune the output and lower the threshold and minimum force by two :image.png (view on web)Then set the motors gains to 50% :image.png (view on web)I've reached already simagic about this scaling issue which makes p1000 and 2000 react so differently while the hardware is "almost" the same. I'm waiting for informations.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
