### ISSUE TITLE
iRacing data not transmitting

### ISSUE THREAD

**Issue by Zanz38** [SHWotever/SimHub#1530]
**Describe the bug**
Bass shakers, Next Level racing HF8 seat pad, Fan and Arduino services (LED Screen) not working when iracing is running. testing bass shakers in the Sound output produces a result, testing in effects profile produces no results.

Wind controls do not work in testing mode

LED matrix goes off when i racing is running and turns back on when iracing closes

HF8 does not work when tetsing

everthing shows as connected.

At some point it may all suddenly activate but not based on data i.e bass just rumble continuously, LED matrix will show for a brief moment. Fan will switch on but not speed relative.

I am not sure what join log files mean so i have zipped the logs folder. If that is not correct please provide a link for more context and i wil reload

**Simhub version**
Make sure to run the latest version9.1.28 and in last 2 or 3 versions
**Third party plugins**
Not sure i am running any

**To Reproduce**
1.Running racing

**Expected behavior**
Feel the runbles in the road, feel the wind in my balding hair and see track flags in an led matrix

**Screenshots**

**Log files**
[SimHub.zip](https://github.com/SHWotever/SimHub/files/14102740/SimHub.zip)

Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi !

Apparently you have symproject fan controller which is failing. Every time the game simhub tries to send data to it (basically when games starts) and it doesn't respond and gets simhub stuck. Could you try to disable it ? It should solve the issue.

Concerning the controller itself I would recommend to check the usb cable, try another port, of it doesn't help do not not hesitate to contact symprojects for hardware warranty.

**Comment by Zanz38** [comment]
Thanks I have unplugged and we are back up ne running.

Thanks again

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
