### ISSUE TITLE
[Feature request] Widget canvas resizing?

### ISSUE THREAD

**Issue by jessemillar** [SHWotever/SimHub#1531]
**Is your feature request related to a problem? Please describe.**
If I create a widget in Dash Studio "from selection" and then want to change the canvas size of the widget, I don't seem to be able to do so.

**Describe the solution you'd like**
It'd be great if there was an obvious textarea or right-click option to let me change the canvas size of a widget. For example, I currently have a widget that I'd like to be wider so I can show more text. I can't figure out how to do that so I'm going to have to recreate the widget via copy/paste of the components into a new widget.

**Describe alternatives you've considered**
See copy/paste method described above. Feels clunky.

**Comment by SHWotever** [comment]
Hi ! 

A dwidget is a "mini" dashboard, so the make settings applies, to resize it go in dashboard properties :
![image](https://github.com/SHWotever/SimHub/assets/2207331/9faf1d49-2afc-48af-82a9-6be394c187ba)

Then set your size :
![image](https://github.com/SHWotever/SimHub/assets/2207331/8551ae3b-0d3d-49ab-a9a8-cf97725c0725)

**Comment by jessemillar** [comment]
Ah. Thanks for the explanation!
