### ISSUE TITLE
Problem on AX206

### ISSUE THREAD

**Issue by pipokorny** [SHWotever/SimHub#1532]
Hello. I'm just a gamer, using an AX206, and I haven't updated the app since December 2023, now I've updated it to version 9.1.28 and the screen didn't turn on anymore, ever again. I had to go back to version 9.1.19 and it worked. I have a license with you, but I don't know how to contribute more because I also speak Spanish and I'm using a translator to communicate with you.

My license, if it works, is edgardo.a.hernandez.o@gmail.com_2DA60C1B9CAB7EA5B0879E24FF735B7D.lic

**Describe the bug**

**Simhub version**
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
I restored default the high performance settings only compatible with "true" firmwares, but not available on various fake devices available recently on  Aliexpress : https://github.com/SHWotever/SimHub/wiki/Dashstudio---USB-Displays#ax206-warning

Hi could you make sure this option is disabled ?

![image](https://github.com/SHWotever/SimHub/assets/2207331/21ccf3ba-643d-497b-9bcc-600a4db0d067)

For a better vision of the issue could you send the log files as requested if that does not help ?

> 
> Log files
> Join log files available in C:\Program Files (x86)\SimHub\Logs
> Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).
> 
> How to attach files : [docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)
> 
> Additional context
> Add any other context about the problem here.
