### ISSUE TITLE
Wrong font in matrix font

### ISSUE THREAD

**Issue by neonflux75** [SHWotever/SimHub#1533]
**Describe the bug**
A little error in matrix 8x8 font definition (at least, In think...)
In MatrixFonts folder there are two files called THICK8x8.matrixfont and THICK-HOLLOW8x8.matrixfont.
The two fonts are the same but the hollow version has only the contour of the font.
The problem is in the definition of number "1", in the THICK8x8 version is left aligned, instead, in the HOLLOW version is centered (as all fonts)
I think it has to be centered in THICK8x8 version too so when I update to the new version I allways edit the file to center it.

**Simhub version**
Last version and older

**To Reproduce**
Go in MatrixFonts folder
Open THICK8x8.matrixfont
Check definition for number "1"
```
char="1"
row="  888   "
row=" 8888   "
row="88888   "
row="  888   "
row="  888   "
row="  888   "
row="  888   "
row="  888   "
```
Open THICK-HOLLOW8x8.matrixfont
Check definition for number "1"
```
char="1"
row="   888  "
row="  8  8  "
row=" 888 8  "
row="   8 8  "
row="   8 8  "
row="   8 8  "
row="   8 8  "
row="   888  "
```

as you can see the HOLLOW type has an initial space that center the font in the matrix, the THICK8x8 instead start left aligned
**Expected behavior**
change definition for char "1" in THICK8x8.matrixfont and custommatrixfont8x8.matrixfont to:

```
char="1"
row="   888  "
row="  8888  "
row=" 88888  "
row="   888  "
row="   888  "
row="   888  "
row="   888  "
row="   888  "

```

**Comment by SHWotever** [comment]
Hi ! 

Thanks for the feedback, it's fixed for the next version.
