### ISSUE TITLE
Forced Frequencies only works in Corner mode

### ISSUE THREAD

**Issue by MycroftLegros** [SHWotever/SimHub#1535]
**Describe the bug**
**forced frequencies** in custom effects only works in corner mode, not in mono, L/R or F/R

**Simhub version**
9.1.26

**Third party plugins**
N.A.

**To Reproduce**
use force frequencies in mono, set frequency to XXHz, it's keeps the 44Hz set in base effect frequency

**Expected behavior**
should work in mono, L/R and F/R

**Screenshots**
attached
![Image1](https://github.com/SHWotever/SimHub/assets/5487071/4a8b3e88-472f-46f2-82a8-eed7c449c721)

**Log files**
N.A.

**Additional context**
N.A.

**Comment by SHWotever** [comment]
Hi !

I've added the frequency for the aggregation mode for the next version, when aggregated it will take the first available (no average etc ...)
