### ISSUE TITLE
Bug about `Custom Serial Devices` plugin not being able to send hexadecimal 0xff

### ISSUE THREAD

**Issue by Liber-coder** [SHWotever/SimHub#1536]
`Custom Serial Devices` cannot send hexadecimal 0xff. For example, I enter javascript code:
```javascript
return '\xff'; 
```
and what it actually sends is `\x3f`
In fact, I've found that it doesn't properly handle any characters larger than `0x7f`：

![image](https://github.com/SHWotever/SimHub/assets/26061859/dc08f68a-8240-42bf-9086-d6d098f7282d)
![image](https://github.com/SHWotever/SimHub/assets/26061859/b73ab9c5-f64a-42b2-8c93-ad2be69706f3)

Is it possible to support greater than `0x7f` ? because most devices require a special character as the closing character.
:)

**Comment by SHWotever** [comment]
Hi ! Indeed the native ascii encoding was not letting it go through, I'm sending binary data for the next version.
