### ISSUE TITLE
Capture Layout Profiles (Bluetooth Lights)

### ISSUE THREAD

**Issue by Luckystrikah** [SHWotever/SimHub#1540]
**Describe the bug**
Ambient lights: The newly implemented profiles for the Capture layouts are not working. At least for the bluetooth lights, probably also for Govee devices.

**Simhub version**
9.1.29 (also before, eversince the function was added)

**To Reproduce**
1. Simply do a capture layout
2. clone profile
3. do changes to the capture zones or scene Settings
4. load other profile -> profile settings will be ignored and stay the same

**Expected behavior**
I would like to be able to customize capture zones and lighting settings for each profile individually. To make it work in several games instead of just one (or even general ambient lighting without running a game).

Thanks a lot!

**Comment by SHWotever** [comment]
Hi ! At this time only the areas sizing/position are being controlled by the profile. 
This was to avoid refining the whole list of devices and color settings for every new profile.

Can you confirm the layout is saved and restored as shown on this quick test I did ?
![LayoutChanged](https://github.com/SHWotever/SimHub/assets/2207331/84b3a5a3-124c-4acf-9736-14b8dc211fc3)

NB : when the profile still does not contain definition for a device it will keep the last used areas as the default

**Comment by Luckystrikah** [comment]
I dont have access to that dropdown menu you are using. I can only load via profiles manager and there no changes have effect. Whether its load/clone/save or import/export. It just won't work. My LEDs are recognized as "Triones"

**Comment by SHWotever** [comment]
The selector is an incoming feature but it's the same as the profile manager.
Could you join SimuLightSettings.json stored in C:\Program Files (x86)\SimHub\PluginsData so I can take a deeper look ?

**Comment by Luckystrikah** [comment]
[SimuLightSettings.json](https://github.com/SHWotever/SimHub/files/14214434/SimuLightSettings.json)
i hope that worked.. thanks!

**Comment by Luckystrikah** [comment]
Nothing suspicious? I was thinking if i could setup profiles in that json file to make it work? Could that be a workaround? Simhub doesn't seem to save my settings, only the most recent one.

**Comment by SHWotever** [comment]
Hi ! 

Sorry I did not had time to look until now, I confirm areas were not saved on this specific kind of devices, I've fixed it for the next release.

Nicolas

**Comment by Luckystrikah** [comment]
Thats so great to hear, thanks a lot!! Really awesome work.
