### ISSUE TITLE
Searching For Game Readers error

### ISSUE THREAD

**Issue by Orlin1313** [SHWotever/SimHub#1541]
**Describe the bug**

![sim hub error](https://github.com/SHWotever/SimHub/assets/159479375/ed3ed82a-390e-44b0-a086-afe31ff5f601)

When opening Sim Hub The window in the above image freezes here and app wont open

**Simhub version**
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi thanks for your report, could you join the log files ? 

Log files
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by Orlin1313** [comment]
Here are todays. its odd because yesterdays is missing.
[SimHub.txt](https://github.com/SHWotever/SimHub/files/14214068/SimHub.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/14214069/SimHub.1.txt)
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/14214070/SimHub.2.txt)
[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/14214071/SimHub.3.txt)
[SimHub.4.txt](https://github.com/SHWotever/SimHub/files/14214072/SimHub.4.txt)
[SimHub.5.txt](https://github.com/SHWotever/SimHub/files/14214073/SimHub.5.txt)
[SimHub.6.txt](https://github.com/SHWotever/SimHub/files/14214074/SimHub.6.txt)
[SimHub.7.txt](https://github.com/SHWotever/SimHub/files/14214075/SimHub.7.txt)
[SimHub.PackageManager.Standalone.1.log](https://github.com/SHWotever/SimHub/files/14214076/SimHub.PackageManager.Standalone.1.log)
[SimHub.PackageManager.Standalone.2.log](https://github.com/SHWotever/SimHub/files/14214077/SimHub.PackageManager.Standalone.2.log)
[SimHub.PackageManager.Standalone.3.log](https://github.com/SHWotever/SimHub/files/14214078/SimHub.PackageManager.Standalone.3.log)
[SimHub.8.txt](https://github.com/SHWotever/SimHub/files/14214079/SimHub.8.txt)
[SimHub.9.txt](https://github.com/SHWotever/SimHub/files/14214080/SimHub.9.txt)
[SimHub.10.txt](https://github.com/SHWotever/SimHub/files/14214081/SimHub.10.txt)
[SimHub.11.txt](https://github.com/SHWotever/SimHub/files/14214082/SimHub.11.txt)
[SimHub.12.txt](https://github.com/SHWotever/SimHub/files/14214083/SimHub.12.txt)
[SimHub.13.txt](https://github.com/SHWotever/SimHub/files/14214084/SimHub.13.txt)

**Comment by SHWotever** [comment]
Thanks for the log, apparently a setting file got corrupted : C:\Program Files (x86)\SimHub\PluginsData\Common\ResolveCache.json  
Did you had hard drive issues ? Overall this particular file can be safely deteted and it will be rebuilt. Can you try to delete it ?
Hopefully there is no other settings corruptions.

**Comment by Orlin1313** [comment]
I did a disk scan last night. Deleting file fixed the issue Thanks much!!!!!

**Comment by SHWotever** [comment]
No problems !
