### ISSUE TITLE
Button mapping not working for new Fanatec Clubsport DD base

### ISSUE THREAD

**Issue by photon1503** [SHWotever/SimHub#1543]
**Describe the bug**
After switching from Fanatec CSL DD to new Clubsport DD, the button mapper does not recognize the different rims anymore.
Maybe Fanatec changed something in their SDK for the new bases?

**Simhub version**
9.1.29

**Third party plugins**
n/a

**To Reproduce**
1. Old mappings deleted
2. New mapping created with base+rim combo #1
3. Disconnect rim, the mapping is still "connected"
4. Connect another wheel, it's not possible to create a new combo

**Expected behavior**
Should behave as with old base

**Screenshots**
![image](https://github.com/SHWotever/SimHub/assets/14548927/5c3f8d06-935a-4215-a6fc-b47754187044)

**Comment by SHWotever** [comment]
Hi ! I checked and I think it's simply due to the wheel model not existing in the Fanatec SDK I got (which make sense) I will try to get an updated one (unfortunately the links I originally got from Fanatec are not working anymore)

**Comment by photon1503** [comment]
Thank you for checking!

**Comment by SHWotever** [comment]
NB : I forgot, it's the interface DLL, simply backup the old one, and copy this new one in the simhub installation folder

**Comment by photon1503** [comment]
Merci beaucoup! Unfortunately I can't test it before tomorrow evening, will let you know the result.

**Comment by photon1503** [comment]
Had a chance to quickly test it. I can confirm that with new Fanatec DLL the button mapper works now also for new base! 
Thank you so much for the prompt reaction @SHWotever 

![Screenshot 2024-02-11 094108](https://github.com/SHWotever/SimHub/assets/14548927/261db487-0582-4ef4-a9f3-760a7ecf5099)

**Comment by SHWotever** [comment]
Thanks for the feedback ! It will be part of the next public version.

Nicolas
