### ISSUE TITLE
AMS2 - Reverse gear

### ISSUE THREAD

**Issue by Butzy79** [SHWotever/SimHub#1545]
In some cars (like the Gt1 cars) in AMS2, when you throw the car into reverse gear, it is appearing the gear 15.

**Comment by SHWotever** [comment]
Hi ! Could you fill the issue template please : https://github.com/SHWotever/SimHub/issues/new?assignees=&labels=triage&projects=&template=bug_report.md&title=

**Comment by SHWotever** [comment]
Hi ! 

Unfortunately UDP format has some format issues about gear as shown here : https://github.com/SHWotever/SimHub/issues/1235
This specific case could be fixable, but there are many others which don't and can't work with udp. Could you switch back to shared memory it's now more more complete and there are not much reasons of using UDP.

**Comment by Butzy79** [comment]
I agree. Please close the issue or delete it :)
