### ISSUE TITLE
Update wiki to mention location of sample plugin

### ISSUE THREAD

**Issue by jessemillar** [SHWotever/SimHub#1546]
I was able to finally find the sample plugin thanks to a kind user on the Discord (and I've since found [this GitHub issue that also answers the question of how to make a plugin](https://github.com/SHWotever/SimHub/issues/710)) but it would save future devs time if the GitHub wiki mentioned the sample somewhere. Maybe add a note to the [Additional Plugins](https://github.com/SHWotever/SimHub/wiki#additional-plugins) section of the wiki saying "If you'd like to make your own plugins, there's a sample in the SimHub installation directory under PluginSdk/User.PluginSdkDemo".

**Comment by SHWotever** [comment]
Originally it was a large tab exactly where you are suggesting, but people were not seeing it ¯\_(ツ)_/¯  so it died since it was useless :D
I will add a page on the wiki about it ;)

**Comment by SHWotever** [comment]
Here we go ;) last link of the general section ;) https://github.com/SHWotever/SimHub/wiki#simhub-general

**Comment by jessemillar** [comment]
Awesome! Thank you!
