### ISSUE TITLE
Allow for renaming of a widget file in the Dash Studio UI

### ISSUE THREAD

**Issue by jessemillar** [SHWotever/SimHub#1547]
I can rename a widget so it displays the name I want in the "Screen hierarchy" in Dash Studio, but the underlying file for the widget is still the old name.

For example, I've renamed my widget to "iRacing Info" in the hierarchy but when I "Edit Widget" the tab still shows the old name of "Functions." I assumed there'd be a "Dashboard Name" in "Dashboard Properties." I see "Dashboard Title" but I'm assuming that doesn't do that I want since the title value is currently blank and the tab still reads "Functions."

**Comment by SHWotever** [comment]
Hi ! The name shown in the hierarchy does not relate to the widget file itself. overall if you have two instances of the same widget file they can't share the same "hierarchy name", but the same file.

The tab is showing indeed the filename which is indeed not renamed as it could break all the existing usages of it. Overall the renaming of the file is not made easy for that specific reason once renamed every usages of it will be broken which is to be made only in good conscience of the impact and manually for now.

**Comment by jessemillar** [comment]
What is the process for manually renaming the widget file? Just changing the name and then fixing all the breakages in the Dash Studio by selecting the new widget file name in the "FileName" dropdown?

**Comment by SHWotever** [comment]
Yes indeed ;) The name(s) as there are up to 3 files side to side (.djson, .ressources, .carclasses)

To rename a whole dash I would recommend to "duplicate it" then delete the old one, that's the safest way
