### ISSUE TITLE
Road Rumble not getting any telemetry.

### ISSUE THREAD

**Issue by IRBrainiac** [SHWotever/SimHub#1549]
Simhub ver. 9.1.3.1
Win 11
Horizon 4 
Bass shakers.

All other shaker telemetry seems to work fine,only Road Rumble seems to have no input.
No shake and no live window readings.

**Additional context**
Tried cranking up the settings to see if the signal was just weak.No effect.
thank you
[SimHub.txt](https://github.com/SHWotever/SimHub/files/14365334/SimHub.txt)

**Comment by SHWotever** [comment]
Hi !
If i'm not wrong FH4 does not give that data. At the time the structure was a backport of the complete telemetry provided also on motorsport, but not all channels are available. I will check and mark it as unsupported if indeed FH4 does not feed that data.
