### ISSUE TITLE
[Feature request] Screen resolution for devices

### ISSUE THREAD

**Issue by bluegeekgh** [SHWotever/SimHub#1550]
I have a turing compatible display but 5''. The device is detected and the dashes showed in the screen, but only reduced in a part or the screen because my device resolution is 480x800 and the supported 3.5' device is 320x480. 

The performance is good for the reduced screen even for "relatives" dashes, so I thinks simple dashes can work well in my resolution (check the video linked below). Is there a way to change the "output resolution"? (i've checked the SimHub files and I couldn't find anything). Or is it possible to add support for this resolution (or a parameter in settings) as the device is detected and it works? 
Thanks in advance.

https://streamable.com/x1gkzq

**Comment by bluegeekgh** [comment]
I there a way to change the output resolution? only with this will work for me

**Comment by SHWotever** [comment]
No it's hardcoded, at the time the 3.5 was the only model.

If somehow I add it it will amplify this compatibility/batch issues I was mentioning and I refuse to orient people deliberately on "randomly working" solutions. 
I like to hack and make a new use of "stuffs" like those screens. But I have to think about users getting stuck with devices they put some significant money in it thinking it would work but are not.
