### ISSUE TITLE
R3E NCalc function drivercarnumber not working as expected

### ISSUE THREAD

**Issue by SCarlsen7757** [SHWotever/SimHub#1553]
**Game**
RaceRoom Racing Experience

**Describe the bug**
When using the NCalc function "drivercarnumber(raceposition)" this does not return the car number. This returns "" (string.empty).

**Simhub version**
9.2.3

**To Reproduce**
1. Start replay of R3E when ingame
2. Go to 'NCalc Tester Binding'
3. NCalc Formula 'drivercarnumber(1)'
4. Raw result "" (string.empty)

**Expected behavior**
Return the car number that is available in R3E.Data.DriverData[].DriverInfo.CarNumber.

![Screenshot 2024-02-25 011037](https://github.com/SHWotever/SimHub/assets/65501777/79d46a2e-2b90-49aa-98d6-8bbbad87f91a)

**Comment by SHWotever** [comment]
Hi ! I confirm I missed it was available on RRRE, I wired it for the next update.

Nicolas
