### ISSUE TITLE
Le Mans Ultimate NOT working

### ISSUE THREAD

**Issue by yanturcotte** [SHWotever/SimHub#1554]
**Describe the bug**
I try to use SimHub to run a dashboard on my vocore screen.  The game is configured but it's always waiting on data and when I open the game nothing happens in the system log.  When I get on the tyrack, still waiting on data.  I have no issues with all the other games that I use my vocore screen.

**Simhub version**

Version 9.2.3 but I tried with 9.2.1 and 9.2.2 and still the same issue

**Third party plugins**

None

**To Reproduce**
1. Open game
2. get on track

**Expected behavior**
My vocore screen is suppose to show me the dashboard I selected

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

[RSC.MissingLogos.txt](https://github.com/SHWotever/SimHub/files/14412180/RSC.MissingLogos.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/14412181/SimHub.1.txt)
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/14412182/SimHub.2.txt)
[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/14412183/SimHub.3.txt)
[SimHub.4.txt](https://github.com/SHWotever/SimHub/files/14412184/SimHub.4.txt)
[SimHub.5.txt](https://github.com/SHWotever/SimHub/files/14412185/SimHub.5.txt)
[SimHub.6.txt](https://github.com/SHWotever/SimHub/files/14412186/SimHub.6.txt)
[SimHub.7.txt](https://github.com/SHWotever/SimHub/files/14412187/SimHub.7.txt)
[SimHub.8.txt](https://github.com/SHWotever/SimHub/files/14412188/SimHub.8.txt)
[SimHub.9.txt](https://github.com/SHWotever/SimHub/files/14412189/SimHub.9.txt)
[SimHub.10.txt](https://github.com/SHWotever/SimHub/files/14412190/SimHub.10.txt)
[SimHub.11.txt](https://github.com/SHWotever/SimHub/files/14412191/SimHub.11.txt)
[SimHub.12.txt](https://github.com/SHWotever/SimHub/files/14412192/SimHub.12.txt)
[SimHub.13.txt](https://github.com/SHWotever/SimHub/files/14412193/SimHub.13.txt)
[SimHub.14.txt](https://github.com/SHWotever/SimHub/files/14412194/SimHub.14.txt)
[SimHub.15.txt](https://github.com/SHWotever/SimHub/files/14412195/SimHub.15.txt)
[SimHub.16.txt](https://github.com/SHWotever/SimHub/files/14412196/SimHub.16.txt)
[SimHub.17.txt](https://github.com/SHWotever/SimHub/files/14412197/SimHub.17.txt)
[SimHub.18.txt](https://github.com/SHWotever/SimHub/files/14412198/SimHub.18.txt)
[SimHub.19.txt](https://github.com/SHWotever/SimHub/files/14412199/SimHub.19.txt)
[SimHub.20.txt](https://github.com/SHWotever/SimHub/files/14412200/SimHub.20.txt)
[SimHub.PackageManager.Standalone.1.log](https://github.com/SHWotever/SimHub/files/14412201/SimHub.PackageManager.Standalone.1.log)
[SimHub.PackageManager.Standalone.2.log](https://github.com/SHWotever/SimHub/files/14412202/SimHub.PackageManager.Standalone.2.log)
[SimHub.PackageManager.Standalone.3.log](https://github.com/SHWotever/SimHub/files/14412203/SimHub.PackageManager.Standalone.3.log)
[SimHub.PackageManager.Standalone.4.log](https://github.com/SHWotever/SimHub/files/14412204/SimHub.PackageManager.Standalone.4.log)
[SimHub.PackageManager.Standalone.5.log](https://github.com/SHWotever/SimHub/files/14412205/SimHub.PackageManager.Standalone.5.log)
[SimHub.PackageManager.Standalone.6.log](https://github.com/SHWotever/SimHub/files/14412206/SimHub.PackageManager.Standalone.6.log)
[SimHub.PackageManager.Standalone.7.log](https://github.com/SHWotever/SimHub/files/14412207/SimHub.PackageManager.Standalone.7.log)
[SimHub.PackageManager.Standalone.8.log](https://github.com/SHWotever/SimHub/files/14412208/SimHub.PackageManager.Standalone.8.log)
[SimHub.PackageManager.Standalone.9.log](https://github.com/SHWotever/SimHub/files/14412209/SimHub.PackageManager.Standalone.9.log)
[SimHub.PackageManager.Standalone.10.log](https://github.com/SHWotever/SimHub/files/14412210/SimHub.PackageManager.Standalone.10.log)
[SimHub.PackageManager.Standalone.11.log](https://github.com/SHWotever/SimHub/files/14412211/SimHub.PackageManager.Standalone.11.log)
[SimHub.PackageManager.Standalone.12.log](https://github.com/SHWotever/SimHub/files/14412212/SimHub.PackageManager.Standalone.12.log)
[SimHub.PackageManager.Standalone.13.log](https://github.com/SHWotever/SimHub/files/14412213/SimHub.PackageManager.Standalone.13.log)
[SimHub.PackageManager.Standalone.14.log](https://github.com/SHWotever/SimHub/files/14412214/SimHub.PackageManager.Standalone.14.log)
[SimHub.PackageManager.Standalone.15.log](https://github.com/SHWotever/SimHub/files/14412215/SimHub.PackageManager.Standalone.15.log)
[SimHub.PackageManager.Standalone.16.log](https://github.com/SHWotever/SimHub/files/14412216/SimHub.PackageManager.Standalone.16.log)
[SimHub.PackageManager.Standalone.17.log](https://github.com/SHWotever/SimHub/files/14412217/SimHub.PackageManager.Standalone.17.log)
[SimHub.PackageManager.Standalone.18.log](https://github.com/SHWotever/SimHub/files/14412218/SimHub.PackageManager.Standalone.18.log)
[SimHub.PackageManager.Standalone.19.log](https://github.com/SHWotever/SimHub/files/14412219/SimHub.PackageManager.Standalone.19.log)
[SimHub.PackageManager.Standalone.20.log](https://github.com/SHWotever/SimHub/files/14412220/SimHub.PackageManager.Standalone.20.log)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/14412221/SimHub.txt)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi !

I would guess that you are lacking some c++ dependencies could you try to install or repair c++ 2013 : vcredist_x64.exe
You can download it from here  https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by SHWotever** [comment]
Thanks for your feedback
