### ISSUE TITLE
Turing Smart Screen dash scaling (fullscreen) on 5 inch

### ISSUE THREAD

**Issue by AbstraktCollective** [SHWotever/SimHub#1556]
_**Is your feature request related to a problem? Please describe.**_
Dashboard Content displayed only in 1/3 part of the screen (scaled down - small).
Portrait looks like Landscape and Landscape looks like Portrait.

Currently on licensed version of SimHub 9.2.3
Non third party plugins installed, simple USB type C external monitor on port 24.

_**Describe the solution you'd like**_
5 inch Turing Smart Screen displaying the dash on fullscreen

_**Describe alternatives you've considered**_
A hint what to modify in a specific file or within the SimHub settings to make it work. I think there must be a file/setting defining the resolution of the screen (3,5" is typicaly 320*480px, mine 5" screen is 800*480px) and forcing the SimHub to display the dash in full 800*480px screen resolution can make it work for me.

_**Additional context**_

Turing Smart Screen parameters:
LCD 5 inch IPS USB type-c
Resolution: 800*480px

Please see attached photos with the problem.
Thank you all for any hints and assistance.

![01](https://github.com/SHWotever/SimHub/assets/162009454/8559722e-131d-4642-8f82-9c188d0659bf)

![02](https://github.com/SHWotever/SimHub/assets/162009454/26bf4317-a218-426c-8c6a-1b700e9d9144)

**Comment by SHWotever** [comment]
Hi ! 

This model is not supported I'm sorry, It's only the 3.5"

I don't plan to support anymore of those chinese models. There have been numerous versions/issues with those chinese screens and unless the manufacturer publish a proper SDK/Documentation which can guarantee a correct working mode on all the versions spread around aliexpress etc, I can't deliberately promote products which have one chance or two of being useless

https://github.com/SHWotever/SimHub/issues/1550

**Comment by AbstraktCollective** [comment]
Ok, I understand. So "End Of Life" for this one I guess.

What manufacturer do you recommend when it comes to compatibility and SimHub future-proof support for dash solutions?
Many use VOCORE screens, are they really a good solution? Considering buying couple of them.

Are there any other, perhaps better ones on the market? Looking for something with USB C connection to keep it simple.
Thank you!

**Comment by SHWotever** [comment]
That's sad indeed I would be happy to add this one to my "toolbox". But the Turing and AX206 are both from the same random Aliexpress family of "look the same" but "has many variations" which has no guarantee about the exact model and firmware being bought.

Currently vocore is one of the rare being both affordable and documented indeed and now offers a wide range of sizes https://github.com/SHWotever/SimHub/wiki/Dashstudio---USB-Displays
