### ISSUE TITLE
ACC loses FFB after SimHub is launched

### ISSUE THREAD

**Issue by DU3RI** [SHWotever/SimHub#1557]
**Describe the bug**
ACC loses FFB as soon as SimHub is launched.

**Simhub version**
9.2.3

**Third party plugins**
None. 

**To Reproduce**
Open ACC.
Jump on track - all fine.
Open SimHub - FFB gone.

**Expected behavior**
FFB works as expected.

**Log files**

[SimHub.txt](https://github.com/SHWotever/SimHub/files/14474187/SimHub.txt)

**Additional context**
Hardware: CSL DD 8nm, Fanatec GT3 Wheel. 
Controllers Input plugin disabled.

**Comment by SHWotever** [comment]
Hi !

I see you are using an usb sound card for bass shakers,  could you try quickly to disable bass shakers ? At first I would think simply to an overloaded usb, this is part of the symptoms described here :
https://github.com/SHWotever/SimHub/wiki/USB-Issues-Troubleshooting

**Comment by DU3RI** [comment]
yes! Thanks for the quick turnaround 👍
