### ISSUE TITLE
plugin conflict on Rfactor 2 between Simhub and SimRacingStudio

### ISSUE THREAD

**Issue by JYCrois** [SHWotever/SimHub#1559]
Good morning,
I have been using Simhub for years now and I am very satisfied with it.
However, I have a problem with Rfactor 2 and Le Mans Ultimate that I cannot resolve, I will explain.
I have a V3 platform from Next level Racing which uses the "MotionSystems_rFactor2Connector64.dll" plugin, no problem on this side.
My problem comes from a conflict between Simhub and SimRacingStudio (which I use for my cylinders) in fact Simhub and SimRacingStudio use the same plugin name "rFactor2SharedMemoryMapPlugin64.dll".
Therefore, every time I launch the automatic configuration of the plugin on Simhub, SimRacingStudio is faulty.
In the same way if I launch the SimRacingStudio automatic configuration, it is Simhub which is at fault.
I think the solution would be to manually rename the plugin installed by Simhub for example to "rFactor2SharedMemoryMapPlugin64-Simhub.dll".
But how do I tell Simhub to fetch this new file “rFactor2SharedMemoryMapPlugin64-Simhub.dll” and not “rFactor2SharedMemoryMapPlugin64.dll”?
Looking forward to a solution from you and congratulations again for your excellent work!
Sincerely,

**Comment by SHWotever** [comment]
hi ! The simhub embedded version is a more recent version, It's the same as the one embedded into simhub and in crewchief. 

It's a common plugin and wasting resources to make a "simhub specific" version providing 99.9% of the same data would be a real waste of CPU resources. On this point I rejoin the original author of this plugin which wanted it to be a single data access for everyone and avoiding blindly duplicating it and wasting lot of resources to export the same data many times).

Simply renaming is not enough the data names published to the apps uses specific names compiled into this dll and there can't be multiple versions of the same plugin just renamed, it needs to be modified and compiled again to make it autonomous (but once again wasting previous ressources doing the same telemetry export many times).

If you keep the srs version it's likely you will miss the latest additions like battery informations, but it will still work with SimHub (the new battery data being simply dead) . In such case you can simply dismiss the automatic configuration banner, you won't have the warning anymore and it will still work at 99.9% (except the new battery data) in the wait of SRS doing the update (this new version has been available for more than one year). 

Best regards,
nicolas
