### ISSUE TITLE
Wrong theme/ background colors in Dash Editor

### ISSUE THREAD

**Issue by snod** [SHWotever/SimHub#1560]
**Describe the bug**

When I open the Dash Editor the dark theme of the UI doesn't seem to be applied for every UI element. I cannot read the text in the control properties.

**Simhub version**
9.2.4

**Windows version**
10

**To Reproduce**
1. Open the Dash Editor
2. Click on any control
3. See error

**Expected behavior**
The text can be read.

**Screenshots**
![dash_editor](https://github.com/SHWotever/SimHub/assets/112815/4de785f1-fc13-45d7-8339-c2706f69cb96)

**Log files**

[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/14500333/SimHub.1.txt)

**Comment by SHWotever** [comment]
Hi ! Thanks for noticing, it's fixed for the next version ! 
In the wait you can edit `{SimHub install directory}\PluginsData\GlobalSimhubSettings.json` with your favorite text editor and set `AppThemeName` to `BaseDark`

![image](https://github.com/SHWotever/SimHub/assets/2207331/6b90e841-9437-4c7e-8190-b2b16c8e1e34)

**Comment by cnetthoefel** [comment]
Awesome 👍 Thanks
