### ISSUE TITLE
From time to times, it stops sending signals to bass shakers.

### ISSUE THREAD

**Issue by flaengel** [SHWotever/SimHub#1561]
Hey guys not sure if this was reported before, 

I was using **9.1.28**, perfect never had an issue whatsoever.

I built a new PC, and downloaded version **9.2.4**, with this version, seems to me like the program "crashes" from time to time (although UI is still responsive), but it completely stops sending signals to bass shakers. I have to restart sim-hub to get back working.

Currently playing AMS 2.

**Log files**
[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/14506389/SimHub.3.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/14506391/SimHub.1.txt)
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/14506392/SimHub.2.txt)

I'm not sure in which of the logs, might show, but if this was logged there's def. more than a couple of times in those logs from yesterday.

**Comment by flaengel** [comment]
Sometimes even in the testing channels separately with that "Test Now", cause of this "freeze state", that requires restarting. I don't necessarily need to be in the AMS2.

Cool will have a look, in this guides about USB's as well.

**Comment by SHWotever** [comment]
Definitely an usb amplifier issue then, is it a nobsound by any chance ? They have quite bad reputation

**Comment by flaengel** [comment]
No, it's not, but tbh I don't know what the actual manufacturer as it's branded by those who re-sell it. (the slip angle kit)

I'll do some more tests, and see if I have a USB2, to connect to the MB, or try to use it again through a power USB hub. (which I was using in my old setup, and never had this issue)

![20240306_120750](https://github.com/SHWotever/SimHub/assets/8862061/d6aa19ec-b04b-4d65-a4dd-201cda43bbeb)

**Comment by SHWotever** [comment]
Maybe a dumb question, if this is USB with 6 channels  that means it contains some kind of very specific chip allowing 5.1 over usb, I know a couple of them which proved to be unstable when using the wrong drivers. Did you install the correct drivers ?

**Comment by flaengel** [comment]
Finally got time to try further, updated bios, USB drivers, changed the port used, and have not experienced the issue so far again. Probably was not a software issue. Will close this issue. Thanks.
