### ISSUE TITLE
Changed leaderboard ranking?

### ISSUE THREAD

**Issue by Weini1972** [SHWotever/SimHub#1562]
Hi Nicolas. Thanks for the great last update! One point from me: My leaderboard now looks like this:

<img width="212" alt="image" src="https://github.com/SHWotever/SimHub/assets/96842558/dafa64b1-0868-4735-b3fe-12e8d6a1758d"> (or see attachment)
<img width="212" alt="Current Leaderboard ranking" src="https://github.com/SHWotever/SimHub/assets/96842558/7d721172-f8d7-496f-8643-799ecef377bf">

I couldn't find a setting that makes it possible for the first placed driver to be at the top of the board again and the last one at the bottom.
Maybe I just overlooked something, or set it up wrong.
Unfortunately, I can't say since when this has been the case. I went back to version 9.1.31. Unfortunately that didn't help either.

Many thanks for your help
Greetings

**Comment by SHWotever** [comment]
Hi !

I guess you are using ACC ? The position shown is now the official one coming from the game (while it was renumbered previously to match the on track real position :  https://github.com/SHWotever/SimHub/releases/tag/9.1.31

Now the position "shown" is the one from the official ranking (as shown in ACC hud) but the order is still the real time one (as before)

**Comment by Weini1972** [comment]
Thank you very much for your quick response!
Yes, it is ACC.
Wouldn't it be possible to display the leaderboard positions according to the rankings from 1-x from top to bottom in order?

ACC offers both variants in Hud mode, right?
I think this was also the case before version 9.1.31, or am I wrong?
<img width="367" alt="image" src="https://github.com/SHWotever/SimHub/assets/96842558/185ed3f5-dd16-450d-a3ac-e418fbdfeccc">

Kind regards.
