### ISSUE TITLE
Return drivers in pits via JavaScript

### ISSUE THREAD

**Issue by jessemillar** [SHWotever/SimHub#1563]
When using functions like `getopponentleaderboardposition_aheadbehind(relativeindex)` with iRacing, I never see drivers in the pits. As soon as they go in the pits, `getopponentleaderboardposition_aheadbehind(relativeindex)` returns the driver behind the driver that just went in the pits. Would you consider adding a second, optional argument to `getopponentleaderboardposition_aheadbehind` and `getopponentleaderboardposition_aheadbehind_playerclassonly` that allows for returning cars that are in the pits?

**Comment by SHWotever** [comment]
Hi !

You can change this behaviour here in settings : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/2d59f7c5-68d7-40c9-af8c-9de73373b49c)

Nicolas

**Comment by jessemillar** [comment]
Oh, neat! I'd never tried changing that dropdown because I assumed it only changed default dashboards. Good to know it affects the underlying JavaScript functions.
