### ISSUE TITLE
Clicking output tuning doesn't work

### ISSUE THREAD

**Issue by bertvankammen** [SHWotever/SimHub#1564]
**Describe the bug**
When I open the shakeit motors, I've a arduino one configured for speed.
The interface shows 1 motor connected. But when I select the tab 'Motors output' and then click on the button 'Output tuning' no window is shown.

**Simhub version**
9.2.5

**To Reproduce**
as described before.

**Expected behavior**
The popup with output tuning options should appear

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/14592912/SimHub.txt)

**Additional context**
I have a arduino one with a cytron MD10 motor shield which I'll use as a wind sim.

**Comment by SHWotever** [comment]
Hi ! Thanks for your report ! IT's fixed for the next version.

**Comment by bertvankammen** [comment]
Hello, that's great news.
Much appreciated.
