### ISSUE TITLE
GT7 - Make data available even when playing replay

### ISSUE THREAD

**Issue by DesmoGiec** [SHWotever/SimHub#1565]
Hello,
I'd like to have datas to be available when playing replays.
That'll be very very useful if I want to create a clip/video edit of a certain driver, or in order to have the possibility to analyze better a certain race incident/episode.
I know that datas are available even in replays, what do you think in enabling simhub to process them even for the replays?
Thanks

**Comment by Tallicia** [comment]
Currently replays are saved from GT7, but when I try to play them in replay, nothing happens. Is this a bug? Or is there something needed to have the replay iterate through the data and display it in the DDU/overlay? I also wonder if there is any IDP telemetry packet sent when an in game replay starts that could sync the simhub telemetry replay to.

**Comment by DesmoGiec** [comment]
It's not a bug, simhub doesn't collect datas from replays on purpose, replay do send udp datas. (verified with gt7 telemetry tool)
I saw @SHWotever labeled this as enhancement, but don't know if he's gonna do something about.

**Comment by Tallicia** [comment]
So that's 2 issues - 1 is it should allow us to choose to show DDU display telemetry when UDP data is sent whether a replay or live, and also a bug that saved replay data in SImhub from Gran Turismo 7 do not play.

**Comment by SHWotever** [comment]
I close, indeed since there is no udp data, it is a game limitation, since it's unofficial hard to ask the game developers enhancements for an interface which is not even official. but in all cases as soon as I can replays are not taken into account to avoid messing  up with all the tracked data.
