### ISSUE TITLE
fault with stream deck iracing

### ISSUE THREAD

**Issue by mrloseth** [SHWotever/SimHub#1566]
Hello. I have recently had major problems with the stream deck when I drive, this started in lates update on simhub. The problem is only as soon as the game starts and im ready to race the stream deck freezes, it can take a long time before it reacts if it does anything at all.
as soon as I close the game and am on the iracing menu everything is normal.
have tried a new profile stream/ changed the USB entry many times. and tried and only have few active buttons. but anyway, only when i run iracing this happens. Worked perfecly 2 year’s now and suddenly this after latest updates.  Any help

if i close the simhub app i can use the stream deck. so thee simhub does something i cant find.

i launch iracing true simhub

**Comment by SHWotever** [comment]
Hi ! I had no other reports of issues with streamdeck ? Are you using third party plugins in the streamdeck software tied to simhub which would be the culprit ? 

Overall I would think at an USB overload as described here : https://github.com/SHWotever/SimHub/wiki/USB-Issues-Troubleshooting as this is the typical symptoms of sound cards taking all the bandwidth.

Could you also fill the template as requested here ? https://github.com/SHWotever/SimHub/issues/new?assignees=&labels=triage&projects=&template=bug_report.md&title= this will give me a better overview.

Another tip, SimHub is extremelely modular so it's easy to disable major features one by one to locate the one which could trigger your issue, can you try to disable them to see if one in particular is tied to your issue ?  
![image](https://github.com/SHWotever/SimHub/assets/2207331/104840c9-9b0e-4e8d-abf2-698f7c62cc4b)

**Comment by FullPace** [comment]
I had this behaviour once but it was gone after a restart.
I assumed it might be something with the pre-martin plugin since this is the only relation I could see between Simhub and Streamdeck.
