### ISSUE TITLE
Circular Gauge not showing gauge image with HTML renderer

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1570]
When using HTML rendering mode  images used with the circular gauge are not showing up. In WPF mode everything works as intended

![Screenshot 2024-03-17 134143](https://github.com/SHWotever/SimHub/assets/116221480/365ab9ad-4b8f-4bf9-ace9-7eea4f063199)
![Screenshot 2024-03-17 134122](https://github.com/SHWotever/SimHub/assets/116221480/4bab4fc3-99fb-4885-91ac-6a41b70b9e81)

**Comment by SHWotever** [comment]
Hi ! 

Thanks for the report, it's fixed for the next version !

Nicolas
