### ISSUE TITLE
Issue with Arduino Serial port selection

### ISSUE THREAD

**Issue by Petersua** [SHWotever/SimHub#1573]
I am unable to select a arduino serial port to connect my arduino for wind simulator. There is no list to choose from when i select the dropdown tab

![Screenshot 2024-03-20 203044](https://github.com/SHWotever/SimHub/assets/164281138/0a3acbb4-324e-4cf9-846a-452dd6ee21dd)

**Comment by SHWotever** [comment]
Hi ! Usually that's caused by a faulty WMI repository used to extract some additionnal informations about serial ports, could you try to repair it ? 
https://www.thewindowsclub.com/how-to-repair-or-rebuild-the-wmi-repository-on-windows-10
