### ISSUE TITLE
F1 Championship standings

### ISSUE THREAD

**Issue by HBrooks04** [SHWotever/SimHub#1578]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the F1 TV championship standings and it only appears to load the default. I've selected use Gary Swallow file and it still only shows the default. I have updated to show an accurate championship standings in the format suggested in the notes but when I save and load it it doesn't change. I've put nationality flags in as I thought it might fix it but it still won't work. And ideas or tutorials on how to get it to work properly as I really want to use it on an F1 23 series I'm doing.
Thanks.

![IMG_20240328_183014](https://github.com/SHWotever/SimHub/assets/165318498/c542846b-531e-465f-9128-dddf4949b528)

**Comment by SHWotever** [comment]
Hi !

Third party plugins like Gary swallow are supported by their respective authors. Do not hesitate to contact them directly for questions and help about those specific content. 

Best regards,
Nicolas
