### ISSUE TITLE
request: Ability for events to switch pages

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#158]
Hey,

Just had a thought. Would it be possible to implement the ability for an event to trigger switching to a certain page. 

For example if the oil temp got too high it switched to the oil temp page.

**Comment by sjdawson** [comment]
I recently tried to do something like this, and discovered that the only way I could mimic it was to have a full-screen overlay appearing for a short time. I'd prefer an events based system, like how the SerialDashPlugin does "DisplayScreenForXs". 👍

**Comment by SHWotever** [comment]
Hi I close this since dedicated conditional overlays are now available in simhub.
