### ISSUE TITLE
Bass Shakers stop working in iRacing

### ISSUE THREAD

**Issue by Jk706** [SHWotever/SimHub#1580]
**Describe the bug**
Bass Shakers stop working and SimHub crashes in iRacing

**Simhub version**
9.2.7

**Third party plugins**
Don't know but I'm running Moza PitHouse V1.2.4.39, Meta Quest Link App V 63.0.0.216.361 in addition to SimHub an iRacing.  I use a Nobsound Mini amp connected via mini usb to usb 2.0.  Connected to a 3.0 powered usb hub.  

**To Reproduce**
Don't know how to tell you this.  Not a programmer just a user.

**Expected behavior**
I expect the bass shakers to work and all of the effects in my profile to be accurate.

**Screenshots**
Dont have any.

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files :[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/14809206/SimHub.1.txt)
**Additional context**
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/14809207/SimHub.2.txt)
[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/14809208/SimHub.3.txt)
[SimHub.4.txt](https://github.com/SHWotever/SimHub/files/14809209/SimHub.4.txt)
[SimHub.PackageManager.Standalone.1.log](https://github.com/SHWotever/SimHub/files/14809210/SimHub.PackageManager.Standalone.1.log)
[SimHub.PackageManager.Standalone.2.log](https://github.com/SHWotever/SimHub/files/14809211/SimHub.PackageManager.Standalone.2.log)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/14809212/SimHub.txt)

**Comment by Patrock2503** [comment]
It seems, that i have the same issue. Furthermore, I can describe that I use a Simagic Bassshacker Motor. As soon as I enter the car (in my case the F4) the Basshaker only shakes like 2 % of normal (when testing with simhub). As soon (still in Iracing) as i leave the car, the shaker works as usual, i tested that several times.. 

Does anyone have an idea ??

**Comment by Jk706** [comment]
My issue ended up being usb hub. Whether powered or unpowered. Once I connected directly to pc it worked fine.
