### ISSUE TITLE
govee light h6056 connects but has lighting issue

### ISSUE THREAD

**Issue by beastlyfern** [SHWotever/SimHub#1581]
**Describe the bug**

I have connect the h6056 govee light and have it working fine is simhub except there is one issue. This light has two bars and each bar has three light sections which is represented by the 6 selection areas for the screen capture. My issue is that one of the lights has three distict sections that light up indivdually when I activate the selection area. But the other one has two and when  activate the third one it lights up both bottom sections on each light.  Not sure if this is a simhub issue or just my light but they seem to fuction properly with the govee app. 

**Simhub version**
Running latest vershion

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**
I expected the both light to have three distinct sections but for some reason one of the 6 selector areas ligth up both bottom parts on each light. 

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

Thanks for any help with this issue

**Comment by SHWotever** [comment]
Hi ! 

This is a known govee issue through the "dream light" API, there are 10 uneven segments; https://github.com/SHWotever/SimHub/wiki/Ambient-lights#govee-lights

When I o implemented govee lights I contacted govee support, they said it would be fixed but it's still waiting since.
