### ISSUE TITLE
[REPLAY] Recherche de caractères parmi le libellé

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1582]
Hello
J'ai beaucoup de replay....c'est tellement pratique
Serait-il possible d'ajouter la possibilité de filtrer sur la DESCRIPTION afin d'afficher uniquement les replays qui m'intéressent
Merci

ex : {
  "StartDate": "2021-01-28T14:42:42.1120887+01:00",
  "EndDate": "2021-01-28T14:44:51.990632+01:00",
  "CarModel": "Porsche 911 GT3 R",
  "TrackName": "Portland Full Course",
  "Description": "temperature pneus freins"
![1](https://github.com/SHWotever/SimHub/assets/58605557/949aeac0-fa67-4390-800f-41313f1fa37c)

}

**Comment by SHWotever** [comment]
Hello ! 

Merci pour la suggestion je clôture car c'est un doublon de https://github.com/SHWotever/SimHub/issues/700
