### ISSUE TITLE
No tyre wear data on ACC

### ISSUE THREAD

**Issue by havetimeforfun** [SHWotever/SimHub#1586]
**Describe the bug**
No tyre wear data on ACC, always display 0

**Simhub version**
9.2.6

**To Reproduce**
Going for a few laps in ACC in practice MOD with tyre wear on 
Finding the wear level still remains to be 0

**Comment by SHWotever** [comment]
Hi unfortunately Kunis is not providing tyre wear on ACC, the field exists as an inheritance from ac telemetry format, but no data is provided
[ACCSharedMemoryDocumentationV1.8.12.pdf](https://github.com/SHWotever/SimHub/files/14879979/ACCSharedMemoryDocumentationV1.8.12.pdf)
