### ISSUE TITLE
ALL LEDs/Some Dashes Reset While Driving

### ISSUE THREAD

**Issue by RetroCoffin** [SHWotever/SimHub#1587]
Randomly while racing, some of the displays and ALL LEDs go thru the car startup sequence in iRacing, meaning, they behave as if I have just started the car (even tho I'll be driving at that time). (SEE ATTACHED VIDEO)
- Devices are connected to POWERED USB HUBS (x3 hubs).

Devices used: 
- Pacelogic Pro (Phone, on the side) 
      - Ignition on/off comes on
      - Engine On/Off comes on 
LED/Arduino:
- GRID Porsche DDU 10  
     - All LEDs go thru the car start up sequence
        - Profile Used: GRID 10" DDU 4-16-4
- Sim Racing Addict Flag Box
     - Flag Box goes thru start up sequence (Ignition, car on, flags and gears) before returning to normal 
     - Profile Used: Daniel Newman Racing v3.3
- GSI X-29 
- Profile Used: Daniel Newman Racing 3.3

**Simhub version**
Simhub V 9.2.7 (Has been happening for several versions) 

**Third party plugins**
- Plug Ins disabled, bug still occurs

**Expected behavior**
I expected the dashes to behave normally, however, they're cycling randomly thru the start up sequence during race conditions.

**Screenshots**
N/A

[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/14895307/SimHub.1.txt)
[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/14895308/SimHub.3.txt)

https://github.com/SHWotever/SimHub/assets/117508061/75a58eac-84bc-4b1f-9710-8618f8569715

**Comment by SHWotever** [comment]
Hi ! 

This looks like a telemetry fault. By any chance did you catched it in a Simhub replay ? I suspect iracing to have more unreliable telemetry in multiplayer sessions, but I don't want to "pollute" online races just for testing.

**Comment by RetroCoffin** [comment]
> Hi !
> 
> This looks like a telemetry fault. By any chance did you catched it in a Simhub replay ? I suspect iracing to have more unreliable telemetry in multiplayer sessions, but I don't want to "pollute" online races just for testing.

File size too big to upload apparently, it's not even a full lap's worth, but yeah I have all replay data for simhub (json, jsonidx and metadata)

**Comment by RetroCoffin** [comment]
I could drop the files in the discord server tho, just let me know where?

**Comment by SHWotever** [comment]
Hi !
Unfortunately discord is really limited too int term of upload size, https://wetransfer.com/ should do the trick ;)
Thnaks a lot !

**Comment by RetroCoffin** [comment]
https://mega.nz/file/BWk0yKZK#tqcqAQSG-MBKwTQK4m5B6vEb0upmm4zugaAJzr2RqZw
https://mega.nz/file/8GV1SarC#okCLz7FoO2hgQL_lpboSQGl92TTI2IwzMM0yRhusS7g
https://mega.nz/file/9TVnlISQ#1AlZ4lAsoSPEhWNEsOVzPxEribIqOEkcEzcHrzZCxHU

Here's the data from the session from the video (I think). I've experienced this in both multiplayer sessions and test drive at a 50/50 rate, sometimes it happens several times thru a session, sometimes not at all.

**Comment by SHWotever** [comment]
Hi ! Thanks for the log I confirm it's an iracing bug, data get's update correctly but for one single frame it suddenly reports a 0 rpm, then gets back to life triggering all the motor start animations. I will try to add a workaround to "skip" this bad data frame.
