### ISSUE TITLE
9.2.8 official release - Main display blackout

### ISSUE THREAD

**Issue by NYCspaces** [SHWotever/SimHub#1588]
Maybe an isolated incident but is anybody else getting screen blackouts with 9.2.8 upgrade? iRacing, 4090, 2 vocors - CSX3 and Sim Racing Addict 6.9, LG Monitors, everything was fine until I tested after doing the 9.2.8 release version update. Center screen (of my main racing display not the DDU)  randomly is going to black for about a half second or so, comes back no tearing or stuttering otherwise.  Originally triggered Solepec plugin errors in Simhub, switched to LR and it seemed fine until I rebooted and started in Lovely and also got the screen blackouts but no errors in the log files.

**Third party plugins** Have not tried this yet but will.

**Comment by SHWotever** [comment]
Hi ! 

I replied you on discord so I'm pasting the answer here ;)

I hardly see the update to cause it, just in case all the previous versions are available here for testing : https://github.com/SHWotever/SimHub/releases

A monitor blackout for me is either hardware or driver.

**Comment by NYCspaces** [comment]
Seems correct, it appears to be an Nvidia driver update solved it, but the only change that triggered it originally was the 9.2.8 update. Thanks for your amazing product and support. Sorry about the double posting, I am sure you don't need both. Doug

**Comment by SHWotever** [comment]
Thanks for your feedback!
