### ISSUE TITLE
Ipad issue "This dash does not exists anymore, redirecting you to the list"

### ISSUE THREAD

**Issue by Gilol68** [SHWotever/SimHub#1589]
**Describe the bug**
I launch my dash on the ipad everything works as it takes a few minutes "variable" and this message appears "This dash does not exist anymore, redirecting you to the list"

**Simhub version**
9.2.6

My ipad was a mini first génération on usb. I have no problem with my other devise a old smartphone no-name usb and a additional screen on HMDI. 
![20240411_144821](https://github.com/SHWotever/SimHub/assets/166722035/53c158f5-8383-46f7-b694-976025775fbf)

**Comment by SHWotever** [comment]
Hi  ! Can you join the log files as requested in the issue template so I can have better insights ? https://github.com/SHWotever/SimHub/issues/new?assignees=&labels=triage&projects=&template=bug_report.md&title=

**Comment by Gilol68** [comment]
[SimHub.txt](https://github.com/SHWotever/SimHub/files/14946593/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! 

I fear an ipad mini first gen is ios 9 ? IOS 10 was the minimum recommended : https://github.com/SHWotever/SimHub/wiki/Troubleshoot-Dashstudio-Web-access#ios

Unfortunately Apple has been always off the technology standards and ios 9 was totally off of them,, later versions were not completely better, that said) even if the hardware could be capable of it, the safari browser was close to "IE" (a norm aside of the norm) at this time and not supporting properly the standard.

**Comment by Gilol68** [comment]
Yep the iPad was on IOS9 and no more update for this génération... But that working and for no reason apparently that loose the "network" the probleme was the iPad and after all test i think taht was dead . I try here to find a miracle :)

**Comment by Gilol68** [comment]
I find a solution.... with the APP simhub i have issue but if i use the safari browser  it's work...
