### ISSUE TITLE
Repeated item cut when the item is outside of the dashboard with HTML renderer

### ISSUE THREAD

**Issue by kaiusl** [SHWotever/SimHub#1590]
**Describe the bug**

Noticed a case when a repeated item gets partially cut or completely hidden on a dash board.
For it to happen following must be true:
  * Item must be at least partially outside of the dashboard
  * Item must be inside a folder which is itself inside a repeated folder
  * HTML renderer must be used. The item doesn't get cut with WPF renderer.

**Simhub version**
9.2.8

**To Reproduce**

1. Download the example dash [Repeat_cut_bug.zip](https://github.com/SHWotever/SimHub/files/14962834/Repeat_cut_bug.zip)
2. Test this dashboard with HTML renderer and notice how the second column of text gets cut.

**Screenshots**

![Repeat_cut_bug](https://github.com/SHWotever/SimHub/assets/37976028/76bb59ea-149b-41a6-95e1-00a31f4b7531)

**Comment by SHWotever** [comment]
Hi ! Thanks for the report, indeed the widget should not have overflowed in wpf, I will make sure it get cuts as it should.

**Comment by SHWotever** [comment]
My bad I misunderstood the issue ;) It's fixed for the next release. it will be allowed to overflow

Nicolas

**Comment by SHWotever** [comment]
Hi ! The fix has been released in the latest version ;)
