### ISSUE TITLE
Custom Serial Devices Plugin not sending data in 9.2.8

### ISSUE THREAD

**Issue by betaeffect** [SHWotever/SimHub#1591]
My Arduino Pro Micro will not receive any UART data from Simhub ver. 9.2.8. 
The controller will receive data from hterm and older versions of Simhub (9.2.5)
Have not tried ver. 9.2.10 yet.

**Simhub version**
Latest version (9.2.8) does not work, older version is ok.

**Third party plugins**
no 3rd party plugins enabled

**To Reproduce**
1. install simhub version 9.2.8
2. flash arduino with UART echo program
3. try to send UART data within the Custom Serial Devices plugin

**Comment by SHWotever** [comment]
Hi ! 

Thanks for the report, I released an hotfix : https://github.com/SHWotever/SimHub/releases/tag/9.2.11
