### ISSUE TITLE
LMU TC/ABS

### ISSUE THREAD

**Issue by RodentYell** [SHWotever/SimHub#1592]
Wasn't to sure where to put this, anyway noticed you done this in 9.2.8

Fix : Disable LMU TC/ABS signal being completely flawed, hoping for a clear data being added the SDK in the future) ..LMU devs if you hear me … please !!

I can assure these on my base shakers the effects were working in 9.2.7..I installed 9.2.9-9.2.11 and there was nothing while braking and and pulling away fast, re-installed 9.2.7 back again and the effects were back again, so using the brakes the ABS active effect was working again as well as the TC effect, so for the moment I will stay with 9.2.7 or hopefully you will activate it again in a fix please...

**Comment by SHWotever** [comment]
Hi ! Unfortunately It was triggering a lot of false positives when braking or when accelerating, the experience might vary depending of the car/game settings or model, but in lot of conditions it was triggering completely wrongly. Currently I was using some "magic" sauce watching the brake bias versus brake pressure and some other tricks but they work really badly with LMU which forced me to disable it until a proper data is available.
