### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object. at SimHub.Plugins.DataPlugins.RGBDriver.LedResult.Merge(LedResult ledResult, Nullable`1 startPosition)

### ISSUE THREAD

**Issue by jason-murray** [SHWotever/SimHub#1593]
**Describe the bug**
My Scripted Content block is not working, it blacks out the whole wheel. The log file is full of RGBDriver errors (1 per ms).

**Simhub version**
SimHub 9.2.10

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**
1. Load ledprofile to Individual Leds for Simagic GT NEO wheel.
2. Observe that LED preview bar is black although ROTARIES scripted content block indicates that LEDS should be on.
3. Toggle the BOTTOM ROTARY COLOUR CYCLE effect group above the ROTARIES block to see more strange behaviour.

**Expected behavior**
The LEDs array returned from the block applied to the wheels LEDs.

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

[IRacing - Deleter's GT Neo - iRacing (v7).ledsprofile.json (renamed to allow upload with .json extension)](https://github.com/SHWotever/SimHub/files/15002307/IRacing.-.Deleter.s.GT.Neo.-.iRacing.v7.ledsprofile.json)

![Screenshot 2024-04-16 214152](https://github.com/SHWotever/SimHub/assets/9424106/b3001789-8fc1-4492-822b-d62250e7f824)
![Screenshot 2024-04-16 214211](https://github.com/SHWotever/SimHub/assets/9424106/ed99791b-0036-4ed5-8edf-75c72fa54b6c)
![Screenshot 2024-04-16 214226](https://github.com/SHWotever/SimHub/assets/9424106/f6545820-0ad3-4f63-9153-e83edbfedd09)

[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/15002313/SimHub.2.txt)

**Comment by SHWotever** [comment]
Thanks again for your report, I've released the hotfix : https://github.com/SHWotever/SimHub/releases/tag/9.2.12
