### ISSUE TITLE
ambiemt lights, ws2812b and matrix not working

### ISSUE THREAD

**Issue by amiyamin** [SHWotever/SimHub#1595]
**Describe the bug**
ambiemt lights, ws2812b and matrix not working. no simulation preview on the leds and matrix. no preview on ambient.

everything else runs fine {shakers, wind, buttons]

**Simhub version**
latest

**Third party plugins**
none

**To Reproduce**
1. Go to 'arduimo leds..'
2. Click on 'anything to turn leds on.'

**Expected behavior**
leds should work;

logs are 50mb

**Comment by SHWotever** [comment]
Hi ! could you join at least the latest log file ? 

Can you confirm you are running 9.2.12 ? https://www.simhubdash.com/download-2/

**Comment by amiyamin** [comment]
Hi. Thanks for replying!
I am using the latest version (trouble had started two versions ago, with the ambient light that stopped working. After the current update, all LEDs stopped working).
I will try and compress the log files or send it via Google Drive or similar.

**Comment by SHWotever** [comment]
Thanks !
