### ISSUE TITLE
CLI batch configuration import

### ISSUE THREAD

**Issue by mattlsp** [SHWotever/SimHub#1597]
It would be awesome if SimHub would allow passing of custom configuration file to omit lots of clicking in the UI for nth time if you already have all tweaked values for certain aftermarket device etc 

I mean something like this:

simhub.exe -[json import flag] [json file as an argument]

**Comment by SHWotever** [comment]
Hi ! Overall I guess you are talking about DIY Arduino? Overall it would not be appropriate to import and crush all users settings for the other devices they may already have. They would need to be merged but it's full of little details.

For your own usage, you can backup and copy paste the individual settings files which are stored in the pluginsdata folder.
