### ISSUE TITLE
Controll Mapping Assistant not available if Dash Studio is disabled

### ISSUE THREAD

**Issue by dunderjester** [SHWotever/SimHub#1599]
**Describe the bug**
Can't access the "mapping assistant" page if the Dash Studio plugin is disabled.

**Simhub version**
Happens in 9.2.9 and 9.2.12, I haven't checked any other version.

**Third party plugins**
None.

**To Reproduce**
1. Enable the Control mapper plugin
2. Disable the Dash studio plugin
3. Visit `http://LOCAL_IP:8888/ControlMapper`
4. Get a blank page
5. Check the browser developer tools:` /ControlMapper` returns a `404`
6. Enable the Dash studio plugin
7.  Visit `http://LOCAL_IP:8888/ControlMapper`
8. Control mapper loads as expected

**Expected behavior**
I expected Control Mapper assistant to work independently of the Dash studio plugin. Granted it's not a big deal to have Dash studio enabled, but I disabled it since I don't use it and didn't expect that hidden dependency.

**Log files**
[Logs.zip](https://github.com/SHWotever/SimHub/files/15135970/Logs.zip)

**Comment by SHWotever** [comment]
Hi ! 

Thanks for the report ! It's fixed for the next version.

Nicolas
