### ISSUE TITLE
Sim Hub Auto Detect Issue

### ISSUE THREAD

**Issue by TinPeach** [SHWotever/SimHub#1601]
**Describe the bug**
SIm Hub is not auto selecting the game upon starting the game - the game needed can only be selected once the actual game is open and running. Sim Hub keeps reverting back to Assetto Corsa unless another game is open, like AMS2. The attached screen grab shows the system log which is constantly updating as shown - it never stops.

**Simhub version**
9.2.6

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**
1. Open Sim Hub
2. Open a game
3. Game is not being selected unless manually selecting which can be achieved when the game is running

Also
1. Open Sim Hub
2. Click on different game to Assetto Corsa - such as AMS2
3. Sim Hub clicks back to Assetto Corsa

**Expected behavior**
Sim Hub to auto select the game upon opening or at least allow me to select a game without having to run the game first

**Screenshots**
![Screenshot 2024-04-28 211359](https://github.com/SHWotever/SimHub/assets/168373979/9d671c46-740e-4926-970b-fecf5d05b94e)
![Screenshot 2024-04-28 212102](https://github.com/SHWotever/SimHub/assets/168373979/76e2909c-ba6d-4826-aeef-878a961e5c0a)

**Log files**
Join log files available in C:\Program File
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/15143615/SimHub.1.txt)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/15143616/SimHub.txt)
s (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
This is a recent problem, last week or so.

**Comment by SHWotever** [comment]
Hi ! Could you check in the tanks manager if there is an application  with one of those processes names ? ACS ACS_x86 acs_dmm AssettoCorsa (the case does not matter) it seems to be a process being stuck or regularly starting. Maybe another software using the se process name ?

**Comment by TinPeach** [comment]
Many thanks for replying. 

Not that I can see - but I am not massively computer literate - apologies. The attached are all I can see in Task Manager, is there a sub menu I should look in?

![Screenshot 2024-05-01 105544](https://github.com/SHWotever/SimHub/assets/168373979/8d2f0b91-49de-4f76-9e59-3750b7890d3b)
![Screenshot 2024-05-01 105632](https://github.com/SHWotever/SimHub/assets/168373979/76549fe6-daaf-462b-bd1b-283998289280)
![Screenshot 2024-05-01 105657](https://github.com/SHWotever/SimHub/assets/168373979/bd2fbc0e-de37-4f3a-aead-2be9b728834d)
![Screenshot 2024-05-01 105719](https://github.com/SHWotever/SimHub/assets/168373979/5c6d29ff-6068-48e1-be75-fca56a4a4f09)
![Screenshot 2024-05-01 105754](https://github.com/SHWotever/SimHub/assets/168373979/35fb627a-8d03-442a-a97a-81eab194e811)

**Comment by TinPeach** [comment]
I did find this in the details tab, but I cannot end task when selected so not sure if this the problem or what to do - sorry again.

![Screenshot 2024-05-01 110800](https://github.com/SHWotever/SimHub/assets/168373979/494efe58-6d44-4bca-9977-562e4b019374)

**Comment by SHWotever** [comment]
Hi ! It looks old like the process is getting stuck. Does it appears only after running the game (typically after a fresh boot) ?. This could be caused by some mods not releasing resources correctly for instance. Have you updated/installed some mods recently? 
Since the process still exists it will trigger the automatic detection. As a workaround if you can't find the root cause of the ac process keeping stuck you can disable automatic detection in simhub settings.

**Comment by TinPeach** [comment]
Thank you for all your help, I seem to have solved the problem - unfortunately being of the older persuasion I can't remember exactly what I did. I do remember I switched something from being software handled to hardware, and that seemed to do the trick. If do remember, I will post it in case anyone else experiences the same. But all good and working perfectly, thank you again.
