### ISSUE TITLE
led brightness control not lightning up the leds

### ISSUE THREAD

**Issue by georgi-iovchev** [SHWotever/SimHub#1602]
When I change my leds brightness, the leds are not showing me live preview (no matter if the "brightness change" option is on in Settings)

I am on version 9.2.12. Before that I was on 9.1.29 and this functionality was working.

![image](https://github.com/SHWotever/SimHub/assets/23377650/5c28bdb5-2472-4319-bd9c-1e7aa267eafe)

Last log file : [SimHub.txt](https://github.com/SHWotever/SimHub/files/15154543/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! 

Thanks for the report it's fixed for the next version,

Nicolas
