### ISSUE TITLE
SimHub Shake-It Motor issue with Simagic HPR in iRacing

### ISSUE THREAD

**Issue by mikhael47** [SHWotever/SimHub#1603]
**Describe the bug**
HPR activates when testing inside SimHub but does not work in game.  Simhub 9.1.29 worked 

**Simhub version**
9.2.12

**Third party plugins**
none

**To Reproduce**

**Expected behavior**
Motor should rumble when ABS is activated

**Screenshots**
![simhub1](https://github.com/SHWotever/SimHub/assets/103081387/b7fef4c7-8178-4fc0-ab13-f6eecd9a1161)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/15170891/SimHub.1.txt)
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/15170892/SimHub.2.txt)
[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/15170893/SimHub.3.txt)
[SimHub.4.txt](https://github.com/SHWotever/SimHub/files/15170894/SimHub.4.txt)
[SimHub.PackageManager.Standalone.1.log](https://github.com/SHWotever/SimHub/files/15170895/SimHub.PackageManager.Standalone.1.log)
[SimHub.PackageManager.Standalone.2.log](https://github.com/SHWotever/SimHub/files/15170896/SimHub.PackageManager.Standalone.2.log)
[SimHub.PackageManager.Standalone.3.log](https://github.com/SHWotever/SimHub/files/15170897/SimHub.PackageManager.Standalone.3.log)
[SimHub.PackageManager.Standalone.4.log](https://github.com/SHWotever/SimHub/files/15170898/SimHub.PackageManager.Standalone.4.log)
[SimHub.PackageManager.Standalone.5.log](https://github.com/SHWotever/SimHub/files/15170899/SimHub.PackageManager.Standalone.5.log)
[SimHub.PackageManager.Standalone.log](https://github.com/SHWotever/SimHub/files/15170900/SimHub.PackageManager.Standalone.log)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/15170901/SimHub.txt)

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Could you check that the rumble motors option is disabled in iracing? They added it recently and it takes control over simhub for the motors.

**Comment by mikhael47** [comment]
I uninstalled, rebooted, then re-installed and it seems to be working now.

Setup is 
P1000i
Simpro feedback setting is off
iRacing vibrate setting is unchecked
