### ISSUE TITLE
Control Mapper Streamdeck Plugin, multi action compatibility 

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1604]
When using the Control Mapper Plugin (Role) in a multi-action, the button gets stuck. 
When checking on the control mapper page the button is lid up until a Simhub restart,

**Comment by SHWotever** [comment]
Hi ! 
I guess it's not triggering the press and release events in order.
Currently to have a "one one" behaviour (virtual controller being pressed at the same time as the button) it's kept held as long as the physical button is.
I will try to make it compatible with multi action is it's possible.

**Comment by SHWotever** [comment]
Hi ! Actually this was less "complicated" than I expected, I get correctly the press and releases but extremely fast causing a race condition. It's fixed for the next version !

**Comment by FullPace** [comment]
Hi, sorry to deliver bad news but I tested the update today and unfort. the keys still got stuck, even from a normal key (not in multiaction) it happened one time.

**Comment by SHWotever** [comment]
Erf :( 

I tried another approach, unfortunately this required to update the stream deck plugin itself : 
[com.wotever.simhubcontrolmapper.zip](https://github.com/SHWotever/SimHub/files/15281898/com.wotever.simhubcontrolmapper.zip)

Can you try this version ? I did not see any issues with those changes.
