### ISSUE TITLE
The SLI Plugin window does not work from version 9.02.9 onwards

### ISSUE THREAD

**Issue by MARVINALIEN** [SHWotever/SimHub#1605]
**Describe the bug**
SLI Plugin from version 9.02.9 cannot be configured because it does not show windows even if it seems to work in game. The problem is present from version 9.02.9 to the latest 9.02.12. Going back to version 9.02.8 the plugin window works correctly.

**Simhub version**
9.02.9 - 9.02.10 -9.02.11 9.02.12

**Third party plugins**
Nothing

**To Reproduce**

1 start simhub
2 enter SLI Plugin
3 Empty window

**Expected behavior**
the usual window shown up to version 9.02.08

**Screenshots**
![9 2 9 bug](https://github.com/SHWotever/SimHub/assets/168651411/e511e799-07e6-4d9b-865b-d9548334b77c)

![9 2 8 ok](https://github.com/SHWotever/SimHub/assets/168651411/7a780f12-6f59-42c2-bc04-1c8dcde6f4dd)

**Log files**
[Logs.zip](https://github.com/SHWotever/SimHub/files/15177765/Logs.zip)

**Comment by SHWotever** [comment]
Hi ! This is a third party plugin, could you report it to the author?

**Comment by MARVINALIEN** [comment]
For some strange reason I was convinced it was a native plugin, I apologize for the error, I reported it to the developer.
Thank you
