### ISSUE TITLE
InstantConsumption doesnt report

### ISSUE THREAD

**Issue by CreeBoom2020** [SHWotever/SimHub#1609]
Hello i have the problem that simhub doesn´t read the InstantConsumption_L100KM value from beamng, even just in the value add menu.

Here is the text that i have in simhub.
isnull([InstantConsumption_L100KM],'0') + ';' +

my simhub version is 9.2.15

I have the Truck Simulator and ShareData plugin form the bmw e46 cluster project

Thanks in Advance!

**Comment by SHWotever** [comment]
Hi !

It's fixed for the next version ;)
