### ISSUE TITLE
Request - simhub auto starts on selected page

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#161]
Hey,

For example when you first open simhub instead of it showing the game list have an option in settings for user to choose whatever page they want (dash studio, property's, settings) at startup.

**Comment by zegreatclan** [comment]
Looks convenient indeed, But with no doubt you want dashstudio as startup screen ? 
I was thinking about some "pin" to home screen (game list) feature for dashs. Are we agree it's the same objective ?

**Comment by Meekstaaa** [comment]
You are right I would like dash studio as startup.

A pin option would be a good way for it to work too!

Many thanks

David Meek
Sent from my iPhone

On 29 Oct 2017, at 15:33, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks convenient indeed, But with no doubt you want dashstudio as startup screen ?
I was thinking about some "pin" to home screen (game list) feature for dashs. Are we agree it's the same objective ?

**Comment by SHWotever** [comment]
Released with 6.7.8 ! It's now possible to choose which tab will be shown at startup
