### ISSUE TITLE
Arduino setup tool error

### ISSUE THREAD

**Issue by DPShillcock** [SHWotever/SimHub#1613]
**Describe the bug**
Unable to open Arduino sketch setup within simhub

I can open the sketch tool from the directory, however it is unable to upload sketch.

**Simhub version**
9.2.15

**Third party plugins**

**To Reproduce**
1. Go to Arduino
2. Click on  My Hardware
3. Click on Open arduino setup tool

**Expected behavior**
Setup tool opens

**Screenshots**

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/15346938/SimHub.txt)

**Additional context**

**Comment by DPShillcock** [comment]
A reinstall fixed this. Perhaps there was an unpacking issue?

**Comment by SHWotever** [comment]
Hi ! Looking at the log this looked like a missing package list file or a corrupted one. If the reinstall fixed it, I would think about a missing one.
