### ISSUE TITLE
Properties for PersistantTrackerPlugin.Driver* are gone from properties list

### ISSUE THREAD

**Issue by Havner** [SHWotever/SimHub#1614]
**Describe the bug**
The properties for:
PersistantTrackerPlugin.DriverAhead*
PersistantTrackerPlugin.DriverBehind*
are no longer visible in properties list even though they still work.

**Simhub version**
9.2.15

**Third party plugins**
None

**To Reproduce**
1. Go to Available Properties tab
2. Type "driver" -> empty list
3. Type "persistant" -> list doesn't contain any driver ahead/behind properties

**Additional context**
https://www.simhubdash.com/community-2/simhub-support/formula-for-driver-behind-ahead-gone/

**Comment by SHWotever** [comment]
Hi ! They have been replaced by more flexible functions : https://github.com/SHWotever/SimHub/issues/1598 The previously existing properties are not listed anymore to not still works to aveat breaking the existing dash
