### ISSUE TITLE
Game specific volume control doesn't work in LMU

### ISSUE THREAD

**Issue by Havner** [SHWotever/SimHub#1622]
**Describe the bug**
Game volume control doesn't work in LMU. Settings -> Global Controls -> Game Volume Control

**Simhub version**
9.3.1

**Third party plugins**
Disables

**To Reproduce**
1. Assign buttons for: Settings -> Global Controls -> Game Volume Control
2. Run LMU, enter track
3. Use the buttons
4. No effect

**Expected behavior**
The buttons to change game volume. The same buttons work for me e.g. in ACC. I do realize that those buttons change the system volume for a specific process. Not the in-game volume slider. And this is what I check. And this is what works for me in ACC but not in LMU. 

As a side not LMU registers two sliders for per process volume control. One seems to be in-menus, the other seems to be on-track. Maybe this is the issue? In any case the buttons change neither.

**Comment by SHWotever** [comment]
Hi ! I took a look and indeed I have 5 process spawn for lmu with no real visual distinction. I've added a prioritization toward the process having a titled window for the next version (which is the case only for the primary game process)

Nicolas
