### ISSUE TITLE
F1 2024

### ISSUE THREAD

**Issue by Homer1664** [SHWotever/SimHub#1625]
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by Homer1664** [comment]
NOT REALLY A BUG But Codemaster have really cocked up the Udp for tyres and rpm. No data is being picked up by sim hub

**Comment by SHWotever** [comment]
Hi ! Can you explain more in depth which data is not working/missing?

**Comment by SHWotever** [comment]
> [SimHub.1.txt](https://github.com/user-attachments/files/15576453/SimHub.1.txt) [SimHub.2.txt](https://github.com/user-attachments/files/15576455/SimHub.2.txt) [SimHub.3.txt](https://github.com/user-attachments/files/15576457/SimHub.3.txt) [SimHub.4.txt](https://github.com/user-attachments/files/15576458/SimHub.4.txt) [SimHub.5.txt](https://github.com/user-attachments/files/15576459/SimHub.5.txt) [SimHub.6.txt](https://github.com/user-attachments/files/15576460/SimHub.6.txt) [SimHub.7.txt](https://github.com/user-attachments/files/15576461/SimHub.7.txt) [SimHub.8.txt](https://github.com/user-attachments/files/15576462/SimHub.8.txt) [SimHub.10.txt](https://github.com/user-attachments/files/15576463/SimHub.10.txt) [SimHub.13.txt](https://github.com/user-attachments/files/15576464/SimHub.13.txt) [SimHub.14.txt](https://github.com/user-attachments/files/15576465/SimHub.14.txt) [SimHub.15.txt](https://github.com/user-attachments/files/15576466/SimHub.15.txt) [SimHub.16.txt](https://github.com/user-attachments/files/15576467/SimHub.16.txt) [SimHub.17.txt](https://github.com/user-attachments/files/15576468/SimHub.17.txt) [SimHub.18.txt](https://github.com/user-attachments/files/15576469/SimHub.18.txt) [SimHub.19.txt](https://github.com/user-attachments/files/15576470/SimHub.19.txt) [SimHub.20.txt](https://github.com/user-attachments/files/15576471/SimHub.20.txt) [SimHub.PackageManager.Standalone.1.log](https://github.com/user-attachments/files/15576472/SimHub.PackageManager.Standalone.1.log) [SimHub.PackageManager.Standalone.2.log](https://github.com/user-attachments/files/15576473/SimHub.PackageManager.Standalone.2.log) [SimHub.PackageManager.Standalone.3.log](https://github.com/user-attachments/files/15576474/SimHub.PackageManager.Standalone.3.log) [SimHub.PackageManager.Standalone.4.log](https://github.com/user-attachments/files/15576475/SimHub.PackageManager.Standalone.4.log) [SimHub.PackageManager.Standalone.5.log](https://github.com/user-attachments/files/15576476/SimHub.PackageManager.Standalone.5.log) [SimHub.PackageManager.Standalone.6.log](https://github.com/user-attachments/files/15576477/SimHub.PackageManager.Standalone.6.log) [SimHub.PackageManager.Standalone.7.log](https://github.com/user-attachments/files/15576478/SimHub.PackageManager.Standalone.7.log) [SimHub.PackageManager.Standalone.8.log](https://github.com/user-attachments/files/15576479/SimHub.PackageManager.Standalone.8.log) [SimHub.PackageManager.Standalone.9.log](https://github.com/user-attachments/files/15576480/SimHub.PackageManager.Standalone.9.log) [SimHub.PackageManager.Standalone.10.log](https://github.com/user-attachments/files/15576481/SimHub.PackageManager.Standalone.10.log) [SimHub.PackageManager.Standalone.11.log](https://github.com/user-attachments/files/15576482/SimHub.PackageManager.Standalone.11.log) [SimHub.PackageManager.Standalone.12.log](https://github.com/user-attachments/files/15576483/SimHub.PackageManager.Standalone.12.log) [SimHub.PackageManager.Standalone.13.log](https://github.com/user-attachments/files/15576484/SimHub.PackageManager.Standalone.13.log) [SimHub.PackageManager.Standalone.14.log](https://github.com/user-attachments/files/15576485/SimHub.PackageManager.Standalone.14.log) [SimHub.PackageManager.Standalone.15.log](https://github.com/user-attachments/files/15576486/SimHub.PackageManager.Standalone.15.log) [SimHub.PackageManager.Standalone.16.log](https://github.com/user-attachments/files/15576488/SimHub.PackageManager.Standalone.16.log) [SimHub.PackageManager.Standalone.17.log](https://github.com/user-attachments/files/15576489/SimHub.PackageManager.Standalone.17.log) [SimHub.PackageManager.Standalone.18.log](https://github.com/user-attachments/files/15576490/SimHub.PackageManager.Standalone.18.log) [SimHub.PackageManager.Standalone.19.log](https://github.com/user-attachments/files/15576491/SimHub.PackageManager.Standalone.19.log) [SimHub.PackageManager.Standalone.20.log](https://github.com/user-attachments/files/15576492/SimHub.PackageManager.Standalone.20.log) [SimHub.txt](https://github.com/user-attachments/files/15576493/SimHub.txt)
> 
> Describe the bug I use F1 23 telemetry in F1 24 since not all my devices have already updated to F1 24. Since the update to 9.3.1 the telemetry crashes often.
> 
> Simhub version 9-3-1
> 
> Third party plugins not used
> 
> To Reproduce Steps to reproduce the behavior:
> 
> Use F1 23 telemetry with UDP forwarding
> 
> Screenshots none
> 
> Log files included, i added all, not sure if you need something in particular.

Hi ! could you make sure to use F1 24 mode for F1 24 ? This is the recommended settings in simhub for this game, unfortunately back compatibility is often cause of troubles and I only ensure it works with the official telemetry version.
