### ISSUE TITLE
Windsim in ATS

### ISSUE THREAD

**Issue by Ginuwine3471** [SHWotever/SimHub#1626]
Morning,

Is there a way to add a wind feature in ATS or ETS for when you roll your window down (left or right independently), your windsim fan comes on? The velocity of the fan speed could change depending on the speed of the truck and the amount the window is open just like in a real vehicle.

**Comment by SHWotever** [comment]
Hi ! No I'm sorry, I don't have a telemetry channel to tell if and how much the window is open.
