### ISSUE TITLE
[Feature request] Turing Smart Screen 5 Inch Support  ( python library supported it and have the communications to it)

### ISSUE THREAD

**Issue by ftk789** [SHWotever/SimHub#1627]
**Is your feature request related to a problem? Please describe.**
No it's just a feature request.

**Describe the solution you'd like**
 Turing Smart Screen 5 Inch Support! Since [This Library file](https://github.com/mathoudebine/turing-smart-screen-python/blob/main/library/lcd/lcd_comm_rev_c.py) Already supports it! They have gotten the serial port commands to send information.

**Describe alternatives you've considered**
Nothing

**Additional context**
[Python file that supports it](https://github.com/mathoudebine/turing-smart-screen-python/blob/main/library/lcd/lcd_comm_rev_c.py)

[The Python Library for turing smart screens](https://github.com/mathoudebine/turing-smart-screen-python)

The good thing about this is that the refresh rate is high and it could be used for some really good stuff.

**Comment by SHWotever** [comment]
Hi ! Unfortunately there are many variations of those screens and they quickly become a trap . The homepage https://github.com/mathoudebine/turing-smart-screen-python with the many variations listed clearly shows that issue better than I can. Those screens quickly become a trap for users buying the wrong one or simply with support being broken later (AX206 is an example of that issue).
If one of those manufacturer give a hand to third party usage (ie SDK, documentation) which would settle down a "well known" list of models and protocols that would be possible. but for now it's too "dangerous".

**Comment by ftk789** [comment]
> Hi ! Unfortunately there are many variations of those screens and they quickly become a trap . The homepage https://github.com/mathoudebine/turing-smart-screen-python with the many variations listed clearly shows that issue better than I can. Those screens quickly become a trap for users buying the wrong one or simply with support being broken later (AX206 is an example of that issue). If one of those manufacturer give a hand to third party usage (ie SDK, documentation) which would settle down a "well known" list of models and protocols that would be possible. but for now it's too "dangerous".

Is there a way we ( as in whoever wants to make this possible outside your team ) can make this a possibility? I like how the refreshrate on the new 5 inch one is fast, SO I was wondering is there a way we can make some kind of a plugin and connect it there? I know there are too much, But best way for this is to make each user make their own plugin for each screen no?

**Comment by SHWotever** [comment]
Currently I don't have a public sdk for that, this part of simhub is rather complex to test as I'm also using process isolation to make absolutely sure a screen (which often uses low level usb API, IE libusb) won't make simhub crash in case of issue.  The code itself is pretty simple : clear, draw, brightness, but that process isolation makes it challenging. 

That said I tried the 2.1 round screen recently, because round screen (which is a form factor which is appealing, just like ultrawides), and the protocol was so awful that I gave up :(

**Comment by ftk789** [comment]
> Currently I don't have a public sdk for that, this part of simhub is rather complex to test as I'm also using process isolation to make absolutely sure a screen (which often uses low level usb API, IE libusb) won't make simhub crash in case of issue. The code itself is pretty simple : clear, draw, brightness, but that process isolation makes it challenging.
> 
> That said I tried the 2.1 round screen recently, because round screen (which is a form factor which is appealing, just like ultrawides), and the protocol was so awful that I gave up :(

Aww man, That's a bummer, Thank you for kind words and hard working. I don't blame you for not supporting all turing screens, I HOPED there was a way we can fully support the 5 inch screen but yea it is what it is, You can't do anything, I hoped there was a way for me to even make it, But yea thank you for your reply and i'm sorry for being annoying. <3
