### ISSUE TITLE
Cube Controls F-PRO led profile "slow" and laggy

### ISSUE THREAD

**Issue by GiuseppeC86** [SHWotever/SimHub#1628]
**Describe the bug**
Since the last 2 releases of SimHub, some of my F-PRO led assignments for certain functions such as Pit Speed Limiter blinking, ABS light feedback and headlight flashing became slow in their reactions and laggy.

**Simhub version**
9.3.3.

**Third party plugins**
Only one installed is Romain Rob Extra Properties plugin.

**To Reproduce**
Either via the "Force activation" setting or in game.

**Expected behavior**
Just like before the recent 2 SimHub builds, all LED assignments should kick-in and stop immediately when required, instead now, for example, they remain ON for a little while after e.g. ABS intervention or Pit Speed Limiter deactivation.

**Screenshots**
Not applicable.

**Comment by SHWotever** [comment]
Hi ! Could you join the logs and led profile so I can take a look? Thanks in advance.

**Comment by SHWotever** [comment]
Can you also specify if you are using usb ? The f-pro is know to have issues with Bluetooth, I don't know if they did roll out an update to fix that (and maybe slow down LEDs)

**Comment by GiuseppeC86** [comment]
> Can you also specify if you are using usb ? The f-pro is know to have issues with Bluetooth, I don't know if they did roll out an update to fix that (and maybe slow down LEDs)

Hello.
Yes, this is while using USB connection as always. No recent firmware/software updates from Cube (last update was on November 2023).
I confirm this issue came up with the latest 2 releases of SimHub, all the rest unchanged.
I have the same leds behaviour/speed both in my arduino dash and F-PRO, and the F-PRO is laggy most of the times compared to the Arduino board Leds (especially for Pit speed limiter where I have the blinking speed set at 50ms, but also ABS feedback and some other functions.

I would like to show you the log but I don't really know how to create one, sorry.

**Comment by SHWotever** [comment]
Thanks, so indeed Bluetooth is not the issue, You can find where to collect the logs and attach them in the bug template https://github.com/SHWotever/SimHub/issues/new?assignees=&labels=triage&projects=&template=bug_report.md&title=
