### ISSUE TITLE
Dasboard Freezes

### ISSUE THREAD

**Issue by Renegat2** [SHWotever/SimHub#1629]
**Describe the bug**
Dashoards freezes in iRacing during races. I use two different types of dasboards (rsc and lovely) on two seperate vocore screens (4.3" and 5") and i am using different usb cables and ports.  Both freezes in Race. This problem is new for me.

**Simhub version**
9.3.4

Nearly every Race. To restart, it helps to deactivate/activate the screens in simhub. Bass shakers and sim wind are working without problems even if the screens freezes.

**Log files**
[SimHub.txt](https://github.com/user-attachments/files/15848575/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! Indeed based on the log it does not look like an usb instability,

Hi ! could you disable any third party plugins first to be sure it's bound to simhub native features? 
![image](https://github.com/SHWotever/SimHub/assets/2207331/5f929cf9-fded-4262-8080-1f4827faeffa)

Lately there have been some breaking changes to the Iracing telemetry and there have been lot of troubles around it. (https://forums.iracing.com/discussion/63518/iracing-telemetry-is-bugged/p1?new=1)

Can you also make sure you are not using any "game optimization" feature ? If they strangle the rendering process that would explain why it silently freezes.
The major ones are 
- Windows game mode (search game mode in start menu)
- Process lasso
- Norton game optimizer

**Comment by Renegat2** [comment]
I disabled third party. There were RSC and YOEP GT. I started one race with no freeze. Btw. it happens more often withe Lovely Dashboard than RSC.

No Game Optimizer were running.

**Comment by SHWotever** [comment]
Thanks for the feedback. Actually the plugins are not directly related to the actual displayed dashboard. That's why I always ask to disable them, even if the related dashsboard not in use.
