### ISSUE TITLE
Sector Times Broken

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1631]
Hi,
I was trying to implement sector times overlay when I realized they are kinda broken.

Instead of being 0:00.000 they become null every lap which makes it hard to write the formulas.
(btw why can't null be always 0 so we can save all these extra isnull condittions?^^) 

A bigger issue is  "Last Sector Time" is only updating after sector 1.
It stays the same for the rest of the lap although the secor times change. 

Here's a screenshot showing sector index = 3 but last sector time is still sector 1 time.
![image](https://github.com/SHWotever/SimHub/assets/116221480/47eaba7c-6c21-4411-bfbb-f8495b4cacbc)

Thanks in advance 
Have a good one

**Comment by SHWotever** [comment]
Hello !

Can you specify the game ?

**Comment by FullPace** [comment]
i tested with replays of AMS 2 and i think it was ACC or Iracing.

**Comment by SHWotever** [comment]
Hi ! I've added a new property (since changing the actual one behaviour which has always been showing sectors times for the current lap would be too risky.

![image](https://github.com/SHWotever/SimHub/assets/2207331/7e095988-4590-49a8-9ef1-4b1e2180452d)

**Comment by FullPace** [comment]
Sorry to reopen this but it's still broken.
LastSectorTimeAnyLap is not updating reliably when SectorIndex is changing.
I can't find a pattern. Sometimes it's updating, very often not. 
Tested with ACC, AMS2 and iRacing (replay)
