### ISSUE TITLE
possible bug run once section (JS) override/conflict between elements

### ISSUE THREAD

**Issue by georgi-iovchev** [SHWotever/SimHub#1632]
**Describe the bug**
Value of a variable defined in run once section in one element override the value of variable with same name in other other element. Happens only if the main code part of the bindings of the elements are absolutely the same.

**Simhub version**
9.3.1, upgraded to 9.3.4 and the issue is there too

**Third party plugins**
no

**To Reproduce**
- A. In dashboard editor create new dashboard. Put two text items - (lets call them T1 and T2)

- B. Set text binding for T1 - computed value use javascript

// Run once javascript section
myvar = 1

// Javascript section
return myvar

- C. Set text binding T2 - computed value use javascript

// Run once javascript section
myvar = 2

// Javascript section
return myvar

- D. Save the dashboard
- E. Start the dashboard ( or "Test dashboard")

**Expected behavior**
Expected result is the "1" "2", but I get "2" "2"

**Screenshots**
![image](https://github.com/SHWotever/SimHub/assets/23377650/772519c5-50d0-4770-a7d3-d54c5eed137e)
![image](https://github.com/SHWotever/SimHub/assets/23377650/79566f86-157f-4f33-bf55-9593cee2cb87)
![image](https://github.com/SHWotever/SimHub/assets/23377650/fc1c3e8a-10b9-452f-b88e-052b9410dc80)
![image](https://github.com/SHWotever/SimHub/assets/23377650/05c16165-5308-46d0-9b93-cfec1c3e97e8)

**Log files**
attached
[SimHub.txt](https://github.com/user-attachments/files/15884931/SimHub.txt)

**Additional context**
Note1 - in the preview during edit - the the expected result is correct for each element.
Note2 - the issue happens only if the main code of the bindings is absolutely same. If i put for example some comment in the code one of the text bindings there is no problem. 
Note3 - The real use case (when i noticed the problem) was in my dashboard I have some sector related text fields and I wanted same code on all the sectors and just in the runonce section put variable for which sector that element is.

**Comment by SHWotever** [comment]
Hi ! Thanks for the report indeed the run once section was not taking into account into the caching strategy making it see as the same in both cases, I've fixed it for the next version.

Nicolas

**Comment by georgi-iovchev** [comment]
Thank you very much for the fast response :)
