### ISSUE TITLE
Overlays and ShakeIt motors stop working after retrying practice session in F1 24

### ISSUE THREAD

**Issue by humbhye** [SHWotever/SimHub#1633]
**Describe the bug**
I enter a practice session in F1 24 and the overlays and HF8 haptic pad all work fine. If I select the option to "Retry Practice Session" from the menu, after approximately 30 seconds the overlay will freeze and the ShakeIt Motors will also stop working.

**Simhub version**
9.3.6

**Third party plugins**
Had RacerRay, Gary Swallow and F1 TV plugins installed. Tested this with all of them disabled, and used a Simhub overlay, and the same issue still happens.

**To Reproduce**
1. Enter the F1 24 game.
2. Start a practice session in any Career mode
3. Pause the game and select "Retry Practice Session". Drive around for ~30 seconds.

I run Fanalab alongside Simhub. I've set up port forwarding to Fanalab to a separate port (20888). The wheel and pedals do not disconnect and continue working normally.

I have also tested this in F1 23, F1 2021 and F1 2020 and none of those games exhibit this behaviour, only F1 24. In all the previous games, overlays and the ShakeIt Motors continue to function normally. Any help appreciated.

_Edit: after further testing, I found that the precise moment that the overlays freeze and the ShakeIt Motors stop working is when I cross the start/finish line._

![Screenshot 2024-06-23 001907](https://github.com/SHWotever/SimHub/assets/173576211/5a91b39d-4547-4fa9-9260-41245c8ead13)
![Screenshot 2024-06-23 001952](https://github.com/SHWotever/SimHub/assets/173576211/79d2312a-61c8-443a-8410-969efca9817b)

[SimHub.txt](https://github.com/user-attachments/files/15939628/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! Thanks for the log apparently F1 sends some bad data about the track position (kind of infinite instead of a 0-1 ) which makes Simhub fight to get it back to the 0-1 range, I've fixed it for the next version.
Nicolas

**Comment by humbhye** [comment]
Hi, thanks for the response and the fix! This issue was driving a bit nuts :)
