### ISSUE TITLE
iRacing - Overlays only visible when in the car

### ISSUE THREAD

**Issue by martinlanza** [SHWotever/SimHub#1635]
The overlays status shows "Overlays are currently hidden and waiting for a game connection to be shown" when iRacing is running but I'm out of the car.
The problem with this is during a team event the other team drivers (watching) can't have the leaderboard visible.

There is a game connection - I can see the game properties

Simhub version = 9.3.6

**To Reproduce**
Create a layout, add the SimHub leaderboard
It's not visible when iRacing is running but driver is out of the car

**Expected behavior**
Be able to have overlays visible:
- When out of the car - leader board
- When in the pits - leaderboard + tyre hud
- When driving - leaderboard + relative + dash

**Screenshots**

![image](https://github.com/SHWotever/SimHub/assets/34517295/e2bfce11-4d13-4a22-8f0d-747f2895822a)

**Comment by SHWotever** [comment]
Hi this  is indeed intentional, for a long time it was the opposite and lot of people complained from it. The automatic show/hide takes into consideration when you are in car.

**Comment by martinlanza** [comment]
> If you toggle "Forced visible" the overlay will be always visible. Then it's up to the dash overlay to hide itself when not in the car.

That makes ALL the overlays visible - not the desired outcome

**Comment by SHWotever** [comment]
Hum, there have been some overlays "hiding" themselves (with a transparent content) internally with some ad-hoc conditions, But the whole layout was always either shown or hidden

I've added an option to show them earlier if wanted : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/4a51a171-5b82-4bba-959b-690a466b8f94)

Overall that's the only difference I see compared to what was possible in the past.

**Comment by martinlanza** [comment]
This show/hide ALL approach completely overrides the dashboard screen settings making them pointless and creating confusion as to how to use dashboards/overlays/layouts

![image](https://github.com/SHWotever/SimHub/assets/34517295/cd9f0048-960b-4ffb-8fb4-90b1de3d8d3e)

**Comment by SHWotever** [comment]
The options you are showing are for screen auto switching inside a dashboard.

Overall there are two steps, 

- Does the layout is "active" and "tries" to show the  content 
  That's what the options of the layout does

- What is show by a specific overlay :  
  Inside an overlay itself you can switch the screens automatically with those options, If in a specific case you just want it to be "blank" (visually it will be the same as "hidden") you can just set an empty screen.
