### ISSUE TITLE
[Feature request] Import / Export Car Settings "Per car overrides"

### ISSUE THREAD

**Issue by fixfactory** [SHWotever/SimHub#1636]
The problem is that, in iRacing, it's necessary to define Per car overrides for each car to get the proper shift point rpm. Because the iRacing SDK does not provide accurate shift points; the data provided in the raw values is quite off compared to the behavior of the in-game steering wheel (sometime off by 1000 rpm!)

And because this is an elaborate task to figure out the correct rpm values for each gear for each car, it would be nice if we could export our values to a json file and share it with the community so they can simply import the settings.

Potential solution: Two simple Import / Export buttons (next to "Forget all cars" button) that would read / write a json file with all the per car overrides settings.

I don't think there's currently a workaround.

![2024-06-24 15_07_14-Window](https://github.com/SHWotever/SimHub/assets/5952846/2da54994-357e-474d-b055-458629c1062d)

**Comment by SHWotever** [comment]
Hi you can get all the files at once by copying the files from C:\Program Files (x86)\SimHub\PluginsData\{gamename}\Cars (ie C:\Program Files (x86)\SimHub\PluginsData\AssettoCorsaCompetizione\Cars) to make it easy to merge etc ...there is one file per car.

Nicolas
