### ISSUE TITLE
Dashboard/Arduino Reset Mid-Race (Old Issue back)

### ISSUE THREAD

**Issue by RetroCoffin** [SHWotever/SimHub#1638]
BUG: 
Mid-Race while car is running, my DDU, tablets and gear indicator reset (it cycles thru the start cycle), occasionally, it only resets the tablets and gear indicator, not the DDU. Additionally, sometimes there is a noticeable delay between the downshifts/upshifts and DDU/Gear Indicator reflecting the change. Telemetry data also not accurate, delta behaves erratically. 

**Simhub version**
9.3.8 verified

**Third party plugins**
Only plug in running is DNR LEDs and whatever is required for Lovely Dashboard.

**Expected behavior**
Dashboard not to reset / lag mid race. 
**Screenshots**
N/A

**Log files** ((File size too large too attach))
https://mega.nz/file/EKtmSbjQ#UGYkQ4cnUyjHGNE4297g6BT-IVfWeuFa5bAy0E0iLvc
https://mega.nz/file/dHNVzKKC#aXOEvDNqLVJnTMEJvfEfRpnlnE6wHY61LNMkIT9lnHA
https://mega.nz/file/4bESDIJT#qsBe2elIAICT53qIgjX7XAsTB9Iti7CL4U5HAppt4ms

**Additional context**
The bug is most noticeable on the 2 laps prior to last lap. This is a previous issue that you kindly addressed earlier this year. Seems it's back.

**Comment by SHWotever** [comment]
Hi ! 

I checked the replay and "the telemetry holes" (let's call it like this) are higher than the tolerance I've set,

Can you check that all your other iracing based software around are up to date ? Apparently the "telemetry holes issue" got worse (very worse) a few days ago and  was triggered by 1simracing stuffs which was breaking sync and making other software read prematurely "non ready" data : https://forums.iracing.com/discussion/63518/iracing-telemetry-is-bugged/p2 .  The iracing staff had also found a reason why this had existed in the past in a more moderate range, but it's still not addressed yet as I see the iracing change log.

After this event, I've raised from 2 to 4 the number of packets allowed to be corrupted but it's only a basic workaround, I can't reconstruct missing data. 

Indeed in your replay I could catch wider events which will lead to a disconnect,  disconnects seen from Simhub will close the lap and indeed record wrong data. I will raise a little more the tolerance, but it's only adding "hangs" in telemetry, still less harmful than a full "disconnect" I agree. 

Can you check all software around if you have some ?

**Comment by RetroCoffin** [comment]
Will do, I currently run Racelabs, Crew Chief and Trading Paints in the
background along with Simhub.

Figured it was an iRacing issue and not much you can do, but thank you for
looking on a Sunday! I'll get back to you after I check for updates.
