### ISSUE TITLE
Saving stuff wont work

### ISSUE THREAD

**Issue by Hattrick25** [SHWotever/SimHub#1642]
**Describe the bug**
When i add a vocore screen to the device section. And when i close simhub and open it the next day. The added vorcore screen is gone...
Same for added profiles (lights, dashboard, arduino's), when i add them and close simhub, there gone when i start simhub again.

Also if i delete a profile, the next time i open simhub its back and the other profile that i made, is gone...

**Simhub version**
9.3.9

**Third party plugins**
Not sure if this can be the fault of 3th party plugins?

**To Reproduce**
1. Go to 'Devices'

2. Click on Add new device

3. Scroll down to 'Vocrore screen'
![image](https://github.com/SHWotever/SimHub/assets/174744478/bbc85d30-0c48-4e49-9ab1-b85716058412)

4. click on "ok"

5. i rename the vocore screen to "wheel dash"
![image](https://github.com/SHWotever/SimHub/assets/174744478/a7cdc08c-4b6e-42ce-939e-86a92f736323)

6. So now i close Simhub.

7. i reopen Simhub
 
8.  And the new device is gone
![image](https://github.com/SHWotever/SimHub/assets/174744478/83991c72-8bd8-44d6-9c49-544b5d07e37c)

**Expected behavior**
I was hoping it would keep my changes after i close simhub.

**Screenshots**
See above

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
don't hesistate to contact me trough email: jonasgilis@hotmail.com

**Comment by SHWotever** [comment]
Hi ! Could you join the log files so I can take a look ?

Log files
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
