### ISSUE TITLE
[Feature request] New version Arduino Uno's compatibility (R4)

### ISSUE THREAD

**Issue by drvr3** [SHWotever/SimHub#1644]
It would be appreciated if compatibility with the new Arduino Uno R4 could be added.
These models are becoming a standard. They have the advantage of including a 0-5V DAC to control a motor.
Thank you for the interest you will show in this request.

**Comment by SHWotever** [comment]
Hi !

I don't plan to support those chips since they are completely different from the old generations and since simhub embeds lot of old boards and lot of the manufacturer libraires have never been updated for those new generations MCU.
