### ISSUE TITLE
Support for ProSimu PRS series 

### ISSUE THREAD

**Issue by pdq-v** [SHWotever/SimHub#1645]
I have used Sim Tools and Sim Racing Studio for full motion support.   I am currently a Sim Hub user because I have a GSI Max 32 wheel which includes a screen.  I understand you are working on releasing full motion support for Sim Hub which would allow me to no longer have to run either SRS or Sim Tools for full motion support.   Both SRS and Sim Tools offer a plugin for my Prosimu rig.   When will you be able to offer a plugin to support my rig?   I will purchase a license as soon as it is available and if you need a beta tester, count me in!

Here's my full rig configuration: 
Prosimu T1000 5M SV motion rig, Valve Index VR Rig, GSI GXL Pro Alpha Wheel, GSI GT-MAX32 Wheel, Simucube 2 Pro Direct Drive Wheel Base, Heusinkveld Sim Pedals, Heusinkveld Sim Handbrake, Heusinkveld Sequential Shifter, Sparco EVO Bucket XL, Butt Kicker Game2 Kit, Corsair Vengeance i7300 Gaming PC Model# CS-9050039-NA (i7 12700K, RTX 3090Ti, 2TB, 64DB DDR5), X 3 - 39” DecoGear Curved Ultrawide Gaming Monitors (2560x1440, 1ms MPRT, 165 Hz, 16:9, HDR400, 4000:1 × 1), LG 27” LG 27GQ50F-B Full HD (1920 x 1080) Ultragear Gaming Monitor with 165Hz, Next Level Racing Quad Monitor stand, Next Level Racing keyboard/mouse stand, Rockville ONE-BAR All in One SoundBar, Corsair Headset

**Comment by SHWotever** [comment]
Hi ! 

I've been in contact with them to get informations about their new "PRS" series, which I did not get yet. The older SCN5/6 actuators will be supported soon, I'm adding the last touch to this.

If somehow you have the simtools interface plugin under hand of the PRS series I would be interrested to get the dll to see it working, I could not find any clear informations about it on the prosimu website (this is under a "customer login" wall).

**Comment by pdq-v** [comment]
I finally connected with Prosimu support and was able to obtain their version of Sim Tools which includes full support for Version  3.   Prosimu provided a direct download link from their website but I first had to provide them my original order#, Prosimu model and the serial numbers of my actuators including whether or not I had traction loss actuator dyadic scn6 (which I do have).  Currently everything is working except for scn6 traction loss so I need to continue troubleshooting that issue.  Attached is a pdf copy of the manual for your reference.   Here's a link to the Prosimu download page where you must first register and create an account if you do not already have a Prosimu account.  https://prosimu.fr/download/?lang=en
[Prosimu SIMTOOLS V3 Manual.pdf](https://github.com/user-attachments/files/16282623/Prosimu.SIMTOOLS.V3.Manual.pdf)

![Prosimu-SimToolsV3-Info](https://github.com/user-attachments/assets/d38d3755-3d98-4e77-a9d8-a4d4294a7781)

**Comment by SHWotever** [comment]
Hi ! Thanks for the informations. The manual unfortunately does not give any technical details about the communication or the hardware being used. 

I will contact them again to see if they agree so send those informations, better do this the clean way.

**Comment by SHWotever** [comment]
Hi ! After a couple of exchanges with prosimu, for their own reasons that I will respect, they prefer not to give me access to any details (docs etc...) allowing to make it happen. This unfortunately closes definitely the prosimu compatibility quest.

**Comment by pdq-v** [comment]
That is very unfortunate news.  Simhub is a great product and full motion capability for the Prosimu sim would have been well received by the community of Simhub users who own a Prosimu full motion sim.
