### ISSUE TITLE
[Feature request]Getting steering angle information

### ISSUE THREAD

**Issue by CNhjx** [SHWotever/SimHub#1649]
Hello Nicolas
I want to display steering angle information on the dashboard, but I can't find the corresponding available properties in GameData.
I think it might be these two (DataCorePlugin.GameData.SpotterCarLeftAngle, DataCorePlugin.GameData.SpotterCarRightAngle) ? But the data doesn't change when I turn the wheel. 
There are a few games like AC and F1 24 that I can use GameRawData, But then programming gets complicated.
![image](https://github.com/user-attachments/assets/d4e1ebe5-f082-40c8-8b49-34f3c60bf356)

**Comment by SHWotever** [comment]
Hi ! Indeed it's a data not available as a standard as it rarely available, and when available it's not always expressed the same (sometimes percent, sometimes angle) and it's not really possible to provide a consistent (unit consistent) data about it unfortunately.

**Comment by CNhjx** [comment]
I got it, thanks a lot for the answer.
