### ISSUE TITLE
arduino nano firmware error

### ISSUE THREAD

**Issue by kraa965** [SHWotever/SimHub#1652]
**Describe the bug**
When I try to flash the arduino nano, I get an error

**Simhub version**
The version is installed: 8.1.1 I tried it on version 9.3.9

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**
1. Go to Arduino 
2. Click My Hardware
3. Click Open Arduino Setup Tools
3. Set up the scheme as shown in the screenshot
5. I get an error when flashing

**Expected behavior**
I expected the arduino to be stitched

**Screenshots**
![image](https://github.com/user-attachments/assets/9a9f2161-4e72-4d94-8a07-f9123ba6b726)
![image](https://github.com/user-attachments/assets/4fdde7ef-4ea3-4943-8dd2-f47264c20943)
![image](https://github.com/user-attachments/assets/8189a633-6b1b-4a6d-a11c-0efd30604285)

**Log files**
[SimHub.log](https://github.com/user-attachments/files/16325842/SimHub.log)

**Additional context**
Tell me how to fix this error

**Comment by kraa965** [comment]
I figured it out more or less, took the source code from the folder, removed unnecessary codes, was able to upload a sketch to Arduino, but simhub cannot connect to Arduino, tell me how to solve this problem?

**Comment by kraa965** [comment]
and tell me, if I change the sources with my own hands, what do I need to do so that simhub defines my arduino?

**Comment by SHWotever** [comment]
Hi ! About the error I see that your installation is inside a OneDrive folder, one drive (and any synchronization tools) are known to create issues with many software (as they might lock files, makes them disappear etc ..). Please make sure to install simhub in a normal folder (program files etc...)

About sketch modifications they must be made strictly inside the dedicated file as shown here : https://github.com/zegreatclan/SimHub/wiki/Custom-Arduino-hardware-support

**Comment by kraa965** [comment]
> Hi ! About the error I see that your installation is inside a OneDrive folder, one drive (and any synchronization tools) are known to create issues with many software (as they might lock files, makes them disappear etc ..). Please make sure to install simhub in a normal folder (program files etc...)
> 
> About sketch modifications they must be made strictly inside the dedicated file as shown here : https://github.com/zegreatclan/SimHub/wiki/Custom-Arduino-hardware-support

there must be some kind of error with OneDrive, because all the files I have are lying locally, as the installer installs
Regarding the code, I want to use your code, just optimize it, I want to make oled work simultaneously, 20 buttons in the form of a matrix and 3 encoders, hence the question arose, maybe you have some kind of main function that connects to simhub, because as soon as they start optimizing the code, simhub stops seeing arduino

and maybe in the future, do the following if the user selects specific parameters, such as the screen, buttons and encoders, so that what is not selected does not even get into the sketch?

**Comment by SHWotever** [comment]
Onedrive keep in sync files meaning reading them when they appear or when they are modified  (and locking them when being read), You will have various issues soon or later. I can only encurage you to install it in a normal place.

About the oled it's indeed a limitation, it consumes a lot of ram as indicated here, you can't make it run along any other features : 
https://github.com/SHWotever/SimHub/wiki/Arduino-SSD1306-0.96''-Oled-I2C#restrictions

The sketch is already being made minimalist with lot of conditionnal compilation to remove most if not all of not activated functions. The issue in a "connected" mode, is that it has to hold the strings, commands, fonts ... which needs some additinnal memory. Currently this makes it just right at the limit on a 328p when being alone.
