### ISSUE TITLE
[Feature request] Support for Govee H61D3

### ISSUE THREAD

**Issue by SergeS2K** [SHWotever/SimHub#1654]
**Is your feature request related to a problem? Please describe.**
SimHub does not have H61D3 Govee Lights shown as compatible. I believe these are a newer model, but support both the Govee Home Desktop App and LAN control. However Simhub does not locate them

**Describe the solution you'd like**
For H61D3 Govee Lights to be supported with Ambient Lighting

**Describe alternatives you've considered**
None

**Additional context**
I have installed Govee Desktop to confirm the lights show up in there and confirm LAN control is enabled. I have restarted my PC, rebooted the router, and made sure Govee Desktop App was closed before opening SimHub.  

I'm not sure if this helps, but I can also confirm these lights work with this other script this guy made here > https://gitlab.com/arsenic645/govee-simracing-lights-sync , while it doesn't involve SimHub, at least I can confirm these lights interface successfully with Assetto & Dirt Rally for RPM syncing.

**Comment by SHWotever** [comment]
Hi ! The api looks really similar the the one I use, except govee ip is hard coded, while I use the govee discovery procesdure to find devices over lan. Are you sure your firewall allows data to enter ? That's the prerequisite to allow discovery

**Comment by SergeS2K** [comment]
Hey! Yes the Firewall permissions are set to allow. The Govee Home Desktop application can locate the Govee Lights without any problems. Is there another Firewall rule I may not be aware of that I'm missing? There was a few video tutorials around on the Govee Ambient lighting with Simhub and I looked through several of them and didn't see any specific firewall rules beside the default that pops up when turning this on in SimHub

**Comment by SergeS2K** [comment]
I did double check and confirm firewall permissions was set correctly as well for SimHub. No luck still.

**Comment by SergeS2K** [comment]
Adding onto this once more. I bought the Govee Light Bars and those were found instantly with no problem, it just seems to be this H61D3 model that isn't detected. Not sure if that's something that can be updated or changed?

**Comment by SHWotever** [comment]
Hi !
I took a look at the Govee API
I'm using the govee API to get compliant SKUs, but unfortunately this H61D3 is not listed yet which explains why simhub won't take it : 
https://app2.govee.com/bff-app/pc/v1/support-skus

I need to find a way to add some not officially listed SKUs without entering in a gamble game (as lan control compliant SKUs are not widely spread). That's why referring to this official list coming from Govee is safer.

**Comment by SergeS2K** [comment]
Ah. Thanks that update and fully understand. I suppose I may purchase one of the older model rope lights for now and will keep this one on hand for a future enhancement. Much appreciated!
