### ISSUE TITLE
LMU - type de pneus

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1659]
Sur LMU, il y a une incohérence sur les types de pneus entre 
DataCorePlugin.GameRawData.CurrentPlayerTelemetry.mFrontTireCompoundIndex
et
driverfronttyrecompound

Peut-etre que ce sont les données fournies par le jeu qui sont incorrectes ?

![1](https://github.com/user-attachments/assets/6bdf5fde-48eb-438e-bd10-198bf0c32956)

**Comment by SHWotever** [comment]
Hello ! J'ai vérifié les codes et les.noms viennent effectivement directement du jeu, je n'ai pas de tables de traduction ou autre. Les 5 données que tu pointes viennent directement de la telemetrie, sans plus de traitements

**Comment by herve4545** [comment]
Hello
oui, je m'en doutais un peu
