### ISSUE TITLE
[Feature request] Please update the feature to add and configure Simagic Haptic motor controllers

### ISSUE THREAD

**Issue by guruguru83** [SHWotever/SimHub#1662]
We suggest that you configure both Simmagic haptic motor controllers.
The reason is because I want to use it in 4 channels.
It is now available for up to 3 channels. Please allow me to configure 6 channels with 2 controllers.
![스크린샷 2024-08-09 232319](https://github.com/user-attachments/assets/1bf82fb2-61a8-4ddb-9c7c-d7120505f781)
![스크린샷 2024-08-09 232535](https://github.com/user-attachments/assets/4fda2960-bd4f-496f-ba52-f595f744d223)
![스크린샷 2024-08-09 232559](https://github.com/user-attachments/assets/1d78a840-09f6-4614-bfe6-906b8fea223a)

**Comment by SHWotever** [comment]
Hi ! Currently the shake it engine is limited to one device per kind. 

I need to check if hardware wise there is a truly unique id which would allow to identify reliability and attach to more than one

**Comment by guruguru83** [comment]
> Hi ! Currently the shake it engine is limited to one device per kind.
> 
> I need to check if hardware wise there is a truly unique id which would allow to identify reliability and attach to more than one

![Screenshot_20240810_084355_KakaoTalk](https://github.com/user-attachments/assets/7461a57f-ace3-4b99-9815-cca5e6766f5f)

On SimHub, it is normally recognized as two devices.

**Comment by guruguru83** [comment]
> Hi ! Currently the shake it engine is limited to one device per kind.
> 
> I need to check if hardware wise there is a truly unique id which would allow to identify reliability and attach to more than one

On SimHub, it is recognized as two devices.
![Screenshot_20240810_084355_KakaoTalk](https://github.com/user-attachments/assets/e58a4f24-0da7-4e9a-9be1-4f69385d0901)

**Comment by SHWotever** [comment]
Hi This was added to [9.6.4](https://github.com/SHWotever/SimHub/releases/tag/9.6.4)
