### ISSUE TITLE
[Feature request] Add new NCalc / JS functions for estimated deltas & estimated laps.

### ISSUE THREAD

**Issue by derrickmoeller** [SHWotever/SimHub#1663]
**Is your feature request related to a problem? Please describe.**
The estimated lap time and estimated delta are only available via $prop, and as such cannot be overridden by a plug-in. Creating JS functions would allow plug-in developers to create solutions that can be used by dash / overlay developers without creating unwanted dependencies.

**Describe the solution you'd like**

I would like to see two new functions created.
- `getplayerestimateddelta`
- `getplayerestimatedlaptime`

**Comment by SHWotever** [comment]
Hi !

The purpose of functions is not to be be overriden. In term of support this would make literrally impossible for me to determine if a function result is wrong where the data is coming from just by looking at the logs or getting a simple replay 

Those data already exists as properties. I under
