### ISSUE TITLE
[Feature request]Toggle switch hold timeout

### ISSUE THREAD

**Issue by Vlad-Zmtr** [SHWotever/SimHub#1670]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but it's feature which would let to use toggle switches in racing games whet setting up matrix buttons for Arduino. 
**Describe the solution you'd like**
Toggle switches are often used in racing button boxes. In current Skecth setup version toggle switches used in Button matrix after switching them stays in ON or OFF position. In racing games like ACC it's not working, ACC accepts only button press. 
It would be good to have option to set timer for toggle switches, so that it behave like button press. 
I think adding timeout option for each row and column where 0 is no timer (current setup) and anything >0ms will set switch to OFF after X ms. 
 

**Describe alternatives you've considered**
Now I just switching toggle switch ON-OFF each time I need to use it. Another alternative is to use switches, that aren't stay in ON position and automatically switches to OFF

 
It could be like this -![simHub-toggle-example](https://github.com/user-attachments/assets/d50bef88-1446-43b3-89b3-390609ea6df3)

**Comment by SHWotever** [comment]
Hi ! As indicated in the wiki this easy matrix wiring does not support latching switches (the whole row or column is getting locked) . For matrix you must use momentary buttons : https://github.com/SHWotever/SimHub/wiki/Arduino---Button-matrix#read-before
