### ISSUE TITLE
Simhub- Two Ardiuno and 8 shake motor control?

### ISSUE THREAD

**Issue by fuadoner** [SHWotever/SimHub#1674]
Now I have a 4-vote motor system in my pedals with an Arduino and motor driver. (channel1, channel2, channel3, channel4)

As a new project, I want to make a seat pad with 4 voting motors. For example, for the road texture (channel5, channel6, channel7, channel8) I will come with a new Arduino and motor driver for this.

Before purchasing, I want to ask;

In addition to the existing selection motors in the pedals, can I control 4 more selection motors separately?

Is this possible since there will be two separate Arduinos?

**Comment by SHWotever** [comment]
I currently you can control up to 12 channels :  each Arduino will get their channels assigned in order : https://github.com/SHWotever/SimHub/wiki/Arduino-Multiple-devices-support
