### ISSUE TITLE
DataCorePlugin.GameData.EngineIgnitionOn does not become true for BeamNG

### ISSUE THREAD

**Issue by blekenbleu** [SHWotever/SimHub#1676]
[SimHub.txt](https://github.com/user-attachments/files/16825383/SimHub.txt)
**Describe the bug**
When running a BeamNG replay with no plugins or addons,
DataCorePlugin.GameData.EngineIgnitionOn does not become true

**Simhub version**
9.4.4 and several earlier versions.

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**
1. disable all addons and plugins
2. load BeamNg
3. launch a replay
4. filter properties by ignit

**Expected behavior**
`GameData.EngineIgnitionOn                          1`

**Screenshots**
![ignition](https://github.com/user-attachments/assets/3410c3ed-470d-462a-afbe-bc9b9a4de998)
**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by dMASSIV** [comment]
I also can reproduce the same issue
