### ISSUE TITLE
TMP1638 leds tab does not allow to select the yellow (red+green) color

### ISSUE THREAD

**Issue by ruenes1** [SHWotever/SimHub#1677]
**Describe the bug**
TMP1638 leds tab does not allow to select 'yellow' color (that is, red+ green) for TMP1638 modules with dual color leds (green and red). Only black, green and red colors are available in the drop down selector.

When enabling the TMP1638 in the arduino editor, there seems to be code in the .ino file to handle the 'yellow' (green+red), which is not used.

`if (state == 'Y') {
      TM1638_screens[0]->Screen->setLED(TM1638_COLOR_RED + TM1638_COLOR_GREEN, i);`

**Simhub version**
9.4.4

**To Reproduce**
1. Go to the TMP1638 leds tab in the Arduino menu. 
2. Create a new effect (such as rpms)
3. Select the color associated to the effect

**Expected behavior**
The yellow color (red+green) should be selectable in the drop down menu and associated to the .ino code handling this color ('Y')

**Comment by SHWotever** [comment]
Hi indeed it was planned but at the time but all of the various modules I had in hands were not supporting it (despite some articles found on internet showing that some of them were capable of It) This made me exclude that possibility at the end (despite some remaining traces indeed in the sketch but which never worked on my hardware).

**Comment by ruenes1** [comment]
Hi. Thanks, I see. 

I built my own circuit around the TMP1638 chip, rather than using a prebuilt module and, indeed, it supports dual colored leds that can be lighted up at the same time to create the yellow color. But now I see supporting this case is quite niche.

Best
