### ISSUE TITLE
Beam/Lights

### ISSUE THREAD

**Issue by JannikWaschbar** [SHWotever/SimHub#1679]
I would like to add a "light" function on my dashboard to see if I have turned my lights on, but there is no property.

If you could add a property like: "no_beam", "low_beam", "high_beam" would be great!

I am not sure if "beam" or "lights" would be better. I am from Germany, so I dont know what would be more easy for the other people.

/

**Comment by SHWotever** [comment]
Hi ! Which game is it ? Overall the "beam" data is something extremely rare.
