### ISSUE TITLE
Simhub won't start if LeoXZ XGT Ultimate is connected to Simagic Alpha Mini on Windows 11 boot

### ISSUE THREAD

**Issue by FractalFootwork** [SHWotever/SimHub#1681]
**Describe the bug**
Simhub won't start automatically or manually after Windows 11 boot/startup if LeoXZ XGT Ultimate steering wheel is connected to hub (Simagic Alpha Mini). If LeoXZ XGT Ultimate steering wheel is not connected during Windows 11 boot/startup, then Simhub will start normally and then I can connect the steering wheel after which everything works correct with Simhub and the steering wheel.

**Simhub version**
9.4.4

**Third party plugins**
Leoxz SimgBridge

**To Reproduce**
1. Leave LeoXZ XGT Ultimate steering wheel connected to Simagic Alpha Mini hub with computer off
2. Turn on PC
3. Simhub won't have started
4. Simhub won't start when manually clicking on the icon

**Expected behavior**
Simhub starting after Windows 11 startup/boot, and Simhub starting when manually clicking on the Simhub icon

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
LeoXZ XGT Ultimate is using the wireless communication
[SimHub.2.txt](https://github.com/user-attachments/files/16902459/SimHub.2.txt)
[SimHub.4.txt](https://github.com/user-attachments/files/16902460/SimHub.4.txt)
[SimHub.5.txt](https://github.com/user-attachments/files/16902461/SimHub.5.txt)
[SimHub.6.txt](https://github.com/user-attachments/files/16902462/SimHub.6.txt)
[SimHub.7.txt](https://github.com/user-attachments/files/16902463/SimHub.7.txt)
[SimHub.8.txt](https://github.com/user-attachments/files/16902464/SimHub.8.txt)
[SimHub.9.txt](https://github.com/user-attachments/files/16902466/SimHub.9.txt)
[SimHub.10.txt](https://github.com/user-attachments/files/16902468/SimHub.10.txt)
[SimHub.11.txt](https://github.com/user-attachments/files/16902469/SimHub.11.txt)
[SimHub.12.txt](https://github.com/user-attachments/files/16902470/SimHub.12.txt)

**Comment by SHWotever** [comment]
Hi thanks for the log, I see that it is freezing inside the leozx plugin  initialization. Can you disable it first and try again (go in left menu, add/remove features, and uncheck leozx plugin)
If it solves it do not hesitate to contact them so they can help you troubleshoot their plugin: support@leoxz.com
