### ISSUE TITLE
Grey Screen on VCORE Dash. Only occurs on 30,20fps when trying to display webpage based Dash Studio Creation. Older Simhub versions work.

### ISSUE THREAD

**Issue by SammyHendrix** [SHWotever/SimHub#1682]
**Describe the bug**
Grey Screen on Delta Sim Tech DU5 when trying to view WebPage Dash. Only occurs when FPS is set to 30 or 20. FPS at 1, 5, 10 works. 

**Simhub version**
4.1.1

**Third party plugins**
None

**To Reproduce**
Enable DU5 Dash and set dash to any webpage produced image from Simhub Dash Studio.

**Expected behavior**
Working as expected in version 9.3.6. 

**Screenshots**
None

**Log files**
None

**Additional context**
Worked with Chris (creator of Delta Sim Tech DU5 Dash) to eliminate any hardware issues.  After bypassing an interface PCB and connecting directly to the VCORE screen the issue was reproducible with the original symptoms.

**Comment by SHWotever** [comment]
Hi !

Could you join the sim log files when this occurs so I can check which model exactly is running and if there are some other insights ?

![image](https://github.com/user-attachments/assets/9ba9c1c4-e275-4be2-9f1b-7ac3cf67daf8)
