### ISSUE TITLE
Not wanting to launch

### ISSUE THREAD

**Issue by MrHuman21** [SHWotever/SimHub#1683]
I try to boot up the program like normal, but when I click on it and see that it loads, it loads for about 5 seconds then nothing, do it again, nothing. I tried just manually starting it through the file explorer to nothing again. I did the C++ repairs and that didn't change anything. I completely deleted SimHub and redownloaded it, but nothing. I restarted the PC about a million times during that process, but didn't help a thing. Do you have any idea what the problem is?

**Log files**

[SimHub.PackageManager.Standalone.2.log](https://github.com/user-attachments/files/16913979/SimHub.PackageManager.Standalone.2.log)
[SimHub.PackageManager.Standalone.3.log](https://github.com/user-attachments/files/16913980/SimHub.PackageManager.Standalone.3.log)
[SimHub.PackageManager.Standalone.log](https://github.com/user-attachments/files/16913981/SimHub.PackageManager.Standalone.log)

**Comment by SHWotever** [comment]
Hi ! could you join the simhub log files ? 
![image](https://github.com/user-attachments/assets/ada9a926-4246-4707-9310-3f6936b68aac)

If somehow they don't get created could you check in windows event viewer, windows events/applications that any error is shown here ? they often comes as pairs, I would need both of them, 
![image](https://github.com/user-attachments/assets/a9a21f83-93a2-4016-8eec-f2ad573a36b7)

**Comment by RetiredHippie** [comment]
Any solutions yet? im having the same issues, along with the submenu (where you click when opening a dash after hitting 'Start'). Its so frustrating, Simhub has worked for me for as long as i can remember, and now this is happening. Ive updated it a few times, reinstalled all Visual and .net packages, full install, older versions, nothing changes.
 
[SimHub.15.txt](https://github.com/user-attachments/files/16948096/SimHub.15.txt)
[SimHub.16.txt](https://github.com/user-attachments/files/16948097/SimHub.16.txt)
[SimHub.17.txt](https://github.com/user-attachments/files/16948098/SimHub.17.txt)
[SimHub.18.txt](https://github.com/user-attachments/files/16948099/SimHub.18.txt)
[SimHub.19.txt](https://github.com/user-attachments/files/16948100/SimHub.19.txt)
[SimHub.20.txt](https://github.com/user-attachments/files/16948101/SimHub.20.txt)
[SimHub.txt](https://github.com/user-attachments/files/16948102/SimHub.txt)
[SimHub.1.txt](https://github.com/user-attachments/files/16948103/SimHub.1.txt)
[SimHub.2.txt](https://github.com/user-attachments/files/16948104/SimHub.2.txt)
[SimHub.3.txt](https://github.com/user-attachments/files/16948105/SimHub.3.txt)
[SimHub.4.txt](https://github.com/user-attachments/files/16948106/SimHub.4.txt)
[SimHub.5.txt](https://github.com/user-attachments/files/16948107/SimHub.5.txt)
[SimHub.6.txt](https://github.com/user-attachments/files/16948108/SimHub.6.txt)
[SimHub.7.txt](https://github.com/user-attachments/files/16948109/SimHub.7.txt)
[SimHub.8.txt](https://github.com/user-attachments/files/16948110/SimHub.8.txt)
[SimHub.9.txt](https://github.com/user-attachments/files/16948111/SimHub.9.txt)
[SimHub.10.txt](https://github.com/user-attachments/files/16948112/SimHub.10.txt)
[PropertyServer.log](https://github.com/user-attachments/files/16948113/PropertyServer.log)
[SimHub.11.txt](https://github.com/user-attachments/files/16948114/SimHub.11.txt)
[SimHub.12.txt](https://github.com/user-attachments/files/16948115/SimHub.12.txt)
[SimHub.13.txt](https://github.com/user-attachments/files/16948116/SimHub.13.txt)
[SimHub.14.txt](https://github.com/user-attachments/files/16948117/SimHub.14.txt)

**Comment by MrHuman21** [comment]
Sorry, I was super busy. Here are pics from the event viewer.
![image](https://github.com/user-attachments/assets/2a7385e9-b54a-4052-9d8c-94a221a30c96)
![image](https://github.com/user-attachments/assets/ab7942ab-71fe-4672-a911-a14bb4edf4c1)

**Comment by SHWotever** [comment]
Hi ! Do you have the .net 9 preview 7 installed ? Separately or through visual studio preview ? Apparently this error is coming from an issue with it, the bug fix is being in progress at Microsoft: https://github.com/dotnet/wpf/pull/9584 . That would explain this "sudden" issue with no visible changes being made on the simhub install.

**Comment by MrHuman21** [comment]
Ok, so what should I do to get Simhub back up and running?

**Comment by MrHuman21** [comment]
And I’m not sure if I have the .net 9 preview 7 installed where can I check if I need to?

**Comment by MrHuman21** [comment]
Hey, is there a fix seeing how my simhub is still not booting?

**Comment by SHWotever** [comment]
Hi Could you chen in add remove programs that you don't have  something called ".net 9 preview" or similar installed ? It could have been bundled with another application for some reasons.
Microsoft also offers a .net repair tool , https://support.microsoft.com/fr-fr/topic/microsoft-net-framework-repair-tool-est-disponible-942a01e3-5b8b-7abb-c166-c34a2f4b612a but not sure it will remove that preview version.

**Comment by MrHuman21** [comment]
![image](https://github.com/user-attachments/assets/b896d981-cf0d-4f2e-947a-541c578eeb6e)
![image](https://github.com/user-attachments/assets/cb3804bf-6c3b-43da-86e0-6cfad3fe5b55)
![image](https://github.com/user-attachments/assets/974fd2d0-11a7-4a03-a3d4-0292582712e5)

I tried the .net repair tool and Simhub still doesn't boot. I took a screenshot of the .net similar installs and just want to check if this looks normal. I also took a screenshot of the most recent error in Event Viewer.

**Comment by MrHuman21** [comment]
I just did a fresh install on my PC and it seems like Simhub is running like normal. Though you didn't quite have the solution yet I just want you to thank you for your help.
