### ISSUE TITLE
Fresh install of 9.4.5 - Freezes after initial profile questions

### ISSUE THREAD

**Issue by GBabes28** [SHWotever/SimHub#1687]
I just installed Simhub for the first time and after answering the questions about units and games it immediately freezes. I have uninstalled and deleted all files and completed another install and it still doesn't work. Looks like there are a few errors in the log file. I have attached a couple of them.

Thanks,

Garrett
[SimHub.txt](https://github.com/user-attachments/files/16919837/SimHub.txt)
[SimHub.1.txt](https://github.com/user-attachments/files/16919838/SimHub.1.txt)

**Comment by SHWotever** [comment]
Hi ! Could you install the latest version ? [simhubdash.com/download-2](https://www.simhubdash.com/download-2/) 9.4.5 had an issue with fresh installations indeed.
