### ISSUE TITLE
Arduino problemas at 9.4.6

### ISSUE THREAD

**Issue by raemca** [SHWotever/SimHub#1688]
version 9.4.6 When you close simhub, the Arduinos remain in standby. All LED strips remain stopped with LEDs on. In addition, the executable remains running without finishing closing and does not allow simhub to be launched again without killing the zombie process.

**Comment by SHWotever** [comment]
Hi thanks for the report, could you join the log files after trying to exit ? 

```
**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
```

**Comment by raemca** [comment]
Sorry, there has been a very quick update from 9.4.5 to 9.4.6. I was on 9.4.4 and I thought I had updated to 9.4.6 but no, I was on 9.4.5. I have updated to 9.4.6 and it is now ok. thank you.El 8 sept 2024 7:21, Wotever ***@***.***> escribió:
Hi thanks for the report, could you join the log files after trying to exit ?
**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
