### ISSUE TITLE
Freeze on Start Up

### ISSUE THREAD

**Issue by ltwalt** [SHWotever/SimHub#1689]
**Describe the bug**
I start the program and after passing the units and games screen the entire program is locked up. I have tried to uninstall and reinstall and repair all of the Microsoft C++ files. Restarted my computer several times.

**Simhub version**
9.04.5

**Third party plugins**
None that I am aware of.

**Expected behavior**
Be able to interact with the program.

**Screenshots**
![2024-09-08_18-50-10](https://github.com/user-attachments/assets/b15ff230-7320-403c-8ecd-da42830e63f3)

**Log files**
[SimHub.1.txt](https://github.com/user-attachments/files/16923935/SimHub.1.txt)
[SimHub.2.txt](https://github.com/user-attachments/files/16923936/SimHub.2.txt)
[SimHub.txt](https://github.com/user-attachments/files/16923937/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! Could you install the latest version ? simhubdash.com/download-2 9.4.5 had an issue with fresh installations indeed.

Duplicate of #1687

**Comment by ltwalt** [comment]
That fixed it! Thanks!
