### ISSUE TITLE
[Feature request] Support for more than one 8x8 LED Matrix on arduino nano

### ISSUE THREAD

**Issue by soonic6** [SHWotever/SimHub#1690]
**Is your feature request related to a problem? Please describe.**
I just tried to add a second 8x8 LED Matrix to an arduino nano.
It just worked, if i choose on PIN6 8x8 LED Matrix and PIN7 a 64x LED stripe. But than, you can use the premade Flag and Spotter animations.
![image](https://github.com/user-attachments/assets/e556e75b-5cab-4dec-812a-3c5944c3992e)
but this is not i very nice workaround.

**Describe the solution you'd like**
Maybe possible adding a counter or an "add another led matrix" button?

**Additional context**
I just want to use two LED Panels for Flags and a seperated one for each side to spotting with the premade animations.

**Comment by SHWotever** [comment]
Hi !

Unfortunately sending around 120leds colors (64leds *2) would be too "jerky" that's why it's limited to one. This would also introduce heave power issues which is not welcome : https://github.com/SHWotever/SimHub/wiki/Arduino-RGB-Matrix#introduction
