### ISSUE TITLE
No way to save arduino sketch in configurator

### ISSUE THREAD

**Issue by VHF-ACADDICT** [SHWotever/SimHub#1691]
**Describe the bug**
save sketch button in configurator don’t work

**Simhub version**
latest version

**Third party plugins**
Not concerned

**To Reproduce**
:
1. Go to '.arduino configurator'
2. Click on 'save sketch in the main menu
3. Search for the file

**Expected behavior**
Finding the file to be able to modified it

**Comment by SHWotever** [comment]
Hi ! It will save the file, but not exporting it, you can edit it with the following button : 
![image](https://github.com/user-attachments/assets/90c6d6f8-b778-4726-b944-2a7c330d7e3e)

**Comment by VHF-ACADDICT** [comment]
Hi,
Thank you but this is only to open Arduino IDE with all the preconfigured sketches, not mine.

**Comment by SHWotever** [comment]
Hi ! If you want to copy it somewhere else after configuring you can copy this folder : C:\Program Files (x86)\SimHub\_Addons\Arduino\DisplayClientV2

Please not the simhub embedded ide is required to compile it, it contains all the required dependencies. Trying to compile it yourself with another version of the IDE won't work.

**Comment by VHF-ACADDICT** [comment]
Ok, thank you, actually i wanna add a servo output [like him](https://github.com/SHWotever/SimHub/issues/1619)
