### ISSUE TITLE
Control Mapper's output mapping "Keys" won't import from exported file

### ISSUE THREAD

**Issue by sjdawson** [SHWotever/SimHub#1694]
**Describe the bug**
After exporting an output mapping that contains keyboard functions, when importing that file, the keyboard mappings aren't restored. They are present in the exported output mapping file though.

**Simhub version**
9.4.6

**Third party plugins**
Gentleman Driver/Truck Simulator (my own plugins, happens with them disabled though)

**To Reproduce**
(Optionally restore all roles to default so there are some button assignments also to make this clearer what's happening)
1. In the output mapping section, assign a role in the keyboard tab
2. Export that output mapping to a file
3. Clear all assigned roles (or restore to default, so the keyboard mapping is cleared)
4. Attempt to import the file that you exported in step 2
5. Note that no keyboard keys have been reimported

**Expected behavior**
Keyboard keys should be being imported, just like buttons are.

**Comment by SHWotever** [comment]
Thanks for the peort it's fixed for the next version !
