### ISSUE TITLE
Bass shakers not working in Iracing and acc

### ISSUE THREAD

**Issue by Baldr68** [SHWotever/SimHub#1698]
**Describe the bug**
If iracing or Acc is  opened, the bass shakers does nnot work. Even the test buttons are not responding. As soon as i close iracing or Acc than the test buttons are working. Also the sound of my car engines are insanely low
**Simhub versio
 latest version

**To Reproduce**
1. Go to '...'simhub
2. Click on '....'iracing or acc
Bass shakers not workinh

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi thanks for the report, 

did you took a look at this ? https://github.com/SHWotever/SimHub/wiki/USB-Issues-Troubleshooting

When in game it could be also a power supply (IE nobsounds) weakness as all the effects are working together and stressing more the amplifier than a single punctual effect test.


If none of the above helped, could you join the requested logs ?

```
Log files
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : [docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)
```
