### ISSUE TITLE
.exe will not open

### ISSUE THREAD

**Issue by andybilly43** [SHWotever/SimHub#1699]
I am currently on version 9.3.1, I am trying to upgrade to 9.4.7 but when I try to open the new version nothing happens

**Comment by SHWotever** [comment]
Hi !

Is it the installer or the start of the application failing ?

Could you check that your antivirus or windows controlled folder access is not blocking it ? (How to disable windows controlled folder access) [geekflare.com/ways-to-enable-controlled-folder-access](https://geekflare.com/ways-to-enable-controlled-folder-access/) . The later is blocking any non microsoft validated apps for using folders like temporary folders needed for the installer to work.

If it's during simhub startup could you join the log files  ?


**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

**Comment by andybilly43** [comment]
It's the installer file (SimHubSetup_9.4.7) 
Windows Controlled Folder access was not turned on
I have deleted Norton and it still will not start

**Comment by SHWotever** [comment]
Thanks could you collect and send the setup log ?
- After starting the installer, go into `%localappdata%\temp`

![image](https://github.com/user-attachments/assets/f0f4b4ed-e91e-457d-9c96-e076fcddd9cb)

- Sort by modification date descending,
![image](https://github.com/user-attachments/assets/82c362f9-82eb-42b2-9459-906ef96528ae)

- You will find a log file at the following format Setup Log YEAR-MONTH-DAY #XXX.txt

![image](https://github.com/user-attachments/assets/91b83912-bc71-4a40-b51e-1ee706a71536)

Could you join me this file ?

**Comment by andybilly43** [comment]
There is no 'Setup Log' only what is in the snip
![Screenshot 2024-09-15 083623](https://github.com/user-attachments/assets/377f4016-c081-4848-9732-64cd9a1f9b52)

**Comment by andybilly43** [comment]
Do you have any suggestions yet?

**Comment by SHWotever** [comment]
Hi ! Unfortunately without logs that means it doesn't start at all, that would look like an antivirus hitting, but you said it was disabled/removed. Could you take a look into windows events viewer ? If there are any errors showing after launching the installer ? They will often show into the windows/application category 
Simply start the installer and check if no events are showing.

Also make sure you have not used any "compatibility" modes over the installer in file properties. They always do worse than better when it comes to "up to date" files.

![365374918-a9a21f83-93a2-4016-8eec-f2ad573a36b7](https://github.com/user-attachments/assets/6b7f45d2-c99a-4691-80bb-5634e339bd51)

**Comment by andybilly43** [comment]
It was the 'real time protection' that was stopping it, thank you for your help!
