### ISSUE TITLE
Fan whine at lower speeds using PWM 

### ISSUE THREAD

**Issue by SolarGITM** [SHWotever/SimHub#1700]
**Describe the bug**

I don't think this is a bug but just might be more then a question so hence putting it here.

I have setup a wind sim using Simhub (excellent) using the Cytron md10 board (as the motors are powerful server motors (3A each) and really needed the extra power of the Cytron to drive them both).

It generally works really well aside from a considerable whining noise from both of the fans at lower revs which disappears as the speed increases. 

I am using the Shakeit direct pwm (which I think is my only option for this hardware?) which unlike the adafruit does not allow the frequency to be adjusted (I don't know if that's the problem but was mentioned in another post) .

**Simhub version**
9.4.7

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**
Steps to reproduce the behaviour:
1. Loaded the sketch for the uno and shakeit direct pwm
3. Configured the shakeit motors speed option but have also tried the shakeit wind option (both work well but with the same sound)  
4. If I press the test button on the Cyton board (either on or in pulses to run the fans slower no whining sound at lower revs)
5. If I increase the value of the min pwm output value to a high setting (100) in sketch then with the fans going straight to higher revs it avoids the whining sound but obviously removes any low speed air effects for slower speeds.

**Expected behavior**
Ideally without the extra sound from the fans at low speed :)

**Screenshots**

**Log files**
[SimHub.txt](https://github.com/user-attachments/files/16996607/SimHub.txt)

**Additional context**
I fully realise this may just be a feature of driving these fans slowly in which case fine, I will turn the engine noise up :).

Many Thanks

**Comment by SHWotever** [comment]
Hi ! Whining noise is indeed a characteristic of lot of power control boards, pwm does use the native Arduino pwm, if the board have no smoothing of any kind it will translate the Arduino pwm frequency. Some of the supported boards allows to tune the frequency on the board (adafruit motor shield v2) or thanks to a very specific pinout it is possible to tune the Arduino frequency (Moto monster). For the generic PWM support it's not possible to get a so deep tuning. I never tested it but a little smoothing capacitor over the pwm pin should be able to "eat" the pulses to make them closer to an analog control (IE https://www.homemade-circuits.com/calculating-filter-capacitor-for/)

**Comment by SolarGITM** [comment]
That's great thanks very much
