### ISSUE TITLE
Update map American Truck Simulator!

### ISSUE THREAD

**Issue by Sergeyz370** [SHWotever/SimHub#1703]
**Describe the bug**
There is no state of Arkansas on the ATS map. Please update the map of America. Thank you."
**Simhub version**
Make sure to run the latest version
SimHub V9.4.7

**Comment by SHWotever** [comment]
Hi !

I've updated the map, 

To refresh the map simply click here and restart simhub : 
![image](https://github.com/user-attachments/assets/830df235-2380-47d2-a6b5-c4e819459912)

![image](https://github.com/user-attachments/assets/ab9ab038-c022-4063-9616-a9a14a50ff19)

**Comment by Sergeyz370** [comment]
Thank you.
