### ISSUE TITLE
[Feature request]Stewart 6DOF simulator platform 

### ISSUE THREAD

**Issue by cobra-blue** [SHWotever/SimHub#1704]
I have a Stewart 6DOF simulator platform but i don't know where can i set it.
![微信图片_20240510001043](https://github.com/user-attachments/assets/b355a87a-7d52-4fad-85ec-bfdd563868e8)

I only see this kind geometry
![12](https://github.com/user-attachments/assets/ca604cad-5be5-4a86-8eff-2e0caa340f79)

**Comment by SHWotever** [comment]
Hi ! Indeed stewart platforms are out of the scope at this time, you can read all the supported geometries on the website : https://www.simhubdash.com/simhub-motion-addon/
