### ISSUE TITLE
BeamNG.drive integration potentially breaking on updates

### ISSUE THREAD

**Issue by stenyak** [SHWotever/SimHub#1706]
Hi, this is Bruno, developer at BeamNG GmbH.

According to user reports, the simhub software appears to be installing files straight into the BeamNG.drive software install directories. Potentially even replacing preexisting official BeamNG.drive files.

If those reports are true, it means that any updates might lead to problems for the users. Such as broken functionality, crashes, etc. Due to incompatibility of simhub code with newer versions, due to Steam replacing files during integrity checks, etc.

It's also been reported that those modified files stay in BeamNG.drive install dir even after SimHub software is uninstalled, which makes it difficult for users to fix their broken BeamNG.drive.

Would it be possible that your SimHub implementation is modified, to use the new moddable protocols system? This will lower the chances of creating issues, it would allow users to disable or uninstall your plugin easily from in-game menues, etc.

More information can be found here: https://documentation.beamng.com/modding/protocols/

If you have any questions please feel free to ask. I'm also available via email in bgonzalez at beamng dot gmbh.

Thank you

**Comment by SHWotever** [comment]
Hi ! I will be happy to change it, at the time i did it it was the only way I found to get as low as the physical steps. 

I have already done the conversion, I just have a few details to clean, I will release an update within the week removing the old one at the same time.

**Comment by SHWotever** [comment]
Just an extra mention, I've seen some other mods overwriting game files, in this specific case it was an extra file being added, overwriting native game files is really above the redline and this is something I avoid. The file was added as an extension in lua\vehicle\extensions\auto

**Comment by stenyak** [comment]
> Hi ! I will be happy to change it, at the time i did it it was the only way I found to get as low as the physical steps.
> 
> I have already done the conversion, I just have a few details to clean, I will release an update within the week removing the old one at the same time.

Awesome, that's great to hear. You should have access to physics step with the new system too, if you have any difficulties let me know.



> Just an extra mention, I've seen some other mods overwriting game files, in this specific case it was an extra file being added, overwriting native game files is really above the redline and this is something I avoid. The file was added as an extension in lua\vehicle\extensions\auto

Are you talking about a mod in the official BeamNG repository, or somewhere else? We only pay attention to mods in the repo. So if that mod is one of them, it might have slipped through our checks - in that case can you link to the mod, so we can take a look? Thank you!

**Comment by SHWotever** [comment]
No no ;) , the one i've seen were modifying outgauge or outsim (I can't remember which one), It was not in the online repository, This is a way I did not took or liked. simhub telemetry extraction was installed in BeamNG.drive\lua\vehicle\extensions\auto
![image](https://github.com/user-attachments/assets/e26a570c-81b8-4fa3-9b5a-fcc48484e4f4)

**Comment by stenyak** [comment]
Ok I see. In any case, just to reiterate: installing files into the steam install dir is not recommended, as the changes may not persist over time, and may create conflicts when steam updates the app.

So the proper solution is to install into the userfolder (ideally in the form of a mod).

**Comment by SHWotever** [comment]
No problems ;) I've already released the update removing the old file and now working as a "protocol" mod ;)
