### ISSUE TITLE
Control mapped does not recognize wheel button before reconnect wheel

### ISSUE THREAD

**Issue by KommyKT** [SHWotever/SimHub#1708]
**Describe the bug**
My problem is that when I start the machine, I always have to disconnect the Simagic GT NEO with maglink in order for the Control Mapper to work. SimHub Control Mapper show Wheel is connected, i use bridge to output mode (arduino pro micro fw 1.3). 
I attached a debug log file.

**Simhub version**
9.4.9

[SimHub.txt](https://github.com/user-attachments/files/17167507/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! I close this,

As seen on discord last week, the wheel was not reporting inputs neither in windows, which means it's system/hardware related.

Just a little insight, from experience simagic does not work at boot depending of the usb port it was connected, stright from the computer or from an usb hub, this feels like an initialization issue in the wheel.
