### ISSUE TITLE
AMS2 [DataCorePlugin.GameData.EngineIgnitionOn] and [DataCorePlugin.GameData.EngineStarted] returning same value

### ISSUE THREAD

**Issue by Lemac-Strohs** [SHWotever/SimHub#1709]
AMS2 [**DataCorePlugin.GameData.EngineIgnitionOn**] and [**DataCorePlugin.GameData.EngineStarted**] seemingly return the same value.

Hence, my own created button box as well as Mr. Lovely's Dashboards cannot figure out when the ignition is on, but the engine is not yet started or not running. When the engine is off, so is the ignition. When the ignition is turned on after a button press (which you can hear in AMS2) **DataCorePlugin.GameData.EngineIgnitionOn** still returns a value of "0".  Once the engine is started, **DataCorePlugin.GameData.EngineIgnitionOn** then returns a value of "1".  AMS2 does have separate ignition and start engine functions.

Whether this is a SimHub issue or a AMS2 Telemetry issue I don't know.  According to SimHub these are both "Computed" properties.

I am running SimHub version 9.4.1 and I see there was some mention of updates to AMS2 telemetry in version 9.4.5. But it doesn't mention this issue. I could update to see, but after spending countless hours building stuff I don't like updating and having things break. An issue I too often have with software.

I'm just bringing it to your attention. I have already created a work around that works, but it's not the best solution. Because as I said, Mr. Lovely's dashboards show this problem as well so I had to update his dash myself.  But that doesn't work for all the others using his dashes.

If I do have a question, it's whether this has already been fixed and I should just update SimHub?

Thank you.

**Comment by Lemac-Strohs** [comment]
Ok, Nevermind. I found this is already a known issue (in french). Just ignore my post.

**Comment by SHWotever** [comment]
Hi ! Indeed the game doesn't provide the data so a fallback is used. https://github.com/SHWotever/SimHub/issues/878

Nicolas
