### ISSUE TITLE
Little bug with Govee H6056

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1713]
When area 4 of 6 ( the red one in picture 1) is triggered it also triggers LED 1. We experience this on two different computers. It's not happening when tested with the Govee app

![image](https://github.com/user-attachments/assets/30a9e4d3-9714-438f-9665-facac7fe2ab6)
![image](https://github.com/user-attachments/assets/418bfa0c-2eaa-467b-b135-1c2c1605e257)

Thanks in advance

**Comment by SHWotever** [comment]
Hi ! Thanks for the report. originally the govee app had the same issue, after fiddling I found which data has been changed for some sku (inclusint the h6056) to properly map the 6 areas, I've fixed it for the next version.
