### ISSUE TITLE
Simhub not uploading leoxz Simbridge 

### ISSUE THREAD

**Issue by mattiahappa** [SHWotever/SimHub#1714]
Simhub v9.4.9 is not uploading leoxz Simbridge v1.8.0.
I tried to enable the plug in but it won’t start.
I already tried to reinstall everything and I also tried to delete al the other plugins but nothing works.
![IMG_7851](https://github.com/user-attachments/assets/b9893357-5e97-4abf-a429-b51570e91dd7)

**Comment by SHWotever** [comment]
Hi ! Simbridge is a third party plugin and directly developed/maintained by leozx. for any questions/issues regarding this plugin you can contact them directly here : support@leoxz.com

**Comment by filowiener** [comment]
hey @mattiahappa,
did you find any workaround or any message from leoxz?
kind regards
