### ISSUE TITLE
Cosmetic: Spelling error on Motion plugin UDP Controller page

### ISSUE THREAD

**Issue by stuartlt** [SHWotever/SimHub#1720]
**Describe the bug**
The UDP Port label is incorrectly listed as 'Target UP port'

**Simhub version**
9.4.11

**Third party plugins**
N/A

**To Reproduce**
1. Go to 'Motion'
2. Click on 'add controller, UDP controller'
3. Scroll down to 'controller and look at able next to IP address, should say 'UDP' rather than 'UP'

**Expected behavior**
Should read as target UDP port.

**Screenshots**
See below:
![image](https://github.com/user-attachments/assets/0ed140b7-02bc-4531-9b26-5eb206a40e84)

**Log files**
NA/ this is cosmetic.

**Additional context**
N/A

**Comment by SHWotever** [comment]
Hi !

Thanks for the report, it's fixed for the next version,

![image](https://github.com/user-attachments/assets/529708ec-9050-4ba9-bf0e-5f3ff424b3db)


Best regards,
Nicolas
