### ISSUE TITLE
Orientación Led

### ISSUE THREAD

**Issue by CarlosGSi** [SHWotever/SimHub#1723]
Hello. I have connected an Arduino Pro Micro with Led 8x8 Grid and the image it projects is in mirror format. I only see the option to rotate but. Greetings and thanks.
![Foto2](https://github.com/user-attachments/assets/f4487bae-b9b4-4853-9038-72c6e3b834c6)

**Comment by SHWotever** [comment]
Hi ! Can you provide the datasheet of your matrix and where you bought it ? Apparently the LEDs are completely arranged on reverse which is uncommon.

**Comment by CarlosGSi** [comment]
https://a.aliexpress.com/_EHdsVNj
