### ISSUE TITLE
Simhub freeze when activating other game or at exit from Simhub

### ISSUE THREAD

**Issue by Jules-TS** [SHWotever/SimHub#1725]
**Describe the bug**
When I switch to an other game, or exit from Simhub, the Simhub freeze for a few minutes. I can break the freeze by disconnecting the arduinos. I think the problem is with the serial display, but I don't use Vocore anymore.

**Simhub version**
9.4.11

**Third party plugins**
Third party plugins disabled.

**To Reproduce**
1. connect arduions to the PC
2. start simhub
3. click on an other game, or switch to an other game (Autodetect current game is on)
4. freeze for few minutes

**Expected behavior**
Not to freeze.

**Screenshots**

**Log files**
 [SimHub.txt](https://github.com/user-attachments/files/17397906/SimHub.txt)

**Additional context**
I can break the freeze by disconnecting the arduinos. I think the problem is with the serial display, but I don't use Vocore anymore.

I have 3 arduino uno (5x 7segments, a 20x4 LCD, an 8x8 matrix, 128x Led, 2x wind, a tacho) and a pro micro (64x Led, 4x rotary, 20x button).
https://4utem.blogspot.com/2024/07/dashboard-v40.html

**Comment by SHWotever** [comment]
Hi ! Based from the logs I see that indeed the arduino is extremely to close. I see you have some encoders linked, those can "spam" the usb and make it unresponsive. Can you check that all encoders works as expected and try to disable them ?

**Comment by Jules-TS** [comment]
> Hi ! Based from the logs I see that indeed the arduino is extremely to close. I see you have some encoders linked, those can "spam" the usb and make it unresponsive. Can you check that all encoders works as expected and try to disable them ?

The rotaries works well.
I deleted the rotaries from the sketch, and uploaded to the pro micro, and disconnected the rotaries from the pro micro. But the freeze is still happens.

Thanks,
Gyula

**Comment by SHWotever** [comment]
Could you try to unplug them one by one to locate which one is causing the hang ? That would allow to focus on the one making it hang.

**Comment by Jules-TS** [comment]
> Could you try to unplug them one by one to locate which one is causing the hang ? That would allow to focus on the one making it hang.

Unfortunately, it was not possible to determine which freezes it. because they are on the same hub and I unplug any of them, they all restart.

**Comment by Jules-TS** [comment]
> They all restart ? That should not happen, the hub could be the culprit then. Have you tried to skip it as recommended in the usb issues guide ? https://github.com/SHWotever/SimHub/wiki/USB-Issues-Troubleshooting

I will try to find the error based on that.
