### ISSUE TITLE
Control Mpper - Unable to Bridge/Flash Arduino ATmega32U4 Pro Micro - 'Could not open serial port'

### ISSUE THREAD

**Issue by Dreese001** [SHWotever/SimHub#1726]
**Describe the bug**
 Unable to Bridge/Flash Arduino ATmega32U4 Pro Micro - 'Could not open serial port'

**Simhub version**
9.4.13

**Third party plugins**
Not sure of this 

**To Reproduce**
1. Go to 'Control Mapper'
2. Click on 'Bridge then 'Flash Update''
3. Select 'COM40'
4. Leave 'Single Controller' selected
5. Tick 'I understand'
6. Click 'Flashversion 1.3'
7. Error - could not open serial port

**Expected behavior**
ATMega to be flashed so that I can use in Control Mapper

**Screenshots**
- see attched
![1 DeviceM](https://github.com/user-attachments/assets/2aa3db1b-e62d-4376-b348-60b8cd854643)
![2 Pre-Flash](https://github.com/user-attachments/assets/68fba3e3-1173-4688-bf58-29ac1774c9db)
![3 Error](https://github.com/user-attachments/assets/267b9297-cb08-491c-952a-d6759efc2a09)
![4 Could not flash](https://github.com/user-attachments/assets/7dc4921e-2b06-408f-aab8-646523335dda)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).
[SimHub.1.txt](https://github.com/user-attachments/files/17404125/SimHub.1.txt)

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
[SimHub.1.txt](https://github.com/user-attachments/files/17404123/SimHub.1.txt)

**Additional context**
I've manually changed the Com Port number various times but same error

**Comment by SHWotever** [comment]
Hi ! Could you try to flash it with a blank sketch  with a basic arduino IDE to see if it reacts correctly ? Seeing the error it looks like the arduino is not behaving as it should.

you can download the arduino ide here : https://www.arduino.cc/en/software

**Comment by Dreese001** [comment]
<img width="1274" alt="13" src="https://github.com/user-attachments/assets/e6752aeb-6d28-4038-8a39-cb1c81b07e87">
Looks to be an issue with Arduino

**Comment by Dreese001** [comment]
I purchased another Arduino (Leonardo this time). It flashed with no issue. Control Mapper is now setup and working. Thanks SHWotever
