### ISSUE TITLE
Windows Defender Blocking download of 9.4.7 saying it has a VIRUS 

### ISSUE THREAD

**Issue by andredurand** [SHWotever/SimHub#1731]
**Describe the bug**
This is not a bug per say. Just didn't know where to provide this feedback. I'm running 9.3.8 and was trying to upgrade to 9.4.7. Upon download, Windows Defender blocks the file download saying VIRUS DETECTED. Looking at the details it says it's a Trojan.  

**Simhub version**
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi ! You can read about antivirus false positives here : https://github.com/SHWotever/SimHub/wiki/Antivirus-false-positives

I try to keep fighting against false positives against latest version, but it's unfortunately impossible to scan the hundreds of previous ones against false positives which could have come later: for false positives against older versions does not hesitate to submit it to your antivirus: false positives submissions form is available here for Microsoft: https://www.microsoft.com/en-us/wdsi/filesubmission?persona=HomeUser )
