### ISSUE TITLE
impossible to connect to the simhub forum

### ISSUE THREAD

**Issue by Pedjy** [SHWotever/SimHub#1737]
Hello, I can't connect to the SimHub forum at all. Emails don't come back to me on three different addresses. Do you have a server problem?

**Comment by SHWotever** [comment]
Hi !

I tested it with free which it seems to be the provider of all the email you used. It seems that indeed it's rejecting any mails for now. I've switched to another email method which should now work with free.

Best regards,
Nicolas Guilbert

**Comment by Pedjy** [comment]
Ça ne marche pas, si je fais mot de passe oublié, ça me ferme la fenêtre pour revenir au forum. Si je veux me réinscrire ça me met cette adresse mail est déjà utilisée veuillez en essayer une autre.  Je ne peux absolument rien faire.

**Comment by SHWotever** [comment]
Could you send the account you are trying to connect to over https://www.simhubdash.com/simhub-contact/ I will check it.

**Comment by Pedjy** [comment]
I just received an email from <wordpress@simhubdash.com> who gave me a new password for my nickname Pedjy. I associated it with my address philippe.djury@free.fr with which I had taken my paid license. For the moment everything works. Thank you very much
Philippe
