### ISSUE TITLE
The map American Truck Simulator

### ISSUE THREAD

**Issue by Sergeyz370** [SHWotever/SimHub#1738]
**Describe the bug**
The map of the American truck simulator is not fully loaded
**Simhub version**
9.5.0

**Screenshots**
![2024-10-24 194547](https://github.com/user-attachments/assets/f6312e78-1a44-4702-ac8f-3d1a94c5d7ae

**Comment by SHWotever** [comment]
Hi Thanks for the report, I've updated the map :
![image](https://github.com/user-attachments/assets/6159060a-9401-498c-ad48-d7fec27aa4bc)

To download the latest version you can follow those instructions :
https://github.com/SHWotever/SimHub/issues/1703#issuecomment-2355866166

**Comment by Sergeyz370** [comment]
Thank you very much!!!

**Comment by Sergeyz370** [comment]
Hello! We need to update the maps again ATS & ETS2. Thanks.

**Comment by SHWotever** [comment]
Hi I've published the maps updates ;) 
To download the latest version you can follow those instructions :
https://github.com/SHWotever/SimHub/issues/1703#issuecomment-2355866166

**Comment by Sergeyz370** [comment]
Thanks for the quick update!! )))
