### ISSUE TITLE
Cannot Update lastest version

### ISSUE THREAD

**Issue by dgvoiceovers** [SHWotever/SimHub#1743]
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by dgvoiceovers** [comment]
![20241103_125125](https://github.com/user-attachments/assets/6848034c-bcf0-4bb1-ba8e-8f2f1bbca383)

I get this every time now for some reason. The last update I was able to download was version 9.04.9 cannot get this to download at all.

**Comment by SHWotever** [comment]
Hi ! 

This is a edge blocking behaviour based on reputation, you can read more informations about such "reputation based behaviours"  here : https://github.com/SHWotever/SimHub/wiki/Antivirus-false-positives

In edge you can accept the files here : 

![image](https://github.com/user-attachments/assets/93e6fa0b-ca12-4b23-9ab5-8fabedab1f6a)

Do not hesitate to report it to microsoft : https://www.microsoft.com/en-us/wdsi/filesubmission ( As indicated I already did it for this release, but microsoft have not processed it yet)
