### ISSUE TITLE
Studio crash after a few minutes..

### ISSUE THREAD

**Issue by Christ-Dek** [SHWotever/SimHub#1744]
**Describe the bug**
Studio crashes after a few minutes..
Impossible to work properly in the studio because it freezes after a few minutes.
As if the SSDs were out of order... You have to constantly kill the process and restart simhub, plus I sometimes lose my work even if it was saved before the crash.
I'm not the only one in this case, so where is the problem please?
Thank you for your support, cordially.

**Simhub version**
version 9.5.2

**Third party plugins**
![427E4BEF-0EE7-4235-96DD-1B2D4ED0C0EE](https://github.com/user-attachments/assets/08d4d244-6373-40b7-b49b-b11463e6486c)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
[SimHub.1.txt](https://github.com/user-attachments/files/17649416/SimHub.1.txt)
[SimHub.2.txt](https://github.com/user-attachments/files/17649418/SimHub.2.txt)
[SimHub.3.txt](https://github.com/user-attachments/files/17649419/SimHub.3.txt)
[SimHub.4.txt](https://github.com/user-attachments/files/17649420/SimHub.4.txt)
[SimHub.5.txt](https://github.com/user-attachments/files/17649421/SimHub.5.txt)
[SimHub.6.txt](https://github.com/user-attachments/files/17649422/SimHub.6.txt)
[SimHub.7.txt](https://github.com/user-attachments/files/17649423/SimHub.7.txt)
[SimHub.8.txt](https://github.com/user-attachments/files/17649424/SimHub.8.txt)
[SimHub.9.txt](https://github.com/user-attachments/files/17649425/SimHub.9.txt)
[SimHub.10.txt](https://github.com/user-attachments/files/17649426/SimHub.10.txt)
[SimHub.11.txt](https://github.com/user-attachments/files/17649427/SimHub.11.txt)
[SimHub.12.txt](https://github.com/user-attachments/files/17649429/SimHub.12.txt)
[SimHub.13.txt](https://github.com/user-attachments/files/17649430/SimHub.13.txt)
[SimHub.14.txt](https://github.com/user-attachments/files/17649431/SimHub.14.txt)
[SimHub.15.txt](https://github.com/user-attachments/files/17649432/SimHub.15.txt)
[SimHub.16.txt](https://github.com/user-attachments/files/17649433/SimHub.16.txt)
[SimHub.17.txt](https://github.com/user-attachments/files/17649434/SimHub.17.txt)
[SimHub.18.txt](https://github.com/user-attachments/files/17649435/SimHub.18.txt)
[SimHub.19.txt](https://github.com/user-attachments/files/17649436/SimHub.19.txt)
[SimHub.20.txt](https://github.com/user-attachments/files/17649438/SimHub.20.txt)
[SimHub.txt](https://github.com/user-attachments/files/17649440/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! Could you join the dash you were editing ? Usually this happens caused by some very specific conditions. On your screen shot you are showing an open dialog, is it always freezing with this dialog ? Which one is it ?

**Comment by Christ-Dek** [comment]
It seems that it freezes as soon as you open an action like adding an image, editing a widget etc. In short, the problems usually occur after a few minutes of use.
For your information, I have disabled almost all the plugins, except those I need like dash studio and devices...
Pour info j'ai désactiver presque tout les pluggins, sauf ceux dont j'ai besoin comme le dash studio et devices...
![Scania 1 1 djson 00](https://github.com/user-attachments/assets/434a1f69-504f-4c0a-bae8-ad37b5c7dd9a)
![Scania 1 1 djson 01](https://github.com/user-attachments/assets/8f163960-0c96-491a-808e-75f3b22d2fe4)
![Scania 1 1 djson 02](https://github.com/user-attachments/assets/1be31c44-90df-417b-9001-a0aae74f73b2)
![Scania 1 1 djson 03](https://github.com/user-attachments/assets/3dcc9513-3359-40eb-907b-8b9d7595cdae)
![Scania 1 1 djson 04](https://github.com/user-attachments/assets/6bdb311a-cd59-47cc-a89a-0856d57c1c23)
![Scania 1 1 djson 05](https://github.com/user-attachments/assets/3ff11ef8-4677-422a-8a30-d66c6da8ea9b)
![Scania 1 1 djson](https://github.com/user-attachments/assets/dd032c5e-ab74-443a-b5b6-dff9d0722fe1)

**Comment by SHWotever** [comment]
could you join the dash file itself ?

**Comment by Christ-Dek** [comment]
It seems that it freezes as soon as you open an action like adding an image, editing a widget etc. In short, the problems usually occur after a few minutes of use.
For your information, I have disabled almost all the plugins, except those I need like dash studio and devices...

I can't post the table file :/

**Comment by SHWotever** [comment]
If you just zip the exported dash file it should be enough to post it here, alternatively a website like https://wetransfer.com/ allows to easily share any files with less restrictions about the size.

**Comment by Christ-Dek** [comment]
[Scania 1.1.zip](https://github.com/user-attachments/files/17650112/Scania.1.1.zip)

**Comment by Christ-Dek** [comment]
I have the impression that simhub32 takes ram and does not unload it. Even after closing the studio and the main window, the exe consumes more than 800MB and remains at + 20% cpu usage...
This is not normal, you have to kill the process and restart the exe.

**Comment by SHWotever** [comment]
Hi ! I confirm it goes really heavy, I'm spotting the 10 gauges per page which are the bottleneck I think. I will investigate if it can be optimized, indeed the memory is growing quickly with them, if there is still enough room it will release it later, but when editing quickly it can go really fast and overpass the memory limit and crash .

In the wait you can make it quite faster at least in execution by not duplicating all the screens content,

you can create a background layer containing only your "base commune" widget
![image](https://github.com/user-attachments/assets/3756246f-d2a2-4f84-b9d6-17fde099071a)

Then in all screens remove the "base commune" widget and set your new "background layer"

![image](https://github.com/user-attachments/assets/c0efd84d-08c3-4402-9687-f75c855bd0c1)

This way during execution it won't have anymore to handle around 60 gauges spread across all the screens but only the 10. Which will make screen loading much faster

**Comment by Christ-Dek** [comment]
Ah ok, I see what the problem is yes.
I have looked for tutorials explaining the implementation of widgets, but it is poor on the web...
I will test this immediately and see the difference then.
Thanks, I will come back for the feedback.

**Comment by Christ-Dek** [comment]
It seems to work, but I still needed patience to succeed...
Thanks for the support, I'll go to sleep less stupid tonight ;)
