### ISSUE TITLE
SIMlab SD43X

### ISSUE THREAD

**Issue by Taiska83** [SHWotever/SimHub#1746]
**Describe the bug**
SIMLAB43X does not work after version 9.0.4. The Simhub application does recognize the screen, but it doesn't work. 9.0.4 is the last version where the display works

**Simhub version**
Make sure to run the latest version
Now it's 9.5.3 but I have to update back to 9.0.4 to get the screen working. The old software version does not support new games, but the screen works

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi !

Could you include the following logs ? 

> Screenshots
If applicable, add screenshots to help explain your problem.

>Log files
>Join log files available in C:\Program Files (x86)\SimHub\Logs
>Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

In addition could you join this specific log file ? C:\Users\nguil\AppData\Local\SimHub\CefSharp\Cefsharp.log

Do you have any specific insights about the setup Graphics card, exact os ? I already had one similar report, but I could not find a pattern yet explaining it.

**Comment by Taiska83** [comment]
I hope I did it right now. there should be all the logs and apparently 
from different versions that I've tried

t: Antti

Wotever kirjoitti 2024-11-08 08:27:

**Comment by Taiska83** [comment]
HELLOU
I feel stupid. I'm sorry.
In previous versions of Simhub, the dashboard worked correctly under the 
name simlab sd43x, but not in the new ones.

If the meter is used as a USB monitor, then it works. Sorry for the 
trouble once again.

t. Antti

Wotever kirjoitti 2024-11-08 08:27:

**Comment by SHWotever** [comment]
Thanks for the feedback, indeed now you're you can't use the wrong models anymore. The simlab screen will only work with this exact model.
