### ISSUE TITLE
[Feature request] Farming Simulator 25

### ISSUE THREAD

**Issue by Dezza069** [SHWotever/SimHub#1749]
**Is your feature request related to a problem? Please describe.**
The problem is I am very used to shaking around with the SimHub driven bass-shakers when driving other games, and getting some feedback like the tractors' engines in previous Farming Simulator releases, and would really like to be doing the same with the latest version of Farming Simulator 25 :)

**Describe the solution you'd like**
Would absolutely love a game-mod which outputs as much vehicle data as possible, maybe suspension movements if that's available. Also other things like vehicle brand/model, speed, gear, various light(s) status, cruise control speed/on/off, GPS engaged, heading, in game time/day/season, current farm name/money, on a field, etc. Would be absolutely fantastic if stuff like attachment/hitch position (ie raised/lowered/active, etc) were also available.

**Describe alternatives you've considered**
I haven't considered any alternatives - I love your program and the Farming Simulator series. Although sometimes play other games like BeamNG, European and American Truck Simulator(s) which interact very well with your app.

**Additional context**
Please and thank you very much!!!

**Comment by SHWotever** [comment]
Hi ! I'm waiting for the release of the GIant Studio utility allowing to build a mod, the game have changed enough to break the current mod and it needs to be troubleshooted.

**Comment by Dezza069** [comment]
Hello!

Thank you very much!

**Comment by SHWotever** [comment]
Hi !  It will be released with the next version, probably this week.

**Comment by Dezza069** [comment]
Thank you! Very excited for your update!

Kind regards :)
