### ISSUE TITLE
[Feature request] Control mapper - unlatch existing FN-latch

### ISSUE THREAD

**Issue by lewisst** [SHWotever/SimHub#1753]
Looking got an option to unlatch a existing latch when pressing another button.

**Usecase:**
I have a FN set by `Momentary to Latching`, this allow the buttons on my wheel to become Replay controls: _(FF, RR, next car, incident, camera etc)_

Been able to assign an **unlatch** to my `drive/enter car` button means that the camera controls are then disabled automatically and don't interfere driving

This out-of-car control via FN-latch can also be used to navigate UI _(i.e via keyboard mapping)_ and auto disable in car.

Similarly, a FN-latch could be used allow wheel buttons to control pit option, while pit-limiter press would switch off the latch _(assuming you tweak options before hitting pit lane!)_

**Comment by SHWotever** [comment]
Hi ! this has been released with the latest version
