### ISSUE TITLE
XAML Binding Failures

### ISSUE THREAD

**Issue by blekenbleu** [SHWotever/SimHub#1756]
**Describe the bug**

Noticed while sorting XAML Binding Failures in prototype plugin,
- 3 were reported with NO optional features or plugins enabled
- 3 more when clicking "Add/remove features"

**Simhub version**
Make sure to run the latest version
- 9.5.4

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)
- none enabled

**To Reproduce**
1. Launch SimHub 9.5.4 by `Debug` from Visual Studio Community 2022 (64-bit) 17.12.0 in Windows 11 Home 23H2
    with all features previously deselected
2. In Visual Studio:  Select XAML Binding Failures
3. In SimHub: Click **Add/remove features**
4. Observe three errors at step 2,  three more at step 3

**Expected behavior**
- No XAML Binding Failures reported
![XAML](https://github.com/user-attachments/assets/d98a7e96-650a-4744-b119-ebbeb8d2bc89)
[xaml.txt](https://github.com/user-attachments/files/17797652/xaml.txt)
[SimHub.txt](https://github.com/user-attachments/files/17797659/SimHub.txt)

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Those are internal binding errors to simhub (they are only temporary during loading actually),  the debugger can't make a difference between the "SDK" related errors and the whole application, it just acts as a logger catching everything.
