### ISSUE TITLE
Connecting Arduino produces high CPU Load

### ISSUE THREAD

**Issue by tomster84** [SHWotever/SimHub#1757]
**Describe the bug**
The moment i add an arduino (2 Race Flags) to Simhub, the CPU-Load is permanently at 22-25% ! (CPU fan going crazy too)
 When i disable the Arduinos (Stop Simhub from Scanning the Ports) everything is normal at around 1.5-2% CPU load... 

**Simhub version**
Simhub 9.5.4 fresh install
Tested  with 9.5.1 -° same issue

**Third party plugins**
none

**To Reproduce**
1. Go to Arduino
2. Click on My Hardware
3. Simhub starts Scanning and Connects to the Arduinos - CPU Load goes up, CPU fan goes crazy
Screenshot: 
![flags](https://github.com/user-attachments/assets/45b2ef35-248b-43ad-9e37-5caa3a2b1f48)

**Expected behavior**
CPU Load should stay around 1-2%

**Log files**
[SimHub.txt](https://github.com/user-attachments/files/17852531/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! Are you using DNR profiles for them ?

**Comment by tomster84** [comment]
Hey!

Nope, i'm not using DNR. Even without any profile activated the cpu load rises as soon as the arduinos are in status "connected". 

Arduinos Identify as CH340 if that helps.

**Comment by tomster84** [comment]
Thank you SHWotsoever for your reply.

I just wanted to let you know, that i solved the issue myself.
It wasn't on SIMHUB. I had do delete/remove the Arduino USB Devices (CH340) from the Windows Device-Manager, deleting the USB Drivers. After a Restart and windows automatic reinstalling of the dreviers, everything works as intended.

It seems that the drivers of the USB Controllers caused that starnge problem.

Thank you anyways! :)
