### ISSUE TITLE
Air and Track Temps in Dashboard show in Celsius even though AMS2 is set to Fahrenheit

### ISSUE THREAD

**Issue by TigerDave99** [SHWotever/SimHub#1759]
**Describe the bug**
AMS2 and SimHub both set to Fahrenheit, yet Lovely Dashboard shows Track and Air temps in Celsius.

**Simhub version**
9.5.4

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**
1. Set SimHub Settings to Fahrenheit
2. Set AMS2 Settings to Fahrenheit
3. Lovely Dashboard shows track and air temp in Celsius
4. Already contacted dev for Lovely Dash and confirmed that issue is most likely with SimHub.

**Expected behavior**
Expected Lovely Dashboard to display Fahrenheit for air and track temps.

**Screenshots**
Attached.
![screencap-simhub](https://github.com/user-attachments/assets/0c842f7c-b665-48a9-bf7d-e7f19f6e810d)
![screencap-ams2](https://github.com/user-attachments/assets/3321edec-8bf0-4454-94e7-4719e66196af)
![screencap-ams2-2](https://github.com/user-attachments/assets/1a80beb9-9fb3-406a-ad8f-45a27ddb2b88)
![screencap-lovely](https://github.com/user-attachments/assets/6e65f784-ffd7-4d66-90cf-75e981c36d6f)

**Log files**
[SimHub.1.txt](https://github.com/user-attachments/files/17908791/SimHub.1.txt)
[SimHub.2.txt](https://github.com/user-attachments/files/17908792/SimHub.2.txt)

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi !

I checked track and air temperatures are correctly converted :

![image](https://github.com/user-attachments/assets/98cdc6af-fdb0-4951-8dab-82b56ab482c0)

The issue must be inside the dash itself hand how it has been built.
