### ISSUE TITLE
probleme transfere donne instantané 

### ISSUE THREAD

**Issue by alex18042006** [SHWotever/SimHub#1760]
Décrivez le bug
Lors de l’utilisation de SimHub pour traiter les données en temps réel provenant de F1 2024, le traitement des données UDP semble échouer de manière intermittente, entraînant une perte de certaines informations critiques (comme les données de position ou d’usure des pneus).

Version SimHub

La version actuelle utilisée est : la dernière .

Plugins tiers
Tous les plugins tiers ont été désactivés pour reproduire le problème sans interférences.

Pour reproduire
Étapes pour reproduire le comportement :

Allez dans « Paramètres » -> « Jeux » -> « F1 2024 ».
Activez le traitement des données en temps réel via le protocole UDP.
Lancez une session de course dans F1 2024 avec le port UDP correctement configuré.
Observez les données dans le tableau de bord SimHub.
Comportement attendu
Les données en temps réel (position des pilotes, type de pneus, niveaux ERS, etc.) doivent être transmises sans interruptions ni erreurs visibles.

Captures d’écran
Le cas échéant, veuillez joindre une capture d’écran du tableau de bord SimHub montrant les informations manquantes ou incorrectes.

Fichiers journaux
Les journaux de SimHub pertinents sont joints à ce rapport. Ils se trouvent dans :
C:\Program Files (x86)\SimHub\Logs

Contexte supplémentaire
Le problème semble survenir uniquement lorsque les données transmises par le jeu augmentent en complexité, comme en cas de nombreux événements simultanés (drapeaux jaunes, changement de météo, etc.).
Il pourrait être utile d’optimiser le traitement des paquets UDP pour éviter ces interruptions.

de plus le traitement des donne et de quel matiere est ce du binaire ou autre ils semblerais interessant que l'envoie des donne ce fasse par texte merci

**Comment by SHWotever** [comment]
Bonjour, pouvez vous joindre les fichiers de log lorsque cela arrive ?

```
Fichiers journaux
Les journaux de SimHub pertinents sont joints à ce rapport. Ils se trouvent dans :
C:\Program Files (x86)\SimHub\Logs
```
