### ISSUE TITLE
Control Mapper configuration reverting on next startup

### ISSUE THREAD

**Issue by GarlicPunk** [SHWotever/SimHub#1762]
**Describe the bug**
Control mapper is not loading last active configuration

**Simhub version**
9.6.0

**Third party plugins**
None

**To Reproduce**
1. Go to 'control Mapper'
2. Output mapping click on 'Assign Role' and create a new role (or rename existing)
3. Exit simhub
4. Load simhub
5. Role modification is missing

**Expected behavior**
Retaisn configuration that was shown in simhub on exit, and startup with that configuration

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Not errors in log.
.

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**
Import / export function allow import/export but i have to reload on conifugration on each PC boot. (configs attached)

[SimHub.txt](https://github.com/user-attachments/files/17968160/SimHub.txt)
[SimHub.1.txt](https://github.com/user-attachments/files/17968161/SimHub.1.txt)
[FANATEC Wheel - FS_WHEEL_SWTYPE_CSSWRS.shcmapping.txt](https://github.com/user-attachments/files/17968165/FANATEC.Wheel.-.FS_WHEEL_SWTYPE_CSSWRS.shcmapping.txt)
[default_outputmapping.shomapping.txt](https://github.com/user-attachments/files/17968166/default_outputmapping.shomapping.txt)

**Comment by GarlicPunk** [comment]
Hot Fixed in 9.6.1

**Comment by SHWotever** [comment]
Hi ! Thanks for the report, this was indeed fixed in yesterday release.
Nicolas
