### ISSUE TITLE
MSFS 2020 Simconnect issue

### ISSUE THREAD

**Issue by gaddster** [SHWotever/SimHub#1765]
**Describe the bug**
Although it appears simhub detects the running game it is permanently waiting for data.  Large amount of errors in log data is then written for each connection attempt.

**Simhub version**
9.6.1

**Third party plugins**
N/A

**To Reproduce**
Launch MSFS either externally or within simhub
See error logs

**Expected behavior**
telemetry data read & interpreted from simconnect

**Screenshots**
![msfs-sh1](https://github.com/user-attachments/assets/e8fb2548-75c6-4625-8c69-f0f968ce50ab)
![msfs-sh2](https://github.com/user-attachments/assets/791363e9-9169-439e-b711-b8521d5475a1)

**Log files**
[logs.zip](https://github.com/user-attachments/files/18012393/logs.zip)

**Additional context**
I've tried: 
Disabling all MSFS addons, other simconnect apps are working ok ie Axis & Ohs, fs2crew, fsltl etc..
Disabled Windows firewall
Starting MSFS from within simhub
Other simhub apps are working ok using the same sound output ie AMS2, AC
Sound device is set to allow exclusive & additional effects disabled.
Apologies if there is something I've missed, MSFS doesn't appear to have any config requirement.

**Comment by SHWotever** [comment]
Hi ! The error is not tied to simconnect but to networking,between the reader process and simhub. On your computer 127.0.0.1 is not recognized. This is often the symptom of a firewall or a VPN blocking communications.

Can you try to disable your VPN if you have any and/or your firewall ?

**Comment by gaddster** [comment]
Hey there - Thanks for the quick reply.  I had tried sans firewall but you're right about the VPN.  When I closed that app and started msfs/simhub without the vpn it worked.  Tried adding the main simhub exe & the simhubfs.exe to the vpn split tunnelling list but still doesn't play if the vpn is up & running first.  Can you see any 'trick' around this or is it just how it is?
cheers

**Comment by SHWotever** [comment]
Hi ! That really depends of your vpn, I know by experience that 127.0.0.1 get locked is caused by aggressive VPNs, but cohabitation depends of each one. If somehow you have IP exclusions in the settings excluding 127.0.0.1 could help.

**Comment by gaddster** [comment]
Thanks again, it doesn't look possible without quiting the vpn app first, easy to sort at least..  Thank you
