### ISSUE TITLE
Slow/laggy RPM LEDs response since Simhub V9.6.1

### ISSUE THREAD

**Issue by GiuseppeC86** [SHWotever/SimHub#1769]
**Describe the bug**
Since the latest build of SimHub I noticed very slow and laggy feedback from my LEDs mounted on the SimDash dashboard which uses an Arduino board. Basically, whenever I shift gear (both up or down) I don't get the RPM drop or raise instantly, but this happens with about half a second delay. The issue is not consistent though, but it can happen at least 5 to 10 times in a lap. Never had such problems in the past and nothing has changed in my SimRig.

**Simhub version**
9.6.1

**Third party plugins**
Only plugin installed is the RomainRob iRacing Property plugin, which didn' t get any update since last January.

**To Reproduce**
Not applicable.

**Expected behavior**
Not applicable.

**Screenshots**
Not applicable.

**Log files**
I don' t think a log can help identify the issue in this case, as the RPM LEDs work properly, they' re just laggy and unresponsive.

**Additional context**
Only sims installed in my PC are: iRacing, rF2 and ACC. All of the three titles have this issue.

**Comment by GiuseppeC86** [comment]
> Hi ! Can you check you are not a victim of fake CH340G ? They create very bad CPU over consumptions since latest windows update delivered driver You can see identification informations and a fix here :
> 
> https://github.com/SHWotever/FakeCH340DriverFixer
> 
> Can you also join the log files anyway, even if no error are visible they help me to get a better "overview" of what is around.

Thank you for your message:

So, first of all I'm investigating it I have a fake chip or not. Reading "The device will appear as a CH340 in the device manager as USB-SERIAL CH340" means that if I see this on my device manager I can assume I have a fake chip or this name is also seen like this for genuine chips?
I will try to follow the steps and send you a log soon.

By the way, just for information, my Windows updated last week to the 24H2 version, and I remember I installed the new SimHub version right after the Windows update. I also remember that not long ago, maybe 2 weeks, Windows update updated automatically my Ch340 drivers even if they were already installed...
I can also say that after the 24H2 update, I can hear my CPU always under load, like 5%, and the fans are always active (it has never been the case before all these updates).
Now I need to investigate what' s causing the issue... Arduino, 24H2 update or SimHub...

**Comment by SHWotever** [comment]
> So, first of all I'm investigating if I have a fake chip or not. Reading "The device will appear as a CH340 in the device manager as USB-SERIAL CH340" means that if I see this on my device manager I can assume I have a fake chip or this name is also seen like this for genuine chips?
I will try to follow the steps and send you a log soon.

In device manager the name just tells it's identified as a CH340G (in opposition to FTDO or other chips models), the most undoubtful way is if the chip has no marking, if it has markings (which is really rare on fake chips) it's more subtil, just like the effects of this new driver which indeed makes CPU usage crazy.

Yes the driver update I was mentioning is the one you got clearly, it's the second time WCH (the original manufacturer of the chip) delivers drivers against fake chips. Last year it has been hitting a lot of them (but not all), it looks like this new one is reaching even more people and in a more sneaky way (Over cpu consumption, lost data etc ...).

**Comment by GiuseppeC86** [comment]
> > So, first of all I'm investigating if I have a fake chip or not. Reading "The device will appear as a CH340 in the device manager as USB-SERIAL CH340" means that if I see this on my device manager I can assume I have a fake chip or this name is also seen like this for genuine chips?
> > I will try to follow the steps and send you a log soon.
> 
> In device manager the name just tells it's identified as a CH340G (in opposition to FTDI or other chips models), the most undoubtful way is if the chip has no marking, if it has markings (which is really rare on fake chips) it's more subtil, just like the effects of this new driver which indeed makes CPU usage crazy.
> 
> Yes the driver update I was mentioning is the one you got clearly, it's the second time WCH (the original manufacturer of the chip) delivers drivers against fake chips. Last year it has been hitting a lot of them (but not all), it looks like this new one is reaching even more people and in a more sneaky way (Over cpu consumption, lost data etc ...).

Thank you Wotever, that is clear now.
Just a quick update:
- I followed the procedure and my chip has been identified as a potential fake. So I executed the installer, and the driver now reverted back to the 3.5.2019.1. I can already say that after rebooting the PC after the installation, the CPU usage went back to 0% at idle and the case fans are now silent. Unfortunately, I do not have now the time to test the sim and the behaviour of the LEDs, but I will report back with logs in the following days.

For now, thank you so much for your kind support and have a nice day.

**Comment by GiuseppeC86** [comment]
Hello.

I can confirm the issues I was experiencing were caused by the newer drivers. By the way, I'm experimenting a few things, and since I used the " FakeCH340DriverFixer " executable, I'm not able to install the new driver back again since it is now blocked.
Reading the instructions it says " Execute FakeCH340DriverFixer.exe unblock to revert the windows update changes, then you can use windows update to reinstall the latest driver update ", but I don' t know how and where to put that "unblock" string after the .exe
Any suggestion? Thank you.
