### ISSUE TITLE
reverse pitch

### ISSUE THREAD

**Issue by willyx77** [SHWotever/SimHub#1771]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hello how to reverse the pitch for airplane games

**Comment by SHWotever** [comment]
Hi ! 

Currently it's not possible,
Could you explain more in details why pitch would need to be reversed ?

**Comment by willyx77** [comment]
I made a mistake, the pitch doesn't work on my flight simulator 24, do you have an idea of ​​the problem?
