### ISSUE TITLE
too many cars in forza horizon 5?

### ISSUE THREAD

**Issue by Furti666** [SHWotever/SimHub#1773]
**Describe the bug**
Simhub hangs on startup
Last entry in log file:
[2024-12-08 17:55:25,467] INFO - Creating Forza Horizon 5 game manager (GSIReader.ForzaMotorsport7.FH4Manager)

**Simhub version**
9.6.1

**Third party plugins**
sjdawson.TruckSimulatorPlugin

**To Reproduce**
n.a.

**Expected behavior**
After deleting 98080 files in 

C:\Program Files (x86)\SimHub\PluginsData\FH5\Cars 

SimHub starts again :o)
Maybe you can fix it.

**Screenshots**
n.a.

**Log files**
done

**Additional context**
n.a.
[SimHub.txt](https://github.com/user-attachments/files/18053264/SimHub.txt)

**Comment by SHWotever** [comment]
Hi !

It looks like some wrong data being sent over the same port generating random data making it recognize more cars than it should. I've added a packet filter for the next version, hopefully it will filter those wrong data.
