### ISSUE TITLE
MINI RX car in AMS2 breaks Simhub

### ISSUE THREAD

**Issue by Escher89** [SHWotever/SimHub#1774]
**Describe the bug**
Driving the Mini RX car in AMS2 breaks Simhub (in my case my two dashes (Android and iOS) and my bass shakers aren't working. My dashes will freeze, they'll get some data when I pause though but remain frozen when I unpause.

**Simhub version**
9.6.1

**Third party plugins**
Lovely Plugin (I'm not using Lovely Dash right now), NonMementaryIgnition, rF2 Simhub Plugin, Truck Simulator Plugin, Headlight Flasher

**To Reproduce**
Just use the MINI RX car in AMS2.

**Expected behavior**
I expected for my hardware to work like it does with the other content in AMS2

**Log files**
[SimHub.1.txt](https://github.com/user-attachments/files/18063694/SimHub.1.txt)

**Comment by Escher89** [comment]
I already fixed it. In car settings -> per car overides was the "MINI Countryman R60 RX" twice in the list of cars, but with a slightly different name --> "Mini Countryman R60 RX". I deleted the later one.

**Comment by SHWotever** [comment]
Hi !

Thanks for the report, I did enforce case bypass for the next version so It should not happen even if the case gets changed in game later.
