### ISSUE TITLE
v9.6.2 broken encoder LEDs on center 4 dials - Simagic GT Neo

### ISSUE THREAD

**Issue by viperman3** [SHWotever/SimHub#1776]
After updating to latest v9.6.2 Simhub from v9.6.1, the LEDs for relative position encoders on GT Neo wheel are not showing correct LEDs positions relative to the encoder dial.  Previous version of Simhub works correctly with same LED profiles.

**Simhub version**
v9.6.2

After reverting back to v9.6.1, the LEDs work correctly for relative encoder positions.

**Comment by SHWotever** [comment]
Hi !

Thanks for the report this is fixed for the next version.
