### ISSUE TITLE
[Feature request] Arduino Tool: POV Axis for analog sticks

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1777]
Would it be possible to have xy axis that use "0" value in the center for POV analog sticks?
-100 look left
0 look center
+100 look right
same for up and down

axis at the moment are 0 to 100 for acceleration etc.
thanks :)

**Comment by SHWotever** [comment]
Hi ! If the hardware being plugged is "plus/minus" hardware (IE Analog joystick) the value will be centered naturally by the hardwqre itself, you just need to adjust the bounds correctly.
![image](https://github.com/user-attachments/assets/af04dbad-8e99-4b0c-af4a-546200b46dbd)
