### ISSUE TITLE
Arduino Pro micrp reset

### ISSUE THREAD

**Issue by Gustavo0278** [SHWotever/SimHub#1778]
**Describe the bug**
After installing the code for the RGB matrix 8x8 and opening the test editor.  testing the flags, the white flag turns to yellowish and reset the Aurduino

**Simhub version**
9.6.2

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**
The white flag should be white

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi !

if the arduino turns completely off this looks like an hardware fault, the most common issue being a wrong wiring or soldering : https://github.com/SHWotever/SimHub/wiki/Arduino--Setup#soldering

Nicolas

**Comment by Gustavo0278** [comment]
Dear Nicolas,

Thank you very much for getting back to me. Possibly I got a bad batch of
Arduino pro micro (6 pieces), because I have tried with the Arduino nano
and everything seems to be working without problems.


Gustavo
