### ISSUE TITLE
[BUG] keyboard emulation pause key sending keycode 255, not 19

### ISSUE THREAD

**Issue by GarlicPunk** [SHWotever/SimHub#1780]
**Describe the bug**
Using Control and events - keyboard emulation, the `Pause` sends incorrect keycode `255`, not `19`.
Similarly, `Print`, `Execute`, `Printscreen` also send 255.

**Simhub version**
Version 9.6.1

**To Reproduce**
1. Setup keyboard emulation, with `pause` as outcome
2. Open an app that does something with pause is pressed, or https://www.toptal.com/developers/keycode
3. Press mapped control
4. See keycode 255 is sent, not 19

**Expected behavior**
keycode 19 is sent

**Screenshots**

Configuration:
![SimHub_-_IRacing_2024-12-17_08-47-16](https://github.com/user-attachments/assets/717f183d-cfc3-49cd-bc8f-edda90bf4e5c)
Output:
![JavaScript_Key_Code_Event_Tool__Toptal®_-_Brave_2024-12-17_08-51-40](https://github.com/user-attachments/assets/4f33377f-f618-4749-a3eb-514d3b53570f)

**Additional context**
Other keys work as expected, so far I've just found the 4 listed. As my keyboard doesn't have a `pause` key and some games don't let you remap their controls, I've made a workround: by mapping simhub to `F10`, and using [PowerToys](https://github.com/microsoft/PowerToys)(keyboard Manager) to map `F10` -> `Pause`.
It would be much nicer all inside simhub as I now have no F10 keyboard command.

Ideal output
![JavaScript_Key_Code_Event_Tool__Toptal®_-_Brave_2024-12-17_08-58-04](https://github.com/user-attachments/assets/48f9b014-52ce-4e8b-bec7-5e85b2f3fc98)

**Comment by SHWotever** [comment]
Hi ! I took a look and indeed the pause key can't be simulated at low level. I will replace it with another method for this key, but it might not be detected by some games.
