### ISSUE TITLE
Run multiple amps via usb without a soundcard for bass shakers

### ISSUE THREAD

**Issue by gbinco** [SHWotever/SimHub#1782]
So far I haven't been able to figure out how to run 4 bass shakers via 2 amps without either combining channels or buying a sound card. 

Would it be possible to run two effects profiles simultaneously? Or assign amp 1 to channels 1 & 2 and amp 2 to channels 3 & 4?

Without this feature it seems I'm stuck combining channels to run 4 shakers off 1 amp or buy a sound card. Either is not ideal. I already have a ton of wiring and devices mounted to my rig, hoping to avoid more.

Thank you for SimHub, it's awesome!

**Comment by SHWotever** [comment]
Hi ! 

You can only run one profile at once, but each effect can be routed separately to both amplifier if needed : https://github.com/SHWotever/SimHub/wiki/ShakeIt-V3-Effects-configuration#effects-configuration

Best regards
