### ISSUE TITLE
Force Feedback diy steering wheel

### ISSUE THREAD

**Issue by yoooodeeeee** [SHWotever/SimHub#1785]
Hello, i made myself a DIY Steering wheel. but i want to integrate FFB in it but its hard since im using an arduino nano and its not HID. so to counter this issue i tried using simhub's FFB. But since i have a L293D IC to control the motors there is no preset in simhub so i tried using the L298N preset but when i do so if i click test on lets say channel 1 (in shake it motors) it only spins 1 direction which is the right and when i tell it to spin the other direction wich is the left it still spins the right so how do i combat this issue. Also i made sure the wiring is correct and everything is correct.

**Comment by SHWotever** [comment]
Hi ! simhub is not made for wheel FFB, wheel FFB has to be bidirectional (left/right), and usually transmitted directly over HID from the game to the device. Simhub motors support is meant for "haptics" (vibrations of any kind) so it can't be transposed to a wheel. There are plenty of relevant projects targeting diy wheels with FFB (with the appropriate arduino board), and redoing another through Simhub would not be relevant.

**Comment by yoooodeeeee** [comment]
> Hi ! simhub is not made for wheel FFB, wheel FFB has to be bidirectional (left/right), and usually transmitted directly over HID from the game to the device. Simhub motors support is meant for "haptics" (vibrations of any kind) so it can't be transposed to a wheel. There are plenty of relevant projects targeting diy wheels with FFB (with the appropriate arduino board), and redoing another through Simhub would not be relevant.

Oh. Well that makes sense. Thank you for your response
