### ISSUE TITLE
P1000/P2000 Haptics to be used with external Pedals

### ISSUE THREAD

**Issue by daz1492** [SHWotever/SimHub#1789]
**Is your feature request related to a problem? Please describe.**
Currently there is the ability to use “only when pressed” for the p1000/p2000 haptics but when using aftermarket pedals this feature isn’t registered. 

**Describe the solution you'd like**
The ability to select axis/have a dropdown for simagic pedals or other manufacture pedals then a way to configure them.

**Describe alternatives you've considered**
Buying the correct pedals but that would be a lot more money that isn’t needed - I’ve seen a few people with this issue so would be well recieved.
 
**Additional context**

**Comment by SHWotever** [comment]
Hi ! This feature has been added in the recent versions along a deeper rework of the pXXX support : 
![image](https://github.com/user-attachments/assets/49586222-b669-45bb-a2eb-be983b725ae2)

It now includes 
- external axis support with configurable trigger level 
- per effect frequencies
- motor gain correction curves 
- multiple kits support
- direct channel allocation from the effect list ...

![image](https://github.com/user-attachments/assets/c91fbbda-8b3f-47ba-ad4b-19322bc7d454)


Just go in devices/add device to add the pedals

**Comment by daz1492** [comment]
Thank you! Sorry I missed this, thank you for the screenshots
