### ISSUE TITLE
Expose raw axis and button values as properties

### ISSUE THREAD

**Issue by redion1992** [SHWotever/SimHub#189]
As discussed a while ago (13/11, in #code) on Discord. I would like access to the value of the steering axis in order to program the LEDs accordingly. Further to that, Meekstaa requested access to the button states.

**Comment by SHWotever** [comment]
buttons are now accessible, but I won't add axis for performances reasons as it's useless for any other simhub features and i really need to keep the CPU footprint moderate .

You will find all the button status under "input status":
![image](https://user-images.githubusercontent.com/2207331/71312895-333f3800-2431-11ea-9742-40cf325ac85e.png)
