### ISSUE TITLE
Second Tile for VR enabled Titles

### ISSUE THREAD

**Issue by Ensi-Ferrum** [SHWotever/SimHub#211]
Do you think you can implement a second tile in the games for VR-enabled Titles, like Project Cars, Project Cars 2, Dirt Rally, RaceRoom Racing Experience, rFactor 2?
Maybe with the possibility to disable Nextion and / or Arduino Interface as it is not needed in VR?
Reason I ask is that not all titles have an fire and forget solution to start in VR. R3E do this with a commandline Parameter I have to change everytime I switch from VR to Desktop-mode and vice versa.

**Comment by SHWotever** [comment]
Things always comes at a time :D , it's now possible to pick VR/non vr for pcars 1/2, I don't know other games offering that option from command line.

![image](https://user-images.githubusercontent.com/2207331/64479006-1861f400-d1b1-11e9-8000-812b4f5c694b.png)
