### ISSUE TITLE
Suggestion: add a shortcut to activate/deactivate overlays

### ISSUE THREAD

**Issue by TGDSimware** [SHWotever/SimHub#231]
Overlays are a precious resources but it is very annoying to be forced to go back and forth from the game to activate/deactivate them.
A shortcut control to activate your preferred overlay would be a great add to simhub.
Even better would be a way to start your preferred overlay automatically with the game.

**Comment by OtterNas3** [comment]
Agree, a "per Game" auto-load function would be a great addition!

For the Shortcut for turning overlays on/off:
I'm pretty damn sure wotever did not implemented it to use it this way but:

Go: Additional Plugins --> More... --> Add new expression

ExpressionEditor will popup.

1. Type any name in the "Expression name" box, like "OverlaySwitchHandler"
2. put this in the "Code" box

```
// Adds actions to toggle Dashs/Overlays

//Overlay 1
//Activation Action Name
value.AddAction("ActivateDashOverlay_1", value.GetType(), (a, b) =>
{
	//Property Name
	value.AddProperty("DashOverlay_1_Active", value.GetType(), true);
});
//Deactivation Action Name
value.AddAction("DeactivateDashOverlay_1", value.GetType(), (a, b) =>
{
	//Property Name
	value.AddProperty("DashOverlay_1_Active", value.GetType(), false);
});
return 1;

```

Then you can map Joy or Keyboard input to the Actions "ActivateOverlay_One" & "DeactivateOverlay_One"
These buttons will then toggle the property
In NCalc: [PluginManager.Overlay_One_Active]
in Java: $prop('PluginManager.Overlay_One_Active')

Use these propertys in your Overlay/Dash for the Visible binding

Of course you would need to load all Overlays once, cause launching a Overlay is only possible with the "Load" button in SimHub itself.
However you could make yourself a OverLay layout and put it in Auto-Load.
Then you just use the buttons ingame to toggle the ones off you dont want.

You could go even further by saving the last used properts and save them in a file for each game, and then load em on game detection. but that would be a bit more code to insert ^^

If you need more then 1 toggle just expand the list with more entrys like:
```
// Adds actions to toggle Dashs/Overlays

//Overlay 1
//Activation Action Name
value.AddAction("ActivateDashOverlay_1", value.GetType(), (a, b) =>
{
	//Property Name
	value.AddProperty("DashOverlay_1_Active", value.GetType(), true);
});
//Deactivation Action Name
value.AddAction("DeactivateDashOverlay_1", value.GetType(), (a, b) =>
{
	//Property Name
	value.AddProperty("DashOverlay_1_Active", value.GetType(), false);
});

//Overlay 2
//Activation Action Name
value.AddAction("ActivateDashOverlay_2", value.GetType(), (a, b) =>
{
	//Property Name
	value.AddProperty("DashOverlay_2_Active", value.GetType(), true);
});
//Deactivation Action Name
value.AddAction("DeactivateDashOverlay_2", value.GetType(), (a, b) =>
{
	//Property Name
	value.AddProperty("DashOverlay_2_Active", value.GetType(), false);
});

//Overlay 3
//Activation Action Name
value.AddAction("ActivateDashOverlay_3", value.GetType(), (a, b) =>
{
	//Property Name
	value.AddProperty("DashOverlay_3_Active", value.GetType(), true);
});
//Deactivation Action Name
value.AddAction("DeactivateDashOverlay_3", value.GetType(), (a, b) =>
{
	//Property Name
	value.AddProperty("DashOverlay_3_Active", value.GetType(), false);
});
return 1;

**Comment by OtterNas3** [comment]
Hope it helps someone.
Comes in Handy also if you just need a Action for use on a Dash-Button to toggle a Property you can use for "somethin"

**Comment by rogueblue42** [comment]
Sorry but the answer doesn't make sense to me. The instruction above probably works fine for someone that codes for a living but that is not me unfortunately. Could someone post a step-by-step guide on how to toggle an overlay? Nothing in the code above looks to me like the name of an overlay that would be saved in my overlay 'library.' Thanks!

**Comment by rogueblue42** [comment]
@OtterNas3 Thanks for writing the information above but any chance you could kindly write an instruction for someone that isn't a programmer? Thank you!

**Comment by martinlanza** [comment]
Dash Studio / Settings / Overlays Display / toggle overlays visibility - assign a key or button to that function to hide/show overlays

**Comment by rogueblue42** [comment]
> 

Thanks for the quick response. The hide/show visibility is a nice feature but not exactly what I was looking for. Everytime simhub opens, I have to manually navigate to Dash Studio / Overlays / Saved Overlay Layouts / Load. I was wanting to assign a key to do this for me, and hopefully select a certain overlay, like assign button 0 to open Overlay_0 and button 1 to open Overlay_1, for example.

**Comment by martinlanza** [comment]
Create an overlay layout in Dash Studio / Overlays 
Set that Overlay to auto load

**Comment by rogueblue42** [comment]
> 

Thanks for the quick response. The hide/show visibility is a nice feature but not exactly what I was looking for. Everytime simhub opens, I have to manually navigate to Dash Studio / Overlays / Saved Overlay Layouts / Load. I was wanting to assign a key to do this for me, and hopefully select a certain overlay, like assign button 0 to open Overlay_0 and button 1 to open Overlay_1, for example.

> 

Still doesn't help unfortunately. I have different overlays for different games which is why I stopped using the autoload feature a while back. This is why I'd like to have buttons be assigned to different overlays, so that I can load them based on which game I'm loading.

**Comment by rogueblue42** [comment]
> Create an overlay layout in Dash Studio / Overlays Set that Overlay to auto load

Still doesn't help unfortunately. I have different overlays for different games which is why I stopped using the autoload feature a while back. This is why I'd like to have buttons be assigned to different overlays, so that I can load them based on which game I'm loading.
