### ISSUE TITLE
Idea - Optimal Shift point

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#251]
Kinda goes hand in hand with the redline function but for some scenarios people might like the redline to be independent of the optimal shift point say for power or fuel consumption.

Could have by default global same as redline but have user customisation options in the car settings alongside the redline. Potentially could have two as well with a user toggle button to switch between so if in a race they are after power they go to one mode or fuel saving the other mode.

**Comment by Ensi-Ferrum** [comment]
Maybe different shift-points per gear?
Revs rise much faster in 1st gear than in 5th gear.

**Comment by SHWotever** [comment]
Hi ! Unfortunately after all those years this request remained very very rare. I close it for readability purpose even if the the feature would be interesting.

On another hand per gear settings are now available which covers most needs.
