### ISSUE TITLE
iRacing New Data DRS now available.

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#262]
Hi,

Just a heads up. DRS Status is now available and can be added to the new data for iRacing.

DataCorePlugin.GameRawData.Telemetry.DRS_Status

=1 - Available
=2 - Enabled
=0 - Not available

**Comment by zegreatclan** [comment]
Thanks ! I'll look at it !

**Comment by Meekstaaa** [comment]
I've just noticed I made a mistake!

1 - coming up (not in zone but is available at next drs zone)
2 - Available now
3 - on
0 - not available

**Comment by zegreatclan** [comment]
Done ! Thanks !

**Comment by Meekstaaa** [comment]
a follow up on this. 

The Formula Renault 3.5 works slightly different.

0 - off (is off in low downforce trims)
1 - available
2 - on

**Comment by zegreatclan** [comment]
Hum ! So is it for all cars ? Or do i have to handle it specifically for this car ?

**Comment by Meekstaaa** [comment]
This is just for this car. It has a different drs setup compared to the formula one cars.

Many thanks

David Meek
Sent from my iPhone

On 10 Jan 2019, at 18:08, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Hum ! So is it for all cars ? Or do i have to handle it specifically for this car ?
