### ISSUE TITLE
A Sim Game is missing (Elite Dangerous)

### ISSUE THREAD

**Issue by DarkNachtara** [SHWotever/SimHub#287]
Hi,
i wand make an Commanders Console for Elite Dangerous
withe an Display for Ships Status and Player Status
but the game isnt in SimHub

Its an API aviable via ED Market connector 
Would be nice for having the game in SimHub

**Comment by DarkNachtara** [comment]
An proper API exist (not for all parts but it can say if the ship is in orbiat flight mode, currend heading and other stuff) 
It is utilised by an Open Scource programm called ED Market Connector

**Comment by zegreatclan** [comment]
I took a second look ,from what i see it polls data from the log files which won't be real time, I will look further however if no telemetry (yaw pitch roll speed .... are available it will be a real problem. Simhub is focused on dash/effects and if I add support without these features it would be really confusing for people and I fear to be blamed for that.

**Comment by DarkNachtara** [comment]
i think it will be an wide open API implementet with 3.4 or 4.0 
but the players of Elite Dangerous knows the problems with the telemetry and non-Real-time logs but 
maybe the guys from ED Market connector can provide some values fair enough to provide some Infomations and some functions to a Dashboard they are useful for Players
Information about the System the Player are in are very usefull for doing politics-Stuff or Players doing some engneering or pirating

**Comment by SHWotever** [comment]
Hi ! After a long thought I won't add this game as it's still not supporting proper telemetry, as most users wants realtime dash, shakeit effects and all the "realtime"package", only exposing deferred log data would be a real disappointment for any users.
