### ISSUE TITLE
Request: AI/human detector on Leaderboard, to change driverID text

### ISSUE THREAD

**Issue by navarreitor** [SHWotever/SimHub#289]
Hi Wotever

I am making a dashboard for the spectating mode, and I find the way to workaround the names issue on PS4 (I think Xbox has the same problem)

My dash show telemetry data of the player you are spectating, but If I use the driverID, it shows the variable code of gamers (100, 105, 204... the PS4 problem) instead of his/her name.

My dash uses a TEXT layer in which the text parameter takes its value from a list, correlated with raceNumer data (the number of each car)

```
var PilotoPS4=$prop('DataCorePlugin.GameRawData.PlayerParticipantData.m_driverId');

if (PilotoPS4==0) {PilotoPS4="Carlos Sainz"};
if (PilotoPS4==2) {PilotoPS4="Daniel Ricciardo"};
if (PilotoPS4==3) {PilotoPS4="Fernando Alonso"};
if (PilotoPS4==6) {PilotoPS4="Kimi Raikkonen"};
if (PilotoPS4==7) {PilotoPS4="Lewis Hamilton"};
(...)

var PilotoSGF=PilotoPS4;
//SGF is the name of my league

var NumeroCoche=$prop('DataCorePlugin.GameRawData.PlayerParticipantData.m_raceNumber');
// NumeroCoche is CarNumber in english

if(NumeroCoche==64) {PilotoSGF="navarreitor"}
else if
(NumeroCoche==75) {PilotoSGF="davroi75"}
else if
(NumeroCoche==95) {PilotoSGF="Spa_chava"}
else if
(NumeroCoche==12) {PilotoSGF="bebeabordozv"}
(....)
;

return PilotoSGF;
```

If your leaderboard could include an **option** to change the text **if the player is human**, with that workaround, we can solve on leaderboards the PS4 (Xbox) issue on F1 2018 (and I suppose other race-games on this platforms because is Sony the one who committed Codemasters to not send player names on data) 

I tried with **textbefore** on the display options, but like I suppose this don't work

**Comment by SHWotever** [comment]
Hi ! For simplicity I won't add this particular feature. If the new versions of F12019 gives proper names I will of course add support for it. But external player name list is not really viable in my opinion
