### ISSUE TITLE
Add diesel tachometer support

### ISSUE THREAD

**Issue by Lang-EVO** [SHWotever/SimHub#296]
I am a fan of China, because I use Google Translate, so some places are not very clear, I hope to forgive me. I have encountered some problems. When I modified a diesel engine instrument, I found that the instrument needs to adjust the speed to 138x1000RPM.In order to make the meter's tachometer full scale, I hope the author can add a diesel engine tachometer option to SIMHUB. thank you very much

**Comment by zegreatclan** [comment]
Hi ! do you have any specifications about the signal which should be sent ? Actually I've made some investigations about this, and while the regular tachometers are pretty well normalized (1 pulse per cylynder) I've not found any norm about diesel tachometers, from what I can see the pulses are taken from other parts of the engine (alternaltor ...) and the scale can be totally random in this case.

**Comment by Lang-EVO** [comment]
Thanks for the reply, the specific situation is this, a Dongfeng Tianlong instrument, the tachometer full scale is 3500RPM, you need to set 138*1000RPM on the SIMHUB to full scale display

**Comment by Lang-EVO** [comment]
![p81129-203315](https://user-images.githubusercontent.com/45336689/49222205-33c7f380-f416-11e8-9439-fabbdb8bf775.jpg)

**Comment by Lang-EVO** [comment]
![image](https://user-images.githubusercontent.com/45336689/49553248-d2ca7f00-f931-11e8-9bdf-a4a66d5ae20f.png)

**Comment by MorGuux** [comment]
It may be due to the way the engine rpm is taken from a diesal. On a petrol, you can use ignition pulses from the spark, to calculate the RPM. Whereas, because diesals don't use a spark, they use a hall effect or similar sensor to mechanically measure RPM. More research is needed.

**Comment by SHWotever** [comment]
Hi ! Unfortunately, tachometers are not easy enough to use, so after a very long though I won't add support for diesel where specs are totally non-standard, 
Currently clusters are the biggest source of arduino related support despite being something technically simple and I can't help about it (I can't check everyone's wiring or ensure their clusters are within the spec or not).  So for my mental sanity, I prefer to keep away from diesel and keep only gasoline support where signal spec is properly defined.
