### ISSUE TITLE
Simhub keyboard configuration

### ISSUE THREAD

**Issue by gegewrc** [SHWotever/SimHub#298]
Hi,

I would like to know if it is possible to simulate a key when a button is not pressed using the simhub keyboard configuration... It's a little bit strange but my handbrake pushes a button in "normal" situation and when I use it, it releases the button and I would like to send at this moment a signal to the game.

Thank you for your time.

**Comment by gegewrc** [comment]
Edit : I change the soldering on the "normaly close" pin and I'ts now working ... I get my simulated key. My problem is that  now, I  have only the key. I don't have the key "pressed" and it is What I'am looking for... handbrake with "F" key.  Any idea? Thanks

**Comment by zegreatclan** [comment]
Sadly the keyboard emulation plugin is not intended for such complex use cases for now (it just sends a press, when it dedect a press from input, but can't hold keys), I will look what I can do ;)

**Comment by zegreatclan** [comment]
How the controller is wired ? Is it a gamepad ?

**Comment by gegewrc** [comment]
Hi wotever. It's a micro switch with two soldering possibilities (normally closed or open) connected to an arduino and using simhub, I assign a button.
