### ISSUE TITLE
[Feature request] control x27.168

### ISSUE THREAD

**Issue by alex77k12** [SHWotever/SimHub#299]
hi, I wanted dashboard customized as shape and size but with indicator hands, then I used an arduino with SwitecX25 library to drive engines x27.168 I read PWM values from other arduino with SimHub and used the first arduino to move engines. You could implement the use of these engines directly in the program so that even those who have no space to use aftermarket gauge or like me only for personal needs should further customize. Such engines are the same as those used on car, economic, reliable instruments, you could create a gauge with a few euros. I enclose the sketch I used to make understand what I mean, sorry I wanted to modify your files to deliver to you the finished work already integrated into your work but your work is too complex for my knowledge.
Thank you for the work you do

[tacho_con_onda_quadra.zip](https://github.com/zegreatclan/SimHub/files/2617574/tacho_con_onda_quadra.zip)

**Comment by zegreatclan** [comment]
Do you have some reference wiring ? From what I see it requires intermediate controllers chips which is something i want to avoid on "standard" components. I try to keep things simple for beginners, so anything with too much solderings is really avoided (for my mental health  when it comes to help total beginners :D )

**Comment by alex77k12** [comment]
hi, no, no chips I wanted to avoid to keep everything as lean as possible for space, cost and ease of understanding.Wanting to use chips you could use L293D or better still because of microstep A4988 or similar but it was not in my intent. The engine in question has a consumption of 20mA two coils then piloted directly from arduino or even an ATtiny85 as you can see in this video used an ATtiny85 and directly connected the pins to the engine as I did using an arduino nano. At an electronic level this works because at least for arduino they are going to use the return protections of the same arduino, even if actually wanting to do a more elegant job it would be necessary to put 2 diodes per pin to protect from returns. About diodes there is a pcb just to do this that you can view here https://www.tindie.com/products/TheRengineer/analog-gauge-stepper-breakout-board/ but as you can see it is not cheap wanting to do the same work is enough 8 flyback diodes that cost very little. However this may be recommended, but I do not consider it mandatory, let's say if one knows how to weld and possesses 8 diodes better, but if he wants to connect in a brutal way the risks should not be high (I've been trying them for a long time and I have not burned anything but heated up ). In this way you can drive 3 engines with an arduino Uno, for limit number pins however 3 motors only one arduino I think that it is sufficient economic without having to complicate to go further, basically a single gauge for economic that it would have other costs. If you want to know more here you can find engine data https://s3-us-west-1.amazonaws.com/123d-circuits-datasheets/uploads%2F1392774822254-xatrnqzc91a9vn29-ddcc8d0e4ed81e9c8567ed6aee309e11%2FX27_Flyer_v1.3.pdf here you can find engine to low cost, I bought these, the only problem I've encountered so far is the slow speed with some very fast cars like F1 using as rev counter, this may also be due to reading between the two arduino, messes to convert value or other reasons, I wanted to know how to get the data that you used to drive pwm in order to drive directly and try to get more speed but obviously this was beyond my knowledge.What used by me you can have it here at 1.82 € 2 pieces including shipping then costs really bass (hands cost more than the engine) https://it.aliexpress.com/item/OEM-1-p-X27-168-Mazzo-Dello-Trans-di-Motore-Passo-A-Passo-per-GMC-Auto/32907916313.html?spm=a2g0s.9042311.0.0.27424c4dnbtih0
In my sketch we read pin 2,3,4,5 on arduino correspond to 4 direct motor pins, pin 7 used only to steal signal from another arduino with on board simhub because I did not know how to steal value in another way. Then pin 2 with 1 motor, pin 3 2 motor, pin 4 3 motor, pin 5 4 motor for motor pin number see image https://www.xsimulator.net/community/attachments/1-png.16333/
I apologize for a long and repetitive explanation but translated with a translator I am afraid I can not explain correctly how I would do it in my language. However I think easy project, feasible even by neophyte once integrated into the code, to explain it would be enough design of wires as you did in wiki for tachometer
If you want to insert it, please let me know, I'll give you everything I know, I can take pictures, videos or whatever you need to help.

Thank you for the work you have done to date

**Comment by alex77k12** [comment]
another thing if you want to link to 0 welds you can use pc audio wiring as done guy carpenter he did not accidentally cook with soldering iron, you for another reason but same result as you see from the photos also connected directly without diodes  https://guy.carpenter.id.au/gaugette/2012/04/04/making-wiring-harnesses/

**Comment by KarlSteeg** [comment]
hows this project going Alex?

**Comment by alex77k12** [comment]
for my part I stopped, I managed to make it work as mentioned above, but taking output signal from arduino with simhub and reworking it with another arduino as I explained above, but I am not able to modify simhub code to integrate it directly, for direct operation , for this reason I asked directly here if possible direct modification. The idea seemed good to me because it was cheap and once thought to be available to almost everyone

**Comment by KarlSteeg** [comment]
ok,  yes, you have a great idea.
im interested in implementing it too

**Comment by penfold42** [comment]
If I do the Arduino side, can you add support to the GUI ?

https://github.com/clearwater/SwitecX25
Supports both direct Arduino control and external driver IC.

Direct needs 4 IO per gauge
Controller needs 2+n I/O for n gauges

**Comment by SHWotever** [comment]
Hi !

I close this issue as my tests have not been convincing and I don't plan to add it to simhub.
