### ISSUE TITLE
Dashstudio - not all backgrounds not loading

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#305]
Just a heads up. Lately I've been having this issue.

On my Prosche dash it doesn't load up the background (which is made up of rectangles) to one of my widgets but it does the other one (that is the same background). Its the meter on the right in the picture.

It's quite a heavy dash but my PC can handle it (I'm only using 26% CPU with simhub crew chief and iRacing).

I'll upload the dash and a set of logs. 

Picture of issue:
https://cdn.discordapp.com/attachments/306850822518734848/520595196094971923/unknown.png

Logs:
https://cdn.discordapp.com/attachments/306850822518734848/520595260280406026/SimHub.log

Dashboard:
https://drive.google.com/open?id=146IXVhFuJ4JdyCBqtAocJdaNxh5l5xRO

**Comment by SHWotever** [comment]
Hi ! I've rewrote all the pictures loading on the web engine a few months ago and  I did not had more reports about this, do not hesitate to tell me if somehow you still have the case.
