### ISSUE TITLE
8*8 dot matrix LED or digital tube, high-end support

### ISSUE THREAD

**Issue by Lang-EVO** [SHWotever/SimHub#308]
In the ETS2, the 8*8 dot matrix of more than 10 gears cannot be displayed, but is directly extinguished. At the same time, the same problem is solved in the reverse gear position R2, and the w2812 array 8*8 dot matrix is also the same problem. Can you increase your support for higher grades?

**Comment by SHWotever** [comment]
Hi !

I missed this feature requiest but higher gears support has been added to all the fonts since a few months.

Nicolas
