### ISSUE TITLE
[Feature Request] UDP telemetry for console games

### ISSUE THREAD

**Issue by opassac** [SHWotever/SimHub#309]
Hi. I'm a console player and i've been using for some days simhub to power my BassShakers for F1 2017/2018 in PS4 with great results (planning on doing a phone holder for my Fanatec wheel base so i can also use the dashboards).
Is it possible to include the option of using UDP telemetry instead of the shared memory in other games (like the F1 games), for example, like Project Cars 1/2? This would make possible for more games in consoles to be used with SimHUB...

Thank you very much for such a piece of software. Already a donator.

**Comment by valeriomazzeo** [comment]
Same here, looking forward to use UDP for Project Cars 2 on console. Any guidance on how to write a plugin for it?

**Comment by valeriomazzeo** [comment]
🎉
