### ISSUE TITLE
Actions mappings  for each game

### ISSUE THREAD

**Issue by Son1cRS** [SHWotever/SimHub#311]
i would like to config simhub dash buttons ( a,b,c,d,next page, etc) for each game, one config for assetto, another config for raceromm........., I usually use serial stearing wheels , will it be possible? Sorry for mi english

**Comment by SHWotever** [comment]
Hi ! 

I close this request. Even if the feature would be interesting I feel like it would introduce too much complexity. I must keep a balance between possibilities and complexity.
