### ISSUE TITLE
Bug/Feature - rF2 delta in leaderboard does not use driver class

### ISSUE THREAD

**Issue by FockeOeuf** [SHWotever/SimHub#320]
Delta to best opponent does not take into account the driver class only setting. Whatever is chose, it stays on the absolute leader gap instead of getting the same class cars to display the gaps.
Although it displays the gaps for the correct cars, logic would be to calculate the gaps with the class leader and not the session/race leader.

**Comment by SHWotever** [comment]
Hi ! I close this, most combos has been made available, relative to the class, relative to the player etc ....
