### ISSUE TITLE
Sugestion - force feedback steering wheel (controller)

### ISSUE THREAD

**Issue by Tofiel** [SHWotever/SimHub#321]
SimHub gathers many solutions for sim racers. Why not to add another one - controller. The Internet is full of Arduino joysticks. Mostly it is described as basic functions: read button/axle pass to a computer as a hid interface. That is the first part of my suggestion - SimHub input device, but not just 8 buttons, my suggestion is to add 4+1 axis (clutch, brake, accelerator, handbrake, and steering wheel). 4+1 because I suspect that steering wheel itself might need a separate Arduino for force feedback.

The second part of the suggestion is calibration: I was using [MMjoy2](https://github.com/MMjoy/mmjoy_en/wiki) what was great about it I could manipulate with characteristisc of inputs i.e. set noise cut off level, alternate linear characteristic into progresive or any other shape etc.

Third part is force feedback. so far we are tied to granite devices as there is no alternative. It is called Open Simracing Wheel but is it realy open if idea is tied to propertiary PCB? I have found [this](https://www.youtube.com/watch?v=v7A_fFHfN_c) video. Can something like this be included in simhub?

**Comment by zegreatclan** [comment]
I'm afraid pushing so far despite being really interesting but it's a little out of the scope of simhub, it's made mostly for dashboards and things like mmjoy has a few years of maturation and does the job properly, so i would tend to think it's a little redundant with already available solutions.

**Comment by Tofiel** [comment]
Bass shakers are not dashboard, but it requires telemetry data, exactly like a force feedback steering wheel. It might not be a top priority but for sure it is an obvious way of progress: if there is a dash there is a button box. If there is a button box there could be different input interfaces (buttons, switches knobs) driven in an analog or digital way. Working button box is a game controller and works the same way as joystick or steering wheel. And from here it is a straight line to force feedback. You could call it redundancy but tap in one building is not redundant tap in other. Works the same but why to walk so far to drink water? So, please do not discard an idea just keep it in a bucket of things to do when it matures enough.

**Comment by SHWotever** [comment]
Hi ! I close this ticket. Unfortunately for the reasons I gave above I will never support DIY FFB steering wheel. There are many projects which already exists and do better than I would do. I try to cover a large spectrum with Simhub but I have to give it some limits. Good FFB is an "art" and clearly this feature is too demanding to be able to include it in simHub.
