### ISSUE TITLE
sugestion - shift registers (inputs)

### ISSUE THREAD

**Issue by Tofiel** [SHWotever/SimHub#322]
so far SimHub supports direct inputs and button matrix. First, one limits the number of buttons second could cause a ghost press. Why not add shift register? Example of use with Arduino code could be found on [SparkFun webpage](https://learn.sparkfun.com/tutorials/shift-registers). They discontinued [brakeout board](https://www.sparkfun.com/products/retired/11733), but with the power of web search [alternatives](https://coolcomponents.co.uk/products/sn74hc165-shift-in-breakout) can be found. With it, 256 buttons would be a limit.

**Comment by zegreatclan** [comment]
Currently I try to stick with basic and obvious hardwares for beginners simplicity. but this breakout board seems interresting ;)

**Comment by Tofiel** [comment]
There are also breakout boards for output shift registers i.e. driving 8 LEDs each, but the question is does sim-racers need those. What I can see is to combine both together that single Arduino could read buttons at the same time it could provide backlight for them. It opens a path to more advanced functionality like a toggle. A momentary button could be defined as a momentary button, or as a toggle switch, and when it is pressed LED will lit as a mark for a toggle. 
   I can see a requirement for the opposite situation where the toggle switch generates a single button press on change of state. The best example is an ignition key. Different games define that function in a different way: on button press, on button release, sometimes the same button turns off engine sometimes another turn engine off. Project cars have two buttons for that one ignition turns on power second start engine.

**Comment by KarlSteeg** [comment]
it would be much much easier for the average me(user)
if more support was added for the Adafruit 16x8 LED Matrix Driver Backpack - HT16K33 Breakout ( https://www.adafruit.com/product/1427 ).
it does all that for you leds and buttons.
i was able to get it to control leds and 2x7-segment or 2x16 segment alphanumeric led.
in Adruine IDE,  but not simhub.  if i can do that, the average user can, and the breakout isnot so expensive(my 2x16seg cant me more than the HT16k)

i was trying to get it working for ETS/ATS where trucks have up to 24 gears. (R1 and R2 aswel)

**Comment by penfold42** [comment]
+1 on this too. 74hct165 support would be great.

I'm likely embarking on a new button box but I want to use a pro micro 32u4 for gamepad support.

With a large collection of buttons and toggle switches, matrix support wont be that useful.
if you add a couple of rotary encoders, its even harder to fit it all in.

I can help on the arduino side if thats useful to you

**Comment by SHWotever** [comment]
Hi !

I close this request, I totally agree with the fact that it would expand the responsibilities, but on another side it involves lot of soldering and possible failure. At this point of complexity i prefer to leave this to more dedicated gamepad solutions , simhub's goal about input was to have something simple to add to display devices. And this further to this "simple" philosophy.
