### ISSUE TITLE
Dash Studio Not resetting back to Idle screen

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#329]
Hi!

Just noticed recently when exiting a game Dash Studio isn't going back to Idle screen. It goes black. If you press an action button it goes back ok.

This happens on iRacing but assume it's a global issue.

Cheers :)

**Comment by zegreatclan** [comment]
Hi ! Could you say me which dash you used and which mode (web or desktop) so I can investigate ? I've tested both modes with and I have not encountered it, so it could be bound to the dash ?

**Comment by Meekstaaa** [comment]
Hey. I had it on my new BMW M8 one. I didn't have it happen just now with my HPD dashboard which is strange.

Here's a standalone link:
https://drive.google.com/open?id=1EAWP0sc3vTxAW_OKRgL7r3LUX9c_iCUb

________________________________

**Comment by Meekstaaa** [comment]
Oh also, it was on desktop mode.

________________________________

**Comment by navarreitor** [comment]
Same with my new dash

**Comment by SHWotever** [comment]
Duplicated by #526
