### ISSUE TITLE
Enable WS2812 GRBW support

### ISSUE THREAD

**Issue by Gianotto** [SHWotever/SimHub#331]
There is a variant for WS2812 that has dedicated white led on it, RGBW.
Currently, the library Adafruit_Neopixel has support to it, so I would like to request to enable support on SimHub arduino setup tool by placing this item as a selection option in WS2812B encoding.

**Comment by SHWotever** [comment]
Hi ! Sadly I never encountered other requests about RGBW so I don't think adding another option which could lead to confusion is a good idea. Until I get new requests about it I prefer not to implement it.
