### ISSUE TITLE
Opacity on border elements different between windowed/in browser

### ISSUE THREAD

**Issue by sjdawson** [SHWotever/SimHub#333]
When toying with some JS that would make for a fading "blink", I stumbled across the following difference between the dash running windowed, and in the browser:

(Left is dash running windowed mode, right is in browser, browser shows the results I'd expect to see)
![2019-03-26_12-47-10](https://user-images.githubusercontent.com/1701603/54998441-0eaf5000-4fc6-11e9-8f0f-f27ce29b2a77.gif)

Doesn't look like opacity is applied correctly to `border` elements in windowed mode.

[Testing.zip](https://github.com/zegreatclan/SimHub/files/3008215/Testing.zip) Rename from .zip to .simhubdash, it's a dashboard with a single idle screen and one element that should repeat the problem. :+1:

**Comment by SHWotever** [comment]
Fixed in latest beta ;) Sorry for the infinite delay about it ;)
