### ISSUE TITLE
Shake It - Impacts

### ISSUE THREAD

**Issue by iLLiac4** [SHWotever/SimHub#347]
Is it possible to add Impacts as an option to simulate in Shake It?

TNX

**Comment by KarlSteeg** [comment]
hi

can i plus 1 this request.
it would be handy to add some ffb for hitting something, and a constant vibe motor on, doesnt do it ,
the motor will have to go from 0% to 100% then drop off at a configurable rate.  if possible with a stepper(eg 150 steps then stop)

**Comment by SHWotever** [comment]
Hi ! I'm making a bit of cleaning, road impacts are now supported since june, about "other players" impact, sadly I have no data about it.
