### ISSUE TITLE
Add formula binding buttons for auto repeat- Dashstudio

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#348]
Hi! You'll probably curse this day as I finally made a github account today ;) 

In dashstudio, could you please add some formula binding buttons for auto repeat values (the 2 offsets and repetitions number)?
I could use one to auto adjust the number of rows in a leaderboard.
I can also imagine a use cases for the repetition offset, so a list could stay the same size, no matter the number of rows.

**Comment by zegreatclan** [comment]
Hi ! I'm afraid this will be really complex to spread accross the whole platform, the difficulty will come from the web engine which requires to know in advance any components running, and making this dynamic would not be compatible with that. I keep the ticket as I think It would be interesting still, if somehow I find a workaround I will try to add it.

**Comment by Romainrob** [comment]
Hi! I (somewhat) understand the limitation. Thanks for your answer.

**Comment by SHWotever** [comment]
I took another look, really i won,'t be possible to add it without a hardcore mess in both engines (desktop and html)
