### ISSUE TITLE
Window snapping a replay = crash

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#352]
Hi, I noticed, when I drag a replay windows near the top of the screen and it snaps to maximize, the windows flickers like crazy until SimHub crashes. FYI I'm using a triple screen setup (nvidia surround).
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3254545/SimHub.log)

**Comment by Romainrob** [comment]
Hi! This morning I snapped a replay again by mistake and the crash happened again. So I did a little digging.  Here are my findings. Enjoy ;)

It is effectively related to Nvidia surround.

Disabling surround solves the issue, even with the desktop spanned over 3 screens. 

Actually, in surround mode every SimHub window snapping causes a 1 sec flicker. I thought this was normal as I'm almost always in surround mode. Thankfully, only the replay window causes the crash.

During the flickering, it looks like the window keep resizing really fast.

The weird thing is if, with surround left enabled,
1. I set my resolution to 1920*1080, starts SimHub, load a replay and snap it = no flickering and no crash
2. Then leaving the replay window open, I set my resolution to 5760*1080 and snap the replay window again = flickers 1 sec and no crash
3. Then close and reopen the replay (without closing SimHub), snap it= crazy flickering until it crashes

I'm not sure what to make of that. Maybe that mean something wrong occurs while loading the replay in surround mode and not at the moment of snapping it?

Win10 1903 - Simhub 6.8.5 - Nvidia 436.30
[SimHub.log.txt](https://github.com/SHWotever/SimHub/files/3615000/SimHub.log.txt)

**Comment by SHWotever** [comment]
Hi! Actually I've not been able to reproduce it yet (at least the crash), I've investigated it as I know well this behavior related to surround, pretty much all WPF apps suffer from this crazy blinking for 1s in surround mode (visual studio does it too) Concerning the replay window crash I think it's related to the autosizing enabled to allow the replay picture to be shown or hidden which may make things even worse, 

I will try using your procedure as it may help to reproduce it, at worse I may try to simply remove it and add a placeholder with "no preview" text so it won't feel dumbly sized when replay does not contains screenshots, Surround is pretty common in sim racing and such crash can be really annoying.

**Comment by Romainrob** [comment]
One more reason to love surround...
Just to be complete. My replays include monitor screenshots of triple screen gameplay. In case the ratio of the screenshots matters.
Let me know if I can do any extra test to help.

**Comment by SHWotever** [comment]
Hello ! J'ai supprimé l'"autosize" qui provoquait le crash dans le dernière update ;)

**Comment by Romainrob** [comment]
Yes! Ça ne crash plus :)
Merci et bonne soirée!
