### ISSUE TITLE
[Feature Request] Add support for new damage fields in ETS2

### ISSUE THREAD

**Issue by vdumitrescu** [SHWotever/SimHub#356]
ETS2 v1.35 has been released, and it includes the [new API v1.10](https://modding.scssoft.com/wiki/Documentation/Engine/SDK/Telemetry).

Since the introduction of the player-owned trailers, the damage of the trailer is kept separately from the damage to the cargo. This is very important, because the trailer damage can be repaired at the service station, and only the cargo damage affects the rewards at the end of the trip.

The new API exposes the separate damage values on the following data channels:
`trailer.cargo.damage`
`trailer.wear.wheels`

The old channel `trailer.wear.chassis` still exists.

**Comment by danfeliix** [comment]
@SHWotever  Thanks I hope you can get this translation of the cities with this new API. Another thing I wanted to know is how to solve it: In the ETS2 game shows 199km that I have to reach my destination, SimHub shows different. There is no way I put in the display is many numbers in length, even if I limit the amount of character to 3 for example not sure why every trip that change the kilometregem example to 1000k will disturb
![Captura de Tela (70)](https://user-images.githubusercontent.com/54558657/63898753-9dd6ee80-c9d0-11e9-902c-00676f402588.png)

![2019 08 28-19 29](https://user-images.githubusercontent.com/54558657/63898805-d37bd780-c9d0-11e9-8900-894d8a749bb6.png)

**Comment by vdumitrescu** [comment]
@SHWotever @danfeliix
I'm afraid the city names currently available are the only ones exposed by the API, even in the latest version.

**Comment by sjdawson** [comment]
Is there a list of the city names in both original and translated versions? This is something I could add to my [TruckSimulatorPlugin](https://github.com/sjdawson/TruckSimulatorPlugin/) for SimHub. :+1:

**Comment by sjdawson** [comment]
@danfeliix I've been working away behind the scenes and have just released [v1.1.8 of the TruckSimulatorPlugin for SimHub](https://github.com/sjdawson/TruckSimulatorPlugin/releases/tag/1.1.8). It adds localisation for city names and should do what you're looking for, in absence of SCS adding it to the output data.

**Comment by danfeliix** [comment]
> @danfeliix I've been working away behind the scenes and have just released [v1.1.8 of the TruckSimulatorPlugin for SimHub](https://github.com/sjdawson/TruckSimulatorPlugin/releases/tag/1.1.8). It adds localisation for city names and should do what you're looking for, in absence of SCS adding it to the output data.
Thank you friend.  What place to put the plugin ??

**Comment by danfeliix** [comment]
@sjdawson Thank you friend.  What place to put the plugin ??

**Comment by sjdawson** [comment]
If you download the 1.1.8 installer, it'll guide you through it. 👍

**Comment by danfeliix** [comment]
@sjdawson Friend worked, for the same test I did with Russian cities like St. Petersburg. Most stayed with English names which is already much better. I hope one day to learn and leave everything in Brazilian Portuguese

**Comment by danfeliix** [comment]
@sjdawson Friend worked, for the same test I did with Russian cities like St. Petersburg. Most stayed with English names which is already much better. I hope one day to learn and leave everything in Brazilian Portuguese
![WhatsApp Image 2020-03-19 at 22 02 28](https://user-images.githubusercontent.com/54558657/77128092-aa369d80-6a2d-11ea-9134-22d82e03ed11.jpeg)

**Comment by sjdawson** [comment]
Excellent, good to see it working fine for your needs! :)

**Comment by danfeliix** [comment]
@sjdawson 

Friend doing more testing some cities are going blank and the names do not appear in the program or on the LCD
![Captura de Tela (195)](https://user-images.githubusercontent.com/54558657/77367099-2f74c780-6d38-11ea-843f-36410b66be55.png)
![2020 03 23-18 53](https://user-images.githubusercontent.com/54558657/77367120-38fe2f80-6d38-11ea-8eca-e31a1e0ead82.png)

**Comment by sjdawson** [comment]
@danfelix are you using any map mods? As at the moment, I only have the localisations from the base game and it's DLC. I'll have to work on a way of getting the localisations from the mods.

**Comment by danfeliix** [comment]
@sjdawson My friend, yes I use some map mods. (RusMap, Promods) I realized that many cities in Russia had this problem. I hope your correction, thank you very much is doing a great job

**Comment by danfeliix** [comment]
@sjdawson Friend I forgot to mention this problem in the translation is occurring on maps that have names with Cyrillic characters, which in this case is used in the Russian alphabet.  Because I tested other maps like EAA and ProMods and I had no problems

**Comment by danfeliix** [comment]
@sjdawson I was testing and I realized that other maps work well, as in the Promods Map that has cities like Teruel, Pafos. The problem is with the Russian names, which have a Cyrillic or Greek alphabet.

**Comment by sjdawson** [comment]
Thanks @danfeliix, I'll get hold of those map mods and do some testing.

**Comment by danfeliix** [comment]
@sjdawson What a good friend!  Can a question be translated into Brazilian Portuguese?  In the same way that the game translates the names of cities.  Example: the city of Prague that shows Praha on SimHub.

**Comment by sjdawson** [comment]
Should be able to, but I might need some translations double checking! 👍

**Comment by danfeliix** [comment]
@SHWotever @vdumitrescu Friends with the new API 1.11 that works in the version of the game 1.36, is it possible to translate city names? It just lacks that to become perfect on my panel for ETS2 games. In the standard SimHub DataCoreplugin it is good that even different Maps like MAP EAA show the names normally. At the base of the Game and maps like Promods that lack the translation. Our friend  @sjdawson created a plugin that makes the name translation work, but it only works with the game's Dlc and base.

**Comment by danfeliix** [comment]
> Deveria poder, mas talvez eu precise de algumas traduções, verificação dupla! 👍

news? @sjdawson ?

**Comment by sjdawson** [comment]
Hey @danfeliix!

Sorry I haven't managed to get back around to this. Things got busy when the COVID train started running, so haven't had any time to do SimHub related things.

I'll see what's in the new API. 👍 

And then see what I can do with other place names!

**Comment by danfeliix** [comment]
> Oi !
> 
> Receio que seja a forma como os nomes das cidades são fornecidos pelo SDK por enquanto,
> talvez esteja traduzido no SDK mais recente, ainda não verifiquei, já tenho em minha lista de tarefas para fazer a atualização (ver [# 356](https://github.com/SHWotever/SimHub/issues/356) ), talvez forneça a versão traduzida dos nomes das cidades.
> 
> Eu fecho este como duplicado, você pode assistir a solicitação futura [# 356](https://github.com/SHWotever/SimHub/issues/356) para saber quando ela será implementada.
> 
> Nicolas

friend @SHWotever  with your great update on simhub already is there any possibility that the names of the cities of the ETS can be translated and display correctly on the LCD panel?

**Comment by danfeliix** [comment]
Hello, any news with the new updates? @sjdawson @SHWotever
