### ISSUE TITLE
rF2 not picked up

### ISSUE THREAD

**Issue by KarlSteeg** [SHWotever/SimHub#360]
HI All.

I have a problem thats started Saturday morning.(22.06.2019)
booted up PC to do race practice.
Simhub would not pick up rF2.
So i tested AC, at first AC worked, but after a few reboots,( i thought a reboot might make it work) AC stopped working aswel.
the 'Dash Studio" screens(7in HDMI) show "waiting for sim"

i had to un-install simhub, reboot PC, install simhub, patch plugin.. then it worked.
next day SimHub stopped picking up rF2.
now rF2 doesnt work again... says "waiting for sim"

any ideas?? it worked flawlessly for many months( i mainly race in rF2)
only thing new that i could think of,, is i made a "dash Studio" screen with Pedal outputs so i can test hardware,, that works perfectly

[KARLSimHubLogs.zip](https://github.com/zegreatclan/SimHub/files/3322744/KARLSimHubLogs.zip)

 

also the games screen, where you can select a game to play,or patch plugin was all greyed out, i couldnt select any games.( first and only time ive seen that)

tested today again(24.06.2019) loaded AC....  Worked.  loaded rF2... not detected.... loaded PCars2... Worked.

FYI..   do not worry about the snip errors, i was playing around with it last night(23.06.2019) but snip wont run properly.

karl

**Comment by KarlSteeg** [comment]
no ideas yet??

**Comment by zegreatclan** [comment]
hi ! I've took a look at your log but I could not see anything explaining it.
Could you check the plugin is correctly installed and active ?
to check that you can see it in solo mode in settings / plugins and ensure the plugin is active : 
![image](https://user-images.githubusercontent.com/2207331/60400276-c2018500-9b71-11e9-8a0f-c2cdcc5ab926.png)


NB : I noticed by the way that your windows is outdated, you are running windows 10 v10586 which is outdated and some features won't work at all (not supported anymore by microsoft development tools). for instance mobile dashboards won't work. I don't think it will prevent game connection in this specific case, but it will probably gives you troubles in the future (not specifically for simhub but for any apps keeping development tools up-to-date like I try to do)

**Comment by KarlSteeg** [comment]
Hi.

thank you for looking into it.

turns out its the plugin from Crew Chief.
i havent used it in a while and not updated it.
i done so today and simhub now picks up rF2.
i hope it works fine without crewchief as i plan on uninstalling it.

thank you again
Karl

**Comment by KarlSteeg** [comment]
as described above.
will the lack of windows update stop my TM1638(single color) from showing rpm on the leds??
i also cannot get my ws2812b from showing rpm or session flags

**Comment by zegreatclan** [comment]
Hi ! I don't think it's related, could you check your leds layout settings ? since you seems to have a global issue with leds I would think about wrong leds settings, or maybe an empty layout being active.

Nicolas

**Comment by KarlSteeg** [comment]
Hi.

Thank you Nicolas.
You might be right.
ive just run around in circles trying to fix it, im no longer sure how or where to look.
i will keep at it
