### ISSUE TITLE
iRacing: Delta/Gap times empty in Leaderboard

### ISSUE THREAD

**Issue by hieblmedia** [SHWotever/SimHub#366]
Hello,
looks like delta and gap times are not calculated in the leaderboard.
Replay1 (race starting): https://drive.google.com/file/d/1tGzcCbgh5zwD4OewBUwxgBFBgGJAoAaP/view?usp=sharing
Replay2: https://drive.google.com/file/d/1XIREYYx6RmRmhG5FSZ8_WRxjJJXNVA1B/view?usp=sharing

**Comment by Wergilius** [comment]
I have the same issue, I think when running multiclass (or just beeing slow) and you not on leaders lap the following stops working:

drivergaptoleader(index to driver not on leaders lap) -> returns null
drivergaptoplayer(any index) -> returns null

still works:
drivergaptoleader(index off driver on leaders lap)
drivername(any index)
drivercarname(any index)

**Comment by SHWotever** [comment]
Hi ! I close this as this has been reworked a lot since, there is not known case. (except rf2 which stops sending the data and only sends laps)
To watch all the data a debug tool is also now included which helps to understand all the data : http://127.0.0.1:8888/diaglb.html
