### ISSUE TITLE
Gauges

### ISSUE THREAD

**Issue by cjeje84** [SHWotever/SimHub#367]
Hello I install the sketch on my arduino but on euro truck 2 when I'm not full of fuel the fuel gauge works but when I full my full gas gauge goes up and down when it arrives thank you in advance for your help

BMW E36 Cluster

**Comment by zegreatclan** [comment]
Hi ! It looks like you may have a calibration issue ? 
You can read some default settings for gauges here : https://github.com/zegreatclan/SimHub/wiki/BMW-E36-Cluster-Setup#suggested-calibration-values-for-bmw-e36-cluster-
Make sure not to use 255 as maximum output value but ensure to adjust it properly according to your gauge : 
![image](https://user-images.githubusercontent.com/2207331/60400331-9df27380-9b72-11e9-8f84-959905d08cd8.png)

Nicolas

**Comment by cjeje84** [comment]
I have the same settings as you give me

**Comment by Bri4nFr4nk** [comment]
did you manage to fix it?
my fuel gauge is also acting weirdly

**Comment by dannyatyeo** [comment]
what settings have people used for the speedo i cant seem to get mine working but i have got RPM working perfect.
