### ISSUE TITLE
iRacing - Incomplete session string

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#368]
Hi!
I've noticed we can't access all the data iRacing output via the Session String.

I'm talking about what's described page 13 :
[telemetry_11_23_15.pdf](https://github.com/zegreatclan/SimHub/files/3344581/telemetry_11_23_15.pdf)

The properties about the drivers ("DataCorePlugin.GameRawData.SessionData.DriverInfo.") and sessions (DataCorePlugin.GameRawData.SessionData.SessionInfo.) only exist for "drivers01" and "session01" at the moment.

Can more/all of this data made available please?
This is a gold mine, and my pickaxe is ready :)

**Comment by zegreatclan** [comment]
Hi ! I will look what I can do, I admit this was clearly a choice of restricting it to avoid drowning the list under a thousands of data, I think accessing this is really reaching the limits of the "key -> value" model

**Comment by Romainrob** [comment]
Hi! Thanks for the answer.
I understand the number of properties would increase quite significantly. Plus, some of them would probably not see much or any use, and some other are already available in another form. Yet there is some good stuff in there that could be useful for leaderboard stuff. 
For my relative leaderboard, I was specifically looking for safety rating, licence color, car model, car class and class color. That the ones I remember of the top of my head. I can’t check right now and for the next few days.
I’m thinking, maybe adding a few dedicated fonctions would do the trick for these. Just like the existing driver’s irating fonction.

**Comment by Romainrob** [comment]
Hi again! I'm back and just had another look.
The functions for car model and car class already exists: drivercarname(raceposition) and drivercarclass(raceposition).

This is what I'm missing : 
1. driveriracingclasscolor(raceposition) as the "CarClassColor" can change for a given class depending on the serie.
2. driveriracingsafetyrating(raceposition) returning the safety rating ("LicString") of the driver . "LicColor" would be nice too but can be derived from "LicString" as this is static.

So a couple of new functions would do the trick, for my use case at least. 

On a side note, I noticed all of these values are in double;  "CompetingDriversXX" and "DriversXX".  I don't know sure what the difference is.

	DataCorePlugin.GameRawData.SessionData.DriverInfo.CompetingDrivers01.CarClassColor
	DataCorePlugin.GameRawData.SessionData.DriverInfo.CompetingDrivers01.LicString
	DataCorePlugin.GameRawData.SessionData.DriverInfo.CompetingDrivers01.LicColor
		
	DataCorePlugin.GameRawData.SessionData.DriverInfo.Drivers01.CarClassColor
	DataCorePlugin.GameRawData.SessionData.DriverInfo.Drivers01.LicColor
	DataCorePlugin.GameRawData.SessionData.DriverInfo.Drivers01.LicString

**Comment by Romainrob** [comment]
Bonjour!
I've been messing with the relative leaderboard today and ran into another (small) issue. Not iRacing specific this time. At least I don't think so. I explained it here:
https://discordapp.com/channels/299259397060689920/306850822518734848/616286824381284383

Would you consider adding the car number to the persistant tracker please?

Regarding my previous request. This got me thinking, having the SR and class color added to the tracker rather than dedicated functions could do the trick too.

Let me know what you think.
Bonne fin de journée!

**Comment by Romainrob** [comment]
Hi! 
Taking baby-steps, and struggling at each one of them, I got a plugin working to feed my relative leaderboard. I can't believe I'm writing these word... This is so cool! :)
It's still needs a bit more testing, but it's definitely getting there.
Do as you please with this ticket and thanks again for helping me getting started!

![image](https://user-images.githubusercontent.com/50543913/66499361-ffa27200-eabf-11e9-8985-46c54a62625c.png)
![image](https://user-images.githubusercontent.com/50543913/66499393-0e892480-eac0-11e9-93c2-813b66b8c7bf.png)

**Comment by jasonbice** [comment]
@Romainrob - How did you get the Safety Rating and License Colors for the other positions?  I'm not seeing these properties for anyone other than Driver01.  Thanks!

**Comment by Romainrob** [comment]
@jasonbice Hi. I made a plugin to add some properties. I'll share it will in this dash next update when it's ready: https://www.racedepartment.com/downloads/universal-simhub-dash-for-iracing.25452/

**Comment by Romainrob** [comment]
Hi. Going over some of my old tickets.
With the community help and yours, I managed to get what I wanted with a plugin.
Feel free to close this ticket.

**Comment by SHWotever** [comment]
Thanks !
