### ISSUE TITLE
[Feature Request] Return ShakeIt Plugin For Dash Studio

### ISSUE THREAD

**Issue by bobsmash** [SHWotever/SimHub#376]
Before the 8.0 update the ShakeIt data was available in Dash Studio for projects. Can it be added back? I found it useful in simulating wheel lock/slide LEDs on my dashes.

**Comment by zegreatclan** [comment]
Hi ! That's a bit challenging as effects are not a "fixedlist" anymore there can be many effects of each kind.
I need to think about what I could do, I admit i'm a bit struggling to find a smart way to expose those values considering the huge structural change exposed earlier

**Comment by SHWotever** [comment]
Released with simhub 6.8.3 ;)
