### ISSUE TITLE
SimHub Notification Upgrade available

### ISSUE THREAD

**Issue by ForcePower76** [SHWotever/SimHub#377]
Hello, since SimHub was no more downloadable from racedepartment I not recieve notification when update version is available, is it normal?

**Comment by zegreatclan** [comment]
Hi !
Indeed I did not had time to replace the current system. I wanted to make something more fancy with a little change log etc .. Still thinking about the best way to do it ;) But getting it back is planned for sure !

Nicolas

**Comment by ForcePower76** [comment]
Thanks for super fast replay, ok, I thought was a issue on my software, thanks for all, I'll wait when notification will be available in next versions whe them will be ready for working. The idea about change log is great and useful :)

**Comment by SHWotever** [comment]
Released with simhub 6.8.3 ;)
