### ISSUE TITLE
ETS2/ATS gear indicator bug

### ISSUE THREAD

**Issue by alex-bluetrain** [SHWotever/SimHub#378]
Euro Truck Simulator 2 and American Truck Simulator plugins have an issue:

They don't report gear shift until the truck moves, if you are fully standing still, as in a red light, and you change gears, the gear change will only be shown when you press the gas pedal and start moving.

this is not a limitation of SCS's Telemetry SDK, but something wrong on the simhub's ETS/ATS plugin implementation.

if the source code of such plugin is available, I'd be glad to fix it, or if you need more feedback from the issue, I'd be more than glad to provide it.

just let me know

**Comment by zegreatclan** [comment]
Hi ! Sorry for the late reply, holidays and catching up with everything took me more time than I expected, indeed I see that the telemetry channel I was using was  "truck.engine.gear" and it was only changing when moving as you described, I changed for   "truck.displayed.gear" which is real time for the next version.

Wotever.

**Comment by SHWotever** [comment]
Fix released with 6.8.3 ;)
