### ISSUE TITLE
ShakeIt - Resetting sound output mapping = Freeze

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#385]
Hi! It's bug report time! Welcome back ;)

I was curious to see it there was on confirmation message on the reset feature of the ShakeIt sound output mapping, so i pressed the button.

![image](https://user-images.githubusercontent.com/50543913/62260737-51b97e00-b413-11e9-8d51-d76c1cfcd536.png)

When i do that SimHub just hangs and won't recover.

[Logs.zip](https://github.com/zegreatclan/SimHub/files/3454602/Logs.zip)

**Comment by Romainrob** [comment]
Hi!
I finally updated Win10 to 1903.
As usual it messed up my audio devices. So I lost all my ShakeIt mapping ;(
When trying to import my previously saved .sichannels files, SimHub also freezes.
[Logs.zip](https://github.com/zegreatclan/SimHub/files/3512211/Logs.zip)

**Comment by Romainrob** [comment]
Hi!
The issue seems to be fixed on the 6.08.3b2.
Thanks!

**Comment by SHWotever** [comment]
Ah nice ! I admit i've not been able to reproduce it, and I hoped I fixed it already :D
