### ISSUE TITLE
2004 LCD(I2C) causing arduino refresh 

### ISSUE THREAD

**Issue by KarlSteeg** [SHWotever/SimHub#386]
hey all.
im back.

for the past while i would get it that the LCD restarts, shows welcome screen and continues showing what it was,   then a random time later, would do the same again   and again   and again.
i thought it was the arduino.  changed between 3 nanos and 2 unos. problem persisted.
now im busy setting up a dash for a friend and making many test setup sketches.
if found that the arduino only reboots/resets if i have an I2C 2004 LCD attached(only have I2C)
i have tried 2 other brand new LCDs and it happens with all of them.
ive noticed that the screen doesn't even need to be attached.  as soon as the Lib is active, it happens.

any idea how to fix this??

Karl

**Comment by zegreatclan** [comment]
Hi ! 

Do you have the related log files ?

I did some tests and it never disconnected (I displayed some random data to make sure the display will refresh every single frame)

**Comment by KarlSteeg** [comment]
i have them Disconnected right now.
but will set it up on the weekend, send the log on sunday.
you'll see i'm still using ver6,60 beta as that's the most stable.  its alot worse if i use another version

**Comment by zegreatclan** [comment]
I would be interested for it to be running on the latest version and sketch. Since if there is an issue I can only work based on the latest versions. 6.6 has been released a long time ago and lot of things have changed since and logs would not be relevant.

**Comment by KarlSteeg** [comment]
ok, that will have to wait until next week then.
have 2 big races this weekend, and cannot risk something going wrong.
then monday ill load new version and test
(eg, back and forth of versions has stopped simhub starting on its own and stopped auto game detection, so ill only fiddle after the races)

thank you

**Comment by zegreatclan** [comment]
Ah ! I remember having seen in the log you were running a deprecated windows 10 version which will probably cause unwanted fails. Have you upgraded to a Microsoft supported version since ?

**Comment by KarlSteeg** [comment]
no,  not yet.  its a mission for me to do so. i have a data cap and last attempt ended with me re instaling windows

**Comment by KarlSteeg** [comment]
hi hi.
for the past week, used v6,6 with and without arduino and LCD.
heres the logs for incase.

now im busy installing the latest version of simhub(downloaded 13.8.2019)
i have updated my win10,  now raceroom data is corrupted,
will send new logs on the weekend

Karl
[LOGS v6.6 folder Karl Steeg.zip](https://github.com/zegreatclan/SimHub/files/3502751/LOGS.v6.6.folder.Karl.Steeg.zip)

**Comment by KarlSteeg** [comment]
howdy


heres some logs.
windows was updated and simhub v6.8.2.

was about to shut down pc when i noticed the ""hello world""
error is in the last log.

[SimHub v6.8.2 Logs lcd resets.zip](https://github.com/zegreatclan/SimHub/files/3513676/SimHub.v6.8.2.Logs.lcd.resets.zip)

**Comment by SHWotever** [comment]
Fix released with 6.8.3 ;)

**Comment by KarlSteeg** [comment]
many many thanks.
i really appreciate it.  
that was driving me crazy, 
i was holding off running 2x lcds on 2x nanos on my new dashboard.
now i can proceed.
many thanks, you my hero.
k
