### ISSUE TITLE
[Feature Request] hwinfo64 plugin to read shared memory

### ISSUE THREAD

**Issue by WibbersGIT** [SHWotever/SimHub#390]
The afterburner plugin works well but is limited on what it can read. For example, I just upgrade to a Ryzen CPU and neither the Systeminfo Plugin or Afterburner are able to read the temperature from the the CPU.

Hwinfo64 is much more thorough in what it can monitor and is updated much more frequently, and has shared memory support. Would it be possible to create a plugin to read system data from the Hwinfo64 shared memory?

https://www.hwinfo.com/

**Comment by SHWotever** [comment]
I'm afraid the SDK is not publicly available, but I've added support for aida64, it's well maintained (but paid). It will be released with next version.
