### ISSUE TITLE
export simhub settings

### ISSUE THREAD

**Issue by KarlSteeg** [SHWotever/SimHub#392]
hi.

is it posible to be able to export simhub settings and screen setups and then load them again.

eg if i need to reinstall windows, could i back it up, reload all and import again.

or do a setup for my friend whos technically challenged, then mail him the exported setup to install on his rig?

this will be very handy.

Karl(the pain in your neck)

**Comment by zegreatclan** [comment]
Hi ! You can backup the whole pluginsdata folder inside simhub install folder, 
It contains all plugins settings (including arduino ...) 
C:\Program Files (x86)\SimHub\PluginsData
The arduino settings more particularly are stored inside C:\Program Files (x86)\SimHub\PluginsData\Common\SerialDashPlugin.json

**Comment by KarlSteeg** [comment]
ok cool,  doing that now.

**Comment by KarlSteeg** [comment]
need to setup a dash for a friend and not loose mine nor have irq clashes
