### ISSUE TITLE
Improve / Find an alternative fallback for wheel slip on RF2 GT3s and endurance pack.

### ISSUE THREAD

**Issue by bjgrech** [SHWotever/SimHub#394]
I'm looking for help setting up the Wheel Slip feature of SimHub ShakeIt Bass Shakers in rFactor 2. I've gotten the feature to work quite well for the USF2000 car in the sim. That is, I get feedback either through the front or rear transducers when either the front or rear wheels begin to skid, respectively. This feedback also increases as the skid becomes more severe. However, the feedback I get for the GT3 (i.e. the cars purchased from the rFactor 2 Store) and many other cars in the sim is very poor when compared to the USF2000 car. I've tried different values for the Gamma Factors, Thresholds, Minimum forces, Input Grains, Base frequencies, High effect frequencies, and overall volumes in the Wheel Slip feature; and different tire volumes in rfactor 2.  Does anyone know why I can't get this feature to work properly with all cars? 

I'm using the latest version of SimHub (version 6.8.2); four AuraSound AST-2B-4 Pro Bass Shakers and have the ShakeIt Bass Shakers set to 4 channels; and the front and rear 3.5 mm jacks from the onboard Realtek high definition audio chip on a desktop PC.

**Comment by zegreatclan** [comment]
Hi ! 
Sadly on RF2 the recent officials mods (including endurance pack, and lot of GT3) does not gives anymore the wheel slip info so I have to interpolate it using wheel speed which is way less accurate as you have noticed, We have less directional and detailed feedback in this case as it is based on the wheel speed difference. I will take a second look to see if I can improve it more, but considering the data I have under hand from the game I'm clearly reaching the limits. Hopefully one day RF2 will give back the data for these cars.

**Comment by bjgrech** [comment]
Thanks for the help.
That helps to explain the issue that I’m having. When I'm driving the official GT3s, wheel skid during braking and accelerating in a straight line isn't felt through the transducers, but is somewhat felt during cornering.

I'll send a message to Studio-397 about this issue and I would like to encourage other RF2 users to also send similar messages.

**Comment by SHWotever** [comment]
Hi ! I recently had the final word about these lacks of data, it seems that it's under non disclosure agreement, that's why we will never get the infos. In parrallel I added an improved wheel lock feature which compensates a little this lack.

**Comment by bjgrech** [comment]
Are you saying that at some stage of RF2's development the software developers probably signed a non-disclosure agreement not to release the skid data to third parties? And therefore you will probably never get the data for vehicles that were developed after the probable signing of the non-disclosure agreement? And that's why there's skid data for vehicles that were developed earlier in RF2's development but not the later ones?
