### ISSUE TITLE
ERROR - System.TimeoutException: The operation has timed out.

### ISSUE THREAD

**Issue by gp66** [SHWotever/SimHub#396]
Simhub latest version.
Current game is iRacing.
Current setup is wheel slip for throttle and wheel lock for brake pedal using Shakeit plugin.
Arduino UNO, Addafruit motor shield, game controller rumble motors.

Rumble works for awhile but as soon as game transitions from practice to qualifying or I wait a few minutes for next session everything stops working.

Log file attached.

Thanks for any help,

Gary

[SimHub.log](https://github.com/zegreatclan/SimHub/files/3530668/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! Thanks for the report, I've found the "pot-hole", this is the same as #386, it will be fixed in the next release.

Nicolas
