### ISSUE TITLE
Max 7221 Led Matrix not workin in Richard Burns Rally

### ISSUE THREAD

**Issue by mufas007** [SHWotever/SimHub#397]
Hi, like in title, it's not working. In Project Cars 2 and Dirt 2.0 works fine. I set up a game path to Richard and starting game from simhub. I also had simillar problem few months ago with MAx7221 7Segment module, wasn't working too. Simhub version 6.8.2

**Comment by SHWotever** [comment]
Hi ! Are you using some mods ? Rbr is really special as it uses direct memory reading. It's possible that some mods modifies the game as much as simhub is not able to read data from it. In all cases make sure to run the latest patch on rbr (1.02 sse) and start it using richarburnsrally_sse.exe, also make sure simhub is running as administrator so simhub can read the game memory.

**Comment by mufas007** [comment]
Hi.
Thanks for answer. No game is not modded but i try patch the game. Simhub is always run like an administrator.
