### ISSUE TITLE
[ETS2] [Display LCD 20x4 i2c] - City name languages

### ISSUE THREAD

**Issue by danfeliix** [SHWotever/SimHub#398]
Friend very much appreciate the simhub. And recently I set up a panel with a 20x4 i2c lcd display to play with Euro Truck Simulator 2 and set the LCD to show the city of origin and destination of the trip, it was very good. The problem that I realized which cities only shows the original name (examples: Warszawa, Zürich) even with the game update (1.33) that translates the names of the cities in the game to the language I use, in SimHub only shows the original name and for be worse names of Russian cities like St. Petersburg on simhub shows Санкт-Петербу́рг and the panel does not show, only codes appear. How do I use language PT-Br in the game translating activating the new option in the game could not simhub understand this action?
![20190825183342_1](https://user-images.githubusercontent.com/54558657/63727760-c11a6600-c837-11e9-8ab0-8931393b1a53.jpg)
![Captura de Tela (68)](https://user-images.githubusercontent.com/54558657/63727981-836a0d00-c838-11e9-94a6-7991ce4ca3ea.png)
![IMG_20190825_183352](https://user-images.githubusercontent.com/54558657/63728002-9250bf80-c838-11e9-9e89-240fc5fcb065.jpg)

new function from 1.33 of the game that translates the names of cities
![2019 08 26-19 32](https://user-images.githubusercontent.com/54558657/63728028-b44a4200-c838-11e9-966d-19d6670bdd43.png)

**Comment by SHWotever** [comment]
Hi ! 

I'm affraid it's the way the cities names are given by the sdk for now, 
It's translated maybe in the latest SDK, I've not checked yet, I already have on my TO-DO list to do the update (see #356), maybe it will give the translated version of the cities names.

I close this one as duplicate, you can watch the #356 future request to see know when it will be implemented.

Nicolas
