### ISSUE TITLE
iRacing - New Silverstone the Persistant tracker isn't working and is causing errors.

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#399]

**Comment by SHWotever** [comment]
Hi !

Do you have the log files so I can see what is happening ?
I'm about to release the next version and I will be happy to fix it before ;)

**Comment by Meekstaaa** [comment]
Sure, here it is!
[SimHub.log](https://github.com/SHWotever/SimHub/files/3571133/SimHub.log)

**Comment by SHWotever** [comment]
Hum Looks like a data record is corrupted and simhub can't load it,
could you try to browse to PluginsData\IRacing\PersistantTracker and remove the silverstone folder ?

I've added security to avoid the pothole it felt into, but I would be interested in a copy of the folder to see what has happened more in detail and ensure I secured the correct case.

**Comment by Meekstaaa** [comment]
Ok. Deleted the folder and the error has gone on the replay but I haven't run any laps to see if the error has fully gone. I'll look tomorrow. 

Could it be due to the new version of Silverstone being released and they renamed the folders in the iRacing install?

**Comment by SHWotever** [comment]
No I don't think so, the crash pointed me where it was loading the simhub lap file, from my deduction the file existed but ended empty (or corrupted) after loading causing this recurring crash. 
Simhub uses the track name as a storage folder, but at worse if it was renamed it would simply recognize it as a new track.
