### ISSUE TITLE
"Redraw the map now" and a "Clear the lap history now" clickable buttons

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#400]
Bonjour! Here is a small quality of life improvement suggestion.
As buttons are a valuable commodity, I think it would nice to have a "Redraw the map now" and a "Clear the lap history now" clickable buttons next to the binding options. Since I have a very punctual use of these features, I bind/unbind a button every time i need to use them.
Thanks for considering the idea!

**Comment by SHWotever** [comment]
If you do a right click on the actions you can trigger it easily,
![image](https://user-images.githubusercontent.com/2207331/64476645-a4642380-d191-11e9-85a7-e06859cac968.png)

The difficulty with these action are that they need to be done when in game (so simhub knows which track and/or car is bound to it. I need to find a smart way to handle this "offline"

**Comment by Romainrob** [comment]
Ahhhh. So it's already there (insert facepalm emoji here). Perfect!
I didn't realize we could right click here.
Thanks!
