### ISSUE TITLE
Sorting the Settings/Game list

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#401]
Bonjour!
Here is another small quality of life improvement suggestion. An easy one hopefully.
I feel that looking for a game in the games list on the Settings/Games page is harder than it should be. I think the games list in the settings should be static and alphabetical.
Thanks for considering the idea!
Bonne journée!

**Comment by SHWotever** [comment]
I totally agree, alphabetical should be a good thing, on another hand I'm really attached to user customization it's why I always left this possibility to reorder them, maybe a "reset order" could be a perfect compromise,

**Comment by Romainrob** [comment]
Always giving us the options... :) I like it!
A button could do it. Maybe a "Sort" button to switch between alphabetical mode and custom mode. So users can go back and forth.

**Comment by SHWotever** [comment]
I added a sort button for the release ;) 
![image](https://user-images.githubusercontent.com/2207331/64478878-7261ba00-d1af-11e9-9e91-4726aa7b253d.png)

**Comment by Romainrob** [comment]
Well done! Thanks!
