### ISSUE TITLE
Thrustmaster manager

### ISSUE THREAD

**Issue by gegewrc** [SHWotever/SimHub#402]
Request :
Hi!
Would it be possible to be able to increase or decrease the wheel rotation with controls like we do with overall gain? It would be easy to quickly change the value without moving back to the simhub soft.

Thanks if possible!! Thanks anyway if not possible :-)

**Comment by SHWotever** [comment]
Hi ! 

Sadly it would mess up in most situations as soon as you are in-game, on most games, changing the wheel rotation breaks ffb and creates weirds behaviours, that's why I did not add any "quick-access" to it.

**Comment by gegewrc** [comment]
Hi!

Thanks for your answer. I will save one profile of rotation wheel per game... It will solve my problem.
Thanks!

**Comment by SHWotever** [comment]
Indeed it think it's the best way (if not only way :D)
