### ISSUE TITLE
ShakeIt - Running disabled effects

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#403]
Bonjour! 
It looks like ShakeIt (motors and bass shaker) is running disabled effects in the background. At least custom effects. I noticed it because of these errors popping up from a disabled wind effect.
![image](https://user-images.githubusercontent.com/50543913/64488127-50664700-d244-11e9-870d-fa1c0fe1b8aa.png)
Tested with a custom shaker effect and had the same result.
I doubt this is an intended behavior so I thought I'd report it. I'm on the 6.8.4 btw.
Bon dimanche!

**Comment by SHWotever** [comment]
Uh uh! Indeed! I was convinced I was not running disabled effects but I missed something, thanks for the report, it will save a few tenths of CPU :D
