### ISSUE TITLE
Arduino/Screen Editor can not save settings

### ISSUE THREAD

**Issue by R0N7N** [SHWotever/SimHub#405]
If I open SimHub, go to Arduino --> Screens and edit a screen setting the editor kinda doesn't save anything and is stuck. I can't even close it.

Running SimHub 6.8.4 licensed and as admin account.
Did reinstallation
Running a decent gamer pc with Win7 x64

SimHub log attached:

[SimHub.log](https://github.com/SHWotever/SimHub/files/3612000/SimHub.log)

**Comment by SHWotever** [comment]
Hi! Thanks for the log, I see Simhub systematically can't write the settings file (access denied to the file). I think it's a file rights issue.

I see three options :

**Setting file is in readonly**
- Go into the file properties for this file "C:\Program Files (x86)\SimHub\PluginsData\Common\SerialDashPlugin.json" 
- Ensure "readonly" is not checked.

**Reset everything:**

- Uninstall Simhub 
- Delete the whole  C:\Program Files (x86)\SimHub remaining folder (user settings are kept here even after uninstall)
- Reinstall Simhub

**To keep your current settings :**

- Close Simhub
- Backup this file somewhere safe: C:\Program Files (x86)\SimHub\PluginsData\Common\SerialDashPlugin.json
- Delete the setting file stored in simhub installation :  C:\Program Files (x86)\SimHub\PluginsData\Common\SerialDashPlugin.json
- Start SimHub :  it will recreate a new empty settings file.
- Close SimHub
- Open both files with a text editor (notepad) the new one and the backup file.
- Replace the whole content from the backup file into the new setting file
- Save the file and start SimHub
It's important to only copy/paste the file content only, if file rights are wrong, copy pasting the whole file would copy the rights too.
