### ISSUE TITLE
Function that returns race position for each dot on Static map

### ISSUE THREAD

**Issue by Ciccina2016** [SHWotever/SimHub#407]
Is it possible to execute a function that returns the race position for each dot on the track map?

If yes than thanks to Gary Swallow plugin I could write a piece of code which fills the dot colour based on class.

I noticed that if you create a new overlay and add the static map there is a section called "OpponentStyle"
each dot returns the position so i guess there is also the possibilty to return the class?

**Comment by SHWotever** [comment]
Hi ! Sadly this is not possible, each map is running alone and there is no communication possible from scripting to a specific component running in a dash (the map). I'm afraid I can't work around that, as technically it is really impossible to address the track map from scripts. (scripts feeds components properties, but the opposite is not possible)
