### ISSUE TITLE
System.OutOfMemoryException Crash

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#408]
Hi!
I've had a couple of System.OutOfMemoryException crashes with the 6.8.4 and 6.8.5
I thought you could be interested in having a look so I saved them
[Out of memory 1 SimHub.log.txt](https://github.com/SHWotever/SimHub/files/3615077/Out.of.memory.1.SimHub.log.txt)
[Out of memory 2 SimHub.log.txt](https://github.com/SHWotever/SimHub/files/3615078/Out.of.memory.2.SimHub.log.txt)
I don't remember exactly when the 1st happened.
The second time, it crashed while loading the ShakeIt output mapping table. It's possible I had 2 effects outputting to same property. I couldn't check afterward as the profile wasn't save due to the crash.

**Comment by Romainrob** [comment]
Hi!
Idk if you found and fixed something, or if these were oddballs, but I haven't had any of these crashes since the 6.8.6 :).

**Comment by SHWotever** [comment]
Nice ! I admit I could not find a particular cause and since I improve a lot of things almost every day, I fixed it without knowing it probably :D
I close it for now, but do not hesitate if somehow it happens again
