### ISSUE TITLE
ERROR - System.Net.Sockets.SocketException (0x80004005)

### ISSUE THREAD

**Issue by jfbodewes** [SHWotever/SimHub#411]
17:52:00,862] ERROR - System.Net.Sockets.SocketException (0x80004005): Er is geprobeerd toegang te verkrijgen tot een socket op een volgens de toegangsmachtigingen niet toegestane manier
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at SimHub.Plugins.DataPlugins.UDPRelay.UDPRelay..ctor(Int32 listeningPort, IEnumerable`1 targets)
   at SimHub.Plugins.DataPlugins.UDPRelay.UDPRelaySettings.ApplyConfig()
[SimHub.log](https://github.com/SHWotever/SimHub/files/3638853/SimHub.log)

**Comment by SHWotever** [comment]
Hi! 

Looks like you have configured the relay to listen to a port already in use. I've fixed the crash occurring in this case for the next version.
To work around this incorrect configuration you can 
- Stop SimHub
- Delete the following file : C:\Program Files (x86)\SimHub\PluginsData\Common\UDPRelay.js
- And restart simhub.

It will reset the UDP relay settings.

Let me know if it helped, 
Nicolas

**Comment by SHWotever** [comment]
Following this issue i've added protection to prevent such situation released in 6.7.8 version
