### ISSUE TITLE
Feature suggestion: allow clean shutdown via programmatic means

### ISSUE THREAD

**Issue by TheIronWolfModding** [SHWotever/SimHub#414]
For example, via Global Event that can be signalled by other apps.  Currently, if I kill app, it loses all settings.

Thanks for your consideration.

**Comment by SHWotever** [comment]
Hi!
I've added a "CLI" interface to communicate with the running SimHub instance in the next version
https://github.com/SHWotever/SimHub/wiki/Command-line-interface
It will work with no administrator privileges (even if SimHub is already running as admin) so it's perfect for any kind of integrations.

**Comment by TheIronWolfModding** [comment]
That sounds fantastic - global event would've required elevation, and I try to avoid that unless needed. 👍

**Comment by SHWotever** [comment]
Released with 6.7.8, thanks again for the feedback !
