### ISSUE TITLE
Feature suggestion: allow for removal of app features

### ISSUE THREAD

**Issue by TheIronWolfModding** [SHWotever/SimHub#415]
It would be nice, if it was possible uninstall/remove SH features that are not in use, like Dash, Statistics, Arduino etc.  Like JRiver Media Center allows it.  It is low priority, but maybe something to allow in the future?

Thanks for your consideration.

**Comment by SHWotever** [comment]
Hi!

I took a look if I could split further the latest features,  for now I'm affraid the cross dependencies makes impossible to remove Arduino part but In a close future, I plan to rework the led editor and make it reusable across plugins so I will be able to make the whole Arduino part optional.

For dashstudio I need to find a way out of the typical plugin method I use as the required servers (websockets and http server) can't be stopped and started at will.

For the last two (statistics and car settings) they are part of the core of simhub, I will try to hide them but the computations will still run in the background.

**Comment by TheIronWolfModding** [comment]
I truly appreciate you giving it such a thorough thought.  This is low priority, but it will make minimalist like me much happier.

Would it be possible to stop background computations as well, or is it too risky?
Would it be possible to stop websockets/http server on restart, and start them optional?  I know restarting things is often difficult, but if it does not even start, that'd be awesome.

Thank you!

**Comment by SHWotever** [comment]
I finally removed the arduino in the latest version, it's now possible to have a raw SimHub doing pretty much nothing except game data reading.
![image](https://user-images.githubusercontent.com/2207331/68998962-61bd7680-08b9-11ea-9cd8-3f79e7ca0827.png)
About dash studio, I have been able to separate features enough so it's also possible to disable it.
