### ISSUE TITLE
Nextion Uploader Closes when opening dropdown

### ISSUE THREAD

**Issue by WibbersGIT** [SHWotever/SimHub#419]
I am trying to use the new 0.58 nextionuploader.exe to upload a tft file to my Nextion. Whenever i drop down the Serial Port or Upload baud rate drop downs the application just closes. There are no errors, it just closes. I am unable to choose a COM port or baud rate and complete the upload.

Simhub 6.8.6

**Comment by SHWotever** [comment]
Hi! 
I've been able to reproduce the issue on my laptop, after some investigations it seems that afterburner is guilty: https://forums.guru3d.com/threads/afterburner-rtss-is-crashing-occt-on-some-setups.428644/

After updating RTSS to the latest version (7.2.2) the crash does not occur anymore.
Make sure to install the latest version of RTSS to solve it : 
https://www.guru3d.com/files_details/rtss_rivatuner_statistics_server_download.html

Let me know if it solved the issue
Nicolas

**Comment by WibbersGIT** [comment]
Thank you very much. I installed the latest RTSS 7.2.3 and the crash doesn't occur anymore. However I noticed I am only able to upload at 9600 baud, which as you can imagine took a very long time to upload a 4MB file. Anyway to troubleshoot that?

**Comment by SHWotever** [comment]
Hi!

That's very strange, what screen model are you using? Could you tell me what does happens exactly? Error message on the screen? Upload freeze ...)

**Comment by WibbersGIT** [comment]
On the first try I get this.

![image](https://user-images.githubusercontent.com/24574428/65819656-1eb22180-e1ed-11e9-9c6a-06c3e29c95d9.png)

The nextion shows an update starting but then freezes at 0%. Then I unplug/replug the nextion and it shows Data Error. Then re-open the uploader and try again and I get this. For any baudrate I choose.

![image](https://user-images.githubusercontent.com/24574428/65819710-bdd71900-e1ed-11e9-9b8e-72be3c392203.png)

![image](https://user-images.githubusercontent.com/24574428/65819741-14dcee00-e1ee-11e9-8f94-c3e32178a7ed.png)

Then the nextion says "The Resolution file resolution is not fit!" This is the same error I used to get when uploading a 0.58 template using the 0.53 uploader.

Untill I try 9600 baudrate then the upload completes successfully, but as you can imagine it takes an hour to upload a 4MB file.

![image](https://user-images.githubusercontent.com/24574428/65819764-78ffb200-e1ee-11e9-96bc-599c7b84f62a.png)

**Comment by SHWotever** [comment]
That's pretty weird it acts as if the data transmission was really bad, have you tried with the editor itself? I've patched it to allow upload even on Arduino micro, you just need to disable leds before.

**Comment by WibbersGIT** [comment]
Yeah i was thinking the same thing. I wonder if I have a weak solder connection somewhere, But I didn't have this issue with the old up loader. I will have to open it up one of these days and check my connections.

Thanks for the help!
