### ISSUE TITLE
Missing "Alt" key in keyboard emulater

### ISSUE THREAD

**Issue by kurtimuc** [SHWotever/SimHub#420]
Hi, I'm using the latest version of SimHub V6.8.6 and do some keypress simulations which nearly works all well. But combinations with the "alt" key aren't working. There is no "alt" key in the list, only a "Alt+none" but this will not work in combination with another key.
An additional great feature would be a free text field to enter the name of the simulated function.
Thanks in advance,

**Comment by carlosflores** [comment]
I have the same problem, any solution?

**Comment by MopheusDG** [comment]
Same here, by the way... what an outstading application ! CONGRATS MAN/WOMAN ! I LOVE IT !

**Comment by thomasvjohansen** [comment]
in rFactor2, to adjust mirrors etc you have to press "ctrl+alt+" & "ctrl+shift+" but its not possible to assign this to one button. Would it be possible to add this?

**Comment by janniek21** [comment]
has this changed yet?

**Comment by kurtimuc** [comment]
Unfortunately not, it is probably a very low priority!

**Comment by janniek21** [comment]
is there a way around this

**Comment by kurtimuc** [comment]
If you absolutely need it, you can use the "JoyToKey" software, where it is possible, for example, to simulate the "alt" key in combination with other keys. Here in SimHub I don't know of any other option, but maybe Wotever can say something about it?

**Comment by martinlanza** [comment]
The Alt key is there, it's named incorrectly, use the "Menu" key

**Comment by janniek21** [comment]
ok il try thanks a lot

**Comment by thomasvjohansen** [comment]
@martinlanza are you saying its the left alt key is named Lmenu?

**Comment by SHWotever** [comment]
Hello ! I released a new version with something more easy to use ;) 

https://i.imgur.com/SxuK6IR.gif

Indeed the names were based on the windows constants and they are a little counter intuitives :(

**Comment by martinlanza** [comment]
> @martinlanza are you saying the left alt key is named Lmenu?
> well im missing the left alt key. "LAltKey"

As per my post, the ALT key is named MENU 
This is not specific to left or right

Per post from Wotever - there is a new version which solves the problem

**Comment by thomasvjohansen** [comment]
i can confirm that left alt works in simhub now, thx @SHWotever
