### ISSUE TITLE
TM1638 with 16 button support

### ISSUE THREAD

**Issue by lucGerm** [SHWotever/SimHub#425]
Unfortunately this TM1638 doesn't work properly. It works pretty similar to the supported TM1638 Board but I couldn't bring it to work that you have still the choice for both TM1638 boards.

[https://www.ebay.com/itm/TM1638-Digital-8-Bits-16-Keys-LED-Keyboard-Scan-And-Display-Module-Digital-Tube/142668705462?_trkparms=ispr%3D1&hash=item2137b7aeb6:g:lSsAAOSwCU1YrUoq&enc=AQAEAAACMBPxNw%2BVj6nta7CKEs3N0qU8%2B5eZDBaYT7oMd6tpQq%2BIK%2FxmzO2asIs2hh8dnRuZL3hgtXJ1ixdzTnJ3beRh3NMlb772yypLf%2FmKDY%2FaWQS1YxduTV5j1m9GJiIYAufFVwGufrel2GwoomjPJorHeNGt4V%2BJ3oyrKi%2BLswCmINw9MmAwyk7hSstsPpiYcLVue6NzVMZwBciz5x5umHwKDMbTmu0iWXWdtimQWgFyYPJF0YLypM3XaYvlFpggbeel750o1jVSXseIIeK0AA2rkdu%2FRgLC22pStapfbH07hs3GzBfY2HZYszDHVs%2BpbqT0IgbX5X26EFe899zPVCg63s9XnrDl%2F19P%2B%2B2bvAKFRd9PTwDndgao2Szz3yrSckuoXMYE0vXzTVFFrtad9xhZBJ7mP%2F1nP8cZF1VPA7LNOsrXJsxMoCl6VgMUgBLRC2ZsjXd%2BtV5JioetVHyZZbEK43JBfRTrSZrOAwckMG2kOIqIz1hI%2F891PKYTKRlNS7yBV%2FOPPx8JCVPC2vx%2Fix9qR1nYKH0qVD3SWci5rPsem51X2Qp1iBoUQaRhh8u2OUjAXjAhh%2B8XI5Amc2ULJ0w45Gvpcqf0WitJ8Gts5R%2Fj%2B5YVNfPWLOeFkXBl%2Bq0F3bBcZp2YiJ3PiRlBWAiS16s13wSEylto2v7gcljKVlrXqv4RZaO%2F%2BziwY5mVZIzdu%2BYbaeKeMRrgRr7pt7tUZBeTbBApxmgo6BOEn64zzPcHIiTr&checksum=142668705462371e0ee5b9d0492fb832a791d84e7a66](url)

**Comment by SHWotever** [comment]
Hi! indeed this board is not supported, I will look to grab some and see if something can be done ;)

**Comment by SHWotever** [comment]
Hi ! Unfortunately such hardware interrest is slowly dropping, and I don't plan to add new "text" based displays.
