### ISSUE TITLE
İndicator for aircraft pitch

### ISSUE THREAD

**Issue by furkanozden** [SHWotever/SimHub#427]
Hi,

I'm trying to make a panel for war thunder. When I try a vertical linear gauge, the image divides. An indication where the image moves along the y-axis would be good.

**Comment by SHWotever** [comment]
Hi !

I'm affraid i've not totally understood the issue, could you attach a screenshot or an example dash ?

Nicolas

**Comment by furkanozden** [comment]
Trying to adjust the horizon ball indicator. I want the ball in the middle to move vertically. I am trying to do this with the vertical linear gauge tool. The result is a visual split. What I want is the visual movement. I want it like dial gauge but in vertical movement.

![horizon_ball_1](https://user-images.githubusercontent.com/3254437/66980127-835bf000-f0b8-11e9-8d6e-43815649f902.png)
![horizon_ball_2 png](https://user-images.githubusercontent.com/3254437/66980128-835bf000-f0b8-11e9-9204-b3040211ae04.png)
![horizon_ball_3 png](https://user-images.githubusercontent.com/3254437/66980129-835bf000-f0b8-11e9-9f8d-63f0173f9869.png)

**Comment by SHWotever** [comment]
Hi ! Unfortunately after all those years this request remained very very rare. I close it for readability purpose even if the the feature would be interesting.
