### ISSUE TITLE
Shake It exported properties missing sometimes.

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#428]
Bonjour!
I noticed the properties exported from Shake It tend to go awol sometimes.
I did a little testing and they are missing after a plugin restart. So i guess the plugin must restart on it's own in some cases.
Really no big deal once you now a SimHub restart fixes it. Still I thought I'd report this.
Bon week-end!

**Comment by SHWotever** [comment]
Ah ! Well seen, Actually the shakeit plugin does not "restart" opposite to most plugins but keeps track of exported properties, following your information, I've found indeed that after a game change or anything triggering a game reader rebuild (settings change ...) it would not recreate the properties .... and .... I've fixed it ;) Hopefully it was an easy fix !

**Comment by Romainrob** [comment]
Wow! That was fast!
Thank you!

**Comment by SHWotever** [comment]
Fix published with the final release ! Have fun !
