### ISSUE TITLE
[request] iflag style function + send pit commands

### ISSUE THREAD

**Issue by ChrisInde** [SHWotever/SimHub#429]
Hi,

I'm trying to cut down the amount of apps that I use with iRacing. Because I already use some functions from SimHub I was wondering if the next two functions could be implemented in the future.

1: flags on a 8x8 rgb arduino shield. I now have iflag which works great but having it in SimHub could open the door for more sims to enjoy this. Also using SimHub for this gives more options to custumization of the color shield. If a new shield is needed to make this work with SimHub then I have no problem investing into this. 

2: I also use z1dashboard but I like simhub more because I can build my own custom dashboards. But one thing that I miss is sending pit commands. Mainly the one button press from my buttonbox to add enough fuel to end the race when making my final pitstop. Z1 calculates the amount needed and by pressing a button it sends this value to iRacing.

Are these things that would be possible in future releases of SimHub?

Mant thanks in advance and keep up the good work! 

Greetings 
Chris

**Comment by SHWotever** [comment]
Hi!

Iflag is a long-time request indeed, I will probably come to it, but for now only Iracing has a  detailed flag system, all other games are really basic about this with only a very few flags, which made me delay it for now since simhub is "multigames" (I often receive lot of reproach when a feature is supported on a very few games)

About pit stop, the same struggle applies about "game exclusive" features. It may come in the future but I can't say when for now.

Nicolas

**Comment by ChrisInde** [comment]
Thanks for your reply. Maybe the 8x8 display can also be used by other sims and iracing to display other things then just flags. Things like a shift light or a countdown, engine info, changing colors based on delta times... Just like we can do with the ws2812b leds. Just an idea of course.

**Comment by ChrisInde** [comment]
Sorry to bother you again with this but I've been looking into this myself and I found the NeoPixel NeoMatrix (https://www.sparkfun.com/products/12662). This is a 8x8 matrix with WS1218 leds which are just one long chain and are addressable.

Correct me if I'm wrong, but with this I think I can create my own flag display using the LED editor of SimHub.

Many thanks in advance!

Greetings,
Chris

**Comment by sebrocco** [comment]
Hi Chris, can you give a update in your project ? im looking exactly the same way.

**Comment by SHWotever** [comment]
Hi ! matrix feature has been released a few releases ago : https://github.com/SHWotever/SimHub/wiki/Arduino-RGB-Matrix

About sending pit commandes, it's too "iracing" specific, i won't add it i'm sorry.
