### ISSUE TITLE
[Feature Request] - More control over the replays

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#431]
Hi! I think having more control over the replays would be nice. These are the features I can think of:

To help when searching a replay:
- Being able to rename the replays
- Being able to rename to reorder the list
- Having a bigger window for the list
- Having a slower/smoother scrolling with the mouse wheel. Mine jump 3 lines at a time (could my mouse settings)

When actually playing a replay
- Having a play/pause button
- Having a speed option
- Being able to loop a region

Hopefully some of them are doable
Thanks for considering the idea et bon dimanche!

**Comment by Romainrob** [comment]
Hi!
The new replay features are awesome!
Thank you very much! :)

**Comment by SHWotever** [comment]
Nice happy that you like it !
I've added all remaining features in the last update, the only one I've not added is custom ordering, I want to keep it by date descending intentionally ;)

**Comment by Romainrob** [comment]
Chronological order is good. The description will help differentiate the special ones anyway.
The replay controls and looping will be so good to tune shakeit! :)
Well done Sir! Thanks again!
