### ISSUE TITLE
Shake It "Speed" issue

### ISSUE THREAD

**Issue by simrce** [SHWotever/SimHub#432]
Hi,
i have a issue with Shake it. I use a Motor Shield v2 with an Adruino for Simwind. If i test the Motors in the Output Selection with "Test now" the motors running with 100% Speed. If i test it in the Effects Profile they running just like 50% of Speed. The same is ingame. I had never issues like this in a older version of Simhub. 

Thanks in advance and sorry for my bad English

**Comment by SHWotever** [comment]
Hi !

Indeed I found an issue about "test" option, it does not takes global gain into account; Fix will be released in the next version so will have the global gain applied,

In the wait you just have to push the global gain slider to get the maximum of the effects :
image
![image](https://user-images.githubusercontent.com/2207331/67160003-12cd0180-f34c-11e9-8512-3c0d2090f6e0.png)

Let me know if it helped,

Nicolas

**Comment by simrce** [comment]
Oh, it works now. It was my fault. I didn't see the regulator for Gain. But it works now. Thank you very much for the fast help
