### ISSUE TITLE
[Feature request] Thrustmater rim name as a property

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#434]
Hi,
I made a custom input display, and having the steering wheel image matching the current rim automatically would be pretty cool.
![image](https://user-images.githubusercontent.com/50543913/67259707-99dac080-f497-11e9-8790-94da9d485609.png)
I have 5 rims. I though I could read the PID with a plugin to tell  which one is on, but it only changes when the F1 rim is on :(
Any chance the Thrusmaster plugin could return the name of the the rim currently installed on the base as a property please?

**Comment by Romainrob** [comment]
Hi. I finished my overlay and had a closer looser a the wheel names.
I noticed some of them appear as a group in the driver. If these rims are all the same for the driver, i guess it won't be a 100% reliable, even if you can access this data, :( 
![image](https://user-images.githubusercontent.com/50543913/67517747-8ac85e00-f6a3-11e9-82fc-06f57fde1bde.png)
So it may not be worth the effort.
Let me know if you feel like looking into this. Or close the ticket if you want. I won't hold it against you.
Here is the overlay btw : https://www.racedepartment.com/downloads/inputs-display-simhub-overlay.28742/
Bonne soirée!

**Comment by SHWotever** [comment]
Hello ! 
I took a look and indeed it looks like you said that even in drivers all wheels are not recognized which makes it unreliable  (my Sparco R383 is not recognized for instance) I really fear that it's not worth the reverse engineering efforts :(

**Comment by Romainrob** [comment]
The R383 has been tempting me form the day they announced it, but it's difficult to justify a 6th wheel... :)
No worries. I understand. I'll go with on a per car basis for the cars I drive the most often.
Thanks for having a look!
