### ISSUE TITLE
iOS dashboard loading issue - Fixable?

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#437]
Hi!
I investigated the iOS dash issue a bit more. I though you may find this interesting, maybe even think of a way to fix this on your end. Here are my findings:

1. A gauge will cause loading issues if it appears empty (value under, equal or barely over the minimum while loading)

2. If the dash still loads, anything loaded after the gauge will be broken (displaying static default values instead of calculated values)

Here is an example to test with:
[iOS gauge- Simple test.zip](https://github.com/SHWotever/SimHub/files/3802151/iOS.gauge-.Simple.test.zip)

I went ahead and fixed my iRacing dash with a workaround. I changed the gauge value formulas to max(actual value, minimum value so the gauge doesn't look empty). Now it loads and runs fine on iOS (crashing on memory limited device aside... ). The only downside is the gauges can't look completely empty now but it's ok.
I'll wait for you opinion on this before updating on RD.
Thanks in advance.

**Comment by SHWotever** [comment]
J'ai attrappé le vilain ! Effectivement une petite intolérance de safari à une instruction, j'ai corrigé !

**Comment by Romainrob** [comment]
Super!
Bien joué et merci!

**Comment by SHWotever** [comment]
Final release published ! Have fun !
