### ISSUE TITLE
Simhub intermittently freezes, no response shaker

### ISSUE THREAD

**Issue by Hylkos** [SHWotever/SimHub#438]
Dear Wotever,

I recently purchased software, and I'm really impressed by the functionality. But since I start using it (for my buttkicker gamer 2), the program freezes from time to time, giving no input to the shaker.

When I switch from the game (RR, F12019), the program is not reponding. Going back to the game, the shaker works after approx. 2 laps. 2 laps later the problem is back. 

This goes on repeatedly.

Am I missing a setting, or is this a known issue?
--
[SimHub.log](https://github.com/SHWotever/SimHub/files/3816298/SimHub.log)

Okay, will send the logs. Additional info:

The functionality was lost 8 times tonight in a 14 laps during race in Bahrain (F1 2019). I kept on racing and I noticed that most of the times it stopt working when I crossed start/finish. At approx. 3/4 of the track (second to final straight) the functionality came back.

**Comment by SHWotever** [comment]
Hi ! Thanks for the log,

I see it's fighting really hard with the lap history database, 
Could you backup and send me the following file so I can analyze it?
C:\Program Files (x86)\SimHub\PluginsData\F12019\DataStore.db

In the wait you can try to delete the file, it will be recreated, simhub lap history will be lost but it should stop the issue.

Nicolas

**Comment by Hylkos** [comment]
Wotever,

I thought of something when you asked for the logs. I installed the program on a external HDD, that might be the issue.

Reinstalling it to the C drive seems to resolve the issue, but I'll try it in duration tomorrow..

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by SHWotever** [comment]
Ah indeed that explains it ! It matches the behaviour i've seen in the log.  When the drive is slow (which looks like) it will take much more time to save the lap (usually a few milliseconds in normal conditions).

**Comment by Hylkos** [comment]
Hi Nicholas,

I tested the software yesterday in a longer session and the problem is solved. So for future references: Don’t install it on a external HDD!

Thanks for your help!

Kind regards,

Hylke Nota

________________________________
Van: Wotever <notifications@github.com>
Verzonden: Wednesday, November 6, 2019 10:09:37 PM
Aan: SHWotever/SimHub <SimHub@noreply.github.com>
CC: Hylkos <hylkos@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [SHWotever/SimHub] Simhub intermittently freezes, no response shaker (#438)


Ah indeed that explains it ! It matches the behaviour i've seen in the log. When the drive is slow (which looks like) it will take much more time to save the lap (usually a few milliseconds in normal conditions).

**Comment by SHWotever** [comment]
Happy to hear it ! Thanks for the feedback !
