### ISSUE TITLE
Simhub not loading

### ISSUE THREAD

**Issue by Gruntypellinor** [SHWotever/SimHub#439]
I have an issue where simhub is starting, making it to the white screen with the logo, and hangs there. The window can be resized but otherwise its unresponsive. I tried all of the steps on the wiki. The first time it did allow the app to fully launch but it subsequently crapped out and since then, the subsequent reinstalls haven't helped.

**Comment by SHWotever** [comment]
Hi ! Do you have the log files so I can take a look? they are stored in C:\Program Files (x86)\SimHub\Logs

**Comment by Gruntypellinor** [comment]
Thanks! Here you go.


Sent from Mail for Windows 10

**Comment by Gruntypellinor** [comment]
This is where it hangs

Sent from Mail for Windows 10

**Comment by SHWotever** [comment]
Hi ! Could you join it directly on github ? attachments are not joined when you reply using mails.

**Comment by Gruntypellinor** [comment]
I will endeavor to figure that out when I get home tonight. Thank you.

**Comment by Gruntypellinor** [comment]
[SimHub.log](https://github.com/SHWotever/SimHub/files/3825844/SimHub.log)

**Comment by Gruntypellinor** [comment]
Here it is thank you

**Comment by SHWotever** [comment]
Thanks ! I see that the lap history storage got corrupted, could you delete the following file : C:\Program Files (x86)\SimHub\PluginsData\KartKraft\DataStore.db, it will reset the lap history and it should get back to life.

Let me know, Nicolas

**Comment by Gruntypellinor** [comment]
Thanks. I'll try that when I get home.

**Comment by Gruntypellinor** [comment]
Thanks! That worked. Back in business.

Sent from Mail for Windows 10

**Comment by SHWotever** [comment]
Perfect! Thanks for the feedback!
