### ISSUE TITLE
Bmw e36 cluster

### ISSUE THREAD

**Issue by OmarDiablo** [SHWotever/SimHub#440]
HI everyone.... 
I made project bmw e36 cluster and followed this video https://youtu.be/L59NL9EuEdM
I success made connection between PC and Arduino board but when when I enter to blinding and press on compute value that's nothing happened and the gauges not work when I play the game,,,  please help me..

**Comment by SHWotever** [comment]
Hi ! You are using an obsolete method, make sure to follow cautiously the instructions available on the official documentation and everything should be fine : https://github.com/SHWotever/SimHub/wiki/BMW-E36-Cluster-Setup,

Nicolas

**Comment by OmarDiablo** [comment]
Thanks a lot it's work now 👌 but I want to ask you,, can I use the flasher or blinker in cluster by arduino??

**Comment by SHWotever** [comment]
Hi! It's not supported I'm sorry, it requires power drivers (to drive 12v) which makes the assembly too complex for out of box support. But you can do your tip120 based power drivers and use custom protocol to drive the pins: https://github.com/SHWotever/SimHub/wiki/Custom-Arduino-hardware-support

**Comment by OmarDiablo** [comment]
Thanks Nicolas ♥

**Comment by dannyatyeo** [comment]
what settings did you use for the speedo
