### ISSUE TITLE
Additional arduino press buttons

### ISSUE THREAD

**Issue by skate2create** [SHWotever/SimHub#441]
Is there a reason for max 12 press buttons, or could I change the enabled buttons count to 15 and make the necessary changes within arduino IDE?  I know I could use a button matrix to get more than enough inputs, but as I only need an additional 3 inputs to my wheel I wondered if I could do it without using a matrix?
I'll be using an arduino Mega to run a TM1638, 5 rotary encoder (3 pin type) and 15 other inputs made up of momentary push buttons and momentary toggle switches. 

TIA.

Dan

**Comment by SHWotever** [comment]
Hi ! Everything has a max :D, technically arduino memory is tight (sketch is universal and can fit many arduinos models and the smallest supported model determines what the sketch must fit. so I have to choose wisely how many instances of each feature I can add, I already raised this limit a couple of times for buttons, but with some hardware combos, it starts to be really really tight that's why I can't add more buttons for now.
If you have 15 buttons, a matrix like 5x3 will do the job pretty easily. Warning, in a matrix setup you can't use multiple buttons at the same time, it must be known. you can see the wiring here : https://github.com/SHWotever/SimHub/wiki/Arduino---Button-matrix
Nicolas

**Comment by skate2create** [comment]
Thanks Nicolas.
With that in mind, I may change my approach. My other option would be a nano, with the 5 rotary encoders, 5x3 button matrix which leaves 2 spare pins which I could use for a WS2801 RGB strip as a rev gauge. In your experience would that work on a nano or am I asking a bit much of the hardware?

**Comment by SHWotever** [comment]
Hum, something is concerning me, Arduino nano or mega can't emulate gamepad, only simhub will see the inputs, that's a lot of buttons just to control Simhub, is it your intention?

If you wan't gamepad emulation only arduino pro micro will do the trick, but it had less pins

**Comment by skate2create** [comment]
My intention would have been to have all buttons & rotary encoders working as a "gamepad" within windows, and after I'd posted my last message I saw the error when uploading the sketch regarding the nano not having USB joystick compatibility.
I suppose there is an option to run a pair of micros inside the wheel to a small USB hub as that would give me the required inputs for all the buttons and encoders, but would mean that I'd have 2 devices to run one wheel. My other option would be to run a bodnar SLI-F1 but it's very costly!
Unless you have another solution?
Picture of my wheel attached so it hopefully makes more sense!
![20191109_193904](https://user-images.githubusercontent.com/57807652/68991692-65211580-0859-11ea-9a5f-3d9fa928daf9.jpg)

**Comment by SHWotever** [comment]
As the micro/leonardo are the only arduino based boards supporting that, I have no solutions indeed except  two arduinos, you can eventually split display and controls and use an stm32 for controls using this : https://opensimhardware.wordpress.com/pedal-button-controller/, and it's a really good controller based on stm32

**Comment by skate2create** [comment]
Excellent, I'll look into it. Thanks Nicolas.

**Comment by skate2create** [comment]
Hi Nicolas, just wanted to say thanks for the tip about OSH.. all up and running alongside my TM1638 running through sim hub :D

**Comment by Borjec1** [comment]
> Hi ! Everything has a max :D, technically arduino memory is tight (sketch is universal and can fit many arduinos models and the smallest supported model determines what the sketch must fit. so I have to choose wisely how many instances of each feature I can add, I already raised this limit a couple of times for buttons, but with some hardware combos, it starts to be really really tight that's why I can't add more buttons for now. If you have 15 buttons, a matrix like 5x3 will do the job pretty easily. Warning, in a matrix setup you can't use multiple buttons at the same time, it must be known. you can see the wiring here : https://github.com/SHWotever/SimHub/wiki/Arduino---Button-matrix Nicolas

Hello. I understand that there is a limit, but i have one project right now, where are only buttons without anything. I need to put 17 buttons in 1 pro micro, they arent momentary, so matrix wont work. Can you please tell me how can i change the limit myself, if i can?
