### ISSUE TITLE
L'Editor Same formula doing different things

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#445]
Hi,

Have the same formula on two custom status led formulas and they do different things.

if([DataCorePlugin.GameData.NewData.CarSettings_CurrentDisplayedRPMPercent]>=6,0,

if(isnull([DataCorePlugin.GameRawData.Telemetry.dcStarter],0)=1,1,0))

Also getting a flickering true/false when starter is active but in the property list it shows steady true

**Comment by Meekstaaa** [comment]
Ok, I think it was my NCalc

**Comment by Meekstaaa** [comment]
Sorry!

**Comment by SHWotever** [comment]
Ah ah no problems :D it happens ;)
