### ISSUE TITLE
L'Editor Changed function

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#446]
Hi,

This one is real, I promise!

Looks like the 'changed' and by extension the 'inincreasing' and 'isdecreasing' functions aren't working with L'Editor. I'm just getting a constant true.

**Comment by SHWotever** [comment]
Hi ! I gave a try using speed or rpms and I get the expected result, Do you have the full formula and maybe the related replay if somehow it's really specific?

**Comment by Meekstaaa** [comment]
if(isnull([DataCorePlugin.ExternalScript.DaveFlags],1)=0,0,

if([DataCorePlugin.GameData.NewData.Flag_White]>0,changed(6000,blink('White Flag',250,1)),0))

That's the formula I'm using, works fine with the old led system but not this. (Ignore the dave flags that's my own one to ignore certain flags in certain situations)

If I change to this instead do you think it would be better:
if(isnull([DataCorePlugin.ExternalScript.DaveFlags],1)=0,0,

isincreasing(6000,blink('White Flag',250,[DataCorePlugin.GameData.NewData.Flag_White]>0)))

I don't have  a replay sadly

**Comment by SHWotever** [comment]
I may have an idea, does the effect is in a conditional group ? if somehow the parent is disabled the formula won't be evaluated (to save on CPU) so if the group becomes active at the same time as your formula it won't detect any change/increase/decrease as the first value encountered will be used as "reference value"

**Comment by Meekstaaa** [comment]
It's not in a conditional group other than 'game running' (Forgot to add, I was in spectator mode on iRacing when this happened)

It's also in a different profile that is attached to my iRacing profile.

**Comment by Meekstaaa** [comment]
Oh, I just did a race not in spectate mode and it didn't make a difference so don't think that has anything to do with it.

**Comment by Meekstaaa** [comment]
Oh also, I just realised. It wasn't blinking either. It was just solid so look like it was ignoring that part. Now I've re-read your statement I understand! Hopefully my new NCalc will work.

if(isnull([DataCorePlugin.ExternalScript.DaveFlags],1)=0,0,

isincreasing(6000,blink('White Flag',250,[DataCorePlugin.GameData.NewData.Flag_White]>0)))

?

**Comment by SHWotever** [comment]
Hi ! Just a followup I understood what was going on with the changed function,

if([DataCorePlugin.GameData.NewData.Flag_White]>0,changed(6000,blink('White Flag',250,1)),0))

the changed function is only evaluated when Flag_White is >0 so it will init only at this time with current value being "1" (so it's not detected as a change.) 
The best way to workaround that is to reorder to make sure changed is always evaluated :
```
changed(6000,blink('White Flag',250,1)),0) && [DataCorePlugin.GameData.NewData.Flag_White]>0
```
In this way it won't give you troubles.

The same applies to isincreasing :
```
isincreasing(6000,blink('White Flag',250,[DataCorePlugin.GameData.NewData.Flag_White]>0)))
&& isnull([DataCorePlugin.ExternalScript.DaveFlags],1)=0
```

**Comment by Meekstaaa** [comment]
Thanks! :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
