### ISSUE TITLE
ShellMacros - Running batch minimized

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#449]
Bonjour!
I'm playing with the CLI to send inputs to SimHub. I'm thinking of using a dash/overlay as a virtual button box dedicated to SimHub controls, including the new Shake It controls.

So i have "C:\Program Files (x86)\SimHub\SimHubWPF.exe" -triggerinputpress MyInput commands inside .bat files in my C:\Program Files (x86)\SimHub\ShellMacros folder.

When I map these to tactile buttons it works, but I'd like the bat file to run hidden or minimized.
I found a working tricks but it involve having calling the batch via a shortcut which is a bit cluncky.

Maybe I'm going at it wrong. I wonder if there is a cleaner/easier way. If so please let me know.
If not, could SimHub launch .bat file minimized either by default or as an option? 
Thanks in advance et bon dimanche!

**Comment by Romainrob** [comment]
Hi! I'm not done but it's getting there. :)

![Button test](https://user-images.githubusercontent.com/50543913/69911095-448abb00-1416-11ea-89b7-ac7965fa994a.gif)

This gave me a couple of suggestions ideas regarding the controls.
1. A ShakeIt calibration reset control mapping would be a nice addition.
2. The low fuel alert trigger value controls would make more sense to me with 0.1 lap steps than the current 1 lap.
Bonne journée! :)

**Comment by SHWotever** [comment]
Ha that's a huge loop indeed :D, i think the best solution is the one i used for SimDeck, simply give a name to the input in dash studio and be able to map it directly on any controls in simhub,
I will look for it :) (and additional controls too ;) )

**Comment by Romainrob** [comment]
That would be perfect! Thank you! :)

**Comment by Romainrob** [comment]
Re. I've done a bit more testing with the controls and here are some additional thoughts/suggestions/

These extra controls would be sweet :
1. Mute control for the global gain of ShakeIt Motors
2. Mute control for ShakeIt Bass Shakers
3. Thrustmaster wheel angle +/- controls

Back to the stepping of the increase/decrease controls, some of them are not adapted to this use case. Either, too much clicking or not fine enough control to my taste. To give a couple more examples, I wish the TM wheel FFB was 5 instead of 1 and the game volume 5 instead of 10. Je sais, je chipotte...
Idk what would be best. Having the option to change any of these may be too much clutter.
If the dash studio buttons could be long pressed and the steps set at 1, that would solve this.

In any case, thanks for considering these ideas.

Game volume controls are a really handy btw. I wish I noticed them earlier. Good bye windows mixer!:)

Oh and for a final nitpicking touch i noticed this small layout issue :
![image](https://user-images.githubusercontent.com/50543913/69918221-d246c480-146f-11ea-8c6a-e3360d6c2698.png)

**Comment by Romainrob** [comment]
Hi! Guess who's back for another round ;)
I've worked a bit more on my "control center" overlay today and I have yet a couple more suggestions/request.

1. Could we have multiple inputs binded to the new ShakeIT controls. I miss the "add" button.

2. Could the value (% and "Muted")in the overlay message be available as a property, as a flexible way to get the gain value of groups and effects when using the controls.
![Button test2](https://user-images.githubusercontent.com/50543913/69996049-8b310000-1551-11ea-9449-dd44813bf949.gif)

3. I doubt this is possible, but I'll ask anyway. I'd like to make the overlay "collapse" as you can see in the giant gif from a couple days ago. Visually, it works great but the whole overlay area stays "unclickable" (as in no click through possible) even when collapsed. Idk if there is a possible solution to this. I'm thinking of some a click through object we could place in the dash layout, and make active or not (using visibility binding maybe ?)

The more I mess with this, the more I think that having an overlay/dash of this kind by default would make sense. Especially if you keep adding more controls. It would be hard the decide what to include in it, since users have widely different setups. Maybe it could be splitted into screens/pages, so people could easily go in and disable what what they don"t need. I'll PM you mine if you want to check it or even reuse part of it if you like. Or not. No pressure.

Once again, thanks for considering these idea. Hopefully some of them you'll like and be doable.
Bonne fin de soirée à toi!

PS:Maybe we should rename the Ticket, I'm afraid I've completely derailled it. sry.

**Comment by SHWotever** [comment]
Just to resume the related action :
Already available : 
- Overlay message as a property, already available :
![image](https://user-images.githubusercontent.com/2207331/70173228-b727bf00-16d2-11ea-88c0-045960b457d2.png)

Possible :
- Make possible to assign an input name to a dashstudio button so it can be used directly as a simhub input. -> Done
- Global mute control for both ShakeIt -> Todo
- Fix layout issue in TM plugin -> Todo
- Multiple inputs for "dynamic actions" (shakeit) -> todo
- Settings for FFB controls steps -> todo
- Settings for game volume steps -> todo



Impossible : 
- Thrustmaster wheel angle +/- controls -> I won't do it, unlike gain, changing rotation kills ffb on most games when done with game running :( 
- Dynamic click trough : really too complex and glitchy :(

**Comment by Romainrob** [comment]
Hi! Thanks for your answer and pointing me to the notification properties. I'll make good use of these :)

**Comment by Romainrob** [comment]
Hi!
I remapped all my controls with the new custom buttons. It's much better. :)
Thanks you very much for that addition.

I have a couple more request/suggestions :

1. Would it be possible to affect these custom name inputs to control the widgets as well? I'm running out of action ABCD as I run more and more dashes/overlays.

2. I think it would make sense for the increment/decrement controls of Shake It to also unmute the effect/group/global when used. Especially since you're most likely adjusting levels "blindly" when using mapped controls.

Thanks once more for considering thees ideas.

**Comment by Romainrob** [comment]
One more detail. I just noticed the notification titles (thanks for adding it btw :)) say "Shakers" and "Motors" instead of "Shakers Power" and "Motors Power" when using the new shake It mute controls.

**Comment by Romainrob** [comment]
Hi again. This is a messy one.
You covered most it though. Thank you again for for all of that!
I think I'll close this one and reopen a cleaner one focused one the minor missing bits.
