### ISSUE TITLE
Needle on dial out of place

### ISSUE THREAD

**Issue by Kesh2430** [SHWotever/SimHub#453]
This issue only happened when I updated Simhub from 6.8.6 to 6.9.1. As you can see in the image, the needle exceeds the dial and boundary box. No changes has been made to the dashboard prior to updating Simhub so I don't understand what has caused this. This visual 'defect' only appears when the dashboard is running i.e open in a browser.

![Screenshot_1](https://user-images.githubusercontent.com/55858688/70340944-b5ccd280-1849-11ea-9c97-b1ad7396dad0.png)

**Comment by SHWotever** [comment]
Hi ! Could you send the dash you are using so I can check this particular case ?

**Comment by Kesh2430** [comment]
Link for dash: https://drive.google.com/file/d/11V-HGY54G8cuKEiJo_c2r4VJJnA1OsJZ/view?usp=sharing

**Comment by Kesh2430** [comment]
> Hi ! Could you send the dash you are using so I can check this particular case ?

Hi could you update me on this problem please?

**Comment by SHWotever** [comment]
Hi ! Sorry I did not came back to you ;) I will get it fixed for the next release ;)

**Comment by SHWotever** [comment]
Hi ! Sorry I did not came back to you ;) I will get it fixed for the next release ;)

**Comment by Kesh2430** [comment]
> Hi ! Sorry I did not came back to you ;) I will get it fixed for the next release ;)

Thank you for your quick reply, I look forward to the next release :)
