### ISSUE TITLE
Suggestion - Shake It "Do not output" option

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#454]
Hi! Guess who is back with another suggestion? ;)
Would it be possible for you to add a "Do not output" checkbox to the Shake It effects?
The idea is that most if not all the effects I export as properties need not to be outputted. Yet they are still visible in the custom mapping table, outputted by default and cluttering the view.
Thanks for considering the idea.
Bonne soirée!

**Comment by SHWotever** [comment]
Released ;)

**Comment by Romainrob** [comment]
Awesome! Thank you!
