### ISSUE TITLE
rF2 - "low fuel" LED's on constantly

### ISSUE THREAD

**Issue by benkayuk** [SHWotever/SimHub#455]
Hi,

Have a PSE DDU display/led and using the new LEDItor in the appropriate part of SimHub for DDU LED settings.

Using rF2, I have the left and right 6 LED's set to flash red with the trigger "Low Fuel (remaining fuel laps)".

However, this is being triggered constantly by the game data it seems, even with a fuel tank and e.g. 39 laps of fuel remaining shown on the SimHub dash display.

Why could this be?

**Comment by SHWotever** [comment]
Hi ! I've released the fix in the latest official version ;)
