### ISSUE TITLE
Dash Studio Crashing SimHub- Dial Gauge - Label Size Settings

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#457]
Hi.
I'm playing with a dial gauge and every time I try changing a "Label Size" setting, Dash Studio hangs and SimHub Crashes.
![image](https://user-images.githubusercontent.com/50543913/71316911-044cb480-2479-11ea-87c6-34a7caf399d4.png)

It seems it doesn't have time to log anything.
[SimHub.log.1.zip](https://github.com/SHWotever/SimHub/files/3992119/SimHub.log.1.zip)

I tried with a fresh new dash == Same issue.

Happy bug hunting! ;)

**Comment by SHWotever** [comment]
Well seen ! The value should not have been expandable.
