### ISSUE TITLE
Dash Studio dials gauges - 2 minor issues

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#460]
Hi.
While playing with dial gauge settings I noticed a couple of small issues:

1. The ScaleGlowRadius, is uncapped and I crashed/hanged SimHub a few time when entering a too large value:
![image](https://user-images.githubusercontent.com/50543913/71525774-90c10200-28d3-11ea-82cf-822b6d3a1c7c.png)

2. The minor ticks color won't change unless the previous major tick color changes. I'm not sure if this is expected. A couple of images to explain better:
Redline at 8050:
![image](https://user-images.githubusercontent.com/50543913/71525953-894e2880-28d4-11ea-83c5-f488d9329bd8.png)

Redline at 8000:
![image](https://user-images.githubusercontent.com/50543913/71525968-9f5be900-28d4-11ea-9556-daaa1b6dce91.png)

Bonne soirée!

**Comment by SHWotever** [comment]
I've released the fix ;)
