### ISSUE TITLE
SimHub crashes during gameplay (I stop feeling my bass shaker)

### ISSUE THREAD

**Issue by Brandonr757** [SHWotever/SimHub#461]
Playing various games but seems to happen most in DiRT Rally 2.0. My setup (for what's set up in SimHub) is a single bass shaker; sometimes I use my phone as a HUD but I'm not using any arduinos/other. Unfortunately I can't identify anything about this, I know I'm giving almost nothing here but it's as simple as the title says; I'm playing and during the race (seems to be a random time, there isn't an associated lag spike or anything) I'll stop feeling my bass shaker. If I check it (just run music into that source) the shaker is still working, but SimHub will not send anything after the crash happens (I can go to the software and navigate it, but hitting any of the "test" buttons does not do anything to the shaker and it crashes when I try to close it; have to use task manager to force-close it).
[SimHub.log](https://github.com/SHWotever/SimHub/files/4014544/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! 

Thanks for the report, I've seen a similar issue recently, I've fixed it this beta version : https://www.simhubdash.com/unofficial/SimHub.6.09.4b1.zip

If somehow it does not help, could you send me all the files available in the log folder ? Unfortunately, the log you sent is just after a Simhub startup and does not shows anything meaningful.

Let me know,

Best regards,
Nicolas

**Comment by Brandonr757** [comment]
Thank you so much, this solved the issue!
