### ISSUE TITLE
L'Editor & Dash studio improvements

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#463]
Hi,

Just looking at this now and I have an idea for the LED property.

Ability to just look at specific LED's you have mapped. I have my LED's shaped like in formula 1 and want to split them up into 3 pieces. 

1-3 left side
4-12 top
13-15 right side

Top work as usual though! :)

**Comment by SHWotever** [comment]
Hi ! Unfortunately after all those years this request remained completely unique. I close it for readability purpose even if the the feature would be interesting.
