### ISSUE TITLE
Controls Mapping - Dynamic target

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#464]
Hello there! :)
Someone ask me about this, an now I wan't it too.
I'm looking for a way to map a physical button to execute a ahk script dynamically.
It's for a refuel button. I have one script per fuel quantity and I want the button to trigger the right script according to fuel calculation.
I've done that before with a tactile button on my dash, but gloves gets in the way. In this case I used an ncalc formula to define which script to run.
I thought about having my button triggering an ncalc script, that would execute the correct ahk script but failed. I don't even know if i can use ShellPlugin.Run from ncalc.
Is that possible? And what would the syntax look like?
Or may there is another way I couldn't think off? If so, could point me toward it please?

**Comment by SHWotever** [comment]
Hello !

I've added the triggeraction function for the next version,

It's likely to be used in JS with some conditions

Don't repeat the following example if you don't want to lose you ears ;)
![image](https://user-images.githubusercontent.com/2207331/81466891-4468c580-91d5-11ea-9443-13f996d24162.png)

**Comment by Romainrob** [comment]
Hi.
Sweet! Thank you! 
This should do the trick. And it opens the door to some cool stuff :)

**Comment by Romainrob** [comment]
I made my auto adjusting refuel button script, quickly tried it in practice and it worked nicely.
Awesome! :)
On a side note, I noticed the triggeraction function doesn't appear in the function list. Maybe it's on purpose. I thought I'd mention it.

**Comment by SHWotever** [comment]
Woops ;) Forgot it, it's fixed ;)
