### ISSUE TITLE
[Feature Request] xbox one controller battery level

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#468]
Hi. And one more to add the never ending list:)

Could you please add a xbox one controller battery level property?

I tried to use Xinput in a plugin but didn't get far. It looks somewhat simple from the outside... not enough for my "skills".

Thanks for considering the idea et bonne soirée.

**Comment by SHWotever** [comment]
Désolé je serais coincé pour le même raison que #553 :( , du coup ça ne sert plus à rien de la garder

**Comment by Romainrob** [comment]
Tkt. Je comprends. Merci qd même.
