### ISSUE TITLE
NCalcScripts .ini files not being loaded. Fresh installation

### ISSUE THREAD

**Issue by ValokAsura** [SHWotever/SimHub#469]
I noticed that my .ini file in the NCalcScripts doesn't get loaded anymore after an uninstall/update.

I installed a fresh copy of 6.9.5 after removing the old installation by going through the instructions on https://github.com/SHWotever/SimHub/wiki/SimHub-Troubleshootings. Everything was removed to prepare for a fresh installation. I put a backup of my ini into the new NCalcScripts folder and it no longer loads on startup. I downloaded a few examples from the discord that I knew worked from previous experience and they wouldn't work either.

I re-installed a second time and have the same issue. A link to the debug mode log and reference screenshot are attached.

I have installed to X:\SimHub

https://image.prntscr.com/image/4TL-5yxjSkmtzCoPIcwGww.png
https://pastebin.com/X8VRm6tj

I cut the log short as the ACC errors just go on forever at that point.

I hope this isn't just me being an idiot and out of touch, as it worked fine a few months ago, which was the last time I used SimHub.

Thanks for your time and awesome program!

VoiD#7859 on Discord

**Comment by SHWotever** [comment]
Hi ! Could you check if the "arduino plugin" is still running ? "NcalcScripts" are handled by this plugin (it was originally designed to add leds capabilities, if the plugin is not running it won't be executed.

Let me know if it helped,
Nicolas

**Comment by ValokAsura** [comment]
Good call, sir. I had disabled the arduino plugin since I don't use it, or, didn't think I did, hah!

Thank you for your time in helping me with this.
