### ISSUE TITLE
overlay editor auto minimise

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#473]
Hi,

Just started to use the overlay editor and noticed that when I set it to auto load on startup the editor widget auto maximises. Any chance to have an option where we can have it auto hide?

**Comment by SHWotever** [comment]
Yeah it's possible you will find the option here :)
![image](https://user-images.githubusercontent.com/2207331/75114983-f541d880-565a-11ea-93f8-54b6d14125bc.png)
