### ISSUE TITLE
Shake It - Custom channel mapping intermitent issue

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#477]
Hi.

Las t week I reworked my shaker installation and moved from 2 sound cards in 4 channel mode to a single card in 7.1 mode.

While remapping everything, I noticed sometimes, if I untick an effect in the table, the effect won't actually be removed from the channel until the effect is deactivated/reactivated or the replay restarted. Most of the times it works just fine. I guess it could be related to the number of channels since I never noticed this with the 4 channel mode.
Also I'm using the popped out window for the table fyi.

I don't see anything obvious in the log.
For example I had this issue again today before restarting the replay at 
[2020-01-28 20:12:36,527] INFO - Replay mode : Replay

Really not a big deal but I thought you may want to know about it.
Bonne soirée.

[SimHub.zip](https://github.com/SHWotever/SimHub/files/4124248/SimHub.zip)

**Comment by Romainrob** [comment]
Hi! I just noticed you tagged this one as done.
Do you want me to try testing this?

**Comment by SHWotever** [comment]
If you can yes that would be nice, I admit this one was tricky, I was able to reproduce it consistently, I made a few changes then was not able to reproduce it anymore. But I could not locate exactly the origin, I only added some safety countermeasures considering what I was able to see then it stopped.

**Comment by Romainrob** [comment]
It looks good on my end too.
I spent 15-20 min messing with the mapping and it the issue didn't occur.
I think it's pretty safe to consider it fixed, so thanks for the fix :).
