### ISSUE TITLE
Usbd480

### ISSUE THREAD

**Issue by romarin84** [SHWotever/SimHub#478]
Hello , 
I’m work on the usbd480 screen and is not possible to make appears a dash picture 
I have enable the screen the number serie are ok and available but when i ask to show me the picture i have this on the screen

![ADCAAC85-FCA6-4C7A-A885-8B91ADEFED05](https://user-images.githubusercontent.com/18055811/73441026-a2724b00-4352-11ea-83fe-0c16b39a0758.jpeg)
![78345C6F-C131-4E02-B970-FE9D700197A0](https://user-images.githubusercontent.com/18055811/73441027-a2724b00-4352-11ea-8787-7e03386f1a21.jpeg)
Really thank you for your help 
Romain Seignour

**Comment by SHWotever** [comment]
Hi ! 
Usually when this happens there are 3 common reasons :
- Bad or badly insulated usb cable.
- Bad drivers or not correctly installed, make sure to reinstall the latest drivers from the screen manufacturer, usually when buying the screen LCDInfo gives to you the official drivers , I had some troubles in the past after some major window updates requiring drivers reinstall.
- Lack of power or bad usb hub, If you are using any usb hubs, make sure to avoid them (at least to unsure it's not causing the issue)

Simhub is bit more intensive with the screen compared to "competitors" software and will reveal more easily hardware issues.

Let me know if it helped, 

Best regards, 
Nicolas

**Comment by romarin84** [comment]
Hello Wotever,


  *   I have test with 2 different cable
  *   the demo of the screen send it with the screen are ok i see all the demo correctly and the driver are send by lcdinfo henri is a cool guys  ^^
  *   when i change th image start up all is ok
  *   in simhub when i down the brightness screen it move the brightness
  *   when i disable the screen in simhub the screen power off
  *   when i put a dashboard inside nothing to do
  *   when i look the screen i see one lateral scroll bar and one ligne in the center of the screen
  *   i have check my power voltage is ok

I don't know where is a probleme in a simhub log all is ok 1 display found and connectée simhub show me the serial number and all is ok

pfiouuu i'm tied but is not finished i have start to create my wheel on 10 Décember i have really enjoy is finishhhhhhh lol

i have configured my arduino for 22 led the program are really perfect for control arduino all is ok

i'm wait your idea  ^^
have a great day
Romain Seignour

________________________________
De : Wotever <notifications@github.com>
Envoyé : jeudi 30 janvier 2020 11:54
À : SHWotever/SimHub <SimHub@noreply.github.com>
Cc : romarin84 <dj84bataclan@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [SHWotever/SimHub] Usbd480 (#478)


Hi !
Usually when this happens there are 3 common reasons :

  *   Bad or badly insulated usb cable.
  *   Bad drivers or not correctly installed, make sure to reinstall the latest drivers from the screen manufacturer, usually when buying the screen LCDInfo gives to you the official drivers , I had some troubles in the past after some major window updates requiring drivers reinstall.
  *   Lack of power or bad usb hub, If you are using any usb hubs, make sure to avoid them (at least to unsure it's not causing the issue)

Simhub is bit more intensive with the screen compared to "competitors" software and will reveal more easily hardware issues.

Let me know if it helped,

Best regards,
Nicolas

**Comment by SHWotever** [comment]
Hum, I see a last clue, maybe the webserver is blocked by something (the dash uses a little webserver)
could you try to show a dash in a classic browser on your computer using the following address http://127.0.0.1:8888/ ? The usbd480 uses the same way to show the dash.

I would still be interrested by the full log files as it could give me some additional clues.
