### ISSUE TITLE
LEDitor - Clear background when active - Offset

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#480]
Hi,
I noticed something strange with the "Clear background when active" feature.
It seems to add an offset when checked.

![image](https://user-images.githubusercontent.com/50543913/73855010-b7a81780-4833-11ea-8abb-4f7c1ef12cae.png)

![image](https://user-images.githubusercontent.com/50543913/73855046-c5f63380-4833-11ea-8c1b-986a548e9cb4.png)

[Any Game - Background clearing test.zip](https://github.com/SHWotever/SimHub/files/4160289/Any.Game.-.Background.clearing.test.zip)

Bonne journée.

**Comment by SHWotever** [comment]
Well seen ! This one was really sneaky as most of my tests were on start position 1, and in this case it wasn't happening :D, 

It's fixed for the next version !

**Comment by Romainrob** [comment]
Great! :)
Thank you Sir!
