### ISSUE TITLE
F1 2018 from Microsoft Store

### ISSUE THREAD

**Issue by EngBitsCH** [SHWotever/SimHub#482]
Hi! I have the game F1 2018 from Xbox Gamepass, and I'm trying to connect with Simhub, but the software show that the game is "Disconnected".

**Comment by SHWotever** [comment]
Hi ! I never experienced Xbox game pass it's know to have issues with telemetry , I guess you will need to configure the game manually (you can see the wiki about getting it configured manually : https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#manual-game-configuration

You may also need to disable Microsoft store security preventing network communication (telemetry is sent using udp) , by using the same procedure described for Forza games : https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#forza-horizon-4--motorsport-7

Let me know if it helped,
Nicolas
