### ISSUE TITLE
SimHub Freezes when switching to Forza Horizon 4/ FM7 on windows 7

### ISSUE THREAD

**Issue by elektryk157** [SHWotever/SimHub#483]
Simhub Freezes when I switch to Forza Horizon 4

This also happens when I try to switch to Forza Motorsport 7. I don't have one of these games on my computer, but I need to switch to FH 4 to be able to use another program. 

At the beginning I thought that it is because I have Windows 7 and FH4 is only on Win10, but I can easily switch to GRID 2019, which also requires Win10. I apologize in advance for my English but I use google translator.

**Comment by SHWotever** [comment]
Hi ! 

Could you join the log files after switching to fh4 or motorsport ? they are available in "c:\Program Files (x86)\SimHub\Logs"

Nicolas

**Comment by elektryk157** [comment]
Here is the log file
[SimHub.log](https://github.com/SHWotever/SimHub/files/4187599/SimHub.log)

The program for which I need to switch to FH 4 is TS-Telemetry. This program reads telemetry data from Train Simulator 2019 and then sends it to SimHub via the FH4 plugin / module (I don't know what it's called).

**Comment by SHWotever** [comment]
Hi ! The new version with the fix has been released ;)
