### ISSUE TITLE
E36 Cluster Fuel Gauge Problem

### ISSUE THREAD

**Issue by Autosim112** [SHWotever/SimHub#484]
Hey,
I built a E36 Cluster, which works really nice. But there is one Point which is annoying me. The Fuel Gauge is set up and works when you start the game. But after a few minutes, or when you accelerate the Gauge is turning to zero, even though the Output isn't zero. The Gauge setup is right and on the 5th arduino pin. I calibrated also the max between 100-162 PWm.
Can someone help or have any ideas?

Greetings from Germany,
Daniel

**Comment by SHWotever** [comment]
Hi !

Have you followed the exact pinout suggested on the wiki (https://github.com/SHWotever/SimHub/wiki/BMW-E36-Cluster-Setup#arduino-pinout) when combining the 3 gauges you must respect it or you will get similar conflicts. 

Nicolas

**Comment by Autosim112** [comment]
Hi, yes i did it the exact same way!

Daniel
