### ISSUE TITLE
RBR NGP 6 Telemetry 

### ISSUE THREAD

**Issue by Rando993** [SHWotever/SimHub#490]
I have a feature request for Richard Burns Rally Next Generation Physics 6. It is the physics model that most people use and also the CZ tournaments plugin uses so you could say its pretty much the standard for RBR these days.
I found documentation for a plugin that provides telemetry data for SFX-100 actuators. According to that  NGP 6 provides much more telemetry data through UDP port. 
That being said i have not checked it myself if those parameters are actually provided.

I attached the file file with the the list of parameters.
[Values.txt](https://github.com/SHWotever/SimHub/files/4235832/Values.txt)

Edit: typos

**Comment by SHWotever** [comment]
Hi ! 

Thanks for the suggestion, RBR which has many many mods available aside from NGP6. I will look if it's possible, but since RBR  has many mods available this particular mod is only concerning a very small part of the users.

**Comment by paskalip** [comment]
+1

The most important (for me) with the new physics are tyre and brake temperatures. It would be great to have these live in a dashboard, as the car handling changes over the course of really long stages.

Also, the values above are the structure of the logged telemetry and not the UDP. This is the UDP structure scripting file [rbr.telemetry.data.TelemetryData.h.txt](https://github.com/SHWotever/SimHub/files/4732938/rbr.telemetry.data.TelemetryData.h.txt), but best is to see the whole project here:
http://www.ly-racing.de/viewtopic.php?t=7878&sid=d2101a5f2f9af2696b9004564de6cf7d

**Comment by troffeo** [comment]
Hi,
Also I have a feature request for RBR NGP 6.
The most important to use all that feature who provide the telemetry data from the NGP 6 is the UDP.
The new telemetry data for RBR and NGP 6 has many parameters as tire temp, tire wear, engine temp (at least 2 different temps) etc.
So I'ii like to have at the future a dashboard who has everything needs to drive with it.
Please let UDP as a choice for RBR NGP 6.

**Comment by SHWotever** [comment]
Hi ! The update support NGP6 has been released, have fun !
