### ISSUE TITLE
SimHub not picking up ACC dash boards

### ISSUE THREAD

**Issue by seandevlin883** [SHWotever/SimHub#491]
![acc 1](https://user-images.githubusercontent.com/61352388/75092965-3069dc00-5575-11ea-995d-02546a46eed2.PNG)
![acc 2](https://user-images.githubusercontent.com/61352388/75092968-32cc3600-5575-11ea-91e6-f5d07fd3d96a.PNG)
I can,t get simhub to work with ACC. its fine with Assetto Corsa etc. I have also included two srceen shots that might help. Many thanks Sean devlin

**Comment by SHWotever** [comment]
Hi !

Indeed this Simhub version is outdated and the game have been changed many time since. Do not hesitate to update simhub first : https://www.simhubdash.com/download-2/ and everything should work fine then. 

Best regards,
Nicolas+
