### ISSUE TITLE
Possible to connect a 12 pin rotary switch to an arduino nano and program in SimHub?

### ISSUE THREAD

**Issue by robin2346** [SHWotever/SimHub#494]
Hi, 

I was wondering if it's possible to connect a 12 pin rotary switch to an arduino nano and program it to work via SimHub. In the list I only see rotary encoders.

If this would work, any advise on how to set this up?

Thanks,

Robin

**Comment by SHWotever** [comment]
Hi ! 

I'm afraid it's not supported, most (if not all games) only supports momentary switches (simple press buttons). On another side if you want to interact with games using momentary switches, going to arduino pro micro will be a better choice as it natively supports gamepad emulation unlike nano, mega or other similar boards. When using nano or similar boards, input will be only seen by Simhub, not the game.

Nicolas

**Comment by robin2346** [comment]
Hi Nicolas,

Thanks for the prompt reply! I was thinking to use one of those button
boards of leo bodnar as the seem to support the rotaries.

With regards to the arduino micro pro being recognized as a gamepad
emulator, do you think its possible to transfer data via HC05 bluetooth
modules instead of using an usb cable? I tried this with the nano but that
didnt work. I think you managed to transfer led data wireless correct (at
least I saw a short youtube video).

Thanks,

Robin

Op zo 23 feb. 2020 om 09:40 schreef Wotever <notifications@github.com>

**Comment by SHWotever** [comment]
I've experimented HC05, unfortunately it has an unacceptable latency no matter what i tried, the video you have seen was a quick test during these experiments, unfortunately it was unstable and slow.

**Comment by robin2346** [comment]
Hi Nicolas,

I'm trying to upload a sketch on my Arduino Pro Micro via Simhub. However
in the process I continue to see the below error message. Do you know how I
can fix this?
[image: image.png]

Thanks a lot in advance for your help!

Happy holidays and kind regards,

Robin Hermans
