### ISSUE TITLE
How to show absolute from (positive or negative) value

### ISSUE THREAD

**Issue by basthard300** [SHWotever/SimHub#495]
Hi, assuming I'm a beginner,
in SIMHUB EDITOR I am finding it difficult to have as a result the absolute maximum value both negative and positive during telemetry as regards the gravity acceleration value in ACC.
The reference value is: [EnsiFerrum_ACC_Physics.accG_Z]
with the format '0.00'
If anyone can help me, I would like a formula that would give me a constantly updated value, with the absolute max value obtained in that session.
the value should be entered in the red box
Thanks so much
![simhub](https://user-images.githubusercontent.com/61467596/75264139-44207700-57ef-11ea-8490-a495b27511fd.png)

**Comment by SHWotever** [comment]
Hi ! To get the absolute of a value you can simply use the abs function
```
abs([EnsiFerrum_ACC_Physics.accG_Z])
```
Nicolas

About max it's not possible currently to hold it for a specific session using simple ncalc script. Plugins will allow to do to it, but it's a more complex process.

Nicolas

**Comment by basthard300** [comment]
tks for now
Paul
