### ISSUE TITLE
ACC Properties - Delta + Time Of day + Engine Map

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#497]
Hi,
Here are a few oddities I noticed with ACC properties.

1. PersistantTrackerPlugin.SessionBestLiveDeltaSeconds seems to be rounded or truncated. Its' always a value in round seconds. (on the latest beta)

2. DataCorePlugin.GameRawData.Realtime.TimeOfDay is accurate but in a weird format
I had to use this to "fix" it:
secondstotimespan(timespantoseconds([DataCorePlugin.GameRawData.Realtime.TimeOfDay])*1000)

3. DataCorePlugin.GameRawData.Graphics.EngineMap seems to always off by 1 for some reason
[DataCorePlugin.GameRawData.Graphics.EngineMap]+1 matches the ingame value.

Bonne journée.

**Comment by Romainrob** [comment]
Hi.
I just noticed the delta in ACC is working properly now on 6.8.9 :) Awesome!
This was the most in your face/annoying of the 3. The other 2 can be worked around.
Idk know if you want to change them after all. It could mess with existing dash (thinking about Ensi dash pack). Do as you please with the ticket.
Thank you for this.

**Comment by Romainrob** [comment]
Ok. Je réalise enfin ma co***rie
Je m'étais planté de propriété pour le delta... C'est pourtant dans le nom "seconds"
J'imagine qu'il marchait bien tout du long, depuis que tu l'as remappé.
Sorry

**Comment by SHWotever** [comment]
Hello ! Tu n'avais pas faux ;) SessionBestLiveDeltaSeconds était méchamment arrondi car le session delta du jeu l’était aussi, j'ai corrigé ;)
Pour EngineMap j'en ai profité pour ajouter la propriété dans newdata version corrigée.
Pour le time of day je n'y ai pas touché, je verrais pour rajouter une propriété standard dans le futur.
Basiquement tout ce qui est rawdata ne peux pas être touché, ce sont les données comme elles viennent du jeu sans modification possible.

**Comment by Romainrob** [comment]
Très bien! 
Merci et Bon Week-end!
