### ISSUE TITLE
Overlay visibility toggle - Button mapping issue

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#500]
Hi.
After testing the new Overlay visibility toggle, it appears the feature works but the button mapping mapping doesn't.
The mapped button does nothing but right click / trigger now does.
Running 6.9.8b1
Bonne journée.

**Comment by Romainrob** [comment]
Hi. 
I just noticed this while remapping all my controls:
![image](https://user-images.githubusercontent.com/50543913/76972920-8a20b480-692f-11ea-8c53-11426ead1912.png)

**Comment by SHWotever** [comment]
Oh ! Thanks for the info, that was my missing information, I could not reproduce it yet. Will makje the fix easy this time ;)

**Comment by Romainrob** [comment]
Nice! I'm glad it helps.

**Comment by SHWotever** [comment]
Hi ! I released the fix in the last public version is it ok for you now ? It wasn't happening in all conditions and I couldn't reproduce it but considering the error I hope I nailed it :D

**Comment by Romainrob** [comment]
Hi.
I missed that released. I'm still on the b3.
I'll update later today and report back.
Thanks

**Comment by Romainrob** [comment]
Yes! You nailed it:)! 
It's working just fine on my end now.
Well done and thank you once more :)
