### ISSUE TITLE
LCD 20x4/16x2 display of gear across multiple lines

### ISSUE THREAD

**Issue by sjdawson** [SHWotever/SimHub#501]
Not sure of the feasibility with existing LCD controls, but I stumbled upon this video and thought it had a really neat way of displaying gear on an LCD display:

https://www.youtube.com/watch?v=HFh1zECXefE

![image](https://user-images.githubusercontent.com/1701603/75765713-d537a680-5d37-11ea-8c4e-d11e9b43bbfc.png)

**Comment by SHWotever** [comment]
Hi ! Unfortunately, I can't add this, this requires custom fonts loading and dedicated display design which goes totally to the opposite of the current "screen designer" which gives good freedom.

**Comment by sjdawson** [comment]
Ah, not to worry then. 👍
