### ISSUE TITLE
OutOfMemoryException 

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#503]
Bonjour Wotever :).

I've been running into some OutOfMemoryException lately.
Running v6.9.8b1

I'm pushing Dash Studio pretty hard and some of my scripts may be janky so I could be to blame.
Still I thought these may reveal something of interest to you.

[Logs.zip](https://github.com/SHWotever/SimHub/files/4296228/Logs.zip)

Bonne journée.

**Comment by Romainrob** [comment]
Hi.
I just had another one.
I wasn't messing with my heavy dash this time.
[SimHub.zip](https://github.com/SHWotever/SimHub/files/4301252/SimHub.zip)
Bon Week end.

**Comment by Romainrob** [comment]
Salut.
J'espère que tout roule pour toi.
Je reviens t'embêter avec mes ptits pb.
Et je te la fais en français cette fois.

J'essaie de chasser les erreurs générées par mon dash pour voir s'il est la cause de la fuite de mémoire et de pb de pertes de connexion avec les dash en wifi. Rien de définitif jusque-là. Je n'arrive pas à mettre le doigt sur ce qui met le bazar... Pour être honnête ma compréhension des logs reste limitée. 

Dans la manoeuvre j'ai activé le debug mode pour creuser un peu plus et je remarque que j'ai un flot constant de 2 types d'erreurs:

![image](https://user-images.githubusercontent.com/50543913/76446201-fe56d780-63c6-11ea-820c-2f7ce181b006.png)

Je ne constate pas d'anomalie pour autant coté arduino à l'usage.
Et je ne sais pas quoi penser de cette erreur de ficher manquant.

Question 1 :
C'est grave docteur?  Ou je coupe le mode débug et peut ignorer ces erreurs?


Coté perte ce connexions, pour le contexte j'utilise 3 dash en mm temps sur 3 tablettes. Les coupures  se produisent essentiellement avec le nouveau dash ouvert, mais ça affecte aussi les autres à ce moment là Pas forcément tous en mm temps. Si je ferme le nouveau dash en charge un plus léger à la place, tout est bcp plus stable.

![image](https://user-images.githubusercontent.com/50543913/76446821-e7fd4b80-63c7-11ea-870c-194021173f6a.png)

J'ai aussi l'impression que mon nouveau dash a aussi tendance à trigger ce type d'évenement : [WatchDog] Abnormal Inactivity detected

Ici le log de ma dernière session (sans le débug mode)

[SimHub.zip](https://github.com/SHWotever/SimHub/files/4319843/SimHub.zip)

Question 2 :
Est-ce que ces elements te permettent de me sugérrer une piste?
Je me demande si le dash est juste trop lourd (bien que si je comprends bien, un fois charger sur la tablette ça ne devrait avoir d'incidence coté PC?)
Ou alors j'ai un script mal foutu. Ce que je soupçonne. Derrière le dash il y un script ncalc et un autre JS qui font référence l'un à l'autre. J'ai déjà générer des références cycliques par le passé mais là c'était un crash/freeze instantané. Cette fois ça à l'air plus "subtil".

Peux m'apporter tes lumirères sur le sujet stp? Rien d'urgent evidement.
Merci d'avance et bonne soirée.
PS: Dsl pour le pavé...

**Comment by SHWotever** [comment]
Hello ! J'avais commencé a analyser les logs il y a quelques jours mais je n'ai pas encore eu le temps d'arriver jusqu'au bout de l'analyse, je soupçonne de trop nombreuses générations de cartes pour la fuite de mémoire ou éventuellement le fichier de calibration de shakeit qui a pris trop de poids, je sais que je peux améliorer des choses de ce côté là. Concernant les cartes est-ce que le dash en présence plusieurs ? Peut-être trop de cartes sur un même dash ?

Concernant le unauthorized rien d'inquiétant ce sont juste des tentatives de connexion échouées car le port est déjà utilisé. La deuxième erreur est liée simplement a la tentative de connexion a la télémétrie, encore une fois la seule façon de savoir si elle est disponible est de "tenter", et éventuellement échouer.

Je vais jeter un œil sur les derniers logs rapidement, je suis sur mon mobile et c'est pas facile de regarder :D

**Comment by Romainrob** [comment]
Ok. Pas de soucis. Fais ça quand ça t'arrange.

Je te confirme que le dash à plusieurs map (2 sur l'écran principal mais seulement 1 visible à la fois, "au choix" et 1 autre sur l'écran des pits). Je vais essayer en masquant les 2 de l'écran principal. Ou si les rendre non visibles ne suffit pas, je testerai en les supprimants.

Concernant le fichier de calibration de shakeit, si ça peut te donner des billes, j'ai ça:
![image](https://user-images.githubusercontent.com/50543913/76452093-cbb1dc80-63d0-11ea-9273-69f6fb3b0798.png)
En espérant que ça soit les bons fichiers.

Du coup je ne m'alarme pas de erreurs que je vois en mode debug. Parfait!
Merci pour ta réponse :)

**Comment by Romainrob** [comment]
Salut.
Agent Romainrob au rapport ;)

Pour infos. Pour les pertes de connexions je pense que ça venait de ma box en fait. Hier soir, j'ai remarqué que j'avais des micro freezse en wifi , genre tte les 2 sec,  que j'avais pas en html localement. Aujourd'hui j'ai fait un full reset  + dépoussiérage de la box et maintenant c'est plus fluide et finis les coupures. :) En espérant que ça dure...

Sinon, j'ai viré les maps du dash et jusque là RAS. A suivre...

Bonne soirée.

**Comment by SHWotever** [comment]
Ah nice ! J'ai déja rencontré çà plusieurs fois avec ma box perso (sfr) et d'autre utilisateurs. Effectivement des les logs je voyais effectivement un blocage "réseau" (qui déclenchait le "watchdog") qui était suivi de la déco de tout le monde (a cause d'un timeout). Reste a résoudre le problème de mémoire :D

**Comment by Romainrob** [comment]
Hmmm. Ok j'éspère que ça ne reviendra pas.
C'est une box SFR. Elle m'a aussi déjà fait perdre du temps suite à une maj foireuse qui forçait le bloquage certains traffics. Heureusement pour moi, je ne sais pas écrire les moteurs de communication... :)

**Comment by Romainrob** [comment]
Salut,
De retour avec une nouvelle fuite de mémoire et des suppositions

[Logs.zip](https://github.com/SHWotever/SimHub/files/4365473/Logs.zip)

Info à prendre avec des pincettes; J'ai l'impression que c'est lié à l'utilisation de dash studio.
Ça se produit souvent au moment de fermer dash studio, et ça bloque sur l'écran "saving". Un peu stressant...
Celà dit, cette fois ci, ça s'est produit à l'ouverture de dash studio. J'imagine que ça dépend de ce qu'on fait au moment où on approche de la limite. Mais, pour ce que ça vaut, d'une façon générale il ne semble pas avoir eu OutOfMemoryException les jours ou je n'édite pas de dash.

En jeu, c'est rare pour moi. Et j'ai ptet déjà bourré la RAM en editant un dash avant de jouer.

Concernant la génération abusive de maps, est-ce que çà pourait venir de l'usage de certains replays?
Genre des replays courts, contenant un passage sur la ligne d'arrivée?

Bon dimanche à toi!

**Comment by Romainrob** [comment]
Re. J'ai fais qq tests.

Ouvrir et fermer dash studio en boucle augmente l'utilisation mémoire jusqu'a l'erreur.
Générant la map 6 fois à chaque ouverture.

J'imagine que c'est ce qui m'arrive, au fils de heures, les jours ou je bricole mes dash.

[SimHub.zip](https://github.com/SHWotever/SimHub/files/4365509/SimHub.zip)

Un gif en prime :)
![Bourrage de RAM](https://user-images.githubusercontent.com/50543913/77253757-b81e3580-6c5c-11ea-88f1-cc29a6dfaa7f.gif)

Sur ce je te lâche la jambe. Bonne journée.

**Comment by SHWotever** [comment]
hello !
Je me suis fait une grosse passe la dessus sur la dernière beta, je ne suis pas 100% certain d'avoir tout tué, c'est extremement difficile à diagnostiquer, mais çà à l'air beaucoup mieux

**Comment by Romainrob** [comment]
Salut!
J'ai refait mon "stress test" avec l'éditeur et ça tient bon. Avant c'était systématique au bout d'un moment. Là même en insistant bien ;), c'est stable. Je vois que l'usage mémoire descent à la fermeture, contrairement à avant. Ça m'a l'air tout bon. 
Bien joué et merci pour la beta pleine de goodies :)

**Comment by SHWotever** [comment]
Merci pour le feedback !
