### ISSUE TITLE
Tire Pressure

### ISSUE THREAD

**Issue by INTIMID883R** [SHWotever/SimHub#504]
Just to let you know that in iracing, the tire pressure's for the rear tires are crossed (LR tire pressure is shown on RR and RR pressure is shown of LR). Not sure if it is in your software or iracing software. maybe you can check it out.
![Screen Shot 008](https://user-images.githubusercontent.com/61875319/76088634-f25db680-5f7d-11ea-97e8-1696a42c20da.JPG)

**Comment by Romainrob** [comment]
Hi.
I just had a look and the value were correct.
![image](https://user-images.githubusercontent.com/50543913/76093414-332aef00-5fc1-11ea-8ce4-4715a9c07bdc.png)
I suspect this is a car specific issue on iRacing side.
What car were you driving?

**Comment by INTIMID883R** [comment]
Thanks for your reply. I am driving the Chevrolet Camaro ZL1. Later today I
will test some of the other cars and see if they are the same. Makes it
difficult to adjust pressure if one can't rely on what pressure one is
starting with.

This may be a dumb question, but is there an app out there somewhere that
would suggest the correct pressure adjustments after running a 10 lap test??
Thanks again
Tony

**Comment by Romainrob** [comment]
The test above was with Mustang cup car. I don't have the Camaro to check.
I don't know of any apps doing what you described.

**Comment by SHWotever** [comment]
Hi ! Indeed I double checked values are properly mapped, but I know that IRacing cars telemetry "plumbing" is a bit manual and errors regularly happen in telemetry. I guess this should be fixed soon by Iracing devs.
