### ISSUE TITLE
Iracing fullscreen problem

### ISSUE THREAD

**Issue by m4s3r** [SHWotever/SimHub#509]
When i have iRacing open with an overlay in windowed mode everything is fully worked.
The problem comes if i make iRacing running fullscreen, my overlay disappear.
Any solution?

Sorry for my bad english.

**Comment by SHWotever** [comment]
Hi ! It's normal indeed, it requires to be in windowed or borderless windowed mode : https://github.com/SHWotever/SimHub/wiki/Dash-Studio-Overlays#game-requirements

Nicolas
