### ISSUE TITLE
USB480 - connection issue  

### ISSUE THREAD

**Issue by N4styVillian** [SHWotever/SimHub#511]
Hi, I am using the latest version of SimHub and using this with SImRacingHardwares GeforceLed screen (USB480).

I am running the latest software and also installed the latest drivers; I've gone through un-installing and installing both but can't get SimHub to send data using the USB480 option.

[Logs.zip](https://github.com/SHWotever/SimHub/files/4361389/Logs.zip)

**Comment by SHWotever** [comment]
Hi ! Thanks for the log, I can see that the screen is properly detected but I can't see any incoming connections, could your review the followinf troubleshooting guide ? https://github.com/SHWotever/SimHub/wiki/Troubleshoot-Dashstudio-Web-access#how-to-access-dashboards-from-tablets-phone-or-remote-computer-browser
USBD480 is relying on the same access to work.

Let me know if it helped, 
 Best regards,
Nicolas

**Comment by N4styVillian** [comment]
Hi Nicolas,
I changed tried http://127.0.0.1:8888 and nothing happened (no server load)
then changed it and tried http://127.0.0.1:10010 it is now loading. So is
it ok to leave it like that? Is it safe?
Thanks

Laud

**Comment by SHWotever** [comment]
Hi ! Thanks for the feedback, it means something was blocking the port (firewall, antivirus, another application ..)
No there is no problems keeping that port.

Nicolas
