### ISSUE TITLE
[Bug] LED RPM (0 to 100%) Dimming when all using current colour not working

### ISSUE THREAD

**Issue by sjdawson** [SHWotever/SimHub#514]
When setting "Use current color for all LEDs" on the "RPMS (0% to 100%)" effect, then "Use dimming" stops working.

**Comment by SHWotever** [comment]
Hello this will be fixed for the next version ;)

**Comment by sjdawson** [comment]
Awesome stuff, I miss using this option.

It a case of reuploading Arduino sketch?

**Comment by SHWotever** [comment]
No no it's software side this time ;)
