### ISSUE TITLE
Moving text on LCD + I2C

### ISSUE THREAD

**Issue by danfeliix** [SHWotever/SimHub#516]
Friend see this video, would it be possible to add this resource? Moving text? It would be ideal for names longer than 20 characters

[https://www.youtube.com/watch?v=8rPyydCnTUM](Moving Text)

**Comment by SHWotever** [comment]
Hi ! it's already possible using the scroll function : 
![scrolldemo](https://user-images.githubusercontent.com/2207331/77634921-0def2800-6f52-11ea-9d0f-ff7081d0fd7c.gif)
Nicolas

**Comment by danfeliix** [comment]
@SHWotever  Oh how wonderful, thank you very much, you are a genius!

Oh, que maravilha, muito obrigado, você é um gênio! Outra pergunta: É possível que o programa entenda que esse comando de movimento só pode ser ativado com nomes longos, com mais de 20 caracteres? Porque os pequenos nomes também permanecerão em movimento
![Captura de Tela (197)](https://user-images.githubusercontent.com/54558657/77647632-84395d80-6f45-11ea-99e0-bc386c238a9b.png)

**Comment by SHWotever** [comment]
Hi ! I've added a new option to the scroll function to fit your need, it's now possible to make it scroll exclusively if the length goes over the defined length. I released it in the latest version :
https://i.imgur.com/Tmll10q.gif
