### ISSUE TITLE
How to run VR games?

### ISSUE THREAD

**Issue by DAREVR** [SHWotever/SimHub#517]
Good morning, I have a question about SimHub to see if anyone knows the answer. I have the program license to play Assetto Corsa Competizione, but I play in VR through Steam VR, when I enter the game from the SimHub program, it is directly opened by normal Steam, so I in the VR viewer I see the lobby of my viewer, and the game on a virtual flat screen in front of me, like a TV, but I don't see it in VR. Is there a way to start the game from Steam Vr ?? Simhub I use it exclusively because I have bodyshakers. Only.

Thank you very much in advance everyone. Greetings.

DARE VR.

**Comment by SHWotever** [comment]
Hi ! unfortunately, the game has no documented ways to start it directly in VR mode outside of steam. You can use the way you use usually (steam launcher ...) simhub will get connected to the game as usual ;)

Nicolas

**Comment by DAREVR** [comment]
But I have to start SimHub on the one hand, and assetto steamvr on the other for Simhub to work on body shaker telemetry ?? Or just by opening the game on steamvr does it work alone ?? I open both not?  A greetings.

**Comment by SHWotever** [comment]
Simply start simhub first , then start the the game as you would usually do to get VR working. 
Simhub does not require games to be started directly from the simhub launcher, the launcher is simply a conveniency feature.
