### ISSUE TITLE
Led and Rpm - "AC and Iracing setup" - LED does not synchronize - MATRIX AND TM1638

### ISSUE THREAD

**Issue by EBEALIEN** [SHWotever/SimHub#518]
Hello everyone,
and a wish that you are all well, you and your loved ones.
Small problem, but I do not go out, sorry! SIMHUB 6.7.3
I created a module with **_"MAX7221 LED,
  and connected with TM1638 7 Segments "_**all to a nano.
Everything has been working well, for years, I have been using a 458 gt2 on "Assetto Corsa" and the 1638 LEDs are synchronized with the car on the screen, including the flashes out of speed, everything is synchronized, I have never touched anything.
But now if I use an F1, or if I use "IRACING" _The LEDs go up much earlier and flash when I'm still at 50% on the screen_. They are not synchronized.
Where should I act to synchronize cars and modules ??
Thank you all!
Antonio - Italy

**Comment by SHWotever** [comment]
Hi ! Unfortunetely no games gives explicit data about that, you can configure redline trigger and engine characteristics here : 
![image](https://user-images.githubusercontent.com/2207331/78424187-f1e33900-766b-11ea-8816-aece22968049.png)

**Comment by EBEALIEN** [comment]
Yes,
the problem was configuring cars on Assetto and cars on Iracing.
Completely successful. They are similar to that displayed on a PC
Resolved!

**Comment by SHWotever** [comment]
Nice ! Thanks for feedback, have fun !
