### ISSUE TITLE
release 6.9.8 - bass shaker doesn't work

### ISSUE THREAD

**Issue by Banfy** [SHWotever/SimHub#519]
Hello

since I upgraded to latest 6.9.8, I noticed bass shaker/buttkicker 2 is not working anymore (AMS2,ACC,AC,RF2). I had no problems before
I still can see simhub connects correctly to the games though as shake it motor still work properly
thank you!
cheers

**Comment by SHWotever** [comment]
Hi !

Could you join the log files after a session ? It's available in C:\Program Files (x86)\SimHub\Logs so I can see what is happening ?

**Comment by Banfy** [comment]
here are the last logs
thank you
regards
christophe

**Comment by SHWotever** [comment]
Hi ! Could you post it on github ? https://github.com/SHWotever/SimHub/issues/519 the attachments are not available in github notifications mail reply.

Nicolas

**Comment by Banfy** [comment]
je ne sais pas si l'upload a fonctionne

[Logs.zip](https://github.com/SHWotever/SimHub/files/4431203/Logs.zip)

**Comment by Banfy** [comment]
si ca a l'air ok

**Comment by SHWotever** [comment]
Bonjour, merci pour les logs, je ne vois pas d'erreurs particulières, la carte "High Definition Audio Device" à l'air bien activée.

Que donnent les tests de sortie ?
![image](https://user-images.githubusercontent.com/2207331/78442583-abe0a200-7678-11ea-9e41-0606e6627655.png)

![image](https://user-images.githubusercontent.com/2207331/78442766-b9962780-7678-11ea-9ce1-df6b13aa1752.png)

Pouvez vous vérifier que shakeit n'est pas en mode muet ainsi que le volume ?
![image](https://user-images.githubusercontent.com/2207331/78443120-d3376f00-7678-11ea-8483-b73ccca695f4.png)

**Comment by Banfy** [comment]
depuis simhub tout fonctionne, je viens de faire ces tests
j ai l'impression que c';est la com entre le jeu et simhub. le buttkicker reagit a l'audio du jeu pas a simhub

**Comment by Banfy** [comment]
je fais qques autres tests...

**Comment by SHWotever** [comment]
Hum ca ce n'est pas normal, je jeu ne devrait pas être entendu sur le buttckiker, c'est bien une carte son dédiée aux buttckikers ?

**Comment by Banfy** [comment]
c'est la carte son integree, line out sur le buttkicker
l'audio normal est prise sur mon casque vr
je viens de creer un nveau profil avec seulement le gear shift su ams2 . je pense que j'ai le son du jeu+ gear shift de simhub

**Comment by Banfy** [comment]
j'ai le sound mirroring active sur steam, c'est peut etre la raison?
test en pause , ams2 s'update!

**Comment by SHWotever** [comment]
Ah effectivement il y a de grandes chances !

**Comment by Banfy** [comment]
bon bizarre
sur ams2, mirroring desactive, a l'arret je sens les rpm alors que le profile ne contient que le gear shift

**Comment by Banfy** [comment]
et la musique du menu passe aussi dans le buttkicker

**Comment by SHWotever** [comment]
C'est vrai qu'il y a quelque chose de pas normal, la musique du jeu ne devrait pas sortir sur cette sortie. Malheureusement c'est plutôt un problème de configuration jeu/vr que de simhub du coup j'avoue que je ne connais pas tous les réglages possible de côté.

**Comment by Banfy** [comment]
Hi Nicolas

knowing that simhub is not the cause of my issue, I have checked everything and looks like the issue is coming from my jack 3.5 not being fully plugged into the sound card.  Now back to normal.
Thank you for the support and this FANTASTIC software!
cheers

**Comment by SHWotever** [comment]
Hi ! I did not had additionnal reports (at least nothing which could not be solved by drivers update.)I close this issue for now as it appears that it's not directly related to simhub.

Nicolas
