### ISSUE TITLE
New LED editor missing feature

### ISSUE THREAD

**Issue by thebartez** [SHWotever/SimHub#520]
Hi.

In old LED editor there is option to "Clear leds when value is beyond range (>) or (<)".

It would be nice to have it in new LED editor, or maybe i missed it somewhere.

**Comment by SHWotever** [comment]
Hi ! I indeed removed it in order to simplify a bit settings,

I will try to add it back on the custom gradient.

Nicolas

**Comment by SHWotever** [comment]
Hi ! Unfortunately after all those years this request remained very very rare. I close it for readability purpose even if the the feature would be interesting.
