### ISSUE TITLE
Dash board with mobile phone, QR, and problem app activates microphone on pc.

### ISSUE THREAD

**Issue by EBEALIEN** [SHWotever/SimHub#522]
Hello everyone and sorry for the inexperience.
Premise, I have a new and super controlled PC,
no programs and no apps outside of iracing and simhub. It is controlled by professional company,
to avoid problems and complications, But I have a bad story: Yesterday, after fixing the LEDs (https://github.com/SHWotever/SimHub/issues/518) I also tried to connect a cell phone without a sim, to try a dashnoard , the QR came out, I scanned it and saw the dashboard work fine.
All right, but I notice a problem that was not there 30 minutes before:
I notice, at the bottom right of the desktop (win 10 simhub 673)  a white microphone that I had never seen, not even with teamspeak3 or discord.
While not having anything active, it detects a connected app, but the problem is that when I use the microphone, this app eats all the resources of the microphone, and I have to scream to hear a small hiss of my voice, making it impossible to use.
I checked everything with this company, drivers, volumes, virus apps, all nothing excluded, microphone active but nothing. We moved rear and front doors but nothing. The headphones work perfectly on another pc.
It was found that before the operation with the mobile phone and simhub, it was fine as a few moments before,  I had consulted via TS3 because of the LED problem.
Anyone know how to show me the way ???

**Comment by SHWotever** [comment]
Hi ! That's really strange indeed, 
Simhub uses default sound card audio analysis (to generate frequencies graphs and some fancies tinhgs like that, could you try to disable it in the plugins list ?
![image](https://user-images.githubusercontent.com/2207331/78451474-3085ed00-7686-11ea-9d04-522b3ad34ce8.png)

About simhub version I you said 6.7.3 this is a one year outdated version, you will have big compatibility issues with many games, make sure to update it first ;) https://www.simhubdash.com/download-2/

**Comment by EBEALIEN** [comment]
Ok for now I have deactivated shaker. Then I uninstalled it, I check other causes with confidence and then re-install.
We have to be sure that the scanned QR, do not access the microphone or,  if there is a way to disable it from the dash or QR site
Thanks

**Comment by SHWotever** [comment]
QR code simply contains the url of the dash, it's a simple internet address, it can't interact with your microphone, no doubts about it ;)

**Comment by EBEALIEN** [comment]
Perfect, I keep checking the PC, then I reinstall new version and try all the procedures again! ;-)

**Comment by EBEALIEN** [comment]
Uninstalled and virus scan on my pc free. Well! Microphone disappeared, and zero apps that engage.
Now I reinstall, just one thing I ask, in order not to save one by one,
where can i find the led configurations in arduino ??
Folder! Path to do a copy paste!
Thanks

**Comment by SHWotever** [comment]
Hi ! All the settings are stored inside pluginsdata folder inside Simhub install directory. You can copy paste the whole folder.

**Comment by EBEALIEN** [comment]
Hi, a mess has happened, I lost the data, I unwittingly superimposed the new one on the old folder and I lost everything.
I worked with the matrix and the tm1638 and I saw the 1638 LEDs synchronized. Now I don't see them anymore.
I only have this file: (how do I insert a file?)

**Comment by EBEALIEN** [comment]
This file is very ok in version 673
[tm e matrix 03-2020.leds.txt](https://github.com/SHWotever/SimHub/files/4434253/tm.e.matrix.03-2020.leds.txt)

**Comment by EBEALIEN** [comment]
I confirm that everything is fine, now there is no interference and everything worked.
No problem with simhub.

**Comment by SHWotever** [comment]
Thanks for the feedback !
