### ISSUE TITLE
[Feature request] Belt tensioner controller

### ISSUE THREAD

**Issue by Banfy** [SHWotever/SimHub#523]
Hi Nicolas

do you have any plan to integrate a belt tensioner controller to simulate breaking G forces?
thank you

**Comment by SHWotever** [comment]
Hi ! In my opinion belt tensioner and similar systems are part of "motion" ecosystems. Currently simhub is not yet supporting any forms of motion. But I may add it in the future.

**Comment by Banfy** [comment]
Hi Nicolas

I am back on this. Actually i think it is feasible already with simhub and would like to check with you.
This is to be used on a static rig with a motor pulling on the seat belt during deceleration phase.
I found this idea here: https://www.youtube.com/watch?v=cu6TLIG1tIk

I will be using the deceleration option from shake it motor and will assign a motor output on the motor shield v2, let's say number #2 for example
My motor is 24 V, so i will connect the motor #2 output from the MotorShield v2 (with 12V PSU) to one input of a L298N (powered with a 24V/2A PSU).
Do you think it can work?

I am not sure what  the output of the motor shield to the L298N input pin should be to provide the maximum power in the motor (as close as possible to 24V). I think it is a PWM output from the shield
thank you

**Comment by SHWotever** [comment]
Honestly, I wouldn't go that way, this "design" is based on stalling the motor when you reach the maximum force, which means potential motor and/or board overheating/burning and eventually catching fire. I also see there is no security about the maximum couple being applied.

**The design proposed _Lebois_ probably works, but based on the reasons above that's not a design I ever try/recommend myself, I see too many risks in it.**

In my opinion belt tensioners are part of the "motion" world with proper closed-loop position control which by nature can be perfectly controlled.

**Comment by Banfy** [comment]
This is a very valid point indeed
