### ISSUE TITLE
Dash Studio Dashboard - Black screen

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#526]
Hi, and thanks for todays update. :)

I think I have another bug for you to crush. ;)

I noticed sometimes dashboards can get stuck on a black screen.
I believe it only happens in desktop mode, upon screen change.
This mainly happens to me when exiting iRacing and the dash transitions to its idle screen.
I have had a couple of users reporting a similar issue.
I saved the logs this time. When mousing over the black screened dash, it generated a lot of additional errors.
[Logs.zip](https://github.com/SHWotever/SimHub/files/4458186/Logs.zip)

Take care. Et bonne soirée!

**Comment by SHWotever** [comment]
I worked on this one too, I forgot it in the change log, it should be good now.

**Comment by Romainrob** [comment]
Nice !
I'll blindly trust you on that one. I don't how to test this as it seemed random and somewhat rare.
I'll report to you if it ever happens again.
Thank you!

**Comment by SHWotever** [comment]
I totally understand, I've never been able to reproduce it neither, but  @Meekstaaa logs and yours were pointing the same piece of code ;)
I close it for now, but do not hesitate if it happens again ;)

**Comment by Romainrob** [comment]
Hi. I'm afraid you're not out the woods yet.
This is still happening. It happened 4 times to me since the 7.0.3.
Same as before. Seemingly at random, while editing the dash. Running it in desktop mode, and upon opening or closing a replay.
The 1rst one ended up in an "out of memory" a bit later. Idk if it's related.
The second time triggered the watchdog.
And the 2 last times , there was nothing in the logs.
Sometimes, pressing the next screen button is enough to fix it on the fly.
[Logs.zip](https://github.com/SHWotever/SimHub/files/4621951/Logs.zip)
Good luck! ;)

**Comment by SHWotever** [comment]
Dammit ! Clearly something to do with automatic reload, it still points to the same place
I will try something else ;)
