### ISSUE TITLE
[BUG] Dash studio ncalc doesnt open while an overlay is open

### ISSUE THREAD

**Issue by manuelbiancolilla21** [SHWotever/SimHub#527]
Version 6.9.9

**Comment by SHWotever** [comment]
Hello ! could you give me exact order you have been opening things ? I tried but I had no specific issues.

**Comment by SHWotever** [comment]
do not hesitate to join the related logs too ;)

**Comment by manuelbiancolilla21** [comment]
Can't replicate it neither.
It happens everytime i boot the pc.

Simhub Opens
It loads automatically the overlay editor with its overlays
I open an overlay in dash studio
I click on a FX value
Ncalc windows appears with 0% opacity (i can move the mouse and check there is text as my cursors changes, and i can even copy things, but i cannot see any of that)
Then i close the overlay editor and click the FX value again
Ncalc shows up and works from there on

[https://we.tl/t-5KmHowntRB](url)

**Comment by SHWotever** [comment]
Ah ok :D that's a way more specific situation :D I will try to reproduce it ;)

**Comment by manuelbiancolilla21** [comment]
https://we.tl/t-rjV3NLPZGT new log, just happened with event triggerer too

**Comment by SHWotever** [comment]
Hi ! Sorry for the late reply, I've tested to reproduce it many times but for now I've not been able to reproduce it yet, 
Maybe a graphics driver issue ? Are your graphics drivers and windows up to date ?
