### ISSUE TITLE
Fuel calculation reset in pitbox, AMS2

### ISSUE THREAD

**Issue by Wergilius** [SHWotever/SimHub#528]
Entering pitbox in AMS2, fuel calculation is reset, or fuel/lap becomes low/wrong.
When in pitbox, IsInPitLane and IsInPit are both 0 but GameRawData.mPitMode have non zero value (4).

**Comment by SHWotever** [comment]
Hi ! Ive made some addtionnal tests and i could not reproduce it, are you running the latest 6.9.9 version ? I've made some little changes in the last version about that. 
Which track have you tested ? Maybe it varies depending of the pit box position on track.

**Comment by Wergilius** [comment]
Yes, 6.9.9 and have not noted any specific car/track combo. Example:
Sprintrace at Brands Indy, do some laps -> fuel 0.4x liter/lap
Jump back to pit -> fuel 0.01 liter/lap

log
[2020-04-13 15:33:26,989] INFO - New valid lap detected
[2020-04-13 15:33:26,989] INFO - Storing lap consumption : 0.40
[2020-04-13 15:33:35,939] INFO - New valid lap detected
[2020-04-13 15:33:35,939] INFO - Storing lap consumption : 0.01
