### ISSUE TITLE
Windows Defender warning for SimHub V6.9.9 Installer

### ISSUE THREAD

**Issue by Viking443** [SHWotever/SimHub#530]
Windows Defender is claiming that this installer has Adware:Win32/Unwaders.A!ml contained within it.
File is then Quarantined.

**Comment by SHWotever** [comment]
Hi ! Indeed last version had more false positives than usual, I've already reviewed the installer for the next version, by removing the separate data file it seems to please antivirus better. Here is a beta https://www.simhubdash.com/unofficial/SimHubSetup_7.0.0b3.exe . Unfortunately small software like simhub regularly suffer from false positives and I have very little possibilities to avoid it.

**Comment by Viking443** [comment]
Thanks for quick reply.
