### ISSUE TITLE
ACC Engine Map wrong

### ISSUE THREAD

**Issue by mihi4** [SHWotever/SimHub#531]
In ACC, [DataCorePlugin.GameData.NewData.EngineMap] differs from [DataCorePlugin.GameRawData.Graphics.EngineMap]. 

In my test, NewData.EngineMap is 8, where rawdata is 7.

**Comment by SHWotever** [comment]
Hi ! It's normal rawdata are the values exactly as it comes from the game, and it can't be changed. Newdata contains simhub processed data not specific to a game so it's made to be easier to display, in the case of ACC telemetry reports 0(in rawdata) while it shows 1 in game, which is indeed taken into account in newdata.
From my tests all the cars had this behaviour. Have you seen an exception ? Newdata should match the in-game display without tinkering.

**Comment by mihi4** [comment]
aaaaaaaah, I guess, I never checked the in-car display :D
