### ISSUE TITLE
ACC: Compact Delta very strange

### ISSUE THREAD

**Issue by mihi4** [SHWotever/SimHub#532]
[DataCorePlugin.CustomExpression.CompactDelta] is veeeery different to 'DataCorePlugin.GameRawData.Graphics.deltaLapTime

**Comment by SHWotever** [comment]
Hi ! Indeed compact delta is fed with simhub All time best delta.

You will find game matching properties here (when it's possible) :
![image](https://user-images.githubusercontent.com/2207331/79698296-60d5aa00-8288-11ea-82e4-ab0057d420a2.png)

In the particular case of ACC, all-time best is not given through telemetry so only Session best will match in game display. And all time best will be fed with Simhub's self tracked data.

**Comment by mihi4** [comment]
Thx, SessionBestLiveDeltaSeconds did it for me!!
