### ISSUE TITLE
Support for my Logitech G29 Driving Force Racing Wheel's LED Shifter / RPM Indicator for use 2 PC games 

### ISSUE THREAD

**Issue by ChrisTCanfield** [SHWotever/SimHub#534]
My steering wheel's LED Lights don't work with my PC games: 

"18 Wheels of Steel: American Long Haul"

and

"NASCAR Racing 2002 Season".

I play them on my windows laptop running: Windows 10 Professional - 64 bit

If you can add support to these games to utilize the shifter / pedal LED Lights, I would be grateful & interested in what you have to say.

Chris Canfield
ChrisTCanfield722@gmail.com / 484-213-5987 (USA: Eastern Time / CELLULAR #)

**Comment by SHWotever** [comment]
Hi !

Indeed only games with documented telemetry are supported. Those games are unfortunately too old and telemetry was not a thing at this time, so it's not possible at all to support them 

Best regards,
Nicolas

**Comment by SHWotever** [comment]
PS : G29 leds are not supported at all by Simhub, it's up to the manufacturer or the game to support it, Only DIY leds and wheels by simhub.
