### ISSUE TITLE
Kart Racer Pro Support

### ISSUE THREAD

**Issue by fasrkart95** [SHWotever/SimHub#535]
i'd like to use sim hub with kart racer pro.  The game configuration screen indicates that the game was automatically configured.  Also indicates no telemetry setting available.  It this game compatible?  What are the the setup steps?

**Comment by SHWotever** [comment]
Hi ! 
"No telemetry setting available" simply means that the is nothing to configure, having the plugin installed is enough.

You simply have to enter in a race/practive and Simhub will connect

Let me know,
Nicolas

**Comment by SHWotever** [comment]
Just for information it will only work on x64 builds of the game available since a couple of months.

**Comment by fasrkart95** [comment]
Can you refresh my memory on how to install the plugin?

**Comment by SHWotever** [comment]
You don't have to do it manually, if simhub shows the game as connected it means that it found the game install directory and installed the plugin already.

**Comment by fasrkart95** [comment]
Thanks.  Then I did it correctly.  SimHub is definitely not picking up the
data.  What information do you need to help troubleshoot?

**Comment by SHWotever** [comment]
Could you tell me which version of SimHub you are running ? I updated the plugin in the last versions and it may be related.

**Comment by fasrkart95** [comment]
I was on 6.9.3,  I'm updating to the latest version now and will let you
know.

**Comment by fasrkart95** [comment]
I’ve done the update and dropped the new plugins in to the plugin director
under the steam folder for kart pro.  Same result.  Rfactor2 works fine.

**Comment by SHWotever** [comment]
Hi ! I made a test  on a fresh virtual machine and I Indeed encountered an issue with the latest version of the plugin. Could you try the following version ? I changed some compilation which should improve compatibility with various computers
[SimHubKRPTelemetry64.zip](https://github.com/SHWotever/SimHub/files/4511657/SimHubKRPTelemetry64.zip)

**Comment by fasrkart95** [comment]
Confirmed.  This works.  Thanks.  Only issue is that the Simhub page give
you the warning.  Assuming because it's looking at the data on the file.

Question.  Do you have anything that works with split times?  I'd like to
see that information on screen with a predictive lap time.

**Comment by SHWotever** [comment]
Currently split times are not directly available to the plugin. Concerning predictive lap time, you can find a full set of properties computed by simhub which should match your need :
![image](https://user-images.githubusercontent.com/2207331/79909008-8dbac600-841c-11ea-98bc-a8132712231f.png)
![image](https://user-images.githubusercontent.com/2207331/79909107-af1bb200-841c-11ea-9ca7-e075da2b275b.png)

About the plugin alert, you can copy the file I sent you to C:\Program Files (x86)\SimHub\_Addons\GamePlugins\KartRacingPro\plugins it will remove the alert.

Nicolas

**Comment by SHWotever** [comment]
Hi ! I've relased the new version with the updated plugin I gave you.

**Comment by fasrkart95** [comment]
Thanks.  Great support and product.
