### ISSUE TITLE
SimHub Android App not loading some dashboards

### ISSUE THREAD

**Issue by SeanAussie** [SHWotever/SimHub#536]
Hi, I am using the android app, but have an issue where some SimHub Dashboards don't load.

I get this message:  'loading Universal SimHub Dash for iRacing v1.6.2 - Delta Bar' it stays on this message and never opens it.

The same dashboard that does not open in the app opens on the tablet in the chrome browser.

I have other dashboards that do open in the app, so the app does function.

Any suggestions to get the dashboards that don't load on the app to load? 
I have the latest app and SimHub installed.

Thanks

**Comment by SHWotever** [comment]
Hi ! 
Which android version are you using ? The app can't make use use of the latest chrome engine and some bugs of chrome engine have not been fixed in older versions of the Android OS. An android 6 will give you the best compability.

**Comment by SeanAussie** [comment]
Hi, thanks for your reply.
I am using an older Samsung Galaxy Note 8 tablet running Android 4.4.2

**Comment by SHWotever** [comment]
Thanks ! Do you have any way to upgrade it to a more recent android version ? Android 4.4 is indeed lacking some advanced features which explains why the complex dash like the one from RomainRob may not load.

**Comment by SeanAussie** [comment]
Hi, Yes, I think it may be time to retire that old girl! Thanks for your suggestions.

**Comment by SeanAussie** [comment]
@SHWotever Sorry to bring this back again, but before I replace the tablet, one last question:
The problematic dashboard runs on the same tablet in the Chrome browser, but not the app.
Surely this can't be an android 4.4.2 issue as its running in the OS in Chrome?
Is there not a log file or something I can try to tell what is causing the issue in the app and not on Chrome?
Thanks

**Comment by SHWotever** [comment]
Hi !

Indeed it's normal , the os itself contains a frozen version of the chrome engine made accessible to the applications (like the simhub android app) while the standalone chrome can be updated separately, so the Chrome browser alone is up to date and brings the latest features and bug files, while simhub app can only make use of the old "browser" component linked to the android version (4.4.2), and the only way to workaround it is to install a newer version of the android os itself. 
Hope my explanations clarifies it a little, sorry it's a little hard to explain accurately and in simple words at the same time :D

**Comment by SeanAussie** [comment]
No worries, thank you very much for taking the time to clarify, fully understood!
