### ISSUE TITLE
Ignore shift to neutral not working

### ISSUE THREAD

**Issue by fleskebacon** [SHWotever/SimHub#537]
For RaceRoom, at least, the "ignore shift to neutral" does not work when using an H-shifter, for the bass shaker effect "gear change".

**Comment by SHWotever** [comment]
Hi !

The shift to neutral is only ignored if you engage the next gear within the specified amount of time (200ms as a default) :
![image](https://user-images.githubusercontent.com/2207331/79887858-d7df7f80-83fb-11ea-9aaa-597156706859.png)
If you still feel the pulse it probably means you are taking a little more time than the defined delay. Could you try to make it higher ?

Nicolas

**Comment by fleskebacon** [comment]
Ok, then I misunderstood the option, I will try adjusting it. But is it possible to turn the effect completely off for all shifting into neutral?

**Comment by SHWotever** [comment]
Currently no it's not possible, I can try to add it for a future version ;)

**Comment by SHWotever** [comment]
Hi I've added it and relabelled the old option for the next version : 
![image](https://user-images.githubusercontent.com/2207331/80909877-19d9c100-8d2c-11ea-8c7a-592a2a2674f9.png)

**Comment by fleskebacon** [comment]
Fantastic news! Now my H-shifter with a dedicated bass shaker will behave
exactly the way I want. Thanks a lot!
