### ISSUE TITLE
Nextion Display Upload Problem

### ISSUE THREAD

**Issue by blitzmax01** [SHWotever/SimHub#538]
Hey guys,

today I got my Nextion 4.3 Display and I edited a new template for it and tried to upload it to the Nextion. But unfortunately it broke up at 50% and I don't know why.
I tried another one from Butonz and this one worked, but not all of them and I really don't know why. 
The Nextion is connected to a TLL Modul, with RX - TX, TX - RX , 5V - VCC, GND-GND

Would be really nice if someone has an idea, what could be the problem.

Thanks for your help!

**Comment by blitzmax01** [comment]
I forgot to say - it says the connection time was to long and it asked me to way or to abort the transfer. If I type wait the same message appears some seconds later and the file can't get uploaded. The file is smaller than 16MB.

**Comment by SHWotever** [comment]
Hi ! Using a TTL here is a list of the most common issues :  
- A bad quality TTL (there are a lot of cheap USB adaptors, and they are not all made equal)
- Bad contacts (solders ...)
- Lack of power (avoid USB hubs, try a better quality USB cable)
- Baudrate too high (often linked to TTL quality point above), You can try to lower the baudrate if that helps : 
![image](https://user-images.githubusercontent.com/2207331/79981431-f3eb2b80-84a4-11ea-80c6-5b18a5c30cd1.png)

As an alternative, if you can't solve your connection reliability issue you can use a micro SD to upload the template to the device (https://nextion.tech/faq-items/using-nextion-microsd/), but you may have issues later with simhub connection itself if the connection is not reliable.

Hope that helps,
Nicolas

**Comment by blitzmax01** [comment]
Hello Nicolas, thanks for the quick help. I use 115200 for transfer, I don't understand why it sometimes works and sometimes not. 
It is connected to a USB 3.0 Power Port, it isn't soldered yet, I connected it with the cables which were in the box. 
I will give it a try :) thanks!

**Comment by blitzmax01** [comment]
Is it possible to use your SimHub Uploader or is it only for Arduino?

**Comment by SHWotever** [comment]
The simhub nextion uploader will work too, but I implemented it in a really similar way as the manufacturer editor, so I guess the result will be pretty much the same.

The random aspect really points m to a connection reliability issue , serial communication can be easily perturbed in bad conditions.
If you can try an usb2 port, usb3 can cause some issues (if depends of the TTL chip and drivers), it's definitely worth a test ;)

Nicolas

**Comment by blitzmax01** [comment]
Okay, I will give it a go! Thanks for that!
