### ISSUE TITLE
Freezing every 10 seconds

### ISSUE THREAD

**Issue by domasmns** [SHWotever/SimHub#539]
Hello! Im having problems with simhub. Game is Live for Speed.

I'm using arduino with custom code which turns servo motors according to speed and rpm (mulpile arduinos setting is used). This part works fine. What doesn't work is that exactly every 10 seconds the data calculations just stop for 2 seconds and returns back to normal. This is seen in servo movements too, for 2 seconds it freezes and the quicly jumps to where the arm is supposed to be. What could be the issue?
Simhub version 7.0.1
Lfs version 0.6T
Pc specs
i3-6100
8gb ram
Gtx 1050 ti
Ssd

This is the ncalc line:
format([DataCorePlugin.GameData.NewData.SpeedKmh],'0')+';'+format([DataCorePlugin.GameData.NewData.Rpms],'0')+'*'+timespantoseconds([DataCorePlugin.GameData.NewData.CurrentLapTime])

I've added lap time so the data is not idling but i think i missed something with the configuration.

Now in the code i'm using delay, even though it isn't recommended, but without delay the servos are too jittery and slow to respond, with delay it's better.

Also, how to send milliseconds of Laptime to arduino?

This is the code i'm running:

> #ifndef __SHCUSTOMPROTOCOL_H__
> 
> #define __SHCUSTOMPROTOCOL_H__
> 
> #include <Arduino.h>
> #include <Servo.h>
> 
> Servo speeedServo;  // create servo object to control a servo
> Servo rpmServo;
> 
> int speeed=0;
> int rpm=0;
> int offset=10;//offset from start position, degrees
> 
> double speeedReduc = 2; //degrees=speeed/speeedReduc
> double rpmReduc = 110; //degrees=rpm/rpmReduc
> 
> class SHCustomProtocol {
>   private:
> 
>   public:
> 
>     /*
>       CUSTOM PROTOCOL CLASS
>       SEE https://github.com/zegreatclan/SimHub/wiki/Custom-Arduino-hardware-support
> 
>       GENERAL RULES :
>     	- ALWAYS BACKUP THIS FILE, reinstalling/updating SimHub would overwrite it with the default version.
>     	- Read data AS FAST AS POSSIBLE in the read function
>     	- NEVER block the arduino (using delay for instance)
>     	- Make sure the data read in "read()" function READS ALL THE DATA from the serial port matching the custom protocol definition
>     	- Idle function is called hundreds of times per second, never use it for slow code, arduino performances would fall
>     	- If you use library suspending interrupts make sure to use it only in the "read" function when ALL data has been read from the serial port.
>     		It is the only interrupt safe place
> 
>       COMMON FUNCTIONS :
>     	- FlowSerialReadStringUntil('\n')
>     		Read the incoming data up to the end (\n) won't be included
>     	- FlowSerialReadStringUntil(';')
>     		Read the incoming data up to the separator (;) separator won't be included
>     	- FlowSerialDebugPrintLn(string)
>     		Send a debug message to simhub which will display in the log panel and log file (only use it when debugging, it would slow down arduino in run conditions)
> 
>     */
> 
>     // Called when starting the arduino (setup method in main sketch)
>     void setup() {
>       speeedServo.attach(3);
>       rpmServo.attach(9);
>     }
> 
>     // Called when new data is coming from computer
>     void read()
>     {
>       // Reads until the semicolon and converts it to integer
>       speeed = FlowSerialReadStringUntil(';').toInt();
>       // Read until the ends of the message
>       rpm = FlowSerialReadStringUntil('*').toInt();
>       int dummy=FlowSerialReadStringUntil('\n').toInt();
> 
>       // Sends back the values to simhub, it will show into the log file/panel
>       //FlowSerialDebugPrintLn("Speed : " + String(speed));
>       //FlowSerialDebugPrintLn("Gear : " + gear);
> 
>       
>     }
> 
>     // Called once per arduino loop, timing can't be predicted,
>     // but it's called between each command sent to the arduino
>     void loop() {
>             speeedServo.write((speeed/speeedReduc)+offset);
>             rpmServo.write((rpm/rpmReduc)+offset);
>             delay(15);
> 
>     }
> 
>     void idle() {
>     }
> };
> 
> #endif

**Comment by SHWotever** [comment]
Hi ! 
Delays must be absolutely removed. I've not tested your sketch, but with 15 ms delay you are slower than 60ps but I've added a security which will stop the refresh if the Arduino is too slow and wait for it to catch up or eventually force a reconnect (which will take about 3s). Coul you make sure to remove the delay then join me the new version the simhub log files ? 

Nicolas

**Comment by domasmns** [comment]
I will provide log files tomorrow. Could you specify which ones you need?

**Comment by SHWotever** [comment]
Simply the last log when it occurs (they are available in C:\Program Files (x86)\SimHub\Logs)

**Comment by SHWotever** [comment]
Hi I I gave a try to your sketch this morning on LFS even if the delay should be removed, it looks like it's short enough and it not blocking too much for a disconnect, so I've not seen any particular issues. Could you look if the arduino is not simply disconnecting due to power drop ?  In my last experiences with servos I had to add some capacitors to avoid voltage drop and arduino reboot.

**Comment by domasmns** [comment]
The servo is connected to an external power supply, I tried to stress test it with arduino sweep program, it works just fine, doesn't disconnect. As far as I can see the problem is somewhere in simhub, the freezing every 10 seconds is obvious when looking at available properties tab, all properties freeze up. I recreated the problem on another pc, without any arduino attached, I was testing bass shaker options. Every 10 seconds audio freezes too. The log attached is with servo running without delay.
[SimHub.log](https://github.com/SHWotever/SimHub/files/4521524/SimHub.log)

**Comment by domasmns** [comment]
https://www.youtube.com/watch?v=MzjNi8edV7g

This is a video of raw data, I tried to send lap time data aswell so the data stream would be constant, but the data is sent only when the accelerator is pressed. Also the freezing every 10 sec is there too.

format([DataCorePlugin.GameData.NewData.SpeedKmh],'0')+';'+format([DataCorePlugin.GameData.NewData.Rpms],'0')+'*'+format([DataCorePlugin.GameData.NewData.CurrentLapTime],'mssff')

I also updated the code:

#ifndef __SHCUSTOMPROTOCOL_H__
#define __SHCUSTOMPROTOCOL_H__

#include <Arduino.h>
#include <Servo.h>

Servo speeedServo;  // create servo object to control a servo
Servo rpmServo;

int speeed=0;
int rpm=0;
int offset=10;//offset from start position, degrees

double speeedReduc = 2; //degrees=speeed/speeedReduc
double rpmReduc = 110; //degrees=rpm/rpmReduc

class SHCustomProtocol {
  private:

  public:

    /*
      CUSTOM PROTOCOL CLASS
      SEE https://github.com/zegreatclan/SimHub/wiki/Custom-Arduino-hardware-support

      GENERAL RULES :
    	- ALWAYS BACKUP THIS FILE, reinstalling/updating SimHub would overwrite it with the default version.
    	- Read data AS FAST AS POSSIBLE in the read function
    	- NEVER block the arduino (using delay for instance)
    	- Make sure the data read in "read()" function READS ALL THE DATA from the serial port matching the custom protocol definition
    	- Idle function is called hundreds of times per second, never use it for slow code, arduino performances would fall
    	- If you use library suspending interrupts make sure to use it only in the "read" function when ALL data has been read from the serial port.
    		It is the only interrupt safe place

      COMMON FUNCTIONS :
    	- FlowSerialReadStringUntil('\n')
    		Read the incoming data up to the end (\n) won't be included
    	- FlowSerialReadStringUntil(';')
    		Read the incoming data up to the separator (;) separator won't be included
    	- FlowSerialDebugPrintLn(string)
    		Send a debug message to simhub which will display in the log panel and log file (only use it when debugging, it would slow down arduino in run conditions)

    */

    // Called when starting the arduino (setup method in main sketch)
    void setup() {
      speeedServo.attach(3);
      rpmServo.attach(9);
    }

    // Called when new data is coming from computer
    void read()
    {
      // Reads until the semicolon and converts it to integer
      speeed = FlowSerialReadStringUntil(';').toInt();
      // Read until the ends of the message
      rpm = FlowSerialReadStringUntil('*').toInt();
      int dummy=FlowSerialReadStringUntil('\n').toInt();

      // Sends back the values to simhub, it will show into the log file/panel
      //FlowSerialDebugPrintLn("Speed : " + String(speed));
      //FlowSerialDebugPrintLn("Gear : " + gear);

      
    }

    // Called once per arduino loop, timing can't be predicted,
    // but it's called between each command sent to the arduino
    void loop() {
            //speeedServo.write((speeed/speeedReduc)+offset);
            //rpmServo.write((rpm/rpmReduc)+offset);
            
            speeedServo.writeMicroseconds(map(speeed,0,400,1000,2000));
            rpmServo.writeMicroseconds(map(rpm,0,10000,1000,2000));

    }

    void idle() {
    }
};

#endif

**Comment by SHWotever** [comment]
Hi ! Thanks for the log,;

I see that the game installation directory is not detected, what version of LFS are you running ?  
Since autoinstall can't occur, could you check that you are running with the insim command line as asked in the instructions : 

> To get map and proper timing you must enable insim by adding the /insim=29999 argument to command line
> IE : C:\LFS\LFS.exe /insim=29999

Alternatively, you can drop this script file previously uncompressed in your LFS data/script directory (IE C:\LFS\data\script)
[autoexec.zip](https://github.com/SHWotever/SimHub/files/4522282/autoexec.zip)

Without this Simhub will poll every 10 seconds indeed to get this part of telemetry, if it's not available it will lock during the attempt.

**Comment by domasmns** [comment]
Okay, the freezing seems to be gone after adding the argument.

But the data stream is still not constant, sending data only when accelerator is pressed (or the rpm is increasing, I don't know which one causes the data stream)

**Comment by domasmns** [comment]
Update, now it seems to work fine, only during the starting phase, when the car is waiting for green light, data doesn't update when the accelerator is not pressed, otherwise when the car is launched everything works fine.
I would say the issue is resolved! 
Thank you!

**Comment by SHWotever** [comment]
The start behaviour is linked to the fact that during  the start phase lap time is frozen to 0.00.00 so simhub only sends actual changes which are only for RPM.
The best way if you want to smooth the needle is to receive data like you do now,
and in "idle" which is called much more often use this kind of code : https://forum.arduino.cc/index.php?topic=247117.msg1766460#msg1766460 to move the needle at a regular interval without using delay which would be fatal in this method.
