### ISSUE TITLE
[Request] LED Matrix Custom screen and 32x8

### ISSUE THREAD

**Issue by Tructruc** [SHWotever/SimHub#545]
Please make possible use 32x8 led matrix MAX 7221 and custom fonts directly in SimHub, and make possible to have a color gradient for RPM, fuel, boost and more like in TM1638 or WS2812B.

**Comment by SHWotever** [comment]
Hi ! I don't plan to add 32x8 matrixes. 
I close it for readability purpose even if the the feature would be interesting.
