### ISSUE TITLE
[Feature request] iRacing qualifyer opponent lap times/position

### ISSUE THREAD

**Issue by andreasdahl1987** [SHWotever/SimHub#546]
SimHub doesnt return lap times or position of opponents during qualifying in iRacing, like Z1 and CrewCheif does. The telemetry is avalable, just not in SimHub. In qualys I always have to check in-game or listen to crew cheif to get my grid position. Would be nice to get on dash :)

**Comment by SHWotever** [comment]
Hi ! Would you have a short simhub replay when this happens ? 
You can record it here ;
![image](https://user-images.githubusercontent.com/2207331/80369496-a8fb5a80-888e-11ea-8b8e-4af56302c1a5.png)

Then press live to stop recording,
The record files will be stored here : C:\Program Files (x86)\SimHub\Replays\iracing

Nicolas

**Comment by andreasdahl1987** [comment]
20200428_213100.telemetry.json
<https://drive.google.com/file/d/1xWxMy2KgnfyeS5ur9KEzFlBp-ykxLyGs/view?usp=drive_web>
 20200428_213100.telemetry.json.metadata
<https://drive.google.com/file/d/1VRkzY5MbDpPD-ZP0QT254g7O4JAWX936/view?usp=drive_web>

This replay should show a RX session with practice, quali and race. The
extra iRacing properties show lap times and position in practice and race,
but not during qualification (probably some other telemetry is also
missing). Crew chief and Z1 dash can return this info during qualy.

**Comment by SHWotever** [comment]
Hi !
A huge thanks for the replay, I've been able to figure my error,
It is fixed for the next version,

Nicolas

**Comment by andreasdahl1987** [comment]
Great news! Thanks😊😊

søn. 3. mai 2020, 09:45 skrev Wotever <notifications@github.com>:
