### ISSUE TITLE
[Feature request] Fanatec LEDs

### ISSUE THREAD

**Issue by andreasdahl1987** [SHWotever/SimHub#547]
I know this is probably ALOT of work, but would be nice to be able to control Fanatec LEDs with SimHub. FanaLab and SLIManager Pro/Fanatec edition are both very limiting. Would be great to be able to edit Fanatec LEDS with Simhub. Probably quite a few users/new users that would be happy about it

**Comment by SHWotever** [comment]
Hi !  Fanatec leds support is not planned at all, as a general rule of thumb I run away any support I can't test myself, but owning each fanatec wheel is definitely not possible for me, I'm sorry.
