### ISSUE TITLE
MAP Led rgb and jellow flag and blue flag

### ISSUE THREAD

**Issue by EBEALIEN** [SHWotever/SimHub#548]
Hi Wotover, **a greeting to all of you and a wish that you are all well!**
I have a small inconvenience and I'll explain.
I have the new simhub version but I manage the LEDs like the previous one,  and in the past I managed to get the result but today I can't get it.
I have a "nano" module to which I connected the TM1638 and the "matrix", everything works fine. I wanted to add 6 RGB LEDs PL9832 F5 connected to a free port on the nano  _(I had already done it in the past and everything worked fine)._ 
I just can't configure the yellow flag and the blue flag I don't remember.
I have 6 LEDs, 123 I would like a yellow flag 456 I would like a blue flag, and I use it on a "AC" and "iracing".
The TM1638 is well mapped as you have solved me, and it is fine, now I am missing these 2 maps!
I read the guides but I just can't and I apologize!
Antonio - Italy

**Comment by SHWotever** [comment]
Hi ! 

Blue and yellow are now built it ;) you will find them in the "status leds" category : 
![image](https://user-images.githubusercontent.com/2207331/80455977-0f36ba80-892d-11ea-8c99-b251de28292c.png)
Then you have to choose how many leds and position :
![image](https://user-images.githubusercontent.com/2207331/80456047-2ecde300-892d-11ea-89ec-04f30e45b642.png)

**Comment by EBEALIEN** [comment]
Okay thank you, I'll try, but I'm afraid to compromise the TM1638. I have the new version of simhub, but for the leds, I use the previous previous configuration!
![immagine](https://user-images.githubusercontent.com/17771086/80461072-0518ba00-8935-11ea-8a57-11b3029a94a2.png)

**Comment by SHWotever** [comment]
Hi ! Indeed it will switch to the new editor for both.

You can find the deprecated examples here : https://github.com/SHWotever/SimHub/wiki/Arduino---some--RGB-leds-configurations-examples/d11358ae4092b8146b08e48e883de4b8b004b8ff

However the old leds editors for both tm1638 leds and RGB will be removed this year, do not hesitate to switch to the new editor.

**Comment by EBEALIEN** [comment]
I'll move on to the new editor and hope to understand something.
But for example, in the link you have given me, we have formulas, such as the Yellow Flag example
Enabled formula: "[DataCorePlugin.GameData.NewData.Flag_Yellow]" But for the Blue one? and then where I find the formulas, my folder is completely empty!

**Comment by SHWotever** [comment]
[DataCorePlugin.GameData.NewData.Flag_Yellow] is a property,
you have to use [DataCorePlugin.GameData.NewData.Flag_Blue] for the blue flag,
When editing the formula you have a button "insert property" with a search engine : 
![image](https://user-images.githubusercontent.com/2207331/80467873-bec85880-893e-11ea-9e50-7d636a959948.png)
![image](https://user-images.githubusercontent.com/2207331/80467901-c8ea5700-893e-11ea-8bad-add612603e2a.png)

**Comment by EBEALIEN** [comment]
Perfect, last night I followed your instructions, and consider that I know nothing.
Well it worked out perfectly, exactly, just like I wanted.
Thanks a lot for the help, but thanks because I am very satisfied with your software, the only and most popular.
Now, I will try with the new interface as you recommended me, and I will tell you if I can also with that!
