### ISSUE TITLE
NCalc Formulas with '+'

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#549]
Hi,

Not sure if I'm doing something wrong but when I use the following:

left([DataCorePlugin.GameRawData.SessionData.CarSetup.Chassis.General.BaseBrakeBias],0,4)

and try to add something to it, it just adds the number to the end. but if I subtract that works fine.

without any formulas on it the string shows the following '57.0% front' but with my formula on it just returns '57.0'. By subtracting say 1, it makes it correct at 56 but adding 1 gives a result or 57.01.

Any way around this or is this just not possible?

**Comment by SHWotever** [comment]
Hi ! 
indeed it's tricky, ncalc try to convert from left to right when adding, 
So if first item is a string it will try to convert the second one as a string :
`left('57.0% front',0,4) + 0` gives `string + number` = `string + number converted as a string`
Simply reversing Is enough : 
`0 + left('57.0% front',0,4)`  gives `number + string `= `number + string converted as a number` 
CQFD !
![image](https://user-images.githubusercontent.com/2207331/80507710-6ceff480-8977-11ea-8977-0808e7bcabe2.png)

**Comment by Meekstaaa** [comment]
Thanks. That did the trick!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
