### ISSUE TITLE
[Feature request] Possibility to get controller axis value from SimHub

### ISSUE THREAD

**Issue by casef** [SHWotever/SimHub#550]
Hi, we briefly talked about this a while back at RD - would it be possible to add the option to allow reading controller axis, specifically a wheel rotation directly in SimHub, so that it would be possible to make a wheel input widget regardless of whether a sim sends out such information or not? As far as I know, it's currently possible to access buttons like this, but not axis. I think simply just reading the axis value with the raw value being converted to degrees manually would be great.

Specifically talking about TM wheels, if that makes any difference.

Thanks.

**Comment by SHWotever** [comment]
Hi ! I've added it for the next version,
![image](https://user-images.githubusercontent.com/2207331/80857569-803ee080-8c53-11ea-8758-ef0aa43ff0e0.png)

**Comment by casef** [comment]
That is awesome! Thank you!
