### ISSUE TITLE
[Question] Simhub & vibration motors

### ISSUE THREAD

**Issue by 7HUND3R36** [SHWotever/SimHub#552]
Hello everyone.

First of all forgive my English, I use google translator. Sorry.

Well, it turns out that 2 days ago I installed some vibration motors for my g27 pedals. I used sakeit and in corsa asseto it worked for me but in iracing it didn't. Now I use the simhub and the motors in asseto corsa or iracing don't work for me. What am I doing wrong?

**Comment by SHWotever** [comment]
Hi !

First of all you need to update the sketch to get the simhub supported one (see https://github.com/SHWotever/SimHub/wiki/Arduino--Setup#sketch-configuration) Make sure to use the exact board when configuring the sketch.

When done properly you will see your arduino connected here with the 4 motors available :

![image](https://user-images.githubusercontent.com/2207331/80916047-88337900-8d56-11ea-84b9-984fd367ded0.png)

Now that hardware is properly configured you can go back to shake it and enable effects on the motors you want : 
![image](https://user-images.githubusercontent.com/2207331/80916064-af8a4600-8d56-11ea-912b-72d984a9623f.png)

**Comment by 7HUND3R36** [comment]
Hi.

I get it as follows

[https://i.gyazo.com/5a1c9492489a5c320fd1dce28840c5fc.png](url)


Why do I get 4 engines? I only have 2 motors connected to motorshield v2.

**Comment by SHWotever** [comment]
It's normal, the board can drive 4 motors, no matter if you have a motor really plugged to each output or not.

**Comment by 7HUND3R36** [comment]
Well I think I have it configured correctly. If I click here

https://i.gyazo.com/c980d5e65613a53f6388b9a4ed2d4aba.png

I do run the engines but while driving they do nothing. I'm going to try rfactor2.

It might not work for me because I don't have a simhub license?

**Comment by SHWotever** [comment]
It's not related to license ;)

Everything looks perfect, but you haven't shown if you had enabled some effects, by default they are all disabled to avoid a big "vibration mess" , you need to enable what you need : 
![image](https://user-images.githubusercontent.com/2207331/80921810-eec98e80-8d78-11ea-95e6-639673425b19.png)
also take care of top right volume, by default it's are 50% you may need to push it higher

**Comment by 7HUND3R36** [comment]
It already works, effectively, I had the effects of the effect profile tag disabled.
