### ISSUE TITLE
Xbox Controller Input - SimHub Focus Issue

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#553]
Hi again.
I noticed the joystickPlugin. Very nice!
So I'm making an input overlay and I noticed SimHub only seems to see the inputs when it's focused.
As soon as I click somewhere else. It stops working.
I don't see anything in the logs
Je paye mon gif ;)
![SimHub Xbox Overlay](https://user-images.githubusercontent.com/50543913/80924002-ff810100-8d86-11ea-853b-21f7525b9428.gif)

**Comment by SHWotever** [comment]
Je vais vérifier, je crois que c'est un problème particulier de la manette de Xbox one qui est mal supportée en mode direct input (joystick classique) ce contrôleur spécifique a toujours posé problème contrairement a tous les volants ou manettes plus classiques

**Comment by SHWotever** [comment]
Effectivement je n'ai pas testé sur mon pc mais cela semble commum a ce contrôleur https://stackoverflow.com/questions/48748313/using-directinput-with-xbox-one-controller-and-window-focus-on-windows-10

**Comment by Romainrob** [comment]
Ah! C'est dommage.
Merci pour ta réponse rapide et bonne fin de soirée :)

**Comment by SHWotever** [comment]
Ok, j'ai regardé, c'est sans issue :( , même en passant en XInput çà coupe. dire que j'avais acheté une manette de XB1 pour remplacer ma bonne vieille manette de 360, je suis vert.

**Comment by Romainrob** [comment]
C'est dommage. C'est probablement la manette la plus populaire sur PC. :(
Merci d'avoir creusé la question.
