### ISSUE TITLE
Blinking Progressbar problem

### ISSUE THREAD

**Issue by Sharkey-NL** [SHWotever/SimHub#554]
Hey peeps

I recently got myself a 2nd hand rim with Arduino Leonardo and a Nextion 2.4"
I use latest Simhub nextion binding editor and Nextion Editor 0.58

I can make a default vertical progressbar blink when rpm>redline and gear<max.gears, I put the code in the Foreground Picture Id.

Code is this
`if([DataCorePlugin.GameData.NewData.Gear]<[DataCorePlugin.GameData.NewData.CarSettings_MaxGears],blink(rpmblink, 150, [DataCorePlugin.GameData.NewData.Rpms]>[DataCorePlugin.GameData.NewData.CarSettings_RedLineRPM]), falseResult)`

But when I want to make a blinking custom progressbar, (with sta=image: back image empty gauge and foregr image filled gauge), it doesn't work.

There is blinking, but not the correct foreground image is blinking, either the foreground image disappears and the background progressbar starts blinking, revealing the 1st page,
When I try the code in another propertie, some complete other image from the stored pictures start blinking and it even messed up the simhub template so I have to upload the nextion one again

Hope it's a bit clear?
Anyone an idea what I'm doing wrong and not seeing ?

**Comment by SHWotever** [comment]
Hi ! Could you give me the full example ?

Currently what I can see is that 
if([DataCorePlugin.GameData.NewData.Gear]<[DataCorePlugin.GameData.NewData.CarSettings_MaxGears],blink(rpmblink, 150, [DataCorePlugin.GameData.NewData.Rpms]>[DataCorePlugin.GameData.NewData.CarSettings_RedLineRPM]), falseResult)
Will probably give some strange results, "falseResult" is not a value, it's just a part of the syntax  example, you need to give picture id to the gauge (0,1 ....5) .
Nextion does not supports removing a picture, you you always need to give it a valid image index.

**Comment by Sharkey-NL** [comment]
Tnx for the fast reply.
I dont have anymore for an example, that's it ;-).
I use that code in Properties - Foreground color from the progressbar with predef. role Engine RPM's. That makes my rpmbar blink at red ref's

I works this way ... so I never looked further to complete the code, hence the "falseResult"left in.
Now I want a selfmade gauge that does the same ...

But I guess the "falseResult" might has something to do with it .... not giving it a value
Do you mean with picture ID the component id from Nex.Editor? Or one of the 2 picture ID's that make up the gauge.

**Comment by SHWotever** [comment]
picture id is the id of the picture you want to set indeed, 
![image](https://user-images.githubusercontent.com/2207331/80967569-df008780-8e16-11ea-94c4-6be5b580a285.png)

Indeed that "falseresult" will make it fail with no doubt ;)

**Comment by Sharkey-NL** [comment]
Oke, let's pull this apart ...
I just use the "_if_" so I won't have a continual blinking gauge at max gear ...

A redline rpm blinking standard progress bar is done by this, right?
Put in "Properties" of "Foreground color".

`blink(rpmblink, 150, [DataCorePlugin.GameData.NewData.Rpms]>[DataCorePlugin.GameData.NewData.CarSettings_RedLineRPM])`

But this doesn't seem to work with a picture-progressbar, so I guess I get it wrong from the start, but can't wrap my head around what I'm doing wrong ... ;-D

If I use the same codeline at the same place, the frontpic from the progress bar is transparent but still works , it incrementally covers the backpic but because it's transparent it reveals, I think, lower picture ID's, but the flashing works, although it's a transparent blink ....
... Hard to explain writing .... :-/

So I presume wrongly that a standard progress bar works the same as a picture progress bar, but it's obviously not the same.
Are there some examples from coding with the Binding Editor? 
I figure things out more easily from example ;-D

**Comment by SHWotever** [comment]
For a color progress bar you will have to set a color : 
```
if(blink(rpmblink, 150, [DataCorePlugin.GameData.NewData.Rpms]>[DataCorePlugin.GameData.NewData.CarSettings_RedLineRPM]),  63488, 1024 )
```
1024 is green, 63488 is red 
![image](https://user-images.githubusercontent.com/2207331/80970556-a31bf100-8e1b-11ea-834b-55d5fd709807.png)


The color codes can be taken from the nextion editor : 
![image](https://user-images.githubusercontent.com/2207331/80970001-cd20e380-8e1a-11ea-9428-28e376712526.png)

When using pictures the process will be similar but with picture ids instead of color codes : 
```
if(blink(rpmblink, 150, [DataCorePlugin.GameData.NewData.Rpms]>[DataCorePlugin.GameData.NewData.CarSettings_RedLineRPM]),  1, 0)
```
Where 0 is the redline foreground picture id, and 1 the normal foregound picture id.

The picture ids can be taken here :

![image](https://user-images.githubusercontent.com/2207331/80970751-f5f5a880-8e1b-11ea-90d9-87621bc7005a.png)

**Comment by Sharkey-NL** [comment]
Okies !! Thanks for your time!!
I try to figure this out, let you know if I get it ... or still not ;-DD

**Comment by Sharkey-NL** [comment]
So I like to report back that with your help I got it working!
I also have a bit more understanding of the language. 
So a big "Thanks" to you, SHWotever
Regards!!
