### ISSUE TITLE
SimHubWPF has stopped working

### ISSUE THREAD

**Issue by MichaelUkolov** [SHWotever/SimHub#555]
Hello everybody.
I have issue with SimHub 7.00.2. Windows says that "SimHubWPF has stopped working" when I just open it. No game, no another devices (Arduino etc.)

Logs say only this:

> [2020-05-04 22:13:48,679] INFO - Starting SimHub v7.0.2 (build time : 25/04/2020 12:39:57)
> [2020-05-04 22:13:48,689] INFO - Administrator privileges : True 
> [2020-05-04 22:13:48,694] INFO - OS version : Microsoft Windows NT 6.1.7601 Service Pack 1, Windows 6.1.7601
> [2020-05-04 22:13:48,694] INFO - License status : Free
> [2020-05-04 22:13:48,694] INFO - Process priority : Normal

What I do wrong? Older, on previous versions (like 6.8 or older) works fine, but now old version doesnt help to solve problem.

**Comment by SHWotever** [comment]
Hum that's strange indeed, I just checked the 7.0.2 on a fresh windows 7 (all updates installed) with no particular troubles. 
Could you check that framework 4.7.2 is correctly installed? https://dotnet.microsoft.com/download/dotnet-framework/net472 click on "Download .NET Framework 4.7.2  Runtime" and then try a repair.

If it does not works could you go into event viewer after the crash,
![image](https://user-images.githubusercontent.com/2207331/81050825-f7c57780-8ec0-11ea-9f26-068a683ad948.png)

Then in windows log/application
![image](https://user-images.githubusercontent.com/2207331/81050847-06139380-8ec1-11ea-8165-1c138ea3ef52.png)

Crash related logs always comes in pairs, could you give me both error messages ?

Nicolas

**Comment by MichaelUkolov** [comment]
> Could you check that framework 4.7.2 is correctly installed? https://dotnet.microsoft.com/download/dotnet-framework/net472 click on "Download .NET Framework 4.7.2 Runtime" and then try a repair.
> 
Tried a repair, then rebooted computer, but have the same error while launching.
> 
> Crash related logs always comes in pairs, could you give me both error messages ?
> 
*.log file from SimHub the same:
> [2020-05-05 14:38:12,624] INFO - Starting SimHub v7.0.2 (build time : 25/04/2020 12:39:57)
> [2020-05-05 14:38:12,638] INFO - Administrator privileges : True 
> [2020-05-05 14:38:12,642] INFO - OS version : Microsoft Windows NT 6.1.7601 Service Pack 1, Windows 6.1.7601
> [2020-05-05 14:38:12,642] INFO - License status : Free
> [2020-05-05 14:38:12,642] INFO - Process priority : Normal

In event viewer have next errors, in my opinion, I guess errors by .NET Runtime, but why if all .NET packages were installed? If it is neccessary, I can give screenshots in English.
![simhub4](https://user-images.githubusercontent.com/12644892/81062660-1470a800-8edf-11ea-9f90-1270bbfdd590.png)

![simhub3](https://user-images.githubusercontent.com/12644892/81062661-15a1d500-8edf-11ea-96a7-6a434032df07.png)

![simhub2](https://user-images.githubusercontent.com/12644892/81062663-15a1d500-8edf-11ea-98a0-298b1e5371f8.png)

![simhub1](https://user-images.githubusercontent.com/12644892/81062665-163a6b80-8edf-11ea-971e-116d8b5fa685.png)

![simhub](https://user-images.githubusercontent.com/12644892/81062666-163a6b80-8edf-11ea-85fc-2b4025dd55b9.png)

**Comment by SHWotever** [comment]
Thanks for the infos,

It's a bit hard to read but I found the error code, it looks to be an error inside the .net framework itself. From what I've been able to find about this error it has been fixed in a windows update patch. Is your OS up to date with all windows update patches ? 

Could you also try install this ? https://dotnet.microsoft.com/download (Download .NET Core Runtime)
It seems a little unrelated but Microsoft forums seem to point to this as an unwanted dependency when the os is not up to date.

Let me know

**Comment by MichaelUkolov** [comment]
Tried on another computer, all works fine on same Windows from first attempt.
Then back to my, checked for updates and fouded some new updates for NET Framework: KB4503575 and some another .NET witout -KB prefix. After installing it, all works! 
Thanks for help!

**Comment by SHWotever** [comment]
Amazing ! Thanks for the feedback!
