### ISSUE TITLE
Doubts with arduino configuration and motorshield v2

### ISSUE THREAD

**Issue by 7HUND3R36** [SHWotever/SimHub#556]
https://i.gyazo.com/3f91e9a358a166e5d29baeaf7d6d33f3.png

Do I have to configure this step first of all if I use simhub? Or do you already do this step from simhub when you start and configure it for the first time?

**Comment by SHWotever** [comment]
Hi ! No it doesn't exists anymore in simhub, running those motors at 12v proved to be safe so this setting has been removed.

**Comment by 7HUND3R36** [comment]
OK. And this configuration here?

https://i.gyazo.com/ea2867012d6c8dc95bb90cd52f2aa54e.png

I have it set in 1890 but is it less recommended?

**Comment by SHWotever** [comment]
Hi ! This setting is described here : https://github.com/SHWotever/SimHub/wiki/Arduino-Shake-It#about-motor-shield-v2-humming-noise

Values close th the default one won't cause any issues, lower values requires to make sure the board is probably ventilated.

**Comment by 7HUND3R36** [comment]
I have another question. I wanted to get an iflag. Make it myself since I have an arduino board left over. What I do not know what matrix to buy since simhub many variants come out.

https://i.gyazo.com/4651a16ea7551d441ca39109f954bd58.png
https://i.gyazo.com/07306198079d4e66fd66d966c2310434.png

Thanks SHWotever.

**Comment by SHWotever** [comment]
Currently, none of the supported devices acts like Iflag,  it works only as a **gear indicator**  (don't use RGB matrix it is deprecated as shown in the setup utility).

![image](https://user-images.githubusercontent.com/2207331/81064727-7d095600-8eda-11ea-9446-ebc263d4c69e.png)


https://github.com/SHWotever/SimHub/wiki/Arduino-MAX7219-Matrix-Wiring

**Comment by 7HUND3R36** [comment]
Yes, I have already fixed that the RGB Matrix is not used in the simhub. I will have to use iflag software apart from simhub to be able to use iflag.
