### ISSUE TITLE
Adding Serial Port baud rate selection for Nextion

### ISSUE THREAD

**Issue by EtienneGameSeed** [SHWotever/SimHub#558]
Hi,

In the latest version of the Nextion Editor, new serial port baud rates have been added (230400, 256000, 250000, 512000, and 921600)

However in SimHub it seems to be forced to 115200.

It would be great if you could add a baud selector in the Nextion parameters so we can use these baud rates, as it in done the Arduino tab.

**Comment by SHWotever** [comment]
Hello !

I've tried it, but unfortunately, it's really unstable, 
At upload it throws errors really easily (tested with both serial TTL and arduino), and when running it the nextion instruction buffer is easily overfilled. In case of complex dash and it will simply lose instructions if they are sent too fast and the display will be out of sync (it can already happen at 115200bauds actually but raising baud rate would make it much more frequent).

Nicolas

**Comment by EtienneGameSeed** [comment]
I just tried with Teensy LC at 250000 and Teensy 3.2 at 921600 bauds and uploaded several times without any error.
Not all baud rates work because of the usart clock generation of mcus sometimes result in too much difference between the real baud rate and the one that you asked to the MCU.
I could not try with Teensy LC at 500000 or Teensy 3.2 at 1 or 2Mbits, because unfortunately these baud rates are not supported yet by Nextion Editor. 

You can check this page :
https://www.pjrc.com/teensy/td_uart.html

And for AVR there is this page:
https://trolsoft.ru/en/uart-calc

you'll notice that on these 3 mcus, 250 k and 500k give 0 % error in the baud rate, which is not the case for 115.2k...

And I'm pretty sure that STM32 mcu that Nextion screens use have no problem with theses baud rates, especially if they propose it in the upload window of the Nextion Editor.

**Comment by SHWotever** [comment]
Concerning upload Indeed it can work in better conditions, But on this point I already updated to the nextion uploader to support it.

But concerning the display refresh no matter the baudrate, the speed is constrained by the rendering on the display and the instruction buffer. When I send data faster to the nextion and the design is complex (large areas to be redrawn) the buffer will easily overfill (even if the enhanced version is less sensible to it compared to the basic.). 
To be totally transparent even if I could technically support it, adding unsafe baud rates would probably generate some additional support due to this easy buffer overfill, and I need to avoid it for my mental sanity ;) Lessons learned from the last years, _don't open the door if you don't want people to enter_ :D

**Comment by EtienneGameSeed** [comment]
Ok I understand, in fact I was not asking to send data data faster or more data from the PC side, but rather be able to choose baud rates that have 0% error (like 250 K) in order to improve robustness.
Never mind. 

Thanks.

**Comment by SHWotever** [comment]
Ah under this angle I understand better the request ;) But I would fall straight into the buffer issue if the data was sent faster :(

Any news about Nitro stunt racing telemetry ? :D I'm ready ;)

**Comment by EtienneGameSeed** [comment]
No news yet, I'm still spending a lot of time updating NodeBlue to support your latest protocol, improving PWM support for pedals and wheel vibration support via ShakeIt.
And I just saw that you changed the RGB led protocol as well :(.

**Comment by SHWotever** [comment]
Hum, not recently,I think I changed it at the end of 2018 to support partial updates (and save serial bandwidth) , I'm always seeking for optimizations when it's possible :D.

The latest version of the sketch has also an unique identifier set at sketch upload to allow unique Arduino recognition even if the name is the same.

**Comment by EtienneGameSeed** [comment]
Yes know it's not recent, I've been using protocol h for a long time, but I thought it was time to upgrade. I'm not doing changes too often, as porting from your parser to a state machine parser is not an easy task ;)
Concerning the name, I can change it in NodeBlue with the HID module (so it's not messed up in games too), and the serial number comes from the hardware. But CPU is not recognized as SIGNATURE_0 / 1 /2 is specific to AVR and doesn't exist in Teensy core
