### ISSUE TITLE
Blinking LED Ncalcs still being processed even if enabled not active

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#559]
Hi,

Not sure if this is fixable or intentional but I thought I'd highlight it.

On the new LED editor, when you have a formula in the blinking box but don't have it active it's still computed and can cause errors. Would it be possible to stop the computing of the formula if the tick box is not active.

**Comment by SHWotever** [comment]
That should be doable ;) I will take a look
Just to confirm it happens when "allow blinking" is unchecked right ? 
![image](https://user-images.githubusercontent.com/2207331/81111087-c5496800-8f1c-11ea-9687-9e6c1c46515e.png)

**Comment by Meekstaaa** [comment]
Hi,

Correct. If that is unticked but a formula is entered below still calculated.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
