### ISSUE TITLE
re-occuring error after stopping replay (might also happen when ending game)

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#561]
Hi,

Just noticed this when i stopped a replay (it even carries on after closing all dash studio windows).

  | INFO | Resolution change detectedOld : Screen[Bounds={X=2526,Y=1080,Width=800,Height=480} WorkingArea={X=4446,Y=1080,Width=800,Height=440} Primary=False DeviceName=\\.\DISPLAY5 New: Screen[Bounds={X=4446,Y=1080,Width=800,Height=480} WorkingArea={X=4446,Y=1080,Width=800,Height=440} Primary=False DeviceName=\\.\DISPLAY5ensuring window iRacing location.
-- | -- | --

[SimHub.log](https://github.com/SHWotever/SimHub/files/4586484/SimHub.log)

**Comment by Meekstaaa** [comment]
ah, I've found what this is.

It's when I change my default monitor to another one when simhub is open it goes mad and keeps reporting a resolution change.

**Comment by SHWotever** [comment]
I've investigated a bit, actually I found where the error was occuring.I've fixed it for the next version ;)

**Comment by Meekstaaa** [comment]
Nice! :)

**Comment by SHWotever** [comment]
Fixed in the last beta ;)
