### ISSUE TITLE
New updates to led editor have caused other issues

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#564]
Hi,

Just a heads up. On the new version now some conditions don’t show up even if are true. (See picture below). 

This particular one is from a default profile that is loaded into a game specific profile. 

But if blinking is enabled it does show (with a blink). This also happened on a car specific one where it wouldn’t show unless blink enabled. 

![C1424D1E-3D62-4DF9-87D4-772FA89D5388](https://user-images.githubusercontent.com/29677438/81402277-fdbd9180-9128-11ea-82e2-4d7e1045d2ec.jpeg)
![72419733-5664-48FF-BEF4-143ACEDD70D5](https://user-images.githubusercontent.com/29677438/81402286-01511880-9129-11ea-8654-4def3024d3e1.jpeg)

**Comment by SHWotever** [comment]
Well seen ! I fix it right now !

**Comment by SHWotever** [comment]
Beta update released ;)

**Comment by SHWotever** [comment]
I triple checked everything on the last beta, everything seems fine now ;)
