### ISSUE TITLE
Doubts with simhub

### ISSUE THREAD

**Issue by 7HUND3R36** [SHWotever/SimHub#565]
Why are there options that come in the left tab and others are hidden in the arduino tab at the top?

https://i.gyazo.com/b9a1ecc185e91daba08e408a9787c334.png

**Comment by SHWotever** [comment]
It's classified based on major features
Arduino contains everything related to Arduino configuration.
Shake it motors can drive anything related to vibration motors (not exclusively Arduino based, it can be Arduino, fanatec pedals, gametrix, force feel ...)
Shake it bass shakers drives bass shakers (not Arduino related at all)
Nextion is a specific kind of display (not related to arduino)

**Comment by 7HUND3R36** [comment]
Finally, another question.

This type of visualization is configured what it shows in the section (arduino-screen) in simhub?

https://i.gyazo.com/1feeabcbdc7279ac021abeac43a22fa5.png

**Comment by SHWotever** [comment]
It will appear as a simple text module, just like max7219 or tm1638 and it will be configured the same way.

**Comment by 7HUND3R36** [comment]
Thanks for help.

**Comment by SHWotever** [comment]
No problems ;)
