### ISSUE TITLE
Share gpio pins between max7319 matrix and 7seg?

### ISSUE THREAD

**Issue by penfold42** [SHWotever/SimHub#566]
Just started using sim hub - I love it !

Is it possible to either
A) cascade a dot matrix 7219 with a 7 segment 7219 ?
B) share clock and data lines ?

**Comment by SHWotever** [comment]
I've never tested it but  max chip has a CS pin for this exact purpose.;)
For wiring simplicity I prefer to keep only easy wirings with one device pin = one Arduino pin. But the if I remember correctly I made the setup tool "duplicate pin" error to be not blocking.

**Comment by SHWotever** [comment]
I forgot about cascading ;)  no it's not possible matrix and text displays are distinct in the code and you can only cascade text displays.

**Comment by penfold42** [comment]
Thanks for the quick replies.

I’ll test the overlapping clock&data pins today.
I didn’t even think to try ignoring the red conflict alert

**Comment by SHWotever** [comment]
Just to confir,m I checked this morning, yes it is possible to bypass it ;)

**Comment by penfold42** [comment]
And I can confirm they can share the clock line successfully on the device.

Data I haven’t tested yet
