### ISSUE TITLE
Thustmaster wheel not found

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#567]
Hi again.
You're closing too many tickets these days so I had to open a new one. :)
I started using the Thustmaster plugin again and noticed it doesn't detect my TS-PC when using the F1 rim. It works with my other rims.
![image](https://user-images.githubusercontent.com/50543913/81479920-94bc4380-9226-11ea-805d-576d425e9abe.png)
Yet the joystick manager does pick it up.
![image](https://user-images.githubusercontent.com/50543913/81479906-8b32db80-9226-11ea-8907-c6411c6289e5.png)

**Comment by SHWotever** [comment]
Hum ! Strange, I think it's due to the wheel appearing as different pid/vid, I need to remember how to find ;) Give me a few minutes to find the info ;)

**Comment by SHWotever** [comment]
![image](https://user-images.githubusercontent.com/2207331/81480093-b10cb000-9227-11ea-8078-a9e1fa17230b.png)
It should be available in the device details, 
for a TS PC with a classic rim it's VID_044F PID_B689
I also need to know where the driver is storing the settings in the registry 
On the TSPC classic rim it's HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_044F&PID_B689\OEM\JoystickSettings\533261683
![image](https://user-images.githubusercontent.com/2207331/81480161-1e204580-9228-11ea-8cbe-91e1c46fb09a.png)
There should be a similar one for the F1 RIM

**Comment by Romainrob** [comment]
Ok. Et voilà:
![image](https://user-images.githubusercontent.com/50543913/81480198-59227900-9228-11ea-80c5-bf66e5af8cac.png)

USB\VID_044F&PID_B68A

Et dans le registre :
![image](https://user-images.githubusercontent.com/50543913/81480250-b0284e00-9228-11ea-98e1-7a928eda5deb.png)

HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_044F&PID_B68A\OEM\JoystickSettings\533260927

**Comment by SHWotever** [comment]
P.A.R.F.A.I.T !

**Comment by SHWotever** [comment]
Je m'était promis pas de beta supplémentaire mais ... :D https://www.simhubdash.com/unofficial/SimHub.7.00.3b8.zip

**Comment by Romainrob** [comment]
Inarrêtable! Je vais tester ça.

**Comment by Romainrob** [comment]
YES! 
![image](https://user-images.githubusercontent.com/50543913/81481052-ae14be00-922d-11ea-9573-83120c785ec2.png)

Du coup, question bonus :
La sauvegarde des settings par jeu, c'est par device (en fonction de la roue installée) ou général.

**Comment by Romainrob** [comment]
Ça a l'air général

**Comment by SHWotever** [comment]
C'est général en effet ;)

**Comment by Romainrob** [comment]
Parfait. Merci encore.
Difficile d'imaginer meilleur support!

**Comment by SHWotever** [comment]
Un ticket de plus en moins ;)
