### ISSUE TITLE
Micro stepper gauge support?

### ISSUE THREAD

**Issue by penfold42** [SHWotever/SimHub#569]
I’d love to be able to drive gauges with a micro stepper as described at: https://guy.carpenter.id.au/gaugette/2017/04/29/switecx25-quad-driver-tests/

If I do the Arduino side, can you add support to the GUI ?

**Comment by SHWotever** [comment]
Hi ! 

The feature request already exists : #299, I close this one as a duplicate ;) 

Nicolas
