### ISSUE TITLE
Monospacing and vert alignement

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#570]
Hi again.
I noticed enabling monospacing has a strange effect on vert alignment.
Desktop and HTML won't match unless the text is aligned to the top.
Desktop on the left, HTML on the right:
![Monospacing vert alignement](https://user-images.githubusercontent.com/50543913/81818251-17e2df80-952e-11ea-88c9-e9e3f2e9edac.PNG)

**Comment by SHWotever** [comment]
Hello !
Indeed small behavior variation, hopefully, this time I've found a workaround ;)

**Comment by SHWotever** [comment]
Released with 7.0.5 ;)

**Comment by Romainrob** [comment]
Thanks for the fix! :)
