### ISSUE TITLE
Configure Appearance OLED Display

### ISSUE THREAD

**Issue by 7HUND3R36** [SHWotever/SimHub#571]
In simhub how can I configure what I want to be displayed in iracing?
https://github.com/SHWotever/SimHub/wiki/Arduino-SSD1306-0.96``-Oled-I2C

In this tutorial he talks about templates but it is not clear to me. It only tells you how it connects and little else.

**Comment by SHWotever** [comment]
Hi ! 

The content is defined here C:\Program Files (x86)\SimHub\OLEDTemplate\Ingame\0_Default\part1.ini
![image](https://user-images.githubusercontent.com/2207331/81846930-2bed0800-9553-11ea-8a7d-36e4c58782f0.png)

All the values after the "=" are ncalc formulas as introduced here : https://github.com/SHWotever/SimHub/wiki/NCalc-scripting---Introduction

Nicolas

**Comment by 7HUND3R36** [comment]
But with that I can already show the temperature of tires in iracing and other things?

Why by default the OLED screen only shows the gears and rpm

**Comment by SHWotever** [comment]
Hi ! It's possible to show it indeed, but you need to edit the file I pointed you.

The default display only shows gear and rpm because it's extremely small, and trying to fit more would make it barely readable.

**Comment by 7HUND3R36** [comment]
https://i.gyazo.com/c8ce779f2f720bc9d6ac02589f28c792.png

And that is done from here?

It is that the tutorial was not very clear to me either, since I have to use a google translator to translate from English to Spanish and there are parts that do not define them well.

**Comment by SHWotever** [comment]
No you need to edit manually with a text editor (notepad, notepad++...) the file I linked you above (C:\Program Files (x86)\SimHub\OLEDTemplate\Ingame\0_Default\part1.ini) there is no wysiwyg editor available for it.

Nicolas

**Comment by 7HUND3R36** [comment]
But I don't know what to edit in that file. I want the temperature of the 4 wheels to be displayed on the OLED.

**Comment by SHWotever** [comment]
You can empty it and add any "Text" sections as you need, for instance front left tyre :

```
[Text]
X=50
Y=0
Color=1
Text=format([TyreTemperatureFrontLeft],'0')
FontSize=2
FontType=0
Align=3
```

X is top coordinates of the text,
Y is left coordinates of the text,
Color 1 = is black on white
Color 2 = is white on black
Text is the text formula to be shown
FontSize goes from 1 to 5
FontType is the kind of font goes from 0 to 2
Align 1 is left align
Align 2 is center align
Align 3 is right align

Just add as many of it you need and change the "text"
NB : This example uses shortened properties TyreTemperatureFrontLeft which is available since the last simhub version, make sure to update simhub first if you want to use my example as is.

**Comment by SHWotever** [comment]
NB : On iracing tire temperature telemetry is only updated in the garage not on track, not sure it's worth displaying temperatures on this particular game.

**Comment by 7HUND3R36** [comment]
Yes, I know, the temperature of the wheels is only displayed when you stop in boxes. Do you have a brake temperature option? even if they are only the forwards. Or water or oil temperature. I only have this OLED screen to show temperatures.

**Comment by SHWotever** [comment]
It will work the same way for any data :
You can get all the available properties here :
![image](https://user-images.githubusercontent.com/2207331/81916618-516e2600-95d4-11ea-8a0d-22e1bd29811f.png)
Simply right click to copy the name :
![image](https://user-images.githubusercontent.com/2207331/81916720-7793c600-95d4-11ea-916d-c609fe0688ac.png)

**Comment by 7HUND3R36** [comment]
Ok, then I'll be looking at this.

See you later SHWotever

**Comment by 7HUND3R36** [comment]
Now you can register it to show the temperatures of the 4 wheels. 

https://i.gyazo.com/1acacf84a066a1c350d8faf05befde2f.jpg

Unfortunately iracing does not have brake temperature

https://i.gyazo.com/9c387f80a8c8ca45470e6efbaf456416.png

This is all new to me. I see that simhub is great software. I have never done this kind of thing. I'll be fiddling with the OLEDtemplate to find new things.

BTW, can I get it to display the wheel name along with the temperature on the OLED?

**Comment by SHWotever** [comment]
Nice !

No i'm I can't remember having seen that data yet in iracing.

**Comment by 7HUND3R36** [comment]
He managed to mark the liters of fuel in tank and fuel consumption of the tank:

https://i.gyazo.com/60cb33bf2f88782068f08d9dded9b129.png

**Comment by vilsezapgbg** [comment]
I need help get ettor in verifying in

**Comment by tahir51** [comment]
is it possible to create more than 1 display and switch among them with a button press or so?
