### ISSUE TITLE
Audio Control Plugin - Gain setting

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#573]
Salut,

I'm experimenting with the triggeraction function to embed cool features in a dash.
Today, I added audio feedback on tactile buttons, and I'm considering shifts beeps or even alerts.
And what if it talked ? Maybe not, we'll see :D

Could you please add a way to adjust the audio control plugin volume?
Possibly with mappable controls too so the dash could even have volume buttons?
Let me now what you think. In any case thanks for considering this idea.

Bonne journée!

**Comment by SHWotever** [comment]
Hello !
I've added it in settings :
![image](https://user-images.githubusercontent.com/2207331/82148124-bcc52b80-9852-11ea-98f3-7967c8be3a6a.png)
And as actions (+5/-5) ;)
![image](https://user-images.githubusercontent.com/2207331/82148134-ca7ab100-9852-11ea-9005-c84f28132e58.png)

**Comment by Romainrob** [comment]
Sweet! :) This looks perfect!
Thanks you very much sir! :)

**Comment by SHWotever** [comment]
Released with 7.0.5 ;)

**Comment by Romainrob** [comment]
Thank you for the addition! This will be fun to mess with :)
