### ISSUE TITLE
Static wind - Mute toggle control

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#576]
Hi!
As reported by hockey9999 :
https://discordapp.com/channels/299259397060689920/453962780857597966/711210761879289907
The "Mute toggle control" of the Shakeit Static Wind effect doesn't seem to work properly.
Bon week-end! :)

**Comment by Romainrob** [comment]
Looking at the logs
It always trigger twice :
![image](https://user-images.githubusercontent.com/50543913/82123636-afe50100-979a-11ea-87d7-ba6c731fc259.png)

Maybe this 
![image](https://user-images.githubusercontent.com/50543913/82123651-c4c19480-979a-11ea-85b9-d45f073d1c16.png)
clashes with 
![image](https://user-images.githubusercontent.com/50543913/82123655-cee39300-979a-11ea-9695-5265690dcf18.png)
As one auto-fill the other and the gain controls don't behave the same.

**Comment by SHWotever** [comment]
Hum ! Indeed a sneaky bug, it's fixed for the next version ;)

**Comment by SHWotever** [comment]
Released with 7.0.5 ;)

**Comment by Romainrob** [comment]
Thanks for the fix! :)
