### ISSUE TITLE
ACC: Update GameData.Flag_Name with all available flags

### ISSUE THREAD

**Issue by mihi4** [SHWotever/SimHub#579]
As it looks, ACC has some more flags then blue, blag, white, yellow and checkered:
ACC_FLAG_TYPE
ACC_NO_FLAG = 0
ACC_BLUE_FLAG = 1
ACC_YELLOW_FLAG = 2
ACC_BLACK_FLAG = 3
ACC_WHITE_FLAG = 4
ACC_CHECKERED_FLAG = 5
ACC_PENALTY_FLAG = 6
ACC_GREEN_FLAG = 7
ACC_ORANGE_FLAG = 8

Any chance to update Flag_Name with the appropriate missing names, too? (Green, Orange, but I don't know Penalty *gg*).

It could always be solved with the game specific properties, but using just one property for all sims would be nice.

**Comment by SHWotever** [comment]
Hello ! flag details are available since a few versions :
![image](https://user-images.githubusercontent.com/2207331/102710119-691b3480-42b0-11eb-8f86-7a14b60ab75e.png)
