### ISSUE TITLE
Arduino pro micro

### ISSUE THREAD

**Issue by Peppazzz91** [SHWotever/SimHub#582]
please add support to arduino pro micro 32U4

**Comment by penfold42** [comment]
Pro micro support is already there ?

**Comment by Peppazzz91** [comment]
![simhub](https://user-images.githubusercontent.com/65404453/82557404-f1dfbf80-9b6b-11ea-8e48-cdf5f8ebfcc6.png)
not yet, i fount "micro" but not "pro micro"

**Comment by Peppazzz91** [comment]
why this issue was closed?

**Comment by SHWotever** [comment]
Hello ! Pro micro is often shortened to "micro", I unfortunately ported this naming abuse, It's indeed the pro micro which is available in the setup tool. I renamed it to "pro micro" as it should be for the next version to avoid confusion. ;)

**Comment by SHWotever** [comment]
Hello ! I close this ticket as it's already the arduino pro micro which is supported as explained above.

Nicolas
