### ISSUE TITLE
Repeat low fuel alert - Bug?

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#586]
Bonsoir.

I wonder if there is an issue with the low fuel alert repeat feature.

I suppose this :
![image](https://user-images.githubusercontent.com/50543913/82840847-52585f00-9ed4-11ea-8f52-4b03cc39f39f.png)

should make this blink:
![image](https://user-images.githubusercontent.com/50543913/82840890-77e56880-9ed4-11ea-9f0a-e860570f1c4c.png)

But it doesn't for me.

Bonne soirée!

**Comment by SHWotever** [comment]
Hello ! No it's not a bug (exceptionally :D)the setting drives the low fuel event repetition , but the current status is still low .

**Comment by Romainrob** [comment]
Thanks for the quick answer :)
You mean this one ? 
![image](https://user-images.githubusercontent.com/50543913/82842949-b7fc1980-9edb-11ea-9a77-c040dafe0d64.png)

**Comment by SHWotever** [comment]
Yes it's this one ;)

**Comment by Romainrob** [comment]
Ok. It all makes sense now. Thank you :)
Bonne journée!
