### ISSUE TITLE
X-Plane support

### ISSUE THREAD

**Issue by AfromD** [SHWotever/SimHub#587]
How can I get started for interfacing Simhub with X-Plane? 

I think I can make a plugin for X-Plane, is there an API description for Simhub somewhere, or some guidance which Parameters need to be communicated in what way?

**Comment by SHWotever** [comment]
Hi ! Currently the game reader SDK is not public because is still evolving a lot at each simhub updates. Releasing a public SDK means freezing the features but I still have lot of plans for the future and I'm not ready to lock the features scope, and I'm not sure you would be happy to rewrite parts of your code twice a month ;)

Concerning flight Sims in a general manner, I've post-poned it for now but it will definitely come at a time. There are lot of prerequisites because flight Sims are really different. It requires new shakeit effects, new LEDs effects, new dashstudio controls ... Actually getting data from the game is the small part of the work. But currently I stay focused on improving/reworking SIM racing features, and when I will be happy with that part I will start working on flight sims.

Nicolas

**Comment by AfromD** [comment]
Ok, too bad for now. I am mostly interested in an alternative for my forcefeel cushion. Extra instruments is usually no problem with flightsims, they have provisions for that already.

What I am missing in Simshaker for aviators is a proper implementation of G-Load. The way it is now, G-Load will cause vibration in certain motors. I think it should not cause vibration, but rather should shift existing vibration to different motors. So it should be a translation of other effects, not a vibration by itself.

E.g. when you lift out of your seat, the sitting area should lower vibrations and the shoulder area should increase. With a forward acceleration, that should only act as a gain on the vibrations in the backrest. With Simshaker, it just starts vribrating out of nowhere. That is a cue, but it is not intuitive. You really have to think "hmmm where does that vibration stem from? probably negative g's...". 

My idea is easy to accomplish by configuring an orientation for each vibration source, and then applying a gain according to the acceleration in that orientation.

**Comment by SHWotever** [comment]
I see, I know that indeed "flight-simmers" are well equipped, serious flight sim is another world compared to sim racing, and it's probably even more demanding :D But I don't want to deliver a 25% working thing :D

Concerning the effect you are describing, shifting effects "in 3d" I not something possible currently in shakeit, and probably all the software are using the same approach, all the effects are generating an output or multiple outputs and they get mixed on motors/shakers. This would require adding a "spatialization" layer across all effects. It's not impossible but it does not fit well the "universal" design I gave for now to shake it.

**Comment by AfromD** [comment]
Well, as motion platforms concerned, I think flight simming might actually be less demanding. What you need is pitch, optionally heave, and vibration. Seatbelt tensioners would be nice for negative G. I was playing with the idea of SFX 100, but for flightsim a simple 2 DOF with shaker might also be adequate. The only harsh bumps are touchdown and rolling over grass. Everything that happens in the air is quite smooth. Sideways accelerations don't play a big role. You don't need super fast actuators. 

And for extra displays, most sims already have all kinds of provisions and add-ons for that, as people build home cockpits all the time. But motion is still quite new.

Without giving the effects an orientation, it might also be implemented as a gain in the mixer. So that the energy of an effect in a certain motor could be adjusted to a certain G-load in a certain axis. For a device that provides directional effects like seat cushions, or multiple shakers, one would then have to configure these gains in the mixer in stead of a G-load effect. That would also be valid for racing sims that have sideways and forward acceleration effects.

**Comment by AfromD** [comment]
As for the better G effect, what if I would provide you with a function:
`AccelerationGain( ActuatorPitch as int, ActuatorRoll as int, ActuatorYaw as int, HorizontalG as float,  VerticalG as float, LateralG as float) returns gain as float`
So inputs would be the positioning of the actuator and the current G-Forces. Output would be a multiplier (basically the positive G-Force acting towards the actuator). When your body (virtually gets pressed into the actuator, all of its vibrations increase, when you are pulled away, vibrations decrease.

You would then simply add something like
```
if GForceMixingChecked 
   ActuatorValue = ActuatorValue * AccelerationGain ( 0, 90, 0, GforceH, GforceV, GforceL)
end if

```
To the mixer code of each actuator. The first three parameters describe the orientation of the actuator in relationship to the body, the latter three pass the current G-forces)
I am not a really great programmer, but I can probably produce this in the most common languages. Just tell me what you would need.

**Comment by SHWotever** [comment]
Thanks for the tips ;) For now I close this ticket as Xplane is not in the simhub scope for the above reasons. Maybe by the end of the year if things goes well ;)
