### ISSUE TITLE
Overlays empty

### ISSUE THREAD

**Issue by jesperordrup** [SHWotever/SimHub#588]
When starting a race the overlays are loaded in but they are empty. I can see the contour of the overlays but nothing in them.

IRacing is launched in windowed mode. Tried both border and borderless.

SimHub registeres game launch and says waiting for data until it changes to game running.
I can see that data flows into simhub. 

Dashboards are working.

Fresh install.
Created an overlay layout with maps.
OBS links are also empty.
Tried HTML engine without any change

[SimHub.log.txt](https://github.com/SHWotever/SimHub/files/4701451/SimHub.log.txt)

Help :)

**Comment by SHWotever** [comment]
Hello ! Maps are recorded after the first valid lap on the track.sice you have fresh install the map is probably non recorded and it will stay empty as long as you don't have any valid lap ;)

Nicolas

**Comment by jesperordrup** [comment]
Ohhhhhhh. Thanks Nicolas!
