### ISSUE TITLE
Displays screen out of games

### ISSUE THREAD

**Issue by 7HUND3R36** [SHWotever/SimHub#589]
When I am out of simulator and I leave simhub in windos task bar on LCD and OLED shows me time and date. Is there a way to change this and what other things can you tell me?

**Comment by SHWotever** [comment]
Hi ! 
For oled you need to customize C:\Program Files (x86)\SimHub\OLEDTemplate\Idle\TurboChanged\part1.ini

For other arduino text screens simply locate the current idle screen :
![image](https://user-images.githubusercontent.com/2207331/83383345-3594bd80-a3e5-11ea-9107-0096e5344db7.png)

On the last version I added a final preview of the arduino text screens, which shows which screen  is currently active : 
![image](https://user-images.githubusercontent.com/2207331/83383417-5826d680-a3e5-11ea-97ee-aea803c5f1ae.png)

**Comment by 7HUND3R36** [comment]
Ok, thanks
