### ISSUE TITLE
Folder path, map buttons.

### ISSUE THREAD

**Issue by EBEALIEN** [SHWotever/SimHub#591]
Forgive me Wotever, and I hope you are well!
_See previous topic_ https://github.com/SHWotever/SimHub/issues/316
I'm starting again the realization of the new steering wheel, tested but never fully assembled. Now after a format of my pc, I would like to find the configuration made above of my "KEY", which is the folder path where to find it ??? I installed several times and spread simhub on each disk ....
Thanks - At the end of the project, I will finally post the whole procedure for everyone!

**Comment by SHWotever** [comment]
Hi ! I'm sorry I don't understand " I would like to find the configuration made above of my "KEY", could you explain ?

**Comment by EBEALIEN** [comment]
Yes,
therefore, I in the past, I configured for race setup, buttons connected in the matrix, and encoder, and everything worked very well.
see here: https://github.com/SHWotever/SimHub/issues/316
Unfortunately, I never finished it and I start again now.
The problem is that I have formatted and also updated simhub, I still have the old files and I would like to recover only the button mapping, as I have configured other in the new simhub.
I would like to know where to find the folder containing the mapping that I did.
See photo: 
![immagine](https://user-images.githubusercontent.com/17771086/83390588-67f8e780-a3f2-11ea-995e-0ed93a509299.png)
in which folder can I find my configuration?
I have simhub, saved in several harddisks during the works, and I could find and copy only that, so as not to damage anything else that I have now prepared.
Thank you, forgive me if I translate very badly!

**Comment by SHWotever** [comment]
These specific settings are stored in C:\Program Files (x86)\SimHub\PluginsData\Common\KeyboardEmulatorPluginSettings.json ;)

**Comment by EBEALIEN** [comment]
Perfect, tonight, I'll comment on the outcome if positive,
but I'm sure it will be fine. You have never been wrong!

**Comment by EBEALIEN** [comment]
Perfect,
I never throw away old installations,
and you understood very well what I am always looking for, you are a true professional!
Everything works, now I just have to proceed with assemblies (already tested and functional)
![VOLANTE REAR](https://user-images.githubusercontent.com/17771086/83513195-b5985180-a4d1-11ea-8523-cc0c1512b18d.jpeg)
![VOLANTE FRONT](https://user-images.githubusercontent.com/17771086/83513200-b7621500-a4d1-11ea-98ff-17bcdb08cd9d.jpeg)

For 458 GT2
_I've already contributed with the license,
tell me how I can contribute to your project again._

**Comment by SHWotever** [comment]
Hi ! No need to contribute again ! Just have fun !
