### ISSUE TITLE
Wheels Slip bass shaker problem

### ISSUE THREAD

**Issue by Moore2877** [SHWotever/SimHub#592]
Once the tires go full slip and the rears are just turning free, such as a burnout. The effect will drop off to nothing.

**Comment by SHWotever** [comment]
Hi ! Indeed shakeit uses calibration based on statistics as soon as you will use long free spin the effect will drop. What game are you using ? Depending of the game the behaviour will vary a bit (due to the data being used) .

**Comment by Moore2877** [comment]
I am using iracing, today's update to the tyre model seemed to have fixed the issue I had though. The game maybe giving data now during full wheel spin.

**Comment by Moore2877** [comment]
Thanks for the quick reply. I assume there is no way to make a full wheel spin effect because of that missing data? You can close the issue too, I am happy with the way it's working at the moment. donated 8c too.

**Comment by SHWotever** [comment]
Ah indeed iracing is lacking slip data, it's based on rpm Vs speed ratio change which are the only data available. Unfortunately no improvement to expect about it, iracing is censoring proper slip data to avoid cheating.
