### ISSUE TITLE
7.0.6 Arduino FAN speed calculation issue

### ISSUE THREAD

**Issue by RealTadango** [SHWotever/SimHub#595]
I just started using SimHub and use an Arduino to control a PWM fan as a wind sim, but i have an issue. The fan never get's about 40%, not in testing and not in the game. I have all gain's at 100%. Then i looked at the Arduino code and noticed the issue in SHShakeitPWMFans.h:

value2 = (value2) / 255.0 * (double)maxs[motorIdx];

This results in a value2 value of 100 for a 100% control signal (max at default of 255), which makes sense, but next line expects a range of 0 - 255:

Timer1.pwm(pins[motorIdx], (int)(((float)value2 / 255.0) * 1023.0));

So the max value for a 100% control signal is 401, which is about the 40% pwm my fan runs at.

I think the first line should be:	

value2 = (value2) / 100.0 * (double)maxs[motorIdx]; 

Because the input value is in 0-100% range and not the raw 0-255 value.

**Comment by SHWotever** [comment]
Hi ! I will double check, but in theory input value is 0 to 255 (a full Byte). Have you pushed the global gain slider (on top right of the effects list) ? It's the most common issue when you can't get full power.

**Comment by RealTadango** [comment]
Mmh... global gain? Never noticed that one! Is that on 50% by default????? That is confusing :) I think i have always switched directly to the motors output tab and never saw the global gain slider at all....... Will try with that one at 100% (makes sense now, but very confusing for a new person :))

**Comment by RealTadango** [comment]
Yes, i returned everything back to the default values and had the global gain (hate the thing now ;)) at 50%..... working fine now, thanks!
