### ISSUE TITLE
Software doesn't attempt to launch.

### ISSUE THREAD

**Issue by S0LCR0WN** [SHWotever/SimHub#596]
SimHub will not launch. 
It does not show up in task manager.
It does not start, then crash.
I reinstalled the software to know avail.
Cleared the relevant AppData, and it booted... but only once, as I couldn't launch it after that.

**Comment by SHWotever** [comment]
Hi ! Could you join the log files ? They are available in the "log" folder inside Simhub install directory. It will give me some clues about what is happening.

Nicolas

**Comment by S0LCR0WN** [comment]
[SimHub.log](https://github.com/SHWotever/SimHub/files/4782972/SimHub.log)

**Comment by S0LCR0WN** [comment]
[2SimHub.log](https://github.com/SHWotever/SimHub/files/4782978/2SimHub.log)
[3SimHub.log](https://github.com/SHWotever/SimHub/files/4782979/3SimHub.log)
[4SimHub.log](https://github.com/SHWotever/SimHub/files/4782980/4SimHub.log)

**Comment by S0LCR0WN** [comment]
I had to rename them so that GitHub would let me upload, they had a .1, .2, .3 extension appended to them.

**Comment by S0LCR0WN** [comment]
Sorry for the spam. Here is a new log from a clean install:
[SimHub.log](https://github.com/SHWotever/SimHub/files/4783197/SimHub.log)

**Comment by S0LCR0WN** [comment]
We are working again. 

I'm not sure why but I couldn't get it to launch as admin for a bit but it seems to be working now, and I am happy about it. 

I used the software for an overlay called iRadar because I have to use a very low FOV on my setup and it helps a lot. 

Thank you!
