### ISSUE TITLE
Connect LCD Nokia

### ISSUE THREAD

**Issue by 7HUND3R36** [SHWotever/SimHub#597]
85/5000
How do I connect the Nokia display on simhub? I activate it but it doesn't tell me where to connect it.

**Comment by SHWotever** [comment]
Hi !

Pins are fixed : 
SCLK = A0
DIN = A1
DC = A2 
A4 = CS or SCE
A3 = RST
VCC = 5V
LED = 3.3V
GND = GND

As defined in the sketch :
// Adafruit_PCD8544 nokia1 = Adafruit_PCD8544(SCLK, DIN, DC, CS or SCE, RST);
Adafruit_PCD8544 nokia1 = Adafruit_PCD8544(A0, A1, A2, A4, A3);

Best regards, Nicolas

**Comment by 7HUND3R36** [comment]
OK thanks. Simhub doesn't support iflag right? is that I have a 8x8 rgb led matrix and a colorduino. I can't get it to work with iflag.

**Comment by SHWotever** [comment]
Hi ! No I'm sorry, Iflag hardware is not supported yet.

**Comment by 7HUND3R36** [comment]
I have a question, where should I put it?

// Adafruit_PCD8544 nokia1 = Adafruit_PCD8544 (SCLK, DIN, DC, CS or SCE, RST);
Adafruit_PCD8544 nokia1 = Adafruit_PCD8544 (A0, A1, A2, A4, A3);

I have never played arduino, only through simhub.

**Comment by penfold42** [comment]
You don’t put it anywhere - it’s already there in the code

**Comment by 7HUND3R36** [comment]
I connect the nokia to the arduino nano and in simhun I activate the nokia and the assigned the arduino nano and the COM port and giving an arduino to load gives me an error and the nokia screen does not show anything.

**Comment by 7HUND3R36** [comment]
Why this error?

https://i.gyazo.com/864b7b1349e13489708efbe918f84c5e.png

**Comment by penfold42** [comment]
I don’t get that error When I enable it.

Have you been messing around with the files or updating libraries from the Arduino GUI ?

**Comment by 7HUND3R36** [comment]
Yes, the state playing arduino IDE. anyway i'm going to formaetar and wanted to save all the simhub sketh so that no configuration is erased. Where is the work kept?

**Comment by DJLevel3** [comment]
> Pins are fixed : SCLK = A0 DIN = A1 DC = A2 A4 = CS or SCE A3 = RST VCC = 5V LED = 3.3V GND = GND

Please add this to the wiki! I've been googling for hours to no avail until I found this closed issue!
