### ISSUE TITLE
Simhub does not work in pc2 online. 

### ISSUE THREAD

**Issue by Pietervanacker20** [SHWotever/SimHub#598]
I use simhub in combination with an arduino nano and 8 bit rgb leds. The rev leds work fine in project cars 2. All settings are correct but when i open project cars 2 online it stops working. Do you have a solution.

**Comment by SHWotever** [comment]
Hi ! Could send me the log files after your online session so I can take a look ? (They are in C:\Program Files (x86)\SimHub\Logs)

**Comment by SHWotever** [comment]
Hi I close it for now as I did not had any other reports, do not hesitate if you can send me the logs.

Best regards,
Nicolas
