### ISSUE TITLE
#Lap Delta to Last Lap" Rawdata Always Empty on iRacing

### ISSUE THREAD

**Issue by bobsmash** [SHWotever/SimHub#599]
Before I contact David Tucker at iRacing, can you verify the Last Lap delta in the rawdata connection? I have every other type of delta available, but the last lap delta is transmitting no data.

**Comment by SHWotever** [comment]
Hi ! I'm not on my computer right now, but could you give me the exact property name ? There are so many dynamic data in iracing I want to be sure I'll be seeking for the correct one.

**Comment by SHWotever** [comment]
Just an additional insight : Simhub "learns" the various "raw" properties available in iracing which changes regularly, it means a property seen once will be retained and appear dead (null) if it's not currently fed by the game.

**Comment by bobsmash** [comment]
I'm not on my home computer at the moment either, but I believe it's "LapDeltaToSessionLastLap" - I just want to make certain there's no bug with SimHub before asking David to check, because he'll certainly ask about the application.

**Comment by Romainrob** [comment]
Hi.
I just had a quick look in a solo test session and it seemed to work as expected on my end:
![image](https://user-images.githubusercontent.com/50543913/85424104-cb9cad80-b577-11ea-8567-1126fdfa59e5.png)
So it can work sometimes at least.

**Comment by bobsmash** [comment]
Which track did you use? I am now suspicious that the issue may have just been Le Mans. I will test some other tracks myself when I get home and see how things look. If this turns out to be track related I will contact David Tucker.

**Comment by Romainrob** [comment]
Brands Hatch Indy.

**Comment by bobsmash** [comment]
I was able to get data at Spa in the Ferrari GT3, so that's confirmed. I'll go back to Le Mans with both the GT3 and GTE to test again to see if there's some specific combination that lead to no data. Needless to say the issue definitely isn't in SimHub.
