### ISSUE TITLE
omsi2 DASHproblem

### ISSUE THREAD

**Issue by xuezhe8973** [SHWotever/SimHub#601]
HELLO! When i was producing a dash to use it in the OMSI, i found some problem! **

1. the carnumber can not be identify correrctly(may be my code was no right{[PersistantTrackerPlugin.DriverAhead_01_CarNumber]} this code is from a dash on ETS/ATS, may be this code is only can be used in the ATS/ETS? If the code can not be active in the omsi, how can i find the correct code?)
2. i need the dash to display which line i drive, the bus's detination,and which is next stop.
3.And When i wrote the formula to show the drivername why the output is the word :me?

** i hope this project can become even biggger, that will help us use one kind of the dash instead of changing the dash when i change my game.the picture i send was my dash
![捕获](https://user-images.githubusercontent.com/67494816/85914775-e458dc00-b873-11ea-9aa5-61644b065877.PNG)

**Comment by SHWotever** [comment]
Hi !

Omsi has only a really limited set of data, I've not been able to extract anything related to map or current "mission",

1. [PersistantTrackerPlugin.DriverAhead_01_CarNumber] is only fed in "race conditions" (it's the driver ahead on track), it's not applicable to truck/bus sims.

2. It's not possible currently

Currently you have everything for a working "engine dashboard", but not mission dashboard, you can see the full property list given by the game here when looking for "raw data" : 
![image](https://user-images.githubusercontent.com/2207331/85915999-9381bd00-b84c-11ea-9130-b85c1c5ac573.png)
![image](https://user-images.githubusercontent.com/2207331/85916006-a2686f80-b84c-11ea-9c6f-e57368d87e8a.png)

**Comment by xuezhe8973** [comment]
thats all right ,but i hope the function will be coming soon. Now i will use these raw data, when the other one could be used,please give a information at the feature about the new version client. hope you have a nice day

**Comment by SHWotever** [comment]
Hi ! I close this as Omsi telemetry is very limited and unfortunately I can't extract more data from it.
