### ISSUE TITLE
Project Cars 2 not creating any vibrations

### ISSUE THREAD

**Issue by ahmiie** [SHWotever/SimHub#602]
Other titles are working fine, however no shaker settings work on PC2. Ive enabled UDP and set both options to PC2 and the data packet its sending is set to 1. 

i cant find anywhere on what actual settings need to be setup. Can someone please help?

**Comment by SHWotever** [comment]
Hi ! If you are using the Pc version you need to enable the shared memory option as shown in the instructions, UDP can be chosen in simhub game settings, but it's not recommended for PC : https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#manual-game-configuration

**Comment by ahmiie** [comment]
As a i posted the message, i actually found that link! 

Will test when i get home. Im also about to drop a donation for such a good product. Thanks for looking out for the sim world
