### ISSUE TITLE
[Question] Can I run a TM1638 and OLED from the same Arduino?

### ISSUE THREAD

**Issue by thedave42** [SHWotever/SimHub#604]
I'm having issues with my Arduino Uno connecting with  SimLab after enabling a single TM1638 and OLED LCD at the same time.  This is how I have them connected 
![image](https://user-images.githubusercontent.com/50186003/86299504-4c315e80-bbb5-11ea-9394-5c14b6e5dbaa.png)
When I upload that configuration to my Arduino, Simhub no longer recognizes the device:
![image](https://user-images.githubusercontent.com/50186003/86299596-88fd5580-bbb5-11ea-8d26-d8c672a6def4.png)

Do I need to run multiple Arduinos to use both of these hardware components at the same time?

**Comment by thedave42** [comment]
FWIW if I enable either one or the other they work. Just not both at the same time.

**Comment by SHWotever** [comment]
Hi ! Indeed as described on the wiki only the Arduino mega will allow you to run multiple features at the same time when using an oled display, this is simply caused by the fact the it requires lot of memory which prevents using anything else aside on smaller Arduinos

**Comment by thedave42** [comment]
Thank you!  I missed that on the wiki. :-)
