### ISSUE TITLE
Shakelt Bass Shakers does no work properly for F1 2020

### ISSUE THREAD

**Issue by Quevedosh** [SHWotever/SimHub#607]
Hi, the Bass Shaker function does not work properly on F1 2020, I tried my F1 2019 and it worked excellent but for my F1 2020 when you in the track it vibrates steady so it makes no distinction if you hit something, change gear or go out the road it just stay vibrating until you kill the add.

**Comment by SHWotever** [comment]
Hi ! The UDP data has been changed since the first beta releases, the simhub update should be released soon, time to implement the latest telemetry definitions and test again everything. I hope to release it before 10th of July for the final public release.

Best regards,

Nicolas

**Comment by SchattiGaming** [comment]
Hi,
the vibration output of my Fanatec V3 pedals does not work either. Neither with the wheels lock or with the wheels slip.

Maybe you can have a look over there.

Game: F1 2020

Thx

**Comment by SHWotever** [comment]
Hi ! The simhub update has been released , I close the issue.

Nicolas
