### ISSUE TITLE
Special Characters issue

### ISSUE THREAD

**Issue by LordFrommel** [SHWotever/SimHub#610]
Similar to #353 which was solved for iRacing in build 6.8.0. This one is for Project Cars 2. Hope it can be solved also.

Special characters in the drivers names don't display properly. See attached screenshot for details on driver 11. Issue happens for any Text field where special characters like Ü, ü, ñ, etc are used.

![Screen Shot 07-12-20 at 05 22 PM](https://user-images.githubusercontent.com/46245778/87250442-056d1f80-c465-11ea-93dd-363100fa8134.PNG)

TIA

**Comment by SHWotever** [comment]
Hi ! 

Indeed, I found a solution, it will be fixed for the next update,

Nicolas

**Comment by LordFrommel** [comment]
Looks like it is fixed indeed with 7.1.0.  Thanks.
