### ISSUE TITLE
Unable to run Sim hub suddenly

### ISSUE THREAD

**Issue by Abucha** [SHWotever/SimHub#616]
so Sim hub worked fine. I got myself a license, everything was perfect. Suddenly it stopped working. Now I can't run it. When I click on it nothing happens. I tried all the resets, still nothing. Even the hard reset where i deleted everything and reinstalled. After this it came up and asked to give Admin permission, when i said ok it vanished again. 
My license is under the email id xxxxxxxxxx@xxxxxx.

**Comment by SHWotever** [comment]
Hi ! 
Could you give me the log files ? (it's available in c:\Program Files (x86)\SimHub\Logs) 

Nicolas
