### ISSUE TITLE
Feature Request | F1 2020 - Support UDP Legacy Mode

### ISSUE THREAD

**Issue by MadMaxx89** [SHWotever/SimHub#617]
Hi community,

The current bass shaker plugin for F1 2020 uses the 2020 UDP format to read telemetry.
Still, I'm also using a SRD-9C from Renovatio as dashboard, which requires F1 2020 UDP legacy mode to work properly.

So at the moment I can only use either my dashboard or bass shaker plugin, which is a bit of frustrating.

Therefore could you please add support for UDP legacy mode in the F1 2020 plugin?
That would be really great!

Thanks for your support :)

**Comment by SHWotever** [comment]
Hi !

Unfortunately "legacy mode" is a really downgraded mode (very little data available ...) it's not a viable alternative to make both apps work at the same time (simhub would not work the best for this game), the best option is to encourage renovatio to keep their software up-to date and implement properly f1-2020

As an alternative, in the wait of a proper renovatio f1-2020 implementation, you can disable automatic game detection in simhub settings, select f1 12016 in simhub, and configure the game manually. You will also need to setup UDP forward so both apps will be fed : https://github.com/SHWotever/SimHub/wiki/Sharing-UDP-data-with-other-applications 

Nicolas

**Comment by MadMaxx89** [comment]
Hi Nicolas,

Thanks for the info!

Actually you're right, so hopefully Renovatio will invest a bit of work to get their software updated.
Anyway, in the meantime I can use your workaround, which is a lot better, than using one app only!

Max
