### ISSUE TITLE
Facetracknoir and Simhub?

### ISSUE THREAD

**Issue by nrg1991** [SHWotever/SimHub#618]
Hi, I got a Delan Clip (Head Tracking) and If I start Simhub the Headtracking doesn't work as before (unplayable).
Can someone Help?

Best Regards 

Andre

**Comment by SHWotever** [comment]
Hi !

Do you have some informations about "what" does not works in delan clip and for which game, if somehow it uses telemetry you may need to share it (depending of the game technology : https://github.com/SHWotever/SimHub/wiki/Sharing-UDP-data-with-other-applications)
It may also use a serial port in this case make sure simhub "ignore" it : https://github.com/SHWotever/SimHub/wiki/Troubleshoot-other-hardware-Serial-ports-conflicts

Best regards,
Nicolas

**Comment by nrg1991** [comment]
[](url)
![Unbenannt](https://user-images.githubusercontent.com/59710369/88439279-0e69d380-ce0b-11ea-9e5d-2e8442359b16.png)

**Comment by nrg1991** [comment]
Thank you for your quick reply. I'm a step closer now :D If I Disable my Arduino Hardware then everything works fine. If i Enable the RGB LEDs ..everthings fine. If I enable The Windsim (SIMHUBDASH) then the FPS of the cam drops extremly. But they're on 3 diffenerent Serial Ports.

**Comment by nrg1991** [comment]
Sorry, I'm very new to something like this but I hope I'll make my way through it :) Thank You very much for your Effort!

**Comment by nrg1991** [comment]
I have to try something new.. now the problem is still there even if I turn Arduino off :(

**Comment by nrg1991** [comment]
I try to go on with the UDP Conflict

**Comment by SHWotever** [comment]
Hi ! Are you using an usb hub for both devices ? This looks like an usb slow down. From what I'm understanding everything works but trackir is slowed down. In my experience similar issue is often caused when usb bandwidth is dropping, this can be caused by parasites, usb hubs etc ... I would try to move the devices on another usb port (ideally straight from a back usb port (front panel of computers are sometimes a small hidden usb hub and it's worth avoiding it.)

**Comment by nrg1991** [comment]
I'm an Idiot :D The Arduino Board for the WINDSIM was on an USB hub but I was 100% sure that it is NOT ... Everthing works fine now! Thank you for your very fast Support even if the problem was a nooby one. I've learned of it.

see you next time :)

**Comment by SHWotever** [comment]
Nice ! Hopefully this was an easy fix ! Have a nice day !

**Comment by nrg1991** [comment]
Sorry for disturbing you.. :D I have another problem with the headtracking thing.. I got the camera worked with the 75fps and sorted a lot of things out (usb hub) At the end it was fine WITH simhub + the 2 arduino devices. At least there was  trouble with the arduino uno for the windsim (Sketched up again)the 3 devices should have 3 different serial Ports.. everthings fine. If I reboot the computer the same Problem again. The Framerate of the Camera goes up and down. I Don’t know how to go on. 


Gesendet von Yahoo Mail für iPhone


Am Samstag, Juli 25, 2020, 9:07 AM schrieb Wotever <notifications@github.com>:




Nice ! Hopefully this was an easy fix ! Have a nice day !

**Comment by nrg1991** [comment]
It always happens withe the Arduino Uno for the wind sim. But If I use another USB port and disable-enable COM3 It works until I restart the Computer. Then same problem again.. 

    Am Samstag, 25. Juli 2020, 09:07:36 MESZ hat Wotever <notifications@github.com> Folgendes geschrieben:  
 
 


Nice ! Hopefully this was an easy fix ! Have a nice day !

**Comment by nrg1991** [comment]
okay, now it is working on another USB port.... sorry I'm going crazy... :D I'll let you know If its solved..

    Am Sonntag, 26. Juli 2020, 10:32:00 MESZ hat Andre Kurbel <andre_kurbel@yahoo.de> Folgendes geschrieben:  
 
  It always happens withe the Arduino Uno for the wind sim. But If I use another USB port and disable-enable COM3 It works until I restart the Computer. Then same problem again.. 

    Am Samstag, 25. Juli 2020, 09:07:36 MESZ hat Wotever <notifications@github.com> Folgendes geschrieben:  
 
 


Nice ! Hopefully this was an easy fix ! Have a nice day !

**Comment by nrg1991** [comment]
and now It#s not working with the optimal fps even if I disable/enable teh arduino Nano or switch/disconnet/connect USb port
    Am Sonntag, 26. Juli 2020, 10:37:28 MESZ hat Andre Kurbel <andre_kurbel@yahoo.de> Folgendes geschrieben:  
 
  okay, now it is working on another USB port.... sorry I'm going crazy... :D I'll let you know If its solved..

    Am Sonntag, 26. Juli 2020, 10:32:00 MESZ hat Andre Kurbel <andre_kurbel@yahoo.de> Folgendes geschrieben:  
 
  It always happens withe the Arduino Uno for the wind sim. But If I use another USB port and disable-enable COM3 It works until I restart the Computer. Then same problem again.. 

    Am Samstag, 25. Juli 2020, 09:07:36 MESZ hat Wotever <notifications@github.com> Folgendes geschrieben:  
 
 


Nice ! Hopefully this was an easy fix ! Have a nice day !
