### ISSUE TITLE
Sli-Pro plugin

### ISSUE THREAD

**Issue by lukester1975** [SHWotever/SimHub#619]
Hello Nicolas and anyone else interested.

Firstly, SimHub is great! Especially grateful for the ForceFeel support, given Realtus's lack of support...

Anyway, I have an Sli-Pro and since I've never had the brain power required to figure out the SLIMaxManager interface, I have been using Fanaleds for years - but obviously using SimHub would have various advantages and so I've been looking for a plugin, but couldn't find one.

So I've written a (currently) very simple plugin to interface with the Sli-Pro. It's not very configurable at the moment, as I've simply coded it to do exactly what I wanted. Here's a quick video: https://www.youtube.com/watch?v=ehVvPFf4alU

(This was running AMS2, so the deltas are coming from PersistentTrackerPlugin - not perfect, but better than the nothing that I was getting from Fanaleds - actually the reason I started looking for an Sli-Pro plugin in the first place).

Anyway, if this is of use to anyone, I'm happy to put the code up on GitHub after a bit more polishing and maybe adding some configuration. For example, it might be nice to make use of the parts of the Arduino LED configuration UI in SimHub to configure the Sli-Pro's LEDs. I'm not sure how viable that would be though, are those UI elements even accessible from a plugin? I'd have to ask lots of questions even if they are, I suspect :) (I should point out I'm an old C++ programmer and this is pretty much my first dabble in to C# ... but it's a good time to learn new stuff at the moment.)

Also, my Sli-Pro is sitting in a Roso wheel which I believe has a custom firmware that behaves slightly differently than the standard one, so that would also need looking at - but I can flash it easily enough between them and figure it out ... probably.

Apologies if I've missed an existing Sli-Pro plugin and alternatively let me know if this of use to anyone.

Thanks

Luke.

**Comment by SHWotever** [comment]
Hi ! Currently the led editor is not part of the "public SDK" i'm sorry, it is still subject to breaking changes, and I only release such components access when I'm sure it won't be broken anymore, which is not the case yet.

Nicolas

**Comment by lukester1975** [comment]
OK, is there a way to know what's considered public and what isn't? I can't see any docs (sorry if I've missed them) so was just browsing assemblies...

I had a few requests for it, so FYI a first cut of the plugin is at FYI code and first build is up on github (in description).
