### ISSUE TITLE
Arduino not recognizing 3rd encoder onwards...

### ISSUE THREAD

**Issue by Nammurg** [SHWotever/SimHub#620]
Hello,

I have used the Arduino section within SimHub to setup an Arduino based button box with 4 switches and 3 rotary encoders.
Everything works except the 3rd rotary encoder...
I have tested that the encoder is not at fault as well as the cable continuity to the Arduino board as well as changed the pinout 3-4 times to different pins.
Also, I have swapped the cables between a working and a non working encoder (on the encoder side not on the board). 
The non working encoder started to work and was recognized as encoder-3 and the one previously working, encoder-2, stopped working.
It seems that only two rotary encoders can be driven at any given time?

Regards,
Thanasis

**Comment by SHWotever** [comment]
Hi ! 

Do you have the pinout and arduino model you used ? There is no particular limitation "software side", but depending of the arduino some pins are not useable (see wiki) and some pins may not have the internal pullup resistor. If you used the encoder model as suggested on the wiki (with on-board resistors) this should not be an issue.

**Comment by Nammurg** [comment]
Hello, thanks for the swift reply!

I have attached the original pinout as well as I marked all the pins I tried with a red X
![image](https://user-images.githubusercontent.com/12989252/88651654-d0e2a000-d0c1-11ea-8559-40c0d293229e.png)

I have seen that on a Nano, you can't use pins A6,A7 & D13 after the fact, however, it still did not work with pins A5-A7, A5-A6, D12-D11, A5-D12...

**Comment by Nammurg** [comment]
Managed to resolve it!
It must be the Arduino board as I used pins D12-D10 and it is now working...

Regards,
Thanasis
