### ISSUE TITLE
System.OutOfMemoryException runnin iRacing crashing SimHub

### ISSUE THREAD

**Issue by S1KRR** [SHWotever/SimHub#621]
iRacing
Simhub (with the dashtemplates from RomainRob instelled, using the 488GT3 dash on an android phone via the android app)
Crewchief
Trading paints

Windows 10, latest
Intel i9900K
NVidia RTX2080ti 11G
32Gb mem

After a few laps of racing in iracing, Simhub  desktop application  crashes with a System.OutOfMemoryException
[SimHub.log.1.txt](https://github.com/SHWotever/SimHub/files/4991060/SimHub.log.1.txt)

**Comment by S1KRR** [comment]
Extrapolated one Dash (mercedes AMG GT3) still after roughly 30 seconds Simhub freezes on the desktop.  Here is teh new log
[SimHub-Oncrash.log](https://github.com/SHWotever/SimHub/files/5174813/SimHub-Oncrash.log)

**Comment by SHWotever** [comment]
Hello ! 

Can you send me the link to the dash you are using and exact version in case there are some updates ? 
Have you tried to disable the extra plugin "iRacingExtraProperties" to ensure it's not the cause of the issue ? 

Nicolas

**Comment by Romainrob** [comment]
Hi.
It the issue does come from my plugin, you could try with a more recent version of it. The one that comes with Meekstaaa dash pack is an older one. Here is the latest one. It should be retro compatible with dash pack : 

[Romainrob.iRacingExtraProperties.dll.zip](https://github.com/SHWotever/SimHub/files/5178301/Romainrob.iRacingExtraProperties.dll.zip)

**Comment by S1KRR** [comment]
Hi,

I get the same. SimHub crashes completely, even with the updated DLL..  It seems to be on the Mercedes AMG dash. I will try an alternative dash tomorrow as well to  confirm.  Log attached for reference
[SimHub.log](https://github.com/SHWotever/SimHub/files/5180391/SimHub.log)

**Comment by S1KRR** [comment]
tried the new DLL, but to no avail Decided to pull the dashes I needed from the pack. It did crash or freeze on me some times. On freeze, it would resume after a few seconds. Now it seems to run stable without freezes on single dashes. Since this seems a weird problem and not systematically spread, I would close the ticket.

**Comment by S1KRR** [comment]
As per previous comment: Since this seems a weird problem and not systematically spread, I would close the ticket.
