### ISSUE TITLE
SimHub installed version number as property

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#622]
Bonsoir.
Could you please add the version number of SimHub as a property?
I could use it to notify people to update when needed,  as I often use recently added feature in my dashboards.
Thanks in advance for considering the idea.
Bonne fin de soirée.

**Comment by SHWotever** [comment]
Hello !

Done ;)

to make it useful I also exposed exploded values so it's a little easier to use it :
![image](https://user-images.githubusercontent.com/2207331/102709993-7126a480-42af-11eb-8393-a3607b4c2b39.png)

**Comment by Romainrob** [comment]
Salut.
Merci pour l'ajout :).
J'avais testé des comparaisons comme '7.3.1' < '7.3.2' avec NCalc et ça avait l'air de fonctionner.
Mais je n’avais pas pensé aux betas.
 
Là je teste vite fait des trucs du genre '7.3.2b1' < '7.3.2b2' et ça m'a l'air bon aussi.
Ça m'étonne un peu tbh. Je ne sais pas si c'est 100% fiable comme approche…

Pour mes dash je teste juste si les strings sont différentes car l’utilisateur ne peut pas avoir de version d’avance sur moi. Mais là ça ne va pas suffire.

Je vais ptet effectivement recombiner le numéro de version sans les points.
Ou comparer major, minor et revision « indépendamment ».

Tu utilises quoi comme teste pour la notif de maj de SimHub par example?

**Comment by SHWotever** [comment]
Hello !!

J'ai changé le fusil d'épaule, je n'ai laissé que la version en cours (pas éclatée) et j'ai ajouté une methode pour faire les comparaisons en suivant les règles que j'applique :
compareversions('7.3.1','7.3.2b1')
![image](https://user-images.githubusercontent.com/2207331/103081237-d93ef880-45d7-11eb-9c35-ffeb24debfa2.png)

Ce sera aussi accessible depuis un plugin en utilisant :
`SimHub.Plugins.Configuration.SimHubVersion.CompareToVersion(versionB)`

**Comment by Romainrob** [comment]
Salut,
Ça m’a l’air parfait 👍
Merci et joyeux Noël!

**Comment by Romainrob** [comment]
Salut,
J'ai joué avec CompareToVersion sous NCalc et dans mon plugin.
Tout semble bien fonctionner.
Merci encore!
Bon dimanche.
