### ISSUE TITLE
Nextion circuit map?

### ISSUE THREAD

**Issue by 7HUND3R36** [SHWotever/SimHub#623]
I would like to have a screen where the circuit map in which I am competing and where the rivals start are shown. As shown in this video at minute 6.30

https://www.youtube.com/watch?v=QkT5tGsKJiA

**Comment by SHWotever** [comment]
hi ! No the nextion does not have the capability, the software on the video is a software similar but is not simhub, however simhub can display it too but only on more powerful devices (hdmi monitors phone/tablets/ usbd480 ...)

**Comment by 7HUND3R36** [comment]
The usbd480 interests me, where could I buy one of these? Are there any limitations I should be aware of with this screen? With that, could you show the circuit map in real time iracing with the rivals?

**Comment by 7HUND3R36** [comment]
Looking online, is this model the usbd480?

https://simcore.com.au/dashboard/

See that it comes out vastly expensive, 295 dollars.

**Comment by 7HUND3R36** [comment]
can this be worth?

https://www.z1simwheel.com/m/manual/lcd.cfm

**Comment by SHWotever** [comment]
Hi ! You can buy the usbd480 on the manufacturer website, it will be way cheaper ;) http://www.lcdinfo.com/products/usbd480-wq43.html

**Comment by 7HUND3R36** [comment]
Okay, well I guess you would need this right?

http://www.lcdinfo.com/products/usbd480.html
http://www.lcdinfo.com/products/usbd480-wq43.html

**Comment by 7HUND3R36** [comment]
I already have my USBD480 screen with the circuit map. I would like to be able to assign a button to simhub to control the screen. Some rotary to navigate the USB480 screens. Is it possible to do this?

https://youtu.be/g5V46rRFyXs
