### ISSUE TITLE
Data refresh rate

### ISSUE THREAD

**Issue by Mtrade** [SHWotever/SimHub#627]
Hi,
I have a licensed version of simhub. I notice that the data update speed counter (i.e. refresh rate) in the bottom of the simhub window hovers around 35 FPS. Should it normally be closer to 60 FPS or is this normal behaviour?
Thanks

**Comment by SHWotever** [comment]
Hi ! It depends of what you are running and the current system load,  some  complex dash/plugins will easily make the processing time drop . It's also the case of big arduino setups like many LEDs on the same Arduino (100leds +). Except that it will try to keep running at 60fps indeed in normal conditions.

**Comment by Mtrade** [comment]
Thanks for the reply.
I do not have any arduinos, bass shakers, etc. currently and I only have some overlays installed. The low refresh rate occurs when I first startup simhub. Interestingly, when I load up an overlay layout I have created, then the refresh rate will increase to 50-57 FPS.
I have modern hardware and CPU and memory load are low when this occurs.
Thanks for your help

**Comment by SHWotever** [comment]
It would be worth checking if you don't have any gsync/freesync forced for desktop app, this will interfere with the simhub rendering (which is wpf/directx based) and will slow down the data loop (due to UI interactions)

**Comment by SHWotever** [comment]
Just to be sure, you haven't any third-party plugins installed, some of the overlays you can find will include a plugin and it maybe the bottleneck,   here is the list of the out of box plugins, so you can check if you don't have any others : 
![image](https://user-images.githubusercontent.com/2207331/89800627-54bf7200-db2f-11ea-9dbc-38a9fe006813.png)

**Comment by Mtrade** [comment]
Ok, I believe it's resolved, I had the Gary Swallow plugin installed. I disabled it and the refresh rate is back up to 60. Thanks!

On another note, I do have g-sync enabled for windowed mode as it allows me to run variable refresh in games while having the simhub overlays. It doesn't appear to have any effect on simhubs refresh rate whether I turn it on or off, it is sitting at or close to 60 with g-sync enabled or disabled.

**Comment by SHWotever** [comment]
Indeed , gary's plugin is known to be a 'bit' heavy ;), I'm not blaming it's a complex plugin too :D
About g-sync it's variable, I've seen some issues in the past, but it's not systematic.
