### ISSUE TITLE
Boost and Water gauges not displaying correct values despite settings in simhub

### ISSUE THREAD

**Issue by cazzoo** [SHWotever/SimHub#630]
Hi,

I've bought two gauges that are slightly different that standard ones for Boost and Water temperature.
Boost can go from -0.9 to 3 Bar
Water temp can go from 50 to 150°C

When setting them in simhub to their respective values, and setting their min/max (and zero) outputs to somethings that makes sense, I can see reported values are not matching ingame ones. I tried to tweak output values but it gets really weird and chunky. Even doing so, I'm not able to get any matching gauges in comparison to ingame values. Tested in several games.

Do you know if setting min/max value does affect the outputed values properly ?

**Comment by SHWotever** [comment]
Hi !

About boost it depends of the game, only AC reports boost pressure and on other games as a fallback it will use simply throttle or engine torque if available, and in this case indeed it won't match the ingame display (https://github.com/SHWotever/SimHub/wiki/Arduino-After-Market-Boost-Gauge#important-notes), what game are you using ? 

About water temp, supports was intended for e36 cluster and after several tests it proved to be unstable (see https://github.com/SHWotever/SimHub/wiki/BMW-E36-Cluster-Setup#update-2020-05-20), I can't tell for any other gauges model. (short story : the e36 cluster goes in "error mode" when the input value is changing too fast, as long as the values changes in a "real world" manner it goes fine, but simply exiting the game (going 0°) and entering again (back to a real value) was enough to trigger the behaviour)

About min and max I added a direct preview of the output value and you can see the current game value or simulated : 
![image](https://user-images.githubusercontent.com/2207331/90368952-2f6cbf80-e06b-11ea-8484-8c620a94e3c7.png) not sure which version you are using currently, but this will give you a direct view of the output, you can also measure it using a voltmeter (as it's simple pwm output)

I made some extensive tests recently and I've not seen any particular issues "code wise", except the low availability of the data across games and the "error mode" behavior of the e36 gauge.

Let me know,
Nicolas

**Comment by cazzoo** [comment]
I was testing for both PCars2 (and AMS2) and Dirt 2.
It seems that values are not well reported by the APIs.
I'll try with AC soon
