### ISSUE TITLE
AMS2 Telemetry Tyres Temp IMO

### ISSUE THREAD

**Issue by newtonpg** [SHWotever/SimHub#632]
SimHub I-M-O tyre temperatures don't match ingame telemetry of AMS2.
I-O temps are very height, like superficial temps while Middle temp is very very low.
Other apps like RSTsoftware and SecondMonitor report the expected values.
Since there aren't any other variables related to I-M-O temps, is it possible that SimHub needs an update on the (AMS2) API version?

PS: I'm focused on SimHub as a quick tyre setup tool and these temps are essential to camber setup and pressure setup.
PS²: Inn/Out tyre temps are crossed. It's a minor bug and we can live with that, but better to fix.

**Comment by SHWotever** [comment]
Hi ! Unfortunately these data are not available in the shared memory version of the API which I'm using primarily. so I use the available temperatures which are mTyreCarcassTemp, mTyreRimTemp, and mTyreLayerTemp

I see that the udp API offers it, but I missed it when implementing it, I've updated it to use the proper data, it will be released with the next simhub update you will need to switch to the udp option in simhub game settings : 
![image](https://user-images.githubusercontent.com/2207331/91131256-23a57c80-e6ad-11ea-9aef-9fe12f7ae483.png)
