### ISSUE TITLE
Track disappearing from generated track map when game paused (Dirt Rally 1.0)

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#636]
I noticed the recorded track disappears from the generated track maps (both from the generated track map and the generated static track map) when the game (Dirt Rally 1.0) is paused.

This happens when the race has allready started. When the game has loaded and I'm in the final 'loading screen' the track is shown and remains visible as long as I stay there.

But as soon as the race has started and I pause the game the track disappears after about 5 seconds.

Is this normal behaviour? Can it be prevented?

I'd like to study the track when the game is paused...

**Comment by SHWotever** [comment]
Hi ! Unfortunately, dirt rally 1 does not have a "paused" status, it just stops sending data, in this aspect, there is no difference between exiting the game or pausing it, I've left a 5s "wait" for short pauses, but since there are both "out of game" and "in game" features it's important to get back to disconnected in a reasonable delay.

**Comment by Shaftoe62** [comment]
Ok, clear. And there is no way to overcome this? Or somehow 'know' when I'm "in game' or "out of game"? Because then I could use a static image of the track as an overlay when "out of game".

Like so....

![Screenshot_20200821-234102_SimHub](https://user-images.githubusercontent.com/53898212/91149471-61110680-e6bb-11ea-8ffe-5c73d12163ca.jpg)

**Comment by Shaftoe62** [comment]
And I can probably use the car's coordinates to plot a dot on the map...

**Comment by SHWotever** [comment]
You have the "gamerunning" property, but just like the map it can't make a difference between paused or exited

**Comment by Shaftoe62** [comment]
That doesn't matter. That would only mean that the 'static track' remains visible when I quit the game. That's even a good thing.

I just have to make screenshots like the one above from all the tracks with the 'player dot' 'invisible'. I just make a dash variant for that.

I can work with that. Thanks.

**Comment by Shaftoe62** [comment]
I'm getting there... I have my own cursor following the coordinates of the car in the game along the track. I figured out the scale factor I have to use for my maps (1200 x 1200 px) which is 2.25.

What I need now is a way to get the x and y (and maybe z) correction-factors from each map.

With this I mean that the coordinates can have positive and negative values and these need to be translated to positive values from the top left to draw the cursor.

I've figured them out for one map manually but I'm prettry sure they must allready be somewhere in the recorded maps?

 Can you point me in the right direction here?

**Comment by Shaftoe62** [comment]
Or perhaps you calculate the boundaries of the map based on maximum and minimum x-y values values with an added margin??

**Comment by SHWotever** [comment]
You got it indeed, it's totally dynamic to fit the available space, I store original coordinates from the game (usually meter based coordinates which can be positive or negative, I guess it depends of the "center" of the map modelling.) and when rendering the map I scale it dynamically to fit the space and keep a small margin

**Comment by Shaftoe62** [comment]
Ok, in that case I have to find a way to programmacally unpack the gz files to extract the tm files and process the data for each map. I think I can work out an algoritm to get the correction values I need.

I'm not proficient enough in javascript to know if that's possible. Is it? 

Or otherwise I'll try to do it with php. It only needs to be done once for my purpose and then I will store these correction factors in a fixed script. I mean I don't really need to do that dynamically every time, right?

Can you give me an indication of how large the added margin is?

**Comment by Shaftoe62** [comment]
Sorry, but I really need to know how much margin you add to the 'bounding box' of the coordinates. Is it a fixed percentage or a fixed amount?

I need it to calculate the scaling factor for each map.

Thanks.

**Comment by SHWotever** [comment]
Hello ! Sorry I was at work ;) it's dynamic :
(int)(Math.Max(OpponentStyle.DotRadius + OpponentStyle.DotBorderThickness, PlayerStyle.DotRadius + PlayerStyle.DotBorderThickness) + this.TrackBorderWidth + this.TrackWidth)

**Comment by Shaftoe62** [comment]
Ah! That means you add the margin (in pixels) at the very end, based on these parameters?

Before that everything is strictly based on coordinates?

In that case I can subtract the margin of my target width before I do my calcultions and add it again later, right?

**Comment by Shaftoe62** [comment]
target size, I mean.

**Comment by Shaftoe62** [comment]
Do opponents values still count, even if there are no opponent in a Rally?

**Comment by SHWotever** [comment]
it's just a margin reservation, at this point it just varies depending of the map designer settings since it's not "game dependant", it will use always it in case an "opponent" comes into the party :D

It's not really possible even for me to give you an explicit mapping formula as everything is computed dynamically depending of the inputs, 
In short I have a record containing game map coordinates, then a renderer uses the margin as given by the formula above, the display size needed and the map record in "game coordinates" to render it and will give back to the map component the picture and the coordinates system to use to map from "game coordinates" to "pixel coordinates".

**Comment by Shaftoe62** [comment]
It's good to know that those imputs affect the margin of the map in this way. Because I am making all those satellite backgrounds, now I know I have to stay away from these settings! Or nothing will fit afterwards!

And because I will not change these parameters anymore I can use them to calculate a fixed margin. So that's fine.

**Comment by Shaftoe62** [comment]
Got it!

Results:

==================
Coordinates in simhub-mapdata/9665.99.tm: 13601
Array
(
    [x] => Array
        (
            [max] => 3085.4914550781
            [min] => 534.27178955078
        )

    [z] => Array
        (
            [max] => 198.75437927246
            [min] => -360.17849731445
        )

    [y] => Array
        (
            [max] => 481.65814208984
            [min] => -2028.4184570312
        )

)
width: 2551.2196655273
height: 2510.0765991211

Extra width: 0
Extra height (times 2): 20.571533203125

Targetsize in px (after substraction of margins): 1134
Scalingfactor: 2.2497527914703

x_shift: 204.48022074977
y_shift: -943.76228375086

=============

And those 'shift' values are fixed values for a specific map. As is the scalingfactor.

Now I can do:

x = $prop('CarCoordinates01') / scalingfactor - x_shift
y = $prop('CarCoordinates01') / scalingfactor - y_shift

That gives me the coordinates of the car in px on my 1200 x 1200 map.

**Comment by SHWotever** [comment]
Nice ! A bit of hardwork I agree :D
