### ISSUE TITLE
Can entire overlays, dashboards or groups of components be turned on or of based on the "gamerunning" property?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#637]
The only way I can find to make things visible in either "in game" mode or in "paused" mode is by putting a formula in the opacity of every component of the overlay in question. 

Is there another way?

**Comment by SHWotever** [comment]
When using overlays this possibility is built in : 
![image](https://user-images.githubusercontent.com/2207331/91274220-a8140000-e77e-11ea-9725-5f5b1039b245.png)

It's not the case for dashboards as they are intended for secondary monitor and this is not needed.

you can also assign a role to pages in a dashboard when in game or out of the game and simhub simm automatically select the relevant one : 
![image](https://user-images.githubusercontent.com/2207331/91274439-f923f400-e77e-11ea-8ffb-22e3dafd2f1b.png)

**Comment by Shaftoe62** [comment]
I think I've tried all of these settings but I did't get it to work What I want to achieve is this:

![image](https://user-images.githubusercontent.com/53898212/91284344-10b5a980-e78c-11ea-9ac0-ae6532ebcdae.png)

**Comment by Shaftoe62** [comment]
And I have made (or am making) the different component as 'overlays'. The large (outer) rectangles are 'overlay layouts'.

**Comment by Shaftoe62** [comment]
![image](https://user-images.githubusercontent.com/53898212/91285062-03e58580-e78d-11ea-8bd1-d2dc932f7378.png)

**Comment by SHWotever** [comment]
Ah ok I see, you want to switch content. This is not possible easily, mainly because I don't want useless content to stay in the background when running the game (even if hidden).  I have to keep the out of box possibilities reasonable concerning performances and system load.

**Comment by Shaftoe62** [comment]
I have very powerful PC. sometime ago I thought: 'hmm... Dirt Rally is not running as smooth as usual...' Turned out I was running Red Dead Redemption Online in 4k and HDR on full max ultra settings in the background...

But I understand your concerns. Although the way I have to overcome that limitation will put more strain on the processes than a buit-in solution:

I will simply develop some special functions that I can call in every opacity field. One way or another, I will get it done.

**Comment by Shaftoe62** [comment]
Also, I will need some sort of trigger/toggle to hide all the 'show-in-pause' elements on a keystroke.

Can I capture keystrokes using only Javascript?

**Comment by SHWotever** [comment]
Well I have to think wider :D if everyone's computer was high end it would save me hours of digging for a few tenth of cpu usage :D

You can read input status by using "inputstatus" properties : 
![image](https://user-images.githubusercontent.com/2207331/91310791-98aeaa00-e7b2-11ea-861a-d47eae7bf5e0.png)

It's dynamic so expect a null before the first press of the input, you can use isnull(property, defaultvalue) to get a default value.

**Comment by Shaftoe62** [comment]
That's ok, I dont need to worry about the load and I don't mind a little bit of extra effort.

Those are the keystrokes Backspace, D F, S and Printscreen, I presume? No joystick (wheel) buttons?

**Comment by SHWotever** [comment]
It will work with both, i just made my screenshot with keyboard, but any "simhub inputs" will appear here (joystick button box, arduino buttons, ...)

**Comment by Shaftoe62** [comment]
You mean if I search on those term? I'm at work now so I can't check. Is there a list online somewhere? So I don't need to bother you about things like that...

**Comment by SHWotever** [comment]
Yes it will appear in the property list, (just make sure to press the input first). You will find it in the formula editor property picker and in the "available properties" tab, just search for "inputstatus" you will find them all .

**Comment by Shaftoe62** [comment]
Fantastic. I have a G29 that I could program to give keystrokes but I prefer to leave the buttons "as is".

**Comment by Shaftoe62** [comment]
Earlier you mentioned that the visibility of the map tracks has a built-in delay of 5 seconds when the game is paused or quit before the track disappears.

But I think you actually mean that the 'gamerunning' property has this delay built-in. Because when I make an items visibility dependent on 'gamerunning == 0' it appears at exact the same moment the track disappears. 5 seconds after the game is paused.

Is there any way I can set this delay to another value? Preferably 0.

**Comment by Shaftoe62** [comment]
The above I mean...

**Comment by Shaftoe62** [comment]
I found a simpler solution to my needs. I can use the existing toggle for show/hide overlay in combination with showing/hiding components based on 'gamerunning'.

So when the game pauses or exits the dash elements disappear and the full satellite map (with latest coordinates) is dispaplayed (after 5 seconds ;-). I can then use the existing toggle to hide the map so I can see the game menu's. I just have to remember to switch the dash elements back on. Not perfect but works for now.
