### ISSUE TITLE
Elevation profile based on map coordinates?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#638]
Wouldn't it be nice to have an elevation profile for Rally tracks? Perhaps even with the position of your car moving along it...

**Comment by Shaftoe62** [comment]
Ay, I now see that the LapDistance is not recorded in the map data. That pretty much rules this out. 

I could use the LapTimes (Keys) for a approximation but that won't be very accurate and probably a bit distorted. 

Laptimes are always different so a 'live' elevation profile is not possible. That won't work without the LapDistance.

I could generate an elevation profile as an svg to get a bit of an impression but not much else.

Without the LapDistance there is very little use for the z -coordinates. Either record the laptimes or perhaps leave the z -coordinates out to save space?

**Comment by SHWotever** [comment]
Hi ! Lapdistance would be a plus, but it is not needed for me, distance can be computed using the 3d coordinates  (sum of the distance between each point) ,lapdistance given by the game would not match the record because it's often based on the ideal line not the actual travel done and is not given by all the games neither, but I need a cross-game solution that's why I did not retain lapdistance. Only 3d coordinates were consistent enough for my needs (delta computation, map  ....).

**Comment by Shaftoe62** [comment]
"lapdistance given by the game would not match the record because it's often based on the ideal line not the actual travel done and is not given by all the games neither" 

That's true but it would be much easier for me to work with. But if you have a formula for me how I can calculate the distance based on coordinates I won't complain...

**Comment by SHWotever** [comment]
It's simple :D
Distance between poits A and B :
√((bx - ax)² + (by - ay)²  + (bz - az)²)

Since games are always giving coordinates in meter this will give you a meter result using stored coordinates.

**Comment by Shaftoe62** [comment]
This idea also made me realise that I can generate my own 'tracks' as SVG's. Then I won't be needing the static map 'plugin' at all for my purpose of the satellite maps. 

Then I can control the margin better as well since I will be using the same settings and formulas for the track svg as for the placement of the cursor in Simhub.

Also, I will be no longer dependent of the resolution of my tablet (I made screendumps of the rendered tracks to make the satellite images) I can make them 4k if I want to.

What I want to achieve is that when I pause the game, I get a large satellite map with my position and all sorts of other info (like the elevation profile and perhaps 'hazards') on my main (4k) screen. For that I made that other issue concerning 'gamerunning on/off'. I'll get back to that over there.

**Comment by Shaftoe62** [comment]
> √((bx - ax)² + (by - ay)² + (bz - az)²)

Fantastic, thanks. That opens a world of possibilities. I'm not a math buff. I'm a graphic designer by trade. But I love this sort of stuff. :-D

**Comment by Shaftoe62** [comment]
> √((bx - ax)² + (by - ay)² + (bz - az)²)

Wow, This calculates the distance in 3d even. Can I leave the z factor out in my case? I''' project that to the y axis of my elevation 
profile. I need the distance between A and B in the x-y plane.

**Comment by SHWotever** [comment]
the elevation map would need to ignore the z axis I guess as it is a z projection over 2d position (x,y) converted to distance. In this case you can simply remove the "Z" part of the formula.

**Comment by Shaftoe62** [comment]
The formula works perfectly! 

But I get a very stange result at the  beginning of the race.

The first distance after the start is a jump of more than 15 meters while all the subsequent distances remain below  1 meter.

Do you have any idea what causes that?

distance[0] (00:00:00) = 0 - elevation = 136.64489746094
**distance[1] (00:00:00.0670000) = 15.909833229322 - elevation = 137.66369628906**
distance[2] (00:00:00.1330000) = 0.038540451142329 - elevation = 137.66577148438
distance[3] (00:00:00.2000000) = 0.068978476180347 - elevation = 137.6708984375
distance[4] (00:00:00.2670000) = 0.097016840009105 - elevation = 137.67686462402
distance[5] (00:00:00.3330000) = 0.1188100739725 - elevation = 137.68664550781
distance[6] (00:00:00.4170000) = 0.16965495443772 - elevation = 137.6990814209
distance[7] (00:00:00.4830000) = 0.14886243442244 - elevation = 137.70788574219
distance[8] (00:00:00.5500000) = 0.15905677695649 - elevation = 137.71408081055
distance[9] (00:00:00.6330000) = 0.21205126148952 - elevation = 137.71978759766
distance[10] (00:00:00.7000000) = 0.18237590915216 - elevation = 137.72894287109
distance[11] (00:00:00.7830000) = 0.24415838749166 - elevation = 137.74600219727
distance[12] (00:00:00.8500000) = 0.2032432670352 - elevation = 137.75996398926
distance[13] (00:00:00.9330000) = 0.26339981737246 - elevation = 137.77842712402
etcetera...

**Comment by SHWotever** [comment]
The first 15 meters are before the starting line and the game doesn't simulate physics during the animation, and so there is no elevation.

**Comment by Shaftoe62** [comment]
This idea also made me realise that I can generate my own 'tracks' as SVG's. Then I won't be needing the static map 'plugin' at all for my purpose of the satellite maps. 

Then I can control the margin better as well since I will be using the same settings and formulas for the track svg as for the placement of the cursor in Simhub.

Also, I will be no longer dependent of the resolution of my tablet (I made screendumps of the rendered tracks to make the satellite images) I can make them 4k if I want to.

What I want to achieve is that when I pause the game, I get a large satellite map with my position and all sorts of other info (like the elevation profile and perhaps 'hazards') on my main screen. For that I made that other issue concerning 'gamerunning

**Comment by Shaftoe62** [comment]
> The first 15 meters are before the starting line and the game doesn't simulate physics during the animation, and so there is no elevation.

It's literally the second datapoint. So there is no game physics whatsoever during that phase? Then I guess I make it a straight horizontal line. Or perhaps just skip the first datapoint.

The total sum of the calculated distances is 53 meters short of the 'official' track length. Where could the have gone??

official: 9666
calculated: 9613.0447371914

**Comment by SHWotever** [comment]
Honestly I don't know :D, since it's the actual traveled distance cumulated with the "approximations" of float coordinates given by the game, it could explain a little difference, there are also a few meters before and after the race which may not be taken into account (I'm not sure about that last point).  In all cases, the question is also on what is based the "official distance",and if it's a comparable value, if it's a center road line, the difference with a real trajectory is not surprising.

**Comment by Shaftoe62** [comment]
It's not that important, really. It's what the game itself says when you choose a rally. So it's somewhere in a tekst file of the game. It could be anything.

For recording the maps I drive every track first at a very leisurly pace and I take care to stay in the middle of the road. I don't follow a 'racing line'.

I hoped that would give me a precise and 'realistic' map. And it does.

It now also has the benefit that I have a datapoint every 70 cm on average. Which is perfect.

**Comment by SHWotever** [comment]
Ok ;)

**Comment by Shaftoe62** [comment]
I know enough now to build a small php app that can generate svg's in different resolutions of the tracks and of the elevation profiles and that will also write a parameter file with stuff like the mentioned scale factor and x and y shift amounts to correctly place the cursor in SimHub.

The track svg's I will then process in Photoshop to integrate them with the satellite maps of different resolutions for use either on my tablet or on the main screen. Same will go for the elevation profiles.

**Comment by Shaftoe62** [comment]
Thanks a lot. You have been very helpful. Kudo's!

**Comment by Shaftoe62** [comment]
Initially I started with Simhub because I bought a Buttkicker. But I soon got distracted by the tantalising possibilities Dash Studio has to offer. All the things I've been missing (or wanting) in Dirt Rally now are possible.

That reminds me: can I find a noob guide to the Simhub SDK somewhere? I mean how to set things up and stuff?

**Comment by Shaftoe62** [comment]
Result!

![image](https://user-images.githubusercontent.com/53898212/91448550-4afd7480-e87a-11ea-943c-edf6b83f43c4.png)

**Comment by Shaftoe62** [comment]
All based on recorded map data exept for the input of the real world altitude at the start. The altitudes shown in the images are correct.

Greece
![elevation_profile 9666 5 1680x840](https://user-images.githubusercontent.com/53898212/91612705-402c0800-e97e-11ea-8e89-9e3785b77e04.png)

Finland
![elevation_profile 14954 68 1680x840](https://user-images.githubusercontent.com/53898212/91612740-56d25f00-e97e-11ea-81c6-51f51cc24ee5.png)

Pikes Peak
![elevation_profile 19476 5 1680x840](https://user-images.githubusercontent.com/53898212/91612775-694c9880-e97e-11ea-90a9-006532a0f35b.png)

**Comment by Shaftoe62** [comment]
And I can generate them in any resolution I might need:

![elevation_profile 9665 99 720x360](https://user-images.githubusercontent.com/53898212/91612928-bfb9d700-e97e-11ea-85b2-6176c2f9534d.png)
