### ISSUE TITLE
How can I make a 'toggle' based on the input of a (joystick) button?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#641]
How can I use the input of a (joystick) button to toggle the visibility of an item in Dash Studio?

I'm using javascript as scripting language.

And I'm looking for an example javascript to do this.

**Comment by Shaftoe62** [comment]
Hello? Do you get my messages?

**Comment by SHWotever** [comment]
Hello ! Sorry I was at work. It's not possible like this. But you can wrap it in a widget add an empty page, and your page with content. When added to your main dash you will be able to select which action (a/b/c/D) will trigger the page change for the widget. Last step, map this action in dashstudio settings.

**Comment by Shaftoe62** [comment]
Ok, thanks. Did you see my question about the 5 seconds delay before 'gamerunning' is triggered?

**Comment by Shaftoe62** [comment]
I found a simpler solution to my needs. I can use the existing toggle for show/hide overlay in combination with showing/hiding components based on 'gamerunning'.
