### ISSUE TITLE
Problem to recognize 2 Arduinos together....... COM conflict???

### ISSUE THREAD

**Issue by Robbyc78** [SHWotever/SimHub#642]
Hi guys,
I have this problem with Simhub and COM port.
I’ve connected separately via usb, 2 rumble motors for the pedal and my ITR SW F1 wheel with display nextion e led bar (the wheel is connected to the PC with only 1 usb port used for nextion display e leds both).
When, in the Arduino section, multiple Arduino, I launch the devices search, simhub is not able to recognize separately rumble motors and led bar (the display nextion, instead, works correctly), but recognize just only one of these (usually only the motors)
If I connect only the wheel, Simhub find the leds and they work fine; If after I connect the usb motors and I re-launch the search for new devices, simhub disconnect the leds (and the relative Com port disappear), and it finds only the motors COM port!!!!! So I cannot play whit leds and rumble motors working togheter.
I believe is not a problem of connection, because it find the devices separately and it assigne 2 different COM ports to them.
I tried every usb port combination without solve the problem.
Can anyone help me?

Thanks in advance

**Comment by SHWotever** [comment]
Hi ! Did your you gave unique names at upload ? If the names are the same for both devices simhub won't be able to consider them properly as two separate devices : https://github.com/SHWotever/SimHub/wiki/Arduino-Multiple-devices-support#how-to-configure-multiple-arduinos

**Comment by Robbyc78** [comment]
Yes the name is the same "simhub dash" for both. How can I change them? To connect the devices I've just connect the usb port and anything else.
Sorry but I'm not expert about tit, and I'm afraid to do same mistakes and to compromise the devices.

**Comment by Robbyc78** [comment]
Yes the name is the same "simhub dash" for both. How can I change them? To connect the devices I've just connect the usb port and anything else.
Sorry but I'm not expert about tit, and I'm afraid to do same mistakes and to compromise the devices.

**Comment by Robbyc78** [comment]
Yes the name is the same "simhub dash" for both. How can I change them? To connect the devices I've just connect the usb port and anything else.
Sorry but I'm not expert about tit, and I'm afraid to do same mistakes and to compromise the devices.

**Comment by Robbyc78** [comment]
Yes the name is the same "simhub dash" for both. How can I change them? To connect the devices I've just connect the usb port and anything else.
Sorry but I'm not expert about tit, and I'm afraid to do same mistakes and to compromise the devices.

**Comment by SHWotever** [comment]
Hello ! Ok so that's the reason,

When you upload the arduino sketch you can set the name in the arduino setup tool, it's the very first option : 

![image](https://user-images.githubusercontent.com/2207331/91854814-94780600-ec64-11ea-84f1-9a6bab433d38.png)

**Comment by Robbyc78** [comment]
I didn't upload anything manually, when i installed the devices. Must I just change the "device name", selecting the correct COM port e push upload? Doing in this way, there isn't the risk to reset all?

**Comment by Robbyc78** [comment]
The problem is I bought the devices already configured, so i don't have any arduino's sketch.

**Comment by SHWotever** [comment]
Ah ok, since the only solution is to re-upload the Arduino sketch with a new name, the best way is to ask your seller to reconfigure you one of the devices with a new name so you can use both at the same time. I admit it's a bit sad that they didn't took the time to set a customized name out of box, that would have avoided you this struggle :(

**Comment by Robbyc78** [comment]
Ok, solved!!!!!
Thank u very very much.
