### ISSUE TITLE
Compensate for Windowed borderless distortion

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#643]
Many games don't have a native windowed borderless option. 

So if I want to use an overlay for such a game I need to use a third party utility that makes the game windowed borderless.

These utilities make the window borderless by stretching the image so borders and taskbar are no longer on the screen.

But by doing so the image gets distorted.

That also includes the overlays in an overlay-layout.

That could be remedied if it were possible to stretch overlays vertically or horizontally.

Now the aspect ratio of overlays is locked. 800 x 600 px can be resized but the aspect ratio will remain 8 x 6.

Would it be an idea to be able to 'unlock' the aspect ratio so one can compensate for the windowed borderless distortion?

**Comment by SHWotever** [comment]
Hello !

Unfortunately this is a rare case and getting picture distorted means another rendering effect with the related performances impacts. Overlays being already playing with the limits, that's something I won't implement
