### ISSUE TITLE
Can I make a "circular gauge" run counter clockwise?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#644]
What I'm trying to achieve is a 'mirrored' circular gauge that runs in a counter clockwise direction.

I've been trying all kinds of values for the circular gauge but it only seems to want to go clockwise...

**Comment by Romainrob** [comment]
Hi. Try setting a negative SweepAngle value.

**Comment by Shaftoe62** [comment]
Ah, I was looking at the wrong component. The 'simplified' circular gauge component does not have a SweepAngle setting.

Solved! Thank you!
