### ISSUE TITLE
Documentation on setting up SDK

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#645]
Where can I find some straight forward step by step  documentation on setting up the Simhub SDK environment?

And some examples to test if it works?

**Comment by SHWotever** [comment]
Hi ! You just need to install visual studio 2019 (community edition is enough), you just need the .net desktop development module, then open the solution "User.PluginSdkDemo.sln" everything is configured to build straight in the correct directory  
Nicolas

**Comment by Shaftoe62** [comment]
Ok, I'll give it a shot.

Thanks.
