### ISSUE TITLE
DashStudio: Any restrictions on font types?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#646]
Are there any restrictions on font-types one can use in DashStudio?

I was trying to use a specific font some time ago but is didn't show correctly in the dashboard or the editor. I could select it as a font in DashStudio but it got replaced by Ariel or something. That was an OTF font.

So that made me wonder if only certain font-types can be used or that the problem might be something else.

Several restarts of Simhub didn't remedy the problem so I quickly switched back to a font I knew was working. I didn't try rebooting though.

**Comment by SHWotever** [comment]
Hi ! Fonts are a jungle world, with lot of malformed fonts etc, for the best compatibility make sure to use TTF fonts. The restrictions are those linked to the WPF technology, but I could not find a guideline about that on the microsoft website. I guess that a properly formed font is what it needs, but i've encountered lot of fonts badly converted from various formats.

**Comment by Shaftoe62** [comment]
Yeah, I know all about the font jungle... That's why I ask in advance before I start searching for the cause of the problem.

I will convert the OTF fonts I need to TTF and test them thoroughly in Adobe Illustrator before using them in DashStudio. That should be a safe route.

Thanks
