### ISSUE TITLE
Copy to clipboard?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#648]
Is there a way to copy data (from at text component) to the Windows clipboard from a running overlay?

I would like to use a text component to return specific (debug) data and copy that to my clipboard.

Now I need to go back to Dash Studio and open the 'formula' of that element to be able to select and copy the returned value(s).

I would like to be able to do that by pushing a joystick button (or any other key) for example while still in the game.

**Comment by SHWotever** [comment]
As you may guess it's so specific that it does not exists ;)
As a workaround you can use the sdk to create an "action" which will give you full access to clipboard using .net , then you can map your action a key/input or even dashboard button to trigger this code.

**Comment by Shaftoe62** [comment]
Ok, I'm trying to compose an inventory (in my head) of everything I need to get to where I want to go with a "game (racenet) independent" time registration solution for multiple players on one account solution.

And this might have been a way to circumvent the need for the SDK but alas.... :-)
