### ISSUE TITLE
Access MySQL database with SDK?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#649]
Another related question:

Can I connect to a (MySQL) database directly using the SDK? If I'm going to make the effort to learn the SDK to register sector/lap times for multiple players etc, I might as well do it properly.

**Comment by SHWotever** [comment]
The "SDK" is 1% about simhub interactions, 99% about c# (the language) possibilities, I never had to connect to mysql through c#, but i'm pretty sure it's possible, google should help you.
