### ISSUE TITLE
Dash Studio: Which properties govern the movement and rotation of the dynamic map component?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#650]
As the title says: I'd like to know which properties are used for the movement and rotation of the dynamic map component.

**Comment by Shaftoe62** [comment]
What I try to achieve is to have a satellite (background) image move and rotate in sync with the track.

To do that I need the above infos but also the formulas that are used for the resizing of the track at high speeds (zoom). 

Can you give me all that?

**Comment by SHWotever** [comment]
Hello I use a smooting based on coordinates (direction vector computation smoothed with multiple samples), I could have used yaw, but it's not available in all games and it's not what I wan't in case of spinning)

**Comment by Shaftoe62** [comment]
Yeah, I noticed it wasn't the yaw as given by the game. So it's probably a complicated formula for which I need the SDK? :-P

**Comment by SHWotever** [comment]
Zoom is a basic algorythm based on speed, 
I'm sorry I can give you only the basics about how it woks but I can't give it the exact details because it's "internal" to simhub and nothing must be built around it so I keep freedom to improve/change it when required.

**Comment by Shaftoe62** [comment]
Ok, fair enough. I'll stick to blurred versions of the satellite maps as background images for now. So they have the same color-scheme of the static map which will be next to it in the overlay layout.

Perhaps it's an idea to have the option to attach a background image that moves rotates and zooms in unison with the track in a future version?

**Comment by AlexLaSarthe** [comment]
Possibly related: I have been toying with the idea of the ability to label turns, with numbers, or names, or even pace notes... ?

**Comment by SHWotever** [comment]
Hi ! Unfortunately after all those years this request remained very very rare. I close it for readability purpose even if the the feature would be interesting.

**Comment by NickoLopez** [comment]
I would love to have at least an option to display turn numbers on track maps.
