### ISSUE TITLE
Pantallas máximas de 7 segmentos

### ISSUE THREAD

**Issue by m4nu311** [SHWotever/SimHub#651]
Hola

En la wiki pone que soporta 6 max7219 conectadas en cascada, quiere decir que si conectas otras 6 en cascada soportaría 12, y max7219 y tm cuántas soportaría simultáneamente

Gracias un Saludo

**Comment by SHWotever** [comment]
Hi ! I'm sorry I don't understand your question (Google translate is barely understandable), could you write it in English please ?

**Comment by m4nu311** [comment]
hello, the thing is, I want to put more than 6 7-segment displays, in the
wiki it says that simhub supports up to 6 connected in cascade, the
question is, can I connect 5 in cascade and then 5 in another cascade
connection and also  6 or tm1637 6 digits and 1 tm1637 4 digits ??  I hope
it is understood, Greetings

**Comment by SHWotever** [comment]
Hi ! 
No it's not possible to add more max7219 , 6 is the maximum supported from a single data pin and for wiring clarity I don't want to add another data pin couple.
About tml1638 a maximum of 6 is supported too, this is based on the widely spread tm1638 boards allowing to use 6 tm1638 in cascade using ribbon cables,

Tml1637 supports up to 8 modules but uses more pins.

They can be combined at will up to **overall 20 displays connected** on one or more arduinos.

Nicolas

**Comment by m4nu311** [comment]
Hello

I already assemble the screens, now I have some configuration doubts. it
has some delay, could it be because it is mounted on an arduino uno and not
on pro micro, should I change it to the micro?  I wanted to put on screen 2
of the photograph the difference with the front pilot and on screen 3 the
difference with the rear pilot, what configuration do I have to look for?
Is it possible to put the rating points of competitions that you win or
lose? Can you put times by sectors 1,2 and 3, best and current time of the
secter?  thank you and sorry for the inconvenience

**Comment by m4nu311** [comment]
Hello

I already assemble the screens, now I have some configuration doubts. it
has some delay, could it be because it is mounted on an arduino uno and not
on pro micro, should I change it to the micro?  I wanted to put on screen 2
of the photograph the difference with the front pilot and on screen 3 the
difference with the rear pilot, what configuration do I have to look for?
Is it possible to put the rating points of competitions that you win or
lose? Can you put times by sectors 1,2 and 3, best and current time of the
secter?  thank you and sorry for the inconvenience
