### ISSUE TITLE
Simhub suddely doesn't start/open

### ISSUE THREAD

**Issue by Jazzmega** [SHWotever/SimHub#653]
Hi all!

I didn't change anything on the computer. It just suddely doesn't start. I tied everyhting here:
https://github.com/SHWotever/SimHub/wiki/SimHub-Troubleshootings

I updated to last version but didn't work.

I attach all logs here: (some of them have several months, I think the only valid is the last one)

[Logs.zip](https://github.com/SHWotever/SimHub/files/5219833/Logs.zip)

Hope anybody can help me.
BTW I have the paid version but it shows free version on the log, I assume it is because I deleted all folders.

Thanks a lot!

**Comment by SHWotever** [comment]
Hi !

Looks like something has enabled the windows "fips" policy (disabling usage of some crytographic algorythms),
I tried to enable it and I ended with the same result (and some other software crashing too)

You will need to get your hands into the registry to disable it : 
Open the registry editor and go to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy (you can paste it in the address bar and set enabled to 0 
![image](https://user-images.githubusercontent.com/2207331/93116194-3d8b1b80-f6bd-11ea-9db4-7d135a580df9.png)

I made you a registry file to disable it (always check the registry file by yourself before executing so you know what it's doing, mine is not harmful, but that's a general security rule of thumb :D) 
[FipsAlgorithmPolicy.zip](https://github.com/SHWotever/SimHub/files/5219931/FipsAlgorithmPolicy.zip)

Indeed if you reseted it you will need to reapply license, just reuse the file you got by mail ;)

Let me know,
Nicolas

**Comment by Jazzmega** [comment]
That was AWESOME! Thanks a lot, it is perfectly working!

Btw, another donation on the way... greetings!

**Comment by SHWotever** [comment]
Thanks a lot ! 
Happy that it solved it !

Nicolas
