### ISSUE TITLE
Option to turn of script execution for components, groups and layers

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#656]
In the times table I made I use different colors voor better and worse times. Therefore I have to place each time in a different text element and each has to make the same 'expensive' calculation twice.

That's taking a heavy toll on performance.

So now I have to build in that this script is only executed when visible. Again twice for each component.

It would be very useful if I could turn of script execution for whole groups and layers. Or even whole overlays. Not just the visibility.

**Comment by SHWotever** [comment]
hi ! It' already the case in most situations, hidden groups/layers will prevent execution of child items (except for web engine due to a technical limitaion) and for each components the visibility is evaluated first, then if visible the other properties will be evaluated.

**Comment by Shaftoe62** [comment]
Hmm, I wonder if that is true in my case. Let me show you what I've done.

The screens below are both the same overlay layout. One "gamerunning", the other "paused" mode.

All purple rectangles are seperate overlays that contain groups/layers with all the components of that overlay. Those group are set to visible/not visible depending on when I want them to appear.

The green rectangle is giving me the most grief. If I remove that overlay from the layout the performance of the dynamic map (left MFD in cockpit) increases dramatically. There all the delta's for the previous laps are calculated based on their preceding best laptimes.

So now I'm working on a function that determines the 'state' of the game more precise/varied than just 'running/not running': notstarted, gameloaded,getready, laprunning, paused, etc. And I plan to use that to accurately execute only the functions/calculations that are needed at any given point.

But you say that's not necessary?

P.S. there are some more overlays in the layout for in case there is no best time reistered yet (so no live delta). But those are minor. And some debugging infos as well. So there are at least some 15 - 18 overlays in the layout.


![paused-overlays](https://user-images.githubusercontent.com/53898212/93665299-a84da580-fa75-11ea-9aae-7fb20cd6873b.jpg)

![running-overlays](https://user-images.githubusercontent.com/53898212/93665323-d8954400-fa75-11ea-8e6d-f8f72da788f3.jpg)

**Comment by SHWotever** [comment]
Hi ! I confirm that child execution gets suspended once it is in an hidden group/layer .
