### ISSUE TITLE
Overlays and dashboards don't show up in rFactor 2

### ISSUE THREAD

**Issue by PANCHOBALL** [SHWotever/SimHub#657]
Hello,
recently I downloaded simhub, and I since used it on rFactor 2, I found it very helpful so thank you. 

Yesterday I bought my license and all was working fine, until i uninstalled simhub to then reinstall it in the other hdd i have in my pc. I cleanly uninstalled all the files, and for the reinstallation I unzipped the zipped .exe file and then executed, so I don't know what I did wrong.

The issue is that after this reinstallation, any ovrlay or dashboard I activate from simhub doesn't work in game, the game deosn't literally detect them I think.

Here you can find the only two Logs I have, since I reinstalled it this morning again and I tried using with only two overlays: https://mega.nz/folder/NjYxiSrY#pDog-aT3e203P7b1tH02SQ

Thank you in advance

**Comment by SHWotever** [comment]
Hi ! I see two things, the game is not connecting but maybe you were not in a race ? 
I also see missing images in the dashboard you are using "Icons\wheel2.png", i don't know the design you are using but if it's using simply this image it will probably appear as empty due to this missing image.

**Comment by PANCHOBALL** [comment]
Hi Wotever, thanks for the tempestive answer!
I were in practice, not in race, but it always worked also in practice and qualifying. The overlay doesn't detect the wheel2.png because the overlay is a pedals+wheel, but, since I didn't want the wheel, I simply didn't put the .png, and, previous to the issue, it worked perfectly, I saw the pedals but I didn't see the wheel as I wanted, so I think that this error of the wheel2.png always occurred but because I wanted it. I now try in race and see if I trigger it.

**Comment by SHWotever** [comment]
Ah ok, practice or race it the same, does the game is still in windowed or borderless mode ?

**Comment by PANCHOBALL** [comment]
Yes, it's always been in borderless mode.

**Comment by PANCHOBALL** [comment]
Hi Wotever, I have just nopticed that on the top left of the screen, on the light blue bar, there's written: "SIMHUB - RFACTOR 2 - GAME DISCONNECTED", even if I see that the game is all configured and son on, maybe this causes the issue?
