### ISSUE TITLE
High cpu usage in windows 10 dev channel

### ISSUE THREAD

**Issue by mcmZero** [SHWotever/SimHub#659]
Windows Insider Program Dev Channel OS Build 20215.1000
![image](https://user-images.githubusercontent.com/2320910/93940835-29ec4e80-fd68-11ea-9aa8-2ad258d28fa8.png)

Everything work fine.
but SimHubWPF process use too high cpu
![image](https://user-images.githubusercontent.com/2320910/93940482-7daa6800-fd67-11ea-8482-dee8b67dac49.png)
[Youtube link](https://youtu.be/DA8svvNP_3I)

Please check my log file
[SimHub.log](https://github.com/SHWotever/SimHub/files/5264147/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! could you try on official windows channel release ?(release preview channel or "non insider build"). Windows 10 dev channel is said as "unstable" and it's probably a bug which will never hit stable windows 10 releases.
