### ISSUE TITLE
raceroom - sector best lap time non enregistré

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#662]
Hello
J'ai un problème sur raceroom et sector 3 indique que ce problème provient de simhub
le problème : sur une course, à la fin du 1er tour uniquement, les sectorxbestlaptime ne s'enregistrent pas.

Sur ce 1er tour, j'ai bien les sector1 et 2 qui s'enregistrent mais sur le passage de la ligne d'arrivée, ca ne bascule pas vers les sector best lap time
A partir du 2ème tour et +, tout s'enregistre parfaitement

sur un entrainement, il n'y a pas ce problème. Il est uniquement présent en course
en mode replay, je n'ai pas non plus le problème. Il est seulement présent pendant que je joue.
très bizarre

j'ai aussi fait un essai sur rfactor 2 et je n'ai pas de problèmes

**Comment by SHWotever** [comment]
Effectivement celui ci était subtil, tout le temps de la grille de départ le tour est indiqué comme invalide par raceroom, et donc je ne prenait pas en compte le tour, j'ai ignoré cette donnée (tour invalide) le temps des feux de départ et je récupere bien le tour comme valide désormais,

Nicolas

**Comment by herve4545** [comment]
cool
merci

**Comment by SHWotever** [comment]
Hello ! Je viens de publier la mise à jour ;)

**Comment by herve4545** [comment]
Tout fonctionne parfaitement maintenant
