### ISSUE TITLE
raceroom track record

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#663]
Sure raceroom, de temps en temps, le track record ne s'enregistre pas
j'ai remarqué que la taille du fichier correspondant au track record est de 60 à 70Ko et j'ai un seul fichier présent dans le dossier concerné
ex : SimHub\PluginsData\RRRE\PersistantTracker\Motorland Aragón-Motorcycle Grand Prix\Porsche 911 Carrera Cup (964)
Lorsque le track record ne s'enregistre pas, j'ai remarqué que dans le dossier concerné, il y a plusieurs fichiers présents dont certains ne font que quelques centaines d'octets et pas quelques Ko.
Je supprime ces fichiers de quelques centaines d'octets et cela rentre dans l'ordre avec l'enregistrement du track record qui se fait

le problème existe pour n'importe quelle voiture et n'importe quel circuit

Par contre, le problème existe toujours pour la Porsche Cup car dans le jeu il y a 2 voitures portant ce même nom mais appartenant à des classes différents
il y a la "Porsche 911 GT3 Cup" de la classe "Porsche 911 GT3 Cup"
il y a la "Porsche 911 GT3 Cup" de la classe ""Porsche 911 GT3 Cup Allemagne"

**Comment by SHWotever** [comment]
Hello ! J'ai corrigé en intégrant l'id unique de voiture, la contrepartie c'est que toutes les données passées seront perdues mais les nouvelles seront bien assignées à la bonne voiture,
Concernant les records vides j'ai renforcé les sécurités pour détecter les faux positifs, et eliminer au mieux ceux qui existent déja, 

Je devrais envoyer le mise à jour ce week-end ;)

Nicolas

**Comment by herve4545** [comment]
merci

**Comment by SHWotever** [comment]
Hello ! Je viens de publier la mise à jour ;)
