### ISSUE TITLE
raceroom track record sur version 7.1.1

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#665]
Hello
Avec cette 7.1.1 sous raceroom, il semble que tous les tracks record soient perdus.
pour chaque binome voiture/circuit, le track record ne se charge plus sur le dash alors que j'ai bien un track record

Il y a bien un fichier présent sur \Software\SimHub\PluginsData\RRRE\PersistantTracker\{track}\{car}
mais le track record n'est pas chargé par le dash

je viens de faire cette course : **Motorland Aragón-Motorcycle Grand Prix** avec la **Porsche 911 Carrera Cup (964)**

le track record effectué pendant cette course est moins bon (2.07.870) que le véritable track est de 2.06.719
Ce 2.06.719 est stocké dans le fichier 00.02.06.7190_20200913_102912.tm.gz
ce fichier n'a pas été mis à jour à la fin de la course....sans doute parce que mon temps est moins bon mais mon dash n'a pas chargé ce 2.06.719

Un problème de datastore.db ?

[00.02.06.7190_20200913_102912.tm.gz](https://github.com/SHWotever/SimHub/files/5286893/00.02.06.7190_20200913_102912.tm.gz)

**Comment by SHWotever** [comment]
Hello ! 
Pour rendre unique les voitures j'ai du changer les noms des voitures pour le stockage, normalement il y aura un nouveau dossier avec un nombre devant comme ici : 
![image](https://user-images.githubusercontent.com/2207331/94344333-d6eff100-001e-11eb-881c-704461e9cdac.png)

tous les anciens records ne sont plus utilisables car le nom a changé omme je le diait ce matin, j'ai analysé les voitures de RRRe et il avait de trés nombreux autres cas c'est pourquoi j'ai du changer le mode de stockage et m'assurer que chaque voiture soient bien uniques.

**Comment by herve4545** [comment]
Ok ça marche

**Comment by herve4545** [comment]
J'en profite pour signaler que pour les dtm 2020, il y a 2 classID 2901 et 2905 de mémoire
2905 pour dtm 2020 esport
2901 pour dtm 2020
Ou l'inverse je ne sais plus

**Comment by SHWotever** [comment]
Ca doit couvrir ce cas aussi, j'ai mis l'id de la voiture dans le nom qui est décliné par classe, un id = une voiture+une classe, comme ca il n'y aura plus de problèmes avec ce genre de conflits. Visuellement le nom sera toujours le meme, mais en interne Simhub fera bien la différence.
