### ISSUE TITLE
raceroom - DataCorePlugin.Computed.Fuel_RemainingTime

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#666]
Hello
Il semble que DataCorePlugin.Computed.Fuel_RemainingTime ne fonctionne plus
Il est toujours à zéro
j'ai fait plusieurs courses avec la même voiture sur le même circuit en mode LAP et TIME et il est toujours à zéro
dans mes souvenirs, sur les versions précédentes, il indiquait toujours le temps restant pour la quantité d'essence embarquée quelque soit le mode de course LAP ou TIME
Je ne suis pas sur mais il me semble que ce problème est apparu avec la 7.1.1

**Comment by SHWotever** [comment]
Hello !

En effet, on corrige d'un coté ca bloque d'un autre :(, j'ai publié un hotfix il y a quelques minutes.

Nicolas

**Comment by herve4545** [comment]
Hello
La V7.1.2 n'a pas résolu le problème...je n'ai rien vu dans la log....sauf ceci 
---->[2020-09-27 17:03:13,865] INFO - CurrentLap invalidated for Fuel stats

[SimHub.log](https://github.com/SHWotever/SimHub/files/5288518/SimHub.log)


je n'ai pas ce problème dans rfactor 2

**Comment by SHWotever** [comment]
Ah effectivement, je n'arrivais plus a récuperer l'historique des tours ce qui empéchait le calcul a cause du changement pour dédoublonner les voitures, (petit changement gros risque :( ). J'ai tout restesté historique, fuel, carte, ca a l'air bon, j'ai envoyé la mise à jour, fingers crossed !

**Comment by herve4545** [comment]
j'ai fait un test rapide et ca fonctionne :)

**Comment by SHWotever** [comment]
Parfait ! Merci pour ton retour !
