### ISSUE TITLE
GTR2 Plugin not working/activated 

### ISSUE THREAD

**Issue by lemmingsch** [SHWotever/SimHub#667]
Since the Upgrade to 7.1.1 (also on 7.1.2), GTR2 shows only Waiting for sim.
The Release Notes sounds promising, wating for that: :-)
GTR2 now uses a dedicated plugin instead of simplified game shared memory (it makes more data available )

Must the plugin activated seperatly or how i can check its activated ?

GT Legends still is working, may there also an dedicated plugin available for more data ?

**Comment by SHWotever** [comment]
Hi ! GTR2 is the steam version ? The plugin should get automatically installed using steam version ?

In the game settings you should see this message if the plugin is correctly installed :
![image](https://user-images.githubusercontent.com/2207331/94371076-01f84480-00f4-11eb-8b57-c5b861042dfe.png)


GTL has been left untouched, even if it's close to the GTR2 it does not suports the plugin.

**Comment by lemmingsch** [comment]
Hi

Thanks for the reply.

Its a custom installation with lots of mods, was running fine until the upgrade to 7.1.1.
![gtr2running](https://user-images.githubusercontent.com/71981579/94371194-fe18f200-00f4-11eb-95b2-2924b1adaa1e.JPG)

Can the XD Tool and the Simhub plugin run together ?

**Comment by SHWotever** [comment]
Ah ok, currently the status is only for the steam version, simHub won't detect the status for other installation folders
I see that I forgot to update my manual instructions to point to the rf1 plugin instructions 
Can you go in C:\Program Files (x86)\SimHub\_Addons\GamePlugins\RFactor1 and follow the howto instructions ? 
You have to copy the rFactorSharedMemoryMap.dll dll into [GTR2 folder]\Plugins (create the folder if it is missing)

**Comment by SHWotever** [comment]
I just released a small hotfix to make it point to the correct manual instructions, obviously only the steam version will be correctly detected for automatic configuration, but the manual instructions are now pointing to the correct instructions for plugin use.

**Comment by lemmingsch** [comment]
Thanks, but looks in my installation copy the files to plugin not helps. This may because some files are changed, for example the gtr2.exe itself (4GB Patch).

**Comment by SHWotever** [comment]
Ah ok, unfortunately customized exe is hard to support, as a fallback i added the old working mode, you need to select it in game configuration : 
https://simhubdash.com/unofficial/SimHub.7.01.4b1.zip
![image](https://user-images.githubusercontent.com/2207331/94373103-61aa1c00-0103-11eb-89b5-30d49e03b6de.png)

**Comment by lemmingsch** [comment]
Hi Wotever

Thanks for this option, now i get the data back in "my" GTR2.

Tested a bit more and reinstall my gtr2 Installation from the Steam Version and added the 4GB Patch from http://www.ntcore.com/4gb_patch.php. And this is still working with Telemetry Plugin. Needs a bit more testing with all the Mods/Online but would be awesome if i had the additional data in SimHub for GTR2. The gtr2.exe of my installation is exact the same as on Racedepartment; https://www.racedepartment.com/downloads/no-cd-patch-for-gtr-2.14171/

Also use GTL still alot (www.altbierbude.de), so would be nice if this addition may also possible. XD Tools looks quite similar to the GTR2 one. 

Best Regards

**Comment by SHWotever** [comment]
Thanks for the feedback, 

About cracked GTR2, the game is still sold (so it's not abandonware) so I won't investigate it : I don't support non legit versions of games for obvious copyright reasons ;).

About GTL I tried the plugin but unfortunately it did not get loaded,and there is no alternative documented  plugin interface at my knowledge (XD uses d3d9.dll detouring which is far from being an officially documented game access.)

Nicolas
