### ISSUE TITLE
External scripts stop running - When using an iRacing car for the first time only

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#668]
Hi.
I'm restarting with a clean SimHub install after my mishaps yesterday and I stumbled upon an issue consistent with a few reports I had these last few weeks.
Seemingly limited to iRacing.
When loading a telemetry replay, or the game, with a specific car for the first time, all external scripts properties disappear.
After restarting SimHub, they're back and loading the same car is fine. But loading a new car, for the time will break it again.
Not a big deal but weird.

https://youtu.be/vavsrskSwrI

**Comment by Romainrob** [comment]
No errors in the logs as long as nothing uses these properties: 

[SimHub.log.1.zip](https://github.com/SHWotever/SimHub/files/5288806/SimHub.log.1.zip)

**Comment by SHWotever** [comment]
Here we go ! It should fix it ! Indeed the datacoreplugin properties where violently deleted when the game reader was triggering data list update, but some were not recreated

https://simhubdash.com/unofficial/SimHub.7.01.4b1.zip

**Comment by Romainrob** [comment]
That was fast!
It looks all good on my end now. :)
Thank you once more!

**Comment by Romainrob** [comment]
Hi again. I think it's safe to close this one too ;)

**Comment by SHWotever** [comment]
Ah true ! Thanks ! I forgot this one in the changelog !
