### ISSUE TITLE
Udp port forward for Richard Burns rally. 

### ISSUE THREAD

**Issue by angelovzr** [SHWotever/SimHub#669]
Please add a Udp port forward for Richard Burns rally since there is no Udp relay anymore.

**Comment by SHWotever** [comment]
Hello !

I've recovered the plugin from its death :D, here is a version including it : https://www.simhubdash.com/unofficial/SimHub.7.01.4b2.zip

The plugin won't enable automatically, as it's redundant with the all in one forwarding system available in the game config ,you simply have to enable the plugin in simhub settings, currently the new forwarding system is intended to be more simple, but it's not possible to add it to RBR (simhub does not use UDP, so there is nothing to be forward).

**Comment by angelovzr** [comment]
Thank you for including the plugin!! Exactly what I needed.
