### ISSUE TITLE
raceroom - track record probleme

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#671]
Hello
Je crois qu'il y a toujours quelques problèmes avec le track record sur la v7.1.3

est il normal qu'il y ait plusieurs fichiers présents dans \SimHub\PluginsData\RRRE\PersistantTracker\Motorland Aragón-Motorcycle Grand Prix\4865,Formula RaceRoom Junior ?

avec la frj sur aragon, j'ai un temps de 2.02.268

simhub m'a affiché ce temps et il l'a perdu pour m'afficher 2.05.256
A un moment donné, j'ai eu un track record à 00.00.000 puis est venu 2.05.256

[00.02.05.2560_20200929_134641.tm.gz](https://github.com/SHWotever/SimHub/files/5298789/00.02.05.2560_20200929_134641.tm.gz)
[00.02.15.0250_20200929_134436.tm.gz](https://github.com/SHWotever/SimHub/files/5298790/00.02.15.0250_20200929_134436.tm.gz)

![1](https://user-images.githubusercontent.com/58605557/94555790-69310880-025c-11eb-88b7-99452b3f0669.jpg)
![3](https://user-images.githubusercontent.com/58605557/94555825-70581680-025c-11eb-9882-e9f2cda5bbba.jpg)

**Comment by SHWotever** [comment]
Est ce que ce serait possible d'avoir les fichiers de logs associés pour aider au diagnostique ?

**Comment by SHWotever** [comment]
En tout cas pour les multiples fichiers oui c'est normal ils sont automatiquement purgés de temps a autre au niveau chronologie ça a l'air très ok, le plus récent est le meilleur temps. 
Concernant le tour loupé j'ai peut être une piste, je ne prends que les tours valides, y a t'il une sortie de piste ? Quand le temps au tour passe a zéro c'est que le tour est invalide et dans ce cas là je ne l'enregistre pas. Ça a l'air de concorder. Dans les logs je devrais pouvoir le vérifier

**Comment by herve4545** [comment]
je viens de faire une course de 9 tours
sur cette course, j'ai fait 2.02.920 et simhub me l'a bien affiché sur mon dash
j'ai relancé une autre course et simhub m'affiche 2.03.538 dès que j'arrive sur ce circuit sans avoir quitté les stands
![1](https://user-images.githubusercontent.com/58605557/94560212-984a7880-0262-11eb-94ed-2f3117fb341b.jpg)
[SimHub.log](https://github.com/SHWotever/SimHub/files/5299050/SimHub.log)
![2](https://user-images.githubusercontent.com/58605557/94560377-dba4e700-0262-11eb-8349-ded76c32f581.jpg)

oui, pour les tours invalides, j'ai bien remarqué que quand je fais une sortie en dehors de lapiste
1) estimated lap time = track record
2) le last lap s'enregistre quand même si la sortie a lieu pendant le tour en cours
3) le last lap ne s'enregiste pas si la sortie a lieu juste avant l'entame du tour car raceroom prévient que le prochain tour sera invalide

**Comment by herve4545** [comment]
cas reproduit
mon temps de 2.03.186 que j'ai sauvegardé a été perdu par simhub dans mon dossier courant
on dirait que quand simhub fait le ménage, il supprime tous les meilleurs temps

![1](https://user-images.githubusercontent.com/58605557/94991026-8af1fe80-0580-11eb-8aba-13408906a470.jpg)

**Comment by herve4545** [comment]
en complément,
j'ai supprimé le fichier 00.02.04.4440_20201003_135040.tm.gz et je l'ai remplacé par le fichier 00.02.03.1860_20200930_131458.tm.gz qui était sauvegardé et j'ai récupéré mon meilleur temps....Normal

Cela confirmerait donc que lorsque simhub fait le ménage dans ces fichiers
\Software\SimHub\PluginsData\RRRE\PersistantTracker\Motorland Aragón-Motorcycle Grand Prix\4865,Formula RaceRoom Junior
--> simhub supprime tous les fichiers présents

**Comment by SHWotever** [comment]
Hello !

Ca m'a pris un peu de temps mais normalement c'est bon, le temps n'était pas enregistré probablement car la detection de tours incomplets était un peu trop aggressive. Je l'ai rendu plus tolérante, j'ai aussi allégé ce qui se passit lors d'un nouveau tour, c'etait probablement la cause de quelques seconds perdues en début de tour qui se manifestait par un rejet à l'enregistrement.

J'ai fait pas mal de tours (petits et grands circuits) et je n'ai pas eu d'anomalies.

**Comment by herve4545** [comment]
Hello
OK ca marche
Il faut bien avouer que ca se produisait plutôt rarement voire très rarement. Je ne l'ai pas eu une seule fois pendant la semaine....et je joue tous les jours :)
