### ISSUE TITLE
[Feature Request] - Property list improvements

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#672]
Hi.
I have (yet more :) ) quality of life suggestions for you. Regarding the property list this time.

1. It would be really handy to be able to use the OR operator in the property list search field to easily monitor multiple specific properties in a single window. A simple dashboard can do the trick but it takes a little editing every time.

2. In the property picker I noticed we cannot use the * character, as we can in the available properties list.

3. Probably not realistic but being able to search a property from its value instead of its name could be helpful when hunting down weirdly names ones with known values. Maybe a "search by value" checkbox that would create a snapshot of the property list, alowing for filtering through frozen values could work?

4. Regarding events and actions, I wish something could be done to help inserting them into formulas. Having to find them and figure out their full names proved challenging for me at first. These may not warrant their own insert buttons for now, but it could be something to keep in mind if more functions make use of them in the future.

As always, thank you for considering these ideas. Hopefully some of them you will like, and are doable.
Have a nice day! :)

**Comment by SHWotever** [comment]
Hello !

An easy answer for the first one ;)
You can watch multiple values by adding ";"
![image](https://user-images.githubusercontent.com/2207331/94558396-24a76c00-0260-11eb-9d7a-28a250118344.png)

I need to study the others ;)

**Comment by Romainrob** [comment]
Damn!
I wish I knew that all along.
Thank you!

**Comment by Romainrob** [comment]
Hi! Thank you for the changes to the property picker in 7.1.4 :)

**Comment by tbs66** [comment]
“being able to search a property from its value instead of its name…”

This feature would be wonderful. I record a stint and then use that recording to work out my dash tweaks. I pause the recording so that I can browse the raw data values in the property lookup.

**Comment by SHWotever** [comment]
Hi ! I added "Search inside values" for the next release : 
![image](https://user-images.githubusercontent.com/2207331/184540710-23e47098-9021-4822-96fc-3d3f0b7c5894.png)

**Comment by Romainrob** [comment]
Very nice! Thank you! This will come handy for sure.
I'm curious about how it'll handle changing values.
Will the prop appear and disappear has its value changes?
Or is the value frozen at the time of the search?

**Comment by SHWotever** [comment]
It's frozen at search time, redoing the search regularly would be really heavy;)

**Comment by Romainrob** [comment]
Good to know. This makes sense. Thank you :D
