### ISSUE TITLE
iRacing flags - Not updating - The revenge! :)

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#674]
Hello!
Following https://github.com/SHWotever/SimHub/issues/594
I'm afraid the iRacing flags issue is back.
I couple people have reported it on Discord and I was able to confirm it:
https://discordapp.com/channels/299259397060689920/306850631271055362/760597079151607808

**Comment by Romainrob** [comment]
Hi! I had a quick look at the flags using a race replay.
I can the confirm the fix included in 7.1.4 works on my end.
Thank you ;) !

**Comment by SHWotever** [comment]
No problems ! Thanks for the feedback !
