### ISSUE TITLE
More granular controls

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#676]
Hi.
I think the following controls would benefit from an adjustable change steps setting:

1. Game volume. Currently at 10% per input
2. TM FBB gain. Currently at 1% per input
3. Low fuel alert trigger. Currently at 1 lap per input. Having adjustable in decimal would be nice.

Thanks you for considering the idea
Bon dimanche! :)

**Comment by SHWotever** [comment]
Pif paf pouf ! I added some to the main settings panel :)
![image](https://user-images.githubusercontent.com/2207331/97153327-99dc6300-1772-11eb-8dd6-28b91f5b6797.png)

Fuel settings in car settings : 
![image](https://user-images.githubusercontent.com/2207331/97153385-b2e51400-1772-11eb-81e2-9bab0ee56bef.png)

And TM here ;)
![image](https://user-images.githubusercontent.com/2207331/97153410-bd071280-1772-11eb-94b4-2ce7b0b9e7b9.png)

**Comment by Romainrob** [comment]
Sweet!
Thank you for these additions. :)

**Comment by Romainrob** [comment]
Bonsoir,
I played a bit with the news settings. This is great 👍 .
The new system volume control is a good idea. I'll definitely add system volume buttons to my SimHub button box 💯 .

A have a couple nitpicks still:
1. I've noticed the step used is double the value entered for the system volume. Either that or it trigger twice per press.
2. Regarding the UI. For the game and system volume buttons mapping, the decrement line is above the increment one. No big deal, but I messed up my mapping the first time round, and it's not consistent with other settings.

Thanks again for all the improvement of the last update
Et bon week-end!

**Comment by SHWotever** [comment]
Hum ! indeed, better stay consistent with ordering, it's changed !
Ah indeed I was using system volume "shortcuts", but it behaves only with 2% steps, I replaced it with direct volume control, only downside it won't show anymore the windows volume popup.

**Comment by SHWotever** [comment]
Aaaand it's released ;)

**Comment by Romainrob** [comment]
I'll look at the dash notfication message then.
Working great 👍 Thanks you again!
