### ISSUE TITLE
Cycle only through favorite dash - Bug?

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#677]
Hi.
Here is a bug Kalsia reported this on Discord. I was able to confirm it on my end.

It seems this checkbox doesn't work as intended:
![image](https://user-images.githubusercontent.com/50543913/95692450-2b51be00-0c26-11eb-9f4e-2e4b8bbeebda.png)

It only cycles through the favorites dashboard even if unchecked.
No error in the logs.
Have a nice day !

**Comment by Romainrob** [comment]
Hi.
It's seems you crushed this little bug on the last version.
Well done! :) Thank you!

**Comment by SHWotever** [comment]
Thanks a lot for the feedback !
