### ISSUE TITLE
NextionMicroBridge Error

### ISSUE THREAD

**Issue by matthewbaines** [SHWotever/SimHub#680]
When attempting to upload the NextionMicroBridge Arduino file I receive an error message:

Arduino: 1.8.12 (Windows 10), Board: "Arduino Leonardo"

NextionMicroBridge:37:1: error: 'Adafruit_NeoPixel' does not name a type

 Adafruit_NeoPixel WS2812B_strip = Adafruit_NeoPixel(WS2812B_RGBLEDCOUNT, WS2812B_DATAPIN, NEO_GRB + NEO_KHZ800);

 ^~~~~~~~~~~~~~~~~

C:\Program Files (x86)\SimHub\_Addons\NextionMicroBridge\NextionMicroBridge.ino: In function 'void ReadLeds()':

NextionMicroBridge:42:3: error: 'WS2812B_strip' was not declared in this scope

   WS2812B_strip.setBrightness(Serial.read());

   ^~~~~~~~~~~~~

C:\Program Files (x86)\SimHub\_Addons\NextionMicroBridge\NextionMicroBridge.ino:42:3: note: suggested alternative: 'WS2812B_DATAPIN'

   WS2812B_strip.setBrightness(Serial.read());

   ^~~~~~~~~~~~~

   WS2812B_DATAPIN

C:\Program Files (x86)\SimHub\_Addons\NextionMicroBridge\NextionMicroBridge.ino: In function 'void setup()':

NextionMicroBridge:125:3: error: 'WS2812B_strip' was not declared in this scope

   WS2812B_strip.begin();

   ^~~~~~~~~~~~~

C:\Program Files (x86)\SimHub\_Addons\NextionMicroBridge\NextionMicroBridge.ino:125:3: note: suggested alternative: 'WS2812B_DATAPIN'

   WS2812B_strip.begin();

   ^~~~~~~~~~~~~

   WS2812B_DATAPIN

exit status 1
'Adafruit_NeoPixel' does not name a type

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Any help much appreciated

**Comment by SHWotever** [comment]
Hi !
 I see you are not using the simhub including Arduino IDE so all the required libraries are missing.
Make sure to use the simhub preconfigured Arduino IDE (you can read where it's stored on the documentation : https://github.com/SHWotever/SimHub/wiki/Nextion-Display#uploading-arduino-micro-sketch) it contains all the required libraries. 

Nicolas

**Comment by matthewbaines** [comment]
ThanksWhat file type is itSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Wotever <notifications@github.com> Date: 13/10/2020  6:41 pm  (GMT+00:00) To: SHWotever/SimHub <SimHub@noreply.github.com> Cc: matthewbaines <matthewbaines77@gmail.com>, Author <author@noreply.github.com> Subject: Re: [SHWotever/SimHub] NextionMicroBridge Error (#680) 
Hi !
I see you are not using the simhub including Arduino IDE so all the required libraries are missing.
Make sure to use the simhub preconfigured Arduino IDE (you can read where it's stored on the documentation : https://github.com/SHWotever/SimHub/wiki/Nextion-Display#uploading-arduino-micro-sketch) it contains all the required libraries.
Nicolas

**Comment by SHWotever** [comment]
You simply have to launch arduino.exe in the given folder. It will open a preconfigured Arduino which can compile the sketch.

**Comment by matthewbaines** [comment]
thanks

do i copy paste the code from NextionMicroBridge into void setup or void loop?

**Comment by SHWotever** [comment]
Hi !
No you simply have to go into the arduino ide  "file" menu then select open and open the sketck in order to upload it.
![image](https://user-images.githubusercontent.com/2207331/96115716-b01f2f00-0ee7-11eb-8c22-3a929bec07c6.png)
