### ISSUE TITLE
F1 2020 wont connect to simhub

### ISSUE THREAD

**Issue by Peyton1822** [SHWotever/SimHub#681]
My simhub is working with all the other games I own such as AC but won't activate with and F1 game and the game is configured correctly according to simhub.

**Comment by SHWotever** [comment]
Hi !

Usually it comes from a conflict (firewall, antivirus, etc...) F1 games uses udo technology which is far more sensitive to this (compared to ac for instance)

You can read a troubleshooting guide here : https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#troubleshooting
