### ISSUE TITLE
Dash Studio : how to get the player current race position in track map scripts ?

### ISSUE THREAD

**Issue by XcellMiguel** [SHWotever/SimHub#683]
Hi,

I'm trying to edit player dot colors via functions, to add class color and transparency when players are in the pits.

Thanks to @Romainrob iRacing plugin we have much more informations available so I could do this in the leaderboards thanks to the "repeatindex()" function, but in the map it seams that there's no similar function.

So is there a way to get the player's race position in the script editor in the Map ?

Thanks.

**Comment by SHWotever** [comment]
Hi ! 

No it's not possible style is global for all opponents. It's not possible to change it for a specific opponent.

Nicolas

**Comment by XcellMiguel** [comment]
Hi,

Ok thanks for your answer.

Indeed if I set a random value every opponent change color at the same time.

Is this something that can be added in a further update ?

Thanks.

**Comment by SHWotever** [comment]
Hi ! I close this issue, it's now possible to assign car classes colours which should cover most cases.
