### ISSUE TITLE
Load cells DIY connections and possibilities

### ISSUE THREAD

**Issue by EBEALIEN** [SHWotever/SimHub#684]
Good morning Wotever, I hope you are well! We here everything ok!

I was asking myself a question, the one concerning brakes and load cells.
The first is if it's already in your software, or it could be something to implement, as for the various arduino accessories.
I see the greatest use with the amplifier HX711 ( https://github.com/bogde/HX711 ) and load cells of this type:
with 3 cables 
![immagine](https://user-images.githubusercontent.com/17771086/96443434-e07b0c00-120c-11eb-965d-cd5b001e58ed.png)
or with 4 cables
![immagine](https://user-images.githubusercontent.com/17771086/96443553-17e9b880-120d-11eb-8978-0f19714ecc36.png)
and through the amplifier, connected to the PC via Pro Micro (or other) and related sketch.
I'm studying it a lot, and I was wondering if maybe implemented in your fabulous SIM,
it would make life simple for thousands of users.
Unfortunately there are too many "Peacocks" on youtube, what real makers who teach.
With esteem
Antonio Italy
_PS: I personally use logitech g25 / 27/29 which has 3 outputs to the potentiometers. Or, you can solve, using the 3 logitech wires,
or in fact they are bypassed with arduino ProMicro or other._

**Comment by SHWotever** [comment]
Hi ! I can see that HX711 library is disabling Arduino interrupts, unfortunately such things will totally kill the simhub sketch communications (create serial communications errors...). 
Disabling interrupts basically makes the communication reliable only in one way (device to computer) so it's not possible to integrate such library in the simhub sketch i'm sorry. 

However a quick search showed some interesting results ;) : https://github.com/search?q=HX711+pedal&type=Repositories

**Comment by EBEALIEN** [comment]
Thanks Wotever, for your interest.
Unfortunately online I found everything but no real Maker explaining how a real designer.
Sure they make videos and give you links to different things, then you realize that the sketch is not good, that the electronics have a missing-Time, and that the components after the videos change them, for stability.
You were the only one with your software, but I understand it's not compatible, for the too many openings that one finds. Thanks you are always a true professional.
