### ISSUE TITLE
Stuttering when app is running

### ISSUE THREAD

**Issue by Yan914** [SHWotever/SimHub#685]
Hi,

I note that i have majors stuttering when app is running on my PC when i play on iracing.
I use 2 boomer to simulate vibrations
have you notice that ?

**Comment by SHWotever** [comment]
Hi !

I did not had similar reports, have you checked the load indicators (CPU usage/GPU usage) to see if there was something abnormal ?

I would also check the GPU settings for forced vsync/gsync or similar settings. If the simhub window is affected by such settings it could create a conflict (as it's powered by direct X).a simple test about that would be to reduce simhub window so it doesn't render.

If that doesn't help could you join the simhub log files so I can check if something suspicious is occurring ?

Nicolas

**Comment by Yan914** [comment]
Hello,

I haven't got any issue about a bottleneck, i've got i5 10600K and a RTX2080...
And i play in VR with an oculus rift S

I've got 2 soundcard , and i notice on each one the issue is the same

[SimHub.log.zip](https://github.com/SHWotever/SimHub/files/5404502/SimHub.log.zip)

**Comment by SHWotever** [comment]
Indeed :D that's a pretty robust configuration ;)

Could you try to disable all the unused plugins in simhub settings to see if that helps ? 
The logs shows nothing particular. 

Have you checked the graphics card settings (in the Nvidia control panel, like windowed gsync settings) that's the kind of advanced settings which can lead to conflicts about refresh rate, often if won't be visible as a load on the system, it will only lead to stuttering.

Reducing to tray the simhub window didn't helped at all ?

**Comment by Yan914** [comment]
Hello Nicolas,

So after a test on different sound source , My motherboard and my sound card... the result was the same ...
But , after that, i close completly the app, and i use the fonction inside Iracing and at this time , i saw clearly the difference ... No stutter with iracing fonction ... at this time!!! thanks for your help.
