### ISSUE TITLE
3 ACC specific properties issues

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#688]
Hello there!:)
Here are some ACC related properties that could use some more love ;)

1. Broken flags
Similar to the recently fixed iRacing flags issue the dedicated DataCorePlugin.GameRawData.Graphics.FlagDetails.Is.XXX don't seem to uptade. 
DataCorePlugin.GameRawData.Graphics.Flag works fine
Briefly tested on a single player race.

2. Missing Turn indicators
As reported by @LowTechRider
https://discord.com/channels/299259397060689920/306851128111398922/769217105803083817
The dedicated turn signal properties are missing and the generic ones do nothing with ACC
int directionLightsLeft  Is Blinker left on 
int directionLightsRight  Is Blinker right on 

3. Wrong GT4 Brake Bias
As reported by @Vitor Sousa
https://discord.com/channels/299259397060689920/306850822518734848/767787445798305792
The weird dash brake bias offset doesn't seem to be taken into account for the gt4 cars.
![image](https://user-images.githubusercontent.com/50543913/97029885-50b3c580-155e-11eb-97fc-d9629342f116.png)
[ACCSharedMemoryDocumentationV1.5.pdf](https://github.com/SHWotever/SimHub/files/5430709/ACCSharedMemoryDocumentationV1.5.pdf)

Merci d'avance et bon week-end à toi!

**Comment by Romainrob** [comment]
Hi.
All good on the latest version.
Thanks for the fixes and additions :)

**Comment by SHWotever** [comment]
Thanks a lot for the feedback !
