### ISSUE TITLE
[Feature Request] ETS2 & ATS telemetry sdk update

### ISSUE THREAD

**Issue by SgtBreadStick** [SHWotever/SimHub#691]
So I've been using SimHub for a while now, especially on ETS2 & ATS, however I've noticed a lot of properties are missing such as air temperature, differential, etc... which are now on the new SCS SDK versions.
Would it be possible for more properties to be added for ETS2 & ATS?

[https://modding.scssoft.com/wiki/Documentation/Engine/SDK/Telemetry](url)

**Comment by SHWotever** [comment]
Hi ! 
sjdawson made a wonderful job adding all of them you can donwwload thr pugin here : https://github.com/sjdawson/TruckSimulatorPlugin
