### ISSUE TITLE
Demo plugin - Code behind xalm examples

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#692]
Hi.
Could you please include a couple of basic examples of xalm binding in the demo plugin?
I'm thinking, a toggle switch that would make a variable true or false and a 2 way text box.
Bonne journée! Ou bonne nuit...

**Comment by lukester1975** [comment]
If it's any help, I've been figuring this out myself for a while [here](https://github.com/simelation/simhub-plugins/tree/master/packages/slipro-plugin).

WPF and xaml is new to me, so I've no idea if I'm doing things correctly (separation of concerns might not be right for one...) but it works (for some definition of works)!

**Comment by Romainrob** [comment]
Hi @lukester1975 
I definitely am not doing things correctly.
I tried following xalm binding tutorials and got little else than frustration out of it. Especially hurting at the part where they say : "see how easy it was?" when my binding won't work...
I'm looking for a barebone working example in the context of SimHub plugins, in the hope it could give me a jump start.
I'll have a look at your files. Thanks for sharing 👍

**Comment by SHWotever** [comment]
We discussed directly with RomainRob, but I leave the sample here ;) If somebody needs it too ;)

[User.PluginSdkDemo.settingsbindingdemo.zip](https://github.com/SHWotever/SimHub/files/5522735/User.PluginSdkDemo.settingsbindingdemo.zip)

In short :
When creating the settings control from the plugin, assign the settings instance to the datacontext : 
```csharp
   /// <summary>
        /// Returns the settings control, return null if no settings control is required
        /// </summary>
        /// <param name="pluginManager"></param>
        /// <returns></returns>
        public System.Windows.Controls.Control GetWPFSettingsControl(PluginManager pluginManager)
        {
            return new SettingsControlDemo(this) { DataContext = Settings };
        }

        /// <summary>
```

Then in the ui we can directly bind any property without going through the code behind:

```xaml
     <CheckBox IsChecked="{Binding Path=TestBool}">TestBool</CheckBox>
                <StackPanel Orientation="Horizontal">
                    <Label>SpeedWarningLevel</Label>
                    <Slider Minimum="00" Maximum="1000" Value="{Binding Path=SpeedWarningLevel}" Width="150"></Slider>

                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <Label>Sample text</Label>
                    <TextBox Text="{Binding Path=SampleText}"></TextBox>

                </StackPanel>

                <StackPanel Orientation="Horizontal">
                    <Label>Real time value refresh</Label>
                    <TextBlock Text="{Binding Path=RealtimeDisplay}"></TextBlock>

                </StackPanel>
```

A little adition to the sample , if we want to modifiy values from the code behind and be reflected on the UI we need to implement "INotifyPropertyChanged", there are a few variations of this, I used one of the most "out of box" in this example,
other variations exists like fody.propertychanged which gets rid of all the additional code (I use this myself), but I wanted to stay on a "from books" approach :
```csharp
 public class DataPluginDemoSettings : INotifyPropertyChanged
    {
        ...

        #region Property supporting UI refresh from code

        private int _RealtimeDisplay = 0;

        public int RealtimeDisplay
        {
            get => _RealtimeDisplay;
            set => SetField(ref _RealtimeDisplay, value);
        }
        #endregion


        #region Utilities methods to refresh the UI see https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged?view=netframework-4.7.2

        protected void OnPropertyChanged(string propertyName)
          => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

        protected bool SetField<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
        {
            if (EqualityComparer<T>.Default.Equals(field, value)) return false;
            field = value;
            OnPropertyChanged(propertyName);
            return true;
        }


        public event PropertyChangedEventHandler PropertyChanged; 
        #endregion
    }
```
