### ISSUE TITLE
Simhub stuck on loading after power failure mid-game upon relaunch.

### ISSUE THREAD

**Issue by liquidbass** [SHWotever/SimHub#694]
Pretty cut and dry - was racing with simhub running my shakers and motors, power went out.  Since then I have not been able to launch.  Once I try to launch it locks up and logs indicate:  

[2020-10-29 18:44:32,875] ERROR - Error while loading game manager
System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.

I have not tried reinstalling, etc.  I really don't want to loose all of my settings for the shakers and motors I have set up.
Most recent log and screen shot included.

[SimHub.log](https://github.com/SHWotever/SimHub/files/5461715/SimHub.log)
![image](https://user-images.githubusercontent.com/73673202/97641477-5f482400-1a19-11eb-82cc-99935e51c529.png)

**Comment by SHWotever** [comment]
Hi Indeed the lap history database got corrupted, you can reset it by deleting the following file : C:\Program Files (x86)\SimHub\PluginsData\PCars2\datastore.db

Nicolas

**Comment by liquidbass** [comment]
Fixed as you expected.  Many thanks sir!  I figured something corrupted, just didn't know where or what lol.  Thanks for the efforts behind this and a quick solution!!!  YOU ROCK!
