### ISSUE TITLE
iRacing Radar Possible Issue

### ISSUE THREAD

**Issue by Jesterface23** [SHWotever/SimHub#695]
In iRacing I have been attempting to use the component Visual Radar and cars are overlapping in the overlay. I am in windowed mode and I haven't noticing any errors in the system log.

I've seen that it worked several months ago in videos and I'm not sure if an iRacing update changed something or if I might be missing something on my end.

Let me know if more information is needed.

Thank You

**Comment by SHWotever** [comment]
Hi !
Unfortunately it's not an issue, Iracing does not give complete coordinates for opponents, so I can only know their % of track done, which does not allow to place them anywhere else than the recorded track line. Other games have more data and will allow to place them correctly in 2D .
Nicolas
