### ISSUE TITLE
Can SimHub act as a vjoy feeder?

### ISSUE THREAD

**Issue by lukester1975** [SHWotever/SimHub#696]
Hi

As per subject. I see vjoyinterfacewrap is there, so I was wondering if I can generate vjoy events with PluginManager rather than having to use vjoy itself?

I've tried things like `			PluginManager.TriggerInput("vJoy_Device_B00", GetType(), PressType.ShortPress);` (and combinations of with `JoystickPlugin` prefix, etc.)

but no luck. 

Thanks!

**Comment by SHWotever** [comment]
Hi !

Indeed vjoy actions were a thing in the early early days of Simhub :D, there is no active code remaining, but i'm planning to get it back, i've learned a lot through another project about vjoy and it would be good to get it working again.

**Comment by lukester1975** [comment]
OK, sounds great - I look forward to it! For now I'll just use vjoywrapper itself, then.

BTW, I noticed when playing around that if I use ControlsEditor and "press" a vjoy button (with the vjoy feeder demo app) the UI reports it as:
 
![image](https://user-images.githubusercontent.com/9592489/97897329-3b912080-1d2e-11eb-97d3-20ffaae7d3e1.png)

However, in PluginManagerSettings.ini it is `"Trigger": "JoystickPlugin.vJoy_Device_B00"` (an additional _ between `vJoy` and `Device`).  No idea if that's good or bad, but thought I'd mention it! Works fine though.

Thanks

**Comment by SHWotever** [comment]
Humm ! Thanks, indeed that is a wpf trick the first "_" is considered as a special char and won't display, I think there are ways to disable this behavior.

**Comment by lukester1975** [comment]
Sounds unpleasant! I have been "enjoying" learning WPF/xaml by writing a plugin ... for some definition of enjoy :)

**Comment by lukester1975** [comment]
Hello Nicolas

You may be aware of this from your other project you mentioned using vjoy, but there seems to be an unpleasant bug in the vjoy version bundled with SimHub that causes a crash: http://vjoystick.sourceforge.net/site/index.php/forum/4-Help/1171-vjoy-crashes-development

Would it be possible to release a new SimHub version with a fixed vjoy so my plugin can simply use the SimHub version? The latest from sourceforge (2.1.9.1-160719) doesn't exhibit the problem for me (so far!). The version numbers in the dlls are a bit messed up and don't match the package version, however (vJoyInterface says its 0.0.0 Commit: 0, vJoyInterfaceWrap says  2.1.6.999).

That said it looks like vjoy development is now mainly on a fork of a fork here: https://github.com/njz3/vJoy so maybe jumping straight to that version is best? I haven't tried that fork yet myself but will do shortly. It doesn't look like SimHub references vJoyInterfaceWrap by default at all, so I guess it won't break anything if I just drop in those dlls.

Or if you build your own vjoy for bundling with SimHub, I think the specific fix is this one https://github.com/shauleiz/vJoy/commit/e801fc4d2b3b39686fdd65269decdb55431c8879 though there a quite a few fixes in the commit history...

Thanks very much!

Luke.

**Comment by lukester1975** [comment]
FYI I had a further play around with 2.2.1.1 to figure out the pinvoke exception - info here https://github.com/njz3/vJoy/pull/2

**Comment by SHWotever** [comment]
Hello !

for now I simply removed traces of the old vjoy plugin, so vjoy related dll won't be part anymore of simhub ;)

**Comment by lukester1975** [comment]
OK makes sense. Maybe I'll put my fixed build of vjoywrapper in my plugin zip and if anyone wants to use it, they can copy it in along with the plugin dll.

Given all of 4 users, I suspect the answer is nobody will :)
