### ISSUE TITLE
Dash Studio HTML mode - Missing dial gauge needle image

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#697]
Bonjour,
J'ai un ptit bug pour toi ;)

As reported by @Mroczny Gracz, the needle of a dial gauge can be missing when running the dash in HTML mode.
https://discord.com/channels/299259397060689920/306850822518734848/772931765609168916

This seems to only happen when using an image from the common library:
HTML on the right
![image](https://user-images.githubusercontent.com/50543913/98007395-a0627e80-1df3-11eb-83c1-c44a5aea29e0.png)

Bonne journée!

**Comment by Romainrob** [comment]
Salut,
This is looking good on my end now 👍 .
Thank you!

**Comment by SHWotever** [comment]
Thanks a lot for the feedback !
