### ISSUE TITLE
iRacing Error loop - 7.2.0

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#698]
Hi
On the last update I have this error loop when playing an iRacing telemetry replay.
Idk if it only affect replays. My subscription ran out... so I didn't test in game.
![image](https://user-images.githubusercontent.com/50543913/98453547-abead800-215a-11eb-8f59-8349eabec17a.png)
[SimHub.zip](https://github.com/SHWotever/SimHub/files/5505656/SimHub.zip)
I tried disabling all non native plugins, same issue.

**Comment by SHWotever** [comment]
Thanks ! Indeed it not systematic and I did not get it during my tests but I found some replays in my collection triggering it !
Fix incomming !

**Comment by SHWotever** [comment]
I just released the hotfix ;)

**Comment by Romainrob** [comment]
Logs are clean now :)
Thank you!
