### ISSUE TITLE
[Feature Request] - Replay list filter

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#700]
Bonsoir.
Sorry to break the round number ;) I've yet one more suggestion.

I think a search/filter bar would be welcome in the replay manager list.
I have a lot of replays and finding the correct one is not easy.
It would be nice to be able to search for cars, tracks or even keys words in the description.

Thanks for considering the idea
Bonne soirée.

**Comment by SHWotever** [comment]
Hello !

It's now available in the last version.

Nicolas
