### ISSUE TITLE
[Feature Request] add f1 2020 m_suggestedGear to Arduino Framework 

### ISSUE THREAD

**Issue by cbartholomew** [SHWotever/SimHub#701]
The gang at code masters released a UDP specification for 2020 F1, and it contains the suggestedGear member, which wasn't in 2019 - Could we get the framework to recognize this additional member so we can add not only "gear", but also, "suggested gear" - the new UDP specification is here:

https://forums.codemasters.com/topic/50942-f1-2020-udp-specification/

> struct PacketCarTelemetryData
> {
>     PacketHeader    	m_header;	       // Header
> 
>     CarTelemetryData    m_carTelemetryData[22];
> 
>     uint32              m_buttonStatus;        // Bit flags specifying which buttons are being pressed
>                                                // currently - see appendices
> 
>     // Added in Beta 3:
>     uint8               m_mfdPanelIndex;       // Index of MFD panel open - 255 = MFD closed
>            ﻿                                    // Single player, race – 0 = Car setup, 1 = Pits
>                                                // 2 = Damage, 3 =  Engine, 4 = Temperatures
>                                                // May vary depending on game mode
>     uint8               m_mfdPanelIndexSecondaryPlayer;   // See above
>     int8                m_suggestedGear﻿;       // Suggested gear for the player (1-8)
>            ﻿                                    // 0 if no gear suggested
> };

**Comment by SHWotever** [comment]
Hi ! 

Thanks for the feedback it's updated for the next simhub update,

Nicolas

**Comment by cbartholomew** [comment]
amazing, thank you
