### ISSUE TITLE
Arduino not recognized after 7.2.2 update

### ISSUE THREAD

**Issue by DeathMagnet** [SHWotever/SimHub#702]
[simhub_no_arduino.zip](https://github.com/SHWotever/SimHub/files/5542814/simhub_no_arduino.zip)

Using a keyestudio mega 2560 clone with DK Shield (2 motors)

Board is recognized and functions perfectly with SimHub 7.1.3 but no longer detected when running 7.2.2

Can see board in Arduino setup (SimHub 7.2.2) and have no issues re-uploading script.

Attached screenshots show settings only scanning one USB port - same results, if set to scan all USB ports
Have also tried lowering baud rate to 9600, with same results.

Attached logs show 7.1.3 detecting board after starting Arduino Plugin - do not see board detection in 7.2.2 logs

Will see if I can dig up an official 2560 to see if results are the same, but keyestudio has been very reliable clone for other projects.

**Comment by xstorm96** [comment]
Same for me, i had to downgrade to 7.1.3

**Comment by SHWotever** [comment]
Hi ! Indeed the new startup code was a little too fast for the mega, the fix is ready for the next version ;)

**Comment by xstorm96** [comment]
okay, when will this bug fix happen? i can't find 7.1.3 on the net and with 7.2.2 installed i can't use my steering wheel!

**Comment by SHWotever** [comment]
As soon as possible ;) I hope before the end of the week ;)

**Comment by DeathMagnet** [comment]
works now.

fast response!

thx much!
