### ISSUE TITLE
UI control to get a game property

### ISSUE THREAD

**Issue by lukester1975** [SHWotever/SimHub#704]
Hello again

Is `SimHub.Plugins.OutputPlugins.Dash.WPFUI.PropertyPicker` considered OK to use in a plugin, or is there something else? I have it working fine (as below, hopefully that's correct) but thought I'd check!

If it is the best thing to use, is there a way to get it to pre-select / highlight a value? If not, could that be added? Would be nice to see if a value is already assigned where I'm using it.

Thanks!

```
var propertiesPicker = new PropertiesPicker();
await ChildWindowManager.ShowChildWindowAsync(Window.GetWindow(this), propertiesPicker);

var property = propertiesPicker.Result;
if (property == null)
    return;

// Use property.Key...
```

**Comment by SHWotever** [comment]
Hello !

Sorry for the long delay, weeks have been extremely busy !

Indeed you can use it, it's not part of the official plugin SDL, but hopefully it should not change soon ;)

Currently no there is no way to preselect a value, the goal is to pick a value as it was made for the formula editor.,

**Comment by lukester1975** [comment]
No problem, thanks for the reply.

As it happens I've changed to using SimHub.Plugins.OutputPlugins.EditorControls.BindingEditor which is working OK, though I do have a few questions so I'll create another ticket at some point. No rush on a reply!

Thanks

Luke.
