### ISSUE TITLE
[FeatureRequest] Make the PacketHeader in F1 2020 accessible

### ISSUE THREAD

**Issue by patapon297** [SHWotever/SimHub#705]
Hi,

I wanted to build a custom overlay for the new Splitscreen mode in F1 2020.
The PacketHeader of F1 2020 includes the Index of Player 2 in Splitscreen, but it is not accessible as a property in Simhub.
Would be great to have access to it.

Cheers and keep up the good work!

**Comment by nosv1** [comment]
Oh heckin heck, I thought it was my own wrong doing for it not being available. Was tryna continue a plugin from 2019, but was so lost when I couldn't load/find the 2020 packet.

**Comment by SHWotever** [comment]
Hi ! 
I've exposed the header values for the next version, however i'm not sure it's really useable :
![image](https://user-images.githubusercontent.com/2207331/101952934-c13fa000-3bf9-11eb-8b93-5b218722551c.png)
