### ISSUE TITLE
Connect Led to make sequences.

### ISSUE THREAD

**Issue by 7HUND3R36** [SHWotever/SimHub#707]
Hi. I want to connect about 60 LEDs to do a rpm sequence on a board. It would connect about 60 5mm LEDs of various colors. The problem is that I don't know how these are connected to an arduino uno and then I can configure them in simhub.

**Comment by SHWotever** [comment]
Hi ! Simple leds are not supported, you can use ws2812b or PL9823 which are supported : https://github.com/SHWotever/SimHub/wiki#components-wiring-and-configuration
