### ISSUE TITLE
JoystickPlugin - Missing Thrustmaster clutch axis

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#708]
Bonjour,
As reported by @Balleknack here https://discord.com/channels/299259397060689920/306850822518734848/781100532437090314 , It seems the joystick plugin doesn't pickup the "Slider 0" clutch axis of the T500rs.
I was able to confirm the issue when testing with t500rs pedals and my TS-PC base. I suspect this could affect other TM wheel bases too.
Hopefully this is fixable.
Bonne journée ! :)

**Comment by SHWotever** [comment]
Hello ! The final version have been released so I close it ;)

**Comment by Romainrob** [comment]
Thanks for the  addition! :)
