### ISSUE TITLE
Freeze on exit

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#709]
Hi,
Since a couple updates back I've noticed SimHub would sometimes freeze on exit.
I saved the logs of the last 3 occurrences.
Maybe they'll reveal something of interest.
As I also recently added settings to my plugins, I wonder if this could be the source of the issue.
Bonne fin de soirée
[Logs.zip](https://github.com/SHWotever/SimHub/files/5611384/Logs.zip)

**Comment by Romainrob** [comment]
Hi. One more.
This time I noticed my dashboards were frozen (iOS an Android), and when trying to reload them, it stayed stuck on the loading screen. Then when closing SimHub, it froze and I had to kill it.
[SimHub.log.zip](https://github.com/SHWotever/SimHub/files/5673246/SimHub.log.zip)
All was fine after restart.
If you don't find any useful info in the logs and I'm the only one to report this, feel free to close the ticket.
I can live with this issue. I'd just though I'd report this.
Bonne journée.

**Comment by SHWotever** [comment]
Hello !

Désolé j'avais pas de feedback sur ce ticket ;) oui les logs me pointent du doigt un endroit en particulier ;) je devrait pouvoir le chasser ;)

**Comment by Romainrob** [comment]
Cool :). Bonne chasse alors!

**Comment by Romainrob** [comment]
Salut!
J'ai pas ce pb depuis la 7.3.1b1
Merci pour le fix. :)
Bon week-end!

**Comment by SHWotever** [comment]
Cool ! Merci pour le feedback !
