### ISSUE TITLE
Documentation for plugins development

### ISSUE THREAD

**Issue by yesid08** [SHWotever/SimHub#710]
Is there any manuals, documentation, or public resources where I can look for information about plugin development?

Is there any possibility to develop such a plugin externally? or there is just the option to develop internally from SimHub (in the plugin editor)

Thank you so much for your response guys!
Yesid G.

**Comment by SHWotever** [comment]
Hi !

A sample is provided with simhub : C:\Program Files (x86)\SimHub\PluginSdk\User.PluginSdkDemo

You will find all the basic operations shown (create action, read values, create property, create UI.

Nicolas
