### ISSUE TITLE
iRacing game reader - Missing ClubName

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#712]
Bonsoir,
Could you please add the ClubName to SessionData.DriverInfo.Drivers ?
It's currently missing.
Bon week-end!

**Comment by SHWotever** [comment]
Hello !

It's added to the rawdata object for the next version ;)
![image](https://user-images.githubusercontent.com/2207331/101951770-d3b8da00-3bf7-11eb-9384-5900f841227a.png)

**Comment by Romainrob** [comment]
Sweet! Yet more properties to add to my plugin.
Merci et bon week end! :)

**Comment by SHWotever** [comment]
Hello ! The final version have been released so I close it ;)

**Comment by Romainrob** [comment]
Thank you!
