### ISSUE TITLE
Questions about SimHub.Plugins.OutputPlugins.EditorControls.BindingEditor

### ISSUE THREAD

**Issue by lukester1975** [SHWotever/SimHub#713]
Hello again

Sorry about the length of this message! I have a few questions about BindingEditor and DashboardBindingData. No rush since you're busy! What I have is working, I'd just like to make sure it's correct/best.

#### BindingMode

* None (== IsNone)
* Formula == (IsFormula)

They are both pretty self-explanatory. ColorGradient == (IsColorGradient) probably too, I just haven't tried to use it.

But what do the other two modes do?

* Expression
* Expose == (IsExposed)

If I set either of those then it defaults to None in the UI as far as I can tell:

![image](https://user-images.githubusercontent.com/9592489/102013911-e8f24d80-3d4a-11eb-91d6-9b6ecc4e5de1.png)

#### DashboardBindingData.ValueGetter

Further to that is what I'm really wondering: is if there's a way to use BindingEditor to just get ValueGetter populated (I'm assuming that is the same ValueGetter that would be populated by PropertyPicker)? So you could have 3 options presented: "None", "Computed Value" (as now) but also "Simple property" (basically just a PropertyPicker).

I can't see how to do it but thought maybe there's a way, since ValueGetter is there? I'm thinking when I just want a property that's going to be much more efficient at game update time than having to evaluate an ncalc/javascript expression.

#### Evaluating ncalc expressions

Is this the right way? It works for ncalc for me, but again not sure it's ideal:

<pre>
var interpreter = SimHub.Plugins.OutputPlugins.Dash.TemplatingCommon.NCalcEngineBase()
</pre>

...

<pre>
res = interpreter.ParseValue(bindingData.Formula);
</pre>

#### Evaluating javascript expressions

But not for javascript :(
<pre>
if (BindingData.Formula.UseJavascript)
	res = interpreter.ParseValueJavascript(BindingData.Formula);
else
	res = interpreter.ParseValue(BindingData.Formula);
</pre>

But I always get null back. Since `NCalcEngineBase` has Base in the name, I'm thinking I need something more derived :) Or maybe a completely different IFormulaEngine for Javascript evaluation? I can't find it in the object browser though.

It feels like something is probably not right with my code, since `SimHub.Plugins.OutputPlugins.Dash.GLCDTemplating.ExpressionValue` knows whether its javascript, so having to call `ParseValue` or `ParseValueJavascript` seems like it might be wrong.

#### Best practice for cancelling dialog

Very minor question since what I have is working well.

I'm storing DashboardBindingData state in my app, since it serializes exactly what I want. When cancelling the BindingEditor dialog, I don't want to lose the initial values of DashboardBindingData. I noticed it implements ICloneable, so thought I could just clone it and use the clone as the DataContext.

However, DashboardBindingData.Clone() doesn't appear to deep clone then Formula field, so if the user edits the expression but then cancels, the old values are lost. What I ended up with was this:

<pre>
var bindingData = (SimHub.Plugins.OutputPlugins.GraphicalDash.Models.DashboardBindingData)led.BindingData.Clone();
if (bindingData.Formula != null)
{
	bindingData.Formula = new SimHub.Plugins.OutputPlugins.Dash.GLCDTemplating.ExpressionValue(
		bindingData.Formula.Expression, bindingData.Formula.Interpreter);
}

var bindingEditor = new BindingEditor();
bindingEditor.DataContext = bindingData;
await ChildWindowManager.ShowChildWindowAsync(Window.GetWindow(this), bindingEditor);
if (bindingEditor.OK)
	led.BindingData = bindingData;
</pre>

Is that the best way? Or maybe something to do with LastValue / LastValueIsInitialized? 

OK I've gone on way too long. Thanks again and really no rush since you're busy! What I have is working, I'd just like to make sure it's correct/best.

Luke.

**Comment by SHWotever** [comment]
Hi ! Actually everything is bundled to avoid most of the struggle,

In your model use this object, extression value is the basic container for any kind of formula :
public OutputPlugins.Dash.GLCDTemplating.ExpressionValue FrontLeftFormula { get; set; } = "";

Then in your UI use the editor control, it will do the whgole job for you, edit cancel, display ... :
```
xmlns:wpfui="clr-namespace:SimHub.Plugins.OutputPlugins.Dash.WPFUI"
<wpfui:FormulaPicker Expression="{Binding Path=FrontLeftFormula}" Height="26" ></wpfui:FormulaPicker>
```

Finally 
To evaluate the result, you were not really far,  
```
// this can be at your plugin scope, don't instantiate it every time that's what matters the much ( the "base" suffix makes think it's abstract, it was long time ago, but it's not anymore)
private NCalcEngineBase engine = new NCalcEngineBase();

double getValue(){
    var result = engine.ParseValueOrDefault(FrontLeftFormula, 0)
    return result;
}

**Comment by SHWotever** [comment]
Last information, the ExpressionValue object can be serialized/deserialized with json with no troubles

**Comment by SHWotever** [comment]
Another last information :D, ParseValueOrDefault has many overrides depending of the datatype you are expecting.

**Comment by lukester1975** [comment]
Goodness that was quick, thanks I shall take a look!

Yeah I have the ncalc engine at plugin scope so that's all good. So this way and using ParseValueOrDefault javascript will just work?

Thanks

**Comment by SHWotever** [comment]
Yep ! It's its job to give a result and handle everything.

**Comment by lukester1975** [comment]
Great, thanks again I shall try it later.

**Comment by lukester1975** [comment]
Cool, I have FormulaPicker working. Thanks!

Quick question: is it possible to style the button? Previously I had used a ToggleButton with some custom styling to match LED colours on SLI-Pro/F1 devices:

![image](https://user-images.githubusercontent.com/9592489/102017316-2f04dc80-3d5e-11eb-826c-c63c5d49b835.png)

Now (with ShowAsButton)

![image](https://user-images.githubusercontent.com/9592489/102017388-9ae74500-3d5e-11eb-8a56-fd564915f0d5.png)

As long as it's possible (I assume it is) I'll try to figure it out on my own before asking for more help! I'm using writing this plugin as an exercise to get to grips with WPF ... which I assume helps with UWP ... which helps with whatever the new thing is...

Thanks again

**Comment by lukester1975** [comment]
I have something working with styling `FormulaPicker`! Not sure how, I don't understand this stuff yet :) Probably not the best way but it does the job.

	<wpfui:FormulaPicker
		EditPropertyName="{Binding Path=EditPropertyName}" Expression="{Binding Path=ExpressionValue}"
		ShowAsButton="True" Margin="2,2,2,2"
	>
		<wpfui:FormulaPicker.Resources>
			<Style TargetType="{x:Type Button}">
				<Style.Triggers>
					<DataTrigger Binding="{Binding Path=ExpressionValue.IsNone}" Value="True">
						<Setter Property="Template">
							<Setter.Value>
								<ControlTemplate TargetType="Button">
									<Ellipse Style="{StaticResource LedStyle}"/>
								</ControlTemplate>
							</Setter.Value>
						</Setter>
					</DataTrigger>

					<DataTrigger Binding="{Binding Path=ExpressionValue.IsNone}" Value="False">
						<Setter Property="Template">
							<Setter.Value>
								<ControlTemplate TargetType="Button">
									<Ellipse Style="{StaticResource LedStyle}" Fill="{Binding Path=SetBrush}"/>
								</ControlTemplate>
							</Setter.Value>
						</Setter>
					</DataTrigger>
				</Style.Triggers>
			</Style>
		</wpfui:FormulaPicker.Resources>
	</wpfui:FormulaPicker>

And then `LedStyle` defined as

	<Style TargetType="{x:Type Ellipse}" x:Key="LedStyle">
		<Setter Property="Height" Value="34"/>
		<Setter Property="Width" Value="34"/>
		<Setter Property="Fill" Value="LightGray"/>
		<Setter Property="Stroke" Value="DarkSlateGray"/>
		<Setter Property="StrokeThickness" Value="1.5"/>
	</Style>

Is there a way to direct the button styling to just the "assigned" "unassigned" buttons? I guess what this is doing is styling any buttons that might be inside `FormulaPicker`. Presumably better to restrict it?

Anyway, all good.

**Comment by SHWotever** [comment]
Hello !

Unfortunately my controls are not intended to be restyled,it l may be possible to restyle it using wpf standards methods, but to be totally honest it's above my regular WPF usage :D
