### ISSUE TITLE
Question about Forza Horizon4

### ISSUE THREAD

**Issue by geek-slt** [SHWotever/SimHub#714]
I see that simhub supports Forza Horizon4, I want to know how simhub obtains Forza Horizon4 telemetry data? I try to get the telemetry data of Forza Horizon4 via UDP, but it keeps failing

**Comment by SHWotever** [comment]
Hi !

I simply used the following reference document and standard UDP client : https://forums.forzamotorsport.net/turn10_postst128499_Forza-Motorsport-7--Data-Out--feature-details.aspx

**Comment by geek-slt** [comment]
Hello !
I know how to access telemetry data via UDP. I have already accessed F1 series games myself, but the data of Forza Horizon4 has always been problematic. I didn’t receive telemetry data until I turned off the windows firewall yesterday. Thank you very much for your answer.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SHWotever/SimHub"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 凌晨1:34
收件人:&nbsp;"SHWotever/SimHub"<SimHub@noreply.github.com&gt;;
抄送:&nbsp;"1151144104"<1151144104@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SHWotever/SimHub] Question about Forza Horizon4 (#714)





 
Hi !
 
I simply used the following reference document and standard UDP client : https://forums.forzamotorsport.net/turn10_postst128499_Forza-Motorsport-7--Data-Out--feature-details.aspx

**Comment by geek-slt** [comment]
Nice!
The telemetry data of Forza Horizon4 has been determined. This document has some minor problems. Thank you very much for your help. The next step is to receive the telemetry data of Dirt Really. Do you have any information?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SHWotever/SimHub"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 中午1:52
收件人:&nbsp;"SHWotever/SimHub"<SimHub@noreply.github.com&gt;;
抄送:&nbsp;"1151144104"<1151144104@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SHWotever/SimHub] Question about Forza Horizon4 (#714)





 
Closed #714.
