### ISSUE TITLE
[Feature Request] Query Interface using the command line interface

### ISSUE THREAD

**Issue by SeriousOldMan** [SHWotever/SimHub#715]
Hi, it would be very helpful to request effect information using the command line interface. The value can be communicated as the exit code of SimHubWPF and the syntax might something like this:

SimHubWPF -query "EffectPath"."setting"

where "EffecctPath" will be _OuterGroup_._InnerGroup_._Effect_, depending on the profile. "setting" depends on the effect, but something like "IsEnabled", "GetIntensity", and so on might be generally helpful.

I created an application to control everything in a simulation rig from simulation games, SimHub, SimFeedback and so on from one single control center and it would be very user friendly to show the current settings for SimHub there as well.

Best, TheBigO

**Comment by SHWotever** [comment]
Hi ! Unfortunately after all those years this request remained completely unique. I close it for readability purpose even if the the feature would be interesting.
