### ISSUE TITLE
Tyre Temps I-M-O

### ISSUE THREAD

**Issue by newtonpg** [SHWotever/SimHub#716]
@SHWotever 
Wish you a Merry Christmas and a Happy New Year!
Keep up the good work!

I've noticed IMO tyre temps works very well in RRRE but their values are passed by AMS2 (UDP mode) as Integer, while in Default Mode they show decimals.
Since IMO tyre temps are mistakenly passed by AMS2 API in Default config, we need to use UDP config.
So I would ask if could change those numbers (temps) precision?

**Comment by newtonpg** [comment]
One may ask why on earth do I need decimal temps on tyres? 
Usually no one needs, except setting up the Ideal Tyre Pressure.
The superficial I-M-O tyre temperatures follows a linear trend at the ideal tyre pressure.
The ideal zone must be around -0.5 to 0.5 (ideally zero) degrees at the middle.
The resulting numbers using integers varies at huge leaps and are impracticable.

**Comment by SHWotever** [comment]
Hi ! 

Unfortunately it's the precision coming from the api itself, I can't change it.

Nicolas

**Comment by newtonpg** [comment]
Thank you for your time!
But I have additional arguments and please, consider I have a low proficiency in English language and don't want to be rude.

So I politely ask if you've verified if the data numbers are really integers or not?
Because some other telemetry app like RST Software, Second Monitor and Iko - Telemetry App v,10.2 report those temperatures as floating point.
Or maybe there are another variables they're using?

**Comment by newtonpg** [comment]
Please forgive me, I'm wrong and there's nothing you can do.
Only RST Software report tyre temps with decimals but even there, resulting from a transformed variable (temp vs press)

**Comment by SHWotever** [comment]
Ah ah ;) no worries ;) 

For reference here are the definitions : https://www.projectcarsgame.com/two/project-cars-2-api/ available in SMS_UDP_Definitions_v2.
```c
	unsigned short							sTyreTempLeft[4];									// 256 8
	unsigned short							sTyreTempCenter[4];								// 264 8
	unsigned short							sTyreTempRight[4];								// 272 8
```

`unsigned short` is an integer type (no decimals)
