### ISSUE TITLE
How can i add rotary encoders ?

### ISSUE THREAD

**Issue by KuqTv** [SHWotever/SimHub#717]
How can i add rotary encoders ? 
![image](https://user-images.githubusercontent.com/76257696/103142000-75aeeb00-46fd-11eb-9968-6ce2cf434878.png)

**Comment by KuqTv** [comment]
Please help because i new

**Comment by SHWotever** [comment]
Hi ! 

It looks like the sketch has been modified which removed the settings,

Can you install the lastest Simhub version ? https://www.simhubdash.com/download-2/
It will restore a fresh unmodified sketch allowing to recover the option.

I also see that you are planning to use an arduino uno, it's not the best choice for such application, a leonardo or a pro micro is much better (see https://github.com/SHWotever/SimHub/wiki/Arduino--Setup#recommended-arduinos)

Nicolas

**Comment by KuqTv** [comment]
ok i download lastest simhub version and check this

**Comment by KuqTv** [comment]
Thanks
