### ISSUE TITLE
Dash Studio - Border color binding oddities

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#719]
Hi,
I noticed using repeatindex in a BorderColor Binding Fx doesn't seem to give the intended result.
For example. Using the same formula : 

isnull(prop('IRacingExtraProperties.iRacing_Leaderboard_Driver_'+format((repeatindex()-1),'00')+'_ClassColor'),'0x33ceff')

![image](https://user-images.githubusercontent.com/50543913/103478135-cf31ac80-4dc4-11eb-841d-e8a489e23ca2.png)

For both the border and background color:
![image](https://user-images.githubusercontent.com/50543913/103478092-b5906500-4dc4-11eb-937e-74678e7fe367.png)

Works fine for the background but not the border:
![image](https://user-images.githubusercontent.com/50543913/103478161-fc7e5a80-4dc4-11eb-94f0-a4391c0415d3.png)

On a side note. I also noticed the prop auto completion window doesn't pop up in when typing [ in the Computed Color window.
Bon dimanche!

**Comment by Dumedo** [comment]
This bug still need a fix

**Comment by Romainrob** [comment]
Hi, I just tested this again on the V9 beta.
This is working now :D
Thanks for the fix!

**Comment by Romainrob** [comment]
Hi, I just tested this again on the V9 beta.
This is working now :D
Thanks for the fix!
