### ISSUE TITLE
Bug in "cycle previous das template" control

### ISSUE THREAD

**Issue by JonathanPineiro** [SHWotever/SimHub#720]
Hello, it happens to me that when I assign a button to change the dashboard, when I give it to advance (next dash template) everything works ok, but when I perform the opposite function (previous dash template) what it does is not go to the previous one and to the previous one successively, what it does is enter into loop the last 4 dashboards of the list, it happens to me both marking only the favorites and if it is done with all the dashboards, I do not know if it is a recognized failure in which it is working or if Nobody reported the error, this happens since I activated it and going through several updates, I await your response and if you need any help I am available too, a greeting

**Comment by SHWotever** [comment]
Hi ! I close this since it has been fixed since.

Nicolas
