### ISSUE TITLE
SimHub OpenHardwareMonitor CPU Temp's Missing on Z490/10900k

### ISSUE THREAD

**Issue by jurnaza** [SHWotever/SimHub#721]
OHM CPU temp's are not populating on a Z490 motherboard with a 10900k.  I have validated that the OHM standalone client is able to read these values.

**Comment by SHWotever** [comment]
Hi ! Indeed I've not updated this component from a long time, I will do it, I was fearing antivures false positives, this component easily triggers it. Can you try to simply drop the dll "OpenHardwareMonitorLib.dll" coming with the latest OHM inside simhub install directory ? It should be enough to get the latest supported hardware.

Nicolas

**Comment by jurnaza** [comment]
That worked, I dropped the OHM 0.9.6 dll in a 7.3.2 install and was able to get all the missing values.
