### ISSUE TITLE
SimHub Does not start

### ISSUE THREAD

**Issue by Geounix** [SHWotever/SimHub#722]
Hello, After installing SimHub it does not start, when I try to start it, the icon appears in the taskbar and then it closes, I would like to know if you know how to solve this problem please, I can not even buy a license since it does not start me.

**Comment by SHWotever** [comment]
Hi ! 

Usually it's caused by out of date monitoring utilities, FanXpert, afterburner etc ... make sure to stop all of them to to localize the particular one is causing the issue.

Best regards, 
Nicolas

**Comment by Geounix** [comment]
I checked and I have none of that open, what other problem could it be?

**Comment by SHWotever** [comment]
Do you have the simhub logfiles ? It could help. It's available in C:\Program Files (x86)\SimHub\Logs

**Comment by Geounix** [comment]
[2021-01-07 14:49:57,668] INFO - Starting SimHub v7.3.2 (build time : 24/12/2020 11:09:12)
[2021-01-07 14:49:57,678] INFO - Administrator privileges : False 
[2021-01-07 14:49:57,683] INFO - OS version : Microsoft Windows NT 10.0.19042.0, Windows 10.0.19042
[2021-01-07 14:49:57,683] INFO - License status : Free
[2021-01-07 14:49:57,683] INFO - Process priority : Normal

**Comment by Geounix** [comment]
I will leave you some screenshots with all the applications that I have installed
![Capture1](https://user-images.githubusercontent.com/74307044/103934704-cb22c900-50fb-11eb-9246-f120109bdd2e.JPG)
![Capture2](https://user-images.githubusercontent.com/74307044/103934713-cfe77d00-50fb-11eb-83a7-a147160a07b2.JPG)
![Capture3](https://user-images.githubusercontent.com/74307044/103934721-d37b0400-50fb-11eb-9f45-b0dc6e3db818.JPG)
![Capture4](https://user-images.githubusercontent.com/74307044/103934732-d675f480-50fb-11eb-8091-322c72cb6148.JPG)

**Comment by SHWotever** [comment]
Thanks !

The log is really similar to the logs I usually see when there is an issue with a performance utility like I previously mentioned, 
Could you look in the system tray if it's not an application hidden here? Often it's linked to applications trying to inject an FPS/Performance overlay in games and crashing WPF applications.

Could you take a look in the windows event viewer in the "application" category, it should give more error details, errors will come by pair, one mentioning explicitely simhubwpf, and one about .net runtime.
![image](https://user-images.githubusercontent.com/2207331/103935166-747eb480-5126-11eb-81cd-7ae0b887217c.png)

**Comment by Geounix** [comment]
These are the errors reported to me
![Capture5](https://user-images.githubusercontent.com/74307044/103935535-1be6f180-50fd-11eb-910e-d1979528d8da.JPG)

**Comment by SHWotever** [comment]
Perfect ! could you paste me the mull details of the two first messages ?
![image](https://user-images.githubusercontent.com/2207331/103935938-5f565580-5127-11eb-9748-182cef6b96e7.png)

**Comment by Geounix** [comment]
Faulting application name: SimHubWPF.exe, version: 1.0.0.0, time stamp: 0x5fe4af18
Faulting module name: clr.dll, version: 4.8.4300.0, time stamp: 0x5f7e61bb
Exception code: 0xc0000005
Fault offset: 0x00046a52
Faulting process id: 0x1dbc
Faulting application start time: 0x01d6e52b1a0513d2
Faulting application path: C:\Program Files (x86)\SimHub\SimHubWPF.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Report Id: 6b297a45-144e-4a53-bbe1-4b6884c14e0b
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Geounix** [comment]
Fault bucket 1755613915326406134, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: SimHubWPF.exe
P2: 1.0.0.0
P3: 5fe4af18
P4: clr.dll
P5: 4.8.4300.0
P6: 5f7e61bb
P7: c0000005
P8: 00046a52
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER592B.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5B6E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5B7F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5B8C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5BBC.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_SimHubWPF.exe_74e213fa25373bd32b9ff267c33bbc7e58414fa1_28490c24_6bb514a1-c634-485a-9f8f-fe1673bd19f4

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6b297a45-144e-4a53-bbe1-4b6884c14e0b
Report Status: 268435456
Hashed bucket: 3bdbc5df86ed46e2d85d318de9c35df6
Cab Guid: 0

**Comment by SHWotever** [comment]
Thanks, it looks like you have .net framework corruption,
Could you try the following microsft repair utility ? https://www.microsoft.com/en-us/download/details.aspx?id=30135
Unfortunately .net framework corruptions are often complex, and it may or may not work, but it's worth a try ;)

**Comment by Geounix** [comment]
Thanks, the solution was to format haha, I have another question if it is not too much trouble, the application starts normal but when I try to use it for f12020 from my xbox it does not take the telemetry and I have it through the same port on the xbox

**Comment by SHWotever** [comment]
Hi! From xbox you have some extra steps to take care, your network settings, firewall opening etc ...  You will find all the troubleshooting/configuration instructions here : https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting
