### ISSUE TITLE
SimHub inconsistent data

### ISSUE THREAD

**Issue by Dji7877** [SHWotever/SimHub#723]
Hello,
I want to try SimHub to play F1 2020 on PS4.
When I run SimHub the communication works fine with the game, but when I run a dashboard the data is completely inconsistent.
Like speed 32 in the last lap 42:23:21.
Data comes and goes and it doesn't make sense.

**Comment by SHWotever** [comment]
Hi !

Looks like you are not running the correct telemetry version in the game settings, could you check it's correctly set to F12020 mode, not legacy or f12019

Nicolas

**Comment by Dji7877** [comment]
yes it's that thanks !
