### ISSUE TITLE
Alternative WS2812B Matrix column layout

### ISSUE THREAD

**Issue by Galukin** [SHWotever/SimHub#724]
Hello, I'm a n00b , so sorry if this is a easy question.
Image on the matrix from a standard sketch Arduino is displayed incorrectly:
Each even row of a matrix inverted horizontally. (In the Portrait Mod) Visually:
![Снимок](https://user-images.githubusercontent.com/77175386/104071212-bf2d2900-5219-11eb-802d-f5a9b8e9e9ae.JPG)
![IMG_20210109_000605](https://user-images.githubusercontent.com/77175386/104071390-22b75680-521a-11eb-8aeb-38cbb8c456ac.jpg)
![IMG_20210109_000915](https://user-images.githubusercontent.com/77175386/104071410-2b0f9180-521a-11eb-8c5c-564d1ca3066a.jpg)
![IMG_20210109_001145](https://user-images.githubusercontent.com/77175386/104071421-31057280-521a-11eb-83b5-4491130e389b.jpg)

Obviously, the program does not take into account that led strips take a zigzag course.
![Сни3ок](https://user-images.githubusercontent.com/77175386/104071888-1da6d700-521b-11eb-8b7c-d7c95b16add5.JPG)
How can I solve this problem?

**Comment by SHWotever** [comment]
Hi thanks for the report, indeed the Arduino code doesn't support this layout, until now I only encountered simple column in only one direction. I will look to add this layout in a future update.

Nicolas

**Comment by SHWotever** [comment]
hi ! The update has been released with the support of this layout.

Nicolas
