### ISSUE TITLE
Nextion LED Stuck when screen turns off.

### ISSUE THREAD

**Issue by ZebbeBa** [SHWotever/SimHub#725]
Hi and tanks for an Amazing Software 🥇 that lights my life and make my seat shake ;)
but... 

I have a 2,4" nextion and one W2812B Neopixel attached via a micro pro with nextionmicrobridge.

When I end a game the LED freezes in its current state when the screen turn off, if I have the "power of Screen" feture enabled.
Then when I disabeld the "power of Screen" the NeoPixel unfreezes and turns off.

It is like the Micro pro stops sending data when the screen is turn of.

Resulting that the lights are one untill i start a new game.

Video: [https://youtu.be/sHSd8F67Oks](https://youtu.be/sHSd8F67Oks )

What i have tried:
- Change the Neopixel
- Change the Pin from 6 to 5
- Resoldered the ground
- Reinstalled all the software
- Reconfiguerd all the settings.
- Replicated the issue on my brothers "clean" computer.
- Test the micro pro to work like a "normal" led controller = works.
- Grabed the Microbrige from the web.
- Tested to have more pixels in the config but just to have one in real life.
- Made my onw rule for when "when game is running" via "GameRunning" property.

What i will try:

- Change the Micro pro to a diffrent one.
- Re-map the nextion and make a Json  

I dont know if this is a feature that should work, but as the LED are within the "when game is running" i guess i should?

**Comment by SHWotever** [comment]
Hi ! Indeed communication stops when screen is stopped, it's a side effect. I will look to change that

**Comment by ZebbeBa** [comment]
Super! Much appreciated!

I guess that would enable people to run fewer micro pro controllers when paired with a nextion screen and LED :-)

**Comment by SHWotever** [comment]
Hi ! I close this as Nextion is out of support for about one year and new nextions models have broken simhub compatibility
