### ISSUE TITLE
Trigger start engine missing

### ISSUE THREAD

**Issue by RandyyCN** [SHWotever/SimHub#726]
Hi team,

Unfortunately i deleted the "default" rgb led profile where there were the pit limitation and the trigger start engine animation. Is there anyway to get it back?

Regards

**Comment by SHWotever** [comment]
Hi you can reset your arduino leds settings by copying this file in C:\Program Files (x86)\SimHub\PluginsData\Common
[ArduinoRGBLedsSettings.zip](https://github.com/SHWotever/SimHub/files/5825831/ArduinoRGBLedsSettings.zip)

Alternatively you can add effects by clicking here : 
![image](https://user-images.githubusercontent.com/2207331/104837080-a1636200-58b2-11eb-92d5-48ba01dad80a.png)

Nicolas
