### ISSUE TITLE
SimHub on smartphone or tablet

### ISSUE THREAD

**Issue by Dji7877** [SHWotever/SimHub#728]
Hi,

I have a problem when I use a dashboard on a smartphone or tablet.
The dashboard is regularly in "Reconnect" state or there is a delay of a few seconds of information. 
It works fine on the PC.
I don't understand why but it cannot be used in this state.

Thanks,
Regard

**Comment by SHWotever** [comment]
Hi !

Have you tried the troubleshooting guide available here : https://github.com/SHWotever/SimHub/wiki/Troubleshoot-Dashstudio-Web-access#dash-is-lagging-or-randomly-disconnecting

Nicolas
