### ISSUE TITLE
Sector Times - Strange values

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#729]
Hi,
It seems the sector times tracker doesn't work properly, with ACC and iRacing at least.
But in a different way for both games:

ACC Brands Hatch
![Sector iRacing ACC Brands Hatch](https://user-images.githubusercontent.com/50543913/104601999-34b25280-567b-11eb-807e-7d512b765971.PNG)

iRacing Daytonna oval
![Sector iRacing Daytonna oval](https://user-images.githubusercontent.com/50543913/104602033-3ed45100-567b-11eb-8100-7f139867dc0c.PNG)

**Comment by Romainrob** [comment]
Hi Alex.
I guess I got confused by the the tags for iRacing.
It's probably not trying to time the sectors but reports the lap time as the 3rd sector as you said
Maybe this is expected then.
Since the sector index updates according to the 3 sector split of the lap, I expected the tracker to time these

Regarding the shorter sectors, with a little help from Wotever, I'm now able to get times accurate to the game for these ;)

For ACC, I've seen this sector time issue reported on Discord multiple times.

**Comment by SHWotever** [comment]
Hello !

I've fixed it in the last release, indeed there was a computation issue the data changed between "AC1" and ACC (despite beeing the same telemetry definition.)

**Comment by Romainrob** [comment]
Hi.
Thank you for the fix!
Bon dimanche.

**Comment by AlexLaSarthe** [comment]
Just to note that @Romainrob has a plugin available which does provide iRacing sector times via interpolation, which supports sector count > 3.
