### ISSUE TITLE
Combining PL9823 & WS2812B

### ISSUE THREAD

**Issue by jkatz098** [SHWotever/SimHub#730]
Can we please have this enabled, I use the WS2812B for my RPM lights but want to use PL9823 for flag lights, I don't want to have to use separate Arduinos

**Comment by SHWotever** [comment]
Hi ! No i'm sorry i can't combine both, i'm already suffering of sketch size issues and combining both would lead to an additional memory usage in the arduino.
In the simplest cases it will work I aggree, but in some combo like oled etc ... it won't fit anymore if I complexity the led management.

Nicolas

**Comment by jkatz098** [comment]
I definitely think just being able to have PL9823 & WS2812B would be really worth it, it makes no sense to change my rpm lights to the leds, and the WS2812B are spaced out too far for flag lights
