### ISSUE TITLE
Thurstmaster TS-XW Rimless not found by Thurstmaster manager

### ISSUE THREAD

**Issue by Dakoriki** [SHWotever/SimHub#731]
![1](https://user-images.githubusercontent.com/77527118/104806299-36952680-57df-11eb-862f-9a7a069ad18d.PNG)
![2](https://user-images.githubusercontent.com/77527118/104806303-39901700-57df-11eb-85f8-348d1f37ce78.PNG)
I saw one ticket for a similar thing to this so here should be the info for it
USB\VID_044F&PID_B692&REV_0100

USB\VID_044F&PID_B692

Computer\HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_044F&PID_B692\OEM\JoystickSettings\832700381

**Comment by SHWotever** [comment]
Hi ! Thanks for the info ! I've added it for the next release.
