### ISSUE TITLE
Nextion template uploading issue

### ISSUE THREAD

**Issue by Dexiion** [SHWotever/SimHub#732]
Hi, I have a nextion 4.3" screen wired to an arduino pro micro as you can see on the image
![WhatsApp Image 2021-01-16 at 14 46 02](https://user-images.githubusercontent.com/61138950/104814978-b637eb00-5809-11eb-9cc1-4cf9c977c304.jpeg)

But when I try to upload some templates on the screen I get this error

![Captura](https://user-images.githubusercontent.com/61138950/104814991-ca7be800-5809-11eb-8530-222de9e307cb.PNG)

I've been searching but I couldn't find nothing to solve this

**Comment by SHWotever** [comment]
Hi ! Have you uploaded the nextion specific sketch it is required to communicate with the screen? https://github.com/SHWotever/SimHub/wiki/Nextion-Display#uploading-arduino-micro-sketch

Also, I can't see it in the picture, but could you double check the wiring ? Rx goes to tx and "vice versa"

Nicolas

**Comment by Dexiion** [comment]
> Hi ! Have you uploaded the nextion specific sketch it is required to communicate with the screen? https://github.com/SHWotever/SimHub/wiki/Nextion-Display#uploading-arduino-micro-sketch
> 
> Also, I can't see it in the picture, but could you double check the wiring ? Rx goes to tx and "vice versa"
> 
> Nicolas
> 

Yeah, I follewed the guide, anda the rx is on the tx and tx is on the rx

**Comment by SHWotever** [comment]
Strange if you did all like written (wiring, j1 and sketch) it means something is wrong between the Arduino and the screen,

Could you double check your soldering quality ? Often a cold solder, or a bad solder is enough to break the communication.
If everything is ok on this point it means there is a physical issue with the screen or the Arduino, in all cases if you can't upload the design, it means simhub won't be able to send telemetry data neither.

**Comment by Dexiion** [comment]
Yes, that was the problem he wires weren't solded correctlt. Thank you so much.
