### ISSUE TITLE
[Feature Request] Best Sector Times

### ISSUE THREAD

**Issue by Super71962** [SHWotever/SimHub#734]
Hi,
I have been working on SimHub dashboards for about a month now and think it is excellent. 
I have one issue that I haven't been able to resolve so far;  in practice and qualification sessions I want to show current lap, last lap and best lap sector times as 1. overall session best (purple), 2. personal session best (green) and 3. slower that personal best (yellow). I have been successful with 2 (green) and 3 (yellow), but cannot find a way of comparing sector times to overall session best sector times (me plus other drivers) to show purple sectors.
I have managed to do this for last lap and best lap times but not individual sectors.
Any help much appreciated.
Regards, G

**Comment by Super71962** [comment]
Sorry, forgot to mention, this is with rF2.

**Comment by Shaftoe62** [comment]
I concur. I've been struggling with this as well.

**Comment by SHWotever** [comment]
Hello ! I close this as it's available since a few versions for every opponents. Best lap sectors/best sectors/current lap sectors/last lap sectors when available or guessing possible from the game.

**Comment by Super71962** [comment]
Great enhancement Wotever!! It all works perfectly :D
