### ISSUE TITLE
SSD1322 OLED Screen

### ISSUE THREAD

**Issue by maberalc** [SHWotever/SimHub#735]
Hi, I just got interested on integrating this kind of OLED screen (SSD1322 2,8" OLED 256*64) on my steering wheel. I got two questions:

- I'm used to Arduino programming and I'm gonna try to integrate it on the sketch that comes with Simhub using another library. I'm just here to know if you were trying to integrate it already or if you could let me know were does it send things to the OLED display. Is it on SHGLCD_BASE.H?

- The other thing is about the templates. Do you plan integrating an editor on Simhub? Do you think I can change the template to use the full resolution of the screen or that I won't be able?

Thanks for your attention.

**Comment by SHWotever** [comment]
Hi !

You need to change this file :
SHGLCD_I2COLED.h

However with a larger screen you will probably have memory issues, currently the smaller size oled already fills the memory, and prevents to use almost any feature along.

For the previous reason I don't plan to add an integrated editor, the use cases are really limited due to these arduino memory issues and it's not worth the time investment.

Nicolas

**Comment by maberalc** [comment]
Yeah, I saw memory problems. In fact used a Mega to test it. But my plan is to use a Teensy 3.2 to use the gamepad with its own library + leds WS2812B + OLED. I will try to fit that in that teensy, else I would need to try on bigger teensy but I guess I will be able to fit that in.

Anyway thanks for the help. It would be great to have that editor tbo, but I understand why it would maybe be a loss of time.

**Comment by maberalc** [comment]
OK, and it just works fine. Changing position on txt files works too. Even using a Teensy LC, I can upload this OLED, Leds and Joystick. Nicolas, if you want more information about it, I'll just let you know what you want. Thanks for this awesome project. Simhub is amazing. 
Bye

**Comment by Phobia943** [comment]
Hey @maberalc  would you share your solution for the SS1322 with me?
