### ISSUE TITLE
[Feature Request] Support for Keypad 4x4 I2C?

### ISSUE THREAD

**Issue by Marcinekk** [SHWotever/SimHub#736]
Hi, i want to save some pins on my arduino, can you add support for I2C Keypad?

I have this keypad https://www.dx.com/p/new-16-key-44-membrane-switch-keypad-4x4-matrix-array-matrix-keyboard-for-arduino-smart-car-2731624.html#.YAxn-uhKiUk

And PCF8574 expander (https://botland.store/expanders/4455-module-pcf8574-gpio-expander-board-for-microcontroller-waveshare-3708.html) (can set address 0x20 or 0x27, so it can't have conflict with LCD 16x2/20x4 I2C)

This keypad working with https://github.com/joeyoung/arduino_keypads/tree/master/Keypad_I2C library.

**Comment by SHWotever** [comment]
Hi !

No unfortunately it requires to use interrupts in order to receive data, but interrupts do not interact correctly with high speed serial communication (lost/ broken data), Currently I can't add anything which make uses of interrupts. 

Nicolas
