### ISSUE TITLE
USBD480 Actions Broken in latest beta

### ISSUE THREAD

**Issue by v4voodoo** [SHWotever/SimHub#737]
Hey folks, just a heads up that the latest 7.3.3b releases seem to have broken triggering dash actions on USBD40. I've gone up and down the versions to verify and 7.3.2 doesn't have the issue.
The behavior is that whatever key mapping is mapped to GraphicalDashPlugin_USBD480_ActionA 
(or B, C, or D) does nothing. Logs don't show the action triggered either. GraphicalDashPlugin.ActionA triggers just fine, so it's only for USBD480 as far as I can tell.

**Comment by SHWotever** [comment]
Thanks ! Indeed it was broken, it's fixed for the next release !
Nicolas

**Comment by v4voodoo** [comment]
Cheers!

**Comment by SHWotever** [comment]
Hi !
It has been fixed with latest version ;)
