### ISSUE TITLE
New session based fuel calculation defaults

### ISSUE THREAD

**Issue by v4voodoo** [SHWotever/SimHub#738]
I love the new per session fuel calculation setting, thank you!
This is minor but breaks dashboards. I've noticed that using the old calculation the default for last lap fuel used to be 0, which dashboards sometimes checked against to display - or n/a. The new calculation defaults to -1, which breaks those checks.
It would be nice for the new value to default to the same value as the old to maintain dashboard compatibility. This is only an issue on the first lap since there is no last lap then.

**Comment by SHWotever** [comment]
Hi ! Thanks for the feedback ! It's fixed for the next release !

Nicolas
