### ISSUE TITLE
[ShakeIT Motors] Usage of multiple L298N boards with Arduino Uno

### ISSUE THREAD

**Issue by gustavomassa** [SHWotever/SimHub#739]
Hello, first of all, thank you for this awesome project! I would be glad to help you.

Arduino Uno is capable of handling at least 2 L298N boards with 4 ShakeIt Motos, but the Arduino Setup only allows us to change between on/off. Maybe starting with the possibility of 2 boards would be perfect.
![image](https://user-images.githubusercontent.com/16235598/105621357-6054db80-5de5-11eb-9418-a0092f669712.png)

The second L298N board could be mapped to pins 13,12,11 and 4,3,2.
I could help you with the code and tests, I have multiple boards and motors to test, but I don't see any way to look up the generated code.
Are you using PlatformIO?

**Comment by gustavomassa** [comment]
@SHWotever I just found out that there is a button to "Open in Arduino IDE", and also figured out the path `SimHub\_Addons\Arduino\DisplayClientV2`

I will do the necessary modifications to be able to handle 2 LN98N Boards on the same Arduino.
Also if you don't mind, I would like to create a repo with the  DisplayClientV2 project and migrate it to PlatformIO.

**Comment by gustavomassa** [comment]
I have a lot of questions. Do you have any docs regarding the protocol used to communicate with Arduino? I was taking a look on the SHCommands.h, but with a doc would be easier.

How can I add/remove TemplateEntry items? As I understood each TemplateEntry has a unique id registered in some file/db. The Arduino Setup Tool is using some kind of string replacement on the.ino file to enable/disable the defines based on the TemplateEntry and conditions.
![image](https://user-images.githubusercontent.com/16235598/106235707-f91a9b00-61d9-11eb-965d-7adb78407230.png)

The first time I changed the code I thought the motors count of the L298N Board was hardcoded on the C# client based on the providerName, then I realized it is being set here:
```
void Command_Motors()
{
#if defined(INCLUDE_SHAKEITADASHIELD) || defined(INCLUDE_SHAKEITDKSHIELD) || defined(INCLUDE_SHAKEITL298N) || defined(INCLUDE_SHAKEITMOTOMONSTER) || defined(INCLUDE_SHAKEITPWM) || defined(INCLUDE_SHAKEITPWMFANS)

	char action = FlowSerialTimedRead();
	// Count
	if (action == 'C')
	{
		FlowSerialWrite(255);
		FlowSerialWrite(ADAMOTORS_SHIELDSCOUNT * 4 + min(1, DKMOTOR_SHIELDSCOUNT) * 4 + min(2, L98NMOTORS_ENABLED) * 2 + min(1, MOTOMONSTER_ENABLED) * 2 + min(4, SHAKEITPWM_ENABLED_MOTORS) + min(4, SHAKEITPWMFANS_ENABLED_MOTORS));
```

The providerName is used just as a description? or is there any other logic behind it?
![image](https://user-images.githubusercontent.com/16235598/106235664-e738f800-61d9-11eb-814f-cc5e55b2c6d4.png)

**Comment by SHWotever** [comment]
Hi ! I'm sorry these parts are not intended to be modified, so there isn't  public documentation available ;)

Description is indeed just a description , It helps for troubleshooting when people reports issues (most of the time it's related to the wrong board being configured, so that's my first check, look the log and check it's the correct board) 

Template entries are self contained in the Arduino source code, the commented JSON at the end of each defines lines contains all the required details to feed the configuration UI. Each time group name is set it initiates a new group and all the next options will be assigned to this group until a new group name is defined. It allows to minimise setup tool maintenance so I can focus exclusively on the Arduino source code.

Nicolas

**Comment by gustavomassa** [comment]
Thank you for the info Nicolas!

The 3 motors using two L298N boards are working fine so far. Now I would like to add a PWN fan for the second LN98N motor output that is not being used.
Can I use the PWM fan as a normal motor using the L298N motor output?
Or should I use one of these PWN output and modify with to output from the L298N board?
I want to use the L298N board because I need 12V and a PWM input.
![image](https://user-images.githubusercontent.com/16235598/107137494-f6abf580-68eb-11eb-8ffc-c9c956c39e00.png)
