### ISSUE TITLE
Nextion und WS2812B funktioniert nicht gleichzeitig

### ISSUE THREAD

**Issue by Neo-One-sim** [SHWotever/SimHub#742]
ich möchte ein Nextion 2,4 und 13x WS2812B auf einem Pro Micro arbeiten lassen
Leider geht nur eines der beiden.
Wenn ich die Übertragung zum Nextion aktiviere funktioniern die LED´s nicht 
Teste ich die LED´S mit dem internen testprogram kann ich keine Nextion übertragung machen.
Aktiviere ich die Nextion verbindung vor dem schließen von Simhub, verbinde ich dann per USB das Pro Micro leuchtendie  LED´s doch dann kann ich mit dem internen testprogram keinen test machen , die LED´s leuchten die gesammte zeit.
Deaktiviere ich die verbindung noch Nextion in Simhub jedoch vor dem schließen, und ich verbinde dann das Pro Micro per USB leuten die LED´s kurz auf erlischen dann und ich kann in dem testprogram die LED´s testen doch dann kann ich die verbindung zum Nextion nicht machen.

Kann nur eine funktion nutzen Nextion oder LED´s doch zusammen geht nicht.
Habt ihr eine Idee was ich hier falsch mache?

**Comment by SHWotever** [comment]
Hi ! I'm sorry I don't speak german, so I used google translate, but translation is really approximate, 

It looks like youy are not using the correct sketch, make sure to use the one given here : 
https://github.com/SHWotever/SimHub/wiki/Nextion-Display#uploading-arduino-micro-sketch
