### ISSUE TITLE
Multi Class Track Map

### ISSUE THREAD

**Issue by stuartrpearson** [SHWotever/SimHub#743]
So I’m seeing people using track maps on their iracing streams with the dots being color specific for the class.  KAPPS seems to have the majority of users but would it not make sense for someone to offer a decent alternative. 

The track map included here is very limited on that aspect and it would be an awesome feature to include carclassColor and then it may become more well known for its track map leading people to look into other parts of the app.

**Comment by Romainrob** [comment]
Hi,
Per opponent dot colors would be a nice touch indeed.
This request keeps popping up on Discord, the forum and my PM.
I think there is a real interest for it. ;) ;)

Maybe the color could affected per position so we could use repeat index and drivercarclass(position) or custom class/team colors properties to build our formulas

Please.
Bonne journée.

**Comment by SHWotever** [comment]
Hi ! This is now available in the last version.

Nicolas
