### ISSUE TITLE
dash studio ne répond pas

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#744]
Hello
très réguilèrement, j'ai le même problème
je lance dash studio et il ne répond pas.
impossible de changer de screen par exemple pour mon dash qui possède 2 screens
impossible de faire quoi que ce soit
et simhub consomme de 24% à 28% de cpu environ et le problème ne se résoud pas ; le dash n'est toujours pas utilisable pour le modifier
j'attends quelques minutes mais ca ne se débloque pas

je ferme simhub et le relance et cela résoud le probème jusqu'au prochain problème
ca se produit déjà depuis plusieurs versions

[SimHub.log](https://github.com/SHWotever/SimHub/files/5903992/SimHub.log)

**Comment by SHWotever** [comment]
Hello !

J'ai retrouvé la copie des deux dashs que tu m'avais déja envoyé pour le moment je n'ai pas réussi à reproduire, est ce qu'il y a un déroulé ou cela se produit plus souvent ? (Juste pour confirmer c'est bien lors de l'édition ?)

**Comment by herve4545** [comment]
quelques fois cela se produit pendant que je joue. je fais alt/tab pour modifier un truc dans le dash
d'autres fois c'est en dehors du jeu
j'ai pas réussi à déterminer le pourquoi du comment mais ca arrive quand même souvent
aujourd'hui, ca m'est arrivé 3 fois. pendant que je créais le ticket d'anos, je suis resté bloqué plusieurs minutes sans solution.
j'ai fermé et relancé et pas de problème
la plupart du temps : j'ouvre le dash et j'arrive donc sur l'écran idle et je clique sur la flèche next screen
assez souvent, j'ai un replay simhub qui est lancé juste avant ou juste après
[V1.0.zip](https://github.com/SHWotever/SimHub/files/5904984/V1.0.zip)

**Comment by herve4545** [comment]
autre test du jour
pendant que je joue à raceroom
alt/tab
impossible d'ouvrir un dash...simhub se mets à consommer 25% de cpu
je reviens sous le jeu et je finis la course....pendant tout ce temps, simhub consomme toujours 25% de cpu
je quitte le jeu 
j'essaie d'ouvrir un autre dash...impossible de l'ouvrir
j'essaie d'ouvrir encore un autre dash....il s'ouvre mais je ne peux pas le modifier
je ferme simhub et tout revient à la normale

**Comment by herve4545** [comment]
Le problème ne s'est pas reproduit depuis plusieurs jours
Le passage de l'écran "idle" vers l'écran "game" peut demander quelques secondes.....était-ce le problème initial ? Je ne sais pas

**Comment by SHWotever** [comment]
:D désolé j'ai pas fait de retour, mais cherché à l'attraper sans succès pour le moment. Je garde le ticket ouvert encore un peu au cas où je trouverai quelque chose ;)

**Comment by herve4545** [comment]
J'ai parlé trop vite
Ça s'est reproduit hier avec RaceRoom en cours.
J'ouvre mon dash et impossible d'aller sur les détails d'un paramètre et simhub qui consomme 25%de cpu

**Comment by SHWotever** [comment]
Hello ! J'ai reussi à reproduire quelque bizarrerie qui semble s'etre evanouie avec une meilleurs priorisation des differentes taches (aquisition de données, rendues), j'ai inclu ce correctif dans la dernière version. J'espère que cela solutionnera le problème.

Nicolas

**Comment by herve4545** [comment]
Hello
Merci
Ca fait un moment que j'ai pas eu de problème

**Comment by SHWotever** [comment]
Cool ! 

Je soupconne aussi les drivers nvidia car j'ai eu pas mal d'autres bizareries (pas liées a Simhub) qui ont aussi disparues, cela pourrait correspondre à une MAJ des drivers, mais c'est plus difficile à prouver/vérifier.

**Comment by herve4545** [comment]
Chez moi, ça ne vient pas de mes drivers nvidia. Je n'ai pas upgradé mes drivers de carte graphique depuis plusieurs mois

Sur mon dash, j'ai positionné l'écran idle en 2eme ; ce qui fait que quand j'ouvre le dash, j'atterris directement sur l'écran comportant toutes les données que je modifie le plus souvent

**Comment by herve4545** [comment]
Hello
toujours quelques problèmes
[SimHub.log](https://github.com/SHWotever/SimHub/files/6177036/SimHub.log)
![1](https://user-images.githubusercontent.com/58605557/111898260-360a4d80-8a25-11eb-8cb6-4a0cab4c901f.jpg)

**Comment by herve4545** [comment]
le dash ne veut pas se charger
obligé de fermer et relancer simhub
![1](https://user-images.githubusercontent.com/58605557/111911216-e51a4980-8a64-11eb-9d5a-d0f6a7c17a89.jpg)

**Comment by SHWotever** [comment]
Hello je clôture, je n'ai pas eu de retour similaires sur la nouvelle version de l'éditeur.

Nicolas
