### ISSUE TITLE
Nextion Upload Error

### ISSUE THREAD

**Issue by TerryP9** [SHWotever/SimHub#745]
Hello,

I created my own dashboard in Nextion and when I try to upload the TFT file to Nextion, it connects, Start to upload and then there is an error (see image above).

![image](https://user-images.githubusercontent.com/78366785/106476175-c6400380-6474-11eb-8faf-50e2104eb5e5.png)

I uploaded other HMI to see if the issue was the display and I was able to do it successfully.

Am I missing something in the configuration? I am using an Arduino Micro Pro.

Thank you!

**Comment by TerryP9** [comment]
I just reran it and now it can't find the Nextion
![image](https://user-images.githubusercontent.com/78366785/106476585-38184d00-6475-11eb-816f-d9e16241876f.png)

**Comment by SHWotever** [comment]
Hi ! it means that there are communication issues, make sure that the sketch is still the correct one, and double check the solderings/wirings, weak/bad soldering, in Theory 115200 upload speed should be 100% reliable when the board is correctly wired.

**Comment by TerryP9** [comment]
Hello
It works when I upload another dashboard so I assumed the soldering is good.
![image](https://user-images.githubusercontent.com/78366785/106477949-b5908d00-6476-11eb-95a0-0df16d1f3492.png)

**Comment by TerryP9** [comment]
Ok so I disconnected the USB, compiled my file, exported the TFT, and pushed it to the Nextion uploader and now it works.

I think it is important to disconnect and reconnect in between different dashboards (correct me if I'm wrong).

Thank you! :)

**Comment by SHWotever** [comment]
Yes indeed, it's the bold advice asking to reset it before uploading. Unfortunately the nextion firware is bugged and prevents multiple upload in a row, but only the manufacturer can fix it.
