### ISSUE TITLE
hmijmap file not creating

### ISSUE THREAD

**Issue by TerryP9** [SHWotever/SimHub#746]
Hello,

I am creating my own Dashboard and I hit "_create sim hub Structure file_".

I followed this link https://github.com/SHWotever/SimHub/wiki/Nextion-Missing-mapping-file

It only generates the **.hmistruct** file and not the **.hmijmap** file.

How can I generate the **.hmijmap** file?

Thank you!

**Comment by SHWotever** [comment]
Hi ! 
- hmistruct is created from the nextion editor ("create sim hub Structure file". button)
- Hmijmap is created withing simhub, 

If you don't have this last file there are two options :

- **You are currently creating your template**, in this case you may not have created your 'hmijmap' file yet
   - Simply follow the instructions available in the [template creation guide](https://github.com/zegreatclan/SimHub/wiki/Nextion-Display---Template-creation-using-mapping-editor) 

- **You are installing a third party template**
   - **If the hmijmap file is provided**, make sure it's copied along the hmistruct file (files must be stored in the same forler and have the same name : 

    ![](https://i.imgur.com/EnydghT.png)
   - **If the hmijmap file is not provided**, it's likely the template is using the deprecated ".ini" files, in this case you simply need to migrate it using the following method : [Migrating legacy templates to editor templates](https://github.com/zegreatclan/SimHub/wiki/Nextion-Display---Migrating-legacy-templates-to-editor-templates)

**Comment by TerryP9** [comment]
Ok got it I need to click on Edit Mapping in Simhub and create my own 👍 

Now if I need some data, not in the predefined Role I need to follow this: https://github.com/SHWotever/SimHub/wiki/NCalc-scripting---Introduction

Is that correct? For TC / Brake Balance / ABS / Fuel liters, etc

Last thing, if I want to add the clock, how is that possible?

Thank you!

**Comment by SHWotever** [comment]
Hi ! Yes, for everything outside of predifined roles it's the way,

The clock is also available as ncalc look for currentdatetime property.

**Comment by TerryP9** [comment]
Also, I'm using a Custom Wheel running Joystick Board, will there be a way to program the Nextion screen so when I click "Next Page" on my wheel it can change the screen?

Thanks!

**Comment by SHWotever** [comment]
Yes you can assign controls here : 
![image](https://user-images.githubusercontent.com/2207331/107127786-c5660200-68b8-11eb-8c54-9a59e1e63b0d.png)

Nicolas
