### ISSUE TITLE
AMS 2 et les t° des pneus

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#747]
Hello
Il y a un problème avec ce jeu et les T° des pneus
- Il y a un gros écart entre les t° des pneus affichés dans le jeu et le T° des pneus que l'on trouve dans la télémétrie dans simhub. Ca concerne les T° inner/middle/outer

J'imagine que c'est le jeu qui ne fournit pas les bonnes infos dans la télémétrie, mais je pose quand même la question

exemple avec les pneus rear left
1)dans la télémétrie, les t° inner et outer sont beaucoup plus élevées et les valeurs semblent être inversées entre inner et outer
2) dans la télémétrie, la T° globale du pneu est correcte par rapport à ce qui est affiché dans le jeu

![1](https://user-images.githubusercontent.com/58605557/106607721-eef2f680-6563-11eb-8f3c-779ce241ce44.jpg)

**Comment by SHWotever** [comment]
Hello !

Effectivement AMS2 (et pcars2) ne donne pas de donnée  inner/middle/outer en mode shared memory, c'est donc mappé sur carcasse, thread etc, qui n'est pas ce que tu attends ... Cependant la donnée est dispo en mode udp (il faut aller dans "game config" dans simhub et choisir le mode UDP et configurer le jeu de manière appropriée. Attention le mode UDP peux mettre le bazar sur le réseau en "spammant" tout le réseau, j'en ai fait les frais il y a pas longtemps, dommage qu'on ne puisse pas configurer une ip dans le jeu ca éviterai bien des problèmes.

**Comment by herve4545** [comment]
ok merci
je vais laisser en l'état

**Comment by SHWotever** [comment]
Pas de soucis !
