### ISSUE TITLE
Error while executing color change binding on text element

### ISSUE THREAD

**Issue by cramis1** [SHWotever/SimHub#748]
I have an overlay that includes a relative box, with some of the elements in the relative box changing color based on the car class. I have noticed that in some cases, the color are effectively getting 'stuck'. Staying at one color even after that position in the relative box changes to a different car that should be a different color.

[Picture of example](https://media.discordapp.net/attachments/306850822518734848/801667621992005632/Question.PNG?width=908&height=610)

Here is an example of one of the color bindings:

    `if(isnull(prop('iRacingExtraProperties.iRacing_DriverBehind_02_ClassColor'),0)==(isnull(prop('IRacingExtraProperties.iRacing_Player_ClassColor'),0)),
    'FFFFFFFF',
    isnull(prop('iRacingExtraProperties.iRacing_DriverBehind_02_ClassColor'),'FFFFFFFF'))`

I have recorded a replay and when I play back the replay, the 'formatted result' of the associated binding outputs the correct hex color, but it does not end up changing what is displayed on the overlay. Attached is a log of when I played back the replay. It appears that I am getting the error: 

    `ERROR - An error occured while executing binding on TextItem4 if(isnull(prop('iRacingExtraProperties.iRacing_DriverAhead_01_ClassColor'),0)==(isnull(prop('IRacingExtraProperties.iRacing_Player_ClassColor'),0)),
    'FFFFFFFF',
    isnull(prop('iRacingExtraProperties.iRacing_DriverAhead_01_ClassColor'),'FFFFFFFF'))
    
     System.FormatException: Token is not valid.
       at MS.Internal.Parsers.ParseColor(String color, IFormatProvider formatProvider, ITypeDescriptorContext context)
       at System.Windows.Media.ColorConverter.ConvertFromString(String value)
       at SimHub.Plugins.OutputPlugins.GraphicalDash.EditorModel.Applybindings(IBindable item, String objectName, DashboardBindingData binding, IFormulaEngine GraphicalDashEngine), formula will not be evaluated for 30s
    `

[SimHub.log](https://github.com/SHWotever/SimHub/files/5937172/SimHub.log)

The overlay and the replay file are available here: https://1drv.ms/u/s!Ak5hbgqd0_Pyjq5bnZ5qmbEM2_3ktA?e=O2fIhq

**Comment by SHWotever** [comment]
Hi color codes have to start with a #, 'FFFFFFFF' is not valid and will freeze the formula due to an error, you need to use  '#FFFFFFFF' 

Nicolas

**Comment by cramis1** [comment]
Oh that makes sense. Thanks!
