### ISSUE TITLE
After Upgrade to SimHub V7.3.6 - Delta Time / Session Best not working in older Simbin Games

### ISSUE THREAD

**Issue by lemmingsch** [SHWotever/SimHub#750]
Hi

After upgrading to V7.3.6 in GTR2 and GTL (and mabye the other Simbin Titles) the Session Best/Delta Time is missing (may related to the Map Feature which is not available on this Sims).

Its working again when downgrade back to 7.3.4.

If needed i can provide more information.

Best Regards

**Comment by SHWotever** [comment]
Hi !

Thanks for the report, you are right a bug was unfortunately introduced in the latest version, games not capable of providing a track name in telemetry would not save the session best data. It's fixed for the next version !
