### ISSUE TITLE
e36 fuel and temp not working simhub 7.3.7 licensed

### ISSUE THREAD

**Issue by WeeFella7T2** [SHWotever/SimHub#751]
hey there i was wondering is the e36 fuel and temp scripts broke in simhub as i cant get them to work if so can we expect a fix if not thats all fine

**Comment by SHWotever** [comment]
Hi ! The gauges were not working properly since the beginning unfortunately, I only marked them as non working to avoid false hopes ;) https://github.com/SHWotever/SimHub/wiki/BMW-E36-Cluster-Setup#update-2020-05-20

**Comment by WeeFella7T2** [comment]
hey there cheers for the quick response thats sad new to hear but hey ho the speedo and rpm are cool to see just going crazy do you have any idea how to wire custom fuel guages or temp guages

**Comment by SHWotever** [comment]
No I'm sorry, I've not made experiments with any other models.

**Comment by dannyatyeo** [comment]
hi what setting did you use for the speedo i cant seem to get mine working
