### ISSUE TITLE
ShakeIt Wind simulation - Shield Docs

### ISSUE THREAD

**Issue by TheJltres** [SHWotever/SimHub#753]
In the image, positive and negative are inverted?
![image](https://user-images.githubusercontent.com/23702867/108511158-cb4be200-72bf-11eb-8ab0-57fc751cb3c6.png)

https://github.com/SHWotever/SimHub/wiki/Arduino-ShakeIt-Wind-simulation#plugging-to-the-shield.

**Comment by SHWotever** [comment]
Hi ! Thanks ! It's fixed, in all cases as wrote in the documentation it's a good reflex to double check polarity of those shields since their are not explicitly labelled.

Nicolas

**Comment by TheJltres** [comment]
Thanks!
