### ISSUE TITLE
Sector times (sector 2) in ACC wrong?

### ISSUE THREAD

**Issue by mihi4** [SHWotever/SimHub#754]
Hi, Wotever!

I thought, sector2LastLapTime would be just the time for sector 2.
But GameData.Sector2Time as well as even GameRawData.Graphics.LastSectorTime are showing something different - both properties have the current TOTAL laptime at the of the sector in it.
e.g. If sector 1 is 30seconds long and sector 2 20seconds, LastSectorTime would be 50 seconds (or 50000 in rawdata) instead of 20 seconds (20000).
Is this behaviour correct? Or shouldn't it either be 30/20 for the respective sector times?
Especially, since sector3 time again is only the value of the specific sector...

greetings
michi

**Comment by SHWotever** [comment]
Hi !

Which version are you running ? it's something i've fixed recently : https://github.com/SHWotever/SimHub/issues/729

**Comment by mihi4** [comment]
Aaaaah, that could be it.

7.3.2

 

thx a lot, I'll update asap ;)

 

greetings

michi

 
 

Gesendet: Freitag, 19. Februar 2021 um 17:01 Uhr
Von: "Wotever" <notifications@github.com>
An: "SHWotever/SimHub" <SimHub@noreply.github.com>
Cc: "Michi Hirczy" <mi.hi@gmx.net>, "Author" <author@noreply.github.com>
Betreff: Re: [SHWotever/SimHub] Sector times (sector 2) in ACC wrong? (#754)


 

Hi !

Which version are you running ? it's something i've fixed recently : #729

**Comment by mihi4** [comment]
Everything fine in version 7.3.7... thx a lot!
