### ISSUE TITLE
Minor UI text issue

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#756]
Salut,
Je viens de remarquer ce petit accroc dans l'interface:
![USBD480Mappings](https://user-images.githubusercontent.com/50543913/108593886-cb5ae900-7376-11eb-94bc-7c7c306baa5f.png)
Bon week-end!

**Comment by SHWotever** [comment]
Thanks ! Fixed it ! A dumb carrier return inserted in the code :(

**Comment by Romainrob** [comment]
No worries.
Bon dimanche! :)

**Comment by SHWotever** [comment]
La nouvelle version est releasée avec le correctif. Merci encore !
