### ISSUE TITLE
PitLimiter indicateor in LFS broken

### ISSUE THREAD

**Issue by Luchianull** [SHWotever/SimHub#759]
It seems that the value reported by the [DataCorePlugin.GameData.NewData.PitLimiterOn] in LFS is wrong or missing.
If running a dash using this function to display the PIT limiter status (like PhilmDash5 Multi), it will display continuously the PIT limiter warning.

**Comment by SHWotever** [comment]
Hi ! Thanks for the report indeed there was an issue. It's fixed for the next version.

Nicolas

**Comment by SHWotever** [comment]
Hi ! I've released the update with the fix.
