### ISSUE TITLE
LED animation & expanded editor

### ISSUE THREAD

**Issue by BuToNz** [SHWotever/SimHub#76]
iFlags type functionality...

![](https://i0.wp.com/boxthislap.org/wp-content/uploads/2016/06/iFlag.gif)

- Pick individual LED numbers/colours (not limited to RGB matrix LED's)
- Basic animations (Fade, flash, cycle colours)
- Built in Ncalc editor
- LED preview window (Perhaps tied to overall dash preview window?)
- Map function integration
- Standard matrix fonts to be able to use RGB matrix

**Comment by SHWotever** [comment]
Published with the final release !
Dedicated 8x8 Matrix support will come later ;)
