### ISSUE TITLE
Dashboard ne fonctionne pas en mode replay sur RBR rally

### ISSUE THREAD

**Issue by TovoMG** [SHWotever/SimHub#761]
Bonjour
mon dashboard ne fonctionne pas quand je suis en mode replay sur RBR rally . J'utilise la dernière version SimHub 7.3.7.
Par contre il marche trés bien en jouant.
J ai bien décocher la cage '' Masquer hors course '' . Il affiche mais ne fonctionne pas
Comment pourrais je remédier cela svp ?
Merci beaucoup
![image](https://user-images.githubusercontent.com/80110095/110125696-e7717800-7dc3-11eb-8ed3-013b53c82a1f.png)

**Comment by SHWotever** [comment]
Bonjour,

Oui simhub ne se connecte au jeu que en mode "live" pas en mode replay, c'est le cas pour la plupart des jeux pour éviter que toutes les stats générées dans simhub soient faussées.

**Comment by SHWotever** [comment]
RBR est un cas a part dans tous les cas, il n'y a pas de télémétrie officielle, et je suis obligé de lire en mémoire ce qui réduit la marge de manoeuvre.

**Comment by TovoMG** [comment]
ReBonjour...pourtant il marchait bien avant en mode replay avec la version 6.9.6 si vous pouvez voir svp. Merci bien
