### ISSUE TITLE
Dash Studio - rFactor2 mAntiLockBrakes does not update

### ISSUE THREAD

**Issue by bobafrek** [SHWotever/SimHub#767]
When trying to read changes to rFactor2 ABS settings during game I receive only a fixed number (2) and it does not update even when the in-game setting changes. When observing GameRawData.extended.mPhysics.mAntiLockBrakes I only ever get a fixed value of 2. (Expected behavior a value between 0 and 2 depending on level of ABS selected in settings)
I can confirm that the same issue exists if I observe GameData.ABSLevel. I am running the latest version of rF2SharedMemoryMapPlugin running default settings and am getting other updates without issue (Traction Control works as expected for instance).

**Comment by SHWotever** [comment]
Hi ! Unfortunately the data is not given by the game only the used assist settings : https://github.com/TheIronWolfModding/rF2SharedMemoryMapPlugin/issues/18

Nicolas

**Comment by bobafrek** [comment]
Thank you for the response. The latest Release candidate of rFactor 2 (on
Steam) seems to have resolved this data field for me and it is working
again. I am not sure if this is a temporary resolution or if they have
changed something in the codebase that will be in the non-beta final
released product. Thought it was worth mentioning to you.
Kind Regards,
Brian
