### ISSUE TITLE
Lap status (valid/invalid) not recorded in Simhub Telemetry

### ISSUE THREAD

**Issue by Luchianull** [SHWotever/SimHub#768]
Currently, when I test my Simhub dash live, in ACC - the status of the lap (valid/invalid) is correctly indicated.

However, if I am using a recorded session, the status is always recorded as valid.

Not sure if the issue is that the data is not correctly transmitted by ACC, or simply not recorded by Simhub telemetry recording feature but the effect is that I cannot debug the dash off-game.

Thank you for looking into it.

**Comment by SHWotever** [comment]
Hi ! What data are you using ? Graphics.IsvalidLap ? That's strange the data is recorded and replayed as is. It should not an issue.

**Comment by Luchianull** [comment]
I'm using 'ACCCDS_Graphics.isValidLap'.
In live mode, works as it should.
With recorded data, it always returns True.

**Comment by SHWotever** [comment]
Ah I see, I'm sorry accds is a third party plugin ;) it's not part of stock simhub ;) I think he acquire data directly so it won't go through the simhub record replay feature, this feature can only replay game data directly acquired by simhub. 
If you use the simhub stock graphics.islapvalid it will.

**Comment by Luchianull** [comment]
Oh, I understand - I never saw other function in the list (when doing the elastic search) and made the wrong assumption that there is only one.

I apologize for wasting your time.

**Comment by SHWotever** [comment]
No problems, 
All the "game specific data are masked by default ,when watching the property list check "show game specific data to show them.

Nicolas
