### ISSUE TITLE
OLED Multiple Screen Pages

### ISSUE THREAD

**Issue by maberalc** [SHWotever/SimHub#769]
Hi, I finally made it and finished my project with that big OLED screen. My question is if it is possible to have multiple pages on the screen and swap between them with a button or something...

**Comment by SHWotever** [comment]
Hi ! You simply need to create another folder in the related mode (ingame or idle) : 
![image](https://user-images.githubusercontent.com/2207331/111587941-2ee40500-87c3-11eb-81be-509780477d14.png)

Then you can map an input to nextscreen in control and events :
![image](https://user-images.githubusercontent.com/2207331/111588065-589d2c00-87c3-11eb-94a9-adc2fd7d82f7.png)

PS : SimHub will only show screens for the current mode so if you add the new screen in "ingame" folder it will only allow to to switch to it when the game is running.

Nicolas

**Comment by maberalc** [comment]
Oh I see, thank you so much.
