### ISSUE TITLE
getting bass noises into headphones when using bass shaker software

### ISSUE THREAD

**Issue by evo97** [SHWotever/SimHub#772]

**Comment by SHWotever** [comment]
Hi ! Make sure to review your windows sound car settings, this often happens when you have some mirroring options active or some advanced mixer software. Also just as a safety measure do not hesitate to double check the your headphones are not enabled inside the simhub sound output settings. 

Nicolas

**Comment by evo97** [comment]
Thanks for the reply Nicolas
Don’t think I have windows mirroring options active (what am i looking for?)

The only sound output active in simhub is voicemeeter

It’s strange been working fine for months then yesterday powered pc off and something must of updated and caused the problem 

even done a fresh install of Windows today (2hrs to set everything up 😥 and still the same

**Comment by SHWotever** [comment]
Mirroring can take many forms, here is a simple example : 
![image](https://user-images.githubusercontent.com/2207331/112544028-d5796880-8db6-11eb-82e1-738fd52396e0.png)

But it can exist at driver level, it really depend of your hardware and drivers. 

As a simple diagnosis test, If you are using voicemeeter could you try to simply shutdown voicemeeter, if I correctly remember it will stop redirecting sound to the configured vioicemeeter outputs, and you should not have any shakeit  sound anymore in your headphone. If you still hear something it means that simhub is sending sound to an unexpected device (directly to your headphones), but if it stops it means that Simhhub is working correctly and that's indeed something between drivers or voicemeeter.

Could you also join the log files ? it will contain traces of the allocated sound devices (c:\Program Files (x86)\SimHub\Logs\).

**Comment by evo97** [comment]
Thanks will look into that’s tomorrow

**Comment by evo97** [comment]
Ok quickly checked the above sound setting this morning and that’s correct 

By turning voicemeeter off I still had windows notification sounds but when opening Assetto Corsa I had no sound?

will attach log file this afternoon 
Thx again for your help

**Comment by SHWotever** [comment]
Thanks for the feedback, in the case logs will be unnecessary, if it stopped when voicemeeter was disabled it means it's correctly sent to the expected output(voicemeeter in this case) so it means it's voicemeeter which is spreading the sound to both your headphones and your bass shakers sound card. Could you check the voicemeeter output settings ? as far as I remember output settings are on the to right corner, based on the final result I think you got it configured (not intentionally :D) to mix both game input and shakers and outputting the result to both outputs. 

If you can I would simply disable voicemeeter, make windows default sound card to the headphones, simhub to the expected output, it should work straight ;) then go back to voicemeeter and tickle the settings.

Nicolas

**Comment by evo97** [comment]
That would make sense. Maybe it’s voicemeeter that’s at fault and did a update ???
Thing is I thought a clean install of windows would of sorted it?

It’s set up as per these instructions with A1 set to Realtek audio with buttkicker plugged into green jack on motherboard and A2 set to Logitech headset with usb dongle in USB port (I’ve also tried different USB ports)

There’s a bass setting in voicemeeter and by turning that down to minimum the buttkicker no longer rumbles (makes sense) but still get the feedback (crackle) in headphones 


Maybe I need to ditch voicemeeter and find another mixing software 


Really appreciate your help with this matter

**Comment by evo97** [comment]
Forgot to add link of instructions 


https://thebuttkicker.com/content/BK-GR2_QSG.pdf

**Comment by SHWotever** [comment]
Hard to say, There are so many settings (in voicemeeter, in windows etc ...) it makes each setup pretty unique.

Concerning those instructions in the BK manual they are intended in order to redirect game sound into the buttkicker, but in the case of simhub it already generates the sound directly and send it to the wanted sound card, so it's not useful.

**Comment by evo97** [comment]
Ok so I could delete voicemeeter then 
I thought I needed it to split sound to buttkicker (green port on motherboard) and headphones (usb dongle)

sorry I’m not very computer savvy

**Comment by evo97** [comment]
Sorted I ditched voicemeeter and pointed simhub to Realtek audio

Thanks so much 
Strange why it used to work tho but I’m happy to ditch another program running in the background 👍
