### ISSUE TITLE
Simhub crash on unhandles exception

### ISSUE THREAD

**Issue by mhensen** [SHWotever/SimHub#774]
I have a controller that is not always responding.. don't know why..
But this causes simhub to crash ..
attached the log file

[SimHub.log](https://github.com/SHWotever/SimHub/files/6214347/SimHub.log)

**Comment by SHWotever** [comment]
Hi it looks like you have some big issues with your controllers, it probably makes the direct input unstable. Could you try to disable the controller input plugin in simhub settings ? It will disable any code reading the controllers and so those instabilities should not affect simhub anymore.

Nicolas
