### ISSUE TITLE
Throttle goes off when the brake motor activates 

### ISSUE THREAD

**Issue by carlosisla28** [SHWotever/SimHub#775]
Hi wotever! I’m Carlos isla and I’m having some troubles. First I thought my tlcm pedals where wrong because the throttle goes off and stucks at 20% I traced the problem to the brake motor. (I have 10 motors and 2 fans) the throttle motor doesn’t make the problem.100% secure it’s the brake motor that causes some problem that the pedal goes off, what details can I offer you to you help me to solve this? Please? Do I need to isolate the motor? Or solder some 1uf(I don’t no what’s the things name) maybe grounding the motor? Please help!

**Comment by carlosisla28** [comment]
I describe the problem. If I activate all motors (without the brake motor) to 100% via simhub it’s ok. But when I include the brake motor and activate all to 100% the throttle goes off in seconds. I need to unplug and plug again to make it work, when I’m racing it happens a lot!

**Comment by carlosisla28** [comment]
All the motors work fine and give no problem. The problem is the throttle caused by the brake motor .
![FC1A5E2F-6A8C-478B-8D5D-32FC1454BAB1](https://user-images.githubusercontent.com/81610277/112942786-e3e4be80-90ed-11eb-8969-b1e32eb1ac68.png)

**Comment by carlosisla28** [comment]
https://user-images.githubusercontent.com/81610277/112942895-04ad1400-90ee-11eb-96b8-3ab8c60f327f.MP4

**Comment by carlosisla28** [comment]
![F1E01D2C-4B89-417E-8A29-79F4BFE92917](https://user-images.githubusercontent.com/81610277/112942941-11ca0300-90ee-11eb-9846-4f07754b8553.jpeg)

**Comment by SHWotever** [comment]
Hi ! This definitely looks like some issues in the pedals themselves, could you try to simply unscrew the guilty motor and hold it with hand to see if it stops. At first sight I would think about a short occuring in the pedals or a bad solder being "shaken" when the motor triggers. 
It could be a power leak too, but it's less likely to happen as your motors looks properly encased and insulated.

By the way those motors weight are huge it may stress a lot both pedals and motor shield, make sure that it matches the shield power specifications (it's written on the wiki or the manufacturer page)

Nicolas

**Comment by carlosisla28** [comment]
I wil try it tomorrow! It’s very awkward how it happens. If I have to guess. I don’t think it’s the vibrations itself that causes the throttle problem, already ordered a new set and will try it, but I’m confused why if a have all motors except the brake one it works fine. 
do you recommend installing the 3 .01 uF thing?

can it be static? 

All my
Motor are 12v, they work great with the exaggerated weight jaja 

I also want to thank you for simhub! I already donate but men, your software make me addict to sim racing .

**Comment by carlosisla28** [comment]
I don’t understand how the weight of the motor can stress on the motor shield?

**Comment by carlosisla28** [comment]
If it’s an emi issue, does the 3 pieces of .01 uf on the motor solve it?

**Comment by carlosisla28** [comment]
Okok! I will look again at the connections! I had the motors for like 3 years without failure and working awesome. In fact the bigger one is set to 40% so it doesn’t be to strong.

i will try a new set of pedals on Sunday, I hope it was a pedal problem! I’m so hyped to test the new rig.

**Comment by benjy3gg** [comment]
I have a similar Problem with the T-LCM Pedals and a rumble motor (smaller one from a cheap PS controller).
Whenever i have simhub open and the arduino connected, after sometime, my Throttle gets stuck and the pedals stop working.
Had the T3PA-Pro Pedals before and it was working fine with them. The Problem might be that the T-LCM are using a Hall-Sensor in the Throttle and Clutch Pedals in comparison to a Potentiometer in the older T3PA-Pro Pedals.
