### ISSUE TITLE
High CPU usage 7.3.10

### ISSUE THREAD

**Issue by bvdkerkhof** [SHWotever/SimHub#778]
[SimHub.log](https://github.com/SHWotever/SimHub/files/6239007/SimHub.log)
[SimHub1.log](https://github.com/SHWotever/SimHub/files/6239008/SimHub1.log)
[SimHub5.log](https://github.com/SHWotever/SimHub/files/6239011/SimHub5.log)

Using Simhub for sometime now and I noticed that since 7.3.10 my Assetto Corsa is reporting High CPU usage. After shutting down the game and looking into TaskManager I noticed SimhubWPF.exe is using 24% CPU. When closing Simhub and running the game all is just fine. 

In my opinion using 24% CPU for Simhub is quit alot. 

**Setup**
Intel i5 9400F
16GB mem
Nvidia GTX 1660 Super 6GB

**Simhub info**
Using Bass Shaker
Using Arduino Uno (disabled output but no impact) with 2Fans for Windsim
Overlays in AC

Disabled plugins and addons to only have the above 3 working, but this has no impact on the CPU usage.

**Comment by SHWotever** [comment]
Hi ! Indeed it's defenitely too high , i'm currently hunting such similar issues. 
However in the logs SimHub1.log and SimHub5.log it shows that you are trying a run a dash without having the plugin and it triggers a lot of errors   (plugins which are known for their high cpu usage unfortunately), such errors will consume a lot of cpu, Could you try with a stock dash to see if it's  the cause of the cpu issue in your case ?

Also i'm not sure what kind of overlay you are using, some overlays around are really complex and "big" (in term of screen surface) making simhub suffer a lot. Make sure to keep moderate about how many overlays and the screen covered size https://github.com/SHWotever/SimHub/wiki/Dash-Studio-Overlays#performances

**Comment by DrTodd13** [comment]
@SHWotever 
[SimHub4.log](https://github.com/SHWotever/SimHub/files/6332259/SimHub4.log)
[SimHub1.log](https://github.com/SHWotever/SimHub/files/6332260/SimHub1.log)
[SimHub2.log](https://github.com/SHWotever/SimHub/files/6332262/SimHub2.log)

I'm also having the same issue.  There are "watchdog" things in my log that I don't know if they are a problem or not.

**Comment by SHWotever** [comment]
Hi ! Sorry I missed your message, could you try without the Gary swallow plugin, I see it still here in the logs, it's known to consume a lot of CPU. In idling on a stock simhub you should have a consumption around 0~1%
