### ISSUE TITLE
ACC NCalc [GameRawData.Cars]

### ISSUE THREAD

**Issue by KrisV147** [SHWotever/SimHub#779]
Sorry, me again..... Might be something and nothing.

NCalc [GameRawData.Cars] has the raw result below for ACC specific properties checked;

System.Collections.Generic.Dictionary`2[System.Int32,ksBroadcastingNetwork.Structs.RealtimeCarUpdate]

When scrolling through list of available properties, a handful above and below this one disappear briefly.

**Comment by SHWotever** [comment]
Hi ! Indeed it should have been hidden by default, it's fixed for the next release.
