### ISSUE TITLE
please add Thurstmaster T-GT support wheel to Thrustmasters FFB control plugin

### ISSUE THREAD

**Issue by mcmZero** [SHWotever/SimHub#783]
productGuid of Thrustmaster T-GT is "B684044F-0000-0000-0000-504944564944".
I would appreciate it if you add it. :)

**Comment by SHWotever** [comment]
Hi ! For sure ! I also need some registry keys as shown in this ticket : https://github.com/SHWotever/SimHub/issues/731 could you grab it ?

**Comment by mcmZero** [comment]
![image](https://user-images.githubusercontent.com/2320910/113521552-25d1a100-95d5-11eb-9a2e-46816ca475ae.png)

USB\VID_044F&PID_B684&REV_0700
Computer\HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\VID_044F&PID_B684\OEM\JoystickSettings\624260363

**Comment by SHWotever** [comment]
Hi ! It's added it will be available in the next public version,
Nicolas
