### ISSUE TITLE
SNowrunner support

### ISSUE THREAD

**Issue by Fugu72** [SHWotever/SimHub#785]
Would it be possible to add Snowrunner to the SimHub supported game list?  I know Im probably one of the few players asking for this if not THE only one, but I think this game has a LOT of potential for vibrations and impact and Id really be happy to have a chance to make it work on my sim rig with the Buttkicker mini I just got. Thank you !!! :)

**Comment by SHWotever** [comment]
Hi ! No unfortunately there is no way to get telemetry, please be sure that as soon as the game make something available I will add it.
Nicolas

**Comment by Fugu72** [comment]
Hey Nicolas, I had a feeling I was gonna hit a dead end with the game.  Im trying to get too much realism out of a simple but awesome game.  Thanks for taking time to answer me.
Have a good one!
Frank :)

Sent from my iPhone

On Apr 6, 2021, at 2:25 AM, Wotever ***@***.***> wrote:

﻿

Hi ! No unfortunately there is no way to get telemetry, please be sure that as soon as the game make something available I will add it.
Nicolas
