### ISSUE TITLE
arduino pro micro sketch upload

### ISSUE THREAD

**Issue by helix118** [SHWotever/SimHub#786]
I am using an Arduino pro micro and have issues getting the sketch rgb LED sketch to fully upload. The arduino is showing in the device manager, but as soon as the sketch gest half way there is an error stating "Can't find arduino communication port". Is there something I am missing? 

![sim hub arduino sketch upload failure](https://user-images.githubusercontent.com/82016154/113663836-587ca780-9670-11eb-83f1-bd1a0dc35a90.JPG)

**Comment by SHWotever** [comment]
Hi ! This means something is going wrong during upload, in theory to uploadod the pro micro it's a matter of putting it in upload mode, the old serial port will disapeear, the new one will appear and must be used for upload, in your case it seems that the new one is not appearing.

As a workaround solution you can try directly with the official arduino IDE, when configured simply click on file/open in arduino IDE : 
![image](https://user-images.githubusercontent.com/2207331/113669780-8257bd80-96b4-11eb-99c0-515ab4f95ab7.png)

Then select your board(1), port (2) and click on upload (3) :
![image](https://user-images.githubusercontent.com/2207331/113669888-ae733e80-96b4-11eb-9a6f-3abdd873c228.png)

**Comment by helix118** [comment]
Merci Wot!

**Comment by helix118** [comment]
I may have spoke too soon! There is an error when I upload the sketch.

![image](https://user-images.githubusercontent.com/82016154/113772989-06c53300-96eb-11eb-8ddb-ed707c0348c1.png)


Arduino: 1.6.13 (Windows 7), Board: "Arduino/Genuino Micro"

In file included from sketch\SHRGBLedsNeoPixelFastLed.h:8:0,

                 from C:\Program Files (x86)\SimHub\_Addons\Arduino\DisplayClientV2\DisplayClientV2.ino:224:

C:\Program Files (x86)\SimHub\_Addons\Arduino\ArduinoIDE\arduino-1.6.13\libraries\FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.003.002

 #    pragma message "FastLED version 3.003.002"

                     ^


Sketch uses 12,604 bytes (43%) of program storage space. Maximum is 28,672 bytes.
Global variables use 596 bytes (23%) of dynamic memory, leaving 1,964 bytes for local variables. Maximum is 2,560 bytes.
An error occurred while uploading the sketch

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by SHWotever** [comment]
Hi ! This message is not an error it appears all the time to tell the library version, unfortunately it looks like you are having the same upload issue than you had with simhub integrated upload procedure. You can enable the "verbose" mode in the Arduino IDE to get more details, but I fear to will lead to the show the same issue. Maybe there is an issue with the pro micro bootloader. 

There are some rescue procedure available on the internet (reset the board manually, or re-upload a clean bootloader) but it is more complex to do. I can point you some links if you want to give it a try.

**Comment by helix118** [comment]
I attempted to reset the board a few times and tried to re-upload with no luck. Would it be worth just trying to get a new pro micro? I don't want to go into too deep a rabbit hole fighting the board to get it to work.

**Comment by SHWotever** [comment]
Hum indeed the last rescue procedure is to re-upload the bootloader, I had to do it a couple of times lately for another project and I won't lie it's "painful" to do, breadboard, use another Arduino, etc.. in my case it was required as I bricked it quite a few times in a row during my experiments :D but I guess in your case you can go straight to another pro micro.

**Comment by helix118** [comment]
Is there a certain procedure I should go through to load the sketch if I used another pro micro? Will I run into the same bootloader issues? I took a look at sparkfun's bootloader reset and am not sure if that's something I will have to do where, I have to reset for the sketch to upload correctly.

**Comment by SHWotever** [comment]
In theory no, all the pro micro I have in stock just works out of box, I plug it and upload that's it ;)

**Comment by helix118** [comment]
sounds good. I'll try it out
