### ISSUE TITLE
use relays with arduino and simhub?

### ISSUE THREAD

**Issue by Palmix64** [SHWotever/SimHub#787]
I guys, I've some rgb led (not smart), and I've tried to use that for flags by searching in the arduino code some way to put a pin to +5v, but I didn't found anything. could someone help me or I have to buy some pl... leds?

**Comment by SHWotever** [comment]
Hi it's not possible yet, only smart leds are supported.

There is already a feature request about this : , do no hesitate to suscribe to the page if you wan't to know when it will be implemented : https://github.com/SHWotever/SimHub/issues/682
