### ISSUE TITLE
shakeit motors problem since update 7.3.13

### ISSUE THREAD

**Issue by Grobi86** [SHWotever/SimHub#790]
Sadly my Shakeit motor settings for deceleration doesn't work properly since the Update 7.3.13. 

I have build an active seatbelt with an Arduino Uno for my Rig.

Since the update it feels like it's now mapped to road vibration. The test buttons for deceleration work properly, but in Pc2 it doesn't work anymore.

In version 7.3.8 everything worked fine.

please have a look at it.

Ps. Where can I download older versions? 

Keep up the great work!

**Comment by SHWotever** [comment]
Hi ! Thanks indeed I see the issue ! Here is a beta with the fix if you want to give it a try : https://www.simhubdash.com/unofficial/SimHub.7.03.14b1.zip

For older versions you can find them all here : https://www.simhubdash.com/official

Nicolas
