### ISSUE TITLE
Driver name of driver 17 (Esteban Ocon) not appearing in leaderboard in F1 2020

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#791]
I'm playing around with the leaderboard widget but somehow one driver name is not appearing. In stead it shows the drivers id.

Can I fix that myself?

Thanks

Jurgen Gardenier

**Comment by SHWotever** [comment]
Hi ! Thanks for the info, indeed it was not available originally, I see Codemasters added it to the list,
I've added the name for the next simhub version, 

Nicolas

**Comment by Shaftoe62** [comment]
Great! Thanks.

**Comment by Shaftoe62** [comment]
Here is the complete list by the way. In case you might be missing someone else. :-)

ID | Driver
0 | Carlos Sainz
1 | Daniil Kvyat
2 | Daniel Ricciardo
6 | Kimi Räikkönen
7 | Lewis Hamilton
9 | Max Verstappen
10 | Nico Hulkenburg
11 | Kevin Magnussen
12 | Romain Grosjean
13 | Sebastian Vettel
14 | Sergio Perez
15 | Valtteri Bottas
17 | Esteban Ocon
19 | Lance Stroll
20 | Arron Barnes
21 | Martin Giles
22 | Alex Murray
23 | Lucas Roth
24 | Igor Correia
25 | Sophie Levasseur
26 | Jonas Schiffer
27 | Alain Forest
28 | Jay Letourneau
29 | Esto Saari
30 | Yasar Atiyeh
31 | Callisto Calabresi
32 | Naota Izum
33 | Howard Clarke
34 | Wilheim Kaufmann
35 | Marie Laursen
36 | Flavio Nieves
37 | Peter Belousov
38 | Klimek Michalski
39 | Santiago Moreno
40 | Benjamin Coppens
41 | Noah Visser
42 | Gert Waldmuller
43 | Julian Quesada
44 | Daniel Jones
45 | Artem Markelov
46 | Tadasuke Makino
47 | Sean Gelael
48 | Nyck De Vries
49 | Jack Aitken
50 | George Russell
51 | Maximilian Günther
52 | Nirei Fukuzumi
53 | Luca Ghiotto
54 | Lando Norris
55 | Sérgio Sette Câmara
56 | Louis Delétraz
57 | Antonio Fuoco
58 | Charles Leclerc
59 | Pierre Gasly
62 | Alexander Albon
63 | Nicholas Latifi
64 | Dorian Boccolacci
65 | Niko Kari
66 | Roberto Merhi
67 | Arjun Maini
68 | Alessio Lorandi
69 | Ruben Meijer
70 | Rashid Nair
71 | Jack Tremblay
74 | Antonio Giovinazzi
75 | Robert Kubica
78 | Nobuharu Matsushita
79 | Nikita Mazepin
80 | Guanya Zhou
81 | Mick Schumacher
82 | Callum Ilott
83 | Juan Manuel Correa
84 | Jordan King
85 | Mahaveer Raghunathan
86 | Tatiana Calderon
87 | Anthoine Hubert
88 | Guiliano Alesi
89 | Ralph Boschung

**Comment by SHWotever** [comment]
Thanks ! I already took back the latest list from the codemasters documentation, and only this name was missing.
