### ISSUE TITLE
How do I activate the “online map service” correctly?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#792]
I've been reading about this in the release notes. But I can't find a setting anywhere.

I changed 

"UseOnlineMaps": true 
"MapSourcePriority": 1

in GlobalSimhubSettings.json and that seems to work. I'm not sure about the second setting.

I can't find anything on the web.

Jurgen

**Comment by SHWotever** [comment]
Hi ! All the settings are available here ;) 
![image](https://user-images.githubusercontent.com/2207331/114260855-9a428080-99d7-11eb-840e-128710cd5c9c.png)

**Comment by Shaftoe62** [comment]
What?!?! How can I have missed that?? I guess I was **_assuming_** (the mother of all fuckups) that this was a link to the regular settings!

Great! A whole new set of toys!

Thanks,

Jurgen
