### ISSUE TITLE
What is the F1 2020 map file format "shtl"? And can I unpack these in a more useable (json) format??

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#793]
As the title states, what happened with the old fashioned json files for the map layouts.

For Dirt Rally I've made a bunch of php scripts to convert this data to all sorts of fun stuff. For F1 2020 I had some similar ideas.

What can I do?

Example:

![Greece](https://user-images.githubusercontent.com/53898212/114274009-d21fe700-9a1c-11eb-877b-0a0696b141d1.jpg)

![Greece](https://user-images.githubusercontent.com/53898212/114273960-97b64a00-9a1c-11eb-8260-9f91da2df41d.jpg)

Jurgen

**Comment by SHWotever** [comment]
Hi ! The file format is exactly the same, (gzipped jsons) only the extension changed (shtl) in order to allow proper file association to the map viewer.
Some additionnal data have been also added (just additions) for better map drawing, but it's not a breaking change.

Nicolas

**Comment by Shaftoe62** [comment]
Ah! That is fantastic news. And any additional data can only be a good thing. I'll dive into it.

Thanks,

Jurgen

**Comment by Shaftoe62** [comment]
By the way, you mention a map viewer and I saw a MapViewer.exe in the SimHub root directory. But When I try to 'exetute' it, nothing happens. Does it need command line parameters or something?

Thanks,

Jurgen

**Comment by SHWotever** [comment]
Indeed it only opens double clicking on an shtl file.
![image](https://user-images.githubusercontent.com/2207331/114281910-64d27d00-9a41-11eb-8e05-7cb0d95ae5dd.png)

**Comment by Shaftoe62** [comment]
Oeoeoehhh... Very Nice! And indeed, this showcases nicely the advantages of the cloud maps. 

Are these available for Dirt Rally? Or is nobody playing that game anymore?

Fantastic, keep up the good work!

Jurgen

**Comment by SHWotever** [comment]
Yes they are available for dirt rally, however it gets downloaded "on demand" for each track you encounter, 
Indeed dirt rally 1 usage is quite low compared to other games and currently I have enough data the generate a cloud version of the map for only 30% of the tracks/configurations, and no tracks have past the "high quality point" with enough data to stop collecting new records (that said my "reject" algorythm is extremeliy strict to ensure that only coherent data is included in the map processing, so lot of the records are being rejected on rally games (penalties, crash, car spin ....)

**Comment by Shaftoe62** [comment]
Ok, understandable. 

When I started with my maps project I took the effort of driving all tracks (rally and hillclimb) in a very controlled manner. 

Obviously to get very accurate data. These are the records I am using.

But these have an enormous amount of data points because I was driving very slowly in order to stay on the road :-).

Could these be of any use? I'd be happy to upload them.

Or will they be anyway as soon as I play the game, now I have the Cloud Maps activated?

I suppose your algorythm will deal with the overload of datapoints and will optimize them, if accepted?

Jurgen

**Comment by Shaftoe62** [comment]
Oh, and if they will be uploaded automatically I wil take a tour through all maps so you will have all of them.

How long will it take for them to be processed after that?

**Comment by SHWotever** [comment]
The algorithm is made to start to generate after 5 valid error free/smooth laps and will take up to 150 ,  it will get processed after a few minutes, but track data or missing track data are cached on your computer for 4hours (to avoid overload on the server) it's clearly a mass learning process you can't trigger alone.
