### ISSUE TITLE
driver_ahead quelques rares problèmes

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#794]
Sur RF2 et peut-être sur d'autres jeux, quelques fois, les driver_ahead sont erronés
voir exemple. Je suis 17eme et le driver_ahead_00 est à 18 alors qu'il devrait être à 16
cela semble se produire au début d'une course où les places changent beaucoup car plusieurs dépassements
seuls les drivers_ahead semblent être impactés et pas les drivers_behind

![1](https://user-images.githubusercontent.com/58605557/114296116-a860d180-9aa9-11eb-9099-edbc4ddbc529.jpg)

**Comment by SHWotever** [comment]
Hello !

Ahead et behind ne sont pas basés sur les positions dans le classement mais sur la progression dans le tour (Ahead _on track_) de ce fait en fonction de comment le jeu l'évalue le classement cela peux différer un peu,  mais malheureusement je ne peux pas m'appuyer sur le classement pour garder ce comportement "on track"  , le but ici est de donner les infos des pilotes qui sont physiquement devant ou derrière sans notion de classement.

**Comment by herve4545** [comment]
OK merci
