### ISSUE TITLE
Labels for datapoints in MapViewer

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#797]
I 'assume' the MapViewer is some sort of svg viewer? If so, you could add labels tot the vertices that become visible when you hover over them.

I've been toying with the idea to use that possibility to compile pacenotes for Dirt Rally.

But if you label the datapoints with the 'lap distance' (and perhaps altitude) the MapViewer would be a very good tool to enrich the Global Maps with all kinds of extra data.

Like, for F1 for instance, speedtraps, DRS measuring/activation points, corner numbers , (famous) corner names, et cetera.

For Rally's it could be "pace notes" like corner severity, jumps, hazards, etc.

You get the idea...

Jurgen

**Comment by Shaftoe62** [comment]
I've been working some more on this and as it turns out you can't label individual vertices/nodes on an SVG path. Only the entire path.

So what i do now is to draw little circles on top of the datapoints. And those can be 'labelled'.

I'll attach an example file so you can see how that works and how the svg code should look.

For now I need only the distance from the start to 'place' roadsigns but it could be enriched in many ways...

P.S. Because the cloudmaps are so much more efficiënt I had to compensate for a shorter total length of the connected datapoints (in 3d :-D), to end up with the right total in the end.


[track[0000000][RY-AR-LJ-F-L][8256.86][las_juntas_heavy_gravel][cloudmap].zip](https://github.com/SHWotever/SimHub/files/6486669/track.0000000.RY-AR-LJ-F-L.8256.86.las_juntas_heavy_gravel.cloudmap.zip)

**Comment by SHWotever** [comment]
Hi ! Unfortunately after all those years this request remained completely unique. I close it for readability purpose even if the the feature would be interesting. On another hand maps are rasterized as a bitmap for performance so any texts would rotate with the map making it pretty much useless
