### ISSUE TITLE
I2C LCD display Arduino Leonardo wrong automatic pins assignment 

### ISSUE THREAD

**Issue by damiank388** [SHWotever/SimHub#798]
After enabling I2C LCD on in simhub with Arduino Leonardo it automatically assigns pins 18 - 19 .
Yet the signal is actually on pins 2 - 3. 
This results in having pins 18-19 out of use when already struggling with pins to connect matrix and rotary encoders. 
And some initial trouble shooting to figure out what is actually happening.

**Comment by SHWotever** [comment]
Hi ! I close this since it has been fixed since.

![image](https://user-images.githubusercontent.com/2207331/184529321-8076e1b6-60a3-44c5-b4ff-25f54cc78ac9.png)
