### ISSUE TITLE
Issue with acceleration and deacceleration bassshaker

### ISSUE THREAD

**Issue by carlosisla28** [SHWotever/SimHub#799]
Hi wotever, i just notice that when I activate acceleration or deacceleration on bassshakers shake it (assetto corsa) they give me feedback of road impacts. I Uninstalled and reinstalled but not change, also deleted the effects and setup them again and continue giving the wrong feedback, I installed sol, and use content manager, is there a setting im missing? Thank you for your time.

**Comment by SHWotever** [comment]
Hi ! Indeed there is an issue ,a fix is ready for the next version : https://github.com/SHWotever/SimHub/issues/790

PS : I close this ticket since it's a duplicate.

**Comment by carlosisla28** [comment]
Thank you!
