### ISSUE TITLE
Ahead / Behind - code etat

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#800]
Hello
Sur les infos ahead et behind, serait il possible de disposer d'une information supplémentaire type "état".

Sous RaceRoom par exemple, quand une IA a abandonné, elle reste aux stands mais on la voit toujours sur les ahead et behind à chaque tour.
Serait il possible d'ajouter un état "DNF" par exemple pour ces cas ?

**Comment by SHWotever** [comment]
Hello ! Je vais regarder, normalement dans le ahead/behind j'exclue tout ce qui est pits etc ... les DNF ont peut ètre un statut spécial.

**Comment by herve4545** [comment]
Sur rf2, on voit les dnf dans les ahead et behind
