### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by boothbenny** [SHWotever/SimHub#802]
i have loads of arduino nanos hanging around and have started to build my own f1 wheel i have tried to connect an 0.97 old and a strip of 24 ws2821b leds and when compiling i get sketch to large is there a way of using 1 nano for the oled and another for the leds but only using one usb cable or can i use an  Adafruit Feather HUZZAH with ESP8266 for both thanks for any help

**Comment by SHWotever** [comment]
Hi ! Infortunately the nano is too tight for hosting both : https://github.com/SHWotever/SimHub/wiki/Arduino-SSD1306-0.96''-Oled-I2C#restrictions

Currently only arduinos are supported : https://github.com/SHWotever/SimHub/wiki/Arduino--Setup#recommended-arduinos
ES32/8266 and other alternative boards are not, it would require to retest/rewrite lot of used libraries.

**Comment by boothbenny** [comment]
thanks for the quick reply i have just found an uno will that run both the oled and leds thanks

**Comment by boothbenny** [comment]
one more question will this be ok to run the oled and leds 

DollaTek Mega 2560 PRO MINI Embedded, MCU ATmega2560, USB CH340G

**Comment by SHWotever** [comment]
Hi ! Yes it's a mega just with another form factor, that should do the trick ;)

**Comment by boothbenny** [comment]
can confirm it works well thanks chap
