### ISSUE TITLE
Button Box - buttons doesn't display

### ISSUE THREAD

**Issue by ksbuchanan** [SHWotever/SimHub#803]
I am trying to apply an imaged to a button; however, the image doesn't display.  The image is 606px square png file, 

...any suggestion?  The default 'red button' that ships with the software is working, so I suspect it is related to the image - but I need to know if there are constraints for the button images.

**Comment by SHWotever** [comment]
Hi ! No thee is no direct constraint, the picture just has to be png or jpg (i've already seen some cases where only extension was changed but in reality it was tga, obviously in this case it won't work). Do you have an example dash to share with this picture, or the picture by iself to share so i can see ?
