### ISSUE TITLE
Assetto Corsa Competizione (ACC) doesn't trigger Yellow and Chequered Flag on SimHUB

### ISSUE THREAD

**Issue by SvenBillie** [SHWotever/SimHub#804]
Hey guys,

as described in the title, ACC doesn't trigger the yellow and chequered flag to sim hub, so they don't work on my LED panel. All the other flags (blue, white, black), spotter and gear display works just fine, so it's not a connection problem.

Do you have a conclusion for this? Is it a known issue for ACC?

Thanks

**Comment by SHWotever** [comment]
Hi ! ACC had lot of issues not reporting flags since the early days, they added global flags a few versions ago, i will see if it can replace the previously existing ones, it may not be accurate, but it's better than nothing.

**Comment by mihi4** [comment]
hmmmm? I'll have to check it out, but IIRC yellow works same as black/blue/green...
