### ISSUE TITLE
All black window

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#810]
Bonjour,
Once in a while when starting SimHub all I get is a black rectangle.
I start it minimized and when open the window it's all black.
Restarting SimHub fixes it.
I don't see anything in the logs or windows events viewer. So... good luck. :)

I believe it started with the 7.11b1 update. I'm not a 100% sure.
It happened the first time I started SimHub after updating, the last few updates since then.
At first I thought it was a one time time thing after updating but it happens, seemingly randomly every few days too.
Maybe it was a coincidence.

It's no big deal as it doesn't happen often and is easy to fix.
I just thought you should be aware of it in case other users have the same issue.
Let me know if If you want me to run any test. 
Bon week-end!

[SimHubBLACKWINDOW.log.zip](https://github.com/SHWotever/SimHub/files/6409459/SimHubBLACKWINDOW.log.zip)

**Comment by SHWotever** [comment]
Hum I know this one, it was originally an issue coming from mahapps I have a few workarounds in code which kept it quiet for long, but when I changed the settings storage solution I had to do it for Windows positions too and it came back and I had to rework my workarounds ,but it seems it's coming back, I will look, this one will be sneaky as in my computers I've not seen it since, It will be a game of trial and errors

**Comment by Romainrob** [comment]
Ok. Good luck then :).
I'll let you know if it's still happening on my end after you include a fix.
It'll take a few days to be sure as it's a somewhat rare occurrence.

**Comment by Romainrob** [comment]
Hi again.
Idk if you implemented a fix but this didn't happen to me since I openned this ticket. Classic!
Feel free to close this one. I'll let you know it it happens again.
Bon week-end!

**Comment by Romainrob** [comment]
Hi,
Idk it's worth reopening but it happened again.
Once after updating SimHub.
Just to let you know it's still a thing.
Bonne soirée.

**Comment by Romainrob** [comment]
Hi,
In case this can help someone.
I figured out a few days ago, I don't have to restart SimHub to fix it.
When the window is all black, clicking again on the SimHub icon in the notification area seems to refresh the Window and solves it.
