### ISSUE TITLE
Hotkey for restarting overlay

### ISSUE THREAD

**Issue by uo271694** [SHWotever/SimHub#811]
Please implement a hotkey for restarting an overlay without exiting the game, it would be very helpful for a lot of people

**Comment by AlexLaSarthe** [comment]
+1 - in fact a hotkey to reload the last loaded complete overlay layout would be perfect.

**Comment by Shaftoe62** [comment]
Will this be available in the next release?

**Comment by SHWotever** [comment]
Yes indeed, it's alreadt available in the beta, and it will be released with the next public version

**Comment by Shaftoe62** [comment]
Great! Tempting but I will have to be patient...
