### ISSUE TITLE
Game Reader - iRacing - CarClassEstLapTime 

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#816]
Salut,
Lors de la grosse maj de la dernière saison, iRacing a réparé CarIdxEstTime et ajouté CarClassEstLapTime aux données dispo.
Je crois que c'est suffisant pour calculer le gap directement depuis les données du jeu relativement simplement.

Ce soir, j'ai fait qq testes de gaps relatifs... oui, ça pousse tard :) ... en single class ça match bien le gap in game. En multi class je galère un peu pour corriger précisément le gap entre les classes, mais je ne suis pas loin du compte.
Bref, c'est prometteur dans l'ensemble.

1. CarClassEstLapTime est dans la SessionData string.
Pourrais-tu l'ajouter à SessionData.DriverInfo.Drivers stp?

2. Si tu voulais ajouter un "Game Computation mode" pour le gap d'iRacing, je pourrai te faire part de mes trouvailles. Si tout fonctionne correctement au final.

Bonne journée!

**Comment by Romainrob** [comment]
Salut,
Je me permets une petite relance stp.
Désolé de t’embêter avec ça mais je ne sais pas comment extraire correctement/efficacement des données de la session string.
Bonne soirée.

**Comment by SHWotever** [comment]
Hello ! J'ai ajouté la donnée pour la prochaine beta, 

Par contre j'ai du mal a voir comment ces données peuvent donner un gap, je suis preneur :D

**Comment by Romainrob** [comment]
Salut,
Super! Merci!
Ça va permettre de faciliter mes testes pour essayer d'affiner le gap entre classe.

Haha, c'est pas super intuitif, mais l'idée c'est que CarIdxEstTime donne le temps "supposé" qu'une voiture aurait mis pour atteindre le point ou elle se trouve sur le circuit. Un peu comme lapDistPct, mais exprimé en temps, et qui, du coup, compenserait pour la non "linéarité" lapDistPct due à une vitesse non constante.

J'avais déjà expérimenté avec par le passé, et ça fonctionnait seulement de temps en temps car la donnée n'était pas fiable.
Maintenant qu'ils l'ont réparées, ça m'a l'air bon.

La différence entre les CarIdxEstTime de 2 voitures de mm classe donne un gap plus stable, et plus proche de celui ingame.
Évidement c'est pas si simple.... ça se complique qd les voitures ne sont pas dans le mm tour, et surtout pas de la mm classe.

CarClassEstLapTime, lui nous donne le temps estimé au tour, fixe, pour chaque voiture, en fonction de sa classe (et mm du modèle semble-t-il). C'est la valeur max de CarIdxEstTime en fait, qu'on avait déjà pour le joueur, (DriverEstLapTime de souvenir) mais pas pour les autres classes.
J’espère pouvoir l'utiliser pour corriger le gap entre les classes avec un ratio MonCarClassEstLapTime/OpponentCarClassEstLapTime. Je m'attend à perdre en stabilité/précision comparé au single classe, mais je ne sais pas encore à quel point.

Je testerai qq variantes de calculs sur la prochaine beta et te dirai quoi, comme on dit par chez toi :)
Bonne journée et tôpette, comme on dit par chez moi!

**Comment by Romainrob** [comment]
Comme vu sur Discord ça fonctionne pas mal;)
Merci encore pour l'ajout.
Bon week-end!
