### ISSUE TITLE
Arduino MEGA 2560 OLED LCD

### ISSUE THREAD

**Issue by ObstacleTAKUYA** [SHWotever/SimHub#817]
Hello,
is it possible to use the OLED LCD with an Arduino MEGA 2560?
I enabled it in the Sketch Setup but it doesnt show any connection on the diagram.

Is this a bug or is it just not possible

Thanks

**Comment by SHWotever** [comment]
Hi ! Yes it's possible, the wiring is not configured in the setup tool, but you have a direct access to documentation : 
![image](https://user-images.githubusercontent.com/2207331/117554328-3f905900-b057-11eb-9742-894c1acc7a7e.png)

https://github.com/SHWotever/SimHub/wiki/Arduino-SSD1306-0.96''-Oled-I2C

**Comment by ObstacleTAKUYA** [comment]
oh okey thats need. i didnt see that in my window size. Thanks for the quick response.
Im currently developing a multi function box where you can plug in the "accessories" (Oled, Tachometer, Matrix) via RJ45 cables. 
![image](https://user-images.githubusercontent.com/54855101/117554354-69498000-b057-11eb-887f-b893f4449db8.png)

**Comment by ObstacleTAKUYA** [comment]
Sadly i still cant see the Component help window hmm

**Comment by SHWotever** [comment]
Hum, it probably means you are running an old version ;) I've added at the beginning of this year.
