### ISSUE TITLE
Wiki Arduino - enhancement

### ISSUE THREAD

**Issue by makejoint** [SHWotever/SimHub#818]
Hi, first of all, thank you for your awesome work! I just noticed that in the Arduino Wiki there is no mentioning of a FTDI driver to be installed or I didn't read carefully.

Following story: 
SW: SimHub installed, no Arduino IDE, Windows 10
HW: New PC, USB Arduino Nano 328p (used 328 in my SimHub config)

I was trying to upload an automatically created sketch, although no response from Arduino on COMx when uploading compiled sketch.

Root Cause: missing CH340 Driver, which I downloaded here [https://www.arduined.eu/ch340-windows-10-driver-download/](https://www.arduined.eu/ch340-windows-10-driver-download/)

I believe you could enhance the Wiki and mentioning that in case of failed upload, try to install the programmer driver (e.g., CH340).

Have a great day!

**Comment by SHWotever** [comment]
Hi ! I added a mention of it , however there are many drivers nowadays, so you have to install the driver matching your own board, Yours were CH340, but there are FTDI and there are other variations depending of the manufacturer choice.

https://github.com/SHWotever/SimHub/wiki/Arduino--Setup#board-drivers

**Comment by makejoint** [comment]
Thank you! Just to be picky, check the main page as well (missing paragraph link to "Board drivers").
