### ISSUE TITLE
Lower FPS for SimHub

### ISSUE THREAD

**Issue by bizibiz** [SHWotever/SimHub#819]
Hello Wotever,

1st amazing job, glad to be a donator for your great software.

A feature request from my side, a strange one maybe but would it be possible to lower SimHub activity ? Licensed product is running at 60FPS and free one is 10FPS. Would it be possible to running at some speed in between (30FPS)?

I don't know why since few weeks now, my ACC game is stuttering and the only way I found is to not run Simhub (ShakeIt) ... I'm a bit sad to don't have any more rumble in my ass.

Is there a way to lower SimHub activity ?

My specs :
i5 6600k @4.6GHz
16Go RAM
GTX 1060 6Gb OC
3400x1400 resolution (resolution scale 0.85)

I set almost all game settings to MID to get an average of 75% activity on both CPU & GPU + Frame limiter 70FPS

**Comment by SHWotever** [comment]
Hi ! Not sure if it's what you mean as the title only does not says a lot ,but you have some simhub fps control here : 
![image](https://user-images.githubusercontent.com/2207331/118401841-88539d80-b667-11eb-9c18-367e404b6ca2.png)

Slow is about 10FPS, Fast 20FPs, and very fast up to 60FPS depending of the computer load and how many dash/plugins you are running.

**Comment by bizibiz** [comment]
Sorry, my bad, I hit enter and the topic was created before I input any description.

Thanks in advance for your support.

**Comment by bizibiz** [comment]
> Hi ! Not sure if it's what you mean as the title only does not says a lot ,but you have some simhub fps control here :
> ![image](https://user-images.githubusercontent.com/2207331/118401841-88539d80-b667-11eb-9c18-367e404b6ca2.png)
> 
> Slow is about 10FPS, Fast 20FPs, and very fast up to 60FPS depending of the computer load and how many dash/plugins you are running.

Hi SHWotever,

Have you seen my question edited ?

Is there a way to reduce SimHub activity to 30FPS for instance instead of 60FPS (licensed version) ?
I'm using your ShakeIt Bass Shakers plugin.

Thanks in advance.

**Comment by SHWotever** [comment]
Hi Sorry I missed it, I've just read the final response, no it's not possible, but it's surprising,  maybe a bad interaction 
Could you try to disable any unused plugins , you can strip it down to something really minimalist :
![image](https://user-images.githubusercontent.com/2207331/118824934-8b929780-b8ba-11eb-8be5-9d0a0eddb2f2.png)

Could you try to disable the udp channel to see if it helps ? Put this file in Documents\Assetto Corsa Competizione\Config
[broadcasting.zip](https://github.com/SHWotever/SimHub/files/6509280/broadcasting.zip) Broadcasting api is a bit bulky in ACC, simhub will complain that the game is not configured but it does not matter for shakeit.

**Comment by bizibiz** [comment]
Hi,

I will try it tonight.
Regarding plugins, I've already disabled all unused, assuming that it can use some resources but I still have ingame stuttering.

Other settings I've changed below, can you tell me if I'm right do disable them (process priority & game reader priority) ?
![image](https://user-images.githubusercontent.com/30074885/118834172-4ffbcb80-b8c2-11eb-8a36-89a711841eea.png)

The last solution for me is to upgrade my setup unfortunately ... I read that ACC is much better when 5~6 cores.

Thanks in advance.

**Comment by bizibiz** [comment]
Hi  Wotever,

No improvement  by disabling  UDP with ShakeIt.
I will check for a hardware upgrade.
