### ISSUE TITLE
LED Matrix reversed

### ISSUE THREAD

**Issue by geniusboywonder2020** [SHWotever/SimHub#820]
Hello i purchased an led matrix from amazon and for some reason its reversed. I have to have it in serpentine mode but the display is the wrong way. Can an option to mirror it be added

**Comment by SHWotever** [comment]
Ah ! So it's a serpentine layout ? You confirm ?

**Comment by geniusboywonder2020** [comment]
yea if i have it non serp then it displays one pixel on each side

**Comment by geniusboywonder2020** [comment]
![image0](https://user-images.githubusercontent.com/62596232/118410026-56e9ca80-b685-11eb-916c-f11dcfd3d9a3.jpg) - SERP 

![image1](https://user-images.githubusercontent.com/62596232/118410034-636e2300-b685-11eb-910a-db61dd7f36c1.jpg)
- NON SERP

**Comment by SHWotever** [comment]
I tried a quick hack, actually it's easier on serpentine as it is already alternating left->right and right->left so it just required to hack the serpentine direction ordering,  
I don't have a serpentine matrix under hand to test it but it should be enough : 

Could you test it and tell me if if it solves it ? 
- Overwrite the file available in C:\Program Files (x86)\SimHub\_Addons\Arduino\DisplayClientV2 with this one :
[SHRGBMatrixNeoPixelFastLed.zip](https://github.com/SHWotever/SimHub/files/6489861/SHRGBMatrixNeoPixelFastLed.zip)
- Then upload again with serpentine mode enabled like before.

Let me know

**Comment by geniusboywonder2020** [comment]
LEGEND!!!! ITS WORKING :)

**Comment by SHWotever** [comment]
I added it as an option for the next release ;) 
![image](https://user-images.githubusercontent.com/2207331/118411027-e5b11400-b692-11eb-9e6c-7d99e6537a86.png)

**Comment by geniusboywonder2020** [comment]
Thanks :)
