### ISSUE TITLE
Are Dirt Rally 1 and Dirt Rally 2 reporting UDP data differently?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#821]
All this talk about car/track id's leave one thing open that I don't really understand.

For Dirt Rally 1 I made a dashboard that shows all recorded laptimes for a specific car/track combination. Perhaps you remember my issue #654 and related issues?

That worked fine for Dirt Rally 1. Also when the game was paused or when I went to the main menu. Which means that the Persistant Tracker data was retained outside 'game-running'.

For Dirt Rally 2 however this doesn't work. It works during a race and when the race is paused (I'm not sure) but definately not when the race is over or when I go to the main menu.

Is this because there is a difference between DR1 and DR2 on how they report the UDP data?

And if so, what would be a smart way to retain the Persistant tracker data for DR2? so I can review the results after a race?

**Comment by SHWotever** [comment]
Yes indeed if i correctly remember dr2 sends a final packet clearing everything (all data comes back to 0) i need to verify but if correctly remember that's the subtility,

**Comment by Shaftoe62** [comment]
That's not very nice of Codemasters.

But is there a way to retain everything?

I've been thinking about putting everything in my own (javascript) variables or object first. And use only these for my application.

Then I could prevent these from being updated whe one or more specific UDP values are zero.

I'm doing that allready for the track id by the way and I will need the same for the car id.

But that seems a pretty wasteful way to retain data I allready had.

It would be very nice if SimHub had a toggle for that.

If you look at my issues from the last few weeks you'll see that most are somehow related to this same fenomenon.

Losing the car id, losing the Persistant Tracker data...

If SimHub had a toggle to set to ingnore this final DR2 zero-package, that would be an enormous help. And not only for me I think...

**Comment by SHWotever** [comment]
I tried a quick hack to ignore that packet (which I confirm is the reset packet just happening at the end of the race) It works well, but I need to check it doesn't have any impact on all the other codemasters game (about 10 other games using the same code), that might take some time and I'm not sure it will be ready for the next release.

**Comment by Shaftoe62** [comment]
That's fantastic! It will solve a lot of problems for me and save me a hell of a lot of work.

In the meantime I will check if this packet is also send under other circumstances. Like abandoning a race to go to the main menu, restarting, "going to the service-area" etc. 

I  wonder why they have implemented that in the first place. Maybe in an effort to stop cheaters from uploading false results to the leaderboard.

And I guess it will be the same for all titles that were released after DR2. I own a lot of Codemasters games but I currently have only DR1, DR2 and F1 2020 installed.

But if I can be of assistance in any way, just let me know.

**Comment by Shaftoe62** [comment]
I've done some tests and as far as I can see the zero-packet is send at the finish and when you retire from the session (quit to main menu).
When paused or in the service area the data is retained.

**Comment by Shaftoe62** [comment]
Hi, it says "done". Does that mean it's in the beta? :-D

**Comment by SHWotever** [comment]
Done is that the code is done and to be released,

I should publish a new beta today or tomorrow including it ;)

**Comment by Shaftoe62** [comment]
Will that also include the reworked tack (and car) id system?

**Comment by SHWotever** [comment]
Yes ! Indeed !

**Comment by Shaftoe62** [comment]
(Copy) Hi, did you happen to make mapping tables for the new track id's, like the one you send me earlier (CodemastersDirtRally2.TrackNames.zip) for other games as well?

I've been using them for:

Dirt Rally 1
Dirt Rally 2.0
F1-2020

I have a lot of renaming/regenerating ahead of me...
