### ISSUE TITLE
données ahead/behind à zéro

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#822]
Hello
sous raceroom et peut-être d'autres jeux
quelques fois les données ahead et behind s'affichent à zéro
j'ai pensé que cela provenait de alltimebest à 0 mais ca ne semble pas être la cause
best lap à zéro pourrait être la cause ?

![3](https://user-images.githubusercontent.com/58605557/118496560-856ab280-b724-11eb-85c1-d14e4a05d1bc.jpg)

**Comment by SHWotever** [comment]
Hello ! 

Effectivement pour calculer les données j'ai besoin d'un temps de référence, c'est celui ci que j'utilise. Des qu'il est définit je peux commencer à calculer les gaps en mode relatif "ahead/behinf on track" 

Nicolas
