### ISSUE TITLE
Which license is this software under?

### ISSUE THREAD

**Issue by STPKITT** [SHWotever/SimHub#825]
Hi,
I failed to find any information about which license SimHub is actually published under. You guys need to put that information on the website and the readme here on GitHub.

**Comment by SHWotever** [comment]
Hi ! No particular license as the code is not public ;)

**Comment by STPKITT** [comment]
Ok, if that's the case then it should be flagged as freeware, donationware, shareware or something like that so that people know. Going open source under GPL license in the future would be the best though :-)

**Comment by SHWotever** [comment]
Hello ! It's hard to qualify it with such restrictive words : it's both free or licensed at user choice, with some additions for licensed obviously, you already have a page describing what brings the license : https://www.simhubdash.com/get-a-license/ 

I will think about how to word it better ;)
