### ISSUE TITLE
Export as property ?? (ShakeIt)

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#827]
In ShakeIt I noticed a checkbox "Export output value as property"

That sounds interesting athough I don't see an application for that for myself right now.

It is however something that I would very much like to be able to do in Dash Studio.

Now I have to repeat functions/calculations often to be able to use the same result for different purposes (change value, color, size, position, transparency, visibility, whatever).

It would be fantastic if I could create my own properties.

Maybe as a checkbox like in ShakeIt of as a function in the formula editor.

Or is there allready a way to do that that I'm simply not aware of?

Forgot to mention: I use javascript in the formula editor

**Comment by SHWotever** [comment]
Yes, you can share js functions using this : https://github.com/SHWotever/SimHub/wiki/Javascript-Formula-Engine#common-functions

**Comment by Shaftoe62** [comment]
I allready make use of the "JavascriptExtensions" folder extensively.

But I still call these functions for every 'binding'.

If I understand the tutorial correctly, I can store results in a 'root' object? And then use that as a 'property' in other bindings?

For example:

Binding 1:

get_track_data () // a function in a "JavascriptExtensions" fil

return root.track_name


Binding 2:

return root.track_country // I have the value available here because I called the function in Binding 1 ??


If so, does this apply for all bindings (only) in the same "dashboard?

Or does it apply for all bindings in all dashboards and all overlays running from the same SimHub Server?

I use two tablets that are connected through ethernet to my game PC. and overlays on the PC itself.

 So if the latter is true I only need to call those functions in one running dashboard or overlay, to have all the root values updated for everywhere else?

**Comment by Shaftoe62** [comment]
Hmm.. No, that doesn't work. I still need to call the function for every binding.

What am I missing/overlooking here?

root seems to work/behave like any other array/object.

**Comment by SHWotever** [comment]
Yes indeed formula execution scope is per binding : https://github.com/SHWotever/SimHub/wiki/Javascript-Formula-Engine#execution-scope

If you want to go further and have the full control over the data in a centralised way the plugin is the way to go.

Ncalc/js is intended for data transformation (changing unit, basic maths, while plugins are intended for data processing, storing data, persisting data etc...

**Comment by Shaftoe62** [comment]
Yeah, we had nearly the same discussion months ago. 

But that's exactly why I am so intrigued by the "export as property" checkbox in ShakeIt. 

If that would be available in the Binding dialog it would allow me to store variables as properties with a global scope without the need to learn of configure the whole plugin business.

Like so:

![image](https://user-images.githubusercontent.com/53898212/119385155-0a763e80-bcc6-11eb-893d-edd123bc0212.png)
