### ISSUE TITLE
Richard Burns Rally, RallySimFans RSF and SimHub and a support for dynamic car slots in RBR

### ISSUE THREAD

**Issue by mika-n** [SHWotever/SimHub#829]
Hi. Thanks for this great application. I use it with Richard Burns Rally (RBR). Like many of you who use SimHub with RBR know there are various different RBR online plugins/platforms. For example RBRTM Tournament (czech) and RallySimFans (RSF) online platforms. Now, my comment/question/suggestion here is related to SimHub support with RSF rbr installation, but also few improvements for RBRTM support in SimHub.

RBRTM and RSF rbr online platforms have the same cars and stages, but very different way of using those at RBR runtime. 

Traditionally RBR can see only 8 cars at a time out of those 100+ custom cars available. If you want the "9th car" or the car you need on the next online rally is not in those 8 slots, you have to close RBR, remove one of the cars and replace it with a car you need and then restart RBR. RBRTM rbr online plugin uses this traditional way of using those RBR car slots.

RallySimFans (RFS) (https://www.rallysimfans.hu) online plugin uses those cars dynamically, meaning that all 100+ cars are readily available right away at RBR runtime and there is no need to close and re-start RBR to drive another car "outside of those 8 slots". Now, this is a problem in SimHub RBR integration because SimHub recognizes only those cars which were in those slots at the time RBR process was restarted (SimHub rbr plugin cached the list of 8 cars at RBR launch time). To make RSF and dynamic car slots work with SimHub I have modded the SimHub RBR integration to make it support all those 100+ cars without requiring RBR restarts after choosing new cars (outside of those 8 cars).

Also, like you know RBR has custom stages both in classic and BTB formats. The SimHub RBR plugin recognized classic maps correctly, but did not see differences between BTB stages (all BTB stages were recognized by SimHub RBR plugin as trackID 41 Cote D'Arbroz. This was because of certain technical reasons how BTB stages work in RBR). Because SimHub treated all custom BTB stages as "the same" Cote D'Arbroz stage then it made the wonderful SimHub feature with stage records/delta times/split times/maps useless with BTB stages. Therefore I modded SimHub RBR integration to support BTB stages also.

Plus the modded plugin has few other small improvements (full real stage names for custom RBR stages instead of showing those as "track-xxx") and bug fixes (SimHub plugin didn't show anything in RBR replay mode with Default operating mode, this data reader bug is fixed in the modded SimHub reader).

Here are couple links explaining these issues and a download link to NGPCarMenu rbr plugin and to the modded SimHub rbr reader plugin.
https://github.com/mika-n/NGPCarMenu/issues/13
https://github.com/mika-n/NGPCarMenu/releases

Now, it is time to cut this long story short. The real question of this post is to ask is there any chances to get these changes as part of the official SimHub rbr datareader plugin? The modded version doesn't change/break "the old logic how SimHub used to work", but just adds these additional features and improvements. Where should I send a code patch/diff of these modded changes for someone officially maintaining SimHub RBR integration, so she/he can review and comment those? Thanks and keep up the good work.

**Comment by SHWotever** [comment]
hi ! I'm interrested indeed, I've looked at side to side compilations of my regular plugin and yours and i see clearly the differences, I see clearly  the GetTrackFullNameFromId which read from memory the track name as a fallback (I tried that but I did not achieved it :D) ,I see also the automatic ini files reload. 

If you have the code of GetTrackFullNameFromId, it's clearly the only method where going through the compilation/decomiation/recompilation (etc...) makes it a bit obscure, and I feel I can rewrite it a little to help future maintenability :
![image](https://user-images.githubusercontent.com/2207331/119131812-3aa9ad00-ba3a-11eb-894e-99ce470273ec.png)


By the way I see you changed the gamestateid I was using, I choose the values using "trial and error" but i'm pretty sure than as an rbr reverse engineering expert you know a much more than me the complete list :D
- Race = 1,
- PauseMenu = 2,
- RaceIntro = 10,
- EndOfRaceMenu = 9,


I attempted when I wrote it to cover some basics of the mods by reading the ini files, but they all works so differently it's clearly hard to support them all properly, at the time I wrote it most mods were indeed "launcher based" altering files before starting, that's why I did not bothered reloading the files automatically at change (which I usually do when I know it can change in most simhub features).

**Comment by mika-n** [comment]
Hi. Thanks for the reply. I will send you the whole code diff as "clear text" with comments, so it is easier to understand. 

The screenshot and the highlighted "GetFullNameStageName" indeed is a new function to read the "full real" stage name for custom tracks.
- The code part reading "TrackData StageName INI option" is for custom maps in classic map format
- The "weird looking" loop reading RBR process memory data is a logic to read BTB stage names from RBR (string format is WCHAR and the the buffer is dynamcially allocated in RBR, so we don't know in advance the size of the buffer. This is why it loops through it until wchar null-terminator is found). And the modded reader optimizes this in a way that this is done only once when a new stage is detected because in RBR it is not possible to change a car or stage while a stage is active (stage needs to be restarted in order to change a car or when jumping to another stage and the modded reader detects this).

Originally the rbr reader used those gameStateIDs you listed above. Only significant missing gameStateID missing was replay=8 state and I added this in the modded version because without this SimHub overlay showed nothing while RBR replay was playing (the Default rbr operating mode works both in racing and replay modes in RBR).

SimHub also seem to have a built-in concept of "IdleScreen vs RaceScreen vs PitstopScreen" and this way makes it easy to show a bit different version of overlays in racing and pitstop modes. I haven't fully investigated how SimHub uses this with RBR (where we don't have real pitstops), but maybe this could be used in RBR to differentiate between RBR racing and replays? Often racing may have less information shown on screen than replaying. Might be useful to make SimHub to support racing vs replay modes in RBR.

Anyway. I will send the modded version with full comments for you to review and rewrite whereever you need is necessary. It makes my life a lot easier in the future if some of these new features and support is part of the official SimHub rbr reader :-)

**Comment by SHWotever** [comment]
Hi ! It took me a little time to understand all the subtility of the RBR trackname, actually it's only available a short time after session entering (it clearly depends of the way to start it too, RBR_RX, ngp car menu etc ...), even if its not what I hoped I did the change to take it into account, if simhub is started in the middle of a race it will fall back the the default trackid based naming, it's not optimal but it's better than nothing.,

**Comment by mika-n** [comment]
@SHWotever Thank you very much and sorry for not commenting on this ticket earlier, I only now had time to fully test the new SimHub version (7.04.3b1) with these RBR improvements and fixes (BTB trackName and ID, replay support, real stage names etc).
Now this works great with the latest 7.04.3b1 version, so I and other RBR drivers no longer need to use the tweaked version of RBR reader plugin. Wonderful (makes my life easier).

About the comment you made above about RBR track names with BTB rbr_rx. Yes, it is a bit weird thing in RBR, so that's why the BTB track name needs to be read using the special string reader logic (the logic I suggested and you integrated into the latest version works with both the original rbr_rx plugin and with "online approved" BTB stages in RallySimFans RSF plugin). But fortunately the special string reading logic is now done only once when a new stage is started, so not a big deal.

Keep up the good work.
