### ISSUE TITLE
Simhub Wind Sim without motor shield

### ISSUE THREAD

**Issue by ObstacleTAKUYA** [SHWotever/SimHub#830]
Hello,
is there any way to make a wind sim without a motor shield?
For example. Simracingstudio uses an arduino NANO for controlling their wind sim.
Cheers!

**Comment by SHWotever** [comment]
Hi ! With pwm fans you can : https://github.com/SHWotever/SimHub/wiki/Arduino-Shake-It#pwm-fans

I think SRS uses some tip120 hidden which replaces the motor shield, but overall it's a power control circuit.

**Comment by ObstacleTAKUYA** [comment]
ah i see! 
So the 12v go to the TIP120 and then to the fan. GND to the arduino and PWM to pin 9 for example

**Comment by ObstacleTAKUYA** [comment]
other question. In the DOCS it says you can connect max 2 PWM fans, but selecting it allows me to add 4. Is this just an error in the docs?

**Comment by SHWotever** [comment]
Hi ! You are right, it's not two it's three, (take care not to mix  "pwm" and "pwm fans", it's not using the same frequency "pwm fans" has a max of 3 as it's the maximum supported by mega or leonardo)

**Comment by SHWotever** [comment]
I fixed it  :D

**Comment by ObstacleTAKUYA** [comment]
Alright :D 
Im currently working on an all in one controlbox that supports a tachometer, FlagMatrix, FlagLED and a wind sim. 
Thats why im asking this since i only want one cable going to the fan. 12v in goes to the box and such....

**Comment by ObstacleTAKUYA** [comment]
so by looking at the board of SRS, it looks like they are realy using a TIP120 with some diode.

**Comment by ObstacleTAKUYA** [comment]
![image](https://user-images.githubusercontent.com/54855101/119173215-3fd12100-ba67-11eb-8dd8-14bab22ac59b.png)

**Comment by SHWotever** [comment]
Yeah it's the typical tip120 wiring :
![image](https://user-images.githubusercontent.com/2207331/119173383-7dce4500-ba67-11eb-9888-91ed3e665072.png)

**Comment by ObstacleTAKUYA** [comment]
Geez, thats nice! 
YOU ARE GREAT!!!!

**Comment by ObstacleTAKUYA** [comment]
hmm. im kinda stuck again :(
the motor in the diagram is just a 2 pin motor. Fans have 3/4 pins. 
Is the speed only controlled via the motor voltage?

**Comment by SHWotever** [comment]
Actually three pins fans are DC fans with a tachometer pin which can be ignored (you will find the pinout easily on Google) , 4 pins fans are pwm fans , in this case you don't need electronic and you can drive them straight from the Arduino as shown here : https://github.com/SHWotever/SimHub/wiki/Arduino-Shake-It#pwm-fans

**Comment by ObstacleTAKUYA** [comment]
can i directly plug the power in of the fan to a 5v out on the arduino?

**Comment by SHWotever** [comment]
No, you need a proper 12v power supply (assuming it's a 12v computer fan)

**Comment by ObstacleTAKUYA** [comment]
hm. it would just pin slower i think

**Comment by SHWotever** [comment]
Most 3pins fans are close to the lowest speed at 5v that means it will run slowly and simhub control would simply stop or start it without much speed control, at best.

Feel free to test it, but I can't ensure you it will be of any interest at 5v ;)

Concerning the 4 pins fans most of them won't work at all at 5v they are intended to work at 12v with the pwm pin controlling the speed.
