### ISSUE TITLE
Cloud map recordings Dirt Rally 1 &2 in new (high precision) filename format Zipped?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#831]
Hi, can I please have the existing Cloud Map Recordings for Dirt Rally 1 & 2 in the new high precision filename format in a zip file?

I have a lot of work to do rewriting php code and SimHub javascript code and renaming all sorts of files to accomodate the new high precision track codes.

So if I could have the existing cloud map recordings allready in the new format, that would save me al lot of work and time.

I know that DR1 is not complete but then I will know which ones are still missing and perhaps do a new 'efficient' recording run for those.

**Comment by Shaftoe62** [comment]
P.S. Did you see the Excel file (AllDirtRallyTrackCodesAndTrackLengths.xlsx) with all DR1&2 track codes I send you in issue #813?

**Comment by Shaftoe62** [comment]
Also, here are the total amounts of all tracks of both games. For verification purposes:

Dirt Rally unique track lengths/codes

Dirt Rally
Rally: 71 (72 tracks but minus 1 because of the 'Gordolon conundrum')
Hill Climb: 8 (12 track variants but only 8 unique track lenghts/codes)
RallyCross: 8
Total unique track lengths/codes: 87

Dirt Rally 2.0
Rally: 155 (156 tracks but minus 1 because of the 'Gordolon conundrum')
RallyCross: 13
Free Roam: 1
Total unique track lengths/codes: 169

**Comment by SHWotever** [comment]
Hi ! Sorry work has been heavy this week and  I've not done the renaming yet , I only plan to get it ready for final release, it's not required for the beta stage. As soon as it's done I can make you a zip yes

**Comment by SHWotever** [comment]
Yes I've seen the zip indeed, thanks a lot

I've seen some small differences in the length which makes me wonder if there is no trap somewhere

Concerning the freeroam there is no map, as there is no lap, the Rx are a bit less accurate than others since there is a joker path with no information to identify it, but it tends to average on the main path

**Comment by Shaftoe62** [comment]
Ok, great!

And I still have a lot of other work/preparations to do so I don't need them right now. I'll test my code with some example files I'll rename manually.

And just to make sure: I assume the new naming convention will be simply like: 11684.169921875.shtl ?

As for the small length differences you have seen: Can you give me one (or more) examples? I'll check them to see if I perhaps made mistakes or if there is some sort of rounding taking place somewhere.

I took the lengths from the SimHub property 'TrackLength'. 

And I'm running SimHub on a Win10 PC with European (Dutch) numbering formats (#.##0,00)

Best to check this pronto so we (you) know the cause.

I've been thinking about this before and a possible way to eliminate any formatting/rounding issues would be to make  the lengths in ångström (length * Math.pow(10, 10)) or picometer (length * Math.pow(10, 12))

**Comment by Shaftoe62** [comment]
As for the Rallcross maps, I'm considering to make (square) custom images in Adobe Illustrator based on the map recordings, satellite images and general track information.

In Rallycross the track bounds and 'obstacles' are of paramount importance. The 'racing line' is useful but mostly only when you lead the race or are somewhere in "nomansland".

I'm still thinking about the final format but it will be a bit of a merge of these images:

![image](https://user-images.githubusercontent.com/53898212/119217610-9bd58d00-badb-11eb-86e3-b99d5ff7deb1.png)

![image](https://user-images.githubusercontent.com/53898212/119217706-333ae000-badc-11eb-96a0-df9cfda25cfd.png)

The idea is to superimpose the SimHub static map (with a transparent racing line) on top of the image so track boundaries, obstacles and the joker lap are clearly visible.

One point of concern I had in this was: Do the rallycross map recordings have enough margin outside the racing line to show cars takingthe joker lap if it lies on the outside of the main track?

As far as I could see in this one example this is not the case. Shall I make a separate issue for that?

**Comment by SHWotever** [comment]
I close this one, I'm sorry I won't deliver full extracts :
https://github.com/SHWotever/SimHub/issues/836#issuecomment-846666522

**Comment by Shaftoe62** [comment]
Never mind. I understand. This is an open platform and you don't want to create a precedent.

I'm doing a complete rewrite of my code now anyway and that includes a map data optimization algorithm of my own. And it uses the cloud maps if available and the local map recordings as fallback. That works for my purposes and it will automatically use valid cloud maps as soon as they become locally available.
