### ISSUE TITLE
Irregularities Cloudmap file naming (DR1-RX)

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#834]
I found some irregularities in the Exel file I send you previously and the current filenaming of the cloud maps.

It is a kind of rounding issue as I suspected.

I assumed the high precision ID would be the exact track length in maximum precision.

And that the added precision of the filenames would be using this track length.

In most cases this is correct. With the exeption of (most of) the RX tracks of DR1.

There, for some reason, the reported track length and the code used in the cloudmap filenames are different.

For example:

Lydden Hill - Clubman Circuit
reported track lenght: 989.75518798828125
code used in filename: 989.755187988281

I'll attach a new version of the Excel file with all these instances highlighted.

Looking at the numbers this must be a rounding issue somewhere.

[AllDirtRallyTrackCodesAndTrackLengths.xlsx](https://github.com/SHWotever/SimHub/files/6527643/AllDirtRallyTrackCodesAndTrackLengths.xlsx)

**Comment by Shaftoe62** [comment]
I have to add: I dont have all the DR1 cloud maps so I can't check it thoroughly for all maps.

If you can send me all available DR1 cloud maps (in their current naming convention) zipped I can do some more checks on it.

**Comment by SHWotever** [comment]
Hi ! I will take a look, that said it only matters to be consistent between recording and requesting on the server so it's not really an issue as long as it matches both actions (submitting the map and requesting it on the server)

**Comment by Shaftoe62** [comment]
I understand, but you mentioned small differences and maybe a 'trap' somewhere. I know from experience that small issues like this can cause big problems down the road. So I thought it best to report it. I's probably quite easy to fix if you can find it :-)

**Comment by SHWotever** [comment]
Hi ! I double checked if there were any issues with this lenght but nothing I could see, the small diffrence comes from conversion from float (as given by codemasters) and double (as used by simhub internally for all standard length processing) , rounding to avoid it would not bring anything interrresting because using the full precision allows on some games to detect subtil track version changes which is a good thing in my opinion.
