### ISSUE TITLE
i deleted the simhub but it still runs without it

### ISSUE THREAD

**Issue by STARZX64** [SHWotever/SimHub#835]
so got rid of simhub cause i didn't want to use it anymore but it still running as the Led on my wheel still light i dont know what happening

**Comment by SHWotever** [comment]
Hi ! Could you check in the task manager that simhubwpf is not present, if it's the case it's likely to be another application driving your LEDs.
Simhub does not have any separate component to drive the LEDs outside of the main application.

Nicolas
