### ISSUE TITLE
Is there a way to make DashStudio play a sound?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#837]
I mean, can I program a Binding to play a sound?

Now I use visual cues for, for instance when I'm 1 minute away from my alltime best finishing time.

I'd like to use sounds for some things as well.

I've been looking at 'controls and events' but I can't really find anything for that.

**Comment by Romainrob** [comment]
Hi.
Yes it's possible using the triggeraction(actionName) function.

Here is an example:

if( isincreasing(1, blink(secondsbeeps, 500, 1))
,triggeraction( 'AudioControlPlugin.Play_beep-07') ,'')

Put your sound files here; C:\Program Files (x86)\SimHub\Sounds
I believe you have to use mp3 files.

**Comment by Shaftoe62** [comment]
Fantastic!! Works like a charm!!

Thanks a lot.

**Comment by Romainrob** [comment]
You're welcome ;)
