### ISSUE TITLE
Can I check if a file (image) exists in Dash Studio?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#838]
Can I check if a file (image) exists in Dash Studio?

If so, how? (in javascript)

**Comment by Shaftoe62** [comment]
Anybody?

**Comment by SHWotever** [comment]
Hello ! Sorry heavy weeks ;) No there is no way currently ;)

**Comment by Shaftoe62** [comment]
No problem, I'll work around it. 

When is the next alfa update scheduled for release?

**Comment by SHWotever** [comment]
Hard to tell, it's almost ready, but work being heavy lately I have a hard time to keep my usual frequency for simhub. I hope today or tomorrow for a last beta, and the final release next weekend.

**Comment by Shaftoe62** [comment]
Ok thanks. Take it easy.
