### ISSUE TITLE
Setting panel in Custom serial devices do not save config

### ISSUE THREAD

**Issue by Wanegain** [SHWotever/SimHub#839]
Hello,

I am working in Custom serial devices in order to drive my motion platform with SimHub !

For that, I need to have some sliders in the setting panel.
Something like that :
![simhub](https://user-images.githubusercontent.com/11090204/120294694-be7b5900-c2c6-11eb-94b4-294ab59a19b2.png)

But this morning I only have this :
![simhub_issue](https://user-images.githubusercontent.com/11090204/120294924-f6829c00-c2c6-11eb-8a77-cfa77937b8c2.png)

I tried to export settings but if I take a look in the exported files, I cannot see all of my sliders, I can only see title of groups I made (ROLL, PITCH, HEAVE, etc...).

Is there something I am missing to save my work ?

**Comment by SHWotever** [comment]
Hi ! Thnaks for the feedback, indeed there was a bug when using groups, the content was not saved, it will be fixed for the enxt version,

Nicolas

**Comment by Wanegain** [comment]
Génial !

It will be very useful for my motions platform :-)

**Comment by Wanegain** [comment]
As a workaround, could it be possible to import settings file with sliders and checkbox inside a group ? If yes, can you please give me the structure of a group when adding items ?

**Comment by bizibiz** [comment]
+1

**Comment by SHWotever** [comment]
Fix released in 7.4.0
