### ISSUE TITLE
Spedometer/Tachometer

### ISSUE THREAD

**Issue by ObstacleTAKUYA** [SHWotever/SimHub#840]
Hello,
i have a question regarding the Tachometer wiring.
In the SPEEDOMETER wiki, it says if it runs on 5V it can be plugged directly into the arduino, but in the Tachometer section is doesnt say anything about 5V. 
Now my Question: If my Tachometer WOULD run on 5V, do i need the TIP120 circuit?

**Comment by SHWotever** [comment]
Hi ! Most of them are bound to 12v car wiring, feel free to test without, some of them works with only 5v (like the BMW E36 cluster), 
If you are not sure, the best is to refer to the tachometer manual, usually aftermarket ones are 12v only which is a standard, and some clusters might accept wider signal range.

**Comment by ObstacleTAKUYA** [comment]
alrighty. Thanks:)

**Comment by ObstacleTAKUYA** [comment]
hey again!
do you know where i can find a 5v speedometer? i couldnt find a single one
