### ISSUE TITLE
périphérique leds rgb ou rgb matrix qui arrêt de fonctionner et refonctionne quelque seconde après dans les jeux  

### ISSUE THREAD

**Issue by erkan377** [SHWotever/SimHub#841]
bonjours,
j'ai plusieurs problem j'ai des fois mes leds qui arrêt de fonctionner correctement et je ne trouve pas de solution 
merci

**Comment by SHWotever** [comment]
Bonjour, auriez vous les logs que je puisse voir en détail ? 

Sinon quelques pistes classiques :
Usb hubs : ils causent souvent des problèmes de puissance, et pour les LEDs c'est d'autant plus un problème.

Luminosité : si il y a des problèmes de courant réduire la luminosité va aider.

Soudures : des mauvaises soudures vont causer des problèmes de stabilité, souvent quand il y a des vibrations, ce qui le cas quand on roule bien souvent.

Emi/parasites : un câble USB de mauvaise qualité peux causer des problèmes, les volants génèrent aussi des parasites, si le câble est proche du volant ou autre périphérique qui génère des perturbations il faut essayer de faire passer le câble ailleurs.

**Comment by erkan377** [comment]
je vous envoie tous les logs ? 
je n'ai pas de problem de soudure ou autre mais j'ai un hub usb avec une alimentation adapter pour

**Comment by erkan377** [comment]
j'ai beaucoup de lag avec l'application simhub beaucoup de ralentissement et même des fois des crash ca prend des fois beaucoup de temps a répondre aussi voici ma config 
https://www.driverscloud.com/fr/configuration/69732505-1/resume
ps: simhub et sur un disque dur NVME*

**Comment by erkan377** [comment]
https://user-images.githubusercontent.com/85454251/120936022-fb4fb180-c705-11eb-80d3-28b7cb1fa44e.mov

**Comment by erkan377** [comment]
j'ai encore un autre problem … pour le réglage sortie pour les shakelt moteurs quelle et la valeurs que je dois utiliser car quand j'utilise le pourcentage pour régler les moteurs ils ne sont pas correcte 
![image](https://user-images.githubusercontent.com/85454251/120936134-8af56000-c706-11eb-9a9d-e468888d2eb1.png)
![image](https://user-images.githubusercontent.com/85454251/120936137-947ec800-c706-11eb-8c2f-cee3a6c5dbc6.png)

**Comment by SHWotever** [comment]
Oui tous les logs dans un fichier zip ça ira,

Pour les hubs, même si alimenté c'est vraiment une piste a éliminer absolument, surtout que la matrice est très consommatrice. 

Le "volume" final pour les moteurs depends de plusieurs parametres cumulés, tout est expliqué ici : https://github.com/SHWotever/SimHub/wiki/ShakeIt-V3-Effects-configuration#gain-control.

**Comment by erkan377** [comment]
[SimHub.log](https://github.com/SHWotever/SimHub/files/6604741/SimHub.log)

**Comment by erkan377** [comment]
pour le log ca vous suffit ?
et merci je vais regarder (;

**Comment by erkan377** [comment]
je vient de regarder sur le lien mais rien ne répond a mon problem (output tuning)

**Comment by erkan377** [comment]
ah bah c'est bon je sais pas comment mais j'ai ressui a regle mon problem pour les vibreurs (;

**Comment by SHWotever** [comment]
J'ai décortiqué les logs on voit qu'effectivement ça coince sur une des Arduinos, et j'ai l'impression que ça part en cascade. Est ce que vous pouvez essayer de les débrancher un par un pour localiser si il y a un fautif en particulier?

**Comment by erkan377** [comment]
j'avais un arduino qui a crame je crois en tout cas il avais juste la leds rouge qui s'allumer ( je l'utiliser pour mes 3 vibreurs contrôler avec un arduino pro micro avec des mosfet et un transformateur 12V) ca mets arriver 3 fois la je vient de le changer avec un arduino mega et il a l'air de fonctionner pour l'instant 
ps: les arduino pro micro aliexpress lol

**Comment by SHWotever** [comment]
Normalement AliExpress ou autre ça n'a pas trop d'impact, j'ai ai de nombreux clones de multiples revendeurs (AliExpress, Amazon, eBay.. ) elles se valent toutes plus ou moins. 

Concernant les mofsets il t'a un protection pour les retours de courants ? (Diode) sur les moteurs c'est un problème typique et il y a de quoi tuer l'arduino sans ça

**Comment by erkan377** [comment]
https://fr.aliexpress.com/item/32962975976.html?spm=a2g0s.9042311.0.0.27426c37aShjwd
voila ce que j'avais acheter

**Comment by erkan377** [comment]
du coup j'ai fait une partie sur ac avec les vibreurs ect... et je n'ai plus eu le problem peut être que le problem de la cartes pour les vibreurs avais un problem.
et du coup es ce que mon Arduino et protéger quand j'utilise mes vibreurs ?

**Comment by erkan377** [comment]
j'ai encore plein de question et d'autre problem que j'ai avec des valant que j'ai réaliser ( niveaux programme simhub ) je vous dirais ca demain soir ou un autre jours (; je vous remercie pour votre aider

**Comment by erkan377** [comment]
bonjours d'accord je vais voir et essayer car aujourd'hui ca me la encore fait ...

**Comment by erkan377** [comment]
[SimHub.log](https://github.com/SHWotever/SimHub/files/6618355/SimHub.log)

**Comment by erkan377** [comment]
voila si jamais vous trouver quelque chose
