### ISSUE TITLE
How i can add library UTFT for SimHub Dash

### ISSUE THREAD

**Issue by jenson1980** [SHWotever/SimHub#842]
Hello all! I used arduino uno and this TFT screen (https://aliexpress.ru/item/32710812577.html?spm=a2g0s.9042311.0.0.264d33edOOVBzd)
How i can use this screen with SimHub?

Sorry for bad english

**Comment by SHWotever** [comment]
Hi ! I tried such screens in the past but these screens are overall too slow for the need so they are not supported. The might be a "come back" of such size screens but combined with an esp32 which is wayyyy faster, future will tell ;)
