### ISSUE TITLE
Game Reader - iRacing - Opponents speed null

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#844]
Hi,
The opponents speed value is always null :(.
![image](https://user-images.githubusercontent.com/50543913/121702940-982d9880-cad2-11eb-9334-3a738bfccb7b.png)
Is this something you could fix with a little plumbing, please?
Or is it not available from the game?
Bonne fin de journée.

**Comment by SHWotever** [comment]
Hello !
I took a look the data was not available, but with a bit of math i've been able to extract a rough estimation. It will be available for the next release ;)

**Comment by Romainrob** [comment]
Awesome! :)
C'est bloqué en kmh ou c'est comme speed local?

**Comment by Romainrob** [comment]
I should have checked before asking. It seems to always be kph.
That's good for me.
Thank you for the addition and todays release! :)
