### ISSUE TITLE
Vocore display bug

### ISSUE THREAD

**Issue by XIANG-z25** [SHWotever/SimHub#845]
When I first started using the vocore screen, everything was OK. But then the content on the screen moved up and looked strange. I've tried to replace different versions of simhub, reload the driver, and restart the computer, but it didn't work. Is this a bug?

![20210611_134532](https://user-images.githubusercontent.com/85831771/121808216-0799b880-cc8a-11eb-807a-0eb37e8877b8.jpg)
![mmexport1623587225595](https://user-images.githubusercontent.com/85831771/121808227-12544d80-cc8a-11eb-9cc0-5b9019a6502d.jpg)
![mmexport1623587231464](https://user-images.githubusercontent.com/85831771/121808230-13857a80-cc8a-11eb-9fe1-1df9e1fa75ba.jpg)
![mmexport1623587235966](https://user-images.githubusercontent.com/85831771/121808232-14b6a780-cc8a-11eb-90d6-c0429d082b7b.jpg)

**Comment by SHWotever** [comment]
Hi ! Usually when this happens a simple hard reboot (unplugging/plugging again) the screen is enough :
https://github.com/SHWotever/SimHub/wiki/Dashstudio---USB-Displays#vocore-specific

I see that your screen is encased inside a wheel, maybe with a custom cable ? Could you try to plug the screen directly with a dedicated cable ?

**Comment by XIANG-z25** [comment]
Yes, I use a custom-made USB cable with shield, and the connection is reliable. I will try to replace the USB cable. Thank you for your reply #

**Comment by visitante147** [comment]
Hello, I need your help, I have the same problem, how have you solved it?

**Comment by visitante147** [comment]
Hello @XIANG-z25 , I need your help, I have the same problem, how have you solved it?

**Comment by XIANG-z25** [comment]
> Hello @XIANG-z25 , I need your help, I have the same problem, how have you solved it?

Hello, I have solved it. I sent the screen back to the seller. The seller solved it after writing the firmware again, but I don't know how to solve it. Maybe you can send an email to VoCore to ask how to solve it.^^
