### ISSUE TITLE
Is Simhub 7.4.0 alfa now? Or not?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#850]
My Simhub 7.3.13 says no:

![image](https://user-images.githubusercontent.com/53898212/122122016-91818700-ce2c-11eb-987c-94fef09ba2b8.png)

But on https://www.simhubdash.com/download-2/ it say yes?

I got some message about my IP and anti-crawling too?

**Comment by SHWotever** [comment]
Hi ! I often give a few days before triggering the new version notification, it's intentionnal. Even more when it's a huge release like this one.
Concerning the antricrawling it's a security plugin, unfortuntely being alone to moderate the forum and website, I have to rely on some automated systems, I had the offortunate experience to have a bunch of spam on the forum, and contact form which made my hosting block any outcoming emails. It's unfortunate to have to rely on these systems but it's the nowadays reality :(

**Comment by Shaftoe62** [comment]
Ah, ok. No worries. I was just wondering if these two issues might be related.

And good to know the delay in the notification is intentional. I just wait for that in case some unforseen bugs turn up. :-)
