### ISSUE TITLE
Transparency Hex issue is not a formula error

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#851]
I wrote a quick testing function to test this fenomenon:

function opacity_test () {
	var base_color = 'ff0000'
	var rpm_percent = $prop('CarSettings_CurrentDisplayedRPMPercent')
	var alfa = clamp((Math.round(rpm_percent * 2.55)),0,255)
	return '#' + alfa.toString(16) + base_color
	}

function clamp(value, min, max) {
	return Math.min(Math.max(value, min), max);
	}

The return values look ok to me but I still get the same error:

&nbsp; | ERROR | An error occured while executing binding on RectangleItem1 return opacity_test() System.FormatException: Token is not valid. &nbsp;&nbsp;at MS.Internal.Parsers.ParseColor(String color, IFormatProvider formatProvider, ITypeDescriptorContext context) &nbsp;&nbsp;at System.Windows.Media.ColorConverter.ConvertFromString(String value) &nbsp;&nbsp;at SimHub.Plugins.OutputPlugins.GraphicalDash.EditorModel.Applybindings(IBindable item, String objectName, DashboardBindingData binding, IFormulaEngine GraphicalDashEngine), formula will not be evaluated for 30s
-- | -- | --

**Comment by SHWotever** [comment]
Hi ! If I test your formula as is I got a 7 digit result : 
![image](https://user-images.githubusercontent.com/2207331/122979994-7668c700-d398-11eb-888f-c4c793f4e029.png)

`
#0ff0000
`

It has to be either 6 or 8 (#RRGGBB or #AARRGGBB)
