### ISSUE TITLE
Uploading WS2812B Software to Pro Micro

### ISSUE THREAD

**Issue by DarkPand0r** [SHWotever/SimHub#854]
I've been trying to upload the software for the WS2812B RGB Matrix to an Arduino Pro Micro on the latest version of Simhub (7.4.0) however everytime I try it comes up with an error "Compiling Failed". 

Have tested on previous versions of simhub which worked perfectly.

**Comment by damiank388** [comment]
Doesn't work Uploading to NANO either on 7.4.0. Log displayed.

In file included from C:\Program Files (x86)\SimHub\_Addons\Arduino\DisplayClientV2\DisplayClientV2.ino:290:0:
C:\Users\damia\AppData\Local\Temp\SimHub-d27abfeb-5b41-43a4-8a1e-08464de1ea30\sketch\SHRGBMatrixNeoPixelFastLed.h:18:7: error: expected ';' at end of member declaration
  bool reverseZigzag
       ^
Using library EEPROM at version 2.0 in folder: C:\Program+Files+(x86)\SimHub\_Addons\Arduino\ArduinoIDE\arduino-1.6.13\hardware\arduino\avr\libraries\EEPROM 
Using library SPI at version 1.0 in folder: C:\Program+Files+(x86)\SimHub\_Addons\Arduino\ArduinoIDE\arduino-1.6.13\hardware\arduino\avr\libraries\SPI 
Using library Wire at version 1.0 in folder: C:\Program+Files+(x86)\SimHub\_Addons\Arduino\ArduinoIDE\arduino-1.6.13\hardware\arduino\avr\libraries\Wire 
Using library Adafruit_GFX at version 1.1.5 in folder: C:\Program+Files+(x86)\SimHub\_Addons\Arduino\ArduinoIDE\arduino-1.6.13\libraries\Adafruit_GFX 
Using library FastLED at version 3.3.2 in folder: C:\Program+Files+(x86)\SimHub\_Addons\Arduino\ArduinoIDE\arduino-1.6.13\libraries\FastLED 
exit status 1

**Comment by SHWotever** [comment]
Hi ! Thanks the feedback i'm looking right now, indeed there is a compilation error, it will be fixed for the next release.

Nicolas
