### ISSUE TITLE
LEDs  When formula is TRUE does not work with  Test data editor 

### ISSUE THREAD

**Issue by damiank388** [SHWotever/SimHub#855]
LED

Custom flags/spotter/pit limiter/pit animations on ''When formula is TRUE'', for example [Flag_Green]. Do not work with ''Open Test data editor''.

It works in the game.

**Comment by SHWotever** [comment]
hi ! Indeed the test data editor only allows to drive built it effects, everything using a custom formula can only use real game data (or a replay) but won't be affected by the test data editor.

**Comment by damiank388** [comment]
So there is no quick fix to it and it wont ever work? Thanks for the reply.

**Comment by SHWotever** [comment]
Hi ! No unfortunately it can't be changed indeed.
