### ISSUE TITLE
Circumvent Echo Show timeout/screensaver

### ISSUE THREAD

**Issue by Pieparker** [SHWotever/SimHub#857]
Hey Nicolas, all,

Wondered if anybody had used the mobile access to show their dashboard on an Echo Show device?

If so: have you, or can you, prevent the dash from returning to the overview/home screen after 5 minutes? There's absolutely zero way to do this via any settings on the device itself.

I did some reading and I saw that you can apparently embed and loop a 0px video to get around this. If I can find the link again, I'll share it here.

I do see NoSleep in the program files however this doesn't prevent the device from sleeping (I tested the [NoSleep Test Page](https://richtr.github.io/NoSleep.js/example/) to be sure).

**Comment by SHWotever** [comment]
Hi ! I think echo show overrides any attempt to prevent sleep like the nosleep technic, I'm not sure if the settings allows to disable totally the sleep behaviour but i fear that it's the only solution : https://www.amazonforum.com/s/question/0D54P00006zSsAESA0/why-does-my-echo-show-keep-going-to-sleep-mode

**Comment by Pieparker** [comment]
That was my fear... darnit. Thanks for your response!
