### ISSUE TITLE
TM 2020 Support?

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#860]
Hi,
I think I know the answer but I'll ask anyway.
Any chance SimHub could support the lastest Trackmania game?

**Comment by SHWotever** [comment]
Hello ! Unfortunately the telemetry shared memory is available but almost dead (it only gives the current track name/id) 

https://forums.ubisoft.com/showthread.php/2244408-Maniaplanet-Telemetry-is-not-fully-functional
https://www.reddit.com/r/TrackMania/comments/i2y07e/trackmania_2020_telemetry_interface/

Without this it's not possible to support it yet :(

**Comment by Romainrob** [comment]
Hi,
Thanks for your answer.
I remember reading about this on release. I hoped they had fixed it by now or implemented a new solution.
I can't find any recent info about it. Someday hopefully.
Bon week-end!

**Comment by Romainrob** [comment]
Hi,
I found this overlay: https://github.com/codecat/tm-dashboard
Based on this api: https://openplanet.nl/

It does work with TM 2020.
The overlay has gear, speed, wheels angle and slip and rpm maybe, but it could be based on speed.
Idk how much more could be available from the game.

Hopefully this is useful info to you. I thought I'd share.
Bonne soirée.

**Comment by SHWotever** [comment]
Hello ! J'ai jeté un coup d'oeil mais pour acceder aux données utiles il y a pas mal de lecture en mémoire directe (à la manière de cheat engine) malheureusement ce genre de technologies sont a réserver aux jeux qui ne sont plus mis à jour car cela peux ètre cassé à la moindre mise à jour. Je préfère ne pas me lancer dans cette aventure et attentre que nadeo/ubisoft répare la télémétrie (qui existe mais n'est pas fonctionnelle pour l'instant)

**Comment by Romainrob** [comment]
Ok, je comprends, surtout qu'ils ne sont pas près de stopper les maj sur celui là.
Merci d'avoir regardé.
Bonne fin de soirée.
