### ISSUE TITLE
VoCore - Black screen after PC waking up from sleep

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#861]
Hi,
After exiting sleep mode, My Vocore sometimes (most of the times but not always) stays black.
If I disable, re enable it in the DS/VOCORE screen, it comes back to life.
I suspect it stays dimmed from the going to sleep phase. Just a guess.
As I can see in the log it's loading the dash on wake up.

[SimHub VOCORENOTWAKINGUP.log](https://github.com/SHWotever/SimHub/files/6755881/SimHub.VOCORENOTWAKINGUP.log)

Did you get any similar reports?
Is there a way I could disable the auto dimming as a test?
Bonne soirée.

**Comment by SHWotever** [comment]
Hello !

I took a look and I spotted that my "sleeping" process was maybe a bit too soft to handle all cases  (it was only dimming the screen and closing the browser) . I replaced it by a more aggressive full usb screen disconnect (just like when unchecking "enabled"), with an additionnal 5s delay when waking up before reconnecting to the screen. This should make it way more reliable.

**Comment by Romainrob** [comment]
Hi,
Nice! I'll let you know if it solves the issue on my end.
Thank you!
