### ISSUE TITLE
Thrustmaster Manager doesn't recognize  TS-PC Racer 488 Challenge Edition - Thrustmaster_Advanced_Mode_Racer

### ISSUE THREAD

**Issue by JonathanKang** [SHWotever/SimHub#862]
I'm using Thrustmaster TS-PC Racer 488 Challenge Edition. In the Thrustmaster driver page, advanced mode is set to enable all 25 programmable keys.

In simhub, under Thrustmaster manager, it says `No thrustmaster wheel found`.

**Comment by SHWotever** [comment]
Hi !

Indeed this one is not supported yet, could you grab some registry keys so I can support it ? 
The needed keys are shown in this previous ticket : 
https://github.com/SHWotever/SimHub/issues/731

**Comment by JonathanKang** [comment]
Here it is. My system language is set as Chinese, but it shouldn't bother that much.

![SimHub1](https://user-images.githubusercontent.com/5607743/124380410-10ad0100-dcef-11eb-95dc-164ed4434590.png)

**Comment by SHWotever** [comment]
Thanks ! It's added for the next release !

**Comment by JonathanKang** [comment]
Thank you for the quick fix. Looking forward to next release!
