### ISSUE TITLE
Raceroom - mode classement - meilleur tour

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#863]
Bonjour
Dans Raceromm en mode classement, 
si on améliore son meilleur temps dans le 1er tour simhub ne l'enregistre pas.
Je pense que simhub ne détecte pas que le 1er tour est en mode lancé et qu'il doit donc être pris en compte.
je l'ai reproduis plusieurs fois sur le nordschleife en porsche cup enduro et porsche cup allemagne

**Comment by SHWotever** [comment]
Hello ! En effet celui là était subtil, pas de changement de numéro de tour ou de reset de temps (car il n'avait pas comméncé) ce qui faisait que le statut invalide de la "prise d'élan" n'était pas réinitialisé  j'ai pu contourner le problème en prenant en compte le démarrage du temps du tour.
