### ISSUE TITLE
Problema leds rgb ws2812

### ISSUE THREAD

**Issue by juanipede** [SHWotever/SimHub#864]
Buenas a todos , tengo un problema , me he creado un display de rpm con 2 tiras de 8 leds rgb (en total 16 leds) . Ya conecte todo como explican en varios tutoriales en youtube , pero siempre la segunda tira de leds tiene poco brillo y colores distintos a la primera , incluso si subo el brillo mas del 5% empiezan a fallar todos los leds o cambiarse de color . Uso un Arduino Pro Micro , ya intente cambiarle los leds y todos me hacen lo mismo , incluso me arme otro display igual con todos los componentes nuevos y me hace lo mismo . Saben que podria ser ? muchas gracias

![WhatsApp Image 2021-07-07 at 9 18 06 AM (1)](https://user-images.githubusercontent.com/87074050/124758016-8e962580-df04-11eb-9b23-3b2af5b45a5f.jpeg)

**Comment by SHWotever** [comment]
Hi ! I'm sorry i don't speak spanish. If you have issues with the last 8 leds it's often a soldering issue https://github.com/SHWotever/SimHub/wiki/Arduino--Setup#soldering , could you double check that they are sturdy and that it's not a "cold join", also make sure not to use an usb hub or a bad usb cable : it could be a lack of power, removing usb hubs and using a good cable can solve lot of issues.

Nicolas

**Comment by juanipede** [comment]
> Hola ! Lo siento, no hablo español. Si tiene problemas con los últimos 8 leds, a menudo es un problema de soldadura https://github.com/SHWotever/SimHub/wiki/Arduino--Setup#soldering , ¿podría verificar que sean resistentes y que no sea un "resfriado únase ", asegúrese también de no usar un concentrador USB o un cable USB defectuoso: podría ser una falta de energía, quitar los concentradores USB y usar un buen cable puede resolver muchos problemas.
> 
> Nicolás

Hello, my problem is in the second strip of LEDs (the one that does not go directly to the Arduino), it has less brightness than the one that goes directly to the Arduino, and the colors are less distinguished. Even if I raise the brightness more than 5%, the LEDs of the 2 strips start to fail and change color. I'm going to test the USB cable and check the solder. Any other solution? Thank you so much

**Comment by SHWotever** [comment]
Hi ! No  other solutions, if it's only half of the leds it's clearly a hardware issue, 95% of the time it's a soldering or a power issue ;)
