### ISSUE TITLE
Lags in ACC for alone session

### ISSUE THREAD

**Issue by andkirby** [SHWotever/SimHub#867]
STR:
1. Start a dash or layout on main display (over the game, "always on top" is ON).
2. Start ACC, start a hot lap session.
3. Get on track

Actual: a dash is lagging heavily.
Expected: normal working.

Here are two videos with strange behaviour.
1. Captured a small piece of display, unexpectedly, it was working normally.
https://youtu.be/66t4NnQBczc
2. This one has a whole display lagging heavily.
https://youtu.be/5HvxA2S9qE8

It does have lags in KartKraft and iRacing. But haven't figured out a reason. In Assetto Corsa Competizione it is obvious: as many cars you have in sessions as less latency you will have (with 10 cars it will be significantly improved but still noticeable).
Played with different settings of FPS (Slow, Fast, etc.) the same result on two different PC.

**Comment by SHWotever** [comment]
Hi ! Could you check the system load (cpu and gpu) and join the simhub log files ? Indeed there is something strange. Ususaly when there are load issues it will sow down quite consistantly. Could you also check that you don't have any 3rd party plugins and try to disable them ? I know that some of them causes isssues.

**Comment by andkirby** [comment]
Hi @SHWotever

Thank you for your response.

> Could you check the system load (cpu and gpu)
I'm not sure whether that's about resources. I have two PCs: 
1. Asus ROG gr8 II with GTX 1060 3GB, i7 CPU (not so weak in CPU, but outdated)
2. Alienware R10 with RTX 3080 10GB, AMD Ryzen™ 7 and corresponding hardware.
The last one is quite new, I haven't had a chance to install too much software on it. And as you understand, it's quite powerful. I have ACC with EPIC graphic preset with ~90 FPS but use HIGH.

> join the simhub log files
Ok, I'll attach it. Shall use maybe some debug mode?

> Could you also check that you don't have any 3rd party plugins and try to disable them ?
If you talk about SimHub plugins, I don't have them. I have my own, quite small one, but lags appeared far from the moment when I started playing with it.

The strangest thing is as I load the game with more cars as it constantly improve FPS in dash panel :)

**Comment by SHWotever** [comment]
Hi ! Could you check that you have vsync enabled, even if you have a super robust setup in case of not capped FPS the game won't leave any GPU room for Simhub, i feel like it's what is happenning here : https://github.com/SHWotever/SimHub/wiki/Dash-Studio-Overlays#performances

Concerning the logs you can put them in a zip file and post it here, they are stored here : c:\Program Files (x86)\SimHub\Logs

**Comment by andkirby** [comment]
@SHWotever thanks for the link. I'll test it.
Yeah, will add logs after tests.

> even if you have a super robust setup in case of not capped FPS the game won't leave any GPU room for Simhub

But it works in the opposite way. =) More load — better work :)

Ok, will get back to you with logs.
I'll test with the lowest settings. I'm pretty sure, if I'll be alone on a track, it will have lags.
Also, I'll try using HTML.

**Comment by SHWotever** [comment]
Actually I think that the more opponents you have the more CPU computation you have it will slow down enough to get some room on the gpu, it's counter intuitive :D

**Comment by andkirby** [comment]
HI @SHWotever 

It's been a while :)
I finally got back to my wheel.

Here is a log file [SimHub.log](https://github.com/SHWotever/SimHub/files/6924347/SimHub.log).
Contains only a single test in ACC

**Comment by andkirby** [comment]
@SHWotever 
Using HTML solved an issue.

Logs from the previous comment **without** using HTML Engine.

**Comment by SHWotever** [comment]
Ah ! So it makes me think the GPU was overall full, not sure about the direction relation with opponents, the HTML engine makes more use of CPU for rendering and way less on GPU that's probably what solves it.

**Comment by andkirby** [comment]
Yesterday tried in iRacing. It's lagging again with HTML engine ON... I'm just pretty rare there.
I'll provide you logs for
- iR session HTML engine ON
- ACC + 20 cars in HTML engine OFF.

>  So it makes me think the GPU was overall full,

I really doubt about GPU. iR consumes much less GPU as you know. I see no logic here.
I can run tests with the lowest graphic settings, and pretty sure it won't help.

@SHWotever what about logs I passed? Does it say something?

**Comment by SHWotever** [comment]
Unfortunately logs showed nothing special. Recently I encounterd another issue with unexplained hangs on arduino feature, it ended to be a side effet of windows "game mode" which focuses all ressources on the game : https://www.windowscentral.com/how-enable-disable-game-mode-windows-10 could you try without it ?(it's enabled by windows by default)

**Comment by andkirby** [comment]
@SHWotever 
Will check definitely. Thanks for this note.
