### ISSUE TITLE
Web page view blocks cookies?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#868]
Hi, I'm working on a "web companion app" for DirtRally which I am running within a SimHub Dash Studio Web page view component.

That works just fine exept for the cookies. 

The build-in web browser (CefSharp?) seems to be blocking these.

Is there a way to make the browser allow for cookies?

Thanks,

Jurgen Gardenier

**Comment by SHWotever** [comment]
Hi ! Currently there is now way, I implemented it as a simple webview (with no cache or cookie storage defined). I will look to add it it.

**Comment by Shaftoe62** [comment]
It's mainly intended as an aide for tuning the car setup before a rally. Gear ratio's in particular.

**Comment by SHWotever** [comment]
Hello ! It's now available in the last version.
Nicolas

**Comment by Shaftoe62** [comment]
Fantastic! You are a real hero!
