### ISSUE TITLE
Vocore2 screen text shift

### ISSUE THREAD

**Issue by helix118** [SHWotever/SimHub#869]
I was having screen shift issues on the Vocore2 after upgrading and reconnecting my dash into a new USB PCIe. Looked at Wot's troubleshooting and still was having the same problems so I emailed vocore support. Looks like there is a firmware upgrade eeprom that is available for the 4in (2 versions) and 5in screens. Launched the eeprom and booted up simhub and the text shift was gone. This may help anyone who is having issues. Below is the path to the new v2touch-win64 with the eeprom firmware upgrade. 

http://vonger.cn/misc/screen/v2touch-win64.zip

**Comment by SHWotever** [comment]
Ah amazing, last time I talked with Chin from vocore he had no solution for it.

I will add this information to the documentation.

Thanks a lot for pointing it.

Nicolas
