### ISSUE TITLE
Argentina missing in CodemastersDirtRally2.TrackNames.csv

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#870]
Hi, Argentina is missing in the new CodemastersDirtRally2.TrackNames.csv

CodemastersDirtRally.TrackNames.csv is complete but I send you an Excel file with all the new tracknames/id's for Dirt Rally 1&2 anyway ;-)

[CodemastersDirtRally1&2TrackNames.xlsx](https://github.com/SHWotever/SimHub/files/6808395/CodemastersDirtRally1.2TrackNames.xlsx)

**Comment by SHWotever** [comment]
Hi ! Thnaks for the report, I don't know how I missed it :( It's fixed for the next update.
