### ISSUE TITLE
F1 2021 - Damages not working in the v.7.4.3

### ISSUE THREAD

**Issue by Javliar** [SHWotever/SimHub#871]
Hi,

I believe that in the newest version the new system of damages does not work in SimHub. [GameRawData.PlayerCarDamageData.m_floorDamage] etc. with different names at the back always show result as 0 - no matter how big of a damage are in the car.

Best,
Michal

**Comment by SHWotever** [comment]
Hi !

Thnaks for the report I published an 7.4.4 update including the fix : https://www.simhubdash.com/download-2/
