### ISSUE TITLE
F1 2021 - Leaderboard does not work

### ISSUE THREAD

**Issue by Javliar** [SHWotever/SimHub#872]
Hi,

it's me again :) The another problem which I found is that the leaderboard which is build in the simhub is not working with F1 2021. It just does not show any kind of times.

Hope it is also fixable :)

Best

**Comment by SHWotever** [comment]
Hi ! Thanks there was indeed an issues with best lap extration not working as it should and whithout this information all the other data could not be computed.

**Comment by Javliar** [comment]
> Hi ! Thanks there was indeed an issues with best lap extration not working as it should and whithout this information all the other data could not be computed.

Thanks, but I think is still does not work correctly. All times are rounded to top value. As an example from top two.
![image](https://user-images.githubusercontent.com/68583477/125824553-e1a028d2-fc73-4fb8-96a4-4b73638d3a68.png)

**Comment by SHWotever** [comment]
Ah thanks ! The precision was lost during conversion.

Lesson learned for next year :D Never add a game while not at home :D It's too hard to test deeply :D

I published the update ;)
