### ISSUE TITLE
AMS2 et pit limiter

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#875]
Hello
Quand la voiture est dans les stands, le pit limiter est à 1 (DataCorePlugin.GameData.PitLimiterOn) indiquant donc qu'il est sur "ON" alors qu'en réalité, si je commence à rouler dans les stands, je m'aperçois qu'il est sur "OFF" car je peux dépasser la vitesse limite
Après la sortie des stands, ce même indicateur se positionne bien sur "0"
un bug dans le jeu ou dans simhub ?

j'utilise le mode par défaut et pas le mode UDP
si j'ai bien compris, le mode UDP n'est pas recommandé car il spamme le réseau. C'est bien ça ?

**Comment by SHWotever** [comment]
Hello ! Effectivement une pétouille, je n'avait pas trouvé la donnée a l'époque et je l'avais donc associé à l'information pitlane pour la rétro compatibilité. Mais après un second regard la donnée est présente dans carstate, j'ai corrigé pour la prochaine version (ca concerne pcars1/2/AMS2)

**Comment by SHWotever** [comment]
Hello ! J'ai releasé la MAJ avec la correction,

Nicolas
