### ISSUE TITLE
ams2 et engineignitionon

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#878]
DataCorePlugin.GameData.EngineIgnitionOn ne passe pas à 1 lorsque je mets le contact
il passe à 1 uniquement après avoir démarré le moteur

**Comment by SHWotever** [comment]
Hello effectivement la donnée est manquante, il y avait bien une donnée engine active, mais qui ne marque que le fait que le moteur tourne, pas très intéressant pour le coup.) J'avais même regardé si d'autres données (pression d'huile ...) changeaient de manière franche et sans erreur possible,mais malheureusement non. Donc pour  ams2 (et les autres : pc2/pc3) je ne peux pas remonter ce statut particulier malheureusement.

**Comment by herve4545** [comment]
c'est bien raceroom, le plus riche en données partagées
et vu que je suis bêta testeur, j'hésite pas à demander les nouvelles données qui m'intéressent
si tu as des suggestions, je suis preneur

**Comment by SHWotever** [comment]
Effectivement racerroom a bien progressé dernièrement ! Sur racerroom il me reste 3 gros manquants par rapport aux autres jeux :
- le type de terrain sous chaque roue (goudron , herbe, Rumble strip etc ....) Ça permet d'avoir des effets plus percutants surtout pour tout ce qui est kerbs. 
- TC actif/ABS actif (quand l'assistance est en train de fonctionner, pour le coup le niveau configuré on l'a déjà, probablement grâce à toi :D)

**Comment by herve4545** [comment]
1) le type de terrain sous chaque roue (goudron , herbe, Rumble strip etc ....) Ça permet d'avoir des effets plus percutants surtout pour tout ce qui est kerbs.
---> Ok je vais créer un ticket


2) TC actif/ABS actif 
oui c'est moi qui avait demandé
donc il ne manque rien ?
j'ai demandé un abs level mais c'est pas dans les tuyaux d'intégrer cette gestion de l'abs

**Comment by SHWotever** [comment]
Ah oui l'ABS actif effectivement était arrivé mais le gros piège c'est que la valeur n'est pas à zéro quand on ne freine pas si je me souviens bien, c'est plus un niveau d'assistance en cours, c'est très détaillé (trop) et ce qui fait qu'on n'arrive pas à extraire la partie intéressante ,sur les autres jeux une a une belle valeur binaire qui représente bien les "coups de piston" qu'on a dans l'ABS lorsqu'il se déclenche (ams2 a cette valeur "abs actif") il il y a un moyen d'extraire de façon fiable cette notion je suis preneur :D

**Comment by herve4545** [comment]
1) sur ams2
j'ai jamais réussi à activer DataCorePlugin.GameData.ABSActive....Il est toujours à 0. Il ne passe jamais à 1
et DataCorePlugin.GameData.ABSLevel n'est pas supporté

idem pour
DataCorePlugin.GameData.TCActive
DataCorePlugin.GameData.TCLevel


2) sur raceroom
il y a DataCorePlugin.GameRawData.AidSettings.Abs qui prend la valeur 5 quand l'abs est actif
c'est ce que j'utilise
c'est pas suffisant ?

et pour le tc, on a ça
DataCorePlugin.GameRawData.AidSettings.Tc = 5

**Comment by SHWotever** [comment]
Hello ! Sur ams2 on a pas l'info concernant les niveau d'assistance configurés (pareil pour PC1/2/3), pour DataCorePlugin.GameData.ABSActive j'ai bien l'info qui remonte (testé sur AJRChevy V8, attention c'est bien la donnée qui indique quand c'est actif ca fait ON/OFF/ON/OFF très vite lors du freinage (et bien entendu il ne se déclenche que quand l'abs est actif (ce n'était pas mon cas au début et en toute logique il restait à zero)
Pour le TC effectivement il semble mort lors de mon test, je pense qu'il s'agit la de l'assistance "reelle" de la voiture quand il y en a, pas les assistance de "jouabilité" (RF2 fais aussi cette différence, assistances de la voiture, assistantes de jouabilité).

Pour RRRE, à le 5 ca mérite d'ètre éssayé, je n'avais pas vu cette valeur ! 

Ps je me permet de cloturer le post sur le forum, ca fait doublon ;)

**Comment by SHWotever** [comment]
En effet la valeur 5 fait le taff  ! 
![image](https://user-images.githubusercontent.com/2207331/126614219-871f7c31-b00e-4176-bf8e-38109b37a45f.png)

**Comment by herve4545** [comment]
ok merci
pour rf2
je n'ai pas vu d'attributs pour le TC et l'ABS;
Tu m'interpelles :)

**Comment by SHWotever** [comment]
Oui ce sont seulement les niveaux d'assistance (level),il n'y a pas de données dispo sur le fait quelles soit actives, et malheureusement pour les niveaux ce sont uniquement les "aides de jouabilité", pas les réglages de la voiture, ca à fait débat depuis des années mais les devs de RF2 n'ont pas apporté d'améliorations depuis bien longtemps (voir même retirent certaines télémétries sur certaines voitures ( par exemple températures, suspensions etc ... sur la plupart des GT3 ....)

**Comment by herve4545** [comment]
Ok merci
Oui la telemetry est pauvre sur rf2

**Comment by SHWotever** [comment]
Hello ! C'est inclus dans la dernière version !
