### ISSUE TITLE
AMS2 - mTyreGrip01/02/03/04

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#879]
Hello
DataCorePlugin.GameRawData.mTyreGrip01/02/03/04

Les % affichés des grip des pneus sont frop bas pour être honnêtes :)
un bug dans le jeu ou dans simhub ?

**Comment by SHWotever** [comment]
Hello, tout ce qui est raw data viens directement du jeu, il n'y a aucun traitement,par contre de souvenir  c'est le grip, pas le contraire (glisse) pour la glisse il faut prendre l'opposé 1 -grip
