### ISSUE TITLE
Feature request: Custom code for LED color/number

### ISSUE THREAD

**Issue by andreasdahl1987** [SHWotever/SimHub#880]
This request is probably too specific for you to spend time on, but Ill bring it up anyways. I enjoy making my own JS scripts for the dash editor, and find this feature extremely useful - basically gives me endless possibilities for customization. I cant find the same kind of freedom with the LED editor. (Well, not entirely true, as most things can be made in the editor by just making hundredes of elements.) 

My idea: A feature in simhub where it can read a string/array from a JS function to enable and change colors on RGB LEDs. It could be structured like "1,6,2,5,3,9,4,10,5,7", meaning "LED 1 - color# 6, LED2 - color#5, LED3 - color#9, LED4 -color#10, LED5 - color#7" The color numbers being predefined; a table of, say, 30 colors. Or any other logical format (maybe a rainbow hue 1-100 system would be a good idea). The point is that this would allow the user to make a single script that describes the all LEDs on/off + color in all possible scenarios, including libraries of shift points and color usage for different cars, etc. Would give more options in thems of customization and would make it easier to add/edit complex features.

**Comment by SHWotever** [comment]
Hi ! I fear that going through ncalc is not really adapted, I'm looking for exposing the led effect SDK so you can build your own effects using the full power of c# with WPF configuration panel, that will be much more efficient and allow to add absolutely anything.

**Comment by andreasdahl1987** [comment]
Ok, dont think I understood much of that, I'll read up a bit. But I get it you've got something in the pipeline...distant future stuff?

**Comment by SHWotever** [comment]
Hi ! I prepared it yesterday, I opened the required "doors" in simhub yesterday and prepared a c# demo project about how to build a led effect.i still have a few details to handle but If everything goes well, this should be bundled in the next version ;)

**Comment by andreasdahl1987** [comment]
Super!

**Comment by SHWotever** [comment]
Hi ! I just released the 7.4.7 update with the SDK ! It's available in C:\Program Files (x86)\SimHub\PluginSdk

Nicolas

**Comment by andreasdahl1987** [comment]
That is massive! Thanks so much :D
