### ISSUE TITLE
Suggestion: Add Format to UDP Forwarding

### ISSUE THREAD

**Issue by twitchexodium** [SHWotever/SimHub#881]
Don't know how complicated it would be. But maybe it's a nice addition to add a choice menu in the forwarding settings for things like F1 Games. I mean the UDP Format changes every year. So maybe we can have a choice menu to forward data in old formats. So you can choose for ex. F1 2021 (and set ingame the format to 2021) and forward data as F1 2020. So it would be cool to use the new Data for all Simhub specific stuff and use the old formats for other programs, where updates may come a lot later after the release, like Fanalab.

**Comment by SHWotever** [comment]
Hi !  F1 2020/ F1 2021 formats and up to F1 2018 are quite complex formats, Converting them is not impossible but at the price of way too much work in my opinion.
Even the historical option "CMPS" which was dedicated to do exactly that has abandonned now  supporting the most recent F1 versions (https://www.eksimracing.org/cmps/) .

In the wait of the other software to upgrade you can disable simhub automatic detection in settings and use the version which will fit the other software, 

I'm pretty sure fanalab will quickly follow, it's a manufacturer software with professionnals developers (while i'm only doing on that alone on my free time) and they probably have some professionnal testing team, they have the "ressources" to do that fast and probably got access to the beta where I've only been able to work on it starting from the public early access.

Nicolas

**Comment by twitchexodium** [comment]
Hey mate, yeah that‘s how i use it :)
Thanks for clarification, dont know that it‘s so complicated :)
