### ISSUE TITLE
ACC wind simulator with Arduino

### ISSUE THREAD

**Issue by scriptoor** [SHWotever/SimHub#882]
Most of the time wind sim works ok but randomly fans stop and then start again. Don't have this issue with the original Assetto Corsa, haven't tested other games. Got connected to only one Arduino and I'm not using any other feature than that. I configured 4 fans as SHAKEIT PWM Outputs. Tested on the 7.4.6 version and previous one. Tried to change the UDP port to 9003 but it didn't help either.

[SimHub.log](https://github.com/SHWotever/SimHub/files/6865272/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! Thanks for the log, I can see indeed two hangs occuring, but what's strange is that I can't see any particular hangs in it, they are simply waiting for processing the next data frame. Could you try those two things :
- in simhub settings set it to high priority. If somehow it's a CPU bottleneck it should help.
- in simhub settings disable any unused plugin. Some of them are running in parallel and maybe there is a  lock which couldn't be identified automatically by my "watchdog"

Let me know.

**Comment by scriptoor** [comment]
High priority setting and disabling other plug-ins didn't help but I have found some weird way to "fix" it. I have noticed that when the Simhub window is in the foreground and I play ACC in the background everything works fine. Anyway, I wish I could use it normally.

If this help:
- I use a single screen 32:9 ratio 5120x1440
- my CPU is i9-7900X
- tested full screen on/off option in ACC
- no other telemetry reading program in the background

I could share my screen with you via Teamviewer etc. if you want.

**Comment by scriptoor** [comment]
Yesterday I have connected 3 shakers with 2 soundcards and the same thing happens with ACC, looks like Simhub loses the connection with the game for a second. Other games are ok.
Any chance to fix that?

**Comment by SHWotever** [comment]
Hi ! This looks like a weird behaviour, this behavior makes think about game boost which is known to cause issues like that (even if I never encountered it specifically) : https://www.windowscentral.com/how-enable-disable-game-mode-windows-10
Copuld you try to disable it and see if it improves the situation ? 
Could you also check the overall system load (CPU/GPU) if it's not drowning ?

**Comment by scriptoor** [comment]
Hey, it worked :D Haven't had much time but have done 15+ laps and no single issue, thanks a lot for the advice :) Amazing work with this software btw, keep it up! :)

**Comment by SHWotever** [comment]
Nice ! Thanks for the feedback ! Have fun !
