### ISSUE TITLE
Hanging while loading replays

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#883]
Salut,
J'espère que tu as passé (ou passes encore) de bonnes vacances.

Je te fait ce ticket que j'ai hésité à faire plusieurs fois par le passé.
Juste pour dire que c'est pas lié à une maj récente.

I noticed loading replays tends to make SimHub hang,
Not every time (even if loading the same replay).
Mostly with large replay files but not only. I'd say more often with large files. I'm not sure.

This implies somewhat long "hang-times" (a few sec to maybe a minute) that can get quite frustrating when testing stuff, and working on plugins as I load replays often.

The logs are clean.

This is no big deal but the inconstancy makes me think there is something fishy going on.
Let me now if if I can do some tests, or if you need me to share some replays.

Bonne fin de soirèe à toi.

**Comment by SHWotever** [comment]
Hello ! Indeed the first step when you start a replay is "indexing it" (locating every records and position) I've observed some replays taking up to 10s for this step, but never more ( my replays are probably smaller.) I will look if I can optimize it, I'm not sure I'm using the fastest method in order to read only a few bytes through a big file.

**Comment by Romainrob** [comment]
Hi,
I see, Maybe the indexes could be saved to a file, if that makes any sense.
Or maybe they already are but temporary only, which could explained the following.

I did some testing and it seems to only hang when loading the replay for the first time.
And the hang duration seems proportional to the replay length, around 1sec per min.
https://youtu.be/rKpVPEnQsJQ

I also tried loading an hour long replay, after restarting SimHub and it didn't hang at all.
https://youtu.be/BFByBuIYiYY

I'll share a link to a large replay it ever finishes uploading.

**Comment by Romainrob** [comment]
Here is the hour long replay:
https://drive.google.com/file/d/1uFoMnIMBOFv9oWs52eHkzwiAE_1iIAca/view?usp=sharing
Bonne journée

**Comment by SHWotever** [comment]
Hello ! I've released the update, first read will occur as before but next one will be almost instant. I decided to avoid destructive ways so it adds a new file aside ang generates it when missing ;)

**Comment by Romainrob** [comment]
Hi.
I'm back and finally testing 7.4.7 :)
I can confirm the replay loading is drastically better.
This will definitely improve the experience.
Thanks for the massive update!
