### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by andreabrachetti** [SHWotever/SimHub#884]
I have a problem with the license, I have formatted the PC and now it does not accept the license anymore, it tells me "Something went wrong while I was loading the license"
Can anyone help me to solve this problem?

**Comment by SHWotever** [comment]
Hi ! Some mail clients sometimes corrupts the license, could you send your information here (PayPal email, transaction Id) so I can send you a clean copy. : https://www.simhubdash.com/simhub-contact/

Nicolas

**Comment by oldichris** [comment]
I have the same problem, however I had already installed the license after I had reinstalled my computer. Now I'm trying to activate the license again, but I get the error message: something went wrong while loading the license
