### ISSUE TITLE
Shake it - Gear effects oddities

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#886]
Salut,
Je te le fais en français ce lui là. Ou franglais quoi ;)

Je revois mon profil bass shaker en profondeur en vu de le rafraîchir et de le simplifier/alléger.
Je re-tune tout, et vire certains de mes effets customs sur-compliqués pour les remplacer par des natifs.

1. Concernant l'effet gear shift, je remarque l'ajout du setting pour moduler la force en fonction des rpm... et j'aime l'idée.
Mais j'ai pas l'impression que ça fonctionne correctement. Ou je le comprends de travers.
Le seuil mini désactive bien l'effet qd les rpm sont en dessous, mais au dessus c'est direct au gain max. C'est pas progressif jusqu'au max effect rpm %.

Pour partager qq reflexions sur le principe d'avoir des shifts moins violent qd on avoine pas:
J'avais tenté de faire la mm chose mais en fonction du changement d'accel, avec un succès mitigé.
Timings compliqués, et les ranges d'accel qui varies selon les voitures.
Il faudrait ta magie d'autocalibration la dessus, et/ou des ranges normalisées accross game.

 D'ailleurs j'ai pas encore trop regardé les prop d'accel que tu as ajouté pour le belt tensiooner il me semble. 
2. C'est normalisé accross games? ou brut depuis les data de chaque jeu?

Une autre option qui me vient à l'esprit serait de moduler le gain en fonction des valeurs de brake et throttle (le plus élevé des 2 au moment du shift). Je crois que je vois expérimenté un peu avec ça.

3. Sinon, j'ai l'impression que l'effet gear grinding est cassé.
Tout ce que j'en tire, c'est des pulses au changement de rapport si mon shifter en H est engagé.
 
 Bonne soirée.

**Comment by Romainrob** [comment]
Pour le point 3
C'est bon en fait. Ça fonctionne. My bad.

**Comment by Romainrob** [comment]
Bonsoir,
Pour partager mon expérimentation avec des effets gear shift customs.

J'ai essayé plusieurs effet ignorant complètement la prop gear.
En gros en essayant de détecter les changements et ou oscillations d'accel ou de speed(pour filtrer les bosses).
Je vois ce ça a du potentiel pour refléter la violence du changement de rapports mais je n'ai pas trouvé d'approche simple et satisfaisante qui fonctionnerait dans les tous cas et qui ignorerait les bosses, et les changement de speed normaux.

Je pense qu'un effet basé sur le changement dans le changement de vitesse, juste pour retourner un "kick" sur les variations d'accel longitudinales serait idéal. Mais je bloque sur la formule.
J'ai testé ça, mais ça ne donne pas l'effet voulu, même en jouant avec les timing:

[Variable]
name='SpeedChangeVariable'
value=abs( maximum( 36, [SpeedKmh]) - minimum( 37, [SpeedKmh]))

[ExportProperty]
name='SpeedChange'
value=[Context.SpeedChangeVariable]

[ExportProperty]
name='ChangeInSpeedChange'
value=abs( maximum( 36, [Context.SpeedChangeVariable]) - minimum( 37, [Context.SpeedChangeVariable]))

Et j'ai aussi testé de basé la force l'effet sur les inputs (90% input et 10% gear). Et c'est de la triche, mais c'est simple ça fonctionne pas mal. J'utilise celui ci pour l'instant.

J'inclus mon profil si tu veux y jeté un œil. T'es pas obligé.
Je ne te demande de "dépanner" mon effet custom. C'est juste si ça donne des idées pour améliorer l’effet natif.

[IRacing - Romainrob - iRacing Bass Shakers v20.zip](https://github.com/SHWotever/SimHub/files/6909814/IRacing.-.Romainrob.-.iRacing.Bass.Shakers.v20.zip)

Pour finir,
J'ai remarqué que Road rumble n'est plus désactivé (unsupported) pour ACC.
Je ne sais pas si c'est par erreurs donc je le mentionne.
Avec les donnée dispo, l'effet ne fait pas grand chose et s'il est high priority on sent surtout les coupures...

Déso pour le pavé et bonne fin de soirée.

**Comment by SHWotever** [comment]
Hello ! J'ai corrigé l'effet en effet une coquillé s'était glissée, 
Pour le road rumble en effet j'ai ajouté une donnée extraite des suspensions, mais vu que ca dépend de la modélisation de la piste ca ne se déclenche que quand il y a suffisament de volume sur le kerb, j'ai aussi ajouté la donnée un peu "décevante" qui vient du jeu.

Pour l'accélération oui c'est standard , ce sont les  champs accélération (m/s²) : 
![image](https://user-images.githubusercontent.com/2207331/128591011-cc364185-8c87-43a3-9999-ccdfa7046416.png)
Le heave est extrait, mais n'est pas standardisé encore (la direction n'est pas iso entre les jeux), c'est un casse tète à déterminer :D
Pour moduler les effets de bass shaker je n'y crois pas trop ce sont des données très brutales sans aucune stabilité ou lissage :(

**Comment by Romainrob** [comment]
Salut,
Tu m'as bien spammé hier ;) Ça fait plaisir.

Pour le rumble sur ACC, j'étais à Spa de souvenir.
J'ai cru reconnaitre la donnée donné du jeu car je sentais l'effet seulement en entrée et sortie de vibreur.
Du coup j'ai pas cherché plus loin. Je re testerai en jouant avec les settings pour voir si je peux en tirer d'avantage.

Merci pour les infos sur les prop d'accel :)
Effectivement ça n'a pas l'air simple pour moduler le gear shift avec. Je vois que ça peut fonctionné mais ptet pas à 100%.
Modulé par "max (brake, throttle)", c'est de la triche, mais pas dégueu à l'usage.
Je suis curieux de tester, la modulation par rpm. Merci pour le fix!
Bon dimanche!

**Comment by SHWotever** [comment]
Hi ! I just released the 7.4.7 update with the fix !

Nicolas

**Comment by Romainrob** [comment]
Hi,
Testing the the rpm based modulation of the gear effect on 7.4.7, I'm still not sure it works as intended.
I can't feel or see any difference across the rpm range:
![Gear Rpm modulation](https://user-images.githubusercontent.com/50543913/130499478-b79d8efd-65bd-4586-925e-defa06fa0c11.png)
Bonne soirée.

**Comment by Romainrob** [comment]
Hmm, it seems I can't reopen closed tickets anymore.
Or maybe this one It was closed too long ago.
Anyway, I hope you still get the comments on closed tickets.
