### ISSUE TITLE
Ardiuno Screens Groups? (Dude/Enhancement)

### ISSUE THREAD

**Issue by braupalizas** [SHWotever/SimHub#887]
Hello, im using Ardiuno TM1637 and Leds for recreate a PCU-6D McLaren (F1 Display). Im thinking was a good idea group the ardiuno screens, similar at the group u can create when create efects in RGB Leds, if i can group the screen, i will can use one rotary encoder or buttons(setting it in controls and events) for move the group, and other rotary encoder or others buttons for move the screen in the group. What would be the advantage? In this case, I will can have in one group, all temps for example, in other group all damage rates, etc. At this moment i have more than 10 screens, and only 1 rotary encoder for move one by one, go to screen 6 in the middle of one race its very difficult.
I dont know if it is possible, maybe have this function and i dont see it correctly

Other fast question: i want buy a license file for use refresh rate 60 FPS and to collaborate with this great proyect that simplified too much my life, but i want know, if i want continue using onlye ONE ardiuno at 10 FPS, can i change it?, or when charge the license file, all ardiuno will up to 60 FPS and cant reduce it?

Thank you too much!, and sorry for my very bad english

**Comment by SHWotever** [comment]
Hi ! There is already a feature request about that : https://github.com/SHWotever/SimHub/issues/828 

I clone this one since it's a duplicate ;)

Concerning the license, currently there is no way to slow down a particular device, they will all run as fast as possible.

Nicolas
