### ISSUE TITLE
NCalc functions maximum and minimum with repeatindex

### ISSUE THREAD

**Issue by xyz4tech** [SHWotever/SimHub#889]
If using 'repeatindex()' in a function maximum() or minimum() I'm getting the maximum or minimum of the complete repetition array instead of current repetition.

Example:
maximum(1500, drivergaptoplayer([DataCorePlugin.GameData.Position] + repeatindex()))

Should this be the case? Is there an other way to get the maximum or minimum of the current repetition?

**Comment by SHWotever** [comment]
Hi ! Indeed it's not normal ! I will look what I can do !

**Comment by SHWotever** [comment]
Hello ! I released a fix in the last version,

Nicolas
