### ISSUE TITLE
small "coquilles" in 7.4.6

### ISSUE THREAD

**Issue by sgeg06** [SHWotever/SimHub#891]
not really bugs, just smalls writing issues in 7.4.6. sketch setup
on the new game pad analog axis (thanks by the way for this fonction), when you select accelerator or brake it's writing throttle on the diagram for both... (by the way throttle and accelerator are similar, may be you mean clutch) 
![Capture](https://user-images.githubusercontent.com/88419558/128125975-75541138-7557-4ed8-a36d-156c83a97115.JPG)

and there is a small "coquille" in the french options in simhub: 
entrée controleur de jeu : boutes a bouton
![Capture2](https://user-images.githubusercontent.com/88419558/128126242-4a5c92e0-3832-46e0-86ab-01c9d6b3e58d.JPG)

thanks for all the work done

**Comment by SHWotever** [comment]
Hello ! 

Merci c'est corrigé pour la prochaine version,

Nicolas

**Comment by sgeg06** [comment]
salut, 
en ai trouvé une autre en cas... 
Dignostic
![Capture](https://user-images.githubusercontent.com/88419558/128621734-b1bdc651-5260-4c1a-a295-927a24d68e01.JPG)

**Comment by SHWotever** [comment]
Hello ! Les corrections sont disponibles avec la version 7.47,

Nicolas
