### ISSUE TITLE
Previous Lap in RaceRoom (Persistent Tracker Plugin)

### ISSUE THREAD

**Issue by xyz4tech** [SHWotever/SimHub#892]
In RaceRoom the Persistent Tracker Plugin does only save a previous lap if it's a valid lap. For validation purpose it would be nice to save all laps even it's an invalid lap (even it's a zero lap time 0:00:00).

With that it would be possible to get the values of PersistantTrackerPlugin.PreviousLap_XX with a repeat index as a complete historie.

**Comment by SHWotever** [comment]
Hi !
Unfortunately this is intentional as most data are not properly trackable without the lap time, it's one of those rare games which stops sending accurate data when the lap invalid and recording the lap was causing lot of side effects that's why lap with no time are excluded from tracking.

**Comment by xyz4tech** [comment]
Thanks for explanation. With the risk of side effects - I understand it isn't worth to change the current behaviour. I found an alternative solution for a repeat index with counting the amount of invalid laps.
