### ISSUE TITLE
Analog inputs for Arduino as game pad

### ISSUE THREAD

**Issue by emilioeer** [SHWotever/SimHub#893]
Is it possible to add analog inputs to a arduino connected as gamedpad? the idea would be to implement DIY Clutch padles, maybe add two axis to enable a padle for bite point like F1 cars, not sure if possible/already integrated or could be developed.

**Comment by SHWotever** [comment]
Hi ! This is already available ;)

![image](https://user-images.githubusercontent.com/2207331/128593390-d18bdeb8-f066-4c94-80a4-e8d883ebc932.png)
