### ISSUE TITLE
Add support for Arduino Due

### ISSUE THREAD

**Issue by fistmaster2k4** [SHWotever/SimHub#894]
I'd like to see support for the Arduino Due in order that the can bus interface and faster Atmel SAM3X8E ARM Cortex-M3 CPU can be utilised. [https://store.arduino.cc/arduino-due](url)

**Comment by martinlanza** [comment]
Me too, the Due is an awesome Arduino version with many I/O capabilities

**Comment by SHWotever** [comment]
Hi ! Unfortunately arduino due as  a 3v board excluding most of the supported devices, but if you are focusing on unsupported features like can you can communicated with the custom serial plugin it will give you full freedom to build your sketch : 
https://github.com/SHWotever/SimHub/wiki#custom-serial-devices-support

**Comment by fistmaster2k4** [comment]
I have been using the  custom serial and the voltage is irrelevant as any devices attached are externally powered, but it ends up being a daisy chain of devices ergo why I wanted it to be natively included, but thanks anyway.
