### ISSUE TITLE
Automobilista1 Sector Laptimes missing

### ISSUE THREAD

**Issue by retroluxfilm** [SHWotever/SimHub#895]
Not sure it this is a bug an incorrect setting or simply a limitation of the rFactorSharedMemoryMap. But somehow at least crew chief is reporting how fast each sector was (not sure if it is correct though) and it uses the same data source.

**Comment by SHWotever** [comment]
Hi ! I just released the 7.4.7 update with the fix !

Nicolas

**Comment by retroluxfilm** [comment]
Great! Will give it a try soon. Thx for your awesome work on simhub. Essential software for simracing.
