### ISSUE TITLE
8x8 64-LED 5050 WS2812 RGB Matrix Display Brightness & current draw

### ISSUE THREAD

**Issue by damiank388** [SHWotever/SimHub#897]
Hi, 
On the manufacturers and retails website we can find that 8x8 matrix can draw over 2A of current:

''One of these RGB LED contains 3 LEDs (Red,Blue and Green). 
Each single LED draw approximately 20mA current at its highest brightness.
So a single WS2812 LED can draw 3 x 20mA = 60mA at maximum brightness - white.
An Arduino cannot supply this amount of power.
You will need a separate 5V power supply; rated for 2A for approximately 50% brightness or 4A for 100%.''

Yet I have measured it today, and with 100% brightness in SIMHUB I see 0.6A draw (white) for the hole matrix. 

So is SimHubs Arduino setup tool limiting the brightness automatically during setup process? 
Or they pulled this numbers out of  ***. Or I don't know how to use Digital multimeter?

**Comment by SHWotever** [comment]
Hi ! There is no soft limit, but there is a theorical hardware limit of ~0.5Amps due to the arduino voltage regulator, that's the limit you hit ;)
