### ISSUE TITLE
configuration affichage choisis simhub oled i2c

### ISSUE THREAD

**Issue by raoulbea-fr** [SHWotever/SimHub#902]
bonjour a tous, dans le cadre de la fabrication d'une boite a bouton pour mon simulateur auto,  je solicite votre aide car etant novice et n'ayant aucune notion de programmation, je souhaite inséré dans cette boite 2 afficheurs oled ic2 pour afficher le traction controle ainsi que la balance bias  je n'arrive pas a la configurer dans simhub (raceroom). pouvez vous me donner la marche a suivre?

merci de m'avoir lu !!
bonne journée.

**Comment by SHWotever** [comment]
Bonjour, il n'est possible d'en utiliser qu'un à la fois : https://github.com/SHWotever/SimHub/wiki/Arduino-SSD1306-0.96''-Oled-I2C , 
attention comme indiqué dans la documentation cet écran utilise beaucoup de RAM de l'Arduino et il n'est pas possible d'utiliser d'autres fonctionnalités à coté sur la même arduino.

Si vous changez le contenu par défaut il faudra éditer le fichier suivant : C:\Program Files (x86)\SimHub\OLEDTemplate\Ingame\0_Default\part1.ini , le langage utilisé dans le fichier est ncalc donc la fonctionnement est décrit ici : https://github.com/SHWotever/SimHub/wiki/NCalc-scripting---Introduction

**Comment by raoulbea-fr** [comment]
Merci beaucoup je vais y mettre le nez dedans ;)
bonne journée.

**Comment by SHWotever** [comment]
Pas de problèmes ! 
Have fun !
