### ISSUE TITLE
v7.4.7 New valid lap data being dumped into the log

### ISSUE THREAD

**Issue by martinlanza** [SHWotever/SimHub#903]
Since upgrading to v7.4.7 the log is being flooded with these info messages:

[2021-08-17 21:53:20,984] INFO - New valid lap detected {
  "IsValid": true,
  "LapNumber": 2,
  "LapId": "984859ef-4998-45de-b82e-9adec6116a48",
  "RecordedAt": "2021-08-17T21:53:20.9843105+10:00",
  "Laptime": "00:01:28.1760000",
  "NewBestLaptime": "00:01:28.1760000",
  "PreviousBestLaptime": "00:01:28.8760000",
  "LapDeltaVsPreviousSessionBest": -0.7,
  "FuelAtLapEnd": 4.0918641090393066,
  "PreviousSimHubAllTimeBest": "00:01:27.1980000",
  "NewSimHubAllTimeBest": "00:01:27.1980000",
  "LapDeltaVsPreviousAllTimeBest": 0.978,
  "SectorDetails": [
    {
      "SectorIndex": 1,
      "SectorTime": "00:00:26.3740000"
    },
    {
      "SectorIndex": 2,
      "SectorTime": "00:01:00.8740000"
    },
    {
      "SectorIndex": 3,
      "SectorTime": "00:01:28.1760000"
    }
  ],
  "LapMaxSpeed": 261.1
}

**Comment by SHWotever** [comment]
Hi ! This is intentional, lap tracking has been already something hard to debug afterwards, that's why I added a full dump of the lap informations so it's easier to understand what has been happening.

**Comment by martinlanza** [comment]
Makes sense, but does it have to be on all the time for everbody?  Trace or config switch would be good...

**Comment by SHWotever** [comment]
hi ! I ended up by logging the lap details in a separate log files, so main log is uncluttered (i only ket a single line with lap time, validity and lap id) so I can refer to the lap log for full lap details.

**Comment by martinlanza** [comment]
Very good - much appreciated

Have to be carefull logging, too much log IO causes stuttering within iRacing
