### ISSUE TITLE
Issue i lost ardiuno screens after reinstall drivers?

### ISSUE THREAD

**Issue by braupalizas** [SHWotever/SimHub#904]
Hello, i having a problem with the screens of ardiuno, i open the simhub and i get the page in blank, without any screens, this screens will save in a files or where it save?, the last things i made was update to 7.4.7 version (i think i use the screen after update anyway), and today morning, i use AMD uninstaller clean up for drivers (becouse i change my graphics card) i dont if this may can make a problem with the screens but i dont know other rason, if i can use logs or anything for check or get it back please tell me

sorry for my bad english and too many thank you!!

**Comment by SHWotever** [comment]
Hi ! 

Screens are saved in C:\Program Files (x86)\SimHub\PluginsData\Common\SerialDashPlugin.json
Sometimes the file can get corrupted if you hard reset your computer or if the simhub process was killed while it was saving. 

Recent simhub versions does backup each last 5 changes to help recovering such situation in C:\Users\Nicolas\Dropbox\AC\Main\SimHub\bin\Debug\PluginsData\Common\_Backups

If somehow you already past the "non return point" and all the backups have been overwritten by an empty file, you can delete C:\Program Files (x86)\SimHub\PluginsData\Common\SerialDashPlugin.json (make a backup first) and reinstall simhub, it will restore the default settings.

Nicolas

**Comment by braupalizas** [comment]
Hello!, i got back my screens, too many thanks to you!!, in the \_Backups the file (b1) last version was broken corrupt, maybe can be becouse i restart my pc too many times with the power button, i get the b2 file and it work perfecly get all my config again :)

Thanks you!!
