### ISSUE TITLE
GTA5 Manual Transmission Mod

### ISSUE THREAD

**Issue by ly200412** [SHWotever/SimHub#905]
Hello. Sinhub still cannot receive the [gtavmanualtransmission] mod data. But I can receive it with [dirt telemetry tool]. What's the situation, please. Can you give me a solution.

**Comment by SHWotever** [comment]
Hi ! I Checked, unfortunately the mod lacks some important data used to determine if the game is currently in race :
IdleRpm and MaxRpm are not reported, which is triggering a "pause" behaviour in simhub and it can't work as is.

I created a ticket on the developper github : https://github.com/E66666666/GTAVManualTransmission/issues/119 wait'n' see ;)

**Comment by E66666666** [comment]
The thing's been updated to set Idle and Max RPM (and with RPM scaled to 8000). Not sure when I'm releasing an update but at least the change is implemented and pushed.
