### ISSUE TITLE
Simhub automatically switches to default game unless selected game is running

### ISSUE THREAD

**Issue by xdesign-michaelcarter** [SHWotever/SimHub#908]
I have three games I use through Simhub - Assetto Corsa, ACC and Dirty Rally 2. If I select either Dirty Rally or ACC before launching either of those games, if I am not quick enough SImhub will switch the selected game back to Assetto Corsa. It's as if there is a timer that switches back to whatever the "default" game is (or simply the first game alphabetically) when it elapses, unless that game is currently running. Often times when my bass shakers are not responding it is because of this issue - I have to alt + tab back to Simhub and select the running game. I'm mainly a Dirt Rally 2 user but I've experienced this with ACC as well.

**Comment by SHWotever** [comment]
Hi ! could you join me the log file ? 
You told it was switching back to AC ? in theory it means that there is a process with one of those names running :
- ACS (64 bit version of AC)
- ACS_x86 (32bit bit version of AC)
- acs_dmm (Japanese version of AC)
- AssettoCorsa (AC official Launcher)

The behaviour you are describing seems to match, once another game is detected as running simhub will first check that the current game is not before switching. 

Could you check when this happens in your task manager that you don't have any of the AC processes listed above running ?

In the wait you can disable automatic game switching here if required : 
![image](https://user-images.githubusercontent.com/2207331/130434737-7c981dce-d2e1-46be-84a7-9ca7575cb04e.png)

**Comment by xdesign-michaelcarter** [comment]
Aha - I did indeed have a process called ACS but it wasn't Assetto Corsa, it was a TP Link service. Once I shut that down the auto switching stopped - the log file confirmed this. Thanks @SHWotever.
