### ISSUE TITLE
SessionOdo resetting to 0 mid session

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#909]
Hi, 
Probably related to this ticket, the 7.4.7 update broke my persistent odometer plugin :(
https://github.com/SHWotever/SimHub/issues/888

I believe it's because DataCorePlugin.GameData.SessionOdo now seems to reset to 0 every time the car speed hits 0.

**Comment by Romainrob** [comment]
To provide a little more info.
I tested with AMS2 and iRacing.
I can't see any errors in the logs.
Bonne soirée.

**Comment by SHWotever** [comment]
Arf ! Indeed on the games I tested it was always rounding to 0.000something which made me miss it :( It's fixed for next version
