### ISSUE TITLE
Auto-launch/close dashboard on game load/exit

### ISSUE THREAD

**Issue by BuToNz** [SHWotever/SimHub#91]
Could be useful as an option?

**Comment by JoshuaxCZ** [comment]
Can be. 

But i have again problems with exit application. 
When i close ass normaly by cross of F4 etc, displays are shutted down (send empty to everything as far as i know).
But when Simhub is running and i'll shutdown whole windows, displays will stay enabled with last informations. 
Is it posible to detect windows shutdown and shutdown simhub too ? Tnx

**Comment by JoshuaxCZ** [comment]
My last shutdown :)
[http://share.vgos.cz/joshuax/achub/windows_shutdown.jpg](url)

**Comment by zegreatclan** [comment]
Will be hard to test :D ... i'll try :D

**Comment by SHWotever** [comment]
Finally done :D
SimHub will save and restore dash if the option is enabled : 
![image](https://user-images.githubusercontent.com/2207331/64479291-19952000-d1b5-11e9-983f-8e474c924f29.png)
