### ISSUE TITLE
Feature request: Possibility to map (wheel) axis input to button / keypress

### ISSUE THREAD

**Issue by ImagineerNL** [SHWotever/SimHub#910]
I can currently map any buttont to any function in simhub or game.
However; e.g. my Fanatec McLaren GT3 has 4 'shift' pedals. (2 on each side)
The 2nd pair of pedals is an analog axis input, which i cannot map to any button.
Same in my F1 rim where a 2axis joystick is.
I would like to be able to map these to a button. If possible i would want to be able to set the treshold (does it register a keypress on 10/20/50/100% downpress). Some axis are flipped 'negative' (100-0) or 'middle' (-100:0:100) ; This might be configured with a checkbox 'inverted' etc.

**Comment by SHWotever** [comment]
Hi ! I don't plan to add this feature. Working with axis is much more like a workaround for the hardware layout and wold add much lot of complexity to the key mapping process, which feels really heavy compared to the potential usage. 
As a workaround something like joytokey would allow you to convert those axis into regular analog inputs.

I close it for readability purpose even if the the feature would be interesting.
