### ISSUE TITLE
How to buy a license key without paypal?

### ISSUE THREAD

**Issue by braupalizas** [SHWotever/SimHub#912]
Hello, im having problems with my credits cars in paypal, im from argentina i dont know if this is the reason becouse i cant, but i have validated my credits cards in paypal but when i will pay i get this:

![paypal error](https://user-images.githubusercontent.com/22064398/130789668-60875f1b-57c2-4001-8e20-d446d2027843.png)

> Unfortunately we have not been able to complete your purchase with the payment method you select. You can complete the purchase with the new suggested payment method from your wallet or choose a different payment method.

I tried with 2 visa credits cards, and one mastercard and i can't pay with anyone, i dont know if anyone can help me, or if u have another payment processor, recently i used this cards in aliexpress without problem i dont know why with paypal i can't.

Too many thanks you, and sorry for my bad english

**Comment by SHWotever** [comment]
Hi !

Thanks for your interest in SimHub.
Currently, PayPal is the only payment method. I'm looking for alternatives for the future, but unfortunately, it won't be available in the short term.

Best regards
Nicolas
