### ISSUE TITLE
Instalação de SDK no Simhub

### ISSUE THREAD

**Issue by FabianoCandido** [SHWotever/SimHub#914]
Olá 

eu instalei a ultima versão do Simhub, 7.4.7  e agora preciso incluir alguns dashs que comprei
porém nem quando executo fora do simhub, nem quando tento carregar o SDK, o simhub tem aceitado.

Eu sempre usei normalmente, e desde que estou em um PC muito melhor que o anterior não consigo usar isso.
Já reinstalei inúmeras vezes o Simhub sem exito.

**Comment by SHWotever** [comment]
Hi ! Could you rewrite it in englis, Unfortunately google translate gave me a really poor translation and I could not understand the issue.

**Comment by FabianoCandido** [comment]
Hello

I installed the latest version of Simhub, 7.4.7 and now I need to include some dashs I bought
but neither when I run from simhub nor when I try to load the SDK, simhub has accepted.

I've always used it normally, and since I'm on a much better PC than the last one I can't use it.
I've regulated Simhub times without success.

**Comment by SHWotever** [comment]
Hi ! I close the issue, third party plugins using sdk are supported by their own authors, do not hesitate to contact them directly.
