### ISSUE TITLE
Gp bikes não está atualizado para o 2019 beta

### ISSUE THREAD

**Issue by EversonNeves** [SHWotever/SimHub#915]
Olá ultimamente o GpBIkes atualizou para o beta19, só que no simhub ele só reconhece se for o beta18. Por gentileza atualizem o Gpbikes na plataforma para que possamos usar as configurações do Simhub nele.
Obrigado

**Comment by SHWotever** [comment]
Hi !

Sorry I don't speak portugese so google translation is a bit inaccurate,

I tried the latest b19 with no particular issues, could you check that you have the built in telemetry plugins availalble in your installation (I use the out of box telemetry provided by the game :
- Can you check that this file is present : C:\Program Files\GP Bikes\gpbikes\plugins\proxy64.dlo
- Can you check that this file is present : C:\Program Files\GP Bikes\gpbikes\proxy.ini

Can you also check that you don't have any older plugins which could conflict with the stock telemetry plugins ?
In my stock game installation I only have those 4 plugins coming with the game, con you check that there no other plugins ? : 
![image](https://user-images.githubusercontent.com/2207331/131314743-5d2418e2-c2b1-4964-bd6c-8e16db93ea51.png)

**Comment by EversonNeves** [comment]
Olá boa tarde!
Eu olhei no meu gpbikes não encontra esses plugins que você menciona.
Como eu consigo eles?

Você me encaminharia eles?
Ou tenho que fazer download em algum lugar ?

Obrigado!

Em ter, 7 de set de 2021 12:22, Wotever ***@***.***> escreveu:
