### ISSUE TITLE
More than one VoCore, VoCore support response 

### ISSUE THREAD

**Issue by damiank388** [SHWotever/SimHub#916]
Hi  SHWotever,

I have asked VoCore support about a possibly to run multiple screens in the future. Here Is their response and file attached. As I have no idea what I'm looking at. 

Hi,

  Currently it is able to run as many vocore on one computer as you want.

  Attachment is the example:

get_port_handle(0xc872, 0x1004);
This will get every vocore screen handle, and every one can be controlled sepratedly.

Regards

Chin

* he attached .c file that I cant attach here. Copy paste:

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <memory.h>
#include <libusb-1.0/libusb.h>

static libusb_context *context = NULL;
static libusb_device_handle *handle = NULL;
static libusb_device_handle *handles[0x10];

#define FRAMESIZE   768000   // 800x480x16bit
#define FRAMESIZE5  819840   // 854x480x16bit
#define MARGIN      0
#define MARGIN5     320

union axis{
    struct hx{
        unsigned char h:4;
        unsigned char u:2;
        unsigned char f:2;
    } x;

    struct hy{
        unsigned char h:4;
        unsigned char id:4;
    } y;

    char c;
};

struct point {
    union axis xh;
    unsigned char xl;
    union axis yh;
    unsigned char yl;

    unsigned char weight;
    unsigned char misc;
};

struct touch {
    unsigned char unused[2];
    unsigned char count;
    struct point p[2];
};

int get_version(libusb_device_handle *h)
{
    unsigned char buf[5] = {0x51, 0x02, 0x04, 0x1f, 0xfc};
    libusb_control_transfer(h, 0x40, 0xb5, 0, 0, buf, 5, 100);
    libusb_control_transfer(h, 0xc0, 0xb6, 0, 0, buf, 1, 100);
    libusb_control_transfer(h, 0xc0, 0xb7, 0, 0, buf, 5, 100);
    return ((int *)(buf + 1))[0];
}

void get_screen_version(libusb_device_handle *h, int *frame_size, int *margin, char *buf)
{
    switch (get_version(h)) {
    case 0x00000005:
        if (buf)
            sprintf(buf, "5inch, 480x854x16/24, SLM5.0-81FPC-A");
        if (frame_size)
            *frame_size = FRAMESIZE5;
        if (margin)
            *margin = MARGIN5;
        break;

    case 0x00000304:
        if (buf)
            sprintf(buf, "4.3inch, 480x800x16/24, D430FPC9316-A");
        if (frame_size)
            *frame_size = FRAMESIZE;
        if (margin)
            *margin = MARGIN;
        break;

    case 0x00000004:
        if (buf)
            sprintf(buf, "4inch, 480x800x16, TOSHIBA-2122");
        if (frame_size)
            *frame_size = FRAMESIZE;
        if (margin)
            *margin = MARGIN;
        break;

    case 0x00000104:
        if (buf)
            sprintf(buf, "4inch, 480x800x16/24, DJN-1922");
        if (frame_size)
            *frame_size = FRAMESIZE;
        if (margin)
            *margin = MARGIN;
        break;

    default:
        if (buf)
            sprintf(buf, "4inch/5inch, 480x800x16, default type");
        if (frame_size)
            *frame_size = FRAMESIZE;
        if (margin)
            *margin = MARGIN;
        break;
    }
}

int get_port_handle(uint16_t vid, uint16_t pid)
{
    struct libusb_device **list = NULL;
    int used = 0;

    int count = libusb_get_device_list(context, &list);
    for (int i = 0; i < count; i++) {
        struct libusb_device_descriptor desc;

        memset(&desc, 0, sizeof(struct libusb_device_descriptor));
        if (libusb_get_device_descriptor(list[i], &desc))
            continue;

        int curport = libusb_get_port_number(list[i]) - 1;
        if (desc.idVendor == vid && desc.idProduct == pid) {
            char screen_info[0x100] = {0};

            libusb_open(list[i], &handles[used]);

            libusb_claim_interface(handles[used], 0);
            libusb_set_interface_alt_setting(handles[used], 0, 0);

            get_screen_version(handles[used], NULL, NULL, screen_info);

            printf("Find screen at USB physics port %d\n", curport);
            printf("Type: %s\n", screen_info);

            used++;
        }
    }

    libusb_free_device_list(list, 0);
    return used;
}

int main(int argc, char *argv[])
{
    int frame_size = 0, margin = 0;

    if (argc > 2) {
        printf("send_frame [bmp16 data]\n");
        return 0;
    }

    // 1. find and open usb device.
    printf("Scaning for VoCore screen...\n\n");

    libusb_init(&context);
    int device_count = get_port_handle(0xc872, 0x1004);
    if (device_count == 0) {
        printf("No screen find, please check driver or USB cable.\n"
               "Press any key to exit.\n");
        getchar();      // avoid suddenly exit for windows.
        return -1;
    }

    handle = handles[0];
    printf("Detected %d screen(s), use first one for test.\n", device_count);

    // close rest screen handles.
    for (int i = 1; i < device_count; i++) {
        if (handles[i]) {
            libusb_release_interface(handles[i], 0);
            libusb_close(handles[i]);
        }
    }

    // we need this data to send correct frame.
    get_screen_version(handle, &frame_size, &margin, NULL);

    // 2. initialize screen and show frame.
    // quit sleep mode, or it will show white screen as default.
    uint8_t cmd1[] = {0x00, 0x29};
    libusb_control_transfer(handle, 0x40, 0xb0, 0, 0, cmd1, 2, 100);

    // read data to buffer and write to screen.
    uint8_t *frame = malloc(frame_size + margin);
    if (argc == 1) {
        if (frame_size == FRAMESIZE)
            argv[1] = "frame.dat";
        if (frame_size == FRAMESIZE5)
            argv[1] = "frame5.dat";
    }

    FILE *fp = fopen(argv[1], "rb");
    if (fp == NULL || frame_size != fread(frame + margin, 1, frame_size, fp)) {
        printf("Input file do not have enough data.\n"
               "Press any key to exit.\n");
        getchar();
        return -1;
    }
    fclose(fp);

    // write start frame command 0x2c.
    uint8_t cmd2[] = {0x00, 0x2c, frame_size, frame_size >> 8, frame_size >> 16, 0x00};

    // example: send two frames to screen.
    libusb_control_transfer(handle, 0x40, 0xb0, 0, 0, cmd2, 6, 100);
    libusb_bulk_transfer(handle, 0x02, frame, frame_size, NULL, 100);

    libusb_control_transfer(handle, 0x40, 0xb0, 0, 0, cmd2, 6, 100);
    libusb_bulk_transfer(handle, 0x02, frame, frame_size, NULL, 100);
    free(frame);

    // 3. now handle touch data.

    unsigned char cmd[128] = {0};
    struct touch *t = (struct touch *)cmd;
    int used = 0;

    printf("\n\nPlease tap on touch screen to test.\n");
    while (1) {
        int x1, x2, y1, y2, t1, t2;
        char map[][6] = {"PRESS", "HOVER", "DRAG"};
        argc = libusb_interrupt_transfer(handle, 0x81, cmd, 128, &used, -1);
        if (argc < 0)
            break;

        x1 = (((int)t->p[0].xh.x.h) << 8) + t->p[0].xl;
        y1 = (((int)t->p[0].yh.y.h) << 8) + t->p[0].yl;
        t1 = t->p[0].xh.x.f;
        x2 = (((int)t->p[1].xh.x.h) << 8) + t->p[1].xl;
        y2 = (((int)t->p[1].yh.y.h) << 8) + t->p[1].yl;
        t2 = t->p[1].xh.x.f;

        if (x2 == 4095 && y2 == 4095)
            printf("%d:%s (%d, %d)\n", t->p[0].yh.y.id, map[t1], x1, y1);
        else
            printf("%d:%s (%d, %d), %d:%s (%d, %d)\n",
                   t->p[0].yh.y.id, map[t1], x1, y1, t->p[1].yh.y.id, map[t2], x2, y2);
    }

    // close usb port.
    libusb_release_interface(handle, 0);
    libusb_close(handle);
    libusb_exit(context);
    return 0;
}

**Comment by SHWotever** [comment]
Hi ! Indeed i'm aware of this solution however it makes the choosen display related to usb port instead of the screen itself, which would lead to broken settings each time you change the usb port, I don't think it's a reliable solution to be sure to peek accurately a specific screen (and so handle many of them) :(

**Comment by damiank388** [comment]
So as long as the DDU would have a physical power switch, and I wouldn't have to unplug it, it would work?

**Comment by Vonger** [comment]
I get so many requests about this feature, could you let me know what is the error, maybe I can help :)
How about add a unique id for each screen and store it in firmware?

**Comment by SHWotever** [comment]
Hi ! @Vonger  Indeed that would be ideal, currently relying on the usb port is too troublesome, I had a similar behaviour with some usb to TTL chips where the serial port was allocated based on the usb port, it was a really uncomfortable behavior, I ended by allocating a unique ID to the arduino firmware so simhub could recognize consistently a unique device. USBD480 works also the same way, in includes a unique serial number, so the device can be consistently recognized.

**Comment by geniusboywonder2020** [comment]
Epic cannot wait for this. You guys are awesome :)

**Comment by GuidoTrampe** [comment]
Oh.. this would be great if it could work...

**Comment by Vonger** [comment]
This is source code and read/write unique id application
http://vonger.cn/misc/screen/screen_uid.20210907.zip

also a simple tutorial here: https://vonger.cn/?p=15160
For old version vocore screen will need to use the application to write a random id to the screen for first time use.

Hopefully this can help develop indicate the screen. :)

**Comment by geniusboywonder2020** [comment]
@SHWotever I have multiple Vocore screens and have added unique UID's to them. Im happy to test a beta version of Simhub for this :)

**Comment by SHWotever** [comment]
@Vonger Amazing, I will play with it ASAP ! I have some rework to do first to get it working but now it's all on me !

**Comment by damiank388** [comment]
Awesome guys !!! You are the best!!!

**Comment by ahshams111** [comment]
Thanks guys for the solution! I downloaded and extracted screen_uid.20210907.zip file in Windows and tried running it but soon I double click on it, it shows blank command prompt disappears soon after without showing any message/error. With Threat protection on I get warning and when I select run anyway or with Threat protection off it doesn't show me the UI and just disappears. 

Also, tried making it work on a mac by following the instructions but when I execute gcc command I get the following error:

gcc screen_uid.c -o screen_uid -lusb-1.0
screen_uid.c:6:10: fatal error: 'libusb-1.0/libusb.h' file not found
#include <libusb-1.0/libusb.h>

Any help on this would be great as I am desperate to make my second Vocore screen work with Simhub.. 

Thanks/regards,

**Comment by damiank388** [comment]
You need drivers for the screen to be detected in command prompt. Plus it doesn't work yet, wait for simHUB update.

**Comment by ahshams111** [comment]
Thanks damiank388 and I understand! As for drivers I have them already as I use the screen with simhub dash. I was only attempting to change the UID using this app - http://vonger.cn/misc/screen/screen_uid.20210907.zip

**Comment by SHWotever** [comment]
@Vonger I played with it, Id writing (with your provided exe) and reading (with the code) worked perfectly, downside I'm facing, I have big instabilities when running many usb context (probably an issue with the libusb wrapper I'm using)I will need to find some smart ideas to workaround that :(

**Comment by ahshams111** [comment]
> You need drivers for the screen to be detected in command prompt. Plus it doesn't work yet, wait for simHUB update.

Thanks damiank388 - libusb was missing from my mac.. upon installing it I am able to run the utility. Thanks

**Comment by SHWotever** [comment]
Hi ! The support is now in the beta available on simhub's discord, it will be publicly available with next simhub release. I've allowed up to 4 screens (more is not really reasonable, as simhub cpu usage will proportionally scale with the number of displays ;) )

**Comment by SHWotever** [comment]
![image](https://user-images.githubusercontent.com/2207331/135329665-9c3612c9-6db1-4c76-9a46-daa000cf2200.png)

**Comment by geniusboywonder2020** [comment]
Your a Legend!!!. Been waiting for this :) Will get it loaded and test for
you.

**Comment by damiank388** [comment]
How do I find invite link to discord lol

**Comment by SHWotever** [comment]
It's available in the releases channel ;)https://www.simhubdash.com/unofficial/SimHub.7.04.8b2.zip

For the old vocore they needs to get a unique I'd written using the method given on vocore website : http://vonger.cn/?p=15160
