### ISSUE TITLE
Nokia lcd black square error 

### ISSUE THREAD

**Issue by Seyitq** [SHWotever/SimHub#917]
hello, I read the codes today and connected the nokia 5110 glcd to the arduino, but only the black square appears on the screen.

sclk = A0
DIN = A1
DC = A2
SCE or ce =A4
RST = A3

[nokia lcds image](https://cdn.discordapp.com/attachments/453962746162315264/882160828806225960/20210831_101148.jpg)

**Comment by TecnoHayat** [comment]
normally it should show the time when idle but it doesn't I tried a lot of templates it didn't work

**Comment by Seyitq** [comment]
hello, I solved the problem, but when I looked at the codes, the pins of the nokia lcd were not written on which leg to connect, I deleted the program and removed the program again, what is the reason, so the next update will be about nokia glcd.
