### ISSUE TITLE
Autostart Dashboard with Game, not windows

### ISSUE THREAD

**Issue by themaluxis** [SHWotever/SimHub#918]
Hey there, 
is there a possibility to start Dashboard automaticaly when Assetto Corsa is launching a game for exemple ?
Autostart (with windows) is great if you have a simracing setup only, but if you play many games or doing some word on your PC instead of playing whole time, its annoying to bring up dashboard on windows starting

Would it be possible to start Dashboard with Race as Overlay ?

**Comment by SHWotever** [comment]
Hi ! 

I close this, this feature and much more has been added to Simhub v8
