### ISSUE TITLE
Test data editor not working with formulas

### ISSUE THREAD

**Issue by exedriver** [SHWotever/SimHub#920]
Within the Arduino configurations, I've found a bug with the test data editor for the RGB Leds for example:

If I use the pre-defined effect "Spotter car left", open the test data editor and simulate under Spotter "car left", then the effect is working (correct).
If I create a custom formular "when formula is true", select the "[SpotterCarLeft]" property as the condition and add an animation effect within the formula, then this animation is not shown when using the test data editor and simulate under Spotter "car left" (not correct, bug?).

As I'm using two 8x8 LED matrixes and therefore are forced to create my animations on my own, it would be great if the custom formulars would also work with the test data editor.

**Comment by SHWotever** [comment]
hi ! Indeed the test data editor only allows to drive built it effects, everything using a custom formula can only use real game data (or a replay) as game data are never altered, but won't be affected by the test data editor.

https://github.com/SHWotever/SimHub/issues/855

I will add a warning message ihn the window, as at first sight it's not obvious I agree.
