### ISSUE TITLE
[Feature request] - ACC New properties please

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#922]
Hi, nice new form! :)

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when some properties are missing.

**Describe the solution you'd like**

The solution I'd like would be to for you to add them please.

**Describe alternatives you've considered**

I don't see any way around the solution I'd like. You won't escape it!

**Additional context**

The missing properties are the following, grip, weather and tyreset related ones:
![image](https://user-images.githubusercontent.com/50543913/132260112-0828a55e-92ca-4fc3-9b59-c56bf01007ec.png)

[ACCSharedMemoryDocumentationV1.7.6.pdf](https://github.com/SHWotever/SimHub/files/7117784/ACCSharedMemoryDocumentationV1.7.6.pdf)

On a side note I noticed these 2 are mislabeled "Not supported", they work perfectly fine:
![image](https://user-images.githubusercontent.com/50543913/132260168-d29d8b74-ae71-4506-8435-e8230af19c3a.png)

Bonne soirée!

**Comment by KrisV147** [comment]
Enums if needed ?

![image](https://user-images.githubusercontent.com/81705070/139600322-14c95efe-9238-4d02-a22e-e4e1cc716307.png)

**Comment by SHWotever** [comment]
Hi ! It's added for the next version, when i last looked it was still not part of the ACC provided samples (only in documentation). It's still not the case unfortunately, so hard to tell if these properties are official yet or not. It seems to work correctly, therefore I've not been able to have a varying forecast, even with high variability, the forecast given was the game was the same as the starting conditions, so hard to tell if it totally works.

**Comment by Romainrob** [comment]
Hi,
I took me a few try to get a session with upcoming changing weather but the property did match the on screen data.
Thanks for the additions!
