### ISSUE TITLE
Dial Gauge doesn't properly update "max value" under HTML engine

### ISSUE THREAD

**Issue by Havner** [SHWotever/SimHub#924]
**Describe the bug**
I have a dash I use for BeamNG, where every car has a different max RPM. That's why I use a "dynamic" RPM gauge that has this NCalc formula under max value (I think I took it from some example dashes):

```
max(2,Ceiling([DataCorePlugin.GameData.NewData.MaxRpm]/1000))
```

This works fine under regular rendering engine, but when using HTML engine, either on screen or on a mobile phone this lags one value behind (e.g for 6600 max rpm it should go up to 7, goes up to 6).

**Simhub version**
7.4.7

**To Reproduce**
1. Launch BeamNG, load some car.
2. Display the included dash on a regular engine
3. Switch engine to HTML, display the dash again
4. The dash should show RPM gauge for max 2000
5. Hit throttle to the floor (on neutral gear) and wait 2 secs (to actually get the max RPM value)
6. The regular engine dash will have updated properly
7. The HTML engine dash will have the max value minus one (see screenshot).

**Expected behavior**
Both dashes update the max value of RPM gauge properly.

**Screenshots**
Regular engine on top
HTML engine in the middle
Phone (HTML) on the bottom
![beamng](https://user-images.githubusercontent.com/6246347/132393803-fcf543ab-34bd-42a9-95f7-941695bdb761.jpg)

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/7123645/SimHub.log)

**Additional context**
[BNG Scarab USB.zip](https://github.com/SHWotever/SimHub/files/7123651/BNG.Scarab.USB.zip)

**Comment by SHWotever** [comment]
Hi I close this issue, as it was related to the old dashboard editor and it has been fixed now.

**Comment by Havner** [comment]
This was related to the HTML rendering engine, not the editor but whatever.

**Comment by SHWotever** [comment]
Hi ! Indeed sorry for the innacurate message. But with the new editor I reworked that specific part (changes detection) in the same time ;)
