### ISSUE TITLE
Dash Studio - TriggerSimHubInputName 

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#927]
**Describe the bug**
Hi,
It seems dash studio tactile buttons no longer report their status as "InputStatus.GraphicalDashPlugin" properties unless the SimulatedKey" box is checked. 

**Simhub version**
7.4.7

**To Reproduce**
1. Add a button to dash and untick the SimulatedKey box

**Expected behavior**
The TriggerSimHubInputName used to work even with SimulatedKey disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/50543913/133703837-2731f0d2-72fc-43f5-8a95-21e182110e21.png)

**Log files**
[SimHub.log.1.txt](https://github.com/SHWotever/SimHub/files/7181595/SimHub.log.1.txt)

**Additional context**
No big deal once you figure it out but potentially breaking for preexisting dashboards
I had to go fix a couple.

Bonne journée

The new SimmulatedKey menu is real nice btw 👍

**Comment by SHWotever** [comment]
it's fixed, indeed some tests were mixed up and the input / simulated keys were mixed when pressing.

**Comment by Romainrob** [comment]
Hi,
I just tested it on 7.4.9b3. It looks good on my end too :D
Thank you for the fix!
