### ISSUE TITLE
Usb Crash

### ISSUE THREAD

**Issue by beastlyfern** [SHWotever/SimHub#929]
**Describe the bug**
USB Crashed during race

**Simhub version**
 
7.4.4

Looked at log file and it seems like all my usb devices crashed but not sure why, could this be because of my wind sim, shakeit motors or shakeit bass setup? Or is it something to do with my PC or usb setup. 

Crash is shown at end of log.

Any insight would be apricated, love the program.  
[SimHub.log.1.txt](https://github.com/SHWotever/SimHub/files/7229145/SimHub.log.1.txt)

**Comment by SHWotever** [comment]
Hi !
This is definitely an hardware issue, if you are using an usb hub, can you check that it's not failing, maybe a shortcut with cable or a bare wire ?  Technically it can be anything, 

If it reproduces often enough, the best approach is to use divide and conquer and unplug each device until you find the guilty one.
