### ISSUE TITLE
iRacing: Rallycross - Joker Laps property per driver is missing.

### ISSUE THREAD

**Issue by hieblmedia** [SHWotever/SimHub#930]
Hello,
the property "JokerLapsComplete" in missing in class iRacingSDK.SessionData._SessionInfo._Sessions._ResultsPositions.

Replay: https://www.dropbox.com/s/hp71b1ne88ml6jo/IRacing_rallycross_with_jokerlaps.zip?dl=1

![image](https://user-images.githubusercontent.com/183510/134994877-548b0f5b-ae99-4595-8e84-4206cf5a1005.png)

**Comment by SHWotever** [comment]
Hi !

It's added for the next version ! 
![image](https://user-images.githubusercontent.com/2207331/135326200-9f213c7c-6635-48e6-9a35-0e05bc2b1dbb.png)

**Comment by SHWotever** [comment]
Thanks a lot for the replay by the way, it make such little changes really fast ;)
