### ISSUE TITLE
Shakeit motors not start working automatically

### ISSUE THREAD

**Issue by Rukibb** [SHWotever/SimHub#931]
Im using ver. 7.4.7. 
I have 3 sets of uno board using motor shield v2.  They are all detected when starting the PC, and all of them can be recognized in simhub. 
I set the static wind on channel 5,6 & 9,10.  Just fans in channel 5,6 run automatically while my pc starts. 
The last set (channel 9,10) will start working after i click "shakeit motor" --> "Motors Output". Without change any settings.
I love simhub, it is fantastic. This is just a very little issue not affecting me much.

**Comment by SHWotever** [comment]
Hi ! Thnaks for the report it's fixed for the next version, indeed it was defaulting to 8 channels until the UI was properly loading the 12 channels when displaying. It's fixed for the next version !

**Comment by Rukibb** [comment]
Thank you so much to the wonderful simhub team.
