### ISSUE TITLE
Exporting Shake It profiles - Wrong file extension

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#933]
**Describe the bug**
Hi,
The exported Shake It profiles (shakers and fans/motors) are currently saved as .ledsprofile instead of .siprofile files. 
So they have to to renamed before being imported because of the extension filter.

**Simhub version**
7.4.8b2

**Screenshots**
![image](https://user-images.githubusercontent.com/50543913/135302368-cbcd786c-2e65-48f4-8462-a859d821e010.png)

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/7253256/SimHub.log)

Bonne soirée!

**Comment by SHWotever** [comment]
Ah ah ! Well seen ! It's fixed for the next release !

**Comment by Romainrob** [comment]
Hi, just to confirm it's back to normal for me on 7.4.8b3.
 Thanks for the fix!
