### ISSUE TITLE
Dash Studio loses data of unsaved work

### ISSUE THREAD

**Issue by dippa-1** [SHWotever/SimHub#944]
**Describe the bug**
When exiting SimHub and when an unsaved Dash Studio is opened at the same time, Dash Studio will also close without asking if the work should be saved.

**Simhub version**
7.4.8

**To Reproduce**
1. Open Dash Studio
2. Drag some Text inside
3. Close SimHub (not Dash Studio)
4. Dash Studio will also close and all data is lost

**Expected behavior**
Prompt the user to save the work, just like when exiting Dash Studio.

**Comment by SHWotever** [comment]
Hi I close this issue, as it was related to the old dashboard editor.
