### ISSUE TITLE
F1 2021 - Session Type Name - Missing Time Trial

### ISSUE THREAD

**Issue by dexter323i** [SHWotever/SimHub#946]
**Describe the bug**
When playing F1 2021, Time Trial, the data.NewData.SessionTypeName has "unknown" value.

**Simhub version**
7.4.8

**Reason**
CodeMasters has changed this enum.
Before 2021:
0 = unknown, 1 = P1, 2 = P2, 3 = P3, 4 = Short P, 5 = Q1
6 = Q2, 7 = Q3, 8 = Short Q, 9 = OSQ, 10 = R, 11 = R2
12 = Time Trial

In 2021:
0 = unknown, 1 = P1, 2 = P2, 3 = P3, 4 = Short P, 5 = Q1
6 = Q2, 7 = Q3, 8 = Short Q, 9 = OSQ, 10 = R, 11 = R2
12 = R3, 13 = Time Trial

It is not even updated in the document. :(

Visit this website: https://forums.codemasters.com/topic/80231-f1-2021-udp-specification/
And Search "R3" or "Time Trial"

**Comment by SHWotever** [comment]
Hi ! Thanks for the info ! It's fixed for the next version !
