### ISSUE TITLE
dirt rally 2.0 et datacarmodel

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#948]
**Describe the bug**
Je fais le rallye des USA avec la fiat abarth 131 et le carmodel affiche plusieurs références de voitures

**Simhub version**
7.4.9b3

**To Reproduce**

**Expected behavior**

**Screenshots**
![1](https://user-images.githubusercontent.com/58605557/139659067-c02886a3-bac7-4645-94c4-a1af363e94a4.jpg)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by SHWotever** [comment]
Hello ! Malheureuseument le jeu ne permet pas de les distinguer, il n'y aucun "id" unique disponible, donc le modèle est déterminé basé sur une "signature" de quelques characteristiques moteur disponibles, et ces voitures ont toutes la meme melheureusement.

**Comment by herve4545** [comment]
Ok merci
