### ISSUE TITLE
[Feature request] Rapsberry Pi RP2040 Support?

### ISSUE THREAD

**Issue by spookeo** [SHWotever/SimHub#949]
Support for the RP2040, Pico, RP2040 Connect, Custom RP2040. A pretty capable board that is cheap to buy, or use on a custom PCB.

There is Arduino support for the RP2040, which can be used for gamepad etc.

If this is possible, I would be happy to assist in testing.

**Comment by SHWotever** [comment]
Hi ! Going out of atmel processors requires a full review of all the libraries unfortunately being alone in the backstage  to maintain Simhub, this requires too much work and maintenance. Currently I have to stick to atmel MCUs until a full replacement emerges (and so i would drop atmel support)
