### ISSUE TITLE
No SDK Detection

### ISSUE THREAD

**Issue by golivezambia** [SHWotever/SimHub#950]
My ETS 1.36.2.2s is unable to detect the SDK (SHETS2Telemetry_x64.dll) on Windows 10 and no prompt window appears. I have tried from the latest Simhub to the earliest version but to no avail. I have followed the instructions of pasting SHETS2Telemetry_x64.dll in the plugin win64 and Win86. Please help.

**Comment by SHWotever** [comment]
Hi ! 1.36 seems a very old version of ETS2 , could you check for updates ? Steam should offer you to update it. Currently simhub implements the latest telemetry starting from ETS2 1.41.
