### ISSUE TITLE
[Feature request] Ets2 & Ats new features from Rencloud v 1.11

### ISSUE THREAD

**Issue by Sergeymxsf1** [SHWotever/SimHub#951]
no support for new features in Rencloud version 1.11

Add new features to the plugin

It would be nice to be able to update this yourself in some way

Hazard Warning (Ets2/ATS 1.41)
Differential Lock (Ets2/ATS 1.41)
Lift Axle and Indicator, Trailer Lift Axle and Indicator (Ets2/ATS 1.41)

**Comment by AKadir68** [comment]
Hello, I live in Turkey. I can't pay with PAYPAL. Sorry.
Can a friend gift me a SIMHUB license, Regards

**Comment by Sergeymxsf1** [comment]
may i know when new features will be added?

**Comment by SHWotever** [comment]
Hi ! Hard to give an ETA, being alone to work on Simhub, time is the limit ;)

**Comment by SHWotever** [comment]
Hi ! This will be released with the next update
