### ISSUE TITLE
Colors are not displayed properly on AX206 in 7.4.10

### ISSUE THREAD

**Issue by jeangagnier** [SHWotever/SimHub#953]
I got an AX206 screen last month from the exact link @SHWotever provided, and I tested it; it worked as expected. However, I tried it again today, and as you can see on photos, the colors are really off. I don't think it's a screen issue as the default/idle screen is the expected colors. 

I'm very puzzled about this. The only thing I can think of is that perhaps the newer version of SimHub corrupted something somehow. I'm now running SimHub 7.4.10.

Steps taken so far:
1. Reinstalled SimHub.
2. Plugged multiple USB cables (including the one that came with the screen that I know worked) in multiple ports.
3. Restarted the computer.
4. Reinstalled the drivers (now, I'm not sure if they're the best ones, but hey).
5. Tried running the same dash on another HDMI monitor. 
6. Reverted to 7.4.8... and it worked!
7. Went back to the new version... and it was back to strange colors.
8. Decided I'd run the 7.4.8 for now :)

Still I thought it should be mentioned for a future patch.

![Photo 2021-11-09, 02 48 16](https://user-images.githubusercontent.com/1359556/140893641-21147674-d602-4b93-8809-3f7b6fb74659.jpg)
![Photo 2021-11-09, 02 48 31](https://user-images.githubusercontent.com/1359556/140893622-d9224c23-8baf-4283-98df-05557fecdefd.jpg)
![Photo 2021-11-09, 02 47 32](https://user-images.githubusercontent.com/1359556/140893635-0b1fba56-f890-4b2b-9446-0a96e13c7fc4.jpg)

And the base screen which worked regardless.
![Photo 2021-11-09, 02 49 28](https://user-images.githubusercontent.com/1359556/140893631-36befb57-db5b-469f-82ac-8323731ab523.jpg)

**Comment by SHWotever** [comment]
Hi ! Thanks for the report, indeed a sneaky regression wa part of 7.4.9 and 7.4.10, I fixed it and released the fix : https://www.simhubdash.com/download-2/

Let me know if it solved it,

Nicolas

**Comment by jeangagnier** [comment]
Quel homme!
