### ISSUE TITLE
USBD480 controller mapped actions A through D not working when changing game

### ISSUE THREAD

**Issue by GiuseppeC86** [SHWotever/SimHub#955]
Hello.

I'm using the latest version of SimHub (7.4.11), but I noticed this bug since a few releases.
Basically, my button box controller functions assigned to action A though D do not work anymore when changing game (I made sure to have the "Autodetect current game" tick still ON); for this reason I need to close SimHub and open it up again in order for the dashboard actions to work normally.
I noticed this bug only affects the USBD480 functions, in fact running the same dashboard on the smartphone with the same assigned controller mappings is fine.

Hope this is enough to investigate the issue.

Thank you.

**Comment by SHWotever** [comment]
Hi ! The fix has been released in the latest update !
