### ISSUE TITLE
Reorder LEDS Effect doesn't work after 32 LEDs - RGB LEDs

### ISSUE THREAD

**Issue by xlordxcheater** [SHWotever/SimHub#956]
Managing a strip of 38 LEDs to show an animation. I can reorder the LEDs until LED 32, after that LED I can't reorder it.

**Simhub version**
7.4.11

**To Reproduce**
1. Go to 'Arduino.'
2. Click on 'RGB Leds'
3. Add Effect REORDER LEDS
4. Nest under reorder leds - Add animation, 36 columns 1 row
6. Reorder LED 33 to the last position ( that's just an example)
5. Go to your animation and click on the LED 33
6. LED 33 is still in the original position
7. Alternatively you can try LED 32 and move it around within the 1 to 32 range and it works. 

**Expected behavior**
Leds 33 to 64 should be able to reordered as indicated in the function.

Thanks

**Comment by SHWotever** [comment]
Hi ! Thanks for the feedback, I've fixed it for the next version !

**Comment by xlordxcheater** [comment]
you're welcome. you would probably have heard this before, but amazing job you've done with SimHub.  Thank you for keeping it up.

**Comment by SHWotever** [comment]
Hi ! The fix has been released in the latest update !

**Comment by xlordxcheater** [comment]
Thanks!! Eager to test it out soon. I will keep you posted
