### ISSUE TITLE
Led Matrix SimDash miss oriented

### ISSUE THREAD

**Issue by mattx38** [SHWotever/SimHub#957]
Since the latest update, my Arduino Led Matrix SimHub Dash, showing gears, is misdirected by a quarter turn. The up side of the numbers are left oriented, but when I change this setup in the Arduino menu, it doesn't make any change.

**Simhub version**
7.4.10

**Comment by SHWotever** [comment]
Hi ! Have you clicked on apply changes after changing the orientation ? 
I've just tested i've not seen issues. 
![image](https://user-images.githubusercontent.com/2207331/141470515-3c92e81d-0165-4a16-b131-81462e8bc0cb.png)

**Comment by mattx38** [comment]
Yes I did

**Comment by mattx38** [comment]
![image](https://user-images.githubusercontent.com/47736789/141470868-ff16fff7-1db4-4991-9a81-d6f4644d3f73.png)

**Comment by SHWotever** [comment]
Je pense qu'il y a une petite confusion, les règlages affichés ici sont ceux de la matrice RGB ,
Au vu des informations, il semble qu'il s'agisse dans votre cas d'une "single color" , tous les réglages sont centralisés ici désormails : 
![image](https://user-images.githubusercontent.com/2207331/141471327-f03872f2-3ce4-4ca0-a11b-0df4c7b67146.png)

**Comment by mattx38** [comment]
C'est exactement ça !
Merci beaucoup pour ce merveilleux outil (dont j'ai acheté la licence déjà depuis quelques temps)
