### ISSUE TITLE
Create Bookmark doesnt work - Replay Controls

### ISSUE THREAD

**Issue by xlordxcheater** [SHWotever/SimHub#958]
**Describe the bug**
Creating bookmarks while replaying the telemetry only creates a bookmark from the beginning. 

**Simhub version**
7.4.11
**To Reproduce**
Provided you record a race with telemetry data
1. Go to 'Replay'
2. Click on 'play button of your replay'
3. Click on play or select any time you want to be in the timeline
4. click on create bookmark
5. click on bookmark
6. the bookmark that was just created is showing 0 to the total length of your video
7. load the bookmark
8. It will play from the beginning of the video

**Expected behavior**
Bookmark should mark the exact location in the timeline when you click on create bookmark

Thanks

**Comment by SHWotever** [comment]
Hi ! bookmarks relates to a replay range, have you assigned a range before creating it ? 
![image](https://user-images.githubusercontent.com/2207331/141503804-ceeb246f-64b7-4232-8bfa-4c4c227f98b2.png)

**Comment by xlordxcheater** [comment]
There you go! Thanks mate! Issue solved.
