### ISSUE TITLE
Hi guys,

### ISSUE THREAD

**Issue by Fsilvest** [SHWotever/SimHub#959]
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by Fsilvest** [comment]
I Guys i have a problem with simhub from past weeks and various versions. When i´m opening Windows Mixed Reality Portal, SimHub close unexpectly. I' m sending logs
[SimHub.log](https://github.com/SHWotever/SimHub/files/7531900/SimHub.log)

Thx in Advance

**Comment by SHWotever** [comment]
Hi ! could you update to the latest version first ? WMR being highly related to usb devices I know there are some conflicts with usbd480 library (which seems to be enabled when seeing your log. Latest version totally isolate USBD480 code so simhub can't crash when such conflicts occurs.
