### ISSUE TITLE
[Feature request] Richard Burns Rally and a gear specific RPM redline and maybe even shiftlight1 and shiftlight2 rpm values?

### ISSUE THREAD

**Issue by mika-n** [SHWotever/SimHub#962]
**The problem of redlineRPM/shiftlight1/shiftlight2 RPMs where a car has different recommended upshift per gear**

SimHub has a great shift light feature (min rpm, max rpm, redline percent of max RPM, shift light 1 percent, shift light 2 percent), but there are few limitations with redline/shiftlight RPM values in a scenario where a game has different cars and each car may have gear specific "optimal" upshift RPM level. Richard Burns Rally is one example.

SimHub let's me define redline RPM as a percentage from max RPM and even let's me customize the value per car (override car settings options). This is good.

But, problems start with shiftlight1 and shiftlight2 offset values. Those are defined as percentage offsets from the calculated redline rpm but the percentage seem to be based on max rpm and it is not possible to adjust the redlineRPM value based on the active gear.
 redlineRPM = maxRPM * redline%
 shiftlight1RPM= redlineRPM - (maxRPM * shiftlight1Offset%) - (maxRPM * shiftlight2Offset%)
 shiftlight2RPM = redlineRPM - (maxRPM * shiftlightOffset2%)

The problem in SimHub it is veeeery difficult to fine tune shift lights correctly per car even when there is a setting to override RPM value per car. SimHub doesn't adjust the redline RPM value per gear but it does it always based on max RPM. Also, it is not possible to override shiftlight1 and shiftlight2 offset values per car (there seem to be one global value for those and this is shared by all cars).

Especially modern rally cars often have different "redline RPM" (=recommended upshift RPM) rpm value for each gear. The built-in shift lights (digidash HUD) in RBR are based on these car and gear specific upshift RPMs. Here is an example of Toyota Yaris WRC "redline RPMs" per gear:
Gear1 upshift = 7320.0
Gear2 upshift = 7230.0
Gear3 upshift = 7170.0
Gear4 upshift = 7060.0
Gear5 upshift = 6960.0
Gear6 upshift = MAXRPM

Also, having only one global percentage value for shiftlight1 and 2 offsets is a bit problematic where one car may have max RPM 9000 and another car 7400 RPM (rpms calculated via percent offsets are in a "different league" so to say and one car may show the "yellow" light too early or too late depending on if shiftlight offset is fine tuned to be "perfect" based on RPM 9000 car or RPM 7400 car). 

**Potential solution**
I have experimented the latest SimHub 7.4.11 version with a modded SimHub-RBR-reader plugin with following changes and this seem to work better than the default logic, but there would be ways to make it even better.

- RBR has physics files per installed car and there is listed Gear#upshift RPM values per gear (rbr\physics\carFolder for a slot\common.lsp).
- The modded SH rbr reader plugin uses these values to dynamically return MaxRPM value as upshift RPM per active gear.
- In SH app I have set "redline percentage from max rpm"  to be "100%" because now max rpm is actually the redline rpm value.
- Also, shiftlight1 and 2 offset percentage values are set to 2-3%, so those early warning lights are not lit too early.

This way SH now works much better with "redline RPM" warning lights and the SH red light is lit at the same time with those RBR built-in lights because it is based on true gear specific upshift recommendation and not just a fixed percentage from max rpm (this fixed value would be good for only one gear).

**Even better solution**
The solution I described and experimented indeed "fakes" the max RPM (GD_MaxRPM in rbrManager) to match up with a gear specific upshift rpm value (read from RBR physics files). But if a dashboard shows min-max rpm values in a gauger scale then this naturally has a side effect where the shown "engine's max RPM" is changed dynamically at runtime per active gear.

The "even better" solution would be a possibility to adjust "redline rpm" value (ie true redline RPM, not just a percentage of max rpm) at runtime based on the active gear (common.lsp "GearXupshift" rpm values). Then the max RPM could remain as it is for the car.

But, to me it looks like at the moment it is not possible to feed "redline rpm" value per gear. There is a car specific "override rpm %" value but the % value would be the same for all gears.

If there would be way to override redlineRPM value per gear then this would be perfect for RBR and maybe for other games also where a different gear has different recommended upshift RPM.

What do you think? Would it be possible to tweak SH backend and reader logic to override "redline RPM" per car and per gear? And with RBR the upshift RPM per gear settings can be read from rbr\physics\carfolder\common.lsp files, so no need to manually maintain those in SH settings unless someone really really want to do it. The modded plugin does this already, but it feeds the upshift RPM via GD_MaxRPM to SH dashboards.

SH seem to have gameSettings.RedlinePercent, gameSettings.Shiftlight1 and gameSettings.Shiftlight2 override values, but I don't know is it possible to adjust those values in a reader plugin or are those values always taken from the persistent game configuration database?

#251 post seem to be related to this suggestion and experiment with a modded version

**Comment by mika-n** [comment]
Here is a link to explaining how the modded "SH reader for RBR" works and a link to the modded plugin. If you need those code changes then just let me know and I'll send those via private msg.
https://github.com/mika-n/NGPCarMenu/issues/17

Or if you have questions about the mod then I'm happy to answer and help with RBR related things.

**Comment by SHWotever** [comment]
Hi ! Thanks for the informations, I took a look, it seems simple to retrieve the information with it indeed (therefor do you know what is the file format ? Extracting it line by line feels not super bullert proof, reading the file is its proper format would be more "satisfying" :D), 

The issue to solve before adding any RBRE specific code is to be able to configure that properly for any game, this upshift variable limit is an issue which exists with some other games (like IR) so it needs to be addressed more globably first (with manual configuration (as RBR would be the only one allowing to retrieve that information.)

**Comment by mika-n** [comment]
Hi. Great you took the effort to look into the issue and a proposed solution for RBR. I'm sure you have better ideas how to integrate the solution properly into SimHub as a generalized solution to make it possible to adjust the redline/shiftlight1/shiftlight2 RPM per car and per gear instead of the solution I did with RBR in mind. It is better to have a game independent solution. I will look into the beta release you just released and for sure I will test it with RBR. Thanks.

The file format of NGP physics files (common.lsp etc) is derived from LISP:
https://en.wikipedia.org/wiki/Format_(Common_Lisp)

The format was used by RBR already in the original vanilla version. A bit weird selection for a file format if there is no LISP code anywhere, but if it does the job then why not. As you have seen from the file it contains nested blocks of (.....) data and each block has a block type name. Gears are defined in ControlUnit block. There may be also string variable following the "opening block" tag, but it is not required so it doesn't work as an anchor keyword. The block type name should however work as an anchor.
`ControlUnit ( "ControlUnit" ..... )`

**Comment by mika-n** [comment]
@SHWotever  Hi. I have now tested the last two beta SimHub versions with "game+car+gear specific" redline RPM support in RBR. The new SimHub GUI interface with this automated redline RPM thing looks good and is easy to use. However, couple comments

- "Per car overrides" has gear N/R and Gear1..GearX redline RPM values, but are those gear indexes wrong with RBR? For example FiestaRally3 in RBR has following NGP6 upshift specs. Note had "Gear3Upshift" is 5800, but the gearX is not actually the X gear, but a gear x-1.  Gear0Upshift is neutral, Gear1Upshift is reverse and Gear2Upshift is actually gear #1

```
common.lsp:
Gear0Upshift					0.0
Gear1Upshift					0.0
Gear2Upshift					6000.0
Gear3Upshift					5800.0
Gear4Upshift					5780.0
Gear5Upshift					5750.0
Gear6Upshift					0.0
RPMLimit						7500.0
```

This is how FiestaRally3 looks like in the latest SimHub beta version.
![image](https://user-images.githubusercontent.com/35538525/144426376-c4cc9d36-c518-4429-8947-bcfd000c0653.png)

So, to me it looks like those redline RPM values are "one off" from the true gear numbers (N and R are correctly recognized, but then the GearXUpshift value is accidentally used directly as a gear# instead of doing -1 offset fix.

But, in overall the new readline RPM logic seem to work great with RBR. Thank you veeeeery much for the improvement.

**Comment by SHWotever** [comment]
Hi ! Thanks for noticing ! I will double check that ! 

Indeed I found during my research that it was common lisp, but unfortunately I could not find any "deserializer" but only interpreters, so I kept in the evil side and used a basic string extraction close to yours :D.

I also took the opportunity of reading this file to extract how many gears has the car and the maxrpm (it was a bit lack of the current reader state)

**Comment by SHWotever** [comment]
Hi ! I fixed it with the latest version !
