### ISSUE TITLE
Flags activation in ACC 

### ISSUE THREAD

**Issue by damiank388** [SHWotever/SimHub#964]
**Describe the bug**
[flag_yellow] is being triggered by anything anywhere on the track, then followed by green. 
What previously was only activating sectors [global yellow1/2/3] from acc.cds, now also triggers [flag yellow].
 
And that is annoying, if smb parks in sector 3 for the race after crash, you get yellow in your face for the whole race.

**Simhub version**
Make sure to run the latest version - 7.4.12b6 this started with addition of multi matrix support (rather sure)

**Expected behavior**
Previously yellow/green Flags ware triggered with bar that shows up in ACC (Left top corner) when something happens just ahead/around the car.  That was more localised to where car is on the track and relevant. 

Now it seems to me that flags activate with what is displayed on both sides of the race timer (middle of  display in ACC). Hence the workaround with limiting display time for [flag_green] as it was on LEDs constantly. 

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by SHWotever** [comment]
Hi ! I reverted the changes in the latest update.
