### ISSUE TITLE
1602 LCD Keypad Shield 

### ISSUE THREAD

**Issue by scarified8** [SHWotever/SimHub#966]
Hello! 
I have the 1602 LCD Keypad Shield(D1/DF robot) on an Arduino Uno, and I'm trying to connect to simhub via the 20x4 lcd menu.
Since this shield uses the LiquidCrystal library (and it's a shield), when running the I2C test it returns:
"No I2C devices found"

There is a way for me to make this shield compatible with Simhub?
The shield is correctly installed and working on Arduino IDE. 
I understand that this display is really slow, but I really wanna use it (and the buttons)

**Comment by SHWotever** [comment]
Hi ! Are you sure it's an i2C lcd ? When reading this shield description I see no mentions of I2C interface. Currently the libraries inluded in simhub should cover most of the I2C screens variations, but not direct wiring (even through a shield.
