### ISSUE TITLE
Best Split and Self Split not working with new version

### ISSUE THREAD

**Issue by jefcam** [SHWotever/SimHub#967]
**Describe the bug**
The best split anf self split are not working with the new version of simhub.

**Simhub version**
7.4.11

![image](https://user-images.githubusercontent.com/94743058/142724231-246fce59-5f84-486d-ad6c-b13b012375d3.png)

**Comment by jefcam** [comment]
no solution for this yet?

**Comment by jefcam** [comment]
I made an intensive test on many simhub versions to check when bestsplit and selfsplit stopped working. The last version that these options worked was 7.4.6.  In 7.4.7 it stopped working.

**Comment by SHWotever** [comment]
I confirm I killed the code with the sector tracking update, I tried to revive it , but it's not compatible with the new way I track sectors. I put it on the to do list, please be patient. I try to do my best to restore it, but there is a single developer (me 🙂 )

**Comment by SHWotever** [comment]
Hi ! Is back, and also available for any opponents and sector count in the last version.
