### ISSUE TITLE
Serial Port Notifier - Not always working

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#968]
**Describe the bug**
Hi,
I just noticed the serial port notifier plugin doesn't work for me, if the unplugged/re-plugged device was already connected when SimHub started.
In this case I get no notification when unplugging it.
And an empty one when plugging it back.
It seems to work fine if the device wasn't connected when  SimHub started.

**Simhub version**
7.4.12

**To Reproduce**
1. Unplug a serial device
2. Start SimHub
3. Connect the serial device back

**Screenshots**
![Serial Notif empty](https://user-images.githubusercontent.com/50543913/142733962-7ab76bec-7b58-4351-8269-400f58763ab5.jpg)

**Log files**
[SimHub Serial Notif NOK.log](https://github.com/SHWotever/SimHub/files/7574843/SimHub.Serial.Notif.NOK.log)

**Additional context**
Tested with an Arduino pro micro

Bon week-end!

**Comment by SHWotever** [comment]
Hi ! Thanks for the feedback , I found, the issue (it was sneaky, sometimes the order was simply changing , and so it was not finding the port with was added or removed, but simply a "a change", triggering an empty popup.

**Comment by Romainrob** [comment]
Hi,
I see.
You're welcome, and thanks in advance for the fix.
Reading this again, my steps to reproduce were wrong. I'll pretend this was a test. You pass :D

**Comment by Romainrob** [comment]
Hi,
I'm checking out the new beta 7.4.13b1
I don't get empty notifications anymore but I only get a notification like half the time
I haven't figured out any logic as to when I get one or don't
I seems when it works for one port it doesn't for the other. I'm testing with 2 Arduino pro micro

**Comment by Romainrob** [comment]
Bonsoir,
Je teste la b2 et j'ai tjrs pas de notif a chaque fois.
Ici j'ai branché/débranché mes 2 Arduino (qui sont sur un hub USB, soit dit en passant) dans différents ordres.
Je vois bien la notif qd ils y une entrée "Serial port monitor : change detected. ..." dans les logs
Mais il n'y en a pas tjrs.
[SimHub.log](https://github.com/SHWotever/SimHub/files/7645387/SimHub.log)
Dis moi si tu veux que je fasse un test particulier.
Bonne fin de soirée.

**Comment by SHWotever** [comment]
Hello !

J'ai trouvé deux cas, un plus "facile" que l'autre.
Le premier cas, c'est windows qui ne raporte pas le changement, j'ai pu le croiser une paire de fois, la liste des port série est stockée dans le registre et des fois il n'est pas supprimé par windows. Dans ce cas précis pas de solution c'est windows qui gère.

Le second cas dont je n'arrive pas à cerner le déclenchemet, le changement est détecté, mais la popup n'apparait pas, ca sent le bug dans la libraire de "toast notification", il faut que je vois si avec une autre c'est mieux.

**Comment by Romainrob** [comment]
Salut,
Je teste dur la 13 final.
Je ne sais pas si tu as fais des changements mais de mon coté et c'est tjrs pareil.
Ça pop un peu qd ça veut bien.
Je regarde dans de device manage manager et je vois bien les ports com aller et venir qd je débranche et rebranche.
Je veut bien regarder dans le registre si ça suit ou pas.
Quelle clef surveilles tu?

**Comment by SHWotever** [comment]
Hello !

Non je n'ai pas fait de changement, j'ai pu voir que la notification echoue de temps en temps malgrès la bonne détection (qu'on voit dans les logs). Pour ca il faut que je trouve une autre librairie ou que je le refasse de 0.

Pour le second cas (registre) ca se passe ici : Ordinateur\HKEY_LOCAL_MACHINE\HARDWARE\DEVICEMAP\SERIALCOMM
C'est çà que .net utilise pour liste les ports série et qui des fois reste coincé, Dans ce cas là par contre j'ai pas la main, c'est windows qui gère.

**Comment by Romainrob** [comment]
Je confirme. Je les vois qui parfois restent dans le registre :(
Puis avec les ghosts ça fait des doublons temporairement, pour 1 ou 2 min.
![image](https://user-images.githubusercontent.com/50543913/144756894-35e74d73-f48d-46db-97b3-a45edb0fce30.png)

**Comment by SHWotever** [comment]
Hello ! Je fais un peu de ménage, de ce coté je pense que tout est bon (au delta près du probleme de windows sur lequel je n'ai pas la main.)

**Comment by SHWotever** [comment]
Hello ! Just a little follow up to this old one, it was indeed not specifically in my hands but in the .net framework code, when releasing a serial port after a physical disconnect the framework was not releasing all the resources instantly but way later (garbage collector through destructor when it hits, or application exit) I added a little hack to force it release it instantly. It won't prevent any other apps using .net to get a serial port "stuck" for a time, but at least simhub won't anymore. 

I leave the piece of code here for science for anyone having a similar issue and finding this issue ;)
It seems that all the online resources about this issue were blaming the usb to serial driver, but .... but ... actually it seems it was wrong. Thanks to the decompiler I've been able to track down an undisposed stream holding a handle to the serial port. This handle was the culprit and was only kept when the serial port was already shown as closed due to serial port loss (physical disconnect ...).

The fix is a serial port override enforcing disposing to make sure the internal SerialPortStream (Accessible as "BaseStream" when serial is open) gets disposed even if it the serial port was already reporting to be closed due to the physical disconnect.

This still requires to properly dispose/close the serial port after disconnect (isopen = false).

It also features static events to track down the serial ports activity (opening, closing, disposing) in a complex setup like SimHub is ;)

```
    public class SHSerialPort : SerialPort
    {
        // The last base stream for later disposing it.
        private Stream internalSerialStream;

        public new static string[] GetPortNames()
        {
            return SerialPort.GetPortNames();
        }

        public SHSerialPort(string portName, int baudRate) : base(portName, baudRate)
        {
        }

        public SHSerialPort(IContainer container) : base(container)
        {
        }

        public SHSerialPort()
        {
        }

        public SHSerialPort(string portName) : base(portName)
        {
        }

        public SHSerialPort(string portName, int baudRate, Parity parity) : base(portName, baudRate, parity)
        {
        }

        public SHSerialPort(string portName, int baudRate, Parity parity, int dataBits) : base(portName, baudRate, parity, dataBits)
        {
        }

        public SHSerialPort(string portName, int baudRate, Parity parity, int dataBits, StopBits stopBits) : base(portName, baudRate, parity, dataBits, stopBits)
        {
        }

        public new void Open()
        {
            base.Open();
            // Holds the stream after opening the port, it can't be accessed again when port is already closed.
            internalSerialStream = base.BaseStream;
            SerialPortOpened?.Invoke(this, this.PortName);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && IsOpen)
            {
                // Let the FW do everything in a normal way.
                internalSerialStream = null;
                SerialPortClosed?.Invoke(this, this.PortName);
            }
            else if (disposing && !IsOpen)
            {
                SerialPortDisposed?.Invoke(this, this.PortName);
            }

            base.Dispose(disposing);

            try
            {
                internalSerialStream?.Dispose();
            }
            catch
            {
                // Can throw an exception when releasing a disconnected port, but will still release the handles as wanted.
            }

            internalSerialStream = null;
        }

        public delegate void SerialPortEventDelegate(SHSerialPort sender, string port);

        public static event SerialPortEventDelegate SerialPortClosed;

        public static event SerialPortEventDelegate SerialPortDisposed;

        public static event SerialPortEventDelegate SerialPortOpened;
    }
````
