### ISSUE TITLE
SIMHUB will not start

### ISSUE THREAD

**Issue by Yuta0710** [SHWotever/SimHub#969]
During initial startup, I get the error shown in the screenshot, and when I try to start the SIMHUB again, I get "initializing Plugin : Web...". When I try to start the sim hub again, it freezes with "initializing Plugin : Web...".
![image](https://user-images.githubusercontent.com/89745745/142799068-359dc9e5-40da-4f10-904e-444857df8b81.png)

[SimHub.log](https://github.com/SHWotever/SimHub/files/7578126/SimHub.log)

The initial startup log is the following txt
[SimHub.log.1.txt](https://github.com/SHWotever/SimHub/files/7578129/SimHub.log.1.txt)

**Comment by SHWotever** [comment]
Hi ! It looks like the font C:\Users\OogamiYuta\AppData\Local\Microsoft\Windows\Fonts\07やさしさゴシックボールド.ttf  is faulty and can't be analysed and si is breaking the loading, could you try to remove it ?
