### ISSUE TITLE
[Feature request] Forza - Car model support

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#970]
**Is your feature request related to a problem? Please describe.**
Hi,
SimHub currently doesn't support car model detection for FH5. Possibly for other Forza games, I didn't check 
DataCorePlugin.GameData.CarModel returns the time of the day for some reason
And we can't use the car settings.

**Describe the solution you'd like**
The car model unique ID is reported via DataCorePlugin.GameRawData.CarOrdinal
![image](https://user-images.githubusercontent.com/50543913/142915038-9513ea25-402e-405a-879d-4e30532d39a9.png)

https://forums.forzamotorsport.net/turn10_postsm926839_Forza-Motorsport-7--Data-Out--feature-details.aspx#post_926839
This still seems to be valid for FH5.

Could you please you use this as car model?
Bonne soirée!

**Comment by SHWotever** [comment]
Thnaks for the report, indeed that was something, I was aware of, originally I wanted to get all the car names, but it's barely impossible on Forza horizon :(

**Comment by Romainrob** [comment]
Hi,
I understand. Hundreds of cars, ever changing with DLCs would be a pain to to maintain.
It sure would be easier if the data actually included the car models by name. :(

**Comment by SHWotever** [comment]
Hi ! It was released with the latest version.
