### ISSUE TITLE
Adding frames in Animation requires 2 layers in order to edit the first layer

### ISSUE THREAD

**Issue by xlordxcheater** [SHWotever/SimHub#972]
**Describe the bug**
Adding frames in Animation requires 2 layers in order to edit the first layer
**Simhub version**
7.4.12
**To Reproduce**
1. Go to 'Arduino, RGB LEds.'
2. Add effect, click animation '....'
3. click add frame
4. click on the newly created frame
5. No Frame to edit

**Expected behavior**
Click on add frame and the new frame should be available to create the animation

**Additional context**
Workaround: Add a second layer, click on the second layer and the 2 layers will be available for edit.

**Comment by SHWotever** [comment]
Hi ! The fix has been released with the latest version.

Nicolas

**Comment by xlordxcheater** [comment]
Thanks Nicolas! This is the best software for simracing.
