### ISSUE TITLE
[Feature request] Allow changing the ETS2 map component's address

### ISSUE THREAD

**Issue by TagForce** [SHWotever/SimHub#973]
**Is your feature request related to a problem? Please describe.**
Not really a problem, simHUB is lacking the ability to show a Forza Horizon map, and creating a web page component loses the ability to keep it at 127.0.0.1, and destroys interaction. Using the ETS2 map component allows for all that, and works like a charm, but reverts back to the original URL upon saving the dash, which is annoying.

**Describe the solution you'd like**
Allow inputting a different map address that is saved.

**Describe alternatives you've considered**
Editing the map.html file directly (instead of creating a map-fh.html file), but that will be reverted back to the original upon updating simHUB, and it will also render the original ETS and ATS maps incompatible with the new html, as there is hardcoded information which is different from FH's information which is not provided in the tsmap-xx.zip files.

The alternative to the alternative is creating a new map.html and tsmap-ets2.zip and tsmap-ats.zip files and provide them to you for inclusion, but since this is very much a work in progress that will take a while.

**Additional context**
While the ETS map component works pretty well for ETS2 and ATS, I've found it also works very nicely for FH4 and FH5, provided there are some modifications to the html. It requires some additional info to render the map and its coordinate system correctly, which is hardcoded in the current html file. This is one of those components that could see a major increase in usability if it wasn't restricted to the Truck Simulators. It is very powerful, but it lacks in customisability to be useful now.

While I see the security issues with releasing the map address field, I feel like the ability to create maps for any supported open world game trump those.

**Comment by SHWotever** [comment]
Hi ! 

As a quick solution I made the web componnent adress bindable, so you can point to a computed address. I also added a proprty to get the simhub server base address, 

To it allows to use the web page view to show a custom map in a few steps : 
![image](https://user-images.githubusercontent.com/2207331/143770410-f9250402-6434-4727-a464-4e55a7ae2532.png)

This will both work in remote (from a phone) and locally.

Those additions will be available int he next release ;)

Nicolas

**Comment by TagForce** [comment]
Brilliant... I now have working maps for both FH4 and FH5, and will be testing this addition to the software when it is released.

Thank you very much.

**Comment by SHWotever** [comment]
Hi ! It was released with the latest version.
