### ISSUE TITLE
[Feature request] iRacing - Tyre Pressure Live

### ISSUE THREAD

**Issue by projektdotnet** [SHWotever/SimHub#974]
**Is your feature request related to a problem? Please describe.**
The tyre pressure variables (GameData.TyrePressure[location]) are the setup cold pressure in iRacing and not the current pressure where available. Is it possible to get that corrected?

**Describe the solution you'd like**
Add the TyrePressureLive variable for each corner

**Describe alternatives you've considered**
Alternatively, adding raw irsdk values under properties, even via plugin, for use in a dashboard

**Comment by SHWotever** [comment]
Hi !

As far as I know the data is not available in telemetry. Currently simhub automatically adds properties as soon as they appear (ir has a really special behaviour where each car can add or remove data, so simhub automatically lists and remember them as soon as they appear) do you know a car where it would be available ? Maybe do you have a simhub replay with that car ? For me not giving live temperatures was a deliberate choice from iracing to avoid an "unfair advantage". 

Nicolas

**Comment by martinlanza** [comment]
The tyre data is only exported through the irSDK when you enter the pits and stop at your pit bay.

**Comment by projektdotnet** [comment]
I thought that the tyre pressure was available for cars that support it (ex BMW M4 GT3). The BMW has it on the in-game dash but you're saying that the irsdk does not get a copy of that via telemetry then? That's a bummer.
