### ISSUE TITLE
ShakeIt Wind dashboard notification text is reversed from actual state

### ISSUE THREAD

**Issue by Dakoriki** [SHWotever/SimHub#976]
When switching idle wind speed with a mapped button the notification text on a dashboard says the opposite of what happened

On v7.4.12
When enabled
![Captaure](https://user-images.githubusercontent.com/77527118/143677554-f04d7a0e-bf5b-4da2-8137-2d5d90391007.PNG)
When disabled/muted
![Captaaure](https://user-images.githubusercontent.com/77527118/143677555-6ed2618b-5d14-414f-98cf-2b20c2522b8c.PNG)

Using this mapped button
![Captaaaure](https://user-images.githubusercontent.com/77527118/143677688-5b37d6ee-bdb8-4d05-aea6-db4ecd2fc550.PNG)

**Comment by SHWotever** [comment]
Hi ! Thanks for the report ! it's fixed for the next version !

**Comment by SHWotever** [comment]
Hi ! It was released with the latest version.
