### ISSUE TITLE
ABS and brake pedal position on servo

### ISSUE THREAD

**Issue by basthard300** [SHWotever/SimHub#979]
Hi everyone, I have this question:
given that I am a beginner, I am using "SHCUSTOMPROTOCOL" because I would like to rotate a SERVO as the brake pedal but I am missing something that I cannot find among the parameters. Is there anyone who can give me a solution?
I am attaching what works for me now and that is the ABS response.
I miss the Pedal Position that I would like to map to the same Servo if possible. know then suggest how to complete this listing.
Where am I doing wrong?

this is my first file:
[ABS TEST.txt](https://github.com/SHWotever/SimHub/files/7644890/ABS.TEST.txt)

**Comment by SHWotever** [comment]
Hi ! 

I'm sorry I can't understand the bug you are encountering. Could you describe it ? The code you sent looks fine and values should be transferred correctly.

Nicolas



Nicolas

**Comment by basthard300** [comment]
bye! again;
I probably didn't get it right, I'll try to do it now:
my file let's say it is composed of two variables, which are respectively "ABSACTIVE" and "BRAKEPEDALDegree".
Now, in the first case the reading of the data by the SIMHUB formula works perfectly. in fact the SERVO follows the excursion with values from 0 to 1.
In the second case, on the other hand, in the SIMHUB LOG I have the reading of the "Percentage degrees" ranging from zero to about 100, but, with the sketch thus set up, I have no movement on the part of the SERVO.
In practice, excluding the first section of the "ABSACTIVE" and trying only the reading of the degrees, there is no work from the SERVO.
While writing I noted that I had forgotten an "=" in the brackets after IF but nothing has changed.
Do you have any suggestions???
THANKS IN ADVANCE

**Comment by basthard300** [comment]
solved...my self! tks a lot 
Paul
