### ISSUE TITLE
(Crash report) Hard restart during use of SimHub under Windows 10

### ISSUE THREAD

**Issue by PhoenixTT** [SHWotever/SimHub#980]
**Describe the bug**
Since version 7.4.13b I experience randomly hard resets of my PC when SimHub is running. I updated all drivers (chipset, video, sound) and the bios of my mainboard. As long as I do not open SimHub the system is stable. After starting SimHub the system hard restarts itself after short time (15-30 minutes). 

**Simhub version**
7.4.13b and 7.4.14

**To Reproduce**
Reset happens randomly during SimHub use. 

Two times during using Dashstudio: 
1. Duplicate existing dashboard template
2. Add rectangle to template, add spotter details
3. File->Save

**Expected behavior**
No randomly restarts during gaming/simracing/using Dashstudio. 

**Screenshots**
No screenshots possible

**Log files**
Log file of last hard reset attached. 

**Additional context**
I experience the same behavior during using Ultimaker CURA, a slicer program for 3D printing. This bug is connected to new Ryzen CPUs and could not be solved by Ultimaker.

**Comment by SHWotever** [comment]
Hi ! Considering it happens wit cura too,I don't think it's particularly related to simhub, I would suspect a graphics driver issue maybe linked to desktop windowed apps (which would be the common point with simhub) .I would try first a simple bios reset it often helps with the most sneaky motherboard stability issues.
