### ISSUE TITLE
IRacing NEW Hyundai TCR causes IRacing to be in "waiting" state

### ISSUE THREAD

**Issue by selectyoungs** [SHWotever/SimHub#981]
Simhub works fine for all cars except the new tcr Hyundai (new Civic is fine), simhub doesnt seem to recognize IRacing with this car

**Simhub version**
newest version

only happens for this car, seems to see iracing is running for a second or 2, then ignores that iracing is running, not sure if its an IRacing issue or simhub issue, but racelabs and kapps still give telemetry with the Hyundai so im not sure.

**Comment by SHWotever** [comment]
Hi ! Thanks for the report. Could you join the log files ( C:\Program Files (x86)\SimHub\Logs) ffter trying this car so I can take a look ?

Nicolas

**Comment by SHWotever** [comment]
Hi ! I've been able to get your logs from the discord, thanks for it ! 

I've released a fix : 
![image](https://user-images.githubusercontent.com/2207331/145207813-19485f9f-bb79-43bd-9a8e-21b4996e6b60.png)


Nicolas

**Comment by selectyoungs** [comment]
Sorry i could not upload my log, was asleep. I have updated simhub and everything works again :)  Thank!

**Comment by SHWotever** [comment]
Perfect ! Thanks for the feedback !
