### ISSUE TITLE
Bass Shakers not working in Farming Simulator 22

### ISSUE THREAD

**Issue by dezza69** [SHWotever/SimHub#982]
**Describe the bug**
No bass shakers when the vehicle's engine runs in Farming Simulator 22

**Simhub version**
Any above 7.4.12 (eg, 7.4.15)

**To Reproduce**
1. Download and install SimHub 7.4.15
2. Install telemetry mod to Farming Simulator 22 (tried manual and auto)
3. run both SimHub and Farming Simulator 22
4. change to vehicle, start engine - no bass shaker.

**Expected behavior**

I'd expect my seat to vibrate from the little bass shaker when the engine runs, like it does with version 7.4.12 (which doesn't "officially" support FS22).

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Nothing shows.

**Additional context**

-------------
As a side note, I found in both FS19 and FS22 the bass shakers (when not affected by the issue described above!) continued to shake as if the engine was running whether or not the vehicle was "entered".

I slightly modified the telemetry mod with this code which changed that behaviour.

Inside "if (vehicle.spec_motorized ~= nil) then"

I added:

			local tempRPM = 0
			if ( spec_motorized.isMotorStarted ) then
				tempRPM = engine.lastRealMotorRpm
                	end
                        self:addNumberToTelemetry("Rpm", tempRPM)

and the bass shakers run as they should (when not affected by the issue described in this bug alert)

:)

Thanks BTW, love this app - it's fantastic to so easily be able to add immersion.

**Comment by SHWotever** [comment]
Hi ! 

Thnaks for the feedback !
Indeed I change I made in preparation of flight sims had disabled all the shakeit effects for this game. I unlocked them.
I also included a fix for the rpm (but on the simhub code side, instead of the plugin)

**Comment by dezza69** [comment]
Thank you very much.

Do I need to download and test anything for you?

(I noticed the Flight Sim folder with the other game "mods" in the program structure - also very, very excited for this future functionality to be enabled).

Kind regards.

**Comment by SHWotever** [comment]
I published the update a few seconds ago ;)  https://www.simhubdash.com/download-2/ It was a little typo easy and fast to fix :D

Nicolas
