### ISSUE TITLE
Horizon 5 Cannot get Steering wheel data

### ISSUE THREAD

**Issue by o129327** [SHWotever/SimHub#983]
Horizon 5 Cannot get Steering wheel data

**Comment by SHWotever** [comment]
Hi !

I checked I could get the values with no particular issues :
it goes from -127 to 127 as excepted :
![image](https://user-images.githubusercontent.com/2207331/145347946-ccb0efdc-53b0-4a4b-a3c6-68933227073e.png)

Nicolas
