### ISSUE TITLE
Water Temperature gauge fluctuation

### ISSUE THREAD

**Issue by Rukibb** [SHWotever/SimHub#984]
hi

Recently I added a Defi boost gauge and a Defi water temperature gauge.
The pointer of the water temp. gauge always fluctuates, both in game and not in game.
When not in game, I need to set the value a bit lower than the bottom value to avoid fluctuation and annoying motor sound.
In game, the higher temp. value sometimes give a stable pointing, below 70 degrees always fluctuate.
When the computer turned off, the water temp gauge pointing 60 degrees very stable. 

thanks

 
 
[1EBD0E34-962A-41E2-A01F-FF4D0C5C110A-15394-000007CB8B171D8E.zip](https://github.com/SHWotever/SimHub/files/7683419/1EBD0E34-962A-41E2-A01F-FF4D0C5C110A-15394-000007CB8B171D8E.zip)

**Comment by SHWotever** [comment]
Hi ! I'm sorry the water gauge is deprecated. 
You can read more informations about it in the documentation : https://github.com/SHWotever/SimHub/wiki/BMW-E36-Cluster-Setup#update-2020-05-20
