### ISSUE TITLE
[Feature request] - ACC 1.8 Additons

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#985]
**Is your feature request related to a problem? Please describe.**

Hi, I recently checked out the 1.8 update of ACC and they added a new car.
The BMW m4 GT3 🤮 💤 

They also changed the BB offset of the cup car.

Here I have updated their respective BB lookup tables:
[AssettoCorsaCompetizione.BrakeBias.bmw_m4_gt3.csv](https://github.com/SHWotever/SimHub/files/7683393/AssettoCorsaCompetizione.BrakeBias.bmw_m4_gt3.csv)
[AssettoCorsaCompetizione.BrakeBias.porsche_991ii_gt3_cup.csv](https://github.com/SHWotever/SimHub/files/7683395/AssettoCorsaCompetizione.BrakeBias.porsche_991ii_gt3_cup.csv)

And they made 4 additions the available data
In SPageFileGraphic:
![image](https://user-images.githubusercontent.com/50543913/145360977-cb054a36-90ea-45bd-83a3-53619b5aadfc.png)

SPageFileStatic
![image](https://user-images.githubusercontent.com/50543913/145361085-443a1a77-71e6-462c-9d3b-7ef611a152dc.png)

[ACCSharedMemoryDocumentationV1.8.pdf](https://github.com/SHWotever/SimHub/files/7683411/ACCSharedMemoryDocumentationV1.8.pdf)

Bonne journée!

**Comment by Romainrob** [comment]
Hi,
I just noticed the tires names are already available in the prop list.
I must have missed it.

**Comment by SHWotever** [comment]
No problems ;) The gaps weren't ;) I added them this morning !

Thanks for the bias files ! When the car was released I tough about it then totally forgot :(

**Comment by Romainrob** [comment]
Sweet!  Thanks you! 
The gaps are the most interesting of the two to me.
Bon week-end!

**Comment by Romainrob** [comment]
Salut,
J'espère que tu passes de bonnes fêtes.

L'offset de la Super Trofeo est également manquant. C'est -14.
Voici la table:
[AssettoCorsaCompetizione.BrakeBias.lamborghini_huracan_st.csv](https://github.com/SHWotever/SimHub/files/7790209/AssettoCorsaCompetizione.BrakeBias.lamborghini_huracan_st.csv)

Merci encore pour cette année pleine maj, aide, support et bonne humeur. 🥇 
Bonne soirée!

**Comment by KaiSforza** [comment]
> ACCSharedMemoryDocumentationV1.8.pdf

Completely unrelated, but where does this pdf come from?

**Comment by Romainrob** [comment]
Hi, it comes from here:
https://www.assettocorsa.net/forum/index.php?threads/acc-shared-memory-documentation.59965/

**Comment by Romainrob** [comment]
Hi,
Thanks for the new gapAhead/Behind properties.
At first they seemed broken to me while testing in a practice session.
It turns out these are not relative gaps, but gaps to the car ahead/behind in the standings.
These worked as intended in the race.

**Comment by SHWotever** [comment]
Perfect ! Thnaks for the feedback !
