### ISSUE TITLE
[Feature request] Add Support for MX1508 Motor Driver

### ISSUE THREAD

**Issue by SlowLogicBoy** [SHWotever/SimHub#988]
MX1508 is a cheap Motor Driver, and I'd like to add support for it in SimHub.

I already made modifications to Arduino Code that integrates with SimHub Arduino setup, I just don't know where I could make a PR for it so you could review it if my modifications are good enough.

I basically ripped of L298N, and made some modifications, I just have one question about passed value to it, what is the range of that :)

**Comment by SHWotever** [comment]
Hi ! Unfortunately 1.5Amps is a little too low, I marked as deprecatred the DK Motor shield a few years ago for the exact same reason (too weak, it was easily frying). The potential for this chip would be really limited.
