### ISSUE TITLE
Huge performance hit with arduino.

### ISSUE THREAD

**Issue by MADAL1EN** [SHWotever/SimHub#989]
**Describe the bug**
Random performance hits when I have multiple arduinos selected in my hardware while only having one connected.

**Simhub version**
7.4.14

**To Reproduce**
1. Play forza horizon 5
2. Have simhub running and connected to an arduino
3. Select multiple arduinos in my hardware tab
3. Huge fps drops happen every 30 seconds or so.

**Expected behavior**
Maybe a notification or something warning that only 1 is connected and multiple are selected.

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/7724725/SimHub.log)

**Comment by SHWotever** [comment]
Hi !

I did not had any simar reports since, I feel like this was more a usb devices specific issue.
