### ISSUE TITLE
Simhub freezing with AMs2

### ISSUE THREAD

**Issue by Duffyc87** [SHWotever/SimHub#990]
**Describe the bug**
Simhub freezes regularly while playing AMS2. Spend more time frozen than working. I use it exclusively for the overlay feature.
It worked for a few months at first but has been freezing now for quite a while.
Have tried a full reinstall.

**Simhub version**
7.4.16

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

[SimHub.log](https://github.com/SHWotever/SimHub/files/7740008/SimHub.log)

**Comment by SHWotever** [comment]
Hi !

Thnaks the log,

This looks really weird, the "watchdog" is indeed catching those freezes but does not shows any particular code being stuck. That would make me think about some features like "windows game mode" capable of totally freezing external processes. 

Could you check if game mode is enabled, and if so try to disable it ?
If that does not help, could you disable the simhub plugins one by one to check if somehow on of those are guilty ?
