### ISSUE TITLE
[Feature request] can i use adafruit shield v2 and a stepper moto as fan 

### ISSUE THREAD

**Issue by video000** [SHWotever/SimHub#991]
now ，arduino with adafruit shield v2 can surport pwm fan，but canvi use  stepper moto instead of dc fan？how to do that ？

**Comment by SHWotever** [comment]
Hi ! No, steppers are not supported by simhub/shakeit.

Nicolas

**Comment by video000** [comment]
can i do something to support it？coding or what？

**Comment by SHWotever** [comment]
If you are familiar with arduino you can edit the sketch : C:\Program Files (x86)\SimHub\_Addons\Arduino\DisplayClientV2\

The file supporting the Motor shield V2 is this one : SHShakeitAdaMotorShieldV2.h
