### ISSUE TITLE
Q: Can a plugin code emulate buttons/keys press, and be triggered by a button?

### ISSUE THREAD

**Issue by andkirby** [SHWotever/SimHub#993]
**Is your feature request related to a problem? Please describe.**
I need to have a chain:
1. On event, a one of buttons press (on a shifter in my case)
2. SimHub would trigger a plugin with custom code (I need to know which button pressed there)
3. this plugin performs business logic and emulate keyboard key/s or buttons press

**Describe the solution you'd like**
It's a bit unclear how to trigger a plugin code on button press. But seems its possible.
And no idea how to emulate programmatically buttons/keys press. Shall I use that "shall" folder?

**Describe alternatives you've considered**
Possibly, it can be covered by shell scripts, but [this page says](https://github.com/SHWotever/SimHub/wiki/Additional-Plugin--Shell-Plugin) not much.

**Additional context**
Currently, messing up with gear shifting in AC, within a plugin I need to have telemetry values about max gears and current gear.

**Comment by SHWotever** [comment]
Hi ! 

To create an action from a plugin you need this (you will find examples in the plugin SDK) :
```
   pluginManager.AddAction("DecrementSpeedWarning", this.GetType(), (a, b) =>
            {
                Settings.SpeedWarningLevel--;
            });
```

Once declared you will be able to map the action to any simhub supported input using the action :
![image](https://user-images.githubusercontent.com/2207331/147286579-6717f9ad-951c-41e3-a7ab-c15640161a5a.png)

Currently there is no "keyboard emulation" framework available from a plugin, it will be up to you to choose the one you prefer (AHK, Inputmanager... there are plenty).

Nicolas

**Comment by andkirby** [comment]
Hi @SHWotever 

Yes, that's good solution. I do have issues with calling AHK. I use it a lot, and in scripts I do call a key down-press.
```
Send, {1 Down}
```
When I trigger it, it shows the script in running, but nothing happened to keys. If I run scripts directly — it works.
Could you please mention other alternatives?
