### ISSUE TITLE
[Feature request] A three color layout of the individual racetrack sectors in the live map would be great. Thanks a lot 

### ISSUE THREAD

**Issue by Weini1972** [SHWotever/SimHub#996]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SHWotever** [comment]
I thanks for your suggestion, 
I close this one as it's a suplicate of an existing one
https://github.com/SHWotever/SimHub/issues/795
