### ISSUE TITLE
HT16k33 Matrix with Arduino Pro Micro?

### ISSUE THREAD

**Issue by ploebb** [SHWotever/SimHub#997]
**Describe the bug**
The "HT16k33 Single Color Matrix" and "HT16k33 Bi Color Matrix" seems to be supported on the Arduino Leonardo but not on the Pro Micro

**Simhub version**
7.4.16

**To Reproduce**
1. Go to Arduino -> My Hardware -> Open Setup Tool
2. Select Arduino Pro Micro (ATMega32u4)
3. Add "HT16k33 Single Color Matrix" or "HT16k33 Bi Color Matrix"
4. No pin shows up on the Wiring diagram

**Expected behavior**
The label "HT16k33 Matrix DAT" and "CLK" should show up on Pins A0 (18) and A1 (19) respectively like on the Arduino Leonardo

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5870131/147925621-c34310d3-ba5d-4bcd-a6b9-869a5bdeec69.png)
![grafik](https://user-images.githubusercontent.com/5870131/147925591-32cc98c3-2526-44d0-8f57-17c5446f2e7e.png)

**Log files**
No relevant info in the Logs I suspect (no errors - I checked) but I can post them, if necessary

I assume the Pro Micro and the Leonardo should be compatible in this case plus the pins 18 and 19 are available on the board. Or do I miss something?

Will it work, if I select the Leonardo but flash the sketch to the Pro Micro? I did not purchase anything yet so I can't try.

**Comment by SHWotever** [comment]
Hi indeed, leonardo and pro micro are just a different form factor of the same board, I've fixed the schematics labels for the next version.

Nicolas
