### ISSUE TITLE
Can't control multiple HDMI dashboards with "Next Dash Screen" mapping

### ISSUE THREAD

**Issue by gmarch** [SHWotever/SimHub#999]
I have two additional monitors, with two dashboards running on them. One is an overhead monitor on my triple setup where I run Romainrob's Universal Dash to get some data that is not on most dashboards, and a 7" HDMI monitor mounted on my DD2 to recreate the car's actual dash.

I have the "show next dash screen" control set. The problem is it changes both dashboards at the same time.

How can I set controls for each dash separately?

Note: These are HDMI monitors, not USB or VOCORE, etc.

I should also note that in the dash settings page, the per device controls had a bunch of old "web" entries which I "forgot". It now has nothing in it, and doesn't seem to populate. Does this have anything to do with individual dash settings?

**Comment by SHWotever** [comment]
Hi ! I close this, this has been made available and much more in the V9 release.

Best regards,
Nicolas
